### ISSUE TITLE
Text layer is not directly on top of canvas

### ISSUE THREAD

**Issue by admehta01** [wojtekmaj/react-pdf#100]
Use [this PDF](http://www.auburn.edu/allynbaconanthology/documents/EchoNarcissus.pdf) and highlight some text halfway down the first page.
You'll notice the highlight is a bit off from the actual text. Happens in the demo as well.

Chrome 62, Windows 10. Using react-pdf v2.2.0.

**Comment by wojtekmaj** [comment]
Hey @admehta01,
thank you for this example!
Rendering text content accurately is super hard. The more examples the better, as this helps me fine tune some settings that create text selection where it should be. Although Mozilla tried and surrendered - their selection is simply a rectangle, and behind this rectangle is usually severely misaligned text in Times New Roman.
So, I'll try my best to figure out if we can make this selection better in your case, but I can't promise you anything... :(
Thanks for understanding!
Wojciech

**Comment by wojtekmaj** [comment]
Ah, one more thing - SVG rendering #55 is a VERY promising stuff that will actually one day replace text layers once for all!

**Comment by wojtekmaj** [comment]
Hey @admehta01,

I'm super excited to announce that in v2.3.0 experimental support for SVG rendering was [added](https://github.com/wojtekmaj/react-pdf/releases/tag/v2.3.0)]. As I said, it is experimental, but if the PDFs you want to display are not *super* fancy, you might want to try it out!

Why? Because SVG rendering gets rid of text layers altogether :)

**Comment by admehta01** [comment]
Awesome, thanks for the quick turnaround! But we embed `<span>`s inside the text layer `<div>`s based on character count from top of document, and it looks like that won't work if we switch to `<svg>`. SVG rendering does look pretty sweet though.

**Comment by wojtekmaj** [comment]
Uh, that's too bad! I hope that <svg>s will suit you with some more research, since as I look on what Mozilla is doing, the switch is inevitable someday!

I found a solution for you though! If you only can accept custom color of selection, you can do:

```css
.ReactPDF__Page__textContent div {
    opacity: 0.5;
}

.ReactPDF__Page__textContent div::selection {
    background-color: blue;
}
```

and this will entirely hide the text rendered in text layer!

Here's how it looks:

![obraz](https://user-images.githubusercontent.com/5426427/32926011-22c277b8-cb45-11e7-92ea-60b8b8ae8c51.png)

**Comment by admehta01** [comment]
Sorry was out of town, but just checked out your solution. Looks pretty good...thanks!

**Comment by admehta01** [comment]
Hmm, upon testing of more PDFs, it seems it's very off in some cases whereas Mozilla PDF js is perfectly aligned.
Here are some of the test docs I am using: [PDF1](http://www.pelister.org/literature/ArthurMiller/Miller_Salesman.pdf) [PDF2](http://obryant.us/Websites/OBryant/images/Chapter3.pdf) [PDF3](https://github.com/wojtekmaj/react-pdf/files/1570901/8f2d09f690e94926ba5707b8f261499d.pdf) [PDF4](https://github.com/wojtekmaj/react-pdf/files/1570907/1e09979691d343e3a73bc68d18d88701.pdf)

Any ideas?

**Comment by nurtureJamesTan** [comment]
hey! i found the problem, i will do a merge request soon
it because u r scaleX is calculated based on a scaled version.
it needs to be reset before calculating

**Comment by nurtureJamesTan** [comment]
hi,

here is the fix, please help to test if it works on your browser
https://github.com/wojtekmaj/react-pdf/pull/121

**Comment by admehta01** [comment]
This will move it up a little bit, but not resolve the cases where it is very off.
See the PDFs in my comment 3 days ago.

**Comment by admehta01** [comment]
I noticed the `viewport.viewBox` coming from Mozilla PDF.js was starting with non zero coordinates on these PDFs.

Adding this code to `PageTextContent.jsx` in `renderTextItem()` worked:

```
const { unrotatedViewport: viewport } = this;
left -= viewport.viewBox[0];
baselineBottom -= viewport.viewBox[1];
```

**Comment by wojtekmaj** [comment]
Hey @admehta01, thanks for looking into it! I'll try to merge it all nicely. Glad you provided these examples, too!

**Comment by wojtekmaj** [comment]
Fixed in 2.5.0. Let me know what you think!

**Comment by Abishek-Sudhakaran** [comment]
while zooming pdf the text breaks and looks blurred..please provide a solution to fix that

**Comment by wojtekmaj** [comment]
@Abishek-Sudhakaran You've got to make sure that PDF you're rendering fits in whatever container you prepared for it. Otherwise, browser will try to squish parts of the PDF. It will fail to do so with the page in its graphical form, of course, but not with the text layer.
