### ISSUE TITLE
Download PDF with filled forms

### ISSUE THREAD

**Issue by mimsou** [wojtekmaj/react-pdf#1002]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

Thanks for this amazing tool ,

It s nice to have Form rendered on Viewer , but can we have a way to download pdf after filling the forms ?
i think i already seen such a feature with PDF.js

Thanks again

**Comment by wojtekmaj** [comment]
Just tried that in Firefox's pdf.js and it looks like you can't save filled forms to disk. This means that, unfortunately, there's no way to do this in React-PDF at the moment as well.

**Comment by mrdaniellewis** [comment]
Firefox's pdf.js now appears to support this. I was able to fill in a PDF, save it and reopen it with the filled in details still present.

**Comment by sirdawidd** [comment]
PDF.ja have already such feature.
