### ISSUE TITLE
worker issue with Gatsby 4 / webpack 5

### ISSUE THREAD

**Issue by jakoblind** [wojtekmaj/react-pdf#1004]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I'm using Gatsby 4 (with webpack 5) and it works fine in develop mode. However in production mode (`gatsby build; gatsby serve`) I get the following error in the console:

```
GET http://localhost:9001/[object%20Object] 404 (Not Found)
```

The PDF fails to render and instead I get an error message `Failed to load PDF file.`

### Steps to reproduce

1. clone https://github.com/jakoblind/gatsby-react-pdf-bug-repro
2. npm install
3. npx gatsby build
4. npx gatsby serve
5. go to http://localhost:9000/
6. Se error as described above.

### Expected behavior

To se a rendered PDF

### Actual behavior

The PDF fails to render and instead I get an error message `Failed to load PDF file.`

### Environment

- **React-PDF version**: 5.7.2
- **React version**: 17.0.1
- **Webpack version (if applicable)**: 5

**Comment by alanpilloud** [comment]
Hi @jakoblind, 

I solved the same issue by loading the worker this way:

```
import { pdfjs } from "react-pdf"
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`
```

I found these instructions here even though it is not related to webpack: https://github.com/wojtekmaj/react-pdf#standard-browserify-esbuild-and-others

It worked with `gatsby serve` and on Netlify.

Hope it solves your issue.

**Comment by jakoblind** [comment]
Hi @alanpilloud 

Unfortunately, this solution doesn't work for me. The library must be self-hosted. I have another workable solution where I copy the `pdf.worker.min.js` file with `CopyWebpackPlugin` and use that. But it would be nice to get it to work without this "hack"

**Comment by egemenu** [comment]
@jakoblind Thanks for help, this works like a charm! Actually alanpilloud's solution worked for me but this approach would make more sense in my situation.

**Comment by richcsmith** [comment]
The solution above by @jakoblind worked like a charm, thank you.

I ran into this issue today after updating all of my packages to their latest versions. I am now using create-react-app (v5, which uses webpack 5), and the legacy way of setting the `workerSrc` did not work for me since it changed the output directory of the compiled worker file, which my app does not have access to (which resulted in 403 errors when attempting to access the file in prod). Sharing in case it helps someone else.
