### ISSUE TITLE
Canvas secondary pages block other HTML elements on screen

### ISSUE THREAD

**Issue by gravitymedianet** [wojtekmaj/react-pdf#1005]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When I use the PDF components in a modal dialog, I have a button on the screen that gets covered by secondary pages of the PDF.

It looks like the text or canvas content leaks all over the HTML element even though it is not visible. If you click and drag the mouse over the PDF canvas as if selecting text, it reveals invisible text from the PDF document.

This gets in the way of clicking links and buttons

### Steps to reproduce

Using bootstrap, create a modal dialog, follow the documentation you give on how to add a PDF component.

Add a button above the PDF. The button is unclickable.

### Expected behavior

It should not cover other HTML elements

### Actual behavior

Other elements above the PDF in landscape mode are covered and unclickable

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Sounds like you need a container that would prevent overflow from happening in case React-PDF rendered content does not fit.
