### ISSUE TITLE
SVG mode changed my pdf original colours

### ISSUE THREAD

**Issue by richarepo** [wojtekmaj/react-pdf#1006]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

![image](https://user-images.githubusercontent.com/25027633/170475408-679063f7-fe2f-48a3-9bce-32b2edd4dee8.png)

My original pdf is this and after i render using react pdf using svg mode he changed pdf background colours.

![Uploading image.png…]()

### Steps to reproduce

I am using just svg in react-pdf for a rendering my pdf.

### Expected behavior

![image](https://user-images.githubusercontent.com/25027633/170475658-8f04f64a-56d3-4f52-a938-10a964ecb25d.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/25027633/170475696-a6b9d6aa-a7cf-4999-b37a-40368e8fc1c7.png)

### Environment

- **Chrome, Safari**:
- **4.1.0**:
- **17.0.2**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
It looks like this issue is directly connected to pdf.js behavior. Please [raise an issue there](https://github.com/mozilla/pdf.js/issues/new). Keep in mind Mozilla considers SVG rendering mode experimental and they may not look into it anyway.
