### ISSUE TITLE
The SVG render method doesn't render text on its expected position

### ISSUE THREAD

**Issue by PavelRybalko** [wojtekmaj/react-pdf#1008]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The svg render method isn't rendered text on his actual position in template

### Steps to reproduce

add to react component this:
   pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

and this:
  <Document renderMode="svg" file={someBase64file}>
          <Page />
        </Document>

### Expected behavior

[merge params test1.pdf](https://github.com/wojtekmaj/react-pdf/files/8785670/merge.params.test1.pdf)
![image](https://user-images.githubusercontent.com/60709039/170675865-0c5d23ae-72e2-457b-94a2-de1a3252d40e.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/60709039/170675984-8040a1f6-8f6b-40a0-843d-9cca0dced958.png)

### Environment

- **Browser**: Chrome  101.0.4951.67 (Official Build) (64-bit)
- **React-PDF version**: 5.7.2
- **React version**: 17.0.1
- **Webpack version (if applicable)**: 5.50.0

**Comment by wojtekmaj** [comment]
It looks like this issue is directly connected to pdf.js behavior. Please [raise an issue there](https://github.com/mozilla/pdf.js/issues/new).
