### ISSUE TITLE
Expose the http response headers in the onLoadSuccess callback

### ISSUE THREAD

**Issue by pellec** [wojtekmaj/react-pdf#1009]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

In the onLoadSuccess callback when a document is loaded, it would be great to be able to inspect the http headers coming back from the request in the http response. 

### Proposed solution

Extend the PDFDocumentProxy object to also include http response headers.
![image](https://user-images.githubusercontent.com/1078388/171865799-25fc7d21-795d-42b2-a479-00e1f68305b1.png)

**Comment by wojtekmaj** [comment]
Unfortunately all we get from pdfjs.getDocument promise is a [PDFDocumentProxy object](https://mozilla.github.io/pdf.js/api/draft/module-pdfjsLib-PDFDocumentProxy.html), which is passed to `onLoadSuccess`. Wish I could pass more info for you, but I can't.
