### ISSUE TITLE
'alt' prop not included in Image component

### ISSUE THREAD

**Issue by Bohemus307** [wojtekmaj/react-pdf#1014]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Currently using React-pdf with Next.JS and typescript and ran into a TS error:
 ```
Type error: No overload matches this call.
                                    Overload 1 of 2, '(props: ImageProps | Readonly<ImageProps>): Image', gave the following error.
                                    Type '{ style: { width: string; marginBottom: number; }; src: string; alt: string; }' is not assignable to type 'IntrinsicAttributes & (IntrinsicClassAttributes<Image> & (Readonly<ImageProps> & Readonly<{ children?: ReactNode; }>))'.
                                    Property 'alt' does not exist on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Image> & (Readonly<ImageProps> & Readonly<{ children?: ReactNode; }>))'.
                                    Overload 2 of 2, '(props: ImageProps, context: any): Image', gave the following error.
                                    Type '{ style: { width: string; marginBottom: number; }; src: string; alt: string; }' is not assignable to type 'IntrinsicAttributes & (IntrinsicClassAttributes<Image> & (Readonly<ImageProps> & Readonly<{ children?: ReactNode; }>))'.
                                    Property 'alt' does not exist on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Image> & (Readonly<ImageProps> & Readonly<{ children?: ReactNode; }>))'.
```

if i add this in node modules locally to `imageprops` it works great but of course not during the deployment build. I could pull current repo and add this as a contributor but for something so small i felt this approach was appropriate. Let me know if im mistaken in any way and thanks for your time on a great library!!

### Steps to reproduce

create Image component in TS app and add alt prop

### Expected behavior

alt prop should be available to image component

### Actual behavior

TS error saying it is not present on the Image components props which is true!

### Environment

- **Browser (if applicable)**:
- **2.2.0**:
- **17.0.2**:
- **5**:

**Comment by wojtekmaj** [comment]
Wrong repo
