### ISSUE TITLE
Images and text are not crisp when compared to PDF link

### ISSUE THREAD

**Issue by tejaswibharadwajp** [wojtekmaj/react-pdf#1015]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi Team, I am having the below issuw while loading a PDF using react-pdf,  have chnaged the renderMode and scale but no luck, can anyone help on this, thanks in advance!

### Steps to reproduce

using react pdf

### Expected behavior

Below is the pdf
![direct_pdf](https://user-images.githubusercontent.com/16951332/174392396-8a7879e1-b9b1-4cd2-95fa-aaa50b3b4599.png)

### Actual behavior

Below image is from React PDF
![react_pdf](https://user-images.githubusercontent.com/16951332/174392329-c5489de0-cee9-4aac-bc20-9dceaf5938c9.png)

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Can you make a repro in CodeSandbox or something similar?
