### ISSUE TITLE
URIError: URI malformed at decodeURIComponent and missing TextLayer.css

### ISSUE THREAD

**Issue by mynameisankit** [wojtekmaj/react-pdf#1022]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

**Tech Stack**: Next.js

Hi Team, I am not able to import the CSS files ``AnnotationLayer.css`` and ``TextLayer.css``. I think that the AnnotationLayer.css import error is related to Next.js but I don't understand why TextLayer.css is missing. 

Link to Relevant Files and Repository - 
- https://github.com/mynameisankit/portfolio-v2
- https://github.com/mynameisankit/portfolio-v2/tree/main/components/common/PdfViewer

### Steps to reproduce

1. Do the following imports:-
   - ``import 'react-pdf/dist/esm/Page/AnnotationLayer.css'``;
   - ``import 'react-pdf/dist/esm/Page/TextLayer.css'``;

Only if the project is cloned:-
2. Uncomment the import lines for the CSS files in ``components/common/PdfViewer/pdf-viewer.jsx``
4.  Goto ``localhost:3000/resume``

### Expected behavior

I should be able to import the CSS files normally

### Actual behavior

I am not able to import the CSS files as shown in the screenshots below.

### Additional information

1. When I add ``AnnotationLayer.css`` import
![image](https://user-images.githubusercontent.com/53820439/177143176-5a0a3f11-02ef-41c5-a222-7f56b6e68f6d.png)
![image](https://user-images.githubusercontent.com/53820439/177143461-2ca6950a-a3cd-4492-be59-97ead26773f2.png)

2. When I add `TextLayer.css` import
![image](https://user-images.githubusercontent.com/53820439/177143268-d6fa7a28-4327-4ee6-ac90-d84fdab9e6a4.png)
![image](https://user-images.githubusercontent.com/53820439/177144517-4b0bf0f9-7024-4f97-a8e4-2b2510457f93.png)

3. After removing the import for the CSS files and adding the following props, everything renders properly.
![image](https://user-images.githubusercontent.com/53820439/177143031-5d13fbfa-53c4-4f82-bc56-307b98b239df.png)

### Environment

- **Browser (if applicable)**: Chrome Version 103.0.5060.66
- **React-PDF version**: ^5.7.2
- **React version**: 17.0.2
- **Webpack version (if applicable)**: 5
- **Next.js version**: 12.0.4

**Comment by PezCoder** [comment]
For people facing this issue, if you're using webpack with next.js.. This fixed the issue for me:
https://github.com/vercel/next.js/issues/30721#issuecomment-1015722604

**Comment by tactycadmin** [comment]
Also running into this issue here. Any updates?

**Comment by gnhbuchanan** [comment]
I'm having the same issue. Any updates? Has anyone been able to bypass this error?
