### ISSUE TITLE
CustomTextRenderer allocating text to wrong text layer children

### ISSUE THREAD

**Issue by JGarnettMtab** [wojtekmaj/react-pdf#1042]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Using `customTextRenderer` to highlight search results. Results are found, but for the Page the number of text layer child elements is not equal to `textContent.items` and so the result of of the customTextRenderer is allocated to the wrong child node of the layerElement ref.

### Steps to reproduce

PDF: https://impact.disney.com/app/uploads/2022/02/2021-CSR-Report.pdf

Page 21 (probably there are many other examples)

customTextRenderer: 
```javascript
function highlightPattern(text) {
  const splitText = text.split('social');

  if (splitText.length <= 1) {
    return text;
  }

  const matches = text.match(pattern);

  return splitText.reduce((arr, element, index) => (matches[index] ? [
    ...arr,
    element,
    <mark key={index}>
      {matches[index]}
    </mark>,
  ] : [...arr, element]), []);
}
```

### Expected behavior

![image](https://user-images.githubusercontent.com/35131716/186870719-a6916eb9-b132-4506-9a41-c7bd22bbc072.png)

### Actual behavior

Search term: 'social'

![image](https://user-images.githubusercontent.com/35131716/186870488-294c524b-7cc9-4db8-a288-6a3b2f21a1ca.png)

### Additional information

Looking at the DOM content has been allocated to the br nodes when it shouldnt have been 
![image](https://user-images.githubusercontent.com/35131716/186871194-b80f6f0a-f23e-4c65-85de-4a1c8aba38e8.png)

I have worked around this issue by extending parameters passed to `pdfjs.renderTextLayer` to be 
``` javascript
    const textDivs = [];
    const parameters = {
      container: this.layerElement.current,
      enhanceTextSelection,
      textContent,
      textDivs,
      viewport
    };
```
    
And then used the following when handling the customTextRenderer.  In the renderTextLayer textDivs gets populated with the appropriate elements in an array that matches with the textItems

```javascript
      textDivs.forEach((element, elementIndex) => {
        const reactContent = customTextRenderer({
          itemIndex: elementIndex,
          ...textContent.items[elementIndex]
        });
        element.innerHTML = renderToStaticMarkup(reactContent);
      });
```

### Environment

- **Browser (if applicable)**: any
- **React-PDF version**: 6.0.0-beta.3
- **React version**: 17.0.2
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
I believe this has long been resolved and thus can be closed.
