### ISSUE TITLE
build error: cant's resolve 'canvas' in '...\.pnpm\...\build' when use pnpm

### ISSUE THREAD

**Issue by zeffon** [wojtekmaj/react-pdf#1045]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I build my project(webpack 5) get an error when using react-pdf of v5.7.2.

```
Module not found: Error: Can't resolve 'canvas' in 'C:\Users\Zeffon\Desktop\app\english\node_modules\.pnpm\pdfjs-dist@2.9.359\node_modules\pdfjs-dist\legacy\build'
```
But It can run normally and It's just an error when build. I tired to use different verision,  but it failed. I tired to install react-pdf of came version pdfjs-dist. But it failed too. So I am wondering if it's because I use 'pnpm'.
And what should i do?

### Steps to reproduce

1. install deps
```
"react-pdf": "^5.7.2"
"pdfjs-dist": "^2.12.313",
```

2. config
```
import path from 'path'
import CopyWebpackPlugin from 'copy-webpack-plugin'
// eslint-disable-next-line no-restricted-globals
const cMapsDir = path.join(path.dirname(require.resolve('pdfjs-dist/package.json')), 'cmaps')

module.exports = function (context, options) {
  return {
    name: 'custom-docusaurus-plugin',
    configureWebpack() {
      return {
        plugins: [
          new CopyWebpackPlugin({
            patterns: [{ from: cMapsDir, to: 'cmaps/' }]
          })
        ]
      }
    }
  }
}
```

3. use
```
import { Document, Page, pdfjs } from 'react-pdf/dist/esm/entry.webpack5'
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry'
pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker
```
```jsx
<Document
  file={file}
  onLoadSuccess={onDocumentLoadSuccess}
  options={options}
  renderMode="none"
>
  <Page pageNumber={pageNumber} width={size && size.width} renderMode="none" />
</Document>
```

### Expected behavior

build success

### Actual behavior

build fail

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
I believe your problem isn't as much about pnpm as about running React-PDF server-side, which makes no sense. You can't render canvas on the server.
