### ISSUE TITLE
Repeated "phantom" page at end of document in modal

### ISSUE THREAD

**Issue by mellodev** [wojtekmaj/react-pdf#1047]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

At the end of any PDF loaded, there is a "phantom" page showing, which is a repeat of an earlier page. react-pdf is being used inside of a react-bootstrap modal if that matters.

![image](https://user-images.githubusercontent.com/1292059/188016914-f0c82ac5-64f9-4d9a-a601-c184672552b1.png)

### Steps to reproduce

Load pdf in a modal, scroll down to bottom of pdf. After the last page, one of the earlier pages starts rendering again.

### Expected behavior

Should not see the phantom page

### Actual behavior

Seeing the top portion of an earlier page rendering

### Additional information

Latest version

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: 5.7.2
- **React version**: 17.0.2
- **Webpack version (if applicable)**: 5.66.0

**Comment by wojtekmaj** [comment]
This doesn't look like React-PDF issue, but to be sure, I'd have to have a look at a reproducible example/sample code.

**Comment by mellodev** [comment]
You were right, this ended up being on our end. The bootstrap modal containing react-pdf was being rendered twice to the page.
