### ISSUE TITLE
Pdf pages not load because of FontLoader

### ISSUE THREAD

**Issue by trannhutle** [wojtekmaj/react-pdf#1050]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When I load the pdf, the pages are not shown and it shows the exception under the console log!
![image](https://user-images.githubusercontent.com/14163032/189900677-406d1676-ede1-48cf-81d3-88d65f31e674.png)

Do you have any idea why is it causing the issues?
Thank you!

### Steps to reproduce

I am using pdf.worker.min.js from the cloudflare

![image](https://user-images.githubusercontent.com/14163032/189901269-7dfbd43a-1ff3-4c88-abd5-aa5ade4ecc5e.png)

### Expected behavior

The PDF is rendered

### Actual behavior

The PDF should show

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 5.6.0
- **React version**: 17
- **Webpack version (if applicable)**: 4

**Comment by wojtekmaj** [comment]
Your `workerSrc` URL isn't following what README suggests for version 5.6.0.
