### ISSUE TITLE
font is blurry in tablet sized iframe (width : 800px)

### ISSUE THREAD

**Issue by Glosign-Kemon** [wojtekmaj/react-pdf#1051]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

font is blurry in tablet sized iframe (width : 800px)
![스크린샷 2022-09-14 오후 1 54 12](https://user-images.githubusercontent.com/76672225/190063034-eea1113d-a3a3-41cc-9a44-2ea63f01a821.png)

font is fine in full screen
![스크린샷 2022-09-14 오후 1 57 48](https://user-images.githubusercontent.com/76672225/190063206-4c6be7f3-e64b-42c5-baee-1968d067c034.png)

why font is blurry in reponsive iframe ??

### Steps to reproduce

1. create pdf in iframe width under 1023px
2. see error

### Expected behavior

font is fine in tablet sized iframe

### Actual behavior

font is blurry in tablet sized iframe

### Additional information

plz... give me advice

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
I'm unable to reproduce that. Maybe your iframe forces the page to resize via CSS because you didn't specify `Page`'s component `width`, hence the blurring?

**Comment by Glosign-Kemon** [comment]
> I'm unable to reproduce that. Maybe your iframe forces the page to resize via CSS because you didn't specify `Page`'s component `width`, hence the blurring?

thx
