### ISSUE TITLE
Module not found: Error: Can't resolve 'buffer'

### ISSUE THREAD

**Issue by usfslk** [wojtekmaj/react-pdf#1057]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Import not working using

import { Document, Page, View, Text } from '@react-pdf/renderer';

```
Module not found: Error: Can't resolve 'buffer' in '/Users/master/Documents/Code/sharecv/sharecv-web/node_modules/base64-to-uint8array'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }

```

Also ReactPDF is not not found  when imported from '@react-pdf/renderer'

`export 'ReactPDF' (imported as 'ReactPDF') was not found in '@react-pdf/renderer' (possible exports: BlobProvider, Canvas, Circle, ClipPath, Defs, Document, Ellipse, Font, G, Image, Line, LinearGradient, Link, Note, PDFDownloadLink, PDFViewer, Page, Path, Polygon, Polyline, RadialGradient, Rect, Stop, StyleSheet, Svg, Text, TextInstance, Tspan, View, createRenderer, default, pdf, render, renderToFile, renderToStream, renderToString, usePDF, version)`

### Steps to reproduce

```
npm install @react-pdf/renderer --save

import { Document, Page, View, Text, ReactPDF } from '@react-pdf/renderer';

const MyDocument = () => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.section}>
                <Text>Section #1</Text>
            </View>
            <View style={styles.section}>
                <Text>Section #2</Text>
            </View>
        </Page>
    </Document>
);

    componentDidMount = () => {
        ReactPDF.render(<MyDocument />, `${__dirname}/example.pdf`);
    };

```

### Expected behavior

no error

### Actual behavior

error app crash

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.

**Comment by adnanHussain07** [comment]
In my react-app there isnt any file name webpack.config.js so here is how I resolved my problem:

1- First, install the buffer package:

**"npm install buffer"**

2- Create a file named at the root of your project.

**react-app-rewired.config.js**

3- Add the following code to the file:

```
const webpack = require('webpack');
module.exports = {
  webpack: (config, { isServer }) => {
    // Add fallback for 'buffer' module
    if (!isServer) {
      config.resolve.fallback = {
        buffer: require.resolve('buffer'),
      };
    }

    return config;
  },
};
```
