### ISSUE TITLE
Annotations not rendering on 5.7.2 (works on 5.6.0)

### ISSUE THREAD

**Issue by preciselywilliam** [wojtekmaj/react-pdf#1058]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

This is what `onGetAnnotationsSuccess` returns on 5.6.0:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/33222967/193232477-50665054-6ced-42dd-b927-f9c37a69b367.png">

This is what `onGetAnnotationsSuccess` returns on 5.7.2:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/33222967/193233154-5f37111e-888e-4ab0-94fa-ca13fce8ad3d.png">

`<Document />` is rendered as such:
```
        <Document
          file={fileUrl}
          size={A4}
          onLoadSuccess={handleDocumentLoadSuccess}
          onLoadError={onError}
          loading={<Loader />}
        >
          // render pages
        </Document>
```

Each `<Page />` is rendered as such:
```
              <Page
                key={index}
                pageIndex={index}
                width={DOCUMENT_WIDTH}
                renderAnnotationLayer
                renderTextLayer
                loading={<Loader />}
                onGetAnnotationsSuccess={(data) => {
                  console.log('onGetAnnotationsSuccess data', data);
                  // handle annotation
                }}
              >
                // render annotations
              </Page>

```

`AnnotationLayer.css` is included as such:
`import 'react-pdf/dist/esm/Page/AnnotationLayer.css';`

`workerSrc` is set as such:
```pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;```

Using `"file-loader": "6.2.0"`, `"webpack": "4.42.0"` and `"react": "16.14.0"`

`v.5.7.0` is giving me warnings for `renderInteractiveForms`. Other than that I am receiving no warnings for any of the three `5.7.x` versions.

No annotations are rendered in `https://mozilla.github.io/pdf.js/web/viewer.html` when I test there.

### Steps to reproduce

Upload file with annotations using `5.7.2`

### Expected behavior

Annotations are rendered

### Actual behavior

Annotations are not rendered

### Environment

- **Browser (if applicable)**: Latest chrome
- **React-PDF version**: 5.7.2
- **React version**: 16.14.0
- **Webpack version (if applicable)**: 4.42.0

**Comment by wojtekmaj** [comment]
Would it be possible for you to create a CodeSandbox for me to look into?

**Comment by preciselywilliam** [comment]
> Would it be possible for you to create a CodeSandbox for me to look into?

I'm not really sure how to set that up with a file upload so that I can use the file I'm testing with. Is there anywhere I can use a tool similar to `https://mozilla.github.io/pdf.js/web/viewer.html` but for 5.6.0 to single out if it's a version problem or a problem with my environment?

**Comment by wojtekmaj** [comment]
You can upload a PDF for me to look into, too.
