### ISSUE TITLE
Logs showing "TT: undefined function:"

### ISSUE THREAD

**Issue by Secretmapper** [wojtekmaj/react-pdf#106]
Hello!

The library works splendidly, but for some reason I get a lot of 'TT: undefined function' logs in my console, which seems to be caused by pdfjs.

Is there any way to supress/remove these? It also happens even with the sample snippet.

<img width="603" alt="screen shot 2017-11-22 at 2 34 36 pm" src="https://user-images.githubusercontent.com/4077143/33113224-49dc4aee-cf92-11e7-8230-3b63a1bd7ab5.png">

**Comment by wojtekmaj** [comment]
Hey @Secretmapper,
there's no way to do it directly via setOptions - I'll keep that in mind.
For the moment, you can import PDFJS from pdfjs-dist (check the entry file you're using to get the right PDFJS path) and do the following:

```js
PDFJS.verbosity = PDFJS.VERBOSITY_LEVELS.errors;
```

This way, only errors will be shown.

**Comment by rootlinux2** [comment]
I'm using
` import { Document, Page, pdfjs } from 'react-pdf/dist/entry.webpack';`
When I try to do this 
`pdfjs.verbosity = pdfjs.VERBOSITY_LEVELS.errors;`

I'm facing this error
![image](https://user-images.githubusercontent.com/24574267/102508152-155fdf80-4053-11eb-8c6d-7538ece9ee42.png)

**Comment by wojtekmaj** [comment]
Yeah, they changed it over the last three years :D

Not checked if that works 100%, but you should be able to set it by something along the lines:

```js
pdfjs.setVerbosityLevel(pdfjs.VerbosityLevel.KEYGOESHERE)
```

where KEYGOESHERE may be as follows:

```js
{
  ERRORS: 0,
  WARNINGS: 1,
  INFOS: 5
};
```

**Comment by casulit** [comment]
> Yeah, they changed it over the last three years :D
> 
> Not checked if that works 100%, but you should be able to set it by something along the lines:
> 
> ```js
> pdfjs.setVerbosityLevel(pdfjs.VerbosityLevel.KEYGOESHERE)
> ```
> 
> where KEYGOESHERE may be as follows:
> 
> ```js
> {
>   ERRORS: 0,
>   WARNINGS: 1,
>   INFOS: 5
> };
> ```

Not working..

**Comment by jmcdl** [comment]
@casulit The option props of the react-pdf Document component can take any of the options specified [here](https://mozilla.github.io/pdf.js/api/draft/module-pdfjsLib.html#~DocumentInitParameters). I was able to use it successfully to set the console to only log errors like so:

```js

import { Document, Page, pdfjs } from "react-pdf/dist/esm/entry.webpack";

<Document
  file={pdf}
  onLoadSuccess={onDocumentLoadSuccess}
  options={{
    cMapPacked: true,
    cMapUrl: "cmaps/",
    verbosity: pdfjs.VerbosityLevel.ERRORS,
  }}
>
...
</>
```

@wojtekmaj I could ad a PR to update the docs if you want?

**Comment by wojtekmaj** [comment]
@jmcdl Sure! Please go ahead.

**Comment by samuliasmala** [comment]
The `Document` options don't allow `verbosity` anymore. Is there any other way to pass it to pdfjs?

For reference, the options type is

```ts
export type Options = {
    cMapPacked?: boolean | null;
    cMapUrl?: string | null;
    httpHeaders?: object | null;
    standardFontDataUrl?: string | null;
    withCredentials?: boolean | null;
};
```
