### ISSUE TITLE
Warning: Setting up fake worker. on network disconnect

### ISSUE THREAD

**Issue by MuthuChess** [wojtekmaj/react-pdf#1061]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

If there is a network disconnect, there is a warning in the console 

> Warning: Setting up fake worker.

We are trying to add a retry functionality suggested in #798 . We try to hit the retry button after the network is available. As the worker is disconnected rerender does not seem to work.

Pls suggest if there is a way to handle the worker when there is a network disconnect.

### Steps to reproduce

1. Assume Retry functionality is implemented as specified in #798 
2. Load the PDF
3. Toggle the developer tools network to offline
4. Switch to another PDF and it would display "Failed to load PDF" with Retry button
5. Toggle to **no throttling** option and click on retry button. 
6. The PDF does not rerender

### Expected behavior

Expecting the document to rerender

### Actual behavior

Display the error message and stays there as the worker is failed

### Environment

- **Browser (if applicable)**: Chrome 105.0.5195.128 
- **React-PDF version**: 5.7.2
- **React version**: 16.8.6
- **Webpack version (if applicable)**: CRA

**Comment by juzoace** [comment]
@MuthuChess @karthigenie have you found a solution @wojtekmaj ? Must there be an active internet connection for the pdf to render or is there a workaround for offline mode?
