### ISSUE TITLE
Page rendering delay on high resolution pages

### ISSUE THREAD

**Issue by MuthuChess** [wojtekmaj/react-pdf#1063]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

My PDF has some high resolution images where the page load is successful but takes few seconds to render the image on to the screen. Until then, there is a white blank page.

There is an attribute **loading** to show message while loading

It would be great if there is an **rendering** attribute to display a message when rendering in progress (between loading success and render success).

### Steps to reproduce

1. Open a PDF with high resolution images
2. The page render will be delayed and a blank screen is displayed

### Expected behavior

To provide an option to display some text so that the user is aware of something is happening

### Actual behavior

It just displays a blank screen where is user is not aware if something is happening or if it is a blank page

### Environment

- **Browser (if applicable)**: Chrome 105.0.5195.128
- **React-PDF version**: 5.7.2
- **React version**: 16.8.6
- **Webpack version (if applicable)**: CRA

**Comment by wojtekmaj** [comment]
There cannot be a rendering placeholder like we have for loading and error, because after the page is loaded, canvas is mounted for pdf.js to paint on. What you can do, however, is to place your own loader on top, and listen to onRenderSuccess to hide it.

**Comment by wojtekmaj** [comment]
See https://github.com/wojtekmaj/react-pdf/issues/1149#issuecomment-1323541137 for more info on how you can, at least to some extend, improve performance of rendering big PDFs on high resolution screens.
