### ISSUE TITLE
React-pdf >= v5.3 throws canvas.node error

### ISSUE THREAD

**Issue by pzoomin** [wojtekmaj/react-pdf#1064]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When trying to upgrade react-pdf to version 5.3.0 or above, I get the following error when building:

```
ERROR in ../node_modules/canvas/build/Release/canvas.node 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

This looks to be related to the underlying pdf.js dependency. Here's the same issue reported there:

https://github.com/mozilla/pdf.js/issues/13200

Since pdf.js comes in as a transitive dependency of react-pdf, though, I'm unable to try the suggest mitigations in that issue discussion.

## Build/environment info:

- React 17.0.1
- Node 16
- Webpack 5.74.0
- 

### Steps to reproduce

- Upgrade react-pdf from 5.1.0 to 5.2.0, it builds fine.
- Upgrade from 5.2.0 to 5.3.0, or any later version, and build fails as noted in issue description

### Expected behavior

webpack build should not fail due to upgrading react-pdf

### Actual behavior

webpack build fails if react-pdf upgraded to 5.3.0 or above.

### Environment

- **Browser (if applicable)**: N/A
- **React-PDF version**: 5.3.0
- **React version**: 17.0.1
- **Webpack version (if applicable)**: 5.5.74

Seeing error both when building locally on mac and in CI/CD where build happens on ubuntu (github actions)

**Comment by wojtekmaj** [comment]
You definitely should not be using React-PDF in server environment.

**Comment by Chocbanana** [comment]
I'm having this same issue, how do I prevent react-pdf from being used server side? I'm using the Gatsby framework

**Comment by wojtekmaj** [comment]
https://www.gatsbyjs.com/docs/using-client-side-only-packages/

**Comment by chaos-sl** [comment]
webpack config add
```
 {
      test: /\.node$/,
      use: {
        loader: "node-loader",
      },
 }
```
Don't forget to add node-loader with npm or yarn
