### ISSUE TITLE
Page Navigation PDF Rendered On Canvas

### ISSUE THREAD

**Issue by DekaAkademi** [wojtekmaj/react-pdf#1065]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I am loading a PDF by uploading. It is rendered on canvas. I'd like to use some cropping tools on it. On initial load it works but when I change the page, other pages were rendered below the canvas and page navigation works below side afterwards.

### Steps to reproduce

----

### Expected behavior

Pages should be rendered on canvas.

### Actual behavior

First page is rendered on canvas. When going other pages, they are rendered below the first page.

### Environment

- **Chrome**:
- **React-PDF version**:
- **React 18**:
- **Webpack version (if applicable)**:

**Comment by DekaAkademi** [comment]
After loading PDF, a canvas is created and the first page is shown. If a page navigation occurs, a new canvas is created below the previous one and pages during navigation are shown on the second canvas.

**Comment by wojtekmaj** [comment]
How is that a bug?

Anyways, here's a CodeSandbox that might help you out.

https://codesandbox.io/s/react-pdf-prevent-flash-se4r7s
