### ISSUE TITLE
fonts error with Edge and Oprea,How can I fix it?

### ISSUE THREAD

**Issue by znzaznz** [wojtekmaj/react-pdf#1066]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I meet an error when I use brower with Opera and Edge when I rendered with canvas，How can I fix it ?
![image](https://user-images.githubusercontent.com/39003442/196081995-c7c4bc5e-93f1-4a2b-9776-085a00b5bcc9.png)

### Steps to reproduce

none

### Expected behavior

none

### Actual behavior

none

### Environment

- **Browser (if applicable)**:Edge: 104.0.1293.63
- **React-PDF version**:5.7.2
- **React version**:18.2.0
- **Webpack version (if applicable)**:none

**Comment by robsco-git** [comment]
I have worked around this issue by disabling hardware acceleration in the browser's settings. Give it a go and see if that works for you. I think it may be related to a set of graphics cards/driver versions.

**Comment by wojtekmaj** [comment]
Is this reproducible in 6.0.0-beta.4?

**Comment by robsco-git** [comment]
> Is this reproducible in 6.0.0-beta.4?

I have had at least one report from a user using 6.0.0-beta.4.

**Comment by wojtekmaj** [comment]
Can I have a sample PDF to look at? It is very weird it's not happening in PDF.js demo!

**Comment by smitroshin** [comment]
Hi, I have the same issue.

You can find it on https://react-pdf.org/repl

![image](https://user-images.githubusercontent.com/20210690/202179919-81b6d3e4-54b3-4407-a045-4f2c6c0ffcaa.png)
![image](https://user-images.githubusercontent.com/20210690/202179967-18dd07ed-4303-477f-bb8c-8aaefb3513ca.png)

**Comment by smitroshin** [comment]
Seems like it's related to https://github.com/wojtekmaj/react-pdf/issues/1010

**Comment by DonikaV** [comment]
Any news? We have same issues in window machines.
