### ISSUE TITLE
canvasBackground missing in typescript types

### ISSUE THREAD

**Issue by paustint** [wojtekmaj/react-pdf#1068]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

canvasBackground is listed on the Readme as an available property, but it is int included in the Props for the Page component in the exported types.

### Steps to reproduce

use typesscript and include the tag `<Page canvasBackground="transparent" />`

### Expected behavior

no compile error

### Actual behavior

ts compile error

### Environment

- **Browser (if applicable)**: chrome
- **React-PDF version**: `"react-pdf": "^5.7.2",`
- **React version**: 17
- **Webpack version (if applicable)**: 4

**Comment by wojtekmaj** [comment]
Types are not maintained here, but on DefinitelyTyped. Please raise an issue there.
