### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by etorsuarezm** [wojtekmaj/react-pdf#107]
Hi, I've implemented react-pdf in a project with react starter kit (https://github.com/kriasoft/react-starter-kit/tree/feature/redux) and everything was working like a charm since last week. When compile the app I get this error...

```
....../app/node_modules/react-pdf/build/annotation_layer_builder.css:16
.annotationLayer section {
^
SyntaxError: Unexpected token .
```

Do you have any ideas ?

**Comment by etorsuarezm** [comment]
Closing this issue I installed css-loader, style-loader and then added 

```
require.extensions['.css'] = () => {
  return;
};
```

To webpack.config.js and also included css and style to loaders inside loaders section of webpack

```
{
      test: /\.css$/,  
      include: /node_modules/,  
      loaders: ['style-loader', 'css-loader'],
    }
```

**Comment by wojtekmaj** [comment]
Hey @etorsuarezm,
generally it's a good idea to exclude node_modules for js/jsx files only. Hardly ever allowing other files from node_modules through your webpack loaders is a bad idea; generally this shouldn't cause performance issues and can resolve some issues related to loading additional resources like CSS or images.
