### ISSUE TITLE
onLoadError occur 'TypeError: undefined is not an Object'

### ISSUE THREAD

**Issue by kaiwenxiao** [wojtekmaj/react-pdf#1104]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I just render the pdf using blob data, also try FileReader, It's a same issue.

### Steps to reproduce

Parent Component:
![6f5e226240acd0c0e98b9e66c8c7b17](https://user-images.githubusercontent.com/31737119/197116345-3b5b0f51-f295-4ca1-93db-71faa9ae9d11.jpg)

![1c27e49d90d1316535ba550e52fa11a](https://user-images.githubusercontent.com/31737119/197116331-653772a7-a5a1-43e3-92fe-3ee22156d84d.jpg)

Child Compnent:
![ad8f07034140bd61ba89bd8d0378f2f](https://user-images.githubusercontent.com/31737119/197116002-eccefb38-0de3-49b9-bd09-2d3665bdaf2c.jpg)

And raise an error 'TypeError: undefined is not an Object' in onLoadError Event, not in console panel. I using 5.x version of react-pdf
![15438e7b28512e89eda95e2a0a0431e](https://user-images.githubusercontent.com/31737119/197115978-dffe5323-8758-4b91-81da-0deb4ff38947.jpg)

Also, the console panel printout:
![41cffe42b9f1952f133f525ff0c0f22](https://user-images.githubusercontent.com/31737119/197115967-14dca51d-75c3-406d-9805-9688459abfa3.jpg)

Thanks!

### Expected behavior

correctly print it

### Actual behavior

get an error

### Environment

- **Browser (if applicable)**: Chrome 100+
- **React-PDF version**: 5.x
- **React version**: 16.8+
- **Webpack version (if applicable)**: 4.x

**Comment by wojtekmaj** [comment]
Might be related: https://github.com/wojtekmaj/react-pdf/issues/594

**Comment by Zummer** [comment]
i got this bug when i used

import 'core-js/stable';
import 'regenerator-runtime/runtime';

in my index.tsx
