### ISSUE TITLE
Text layer container isn't scrolling horizontally along with canvas

### ISSUE THREAD

**Issue by gladkovayuliya** [wojtekmaj/react-pdf#1118]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

In my app i have pdf previewer with scaling feature. To do that, i set the width of page to some value. At some point page doesn't fit in and the horizontal scroll shows up. The page looks normal, but the text layer does not, it's not scrolling with canvas, it stays pinned to the left.
There are couple of solutions i came up with: wrap Document in div with desired width or set overflow of text layer to inherit instead of hidden.

### Steps to reproduce

1.  Set page width bigger than width of document itself
2.  Select all text on the page
3.  Selection ends at some point, not at the real end of the page (horizontally)

### Expected behavior

Selection is scrolling along with canvas

### Actual behavior

Selection doesn't reach the end of the page

### Additional information

Sandbox example to illustrate the issue: https://codesandbox.io/s/react-pdf-textlayer-align-gzuncr?file=/src/index.jsx

### Environment

- **React-PDF version**: "6.0.0-beta.4"
- **React version**: "18.0.0"

**Comment by rabbanirizwan** [comment]
![6z8o50](https://user-images.githubusercontent.com/33807776/199528611-8afd1931-d916-4c31-9b46-04bdfcca497e.gif)
I have tried to reproduce this issue but I think it is working fine

**Comment by wojtekmaj** [comment]
Maybe it happens on some specific browser?

**Comment by gladkovayuliya** [comment]
@rabbanirizwan, but in your gif you are selecting only half of the text and cannot select another, how is it normal?

**Comment by wojtekmaj** [comment]
My bad. I now understand what's up :) Fixed.

**Comment by gladkovayuliya** [comment]
thank you!
