### ISSUE TITLE
Font-family not persisting

### ISSUE THREAD

**Issue by admehta01** [wojtekmaj/react-pdf#112]
Using [this PDF](http://www.auburn.edu/allynbaconanthology/documents/EchoNarcissus.pdf), I am rendering page by page and have prev/next buttons to change the page.

When the PDF first loads on page 1, the `ReactPDF__Page__textContent` divs have `font-family: g_d0_f1;`.
When I switch to page 2, the `font-family` changes to `serif`.
When I go back to page 1, the `font-family` is still `serif`, so the text layer is quite off.

Any ideas?

**Comment by wojtekmaj** [comment]
Hey @admehta01,
React-PDF is designed in such a way that it drops font-family declaration in case it looks horribly wrong for it (more than 10% difference to the rendered text on canvas). So I guess it might be it. However, some major adjustments have been made in version 2.5.0, so would you kindly recheck if that's still an issue for you?

**Comment by wojtekmaj** [comment]
Not reproducible in 3.x, so I'm closing it. In case it still needs a fix, let me know.
