### ISSUE TITLE
Images is getting squished if browser window zoom size is not 100%

### ISSUE THREAD

**Issue by hdupadhyay** [wojtekmaj/react-pdf#1120]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Images is getting squished if we produced PDF with browser window size is other than 100%. if we reset window size to 100% than it's working fine. 

Squished PDF
-------------------------
![image](https://user-images.githubusercontent.com/77604504/199423252-3e075f6b-393e-430c-bb77-7ec66e81965f.png)

PDF looks fine with 100% screen size
-------------------------
![image](https://user-images.githubusercontent.com/77604504/199423506-3a83d423-b3c9-413e-8c6c-450c92440884.png)

### Steps to reproduce

1. Open any browser window
2. Reset screen size with [command and - ] or [Cltr and  -]
3. Now generate PDF that contain images
4. check result

### Expected behavior

Image must not squished with any screen size.

### Actual behavior

Images are getting squished when screen size is other than 100%.

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
This is likely because you have a CSS rule that overwrites `width` (e.g. `max-width: 100%`) but not `height`. Add `height: auto` and you should be good to go.

WARNING: Resizing pages using CSS is a bad idea and will lead to misalignments of text & annotation layers.

**Comment by hdupadhyay** [comment]
No it's not like that, I'm not resizing page via CSS. 
I was talking about browser's window zoom-in and zoom-out that will make PDF images squished.
Please reopen this issue.

**Comment by wojtekmaj** [comment]
I'll need a reproducible example to have a look at what's going on. I think it has to be a CSS rule of some kind.
