### ISSUE TITLE
When using Server Side Rendering, an error message "ReferenceError: window is not defined" appears

### ISSUE THREAD

**Issue by Ilyomix** [wojtekmaj/react-pdf#113]
Hello,

Maybe I missed something but if someone can help me it will be great.
When I import `Document` and `Page` on my .jsx file, webpack crash on launch.
(cf: import { Document, Page } from 'react-pdf')

But when I remove the import, webpack launch without problem.

The fact is my project is running with server side rendering, and I think that the attribute window is not checked inside Document and Page component (cf : if typeof window !== 'undefined')

Thank you for listening my issue.

**Comment by wojtekmaj** [comment]
Hey,
would you please include an error stack if you have any?

**Comment by wojtekmaj** [comment]
Hey @Ilyomix,
do you still have this issue? If so, please share more details! I'd really like to get that fixed :)

**Comment by wojtekmaj** [comment]
Fixed in v2.5.1. Hopefully. ;)
Let me know in case I'm wrong.
Thanks!

**Comment by mskutle** [comment]
Hey @wojtekmaj, thanks for this great package :) I'm having this same issue with SSR on version 3.0.5, did you fix this in 2.5.1?

**Comment by wojtekmaj** [comment]
Hello, would you please give me the full error stack?

Also please mind that this library makes little sense on Server Side. Canvas has to be rendered on client side.

**Comment by mskutle** [comment]
UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at /usr/src/app/node_modules/pdfjs-dist/lib/web/ui_utils.js:391:3
    at new Promise (<anonymous>)
    at Object.<anonymous> (/usr/src/app/node_modules/pdfjs-dist/lib/web/ui_utils.js:390:24)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)

I have, however, circumvented the error by checking that the code is running in a browser before rendering the component.

**Comment by wojtekmaj** [comment]
Thank you - that's an issue on PDF.js side. I'd need to raise a pull request for them.

**Comment by wojtekmaj** [comment]
It's an issue on PDF.js side, but I see it has been fixed. Check out newest [v4.0.0-beta.3](https://github.com/wojtekmaj/react-pdf/releases/tag/v4.0.0-beta.3) - it should work!

**Comment by Ilyomix** [comment]
10 months later (I moved to Gitlab for work), thank you @wojtekmaj ;) !!
