### ISSUE TITLE
Received path to file not what was sent

### ISSUE THREAD

**Issue by leberjs** [wojtekmaj/react-pdf#114]
I have run into an interesting issue when trying to get this package to work.

This is the error I am receiving:

`ENOENT: no such file or directory, lstat 'D:\D:\Dev\electron-pdf-cms\dist\Dev\__TEST__\Menzner\TestData\V Groove Paneling\PDF\pdf-sample.pdf' UnknownErrorException {name: "UnknownErrorException", message: "ENOENT: no such file or directory, lstat 'D:\D:\De…er\TestData\V Groove Paneling\PDF\pdf-sample.pdf'", details: "UnknownErrorException: ENOENT: no such file or dir…er\TestData\V Groove Paneling\PDF\pdf-sample.pdf'"}`

Passing in both D:\Dev\electron-pdf-cms\dist\Dev\__TEST__\Menzner\TestData\V Groove Paneling\PDF\pdf-sample.pdf and \Dev\electron-pdf-cms\dist\Dev\__TEST__\Menzner\TestData\V Groove Paneling\PDF\pdf-sample.pdf results in the same issue.

It seems to be appending an extra D:/ to the file path no matter what I pass in.

**Comment by wojtekmaj** [comment]
Hey,
it's highly unlikely that the package would work on local file system. I suggest you using a simple webpack server for your development.

**Comment by leberjs** [comment]
I have been using the webpack dev server. 

This is an electron project. Are you saying this package will probably not work?

**Comment by wojtekmaj** [comment]
I'm just saying you generally should not use paths to files on the disk. On Chrome or Firefox or whatever, for security reasons it wouldn't be possible to load a file from the disk other than using file `<input>`.
