### ISSUE TITLE
Blank White Page while rendering PDF from a Base64 URL.

### ISSUE THREAD

**Issue by f0-x** [wojtekmaj/react-pdf#1144]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I've followed this [guide](https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions#how-do-i-load-a-pdf-from-base64), and supplied a valid base64, but my PDF doesn't render, just a white page with no errors at all.

### Steps to reproduce

1. Fetched a PDF from a REST API as a UTF-8 encoded string.
2. Converted the UTF-8 PDF String to base64 using a helper function below.
`export function getBase64FromUTF8(str: string | number | boolean) {
    return btoa(encodeURIComponent(str).replace(/%([0-9A-F]{2})/g, function(match, p1) {
        return String.fromCharCode(parseInt(p1, 16));
    }))
}`
3. Supplied the base64 to `file` as suggested [here](https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions#how-do-i-load-a-pdf-from-base64).

### Expected behavior

A Proper PDF file render.

### Actual behavior

![image](https://user-images.githubusercontent.com/96965109/200482626-feabec95-561d-4d74-ad88-55e54ff2837d.png)

### Environment

- **Browser (if applicable)** = Google Chrome Version 109.0.5396.2 (Official Build) dev (64-bit):
- **React-PDF version** = ^5.7.2:
- **React version** = 17.0.2:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
I don't see `data:application/pdf;base64,` but in your code 🤔

**Comment by f0-x** [comment]
> I don't see `data:application/pdf;base64,` but in your code 🤔

Sorry, @wojtekmaj. for wasting your time. Turns out it was a problem with my base64 encoding. I tried converting a publicly available PDF into base64 and rendered it successfully. However, could you still point me toward resources to properly encode my UTF-8 PDF to a valid base64 ? Or point out what the issue with conversion possibly be? Not supported latin characters in my PDF ? or something like that. Thanks a lot for your time.

**Comment by wojtekmaj** [comment]
Well, do you have `data:application/pdf;base64,` bit added somewhere? 

If it's present, then I don't immediately see what might be wrong with this conversion. Aside from... It being unnecessary. If you have binary data represented as a string, you might want to explore Uint8Array instead.

**Comment by f0-x** [comment]
Hi @wojtekmaj are you saying it is no longer necessary to prefix our base64 string with `data:application/pdf;base64,` when supplying it to `<Document file=...>`? 

When I supply my base64 to file without `data:application/pdf;base64,`, I see a network request to that long base64 string instead. I'm confused sorry.

**Comment by f0-x** [comment]
Tx @wojtekmaj I get you now. I was able to fix my issue by directly piping the API response (binary) to the <Docujment file=...> and it worked. Thank you for your time. ✌
