### ISSUE TITLE
"Failed to construct 'URL': Invalid URL" when using Webpack 5

### ISSUE THREAD

**Issue by sergeu90** [wojtekmaj/react-pdf#1150]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Failed to construct 'URL': Invalid URL 

![image](https://user-images.githubusercontent.com/7217517/200930310-09893166-1fc4-41eb-862e-b1964850f822.png)

### Steps to reproduce

`import { Document, Page } from 'react-pdf/dist/esm/entry.webpack5'; `

and get error.

### Expected behavior

Need to work with webpack 5

### Actual behavior

I see error Failed to construct 'URL': Invalid URL

### Environment

```
"react-pdf": "5.7.2",
"react": "18.2.0",
 "webpack": "5.75.0",
```

**Comment by wojtekmaj** [comment]
Can you share repro repository for me to look at? Obviously, [Webpack 5 sample included in React-PDF repo](https://github.com/wojtekmaj/react-pdf/tree/main/sample/webpack5) works fine, so it will be of no use.

**Comment by sergeu90** [comment]
@wojtekmaj  

Sorry i can't share repo. I used simple case. Install react-pdf and import 

`import { Document, Page } from 'react-pdf/dist/esm/entry.webpack5';` and all without any configuration

**Comment by PageB** [comment]
I have the same error when using vite builder.

`import { Document, Page } from "react-pdf/dist/esm/entry.vite";`

`Uncaught TypeError: Failed to construct 'URL': Invalid URL at entry.vite.js`

**Comment by jannikbuschke** [comment]
Seeing the same issue

**Comment by wojtekmaj** [comment]
The way we handle workers has been reworked (pun not intended) in v7 beta, so please check it out and see how it works for you!
