### ISSUE TITLE
customTextRenderer not working correctly in v6

### ISSUE THREAD

**Issue by paescuj** [wojtekmaj/react-pdf#1151]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The `customTextRenderer` doesn't seem to work correctly anymore in v6.

If a `customTextRenderer` is defined (even with the example provided under [Page -> Props](https://github.com/wojtekmaj/react-pdf#props-1)) the text elements are wrongly positioned and there are a lot elements with the content `undefined`:
```html
<span style="left: 101.687px; top: 100.54px; font-size: 2.16834px; font-family: sans-serif;" role="presentation" dir="ltr">undefined</span>
```

If the `customTextRenderer` is removed, everything works as expected and the text elements are correctly positioned.

### Steps to reproduce

1. Configure custom rendered:
```jsx
<Page
  customTextRenderer={
    ({ str, itemIndex }) => {
      return `<mark>${str}</mark>`;
    }
  }
  ...
/>
```
2. Check page and inspect elements

### Expected behavior

Text elements via custom rendered should be positioned correctly and not include `undefined` values

### Actual behavior

Text elements are wrongly positioned (clearly visible when using `<mark>`) and contains `undefined` values

### Environment

- **Browser (if applicable)**: Firefox 106.0.5
- **React-PDF version**: 6.0.2
- **React version**: 18.2.0
- **Webpack version (if applicable)**: -

**Comment by wojtekmaj** [comment]
"not working" is a bit of an overstatement, but yes, the example provided wasn't very good and lacked a null check which was not necessary in React before. Fixed that. :)

**Comment by wojtekmaj** [comment]
Yup, that _is_ a valid bug - thank you for noticing this!
