### ISSUE TITLE
When when resources are large, there appear Caton phenomenon, can realize the lazy loading？

### ISSUE THREAD

**Issue by sunlandong** [wojtekmaj/react-pdf#117]
When when resources are large, there appear Caton phenomenon, can realize the lazy loading？

**Comment by wojtekmaj** [comment]
Hey @sunlandong,
React-PDF makes it possible to do lazy loading, but it won't do it for you. It's just a "bridge" that will allow you to get PDFs displayed in React with little to no configuration. If you want to lazy load your pages, you should dig and see what other folks did. I've seen people pairing React-PDF with react-virtualized to do the job. Maybe that will get you going!
