### ISSUE TITLE
Can't find Page object in customTextRenderer layer prop on v6.0.3 (works on v5.7.2)

### ISSUE THREAD

**Issue by sherryzhang001** [wojtekmaj/react-pdf#1190]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

On v6.0.3, customTextRenderer no longer provide Page object in layer prop. Is there any reason for removing it? Currently we are using _pageIndex to do a cross div search, without it we couldn't tell which page the text is on.
<img width="630" alt="Screen Shot 2022-11-23 at 15 23 13" src="https://user-images.githubusercontent.com/44595197/203491607-09e3082b-be75-4072-acfe-2f27db0b8370.png">
<img width="1104" alt="Screen Shot 2022-11-23 at 14 13 11" src="https://user-images.githubusercontent.com/44595197/203491625-3456fe40-8487-43d9-8f21-76db789ef281.png">
<img width="691" alt="Screen Shot 2022-11-23 at 11 41 01" src="https://user-images.githubusercontent.com/44595197/203491635-7f9ba632-1675-4f10-b1f0-d9ce2ac2cf13.png">

### Steps to reproduce

console log the layer prop of customTextRenderer function.

### Expected behavior

get same object as in v5.7.2

### Actual behavior

Page object no longer in it

### Environment

- **Browser (if applicable)**: Chrome 107
- **React-PDF version**: 6.0.3
- **React version**: 17.0.2
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
This was never documented/intended.

**Comment by sherryzhang001** [comment]
> > This was never documented/intended.
> 
> Additionally, this has been announced as a breaking change in v6.0.0 (#944).
> 
> If you still need to access the current page you can easily control and track it via `pageIndex`.

Could you explain more about it? How can I get pageIndex in customTextRenderer?

**Comment by wojtekmaj** [comment]
Yeah, I actually don't see an easy way to do this :D I'd be able to work around it, but no reason to force everyone else to suffer from it.

**Comment by paescuj** [comment]
Pretty simple:

```
const [pageIndex, setPageIndex] = useState(0);

<Page
  pageIndex={pageIndex}
  customTextRenderer={
    (textItem) => myCustomTextRenderer(textItem, pageIndex)
  }
 />
```

But of course, it is more convenient if it is available out of the box 😄 So, thanks @wojtekmaj for https://github.com/wojtekmaj/react-pdf/commit/34fbf099933faf651ccb54d3700110527849bc65!

**Comment by sherryzhang001** [comment]
> textItem

Thank you so much for the changes!! May I ask which release will it be in?

**Comment by sherryzhang001** [comment]
> Yeah, I actually don't see an easy way to do this unless you inline `customTextRenderer` and you have direct access to pageIndex you use to render `Page` components :D I'd be able to work around it, but no reason to force everyone else to suffer from it.

Thank you so much for the changes!! May I ask which release will it be in?

**Comment by sherryzhang001** [comment]
> Yeah, I actually don't see an easy way to do this unless you inline `customTextRenderer` and you have direct access to pageIndex you use to render `Page` components :D I'd be able to work around it, but no reason to force everyone else to suffer from it.

Thank you so much for the update!! May I ask when will this change be released?

**Comment by EricLiu0614** [comment]
@wojtekmaj - Thank you for making the change! I also wondering when the new release will be published :)
