### ISSUE TITLE
not working with idm browser extension

### ISSUE THREAD

**Issue by pedram6195** [wojtekmaj/react-pdf#1195]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

when I try to preview a PDF file, idm's download box shows up and pdf fails to load with the following message: 

`Failed to load PDF file`

### Steps to reproduce

1. open a browser with idm extension enabled
2. try to show a pdf

### Expected behavior

to show the preview correctly

### Actual behavior

shows `Failed to load PDF file` error

### Environment

- **Browser (if applicable)**: firefox/chrome
- **React-PDF version**:^5.7.2
- **React version**:^18.1.0
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
I don't know what IDM extension is doing, but if it breaks web fundamentals like network requests then you should report it to the extension authors.
