### ISSUE TITLE
Text layer is not generated

### ISSUE THREAD

**Issue by admehta01** [wojtekmaj/react-pdf#120]
When using [this PDF](https://github.com/wojtekmaj/react-pdf/files/1577702/d41fabe8a5ca46a4be7e48f5be6768d4.pdf) in the demo.
In the Mozilla web viewer, the text layer is there and text is able to be selected.

**Comment by wojtekmaj** [comment]
Hey,
thanks for the report!
It actually is generated, but horribly misaligned ;) Fixing that in 2.4.3 :)
