### ISSUE TITLE
Unable to check the checkbox

### ISSUE THREAD

**Issue by leyvezzy** [wojtekmaj/react-pdf#1203]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When use a document with checkbox, before to v6.0.1 i can check all of box, but now i can't check no checkbox.
I tried to set the checkbox appear always checked, and i can unchecked, but i can't check it one more time

### Steps to reproduce

1.- Use some document with checkbox
2.- Use some event listener

### Expected behavior

I expected can check and uncheck all checkbox in document.

### Actual behavior

I can't check no checkbox in document

### Additional information

![Captura de Pantalla 2022-11-28 a la(s) 10 10 02](https://user-images.githubusercontent.com/86985597/204604739-d9c38a41-9e99-42a8-b8bc-0e18fcff8d83.png)
![Captura de Pantalla 2022-11-28 a la(s) 9 41 22](https://user-images.githubusercontent.com/86985597/204604753-e9162bdf-1619-460f-855f-b7244043a07d.png)
I saw update some of values within checkbox object, but i don't find in documentation.

### Environment

- **Browser (if applicable)**: Google chrome V107.0.5304.121, Firefox Developer Edition 108.0b7
- **React-PDF version**: v6.2.0
- **React version**: v18.2.0
- **Webpack version (if applicable)**: no applicable

**Comment by hiruthicShaSS** [comment]
Hey, I am facing the same issue. I tried the issue #961 
```js
pdfjs.GlobalWorkerOptions.workerSrc = `/node_modules/pdfjs-dist/build/pdf.worker.entry.js`;
```
but it produces a runtime error:
```
Uncaught SyntaxError: Unexpected token '<'
    at handleError (http://localhost:3000/static/js/bundle.js:62816:58)
    at http://localhost:3000/static/js/bundle.js:62835:7
```

I am using:
- **Node:** v17.9.1
- **react-pdf:** ^6.2.2
- **Chrome:** 113.0.5672.127 64 bit

Is there any update on this issue?

**Comment by TadasValaitiz** [comment]
I'm facing same issue
