### ISSUE TITLE
`react-pdf/dist/esm/entry.vite` is not included in `@types/react-pdf@5.7.4`

### ISSUE THREAD

**Issue by hanayashiki** [wojtekmaj/react-pdf#1204]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

According to the documentation, if I want to import a vite-compatible build, I should import in the following way:

```ts
import { Document, Page } from 'react-pdf/dist/esm/entry.vite';
```

The build is perfect, but TypeScript complains:

```
Could not find a declaration file for module 'react-pdf/dist/esm/entry.vite'. '.../react-pdf/dist/esm/entry.vite.js' implicitly has an 'any' type.
  If the 'react-pdf' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-pdf'
```

I think the module should be included in `@types/react-pdf`.

To work this around in Vite 3, I would suggest adding `resolve` in `vite.config.ts`:

```ts
    resolve: {
      alias: {
        'react-pdf': 'react-pdf/dist/esm/entry.vite',
      },
    },
```

and just import `react-pdf`. However, in this way, you should provide the relative path to css modules in this package, since all `react-pdf/*.css` would also be resolved under `react-pdf/dist/esm/entry.vite`.

### Steps to reproduce

1. Use TypeScript

2. Add the following code

```ts
import { Document, Page } from 'react-pdf/dist/esm/entry.vite';
```

### Expected behavior

No type errors should be here

### Actual behavior

It errors

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 6.2.0
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Types are not maintained here, but on DefinitelyTyped. Please raise an issue there.
