### ISSUE TITLE
Nor rendering correct Turkish Lira symbol

### ISSUE THREAD

**Issue by swarmukhdefault** [wojtekmaj/react-pdf#1205]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The ₺ symbol gets rendered as &prime;&prime; (two `prime` characters). But when the two `prime` characters are copied from a PDF viewer and pasted somewhere else, the text that gets pasted is the ₺ symbol.

All other currencies extracted from Toptal along with each of their HTML symbol, HTML code and HTML hex code works fine, except for the Turkish lira.

### Steps to reproduce

Used `puppeteer`'s `pdf` functionality to generate a PDF from the following HTML

```html
<div>HTML Symbol: ₺</div>
<div>HTML Code: &#8378;</div>
<div>HTML Hex Code: &#x20BA;</div>
```

### Expected behavior

<pre>
HTML Symbol: ₺
HTML Code: ₺
HTML Hex Code: ₺
</pre>

### Actual behavior

All of them gets rendered as:

<pre>
HTML Symbol: &prime;&prime;
HTML Code: &prime;&prime;
HTML Hex Code: &prime;&prime;
</pre>

### Environment

- **Browser (if applicable)**: Chrome, Firefox
- **React-PDF version**: 5.5.0
- **React version**: 16.14.0
- **Webpack version (if applicable)**: 5.23.0

**Comment by swar-mukh** [comment]
@wojtekmaj nope. That's not the case, I addressed in the correct repo.

Actually, the issue was due to absence of `charset` value of `utf-8` was missing. Well, that's a long time back now! Regards!
