### ISSUE TITLE
file is fetched twice

### ISSUE THREAD

**Issue by 78raoul78** [wojtekmaj/react-pdf#1213]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When I render a pdf with its url, the file is fetched twice due to a set state done for the number of pages.

### Steps to reproduce

I'm using react-pdf to display a pdf file in the following way : 

```
import React, { FC, useState } from 'react'
import { Document, Page, pdfjs } from 'react-pdf'

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js`

export interface PDFProps {
  url: string
  width?: number
  onLoadError?: Document['props']['onLoadError']
  onSuccess?: () => void
}

export const PDF: FC<PDFProps> = ({ url, onSuccess }) => {
  const [pageNumbers, setPageNumbers] = useState<number[]>([])

  const onLoadSuccess: Document['props']['onLoadSuccess'] = ({ numPages }) => {
    if (numPages !== pageNumbers.length) {
      const pagesIndex = [...Array(numPages).keys()].map(
        (pageIndex) => pageIndex + 1,
      )

      setPageNumbers(pagesIndex)
      if (onSuccess) {
        onSuccess()
      }
    }
  }

  return (
    <Document
      options={{
        standardFontDataUrl: `https://unpkg.com/pdfjs-dist@${pdfjs.version}/standard_fonts`,
      }}
      file={{ url, withCredentials: true }}
      onLoadSuccess={onLoadSuccess}
    >
      {pageNumbers.map((pageNumber: number) => (
        <div key={pageNumber}>
          <Page pageNumber={pageNumber} />
        </div>
      ))}
    </Document>
  )
}
```

Almost everything is working well, the file is correctly opened and I can navigate through all the pages but I have the following issue : When the document loads for the first time, it does a network request to fetch the file, but then the onSuccess callback is called and this one affect the state (setPageNumbers) causing the document to rerender and so doing again the same network request to fetch the file, this could be seen in the network tab : 

![image](https://user-images.githubusercontent.com/38441420/205333660-f1ce5369-4298-40f4-9788-9c55576df50d.png)

### Expected behavior

File should only be fetched once.

### Actual behavior

File is fetched twice.

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by bregy1** [comment]
having the same issue here..

**Comment by wojtekmaj** [comment]
Are you using StrictMode by any chance?

**Comment by bregy1** [comment]
No , I am still on React 17--

**Comment by vfa-tuanva** [comment]
@78raoul78 You could solve this problem by reading this topic 'React-PDF reloads itself with every render. What's going on?' in this link https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions
and set file object as a state in component

**Comment by jiangxiaoqiang** [comment]
did you fixed this issue? @78raoul78

**Comment by wojtekmaj** [comment]
The reason the file is fetched twice is a combination of:
- Usage of React Strict Mode, which renders everything twice to make it easier to expose issues like lack of proper effect cleanup of lack of good memoization
- ...and a lack of good memoization :D

In docs, you can read:

> **Warning:** Since equality check (`===`) is used to determine if `file` object has changed, it must be memoized by setting it in component's state, `useMemo` or other similar technique.

And your code fails to memoize both objects passed to `options` and `file` props.

**Comment by jiangxiaoqiang** [comment]
> The reason the file is fetched twice is a combination of:
> 
> * Usage of React Strict Mode, which renders everything twice to make it easier to expose issues like lack of proper effect cleanup of lack of good memoization
> * ...and a lack of good memoization :D
> 
> In docs, you can read, regarding `options` prop:
> 
> > **Note:** Make sure to define options object outside of your React component, and use `useMemo` if you can't.
> 
> and regarding `file` prop:
> 
> > **Warning:** Since equality check (`===`) is used to determine if `file` object has changed, it must be memoized by setting it in component's state, `useMemo` or other similar technique.
> 
> And your code fails to memoize both objects passed to `options` and `file` props.

I have already use useMemo with the option and url but still fetch 3 times when open the component with pdf render.

**Comment by wojtekmaj** [comment]
Does it actually fetch multiple times, or it fetches the PDF bit by bit? Because if the server supports it, the library will only download the parts of the PDF it needs to render the desired pages.
