### ISSUE TITLE
How do I make Page responsive?

### ISSUE THREAD

**Issue by Keshish** [wojtekmaj/react-pdf#1214]
### Before you start - checklist

- [X] I followed instructions in the documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

React-pdf works fairly well for the desktop version, however, when I switch to the mobile version, it becomes blurry. I have tried many fixes without success.

I looked at issues #958  and #849  and tried to scale them, but I was unable to fix. Changing the render mode to SVG also helped the resolution but harmed the design and resulted in issue #529 , which I was also unable to resolve.

the following code shows the implementation of react-pdf with its CSS part,

![sc](https://user-images.githubusercontent.com/59834652/205937008-ae6bae99-eaef-4dc4-a2ec-f9fe542035c7.png)

> This is my first Issue on GitHub, so if you see anything that may be improved, or missing, ask for it please.

.TSX

```typescript
export default function PdfCard() {
  const [numPages, setNumPages] = useState<number>(0);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }: any) {
    setNumPages(numPages);
  }
  return (
    <>
      <div id="ResumeContainer" className="mt-4">
        <Document className={'PDFDocument'} file={samplePDF} onLoadSuccess={onDocumentLoadSuccess}>
          {Array.apply(null, Array(numPages))
            .map((x, i) => i + 1)
            .map(page => (
              <Page 
              renderMode={"svg"}
                key={page}
                className={'PDFPage PDFPageOne'}
                pageNumber={page}
                renderTextLayer={false}
                renderInteractiveForms={false}
              />
            ))}            
        </Document>
      </div>
    </>
  );
}
```

.CSS
```typescript
#ResumeContainer {
    margin: auto;
    width: 90%;
    display: flex;
    flex-direction: column;
    align-items: center;
    }
    
    .PDFDocument {
    display: flex;
    flex-direction: column;
    align-items: center;
    }
    
    .PDFPage {
    box-shadow: 0 0 8px rgba(0, 0, 0, 0.5);
    }
    
    .PDFPageOne {
    margin-bottom: 25px;
    }
    
    .PDFPage > canvas {
    max-width: 100%;
    height: auto !important;
    }```

### Steps to reproduce

Try to inspect any pdf in the mobile version 

### Expected behavior
please check attached screenshot's resolution,

### Environment

- **Browser (if applicable)**: Chrome Version 108.0.5359.71
- **React-PDF version**: 5.7.2
- **React version**: 18.0.0
- **Webpack version (if applicable)**: 5

**Comment by SebiBasti** [comment]
I have a smilir issue: I implemented a little fullscreen feature that sets the width to `100%` and afterwards the `canvas` gets blurry. In `svg` mode it works fine, but if it's not supported in the future I would like to get `canvas` working.

**Comment by wojtekmaj** [comment]
Remember that canvas is essentially a raster image with certain dimensions. We need to redraw it if scale is to be changed. Therefore, you need to listen for window resize events, and calculate desired width using JavaScript, not CSS, and passing it to Page component using width prop. Scaling it up using CSS will make it blurry, scaling it down will make it extra crispy and not looking very well in most cases.
