### ISSUE TITLE
Is there a a way to override the render lifecycle?

### ISSUE THREAD

**Issue by abdobrianZverse** [wojtekmaj/react-pdf#1228]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

I want to have a way to override the render lifecycle so that I could render multiple pdfs in a scene like environment without requiring multiple canvas'.  Is there currently a way to do that or would this require a new feature? I have not found anything like this in documentation / previously asked questions.

**Comment by wojtekmaj** [comment]
Hello,
there's currently no way overriding render lifecycle and I doubt it would be possible looking at PageCanvas and PageSvg components. But of you have any idea how to implement that without a ton of changes, let me know!
