### ISSUE TITLE
Disabled rendering with text layer enabled

### ISSUE THREAD

**Issue by vsolominov** [wojtekmaj/react-pdf#1229]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

If I set the `renderMode='none'` parameter together with the `renderTextLayer={true}` parameter, then the text cannot be selected.

### Steps to reproduce

1. Go to [Test project](https://codesandbox.io/s/react-pdf-textlayer-render-gcvzuq)
2. Try select the text

### Expected behavior

Text selected

### Actual behavior

Text not selected

### Environment

- **Browser**: Chrome 108.0.5359.125
- **React-PDF version**: 6.2.0
- **React version**: 18.2.0

**Comment by vsolominov** [comment]
Can you please tell me if it is possible to display only the text layer (eg white background, black text) without displaying the rest of the content (or at least under the white background)?

**Comment by wojtekmaj** [comment]
TextLayer indeed "hooks" into a container that is expanded by rendered PDF content, so if it's missing, you gotta make some styling changes.

Try:

```css
.textLayer {
  position: static;
}

.textLayer span, .textLayer br {
  color: inherit !important;
}
```
