### ISSUE TITLE
Invalid PDF structure

### ISSUE THREAD

**Issue by cgd199158** [wojtekmaj/react-pdf#123]
I tested multiple PDF files, but it still render error "Invalid PDF structure" 
`
"react": "^15.5.0",
"react-dom": "^15.5.0",
"webpack": "^3.8.1",
"react-pdf": "^2.0.0"/"^2.4.2",
`

**Comment by wojtekmaj** [comment]
Hey @cgd199158,
would you please share a piece of your code, how are you passing the file exactly?

**Comment by cgd199158** [comment]
`<div className="content" style={{overflow: 'auto'}}>
      <div className="details-wrap ">
        <div className="details-title">
          <h2>{newsItem.title}</h2>
          <div className="details-infor-wrap">
            <div>
              <span className="details-infor">文章类型:{newsItem.category ? newsItem.category.name : ''}</span>
              <span className="details-infor">发布时间:{newsItem.createDate}</span>
              {/* <span className="details-infor">关键字:{newsItem.keywords}</span> */}
            </div>
            <span className="details-action">
              <span>【下载附件】</span>
              <span><a  href="javascript:window.opener=null;window.open('','_self');window.close();">【关闭窗口】</a></span>
            </span>
          </div>
        </div>
        {/*<div className="detauls-content" dangerouslySetInnerHTML={createMarkup()}>*/}
        <div className="detauls-content" >
          <Document
            file="sample.pdf"
          >
          </Document>
        </div>
        <NewsFooter />
      </div>
    </div>`

**Comment by cgd199158** [comment]
`<div className="detauls-content" >
          <Document
            file="sample.pdf"
          >
          </Document>
       </div>`
The simplest example I have used.

**Comment by wojtekmaj** [comment]
That looks okay to me, as long as `file` is a valid URL and you're using a server for testing. Check Network tab in Developer Tools if your file downloads properly.

**Comment by cgd199158** [comment]
![image](https://user-images.githubusercontent.com/18514077/34430560-54d36a1e-eca1-11e7-9f51-e5a81d826e64.png)
![image](https://user-images.githubusercontent.com/18514077/34430593-8e242948-eca1-11e7-9984-2aaba62d5b3f.png)

**Comment by cgd199158** [comment]
![image](https://user-images.githubusercontent.com/18514077/34432601-ae5a1e86-ecb3-11e7-9ac3-9c5ed0ee614d.png)
What is this document for?

**Comment by wojtekmaj** [comment]
You have set up your bundle improperly. Please read README file to get more info about pdf.worker.js.

**Comment by elmalitsi** [comment]
I had the same issue. It was due to the url. Its needs to be https not http. Once I changed that it worked fine.

**Comment by wojtekmaj** [comment]
In your specific case, it may had to be https if you have a https server. But there's no such requirement from React-PDF side.
