### ISSUE TITLE
Set height in version 3 

### ISSUE THREAD

**Issue by LTAbhirup** [wojtekmaj/react-pdf#1230]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I am trying to set height on the Page component, but found the `height` prop is missing. Need help .
The page tooks the rest of the content and hence the page number text is missed out.

<img width="807" alt="Screenshot 2022-12-23 at 11 35 56 AM" src="https://user-images.githubusercontent.com/104512954/209281277-615cc5ac-2fa1-4774-921f-79fb80fc59a6.png">

### Steps to reproduce

JSX
```
<div>
        <Document
          file="/shared/sample_pdf.pdf"
          onLoadSuccess={this.onDocumentLoad}
        >
          <Page pageNumber={pageNumber} height={100} width={300}/>
        </Document>
        <p>
          Page {pageNumber} of {numPages}
        </p>
      </div>
```

### Expected behavior

The height will be configurable.

### Actual behavior

The height is not configurable

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 3.0.6
- **React version**: 15.6.2
- **Webpack version (if applicable)**:3.11.0

**Comment by wojtekmaj** [comment]
Last React-PDF v3 has been released over 4 years ago and is no longer supported.

**Comment by LTAbhirup** [comment]
hey , i am using the width prop  and scale prop , but it is not zooming. Any solution ?

Not sure if it is this issue: https://github.com/wojtekmaj/react-pdf/issues/872#issuecomment-946587175
```
<Document
      file="/shared/sample_pdf.pdf"
      onLoadSuccess={this.onDocumentLoad}
    >
      <Page pageNumber={pageNumber} 
      // height={100} 
      width={200} 
      scale={5}
      />
      <p className='page-number'>
      Page {pageNumber} of {numPages}
    </p>
</Document>
```

Output:
<img width="1425" alt="Screenshot 2022-12-23 at 2 40 45 PM" src="https://user-images.githubusercontent.com/104512954/209307348-474443df-088b-46fd-ab87-1c5b9c898bc4.png">
