### ISSUE TITLE
The first anchor link cannot be opened

### ISSUE THREAD

**Issue by otofu-square** [wojtekmaj/react-pdf#1231]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When a page in a PDF contains multiple links, the first link that appears seems to be unclickable.

### Steps to reproduce

1. Go to https://codesandbox.io/s/react-pdf-broken-first-link-hj14yz
2. If you click on `https://example.com/1` the link won't open

### Expected behavior

All links are clickable.

### Actual behavior

The first link is not clickable.

### Additional information

This seems to be due to the fact that the z-index of `endOfContent` changed from -1 to 0 in [this commit](https://github.com/wojtekmaj/react-pdf/commit/321b9e59288e9a650ad405c1249aeddbfbd1f4bd), which conflicts with the `z-index: 0` of the text layer of the first link.

It seems that either changing the z-index of endOfContent back to -1 or changing the z-index of the text layer to start with 1 may solve the problem.

### Environment

- **Browser (if applicable)**: Chrome 108
- **React-PDF version**: 6.2.0
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by rgarfield11** [comment]
Sorry @otofu-square this was a while ago, but were you able to resolve this issue? 

Looking at your sandbox example and inspecting DOM elements tab, I see that the first link is a `<span>` while the others are `<a>` tags. Did this have anything to do with the z-indexing as you suspected?
