### ISSUE TITLE
Vite entry error

### ISSUE THREAD

**Issue by LTAbhirup** [wojtekmaj/react-pdf#1232]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I am getting this error when using vite entry
![Screenshot 2022-12-26 at 6 14 08 PM](https://user-images.githubusercontent.com/104512954/209550562-d635f8de-1688-4800-9703-0990f566302e.png)

### Steps to reproduce

Code:
```
import {useState} from 'react';
import {Box } from '@mui/material';
import {Document, Page} from 'react-pdf/dist/esm/entry.vite';

const ReactPDF = ()=>{
    const [numPages, setNumPages] = useState<number|null>(null);
    const [pageNumber, setPageNumber] = useState(1);
  
    function onDocumentLoadSuccess({ numPages }: {numPages: number}) {
      setNumPages(numPages);
    }
    
    return (
    <Box bgcolor="background.paper">
        <Document file="./sample_pdf.pdf"
        onLoadSuccess={onDocumentLoadSuccess}
        >
            <Page pageNumber={pageNumber}/>
        </Document> 
    </Box>
  )
}

export default ReactPDF;
```

### Expected behavior

Should render the pdf

### Actual behavior

Webpage crashing

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**:6.2.0
- **React version**: 17.0.2
- **Webpack version (if applicable)**:
-     "vite": "^3.0.7",

**Comment by wojtekmaj** [comment]
Related: #1148. Looks like it may be related to https://github.com/wojtekmaj/react-pdf/issues/1148#issuecomment-1314180559?

**Comment by LTAbhirup** [comment]
@wojtekmaj for now, solved this issue by importing pdfjs from this library and using the workerSrc
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;

Thanks

**Comment by wojtekmaj** [comment]
Just a small note: if you're manually providing workerSrc, there's no point to keep using Vite-specific entry point which sole purpose is to provide workerSrc. :)

**Comment by maaaathis** [comment]
> > @wojtekmaj for now, solved this issue by importing pdfjs from this library and using the workerSrc pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;
> > Thanks
> 
> ```
> import pdfWorker from 'pdfjs-dist/build/pdf.worker.js?url';
> import {Document, Page} from 'react-pdf/dist/esm/entry.vite';
> import {pdfjs} from "react-pdf";
> 
> pdfjs.GlobalWorkerOptions.workerSrc = pdfWorker;
> ```
> 
> it works with vite3 + ts 4.6 + react 18.2 + react-pdf 6.2.2 compared with your solution, this method does not require external CDN.

Do you have a new solution for this, @flymyd? 
When using the latest versions, I encounter an error stating that it can't find `react-pdf/dist/esm/entry.vite.`. Switching to plain `react-pdf` resolves the issue. However, a new error surfaces: `Failed to resolve import "pdfjs-dist/build/pdf.worker.js?url".` There is no `pdf.worker.js'`in the directory, only `pdf.worker.mjs,` which does not support my import.

**Comment by flymyd** [comment]
> > > @wojtekmaj for now, solved this issue by importing pdfjs from this library and using the workerSrc pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;
> > > Thanks
> > 
> > 
> > ```
> > import pdfWorker from 'pdfjs-dist/build/pdf.worker.js?url';
> > import {Document, Page} from 'react-pdf/dist/esm/entry.vite';
> > import {pdfjs} from "react-pdf";
> > 
> > pdfjs.GlobalWorkerOptions.workerSrc = pdfWorker;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it works with vite3 + ts 4.6 + react 18.2 + react-pdf 6.2.2 compared with your solution, this method does not require external CDN.
> 
> Do you have a new solution for this, @flymyd? When using the latest versions, I encounter an error stating that it can't find `react-pdf/dist/esm/entry.vite`. Switching to plain `react-pdf` resolves the issue. However, a new error surfaces: `Failed to resolve import "pdfjs-dist/build/pdf.worker.js?url".` There is no `pdf.worker.js` in the directory, only `pdf.worker.mjs,` which does not support my import.

What versions of Vite and react-pdf are used in your project?

**Comment by flymyd** [comment]
> > > @wojtekmaj for now, solved this issue by importing pdfjs from this library and using the workerSrc pdfjs.GlobalWorkerOptions.workerSrc = ;
> > > Thanks`//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`
> > 
> > 
> > ```
> > import pdfWorker from 'pdfjs-dist/build/pdf.worker.js?url';
> > import {Document, Page} from 'react-pdf/dist/esm/entry.vite';
> > import {pdfjs} from "react-pdf";
> > 
> > pdfjs.GlobalWorkerOptions.workerSrc = pdfWorker;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it works with vite3 + ts 4.6 + react 18.2 + react-pdf 6.2.2 compared with your solution, this method does not require external CDN.
> 
> Do you have a new solution for this, @flymyd? When using the latest versions, I encounter an error stating that it can't find . Switching to plain resolves the issue. However, a new error surfaces: There is no in the directory, only which does not support my import.`react-pdf/dist/esm/entry.vite``react-pdf``Failed to resolve import "pdfjs-dist/build/pdf.worker.js?url".``pdf.worker.js``pdf.worker.mjs,`

This is a sample with vite@5.0.3 and react-pdf@7.5.1
```typescript
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';
import 'react-pdf/dist/esm/Page/TextLayer.css';
import {FC, useState} from "react";
import {pdfjs, Document, Page} from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url,
).toString();
const App: FC = () => {
  const [numPages, setNumPages] = useState(null);
  return (
    <Document file="https://test.com/sample.pdf" onLoadSuccess={(e: any) => setNumPages(e.numPages)}>
      {Array.from(new Array(numPages), (_el, index) => <Page key={`page_${index + 1}`} pageNumber={index + 1} width={980}/>)}
    </Document>
  )
}
export default App;
```

**Comment by leonbloy** [comment]
Should be `'pdfjs-dist/build/pdf.worker.min.mjs' ` instead of ` 'pdfjs-dist/build/pdf.worker.min.js'` in version 9.0

**Comment by LatVAlY** [comment]
using pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.mjs',
  import.meta.url
).toString();

locally works but on the production getting an error 
Setting up fake worker failed: "Failed to fetch dynamically imported module: https://www.test.com/assets/pdf.worker.min-DGf6LXVo.mjs".

any solution to tackle this? 

here is my vite.comfig.ts
`export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  build: {
    rollupOptions: {
      output: {
        entryFileNames: `[name].[hash].mjs`,
        chunkFileNames: `[name].[hash].mjs`,
      },
    },
  },
  define: { 'process.env': {} },
  optimizeDeps: {
    esbuildOptions: {
      plugins: [fixReactVirtualized],
    },
  },
});
`

**Comment by miteshsavani810** [comment]
> using pdfjs.GlobalWorkerOptions.workerSrc = new URL( 'pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url ).toString();
> 
> locally works but on the production getting an error Setting up fake worker failed: "Failed to fetch dynamically imported module: https://www.test.com/assets/pdf.worker.min-DGf6LXVo.mjs".
> 
> any solution to tackle this?
> 
> here is my vite.comfig.ts `export default defineConfig({ plugins: [react()], resolve: { alias: { '@': path.resolve(__dirname, 'src'), }, }, build: { rollupOptions: { output: { entryFileNames: `[name].[hash].mjs`, chunkFileNames: `[name].[hash].mjs`, }, }, }, define: { 'process.env': {} }, optimizeDeps: { esbuildOptions: { plugins: [fixReactVirtualized], }, }, }); ` when checking the network, the file is there but seems like is commented out! ![Screenshot 2024-08-02 at 16 34 06](https://private-user-images.githubusercontent.com/60847724/354630092-c45b04dd-ad84-4411-ad55-6d4c9efc4049.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTY3NjYsIm5iZiI6MTcyNDE1NjQ2NiwicGF0aCI6Ii82MDg0NzcyNC8zNTQ2MzAwOTItYzQ1YjA0ZGQtYWQ4NC00NDExLWFkNTUtNmQ0YzllZmM0MDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDEyMjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YWQyOGQ3MTEwN2M5MDFhYjk0ZjNiNmYzMGRlNjcwZjg1MGJkMDdhNGNjYTk2NGE3MDc4Yjg2Y2YyM2Q4ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7M39l6bNSPCoA9jJ_f1BIUCnmtveUzgJQBtdWAv5PRQ)

Facing the same issue.

**Comment by anton-x-t** [comment]
This worked for me (React/Vite):
```
import { pdfjs } from "react-pdf";
import pdfWorker from "pdfjs-dist/build/pdf.worker.min.mjs?worker";
pdfjs.GlobalWorkerOptions.workerPort = new pdfWorker();
```

Sources:
What should be the value for workerSrc? 8305,
thank you Leung Yau Ming,
https://github.com/mozilla/pdf.js/issues/8305#issuecomment-1674973556

Importing Script as a Worker, vite.dev,
thank you helloworld3200 et al,  
https://vite.dev/guide/assets.html#importing-script-as-a-worker

**Comment by wjourney** [comment]
> using pdfjs.GlobalWorkerOptions.workerSrc = new URL( 'pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url ).toString();
> 
> locally works but on the production getting an error Setting up fake worker failed: "Failed to fetch dynamically imported module: https://www.test.com/assets/pdf.worker.min-DGf6LXVo.mjs".
> 
> any solution to tackle this?
> 
> here is my vite.comfig.ts `export default defineConfig({ plugins: [react()], resolve: { alias: { '@': path.resolve(__dirname, 'src'), }, }, build: { rollupOptions: { output: { entryFileNames: `[name].[hash].mjs`, chunkFileNames: `[name].[hash].mjs`, }, }, }, define: { 'process.env': {} }, optimizeDeps: { esbuildOptions: { plugins: [fixReactVirtualized], }, }, }); ` when checking the network, the file is there but seems like is commented out! ![Screenshot 2024-08-02 at 16 34 06](https://private-user-images.githubusercontent.com/60847724/354630092-c45b04dd-ad84-4411-ad55-6d4c9efc4049.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MTk1NTIsIm5iZiI6MTczMTkxOTI1MiwicGF0aCI6Ii82MDg0NzcyNC8zNTQ2MzAwOTItYzQ1YjA0ZGQtYWQ4NC00NDExLWFkNTUtNmQ0YzllZmM0MDQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA4NDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NzZiOTVlNDYzY2MzZDYwMDUyZDI2ZTYxNDlhYjU4MzhkMzIyZmVjZTc3MmVkOWUzYmViZGNhMjdhMzZhYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7xWindk94HClUikMULsxp9TeOWJh11vMnDtvwgrafQU)

I meet the same question, have you resolved it ?

**Comment by hrdanu-mitrais** [comment]
> using pdfjs.GlobalWorkerOptions.workerSrc = new URL( 'pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url ).toString();
> 
> locally works but on the production getting an error Setting up fake worker failed: "Failed to fetch dynamically imported module: https://www.test.com/assets/pdf.worker.min-DGf6LXVo.mjs".
> 
> any solution to tackle this?
> 
> here is my vite.comfig.ts `export default defineConfig({ plugins: [react()], resolve: { alias: { '@': path.resolve(__dirname, 'src'), }, }, build: { rollupOptions: { output: { entryFileNames: `[name].[hash].mjs`, chunkFileNames: `[name].[hash].mjs`, }, }, }, define: { 'process.env': {} }, optimizeDeps: { esbuildOptions: { plugins: [fixReactVirtualized], }, }, }); ` when checking the network, the file is there but seems like is commented out! ![Screenshot 2024-08-02 at 16 34 06](https://github.com/user-attachments/assets/c45b04dd-ad84-4411-ad55-6d4c9efc4049)

I managed to solve it by adding a new key to the Vite build output configuration, like this:

```
...
assetFileNames: (assetInfo) => {
          if (assetInfo.names.includes('pdf.worker.min.mjs')) {
            return 'pdf.worker.min.mjs'
          }

          return '[name].[hash].[ext]'
        }
```
