### ISSUE TITLE
Error does not provide an export named 'default' in vite 4

### ISSUE THREAD

**Issue by ming2024** [wojtekmaj/react-pdf#1243]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Describe the bug

when I run storybook, the latest version of vite will face error of
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/111698568/209984675-76fa6641-c38d-4f90-85ec-b1e186b4d631.png">

I downgrade to older version, the error is gone.
"vite": "^2.6.10"

### Steps to reproduce

run `npm run storybook` it's working fine
https://github.com/ming2024/vite-boilerplate/tree/vite2

do the same in this branch https://github.com/ming2024/vite-boilerplate/tree/main it will throw error

### Expected behavior

it shouldn't throw error on both vite version.

### Actual behavior

vite 3, 4 doesn't work.

### Additional information

I tried to use cdn as other have tried, eg.

```
pdfjs.GlobalWorkerOptions.workerSrc = '//unpkg.com/pdfjs-dist@3.1.81/build/pdf.worker.entry.js'
```
doesn't solve the problem.

**Comment by ming2024** [comment]
need to know how to use react-pdf in vite 4, because with vite 2 I have another issues and no way I would use vite 2 just because of 1 lib. thanks!

**Comment by wojtekmaj** [comment]
Hmmm, I have added [Vite 4 sample](https://github.com/wojtekmaj/react-pdf/tree/vite-4-sample/sample/vite4) and it seems it's working fine. Not sure what the difference is.

**Comment by eldyvoon** [comment]
This is a false positive that happens on my laptop. It could be because of node version error. Thanks for looking into it.

**Comment by wojtekmaj** [comment]
Happy to reopen if it actually is React-PDF's fault. :)
