### ISSUE TITLE
Style for wordSpacing is ignored

### ISSUE THREAD

**Issue by marto** [wojtekmaj/react-pdf#1275]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Word Spacing (as per https://developer.mozilla.org/en-US/docs/Web/CSS/word-spacing) does not work. This is supported by the underlying PDFKit library (see https://pdfkit.org/docs/text.html#text_styling), but by the looks of it is not being passed down.

### Steps to reproduce

Go to https://react-pdf.org/repl and change the `text` style and add `wordSpacing: '100px'`.

### Expected behavior

The amount of space between each word in the text should increase to 100px.

### Actual behavior

The amount of space between each word remains the same.

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: ^3.0.2
- **React version**: 
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
