### ISSUE TITLE
SyntaxError: Unexpected token '||=' on version 

### ISSUE THREAD

**Issue by rubenofen** [wojtekmaj/react-pdf#1276]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When try to build my Next.js application using react-pdf 6.2.2 this error is raised.
As can be seen, this operator is in line 1779 of inside build folder pdf.js. Presumably, this operator is coming from some Ruby developer.
![Screenshot 2023-01-12 at 17 53 44](https://user-images.githubusercontent.com/18423735/212131556-f40df24a-35de-4fe9-a82b-8c1f1480586d.png)

### Steps to reproduce

Try to build a Next.js project inside Vercel deployment

### Expected behavior

the project is built and deployed

### Actual behavior

An error is raised during building 

/vercel/path0/node_modules/pdfjs-dist/build/pdf.js:1779
--
17:52:12.162 | return this._jsActionsPromise \|\|= this._transport.getPageJSActions(this._pageIndex);
17:52:12.162 | ^^^
17:52:12.162 |  
17:52:12.163 | SyntaxError: Unexpected token '\|\|='
17:52:12.163 | at wrapSafe (internal/modules/cjs/loader.js:1001:16)
17:52:12.163 | at Module._compile (internal/modules/cjs/loader.js:1049:27)
17:52:12.163 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
17:52:12.163 | at Module.load (internal/modules/cjs/loader.js:950:32)
17:52:12.164 | at Function.Module._load (internal/modules/cjs/loader.js:790:12)
17:52:12.164 | at Module.require (internal/modules/cjs/loader.js:974:19)
17:52:12.164 | at require (internal/modules/cjs/helpers.js:101:18)
17:52:12.164 | at Object.<anonymous> (/vercel/path0/node_modules/react-pdf/dist/cjs/entry.js:27:37)
17:52:12.165 | at Module._compile (internal/modules/cjs/loader.js:1085:14)
17:52:12.165 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

### Environment

- **React-PDF version**: 6.2.2
- **React version**: 17

**Comment by FindingHomeHere** [comment]
I'm also running in to this! Same output, Same React-PDF version, but React 18.

**Comment by vgermes** [comment]
Try adding the plugin to `@babel/plugin-proposal-logical-assignment-operators` in `webpack` configurator.

**Comment by rubenofen** [comment]
I have updated to:
"next": "^13.1.6"
"react": "^18.2.0",
"react-pdf": "^6.2.2",

and the issue is still present.

I have tried to add the babel plugin too, to my babel config project, and in local is building fine, but in the server is not working. And the issue is the same

`
{
  "presets": ["next/babel"],
  "plugins": [["styled-components", { "ssr": true }], "@babel/plugin-syntax-logical-assignment-operators"]
}
`

Any ideas?

**Comment by devil-geek** [comment]
hey I had the same issue, I was able to solve it without babel plugin in Vercel just go to Settings->General->Node version
and change the node version to match you local version, for me node 16 worked, previously had node 14 with the error.
hope that helps.
