### ISSUE TITLE
Safari 14 on iOS 16+ blocks execution for complexes PDFs

### ISSUE THREAD

**Issue by seb-montana** [wojtekmaj/react-pdf#1278]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When we use complexes PDFs, with lot of vectors, only on Safari on iOS 16+, processus seems to be stopped  (no error in console).
I think Safari prevents performance degradation for save iPhone battery.

This is an PDF example : [https://static.app-elly.fr/test-bug-pdf-viewer.pdf](https://static.app-elly.fr/test-bug-pdf-viewer.pdf)

Any idea ?

Thanks,

### Steps to reproduce

https://mozilla.github.io/pdf.js/web/viewer.html?file=https://static.app-elly.fr/test-bug-pdf-viewer.pdf
Maybe reload one or two times.
Bug appends on iPhone iOS 16+
Bug appends on xCode Simulator iPhone iOS 16+

### Expected behavior

Process not blocked, maybe optimized.

### Actual behavior

Process blocked by Safari (no error in console)

### Environment

- **Browser (if applicable)**: Safari 14
- **React-PDF version**: ^6.2.2
- **React version**: ^18.2.0
- **Webpack version (if applicable)**: 5.73.0

**Comment by JaZZim** [comment]
A similar problem is observed in safari on macos. It takes a long time (~ 2 minutes) to render a document of 42 pages, then it displays it without any problems. No such problems in google chrome
### Environment
- Browser: Safari 16.2
- React-PDF version: ^5.7.2
- React version: ^17.0.2
- MacBook Pro (14, 2022)
- macOS: Monterey

**Comment by wojtekmaj** [comment]
If you see this problem on https://mozilla.github.io/pdf.js/web/viewer.html?file=https://static.app-elly.fr/test-bug-pdf-viewer.pdf as well, there's nothing we can do, unfortunately. Mozilla's PDF viewer is the "golden standard" for what can be achieved with pdfjs-dist, so if the problem exists there, it's extremely likely it's gonna exist on out side, too.
