### ISSUE TITLE
PDF is rendered twice

### ISSUE THREAD

**Issue by AndreasPresthammer** [wojtekmaj/react-pdf#1292]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

PDF for a single page is rendered twice:

![image](https://user-images.githubusercontent.com/328539/213003210-0808fe14-73f3-4b37-ad45-2ec9a1afed63.png)

the actual first page should look like this:

![image](https://user-images.githubusercontent.com/328539/213003472-223d06d1-2eff-4695-bd33-57a7787b2c4d.png)

Link to actual pdf:

https://www.africau.edu/images/default/sample.pdf

### Steps to reproduce

I've created a minimal repro of the issue in this github repo: https://github.com/AndreasPresthammer/react-pdf-repro

See: https://github.com/AndreasPresthammer/react-pdf-repro/blob/master/src/App.tsx for the relevant implementation.

Run `npm start` to start it.

### Expected behavior

Should not render the content twice.

### Actual behavior

Renders the content twice.

### Additional information

I load the content using blob (see repro for details). This might (?) be relevant. 

Furthermore this approach worked fine in react-pdf@5.7.2. This issue seem to be introduced in version 6 and higher.

### Environment

- **Browser (if applicable)**: Chrome Version 109.0.5414.75 (Official Build) (64-bit)
- **React-PDF version**: 6.2.2
- **React version**: 18.2
- **Webpack version (if applicable)**:

**Comment by glaserL** [comment]
I experieced this as well, tried to downgrade a few minor versions and then I saw this output: 


```
Warning: TextLayer styles not found. Read more: https://github.com/wojtekmaj/react-pdf#support-for-text-layer
Warning: AnnotationLayer styles not found. Read more: https://github.com/wojtekmaj/react-pdf#support-for-annotations
```

Basically adding 
```typescript
import 'react-pdf/dist/esm/Page/TextLayer.css';
```

fixed this. See also the PR in your repo where you reproduced the behaviour:
https://github.com/AndreasPresthammer/react-pdf-repro/pull/1

**Comment by aarowman** [comment]
@glaserL yes, I think that's the issue. I had a similar issue, but it was just rendering the TEXT below the pdf. After adding that import (as the README describes), it seemed to work fine. Another option is to remove text rendering with `renderTextLayer={false}`

I had a PDF with an image and text, but only the text showed (not the image), so that was my clue.

**Comment by ncordin** [comment]
Same issue here. The problem with those 2 fixes is there will be white space where the text was supposed to be.

**Comment by ncordin** [comment]
> 
Thanks !
We also need to import the second css file, otherwise pages will be separated by white spaces (placeholder of text layer).

So the complete fix:

```
import 'react-pdf/dist/esm/Page/TextLayer.css'
import 'react-pdf/dist/esm/Page/AnnotationLayer.css'
```

**Comment by aarowman** [comment]
No, after you import the css or turn text rendering off, it shows up with
correct sizing. It did for me (both options)

**Comment by wojtekmaj** [comment]
Just for the official record @glaserL and @ncordin are totally right that this is the case of missing CSS imports. Closing this :) Happy coding.

**Comment by Nazil-ashraf** [comment]
{Array.from(new Array(numPages), (el, index) => (
      <Page
        renderTextLayer={false}
        renderAnnotationLayer={false}
        customTextRenderer={false}
        key={`page_${index + 1}`}
        className="pdf-page"
        pageNumber={index + 1}
      />
    ))}
    by adding
        renderTextLayer={false}
        renderAnnotationLayer={false}
        customTextRenderer={false}. , fixed my issue and working fine

**Comment by franshuyadav** [comment]
Late to the thread, but on adding renderAnnotationLayer={false}, the scale attribute of Page stops working. Anyone found a workaround for that?
