### ISSUE TITLE
pdf with no password is asking for password

### ISSUE THREAD

**Issue by NikhilAgarwal05** [wojtekmaj/react-pdf#1293]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Uploaded a normal pdf file with no password, when trying open that pdf file using react-pdf then asking for password

### Steps to reproduce

Uploaded a normal pdf file with no password, when trying open that pdf file using react-pdf then asking for password

### Expected behavior

This pdf should not ask for password

### Actual behavior

Asking for password

### Additional information

May convert a photo into pdf and then try, or with normal pdf

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by NikhilAgarwal05** [comment]
react-pdf version using -  "version": "5.7.2",

**Comment by wojtekmaj** [comment]
Please provide reproducible example, otherwise I'm not able to help you.
