### ISSUE TITLE
Access to fetch at 'api.domain.com' from origin 'domain.com' has been blocked by CORS policy

### ISSUE THREAD

**Issue by Tokke93** [wojtekmaj/react-pdf#1294]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When fetching the pdf from a remote URL instead of through an import, CORS errors show up.

`<Document file={link} onLoadSuccess={onDocumentLoadSuccess}>
            ...
          </Document>`

pdf-worker is loaded this way:
 `pdfjs.GlobalWorkerOptions.workerSrc = '//unpkg.com/pdfjs-dist@${pdfjs.version}/legacy/build/pdf.worker.min.js';`

I don't think this could be a server issue because I was able to render the pdf by using a default html object like so:
`<object  data={link} type="application/pdf">
          <embed src={link} type="application/pdf" />
 </object>`
 

### Steps to reproduce

Use the following code:

```
import { Document, pdfjs } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = '//unpkg.com/pdfjs-dist@${pdfjs.version}/legacy/build/pdf.worker.min.js';

const ReactComponent = () => {

  const [numPages, setNumPages] = useState<number>(0);

  function onDocumentLoadSuccess({ numPages }: { numPages: number }) {
    setNumPages(numPages);
  }

  return (
    <Document file={remote_url.pdf} onLoadSuccess={onDocumentLoadSuccess}>
         {numPages > 0 && (
         <>
            {[...Array(numPages)].map((_, pageNumber) => (
                <Page pageNumber={pageNumber} />
            ))}
         </>
         )}
     </Document>
  )
}
```

### Expected behavior

No CORS errors

### Actual behavior

Getting CORS error:
`Access to fetch at 'http://api.domain.com' from origin 'http://domain.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

### Environment

- **Browser (if applicable)**: Google Chrome Version 109.0.5414.87 (Official Build) (x86_64)
- **React-PDF version**: "^5.0.0",
- **React version**: "16.12.0",
- react-scripts: "4.0.3"

**Comment by wojtekmaj** [comment]
That is expected browser behavior and has nothing to do with React-PDF itself.

Read more: https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions#when-im-trying-to-load-a-pdf-file-from-an-external-source-im-given-a-message-failed-to-load-pdf-file

**Comment by RamuEdupa** [comment]
add cors extension in the browser and check after setup
