### ISSUE TITLE
Page doesn't render pdf if IDM extension is enabled

### ISSUE THREAD

**Issue by shahriarhossain** [wojtekmaj/react-pdf#1296]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

If I have the "internet-download-manager (IDM)" extension enabled, then my browser doesn't render pdf. I believe this could be the case for many others as well. I was wondering If there is any recommended way for such a scenario. 

### Steps to reproduce

1. Enable "IDM Integration Module"
![image](https://user-images.githubusercontent.com/6463320/213951714-b2c9589d-cd97-445c-928d-88cebfb5d1af.png)

2. Visit any website where react-pdf has been used to render pdf.

3. It does not show anything on the page

4. You get "Failed to load resource: net::ERR_BLOCKED_BY_CLIENT" error. 
![image](https://user-images.githubusercontent.com/6463320/213951869-d63cab52-cdc9-478b-b18d-1166977b2896.png)

### Expected behavior

Expecting the viewer will render the pdf like this:
![image](https://user-images.githubusercontent.com/6463320/213951971-2f5bb8da-4e1b-48db-9804-0d745a162e8c.png)

### Actual behavior

1. It does not show anything on the page
![image](https://user-images.githubusercontent.com/6463320/213951825-d0f2e38d-6a2a-47bc-a9d1-79a592d8fedb.png)

2. In the console I see the following error: 
"Failed to load resource: net::ERR_BLOCKED_BY_CLIENT" error. 
![image](https://user-images.githubusercontent.com/6463320/213951869-d63cab52-cdc9-478b-b18d-1166977b2896.png)

### Environment

- **Browser (if applicable)**: chrome 109
- **React-PDF version**: ^6.2.2
- **React version**: ^18.2.0
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
It's hard to deal with extensions that are tampering with browser behavior. I would recommend writing to their support as it seems to start falling apart from their script crashing (screen.js is not React-PDF's thing).
