### ISSUE TITLE
Can't load pdf using example code?

### ISSUE THREAD

**Issue by osaesm** [wojtekmaj/react-pdf#130]
Hi,

I was using the example code to see if I had set up everything correctly, but on my website, I get this error: "Failed to load PDF file." I'm not sure if I've misread the set up or something and was wondering if you know why the example code might not be working.

Thanks!

**Comment by wojtekmaj** [comment]
Hey @osaesm,
if you handle errors using `onLoadError`/`onSourceError` callbacks, you can get much more info about what happened. The errors should also be seen in the console once you open development tools in your browser. You should be able to tell what's wrong by reading the detailed message, but in case it's still not clear, I'll be there to help ;)

**Comment by osaesm** [comment]
Sorry if this is a basic issue (I'm pretty new to react and web dev in general) but it's giving me the message "Invalid PDF Structure". Do I have to feed the PDF file in base64 or is a reference to the file itself fine?

**Comment by wojtekmaj** [comment]
Reference is fine, if valid of course. See #123 which was the same or similar problem.

Most likely you're getting error 404 because the address is not valid.
