### ISSUE TITLE
Styling not applied to child elements within View render callback

### ISSUE THREAD

**Issue by physicsboy** [wojtekmaj/react-pdf#1300]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Rendering a component with child and grandchild elements via the View render callback caused styling issues to appear that aren't present when rendering the component in the traditional way (not via a View render callback), showing no margin, padding, border radius or font styling on the child or grandchild. Note: Styling for the grandchild <Text> element was included in the main container.

### Steps to reproduce

1. Create a component with <View> main element, a  <View> child and  <Text> grandchild
2. Pass a style object to the top level that contains `color` for styling the grandchild text and pass a style object for the child <View> with either padding or margin that is defined with a string (ie. `padding: '6px 12px'`)
3. Render the component in the standard React way: `<Component />` and then again as the result of a render callback:
```
<View render={() => <Component />} />
```

### Expected behavior

A compoent containing child and grandchild components each containing styling around fonts, margin and padding that renders correctly on its own should also render correctly when the result of a View render callback prop.

### Actual behavior

Components returned from a <View> render callback appear to have CSS properties such as font, fontWeight, fontSize, borderRadius dropped from child/grandchild elements and require redefining or changing to a different format. See additional information for full explanation and my workaround.

### Additional information

# Issue
CSS is missing when returning a component via the View render callback

# Background
I created a table header row component with a container (row), child (column) and a grandchild (cell) with associated styling such that I defined the `color`, `fontSize` and `fontWeight` in the object given to the row, not the cell, as this would work in traditional CSS.
```
const TableHeaders = () => (
  <View style={styles.row}>
    <View style={styles.column}>
        <Text>Label</Text>
    </View>
  </View>
);

const styles = {
   column: {
    margin: '0 50px',
  },
  row: {
    fontSize: 10,
    color: 'red',
    flexDirection: 'row',
    backgroundColor: 'lightblue',
    borderRadius: 4,
    margin: '2px 0',
    padding: '10px 7px'
  }
}
```
This works perfectly when rendering the Component in the traditional way as a standard child of the main document page
```
<Document>
    <Page style={styles.body}>
       <TableHeaders />
    </Page>
</Document>
``` 
![image](https://user-images.githubusercontent.com/25344133/214939676-309f1f13-416f-4761-8b4e-fd190a8bb673.png)

However, when including the `TableHeaders` component via the return of a View `render` prop callback, it appears that some of the styling is dropped
```
<Document>
    <Page style={styles.body}>
      <View render={() => <TableHeaders />} />
    </Page>
  </Document>
```
![image](https://user-images.githubusercontent.com/25344133/214939891-1e92ced1-eedc-42d6-9610-7c8790761459.png)

# Investigation results, solutions & "workarounds"
## Font
Anything related to styling the final <Text> element such as `fontSize`, `fontWeight`, `color` **needs** to go in a style object connected to that element. It **cannot** live further up the tree attached to a container like traditional CSS. I found that I needed to redefine `fontFamily` down here also.

## Margin and Padding
I had been applying my margins and paddings via strings that mirrored how I would apply this in CSS, ie: `[margin|padding]: "[vertical]px [horizontal]px"`, however I found that breaking these into their own constituent parts such that they could be defined with numbers instead did the trick:
**before**
```
margin: '2px 0',
padding: '10px 7px'
```
**after**
```
marginTop: 2,
marginBottom: 2,
paddingTop: 10,
paddingBottom: 10,
paddingLeft: 7,
paddingRight: 7
```
This was a similar issue for the `borderRadius` in the Repl editor, needing to break it down to `border[Top|Bottom][Left|Right]Radius`.

**Final result**
![image](https://user-images.githubusercontent.com/25344133/214942659-b9f9d57a-6ee4-437c-802b-d904a7202e19.png)

## [Final Repl with workarounds](https://react-pdf.org/repl?code=3187b0760ce02e00402a043011806c0a6009342026681384300bc300140250901f390140c8cc00f22a9a0128803bb50d3035b274018440a00ae016cc3500ca20a5a182991a14cc03d1b51e3a6cfe8cb4ece3cf8500dc74ea848b04d76e25c806f60002c0258a1cf8d18005f2a625a327e6600354f342768004f74621778f408003a7c1e00ea372f1f3f40ad2898f32b1b706878613411751467325cef5f7f209a7a233834000f5814b424fef4e03aeca6fcd6e31ea852eb5b4a9331491906f196c0e0d0f0e2d8a80481e4bdd4b4d065c0be4145ba9c8f668280e36ada94140b964d1dd9b98ad80045094f37440506529128ed3091800222060349fc33430b0000a080039b29fa83239a1d248100e0e2d924675aa585c010889a37a0876300019a02d03818014f0f824b82422c13393d954ea00460d4ab20934a88c5bcb430b8528c088cb37cec3021b385cfc118bc005c3075409e9e0281c93c002f340ea008c0006000d1234e207c0ea00e47e1c33bf8013b6314efa1d5ea9852043e0d19e3000064d0f4a80ea00acdec0f0743600e278d1ee18cc1639e84e65b8fea47e3f0ecb8080000e91e8c71709e0904075001604e308b25f2ea7d3506ace16bf5981370b8ef640085815045256bb35bae379b3056c11475071d483b19eeef76748fa7a1ba50cf1f980504f3805d79e75ce900860001acd19909180704b474ba50698cea024680bd228321b0d4b32c7500098e77fd9325c57502e732d701ecc034480cb56d244e09c010b44a0c5050d83e0b0cd149c75001d8f08c208b5d33622737e1f14240b011d0cc390980006678cd0fc310ec2a41d400360e318ae2d10c11d5350d040501d5d884c023a002328386c08f644a1000c4327f1d9321987f901605946a5152000)

# Request
Can it please be made such that any working CSS like we had in the initial component still works when being brought back via the render process?

### Environment

React-pdf website Repl

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
