### ISSUE TITLE
Can't resolve 'react-pdf/dist/esm/Page/TextLayer.css'

### ISSUE THREAD

**Issue by Pitbouyaaaa** [wojtekmaj/react-pdf#1309]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I am able to view the PDF, but I am unable to copy the content from it. As per the documentation, I tried adding a TextLayer like this:

`import 'react-pdf/dist/esm/Page/TextLayer.css`

However, I am getting an error. Although I am not using the AnnotationLayer, I imported it as well:

`import 'react-pdf/dist/esm/Page/AnnotationLayer.css';`

But I am not getting any error for AnnotationLayer."

### Steps to reproduce

This is how the code looks now

import React, { useState } from 'react';
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';
import 'react-pdf/dist/esm/Page/TextLayer.css';

function News(props) {

  const [numPages, setNumPages] = useState(null);
	const [pageNumber, setPageNumber] = useState(1);

	const onDocumentLoadSuccess = ({ numPages }) => {
		setNumPages(numPages);
	};

	const goToPrevPage = () =>
		setPageNumber(pageNumber - 1 <= 1 ? 1 : pageNumber - 1);

	const goToNextPage = () =>
		setPageNumber(
			pageNumber + 1 >= numPages ? numPages : pageNumber + 1,
		);

	return (
		<div>
			<nav>
				<button onClick={goToPrevPage}>Prev</button>
				<button onClick={goToNextPage}>Next</button>
				<p>
					Page {pageNumber} of {numPages}
				</p>
			</nav>

			<Document
				file="document.pdf"
				onLoadSuccess={onDocumentLoadSuccess}
			>
				<Page renderTextLayer={true} renderMode="svg" pageNumber={pageNumber} />
			</Document>
		</div>
	);
}

export default News;`

### Expected behavior

No error and ability to copy text from PDF

### Actual behavior

Getting missing module error

### Additional information

i have tried installing react-pdf multiple times even by removing package.json.lock. Can't still resolve it

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: ^5.3.2
- **React version**:"^17.0.2",
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
You're using React-PDF 5.3.2 while referring to React-PDF v6 documentation. There's no TextLayer.css in v5.
