### ISSUE TITLE
onMouseEvents

### ISSUE THREAD

**Issue by nnnikolay** [wojtekmaj/react-pdf#131]
Hi Wojciech,

First of all, thanks for the component and sharing it with us!

Well, I would like to use your component in my app with the following use case:
When pdf page rendered, the user moves his mouse over any part of the Page and start
drawing a rectangle (like block selection in some text editors), which I call TextBox. 

For that I need following events to be passed down:

```
                  <Page
                    onMouseDown={this.startDrawingTextBox}
                    onMouseUp={this.finishDrawingTextBox}
                    onMouseMove={this.keepDrawingTextBox}
                 ...
```

but when I use the code above nothing happens, is it possible to use them? 

Thanks

**Comment by wojtekmaj** [comment]
Hey @nnnikolay, do you still need assistance?

**Comment by nnnikolay** [comment]
@wojtekmaj Thanks, for this issue it was my bad :-)
