### ISSUE TITLE
PDF not showing in different browsers

### ISSUE THREAD

**Issue by abedshaaban** [wojtekmaj/react-pdf#1318]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

pdf is not loading in some applications because of application version incompatibility, what do you think I should do to fix this problem? Most of my users are on old applications and cannot update or change them.

### Steps to reproduce

none

### Expected behavior

load pdf properly

### Actual behavior

the loading and rendering of a pdf doesn't show in the browser

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Closing - missing all required information
