### ISSUE TITLE
Highlight sections in a PDF

### ISSUE THREAD

**Issue by nikolayg** [wojtekmaj/react-pdf#132]
Hi there,

This library looks very promising - thank you for efforts?

Does it support programmatic highlighting (e.g. with yellow background) of parts of the viewed PDF? If so, can you please point me to some documentation or sample code?

Cheers,
Nik

**Comment by wojtekmaj** [comment]
Hey @nikolayg, thanks for asking! I investigated.

Annotation highlight is fully supported, check out this document: [annotation-highlight.pdf](https://github.com/wojtekmaj/react-pdf/files/1649802/annotation-highlight.pdf) using [test suite](http://projekty.wojtekmaj.pl/react-pdf/test/).

Highlighting custom text (i.e. search phrase) is definitely possible in PDF.js, but not implemented in React-PDF just yet. I think it's a neat idea tough - I'm adding it on my list!

**Comment by nikolayg** [comment]
Thank for your answer! 

Could you please point me to documentation or sample code used for this annotation?

**Comment by wojtekmaj** [comment]
Annotation highlight - check PageAnnotations component.
Highthing search queries - the easiest way to see Mozilla's implementation is by searching in PDF file in Mozilla Firefox.

**Comment by wojtekmaj** [comment]
Hi @nikolayg, thanks to #163 you should be able to implement highlighting using customTextRenderer prop. If you need inspiration, [a component which you may use to mark words in the text can be found in my another project](https://github.com/wojtekmaj/facebook-comment-scraper/blob/master/src/components/_common/Mark.jsx) (hmmm, I should make it into a package...)

The feature was first introduced in v3.0.0-beta and you can test it out by using `npm install react-pdf@next` or `yarn add react-pdf@next`. If anything goes wrong, let me know in #143.

**Comment by wahlforss** [comment]
> Annotation highlight - check PageAnnotations component.
> Highthing search queries - the easiest way to see Mozilla's implementation is by searching in PDF file in Mozilla Firefox.

@wojtekmaj Hey could you elaborate on this? How would I implement programmatical search and highlight?

**Comment by wojtekmaj** [comment]
@wahlforss See #132, #212, #235.

**Comment by AnjaliPatodia** [comment]
on selecting text the content is highlighted with shadow. 
Please help id any knows the solut
![pdf hightlight](https://user-images.githubusercontent.com/57519075/101759604-d0422780-3aff-11eb-9958-70bf406d8028.png)
ion

**Comment by Akaban** [comment]
Hello @AnjaliPatodia,

In my case I solved the issue by disabling some CSS rules, more information here #727
