### ISSUE TITLE
SVG mode svg:tspan missing text

### ISSUE THREAD

**Issue by liujunbo1988** [wojtekmaj/react-pdf#1322]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

This happens on some Android 9 phones

Please look at Actual behavior， I uploaded a picture to show the problem. 

The location to display the text is currently blank，Only one or two words in a line are displayed correctly

Switch renderMode to canvas will also cause same errors 

### Steps to reproduce

See error

### Expected behavior

Just show all text

### Actual behavior

![WechatIMG90](https://user-images.githubusercontent.com/27808651/217200821-dab7a5d7-7dd4-40ca-bffc-e8b68a889fd0.jpeg)

### Environment

- **Browser (if applicable)**: Android System WebView 68.0.3440.91
- **React-PDF version**: 5.7.2
- **React version**: 17.0.1
- **Webpack version**: 4.29.6

**Comment by wojtekmaj** [comment]
SVG mode is considered unstable, unsupported, and as per docs you use it at your own risk. I may look into your case if you provide a reproducible CodeSandbox with [react-pdf v6 template](https://codesandbox.io/p/sandbox/react-pdf-ugh4nx).

**Comment by liujunbo1988** [comment]
I tried to run your sample project in chrome (version 68), The result is the same as picture shown in this link https://github.com/wojtekmaj/react-pdf/issues/864#issuecomment-963883111 . and this comment https://github.com/wojtekmaj/react-pdf/issues/864#issuecomment-965746649 gets the point。

I tried [mikecousins](https://github.com/mikecousins)/[react-pdf-js](https://github.com/mikecousins/react-pdf-js)，
'pdfjs-dist": "2.1.266" works fine in chrome (version 68)

**Comment by tacomanator** [comment]
Here is another sample file which was generated by exporting a note from Apple Notes. English text shows; Japanese text missing. Is this the same issue? The Japanese characters are not present/visible in the inspector at all.

File: [AEIOU.pdf](https://github.com/wojtekmaj/react-pdf/files/10985258/AEIOU.pdf)

PDF in Preview on Mac (also works on Windows, etc.):

<img width="708" alt="スクリーンショット 0005-03-16 8 04 37" src="https://user-images.githubusercontent.com/63794/225464303-4075f005-b401-4598-b0ba-56ad5cb100c7.png">

Issue as reproduced on [test page](https://projects.wojtekmaj.pl/react-pdf/test/):

<img width="1082" alt="スクリーンショット 0005-03-16 8 05 02" src="https://user-images.githubusercontent.com/63794/225464320-4198c4e0-896e-444f-a020-96601b8daf03.png">

**Comment by tacomanator** [comment]
My bad. I had not noticed the docs section about cMaps for non-latin character support. [Loading from an external CDN](https://github.com/wojtekmaj/react-pdf/blob/a7796bbb544256f95ad2ac315a2f8a10696b2aa4/README.md#setting-up-react-pdf) solved the problem. Presumably it would also work on the test page.
