### ISSUE TITLE
structuredClone is not defined running tests

### ISSUE THREAD

**Issue by alejouribesanchez** [wojtekmaj/react-pdf#1326]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When I try to run unit tests for react-pdf  I get the issue
 DocumentComponent Error ReferenceError: structuredClone is not defined
        at LoopbackPort.postMessage (/Users/alejo/react-pdf/create-react-app-5/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/api.js:1964:13)
        at MessageHandler.sendWithPromise (/Users/alejo/react-pdf/create-react-app-5/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/shared/message_handler.js:199:19)

### Steps to reproduce

I tried to integrate unit tests to the Example project: 

https://github.com/wojtekmaj/react-pdf/tree/main/sample/create-react-app-5

To be able to achieve that was necessary to add this to the package.json

```
  "devDependencies": {
    "@testing-library/react": "^13.4.0"
  },
  "jest": {
    "moduleNameMapper": {
      "^react-pdf": "react-pdf/dist/esm/entry.jest"
    },
    "transform": {
      "^.+\\.(js|jsx)?$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "node_modules/?!(@react-pdf)"
    ]
  }
```

But after run the test with the command line  `react-scripts test --env=jsdom --watchAll=false --coverage`
```
import { render, screen, act, waitFor } from '@testing-library/react';
import Sample from './Sample';

test('renders pdf container', async () => {
    await act(() => render(<Sample/>));
    const pdfContainer = screen.findByTestId("pdf-container");
    waitFor(() => expect(pdfContainer).toBeVisible());
});
```
I got the issue Error ReferenceError: structuredClone is not defined

```
  console.log
    DocumentComponent Error ReferenceError: structuredClone is not defined
        at LoopbackPort.postMessage (/Users/alejo/react-pdf/create-react-app-5/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/api.js:1964:13)
        at MessageHandler.sendWithPromise (/Users/alejo/react-pdf/create-react-app-5/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/shared/message_handler.js:199:19)
        at _fetchDocument (/Users/alejo/react-pdf/create-react-app-5/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/api.js:497:48)
        at /Users/alejo/react-pdf/create-react-app-5/node_modules/pdfjs-dist/build/webpack:/pdfjs-dist/build/pdf/src/display/api.js:413:31
```

### Expected behavior

I expected to get onLoadSuccess={onDocumentLoadSuccess}

### Actual behavior

 onLoadError={(error) => console.log("DocumentComponent Error", error)}

### Additional information

[create-react-app-5.zip](https://github.com/wojtekmaj/react-pdf/files/10711390/create-react-app-5.zip)

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Are you running Node 16 or older? structuredClone was added in 17 and thus is supported in latest LTS. On older versions you may need to set up a polyfill.

https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

**Comment by alejouribesanchez** [comment]
I am running  node 19

**Comment by VMarsola** [comment]
Any updates on this issue ? I'm facing the same problem
