### ISSUE TITLE
Page annotations makes SSR crash  

### ISSUE THREAD

**Issue by TriPSs** [wojtekmaj/react-pdf#133]
Hi,

I get the following error when trying to load the component on the servers side.

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    in Resolver
  app:esc:server:universal:server:error   TypeError: Cannot read property 'toLowerCase' of undefined
  app:esc:server:universal:server:error
```

If i remove [this line](https://github.com/wojtekmaj/react-pdf/blob/master/src/PageAnnotations.jsx#L4) the code works as expected. 

Is there a way for me to solve this?

**Comment by TriPSs** [comment]
When i stop my server i also get the following error:

```
ReferenceError: window is not defined
    at /node_modules/pdfjs-dist/lib/web/ui_utils.js:391:3
    at Promise (<anonymous>)
    at Object.<anonymous> (/node_modules/pdfjs-dist/lib/web/ui_utils.js:390:24)
    at Module._compile (module.js:573:30)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/pdfjs-dist/lib/web/dom_events.js:29:17)
    at Module._compile (module.js:573:30)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:507:32)
```

**Comment by wojtekmaj** [comment]
Hello @TriPSs,
regarding the first issue, you have to handle importing CSS files using some loader. If you're using Webpack, you can use null-loader if you want a CSS file to be ignored server-side. This CSS is crucial though for annotations to work, so I doubt there would be another way around this.

Regarding the second issue, I'll need to investigate more, stay tuned.

**Comment by TriPSs** [comment]
@wojtekmaj Thanks for answering, i have the following css loader configured:
https://github.com/tripss/react-esc/blob/master/src/build/webpack.config.server.js#L34

https://github.com/tripss/react-esc/blob/master/src/build/webpack.config.js#L14

**Comment by wojtekmaj** [comment]
That looks okay to me.

The error states `TypeError: Cannot read property 'toLowerCase' of undefined` so I looked for `toLowerCase` in both mine and your repositories and it seems [this](https://github.com/TriPSs/react-esc/blob/d71b769d5b11a86796f2d30718b0faa68237200e/src/client/modules/JSS/createGenerateClassName.js#L10) is the only place. So it seems your script that parses classNames is in conflict with that.

**Comment by TriPSs** [comment]
That is indeed what i thought to, that code is only executed at production env and is only for all JSS styling.

**Comment by wojtekmaj** [comment]
Hmmm. In that case, we'll need a better stack trace. I was trying to find out what "app:esc:server:universal:server:error" is, but I don't think that code is public :(

**Comment by TriPSs** [comment]
@wojtekmaj That peace of code can be found here:
https://github.com/TriPSs/react-esc/blob/master/src/client/modules/HandleError.js#L9

**Comment by wojtekmaj** [comment]
CSS are not automatically imported anymore as of [v3.0.0-alpha.3](https://github.com/wojtekmaj/react-pdf/releases/tag/v3.0.0-alpha.3). Let me know what you think!
