### ISSUE TITLE
The process stops when the iPhone loads two pages of a complex PDF.

### ISSUE THREAD

**Issue by unuz** [wojtekmaj/react-pdf#1338]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The process stops when the iPhone loads two pages of a complex PDF.

The first time it loads it's fine, but when I change state and reload the page the process stops.

Is there any way to solve this problem?

What the hell am I doing wrong?

This is my some code.

![image](https://user-images.githubusercontent.com/50819145/219530255-5580df9b-e51b-4ec8-ad91-3ae2867154f6.png)

### Steps to reproduce

Load the page.

Change state.

Repeat state change.

problem occurred

<img width="282" alt="F6CD52AE-B711-431A-9ADC-376463669373" src="https://user-images.githubusercontent.com/50819145/219527772-48993bb9-5e07-4c7f-89b8-63822cddf482.png">
<img width="282" alt="BC3CD443-2FDE-40FD-BC23-8777329F3A07" src="https://user-images.githubusercontent.com/50819145/219527775-23cdfa08-6ec5-4199-bdf8-f1469d5fd01f.png">
<img width="282" alt="02581C5C-C1AE-4CE7-92CB-B71176FB6A70" src="https://user-images.githubusercontent.com/50819145/219527783-d61cd5e8-e7cb-4444-b76a-70a83dc37a39.png">

<img width="1280" alt="스크린샷 2023-02-17 10 29 06" src="https://user-images.githubusercontent.com/50819145/219526764-929747cd-c53c-4c34-8448-67ead74f6f1f.png">

### Expected behavior

The page should render normally.

### Actual behavior

The page does not render and the process hangs.

### Environment

- **Browser (if applicable)**: safari, chrome, 
- **React-PDF version**: 6.2.0
- **React version**: 18.2.0
- **OS**: ios 16.2

**Comment by wojtekmaj** [comment]
See https://github.com/wojtekmaj/react-pdf/issues/1149#issuecomment-1323541137
