### ISSUE TITLE
PDF did't load in android webview

### ISSUE THREAD

**Issue by CoderAWei** [wojtekmaj/react-pdf#1339]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

My requirement is to preview PDF in both web and mobile( include Android and iOS) sides.
The web side and IOS are normal display, but when the page is embedded into android error will be reported.
> ``Uncaught ChunkLoadError: Loading chunk vendors-node_modules_react-pdf_esm_entry_webpack_js faild. (missing: http://xxx:3000/vendors-node_modules_react-pdf_esm_entry_webpack_js.chunk.js)``

The page is white. So I want to know what cause this question?

### Steps to reproduce

1. click file will go to pdf preview page
2. page becomes white, nothing shows.
3. Open the console to see the error message: ``Uncaught ChunkLoadError: Loading chunk vendors-node_modules_react-pdf_esm_entry_webpack_js faild. (missing: http://xxx:3000/vendors-node_modules_react-pdf_esm_entry_webpack_js.chunk.js)``

### Expected behavior

**Can display pdf normally like web side and iOS side.**

### Actual behavior

**White page, nothing shows!**

### Additional information

> error info:
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/85542563/219569111-b7736263-b9bb-49fc-ac95-1056d6a29587.png)

> network info:
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/85542563/219569247-3d9f2e98-add2-4511-99d1-6af6b1887afa.png)
you can see, this file can be find and load

### Environment

- **Browser (if applicable)**:  ``Chromium WebView 83``
- **React-PDF version**: ``6.2.2``
- **React version**: ``18.1.0``
- **Webpack version (if applicable)**: ``webpack 5``

**Comment by wojtekmaj** [comment]
Looks like the previous SyntaxError causes the error you're mentioning.

**Comment by Pswzy** [comment]
'你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。'

**Comment by Pswzy** [comment]
'你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。'

**Comment by Pswzy** [comment]
'你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。'

**Comment by Pswzy** [comment]
'你好。已收到你的邮件，我会在假期结束后尽快处理。————————————这是来自QQ邮箱的自动回复邮件。'
