### ISSUE TITLE
InvalidPDFException

### ISSUE THREAD

**Issue by nikolayg** [wojtekmaj/react-pdf#134]
I'm getting `InvalidPDFException` on every PDF that I try with. For example this one - http://gahp.net/wp-content/uploads/2017/09/sample.pdf

The error message is:

```
InvalidPDFException {name: "InvalidPDFException", message: "Invalid PDF structure"}
```

I use React 16 and my code is pretty much the same as the example from the README:

```
import { Document, Page } from 'react-pdf/build/entry.noworker';

...

<Document
    file="/Users/nikolay/Desktop/sample.pdf"
    onLoadSuccess={() => alert('!!')}
>
    <Page pageNumber={1} />
</Document>
```

What am I doing wrong?

**Comment by nikolayg** [comment]
I did more experiments.

It works with a URL, when the URL matches my server (i.e. avoiding CORS issues).

How can I make it work with files on other remote servers (i.e. CORS) or local file system files?

**Comment by wojtekmaj** [comment]
For that, you'd need to set up CORS proxy server. Although original content providers might not be very happy about that.
