### ISSUE TITLE
Scrolling/Focusing on a Page

### ISSUE THREAD

**Issue by nikolayg** [wojtekmaj/react-pdf#135]
Hi there,

The [sample code](https://github.com/wojtekmaj/react-pdf/blob/master/sample/Sample.jsx) shows how to load multiple pages. Given that all pages are rendered, how can we scroll to an individual page?

**Comment by wojtekmaj** [comment]
You have two options:

1. Use `document.querySelector` to find a page with specific [[data-page-number=n]](https://github.com/wojtekmaj/react-pdf/blob/master/src/Page.jsx#L342) element

2. Use [ref like in test suite](https://github.com/wojtekmaj/react-pdf/blob/master/test/Test.jsx#L162-L171).

**Comment by buddy-maguire** [comment]
could you please elaborate on this for me, i have a header that renders all the pages, each page wrapped in a button. below that i have rendered one page of the document, i wish to onClick setState pageNumber to the pageNumber of the specific page... here is the important part of the header...      ``` <Document
                    file={file}
                    onLoadSuccess={this.onDocumentLoadSuccess}
                  >
                    <Row
                      style={{
                        justifyContent: 'center',
                        overflow: 'auto',
                        height: '100%',
                        width: '100%'
                      }}
                    >
                      {Array.from(new Array(numPages), (el, index) => (
                        <button
                          onClick={this.changePage}
                          style={{
                            margin: '1px',
                            border: 'none',
                            height: '95%'
                          }}
                        >
                          <Page
                            scale={0.01}
                            key={`page_${index + 1}`}
                            pageNumber={index + 1}
                          />
                        </button>
                      ))}
                    </Row>
                  </Document> ```


here is the function....  ```  changePage(event) {
    console.log(event.target);
    this.setState({ pageNumber: event.target.pageNumber });
  } ```   


when i view the console log i see the data-page-number, and i have tried various things to get it to work, but no success...

**Comment by buddy-maguire** [comment]
> You have two options:
> 
>     1. Use `document.querySelector` to find a page with specific [[data-page-number=n]](https://github.com/wojtekmaj/react-pdf/blob/master/src/Page.jsx#L342) element
> 
>     2. Use [ref like in test suite](https://github.com/wojtekmaj/react-pdf/blob/master/test/Test.jsx#L162-L171).

could you please elaborate on this for me, i have a header that renders all the pages, each page wrapped in a button. below that i have rendered one page of the document, i wish to onClick setState pageNumber to the pageNumber of the specific page... here is the important part of the header... <Document file={file} onLoadSuccess={this.onDocumentLoadSuccess} > <Row style={{ justifyContent: 'center', overflow: 'auto', height: '100%', width: '100%' }} > {Array.from(new Array(numPages), (el, index) => ( <button onClick={this.changePage} style={{ margin: '1px', border: 'none', height: '95%' }} > <Page scale={0.01} key={`page_${index + 1}`} pageNumber={index + 1} /> </button> ))} </Row> </Document>

here is the function.... changePage(event) { console.log(event.target); this.setState({ pageNumber: event.target.pageNumber }); }

when i view the console log i see the data-page-number, and i have tried various things to get it to work, but no success...

**Comment by wojtekmaj** [comment]
That looks fine to me!
