### ISSUE TITLE
PDF not rendering correctly for some devices

### ISSUE THREAD

**Issue by abhikarsh-gupta** [wojtekmaj/react-pdf#1351]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Working with a very basic `
<Document 
file={{
              url: decodedUrl,
            }}
            onContextMenu={e => e.preventDefault()}
            onLoadSuccess={onDocumentLoadSuccess}
            className="pdf-viewer-container"
            onPassword={handlePassword}
          >
            {Array.from(new Array(numPages), (el, index) => (
              <div style={{ border: "1px solid black", marginBottom: "2vw" }}>
                <Page
                  key={`page_${index + 1}`}
                  pageNumber={index + 1}
                  width={pdfWidth} // pdfWidth = 800
                />
              </div>
            ))}
          </Document>`  setup.

Everything seems to be working perfectly on my device. but some users are reporting broken text, improper rendering of the text in the pdfs. 

I am unsure as to what is causing the issue. Apologies for formatting of code. 

Any help will be greatly appreciated

Attaching below images of error. 
<img width="751" alt="Screenshot 2023-02-21 at 5 37 42 PM" src="https://user-images.githubusercontent.com/111742827/220341057-47f7a78c-ac85-44bb-ab1a-a27e42f6506d.png">
<img width="729" alt="Screenshot 2023-02-21 at 5 37 54 PM" src="https://user-images.githubusercontent.com/111742827/220341090-0c9c78ac-0b75-4a2f-84c7-c2b24af3bd57.png">
<img width="733" alt="Screenshot 2023-02-21 at 5 38 07 PM" src="https://user-images.githubusercontent.com/111742827/220341102-5076496b-3e32-4d15-bd8d-c177f27c4006.png">

### Steps to reproduce

I don't have any clue right now. 

### Expected behavior

The pdfs should render with proper formatting irrespective of device. 

### Actual behavior

pdfs not rendering properly.

### Additional information

I cannot attach the file due to security and compliance reasons. 

### Environment

- **Browser (if applicable)**: chrome 109
- **React-PDF version**:  5.7.2
- **React version**: 17.0.2
- **Webpack version (if applicable)**:

**Comment by Roong-z** [comment]
It's a similar phenomenon.

I wrote it with a very basic syntax, and it only breaks the PDF area on certain devices (the whole galaxy s21).

I've checked all the issues, upgraded the version, checked the webpack settings, etc. but I couldn't solve it.

It would be great to know the cause of the problem.

My environment
Browser (if applicable) : chrome
React-PDF version : 5.2.0 & 5.7.2 & 6.2.2 All failed
React version : 17.0.2 & 18.2.0 All failed
Webpack version (if applicable) : 4,5 All failed

`<Document
                        className={"pdf-document"}
                        file={file}
                        onLoadSuccess={onDocumentLoadSuccess}
                        options={options}
                        // onClick={handleDocumentClick.bind(this)}
                        // style={{border: "3px solid blue"}}
                    >
                        <div
                            scale={scales}
                            style={{
                                width: 0,
                                height: 0,
                                position: "relative",
                                backgroundColor: "white",
                                opacity: 1,
                                border: 0,
                            }}
                        >
                            {pageLoadCompl && (
                                <CompInfoList
                                    onRemove={onRemove}
                                    onUpdate={onUpdate}
                                    docData={docData}
                                    pageData={pageData}
                                    handleBackdropClose={props.handleBackdropClose}
                                />
                            )}
                        </div>
                        {Array.from(new Array(numPages), (el, index) => {
                            return (
                                <Page
                                    key={`page_${index + 1}`}
                                    inputRef={
                                        pageNumber === index + 1
                                            ? (ref) => ref && ref.scrollIntoView()
                                            : null
                                    }
                                    pageNumber={index + 1}
                                    onRenderSuccess={onPageRenderSuccess}
                                    renderTextLayer={false}
                                    renderInteractiveForms={false}
                                    style={{border: "3px solid cyan"}}
                                    scale={scales}
                                />
                            );
                        })}
                    </Document>`

**Comment by codeskills-nl** [comment]
HI, some users mention the same problem here.
I found the following issue: https://github.com/mozilla/pdf.js/issues/14641 at pdf.js

**Comment by wojtekmaj** [comment]
This has been resolved in #1010 and released in v6.2.2.
