### ISSUE TITLE
Bundle crashes with fatal error after using reactpdfrenderer 3.0.1

### ISSUE THREAD

**Issue by sachin717** [wojtekmaj/react-pdf#1353]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Gulp bundle starts giving fatal error , when the vode is commented its working fine 
When i start to use any of the imports its start giving fatal error i.e heap out of memory
My node version is 10.17.0
React version is 16.8.5

### Steps to reproduce

Import react pdf rendere 
Use <pdfdownloadlink>
Use <document>

### Expected behavior

Bundle should work

### Actual behavior

Fatal error

### Environment

Chrome- **Browser (if applicable)**:
3.0.1- **React-PDF version**:
16.8.5- **React version**:
1.13.1- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
