### ISSUE TITLE
Single Page WIth Navigation Recipe Bug

### ISSUE THREAD

**Issue by willisplummer** [wojtekmaj/react-pdf#1363]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I think that there's an issue with the [recipe for a single page with navigation](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-single-page-with-navigation).

Based on my experience with it, each page is loaded only when it is rendered, so clicking the button to go to page two causes `onDocumentLoadSuccess` to fire and reset you back to page 1? Which makes it so you can't really view additional pages, right?

I fixed in my project by removing the `setPageNumber` call from `onDocumentLoadSuccess`

Does that make sense?

### Steps to reproduce

Copy the [recipe for a single page with navigation](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-single-page-with-navigation) and then click next page button

### Expected behavior

You see page 2

### Actual behavior

PDF flickers and then page number resets to 1

### Additional information

I'm using v 5.7.2 so maybe it's a change between 5 and 6 but I didn't see anything in the upgrade guide that indicated that it would be different.

### Environment

- **Browser (if applicable)**: chrome
- **React-PDF version**: 5.7.2
- **React version**: 16.8
- **Webpack version (if applicable)**: 4

**Comment by wojtekmaj** [comment]
Hmmm, I'm not able to reproduce:

![image](https://user-images.githubusercontent.com/5426427/236844621-1926d380-8e2c-4b2c-b570-9904e988018c.png)

**Comment by willisplummer** [comment]
I think it probably had to do with how I was fetching the pdf and some hooks causing the component to re-render and now I can't repro on a Create React App project. You can disregard thanks

**Comment by wojtekmaj** [comment]
Sure, thanks! If you stumble upon a reproducible case again, please share and I'll be happy to reopen and look into it.
