### ISSUE TITLE
Error: The `Array.prototype` contains unexpected enumerable properties: remove; thus breaking e.g. `for...in` iteration of `Array`s.

### ISSUE THREAD

**Issue by wcg-developers** [wojtekmaj/react-pdf#1369]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When I am viewing the pdf from the URL then it will throw that error 

![image](https://user-images.githubusercontent.com/43981192/223449027-c2ecf1d3-3a70-4cd4-a580-ab6232fea3c6.png)

And **version of the package** is below

**react-pdf:- 5.7.1
pdfjs-dist :- 2.12.313,
Node:- 14.21,
react: -17.0.2**

I have provided a link to pdf in your Document component after that when it's rendering, it will throw an error like this

### Steps to reproduce

- I have imported **Document, Page, pdfjs**  components from react-pdf
- I have provided a link of my pdf to the **Document** component's props as **file**
- I have also provided a Success and error function to that **Document** component

### Expected behavior

I think it will fetch the pdf data from the given URL and show it on my web page as it is 

### Actual behavior

It throws an error like above 

![image](https://user-images.githubusercontent.com/43981192/223451695-62870251-3305-41a0-9045-635b8c8ea65c.png)

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Hi! To have a look at this issue, I'll need a reproducible example. But first, I'll need you to update React-PDF to the latest version. I'm not able to support anything else than the latest version. Thanks!
