### ISSUE TITLE
customTextRenderer Highlighted text not highlighting properly

### ISSUE THREAD

**Issue by naveenApplikation** [wojtekmaj/react-pdf#1375]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Highlighted text was not covers the ui fully .[
![Screenshot 2023-03-09 at 7 25 50 PM](https://user-images.githubusercontent.com/116150603/224062905-314a67fd-090c-4ff6-8317-e8b29dc19290.png)
](url)

the text was halfly highlighted in some place.

### Steps to reproduce

1 : use pdf with same text , with different fontsize and weight
2 : search the text 
3 : you will see this issue

### Expected behavior

![Screenshot 2023-03-09 at 8 33 29 PM](https://user-images.githubusercontent.com/116150603/224065099-f7ed52f3-9cfd-4c32-a5a8-ff0b54d15e83.png)

### Actual behavior

![Screenshot 2023-03-09 at 8 34 49 PM](https://user-images.githubusercontent.com/116150603/224065468-5d196937-c4e7-4616-a00b-2bcf55b7fa7a.png)

### Environment

- **Browser (if applicable)*google chrome: 110
- **React-PDF version: 6.2.2
- **React version: 17.0.2
- **Webpack version (if applicable)**:

**Comment by walkingtospace** [comment]
+1 getting the same issue too

**Comment by evanhameed99** [comment]
+1 getting the same issue too

**Comment by evanhameed99** [comment]
I was getting the same issue, the scaling of the canvas and the text layer gets wrongly calculated after the `customTextRenderer` method is invoked. (The textLayer gets a scale of 1 which causes the offset). 

In my case, I did a small workaround to re render the pages after the customTextRenderer is fully invoked.

**Comment by wojtekmaj** [comment]
@johnn134 That was already an expectation, the migration was not meant to introduce any breaking changes, aside from highly recommended removal of external types, of course.

**Comment by wojtekmaj** [comment]
I believe this issue has been resolved already in v7.
