### ISSUE TITLE
Have a 504 error when getting `pdf.worker.js` using vite entry

### ISSUE THREAD

**Issue by Gu-Miao** [wojtekmaj/react-pdf#1377]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I create a simple demo, but it can't work. I use pnpm, vite@4, typescript.

My code: 

```tsx
import { useState } from 'react'
import { Document, Page } from 'react-pdf/dist/esm/entry.vite'
import type { DocumentProps } from 'react-pdf'

function App() {
  const [numPages, setNumPages] = useState(0)
  const [pageNumber] = useState(1)

  const onDocumentLoadSuccess: DocumentProps['onLoadSuccess'] = ({ numPages }) => {
    setNumPages(numPages)
  }

  return (
    <div>
      <Document file="/test.pdf" onLoadSuccess={onDocumentLoadSuccess}>
        <Page pageNumber={pageNumber} />
      </Document>
      <p>
        Page {pageNumber} of {numPages}
      </p>
    </div>
  )
}

export default App
```

I get a 504 error when getting the `pdf.worker.js`:

![image](https://user-images.githubusercontent.com/28031505/224597627-24a73036-0320-49b0-8005-dd3dbd7d5fc6.png)

In the `.vite` dir, the bundle is:

![image](https://user-images.githubusercontent.com/28031505/224597694-0dabdcb6-42d7-429b-8466-6a1a6858bde0.png)

I also tried this: https://github.com/wojtekmaj/react-pdf/issues/1148#issuecomment-1314180559. But it's not good for me.

By the way, the entry path in README is outdate. It's not `index.vite`, it's `entry.vite` now.

### Steps to reproduce

A minimal reproduction is here: https://github.com/Gu-Miao/react-pdf-test

### Expected behavior

Demo works fun

### Actual behavior

Get a 504 error when getting `pdf.worker.js`

### Environment

- **Browser (if applicable)**: Chrome 110
- **React-PDF version**: 6.2.2
- **React version**: 18.2.0
- **Vite version**: 4.1.4
- **Pnpm version**: 7.29.1

**Comment by itayper** [comment]
Having the same issue
Tried to lower version to 6.0.2 as to when it was solved.
https://github.com/wojtekmaj/react-pdf/issues/1148#issuecomment-1314180559 

Couldn't get it to work.

**Comment by EdenTurgeman** [comment]
Tried using it with vite 4 and got the same error. :(

**Comment by ChrisSamo632** [comment]
When I set an `onLoadError` event handler to display the `error.message` in a Vite setup (using the suggested `entry.vite` from the README.- note `entry` and **not** `index.vite`), I see the following returned:

> Setting up fake worker failed: "Cannot load script at: http://localhost:3000/node_modules/.vite/deps/pdfjs-dist/build/pdf.worker.js".

Looking in the `node_modules/.vite/deps` directory, there indeed isn't a `pdfjs-dist/` sub-directory (nevermind the rest). There is a `node_modules/.vite/deps/react-pdf_dist_esm_entry__vite.js` file (along with the same file with a `.maps` extension) - is this what should be referred to by `react-pdf` instead **or** is the required `pdf.worker.js` not being included in the `.vite/deps` as expected? In which case, where should it come from and how should it get here?

N.B. I've **not** included `pdfjs-dist` as an explicit dependency within `package.json` as `react-pdf` is using an old version (`2.x` rather than the current `3.x`) and keeping the two inline could be challening in future.

**Comment by snimstice** [comment]
请问解决了吗？

**Comment by idaibin** [comment]
Don't use `entry.vite`,  it works.
```js
import { Document, Page } from 'react-pdf';
import * as pdfjs from 'pdfjs-dist/build/pdf';
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.js',
  import.meta.url
);
```

**Comment by wojtekmaj** [comment]
Indeed it appears that because of https://github.com/vitejs/vite/issues/10839 Vite entry file does not behave correctly. If you guys have any idea how we could possibly implement this to make it work out of the box again, I'd be very grateful.

**Comment by ChrisSamo632** [comment]
Thanks @idaibin , while that didn't quite work for me it did lead me to implement one of the other `pdf.worker.js` setups from the README, like:

```js
import { Document, Page, pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;
```

which works both when running in `vite --mode localdev` mode and also when transpiling with `vite build` then serving the JavaScript through `nginx` (the `entry.vite` approach from teh README works for the latter but not the former, which is frustrating if developing a TypeScript app with `vite` then deploying to an `nginx` or similar server)

I suspect that the `import * as pdfjs from 'pdfjs-dist/build/pdf';` approach may require `pdfjs-dist` to be a dependency within the `package.json` (or using `vite.config.js` to put the file in the correct place for serving through the web server), but I'd rather avoid doing that so as not to keep that dependency inline with that of `react-pdf` (which is quite an old version now by the looks of it)

**Comment by Gu-Miao** [comment]
@idaibin thanks, it works for me.

First, my `react-pdf`'s version is `6.2.2`, so I need a `pdfjs-dist@2.16.105` in my `dependencies`. You can check it in `package.json` of your `react-pdf` package in `node_modules` directory.

My final code using typescript:

```tsx
import { useState } from 'react'
import { Document, Page } from 'react-pdf'
import * as pdfjs from 'pdfjs-dist'
import type { DocumentProps } from 'react-pdf'

const src = new URL('pdfjs-dist/build/pdf.worker.js', import.meta.url)
pdfjs.GlobalWorkerOptions.workerSrc = src.toString()
```

**Comment by wojtekmaj** [comment]
@Gu-Miao your solution is now actually the recommended one in v7 😅 See README for details.

**Comment by xavier-villelegier** [comment]
@Gu-Miao did you manage to make it work without having to _explicitly_ add `pdfjs-dist` as a deps? Having to keep it in sync with `react-pdf`'s own `pdfjs-dist` version is not very convenient when using things like dependabot 😕

So far I've tried to add `pdfjs-dist` in the `optimizeDeps.exclude` Vite config, but no luck. I also didn't find any way to tell to the package.json to use the same version as react-pdf deps

**Comment by athenacfr** [comment]
> pdfjs-dist



> @Gu-Miao did you manage to make it work without having to _explicitly_ add `pdfjs-dist` as a deps? Having to keep it in sync with `react-pdf`'s own `pdfjs-dist` version is not very convenient when using things like dependabot 😕
> 
> So far I've tried to add `pdfjs-dist` in the `optimizeDeps.exclude` Vite config, but no luck. I also didn't find any way to tell to the package.json to use the same version as react-pdf deps

If you're using vite you can import the worker url (no need to add it as a dependency, since `react-pdf` already has it as its dependency).

This solution is actually the same shown in documentation, the only difference is that vite will handle getting the right url path.

```ts
import { pdfjs } from 'react-pdf'
import pdfWorkerURL from 'pdfjs-dist/build/pdf.worker.min?url'

pdfjs.GlobalWorkerOptions.workerSrc = new URL(pdfWorkerURL, import.meta.url).toString()
```

**Comment by yaswanthmaddula-sureify** [comment]
> > pdfjs-dist
> 
> > @Gu-Miao did you manage to make it work without having to _explicitly_ add `pdfjs-dist` as a deps? Having to keep it in sync with `react-pdf`'s own `pdfjs-dist` version is not very convenient when using things like dependabot 😕
> > So far I've tried to add `pdfjs-dist` in the `optimizeDeps.exclude` Vite config, but no luck. I also didn't find any way to tell to the package.json to use the same version as react-pdf deps
> 
> If you're using vite you can import the worker url (no need to add it as a dependency, since `react-pdf` already has it as its dependency).
> 
> This solution is actually the same shown in documentation, the only difference is that vite will handle getting the right url path, which may be is necessary to work in different environments.
> 
> ```ts
> import { pdfjs } from 'react-pdf'
> import pdfWorkerURL from 'pdfjs-dist/build/pdf.worker.min?url'
> 
> pdfjs.GlobalWorkerOptions.workerSrc = new URL(pdfWorkerURL, import.meta.url).toString()
> ```

This is working fine in dev mode but in the build preview using vite, its not. Any idea on that ? @athenacfr

**Comment by anton-x-t** [comment]
This worked for me (React/Vite):
```
import { pdfjs } from "react-pdf";
import pdfWorker from "pdfjs-dist/build/pdf.worker.min.mjs?worker";
pdfjs.GlobalWorkerOptions.workerPort = new pdfWorker();
```

Sources:
What should be the value for workerSrc? 8305,
thank you Leung Yau Ming,
https://github.com/mozilla/pdf.js/issues/8305#issuecomment-1674973556

Importing Script as a Worker, vite.dev,
thank you helloworld3200 et al,  
https://vite.dev/guide/assets.html#importing-script-as-a-worker

Have a 504 error when getting pdf.worker.js using vite entry 1377,
thank you Athena Freitas,
https://github.com/wojtekmaj/react-pdf/issues/1377#issuecomment-2374304234

**Comment by anderskleve** [comment]
Still having trouble getting this worker script loading properly in my React app, using Vite.

Using the recommended import solution for the worker, and also trying the solution that @anton-x-t suggested, resulted in this error:

![image](https://github.com/user-attachments/assets/078e6ef9-d05d-4817-9fa0-0238b52257ae)

Vite: 4.5.5
react-pdf: 9.1.1 

Only solution that works for me is grabbing the worker from a CDN, which I guess is fine for now.

**Comment by athenacfr** [comment]
> Still having trouble getting this worker script loading properly in my React app, using Vite.
> 
> Using the recommended import solution for the worker, and also trying the solution that @anton-x-t suggested, resulted in this error:
> 
> ![image](https://github.com/user-attachments/assets/078e6ef9-d05d-4817-9fa0-0238b52257ae)
> 
> Vite: 4.5.5
> react-pdf: 9.1.1 
> 
> Only solution that works for me is grabbing the worker from a CDN, which I guess is fine for now.

It seems your server is not handling mjs/cjs a extensions properly, I had the same problem. If you use nginx you this should work:

```
types {
  # Extend application/javascript mime to include cjs and mjs
  application/javascript js cjs mjs;
}
```

**Comment by andretti1977** [comment]
> > Still having trouble getting this worker script loading properly in my React app, using Vite.
> > Using the recommended import solution for the worker, and also trying the solution that @anton-x-t suggested, resulted in this error:
> > ![image](https://private-user-images.githubusercontent.com/11349680/395489788-078e6ef9-d05d-4817-9fa0-0238b52257ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MDU3MTYsIm5iZiI6MTczNjUwNTQxNiwicGF0aCI6Ii8xMTM0OTY4MC8zOTU0ODk3ODgtMDc4ZTZlZjktZDA1ZC00ODE3LTlmYTAtMDIzOGI1MjI1N2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDEwMzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMWE2NGE3YWQ3ZWQ1NzVlYzQzYjBjNTM0ZmQ0YWU4NjI3NjZhY2EzYTIzNWI2ZTFhNjBhZTIwMTQyOWZhYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UHIfwiynUXQHt0qoh24DP-DUezY-eGVShl3a-C839-0)
> > Vite: 4.5.5
> > react-pdf: 9.1.1
> > Only solution that works for me is grabbing the worker from a CDN, which I guess is fine for now.
> 
> It seems your server is not handling mjs/cjs a extensions properly, I had the same problem. If you use nginx you this should work:
> 
> ```
> types {
>   # Extend application/javascript mime to include cjs and mjs
>   application/javascript js cjs mjs;
> }
> ```

**OH MY GOD!!!**

Thank you so much! I've tried all the possible solutions listed in this and related threads and this was the solution!!!

I'm using react-pdf 9.1.1 and vite 6.0.2 and using the documented approach everything worked well when developing but breaks when building and deploying it via docker on an nginx server with the same problem relative to handling mjs as octect-stream.
Had to create and copy over nginx a new mime.types file with the extended mime.type.

For other people reference:

**PDFPage.jsx**
```
//as documented on react-pdf documentation:
import {Page, Document, pdfjs} from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
    'pdfjs-dist/build/pdf.worker.min.mjs',
    import.meta.url,
).toString();
...
...
```

**Dockerfile**
```
FROM nginx:1.27.3-alpine AS prod
COPY ./dist /usr/share/nginx/html
COPY nginx.conf  /etc/nginx/conf.d/default.conf
COPY mime.types  /etc/nginx/mime.types
EXPOSE 3100
```

**mime.types**
```
types {
    text/html                                        html htm shtml;
    text/css                                         css;
    text/xml                                         xml;
    image/gif                                        gif;
    image/jpeg                                       jpeg jpg;
    application/javascript                           js cjs mjs;
    application/atom+xml                             atom;
    application/rss+xml                              rss;
    ...
    ...
```

**Comment by xxs3315** [comment]
> > Still having trouble getting this worker script loading properly in my React app, using Vite.
> > Using the recommended import solution for the worker, and also trying the solution that [@anton-x-t](https://github.com/anton-x-t) suggested, resulted in this error:
> > ![image](https://github.com/user-attachments/assets/078e6ef9-d05d-4817-9fa0-0238b52257ae)
> > Vite: 4.5.5
> > react-pdf: 9.1.1
> > Only solution that works for me is grabbing the worker from a CDN, which I guess is fine for now.
> 
> It seems your server is not handling mjs/cjs a extensions properly, I had the same problem. If you use nginx you this should work:
> 
> ```
> types {
>   # Extend application/javascript mime to include cjs and mjs
>   application/javascript js cjs mjs;
> }
> ```

what if without nginx? say just use mjs in GH Pages? I use the mjs worker from a CDN for now :-;
