### ISSUE TITLE
How to inline Image and Text next to each other. Using View Component

### ISSUE THREAD

**Issue by shai93** [wojtekmaj/react-pdf#1384]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Wanted to inline Image and Text next to each other. I try to wrap both inside Text component it is showing inline but the alignment of image is little weird. Image move to little upward doesn't align to text content.

### Steps to reproduce

[Repl](https://react-pdf.org/repl?code=3187b0760ce02e004d09e01b02984605e18194a4e5600b6592803a6002764043299002806f00a0618023100137802e1859b0090016da8500e6012cc3f00ac001800d2b18017c55b0252241443a0947e82d876ac0035848a2002b982e01844221015f80722820c778f9bd598d4012801b99823412160b841803061e95400780044e36c4590c0a000f954d9920015a82591f34d4d92005590003cf20b2a606beaf2b07d9060e81a5a01e96a1a2b9b0a0124c4ca609a461051d1184c472a01dca4b8a009783d14001cebfda696880c8c3c019814f63d0f2ad4d46f4c202981d000890ca0762178fafa011d6c520017980da3b5b3b1f4c052040cea46a0ec00b4103b06d1100467858881e06a32c20e41f3fdd87d11089107d001b253905c6035000ecc074750004cc00007032b872745c9d85c567b1d1004e4a40058d9ace4073a8a41d98024af181f586235690c6022371747a506480cda6aaaa1a864d03494cac3037a580996ca34c21100128d1805022aa40062a42a03990147a2c5804ea0000)

### Expected behavior

Text and Image should be inline also Image vertical alignment should be proper

### Actual behavior

Image vertical alignment is not proper when wrap inside Text component

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
