### ISSUE TITLE
Content rendering twice each page

### ISSUE THREAD

**Issue by aruljayaraj** [wojtekmaj/react-pdf#1385]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Here is the demo to reproduce this issue. 

[https://stackblitz.com/edit/react-9wseew?file=src%2FApp.js](https://stackblitz.com/edit/react-9wseew?file=src%2FApp.js)

### Steps to reproduce

Here is the demo to reproduce this issue. 

[](https://stackblitz.com/edit/react-9wseew?file=src%2FApp.js)

### Expected behavior

Loaded pdf without any error and duplicate content on each page. 

### Actual behavior

Loaded pdf with duplicate content on each page. 

### Environment

- **React-PDF version : 6.2.2**:
- **React version: 8.2.0**:

**Comment by raldred** [comment]
If you have textlayer enabled, you might be missing
```
import 'react-pdf/dist/esm/Page/TextLayer.css';
```

https://github.com/wojtekmaj/react-pdf#support-for-text-layer

**Comment by aruljayaraj** [comment]
![Screenshot 2023-03-17 at 8 08 47 PM](https://user-images.githubusercontent.com/414208/225936755-53da913a-208e-4ace-815d-1abfab892ec8.png)
Thanks @raldred Content repeat issue is fixed. But I got different issues. When opening the site on mobile, the pdf is not responsive even height is 100%, and didn't show all pages. 
Here is the link to test : [https://stackblitz.com/edit/react-zurgtz?file=src%2FApp.js](https://stackblitz.com/edit/react-zurgtz?file=src%2FApp.js)
