### ISSUE TITLE
Whether onLoadSuccess in Outline can get the pageNumber

### ISSUE THREAD

**Issue by crazyweeds** [wojtekmaj/react-pdf#1387]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

Whether onLoadSuccess in Outline can get the pageNumber

**Comment by wojtekmaj** [comment]
No it can't - Outline is Document wide.
