### ISSUE TITLE
Render of the text layer with the same font as the pdf.

### ISSUE THREAD

**Issue by TeoColuccio** [wojtekmaj/react-pdf#1404]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Is it possible to render the text layer above the canvas (or svg) with the same original font, so as not to create overlaps (visible on the screen)? 
![screen](https://user-images.githubusercontent.com/16000669/227516961-7065844a-1328-472f-80ad-45a08854b580.png)

This is because I noticed that only the sans-serif font-family is ever used for the text layer.
If you could get the original font name for each rendered span (or even in the single svg tag), that would be a lot.

### Steps to reproduce

Simply render a pdf and highlight text.

### Expected behavior

Render the text layer with the same fonts as the pdf (in my case LMRoman).

### Actual behavior

The text layer is always rendered using sans-serif.

### Additional information

opening the file directly with firefox (and therefore with pdfjs), I noticed that the text layer is rendered correctly. This is even if in the span, the font-family is sans-serif. Unfortunately I don't have the skills to explain this.
![scree](https://user-images.githubusercontent.com/16000669/227517909-06c8192d-514c-41c9-a455-4b79da29acf2.png)

### Environment

- **Browser (if applicable)**: all
- **React-PDF version**: latest
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by reteps** [comment]
I have the same issue.
![image](https://github.com/wojtekmaj/react-pdf/assets/13869303/b947d589-8a7f-4ba3-bc2e-710fba3fb3f0)

**Comment by wojtekmaj** [comment]
Hey, this is not going to be possible. Old versions used to do this, but apparently, it caused more problems than it fixed. Sorry!
