### ISSUE TITLE
`canvasBackground` prop not working correct

### ISSUE THREAD

**Issue by happylolonly** [wojtekmaj/react-pdf#1405]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I added this prop, but it shows this bg for a sec and then change it to white.
Is this working now? 

I can share more info if need.
<img width="630" alt="image" src="https://user-images.githubusercontent.com/18665326/227594625-e684324b-9330-468c-8b21-5d2f1c4e89e7.png">

### Steps to reproduce

add this prop

### Expected behavior

bg changed

### Actual behavior

bg jumping, and again white

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: 6.2.2 last
- **React version**:  18
- **Webpack version (if applicable)**: 5.74.0

**Comment by happylolonly** [comment]
debugged canvas, looks like it saving bg correct...
that means this is pdf background that not possible to change?
testing this link
https://gateway.ipfs.cybernode.ai/ipfs/QmV6cRDRdDQYWojiaUxYgPrN8PT9tXMu5NFVj3txsjKcpj

**Comment by happylolonly** [comment]
someone have ideas of problem?

**Comment by happylolonly** [comment]
😴

**Comment by wojtekmaj** [comment]
Judging from the description, it is an issue fixed in #1279. You can test this in recent 7.0.0-beta.4.

**Comment by happylolonly** [comment]
@wojtekmaj when 7.0.0 will be deployed to npm?

**Comment by wojtekmaj** [comment]
Beta is already there
