### ISSUE TITLE
Example file like in pdf.js demo

### ISSUE THREAD

**Issue by linxianxi** [wojtekmaj/react-pdf#1417]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

like https://mozilla.github.io/pdf.js/web/viewer.html. I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one, but it would be great to provide a complete example

**Comment by wojtekmaj** [comment]
I don't understand what you need. You want me to add better sample PDF?
