### ISSUE TITLE
Load from url requiring session cookie

### ISSUE THREAD

**Issue by mathieusteele** [wojtekmaj/react-pdf#142]
How can I submit a session cookie with the request? I can make successful API calls with other libraries when I include the credentials/cookies.

My PDFs are not loading - getting an error the InvalidPDFException but my network tab shows that a GET request is being sent for the file but that the credentials or cookie does not appear to be part of the request.

<img width="386" alt="screenshot" src="https://user-images.githubusercontent.com/440181/35423839-17dbabac-021e-11e8-9642-536de7db4b46.png">

**Comment by wojtekmaj** [comment]
Hey @mathieusteele,
please see README docs for `file` prop. There is an ability to pass `httpHeaders` along the `url`. Would that be something that answers your needs?

**Comment by mathieusteele** [comment]
`withCredentials: true`

was the tip I needed.

Thanks for a great library and a fast response.
