### ISSUE TITLE
The PDF content is rendered twice

### ISSUE THREAD

**Issue by JenniferFuBook** [wojtekmaj/react-pdf#1423]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Every page content is rendered twice.

### Steps to reproduce

In Create React App, modify src/App.js to the following:
```
import { useState } from 'react';
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack5';

function App() {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  return (
    <>
      <Document
        file="https://html.spec.whatwg.org/print.pdf"
        onLoadSuccess={onDocumentLoadSuccess}
      >
        <Page pageNumber={pageNumber} />
      </Document>
      <p>
        Page {pageNumber} of {numPages}
      </p>
    </>
  );
}

export default App;
```

### Expected behavior

It renders a PDF file as following:
![Screen Shot 2023-03-31 at 10 20 45 PM](https://user-images.githubusercontent.com/54613999/229267236-4276faf4-e42b-4341-b1cd-dd03cc27c462.png)

### Actual behavior

It renders a PDF file as following:

![Screen Shot 2023-03-31 at 10 25 58 PM](https://user-images.githubusercontent.com/54613999/229267311-99d806b1-6525-4b2d-bc8c-e83b18c520b5.png)

### Environment

- **Browser (if applicable)**: Chrome Version 111.0.5563.146
- **React-PDF version**: 6.2.2
- **React version**: 18.2.0
- **Webpack version (if applicable)**: 5.64.4

**Comment by wojtekmaj** [comment]
You're rendering a text layer, but without importing necessary styles. Check your browser console and README for details.

**Comment by JenniferFuBook** [comment]
It works. Thank you!
