### ISSUE TITLE
usePage hook

### ISSUE THREAD

**Issue by MarioSimou** [wojtekmaj/react-pdf#1453]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

Currently, the library doesn't provide options for someone to build his/her own custom `TextLayer`. It would be very helpful if we expose the `PageContext` with a hook, something similar to `usePage`, and a consumer could use it to access the state of the page. 

### Proposed solution

Expose the `PageContext` with a hook, such as `usePage`.

**Comment by wojtekmaj** [comment]
Implemented in 72f4da8d64fa3009358ba5f618dc9c877ff33627.
