### ISSUE TITLE
TypeError: key.split(...).at is not a function

### ISSUE THREAD

**Issue by Shawful** [wojtekmaj/react-pdf#1465]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Building into nextjs project here.  

After running `npm i react-pdf -P`, and attempting `npm run build`, I experience the error in the title.  Is there a previous version I should roll back to?

### Steps to reproduce

install, build with nextjs

### Expected behavior

expect a successful build

### Actual behavior

> Build error occurred
TypeError: key.split(...).at is not a function
    at new KeyboardManager (/node_modules/pdfjs-dist/build/pdf.js:4213:43)

### Environment

- **Browser (if applicable)**: chrome, latest
- **React-PDF version**: 6.2.2
- **React version**:17.0.2
- **Webpack version (if applicable)**: not using webpack

**Comment by Shawful** [comment]
When rolling back to 5.7.0, I saw the issue was resolved, if that helps.

**Comment by berrytsukiii** [comment]
> When rolling back to 5.7.0, I saw the issue was resolved, if that helps.

can't fix in vite application，sad

**Comment by wojtekmaj** [comment]
@berrytsukiii You should be able to get older versions working with Vite by following manual configuration process. I don't recommend that however, because I have almost no capacity to provide support for the latest version, let alone legacy ones.

**Comment by berrytsukiii** [comment]
@wojtekmaj thks and according to this comment https://github.com/wojtekmaj/react-pdf/issues/1220#issuecomment-1346022385 ，i have solved it temporarily。it seems more safety and stable to use the legacy pdf-js lib

**Comment by sebdec** [comment]
It happens on Safari v14.1.2 too (we don't use Vite)
it seems that it happens on version 6 react-pdf, not sure if it's a good idea to downgrade because this release fixes other important issues.

**Comment by chongqiangchen** [comment]
install corejs and add this:

import 'core-js/features/array/at';

**Comment by sumit-velocis** [comment]
@chongqiangchen still the same error continues...

**Comment by chongqiangchen** [comment]
> @chongqiangchen still the same error continues...

let me see how you write ？

**Comment by chongqiangchen** [comment]
> ![app-pdf](https://user-images.githubusercontent.com/62284446/236810997-50f02b76-4172-4bd2-95d3-a662aa160027.PNG) ![error](https://user-images.githubusercontent.com/62284446/236811005-2fb05afc-bf5d-425d-a442-0b25e842a80c.PNG)
> 
> "react-pdf": "^6.2.2", "core-js": "^3.29.1"
> 
> You can see the attached screenshot. let me know if i am doing anything wrong with it....

I write similarly to you, but I don't seem to have encountered your problem.

My component: https://github.com/chongqiangchen/unowai-frontend/blob/main/src/ui/widgets/pdf/index.tsx

Where I import the core: https://github.com/chongqiangchen/unowai-frontend/blob/main/src/pages/_app.tsx

**Comment by jakec-dev** [comment]
I have the same issue and importing the core-js 'at' array helper to App.tsx didn't help.

Perhaps the 'at' helper should be removed? It seems a bit too new to be used in production yet. It's only supported in modern browsers at this stage.

**Comment by wojtekmaj** [comment]
I'm not using it, pdfjs-dist is using it. I have updated instructions in README and suggested using legacy worker if needed. Let me know if this works!

**Comment by asif-simform** [comment]
Facing the same issue with the latest version `7.0.3`

**Comment by wojtekmaj** [comment]
@asif-simform Did you import 'core-js/features/array/at' as advised?

**Comment by asif-simform** [comment]
@wojtekmaj 

Yes, I've tried the same using `import 'core-js/features/array/at'` at the main `index.js` file. But still facing the same issue in safari.

Browser:- Safari Version 14.1.2 (16611.3.10.1.16)
Browser:- Safari Version 15.2 (17612.3.6.1.6)
![image](https://github.com/wojtekmaj/react-pdf/assets/62657766/f5e814a4-7655-4967-8835-ee00f9f768fa)

**Comment by wojtekmaj** [comment]
@asif-simform There's not a lot I can tell from this screenshot other than that Array.prototype.at is still undefined so either you're doing something incorrectly (e.g. loading core-js AFTER react-pdf) or perhaps some other tool is messing around with core-js imports.

**Comment by Wangggym** [comment]
<img width="411" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/26135370/0e20d51f-1028-461a-a7a6-3cc0da2946b2">
`core-js` cannot fix my question. I had to manually write a compatible writing method

**Comment by jjcoffee** [comment]
Just a heads up that this error also comes up from PDF.js itself now (rather than just the worker), so adding the polyfill is the only real solution. The core-js [fix](https://github.com/wojtekmaj/react-pdf/issues/1465#issuecomment-1537669572) is working fine for me, it just needs to be imported before `react-pdf`.
