### ISSUE TITLE
customTextRenderer should allow to return React components

### ISSUE THREAD

**Issue by BennyAlex** [wojtekmaj/react-pdf#1468]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

I would like to return a react component with a onClick method when calling `customTextRenderer`, but when I do this, I only see [object object] in the DOM.

Since this is a react libary, we should be allowed to return components also.

### Proposed solution

Allow react nodes to be returned and displayed by customTextRenderer

**Comment by wojtekmaj** [comment]
Unfortunately as of #1124 this is not possible. Please see PR description for details & workaround.

**Comment by BennyAlex** [comment]
@wojtekmaj 
this removes the abbility to use onClick etc

**Comment by wojtekmaj** [comment]
Yep, unfortunately. What you can still make use of, however, is event bubbling. Listen for clicks higher up the DOM tree. I understand this is nowhere near as convenient but my (bad) re-implementation of TextLayer caused way too many problems and I simply had to go with the "native" one.
