### ISSUE TITLE
backgroundColor property is not working properly

### ISSUE THREAD

**Issue by AlexisG0** [wojtekmaj/react-pdf#1477]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi I'm trying to add backgroundColor property but got "unsupported number: NaN", here is my code :

`  const styles = StyleSheet.create({
      horizontalLine: {
        position: "absolute",
        top: "-5pt",
        right: "0",
        width: "8pt",
        height: "8pt",
        borderRadius: "50%",
        backgroundColor: "#000",
      },
    });
`
    
If I comment backgroundColor everything is working : 

### Steps to reproduce

No response

### Expected behavior

No response

### Actual behavior

No response

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
That doesn't look like any React-PDF related code.
