### ISSUE TITLE
May be the file names in the README are not correct

### ISSUE THREAD

**Issue by 87prashant** [wojtekmaj/react-pdf#1489]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

https://github.com/wojtekmaj/react-pdf/blob/50cb697d95a79465bb981df1bc4ea1fdd222f855/README.md?plain=1#L122

I know they are recently changed form entry to index. I am not sure there is mismatch or not in README file but for me `index...` files are not present instead `entry...` files are present in node modules.

### Steps to reproduce

NA

### Expected behavior

NA

### Actual behavior

NA

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: 6.2.2
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
https://github.com/wojtekmaj/react-pdf#before-you-continue

**Comment by 87prashant** [comment]
Sorry, haven't read from top. Don't blame me I inherited it as an enginner. BTW, thanks for the great library.
