### ISSUE TITLE
`entry.noworker` doesn't work because of `pdfjs-dist` update

### ISSUE THREAD

**Issue by Kerumen** [wojtekmaj/react-pdf#149]
Since the version [v2.0.310](https://github.com/mozilla/pdfjs-dist/tree/v2.0.310/build), the file `pdf.combined.js` in not present in the build anymore. Hence, the `entry.noworker` doesn't work.

They removed this entry in [this PR](https://github.com/mozilla/pdf.js/pull/9385).
I don't understand why but as a temporary solution to get this lib working you can pin the dependency of `pdfjs-dist` to `2.0.305`.

**Comment by wojtekmaj** [comment]
[x] Fix on 3.x branch
[x] Cherry pick to 2.x branch
[x] Automatic testing
[ ] Manual sanity checks

**Comment by Kerumen** [comment]
@wojtekmaj I'm installing this version in my project, will keep you updated.

**Comment by Kerumen** [comment]
@wojtekmaj It works fine! Thanks for the quick publish :)
