### ISSUE TITLE
pdfjs.version is 2.16.105 instead of 3.5.14

### ISSUE THREAD

**Issue by aready87** [wojtekmaj/react-pdf#1490]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Using:
     "react-pdf": "^6.2.2",
     "pdfjs-dist": "^3.5.141"

I get the following error:
```
details: "Error: The API version \"2.16.105\" does not match the Worker version \"3.5.141\"."
message: "The API version \"2.16.105\" does not match the Worker version \"3.5.141\"."
name: "UnknownErrorException"
```

The problem is fixed by limiting pdfjs-dist to 2.16.105. However, I believe this is a bug?

I noticed that the samples, all of the pre-built bundlers are using pdfjs-dist of 2.16.105.

And even if I'm not using a bundler but using import { pdfjs } from "react-pdf", pdfjs.version still gives me 2.16.105.

I believe react-pdf is somehow pulling 2.16.105 instead of the 3.5.141 listed in its package.json.

### Steps to reproduce

In console: yarn add react-pdf;

    "react-pdf": "^6.2.2",

In new.js file: 
```
import { pdfjs } from "react-pdf";
console.log(pdfjs.version);
```

You get the following:
```
% node new
2.16.105
```

### Expected behavior

Expecting: 3.5.141

### Actual behavior

2.16.105

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 6.2.2
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
You misconfigured PDF worker and somehow you are getting the other version than expected. Not the other way around.

**Comment by Didi3333** [comment]
Got the same as @aready87 , 

react-pdf 6.2.2 and import { pdfjs } from "react-pdf";
console.log(pdfjs.version); =>2.16.105

**Comment by wojtekmaj** [comment]
#1434 did not get published yet.
