### ISSUE TITLE
Safari not working

### ISSUE THREAD

**Issue by chongqiangchen** [wojtekmaj/react-pdf#1491]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I only visit the official page, but it still cannot load properly.

### Steps to reproduce

1. go to https://projects.wojtekmaj.pl/react-pdf/

### Expected behavior

can show

### Actual behavior

not show

### Environment

- **Browser (if applicable) Safari: 15.0**:
- **React-PDF version V6.2.2**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by chongqiangchen** [comment]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/47734376/236725327-b8791c40-810d-4011-aa6e-4007e04b6363.png">

**Comment by chongqiangchen** [comment]
I cannot load PDF correctly on my own website, and there is no error reported in the console. The same code can load properly on Google. Where could the problem be?

my code:
```
import { Document, Page, pdfjs } from 'react-pdf';
import pdfWorker from 'pdfjs-dist/build/pdf.worker.entry';
pdfjs.GlobalWorkerOptions.workerSrc = pdfWorker;

import 'react-pdf/dist/esm/Page/AnnotationLayer.css';
import 'react-pdf/dist/esm/Page/TextLayer.css';
```
```
<Document
                                options={{
                                    standardFontDataUrl: `https://unpkg.com/pdfjs-dist@${pdfjs.version}/standard_fonts`,
                                }}
                                file={pdf}
                                onLoadSuccess={onDocumentLoadSuccess}
                            >
                                {Array.from(new Array(numPages), (_, index) => (
                                    <div key={`page_${index + 1}`} id={"pdf_" + index + 1}>
                                        <Page
                                            pageNumber={index + 1}
                                            customTextRenderer={textRenderer}
                                        />
                                    </div>
                                ))}
                            </Document>
                            ```

**Comment by wojtekmaj** [comment]
There might be a compatibility issue I'm not aware of. Any errors in the console?

**Comment by chongqiangchen** [comment]
> There might be a compatibility issue I'm not aware of. Any errors in the console?

I fix .at，but cant show pdf too

**Comment by liuchunda** [comment]
可以使用css降级兼容。
使用```
 .textLayer {
        * {
          color: rgba(0,0,0,0.88);
        }
```覆盖```
.textLayer :is(span,br) {
color: transparent;
position: absolute;
white-space: pre;
cursor: text;
margin: 0;
transform-origin: 0 0;
}
```
这样在safari浏览器中就可以显示文字了，只是没有颜色了
