### ISSUE TITLE
But with fonts

### ISSUE THREAD

**Issue by AlexisG0** [wojtekmaj/react-pdf#1492]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi I'm trying to add a custom font, but here is the result I get.

`Font.register({
  family: "Inter",
  fontStyle: "normal",
  fontWeight: "normal",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZhrib2Bg-4.ttf",
    },
    {
      src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
      fontStyle: "normal",
      fontWeight: "bold",
    },
    {
      src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuBWYMZhrib2Bg-4.ttf",
      fontStyle: "normal",
      fontWeight: "extrabold",
    },
    {
      src: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2Bg-4.ttf",
      fontStyle: "normal",
      fontWeight: "light",
    },
  ],
});
`

I'm using the font like this : 
`
const styles = StyleSheet.create({
      name: {
        color: "#000",
        fontFamily: "Inter",
        fontWeight: "extrabold",
      },
    });
<Text style={styles.name}>
Firstname Lastname
</Text>`

But here is the result : 
<img width="329" alt="image" src="https://user-images.githubusercontent.com/16312414/236833077-64ede31c-a386-440b-9458-d92eac6e60ad.png">

### Steps to reproduce

No response

### Expected behavior

No response

### Actual behavior

No response

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Missing required info, please fill in the template
