### ISSUE TITLE
Node Error:  Attempted import error: 'create' is not exported from 'fontkit' (imported as 'fontkit').

### ISSUE THREAD

**Issue by JosePabloo** [wojtekmaj/react-pdf#1501]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

App is using eact-pd and when rendering, it's throwing the following error: 
 
./node_modules/@react-pdf/font/lib/index.browser.es.js
Attempted import error: 'create' is not exported from 'fontkit' (imported as 'fontkit').
<img width="1414" alt="Screen Shot 2023-05-23 at 4 50 12 PM" src="https://github.com/wojtekmaj/react-pdf/assets/20023882/ed2cc8e7-e9f0-4725-83da-2737c0014db0">

### Steps to reproduce

Yarn install, 
Yarn start 
app won't load

### Expected behavior

Should not block app from starting 

### Actual behavior

App doesn't load. Errors out 

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
-   "@react-pdf/renderer": "^2.0.21",
- **React version**:
-     "react": "17.0.2",
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
