### ISSUE TITLE
Google Chrome 90.0.4430.72 error 

### ISSUE THREAD

**Issue by sergeu90** [wojtekmaj/react-pdf#1507]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi All. In the documentation wrote support version >= 88 but i have errors on 90 version 
![image](https://github.com/wojtekmaj/react-pdf/assets/7217517/62aec3b1-9c2d-4074-8e58-5001558dca59)

### Steps to reproduce

Install 90 version Google Chrome.

### Expected behavior

Not errors excepted

### Actual behavior

![image](https://github.com/wojtekmaj/react-pdf/assets/7217517/f28891b4-5eb4-4de2-a8cc-6cb7418b17d3)

### Environment

- **Browser (if applicable)**: 90.0.4430.72  
- **React-PDF version**: 7.0.1
- **React version**: 18
- **Webpack version (if applicable)**:  5.84.1

**Comment by wojtekmaj** [comment]
Shoot. It appears we can't trust Mozilla _at all_ when it comes to their own compatibility information. 

The only thing I can advise for now is to import core-js Array.prototype.at polyfill (`core-js/es/array/at`). Chances are you may need additional polyfills, but this should get you started.

**Comment by sergeu90** [comment]
@wojtekmaj Yes. I added core js and works after that.
