### ISSUE TITLE
./node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node Module parse failed: Unexpected character '�' (1:2)

### ISSUE THREAD

**Issue by 192114** [wojtekmaj/react-pdf#1508]
### Before you start - checklist

- [x] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

'use client' is already written in the code and import by next/dynamic(ssr: false)

 I get the following error when dev:

```shell
./node_modules/.pnpm/canvas@2.11.2/node_modules/canvas/build/Release/canvas.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

### Steps to reproduce

This is [codesandbox](https://codesandbox.io/p/sandbox/kind-chaum-shlb6x)

### Expected behavior

I expect no errors

### Actual behavior

Uncaught ModuleParseError: Module parse failed: Unexpected character '�' (1:2)

### Environment

- "next": "13.4.1"
- "react-pdf": "^7.0.1"

**Comment by wojtekmaj** [comment]
Try not running react-pdf server side. It doesn't make a lot of sense to be honest, since canvas needs to be rendered in the browser anyway.

**Comment by FengeRVictor** [comment]
I have the same issue.

**Comment by FengeRVictor** [comment]
Ok, in next.config.js :

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (
    config, options
  ) => {
    // Important: return the modified config
    config.module.rules.push({
      test: /\.node/,
      use: 'raw-loader',
    });
    return config;
  },
};

module.exports = nextConfig;

```

with npm install -D raw-loader

**Comment by kusalkalinga00** [comment]
> Ok, in next.config.js :
> 
> ```
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   webpack: (
>     config, options
>   ) => {
>     // Important: return the modified config
>     config.module.rules.push({
>       test: /\.node/,
>       use: 'raw-loader',
>     });
>     return config;
>   },
> };
> 
> module.exports = nextConfig;
> ```
> 
> with npm install -D raw-loader

this fix for me also, Next js 13.4 app router .

**Comment by rohankm** [comment]
im facing the same issue and the above method is not working for me

**Comment by wojtekmaj** [comment]
Have you seen the note for pnpm users in this section? https://github.com/wojtekmaj/react-pdf#configure-pdfjs-worker

**Comment by liowalex** [comment]
> Ok, in next.config.js :
> 
> ```
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   webpack: (
>     config, options
>   ) => {
>     // Important: return the modified config
>     config.module.rules.push({
>       test: /\.node/,
>       use: 'raw-loader',
>     });
>     return config;
>   },
> };
> 
> module.exports = nextConfig;
> ```
> 
> with npm install -D raw-loader

If you're using this fix and happen to be using the stripe package, or any other packages with` .node` files, you might want to be more specific with the matcher phrase:

https://github.com/stripe/stripe-node/issues/1896#issuecomment-1711802291

**Comment by ssreynoso** [comment]
Worked for me. Thanks!
