### ISSUE TITLE
Failed to load PDF File error on production build

### ISSUE THREAD

**Issue by baqirvd** [wojtekmaj/react-pdf#1509]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

My goal:

Click the view button to preview the uploaded PDF file

Problems:

Failed to load PDF file is displayed after uploading

`import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
<Document file={pdf}> <Page pageNumber={1} /> </Document>
`

### Steps to reproduce

Upload PDF file, click the view button to display failed to load PDF file

### Expected behavior

Click the view button to preview the uploaded PDF file

### Actual behavior

Failed to load PDF file is displayed after uploading

### Additional information

This is working perfectly in the development environment, but not working on production build

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 6.2.0
- **React version**: 18.2.0
- **React scripts version**: 5.0.1
- **Craco version**: 7.1.0

**Comment by wojtekmaj** [comment]
Have you checked this?

https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions#when-im-trying-to-load-a-pdf-file-from-an-external-source-im-given-a-message-failed-to-load-pdf-file

**Comment by baqirvd** [comment]
Followed the solution mentioned here https://github.com/wojtekmaj/react-pdf/issues/991
