### ISSUE TITLE
Fixed Page with Absolute Positioning in ReactPDF

### ISSUE THREAD

**Issue by benjaminsanga-ogtl** [wojtekmaj/react-pdf#1510]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When I used the package with precise absolute positioning to match my design, the number of pages did not increase based on the content. Instead, it remained as a single page, but the styling was accurate and suitable for my needs.

### Steps to reproduce

- Create a document with the Document component.
- Add a Page component with the Document component and give it a styling with position absolute, along left and top properties.
- Add View and Text components with an absolute position styling.
- Add large text in the Text component.

### Expected behavior

Page increasing according to the length of text.

### Actual behavior

Text is truncated at the end of the first page, and does not render any other page.

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.

**Comment by benjamin-sanga** [comment]
Noted with thanks
