### ISSUE TITLE
react-pdf v6 drops support for Chrome before 92

### ISSUE THREAD

**Issue by benasher44** [wojtekmaj/react-pdf#1513]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Since v6 no longer uses the legacy pdfjs-dist build, which no does not include the Array.at polyfill, a feature not supported until Chrome 92. I believe this was done in #988

### Steps to reproduce

Run react-pdf in Chrome 91

### Expected behavior

react-pdf runs

### Actual behavior

It crashes on load accessing Array.at

### Additional information

I'm not expecting fixed backward compatibility, but I do think the guide should be updated.

### Environment

- **Browser (if applicable)**: Chrome 91
- **React-PDF version**: v6+
- **React version**: react 16.8
- **Webpack version (if applicable)**: 5.x

**Comment by benasher44** [comment]
[This file](https://github.com/mozilla/pdf.js/blob/v2.16.105/src/shared/compatibility.js#L69) adds the compatibility polyfills in the "legacy" build (no longer used in v6). The comments there probably give the most accurate browser support info

**Comment by benasher44** [comment]
Also because pdfjs has a [static initializer that creates KeyboardManager](https://github.com/mozilla/pdf.js/blob/v2.16.105/src/display/editor/tools.js#L442) (which uses `Array.prototype.at` in its constructor, it's not enough to just use the legacy build of the worker, since loading react-pdf will end up calling the modern version without polyfills

**Comment by wojtekmaj** [comment]
You're right. I believe that:

* Polyfills need to be loaded to extend support limited by new functions
* pdfjs-dist should be transpiled using e.g. Babel and legacy PDF.js worker should be used to extend suport limited by modern syntax

**Comment by benasher44** [comment]
I would just update it (v5 -> v6 migration guide and anywhere else) to say what the minimum versions are without polyfills/transpilation. Otherwise, a lot of digging is needed to determine the correct version spec.

The fact that polyfills + transpilation is needed for backward compatibility is true of any library, and what you need to do depends on bundler (e.g. users of `@vitejs/plugin-legacy` and custom/specific webpack configs may not notice, depending on their configuration, whereas CRA users are kinda SOL in terms of offering them easy and specific instructions). I think maintenance of documentation like that goes well beyond anyone's expectations, so that's why I think just saying what is supported without modifications is probably best.

**Comment by FizzyElt** [comment]
I am working on Chrome v87 and I have encountered the same issue. 
So, how can I solve it? 
By using v7 and setting the legacy worker?

**Comment by wojtekmaj** [comment]
Upgrading to v7 won't increase compatibility, you're fine on v6 for now (but of course, you're welcome to upgrade!). It looks like we need a couple of polyfills (see above) to increase the compatibility but the full list is currently unknown.
