### ISSUE TITLE
Additional text is highlighted when the user hits break points in the text 

### ISSUE THREAD

**Issue by viktor1ja** [wojtekmaj/react-pdf#1516]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When the user is selecting text in the pdf and stops, additional text almost till the end of the page is selected.

### Steps to reproduce

Create a pdf in React application using a code snippet 
`      <Document
        key="pdf-doc"
        data-testid="pdf-viewer"
        file={file}
        ref={ref}
      >
        {ready &&
          Array.from(new Array(numPages), (el, index) => {
            return <Page key={`page_${index + 1}`} width={pdfWidth} pageNumber={index + 1} />;
          })}
      </Document>`

Open pdf in the application and select part of the text using the mouse. Additionally, not selected part of the text is highlighted

### Expected behavior

Only selected part of the text is highlighted

### Actual behavior

Not selected part of the text is highlighted

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: 7.0.1
- **React version**: 18.2.0

**Comment by mixeden** [comment]
+1 to this bug, but I think this is actually been answered already here https://github.com/wojtekmaj/react-pdf/issues/101

**Comment by wojtekmaj** [comment]
Unfortunately, due to how PDFs are built, and due to how Chromium handles text selection, little can be done to improve text selection behavior. It works kind of nicely on Firefox, but on Chromium... Not so much. Unfortunately this will be a wontfix, until the situation changes.
