### ISSUE TITLE
Some links in pdf header and footer are not clickable

### ISSUE THREAD

**Issue by viktor1ja** [wojtekmaj/react-pdf#1517]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Some links in the pdf header or footer are not clickable. They have link styling, but don't have html link element and are not accessible via linkService

### Steps to reproduce

Create a pdf with links in the footer or header. A link has link styling, but don't have html link element and is not clickable doesn't

### Expected behavior

Link is clickable

### Actual behavior

Link is not clickableThe link

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: 7.0.1
- **React version**: 18.2.0
- **Webpack version (if applicable)**: 5.64.4

**Comment by wojtekmaj** [comment]
Do you have an example PDF I can reproduce it with?
