### ISSUE TITLE
Error when loading empty url

### ISSUE THREAD

**Issue by josephpung** [wojtekmaj/react-pdf#152]
Error Message: _Invalid parameter object: need either .data, .range or .url Error: Invalid parameter object: need either .data, .range or .url_

Is there a way to load the component with no url provided without triggering an error in the console? Im currently passing the url via props from the parent element. The initial url is just a blank string as I want to load the initial error message, which works fine, but is there a way to disable the console message?

Parent props
<img width="209" alt="screen shot 2018-02-09 at 4 56 52 pm" src="https://user-images.githubusercontent.com/30632611/36019432-446c0caa-0dba-11e8-9d21-2c50e27ff93c.png">

error message
<img width="1032" alt="screen shot 2018-02-09 at 4 56 45 pm" src="https://user-images.githubusercontent.com/30632611/36019433-44a02120-0dba-11e8-9a49-0951c067e22f.png">

Thanks in advance! (amazing lib by the way)

**Comment by josephpung** [comment]
<img width="831" alt="screen shot 2018-02-09 at 5 41 55 pm" src="https://user-images.githubusercontent.com/30632611/36021375-8c4f4054-0dc0-11e8-9e58-1beabe3017ed.png">

it okay i managed to find a workaround, loaded a different component if the url was blank, leaving this here in case anyone else encounters it!

**Comment by wojtekmaj** [comment]
@josephpung, your solution is perfectly okay. Another one would be not using "parameter objects", because you don't really have a reason to. Instead of 
`file={{ url }}`
you can write
`file={url}`.

**Comment by nags-git** [comment]
with the below lines of code i am having the same issue, do you have any resolution

 <Document
                  file={{
                    url: fileInfo.presigned_url,
                    httpHeaders: {
                      "Access-Control-Request-Method": "GET",
                      "Access-Control-Allow-Origin": "*"
                    }
                  }}
                  onLoadSuccess={onDocumentLoadSuccess}
                  renderMode="canvas"
                  loading=""
                  onLoadError={onDocumentLoadError}
                >
