### ISSUE TITLE
Missing `httpHeaders` type

### ISSUE THREAD

**Issue by kamilkazmierczakMtab** [wojtekmaj/react-pdf#1525]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Missing `httpHeaders` type

### Steps to reproduce

Documentation says that you can provide `httpHeaders` to `Document` component in  `file` prop.
This actually works but you can't pass it without TS error.
Invalid `Source` type used by `File` https://github.com/wojtekmaj/react-pdf/blob/main/src/shared/types.ts#L59  
Missing type https://github.com/mozilla/pdfjs-dist/blob/5f07d5a4159bb99eee2f6143d1297f03b45bba58/types/src/display/api.d.ts#L24

### Expected behavior

Types are correct

### Actual behavior

Types are incorrect

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Just checked and it doesn't say so, but I do remember it used to say it before 43d7dab7b7052e31565a9c5b76b6b063377b388d.
