### ISSUE TITLE
We encountered a pdf that could not preview properly.

### ISSUE THREAD

**Issue by jilliss** [wojtekmaj/react-pdf#1528]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

It should be noted that this file can be displayed normally through wps and word, as well as when I open it with edge.

This is the version I use.：` "react-pdf": "^6.2.2",`

This is the problem, pdf.
[bug.pdf](https://github.com/wojtekmaj/react-pdf/files/11683199/bug.pdf)

### Steps to reproduce

Load this pdf page via base64, or url

### Expected behavior

Pdf display normally

### Actual behavior

Pdf display blank

### Environment

- **Browser (if applicable)**: Chrome  114.0.5735.110
- **React-PDF version**: ^6.2.2
- **React version**:  ^17.0.2
- **Webpack version (if applicable)**: 5.28.0

**Comment by wojtekmaj** [comment]
You likely forgot about this:

https://github.com/wojtekmaj/react-pdf#support-for-non-latin-characters
