### ISSUE TITLE
Node error Importing a react-pdf component into page using new nextjs app directory

### ISSUE THREAD

**Issue by abduljamac** [wojtekmaj/react-pdf#1532]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

My project is using the new app directory for next-js, I created component which contains react-pdf code, that looks like this:

```import { pdfjs, Document, Page, Outline } from "react-pdf"
import "react-pdf/dist/esm/Page/TextLayer.css"
import "react-pdf/dist/esm/Page/AnnotationLayer.css"
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`

export default function PDFViewer({ file }) {
	useEffect(() => {
		pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`
	}, [])

	const [numPages, setNumPages] = useState(null)
	const [searchText, setSearchText] = useState("")

	// const file = "assets/record.pdf"

	function highlightPattern(text, pattern) {
		return text.str.replace(pattern, (value) => `<mark>${value}</mark>`)
	}

	function onDocumentLoadSuccess({ numPages }) {
		setNumPages(numPages)
	}

	function onItemClick({ pageNumber: itemPageNumber }) {
		setPageNumber(itemPageNumber)
	}

	const textRenderer = (textItem) => {
		if (!textItem) return null
		return highlightPattern(textItem, searchText)
	}

	function onChange(event) {
		setSearchText(event.target.value)
	}
	return (
		<>
			<div>
				<label htmlFor="search">Search:</label>
				<input type="search" id="search" value={searchText} onChange={onChange} />
			</div>
			<Document file={file} onLoadSuccess={onDocumentLoadSuccess}>
				<Outline onItemClick={onItemClick} />
				{Array.from(new Array(numPages), (_, index) => (
					<Page
						size="A4"
						key={`page_${index + 1}`}
						pageNumber={index + 1}
						customTextRenderer={textRenderer}
					/>
				))}
			</Document>
		</>
	)
}
````

and when I import it into page.tsx, I get the error below:

![Screenshot 2023-06-07 at 13 52 20](https://github.com/diegomura/react-pdf/assets/31995285/ea2b2f31-82eb-4629-bcdf-c7ae1d31b1f6)

However it works fine in non app directory project, so I assume its problem with next-js app directory not being compatible with react-pdf. I was wondering if anyone experienced this problem and if they have a work around?

### Steps to reproduce

N/A

### Expected behavior

To not show the error?

### Actual behavior

N/A

### Environment

- **Browser (if applicable)**:
- **React-PDF version*^7.0.3*:
- **React version*^18.2.0*:
- **Webpack version (if applicable)**:

**Comment by MattL75** [comment]
Check #1508 maybe the fix in there will help you?

**Comment by icaro-rdp** [comment]
i'm in the same situation with a brand new nextJS app route project.

**Comment by icaro-rdp** [comment]
@abduljamac https://github.com/wojtekmaj/react-pdf/issues/1508#issuecomment-1570532754 this worked for me!

**Comment by abduljamac** [comment]
> @abduljamac [#1508 (comment)](https://github.com/wojtekmaj/react-pdf/issues/1508#issuecomment-1570532754) this worked for me!

Did it work without using DynamicOptions from next?

@icaro-rdp

**Comment by icaro-rdp** [comment]
> > @abduljamac [#1508 (comment)](https://github.com/wojtekmaj/react-pdf/issues/1508#issuecomment-1570532754) this worked for me!
> 
> Did it work without using DynamicOptions from next?
> 
> @icaro-rdp

I've used it so as to avoid ssr, dunno if it works without it

**Comment by emiller7** [comment]
Adding the config did not resolve the issue 

webpack: (
        config, options
    ) => {
        // Important: return the modified config
        config.module.rules.push({
            test: /\.pdf$/i,
            use: 'raw-loader',
        });
        return config;
    },

**Comment by emiller7** [comment]
ok - so following the docs (latest) using react 18 I have to use the CDN url for

pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;

when using react-pdf I get the following error .6.172" does not match the Worker version "3.8.162"

Using the CDN URL worked so I assume you could download the latest worker and reference that instead of using the CDN

**Comment by wojtekmaj** [comment]
@emiller7 The error you're getting suggests to me that you have installed pdfjs-dist separately and in fact you have two copies of pdfjs-dist installed in your repository. I'd suggest you fix that.

**Comment by emiller7** [comment]
@wojtekmaj yes your correct - for some reason pdfjs-dist keeps appearing in my node_modules folder even though I did not npm install it or include it in my package.json - trying to figure out how to remove it

**Comment by emiller7** [comment]
@wojtekmaj actually when doing npm install react-pdf it also installs pdfjs-dist folder into my node_modules folder with version 3.6.172. The version in the react-pdf folder in node_modules uses a newer version

**Comment by wojtekmaj** [comment]
Since the original issue has been resolved and the solution has been properly documented in README, I'm closing this.
