### ISSUE TITLE
How to support ie 11

### ISSUE THREAD

**Issue by jilliss** [wojtekmaj/react-pdf#1534]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I'm having a bad problem.
 I have to be compatible with ie 11 for my functionality. 
I want to know. Is this component supported?  If supported. How can I do it

### Steps to reproduce

ie 11 not work

### Expected behavior

normal work

### Actual behavior

not work

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
https://github.com/wojtekmaj/react-pdf#compatibility
