### ISSUE TITLE
Online demo not working with the url i passed

### ISSUE THREAD

**Issue by chathurvedijarugu** [wojtekmaj/react-pdf#1536]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

when i am passing the browser url of pdf file then that pdf is nor rendering,then i checked with online demo "https://projects.wojtekmaj.pl/react-pdf/test/" but even that demo cant render that pdf file

### Steps to reproduce

see error

### Expected behavior

![image](https://github.com/wojtekmaj/react-pdf/assets/115549774/f7c49a6b-169c-40c2-93af-52cec93528af)

### Actual behavior

![image](https://github.com/wojtekmaj/react-pdf/assets/115549774/190e23a0-f981-4618-900d-93523df862c0)

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Can you pass the actual URL you're trying to use?

**Comment by siddharthshankarpaul** [comment]
@wojtekmaj 
here is one URL i tried https://www.africau.edu/images/default/sample.pdf

**Comment by juzarantri** [comment]
how can i fetch pdf data and pass?

**Comment by juzarantri** [comment]
please provide code snippet I am not getting where am I stucked

**Comment by kennaku1** [comment]
@juzarantri, Are you using the "Page" child component? I was missing this and it caused my PDF not to render. You need to set the page numbers as well. If you load a BLOB you need to convert it to a file as well. 

        const file = new File([blob], 'PDF_NAME_HERE', {type: 'application/pdf', lastModified: Date.now()});

**Comment by wojtekmaj** [comment]
That test page is not really intended for the public, but since you're playing with it, you must learn about CORS policy and how browsers handle cross origin requests. More on that on Google, but basically, you can't just request any data from any server and expect it to work. The server needs to be configured to allow, via special HTTP headers, certain origins to request data from itself.

**Comment by ZeeshanAhmadKhalil** [comment]
It's giving Cors error on every PDF.
