### ISSUE TITLE
Uncaught TypeError: Cannot perform Construct on a detached ArrayBuffer

### ISSUE THREAD

**Issue by KamilSlaweta** [wojtekmaj/react-pdf#1539]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I setup a simple component like 

```
<Document
  file={file}
  options={{
    cMapUrl: `https://unpkg.com/pdfjs-dist@${pdfjs.version}/cmaps/`,
    standardFontDataUrl: 'standard_fonts/',
  }}
>
  {Array.from(new Array(numPages), (el, index) => (
    <Page key={`page_${index + 1}`} pageNumber={index + 1} />
  ))}
</Documnet>
```

File is provided via props and changes only when I provide a different file from file input

Whenever I provide a PDF file for the first time, it works fine. When I want to change a PDF file it breaks with 

![image](https://github.com/wojtekmaj/react-pdf/assets/33666200/67f62fc1-3d1b-4659-bf31-a5e8dc836b51)

### Steps to reproduce

Just try to play around with a react PDF

### Expected behavior

App is not crashing and rendered PDF file has been changed

### Actual behavior

App is crashing.

### Environment

- **Browser (if applicable)**: ARC 0.109.0 
- **React-PDF version**: 7.1.2
- **React version**: 17.0.2
- **Webpack version (if applicable)**: 5.70.0

**Comment by KamilSlaweta** [comment]
Additionally, I have something like 

```
 const [numPages, setNumPages] = useState<number>();

  const onDocumentLoadSuccess = ({ numPages: total }: PDFDocumentProxy) => {
    setNumPages(total);
  };

```

Whenever I pass `onDocumentLoadSuccess` into `Document`, the app breaks. But when I remove `setNumPages(total);`, it loads fine.

**Comment by heyajohnny** [comment]
I can confirm I have the same error when upgrading from react-pdf 6.2.2 to 7.1.2
The moment you execute `setNumpages(total)` You'll get the error.

**Comment by WITfeng** [comment]
i have the same error when i load blob pdf. its dismissed when i load local pdf path

**Comment by taneliang** [comment]
I've also noticed this after upgrading from v6.2.2 to 7.2.0. In our app, this error is thrown when unmounting and remounting `Document` with the same ArrayBuffer `file`. I haven't been able to repro this with URLs and File objects.

I'm not sure what's causing this either, but I've managed to prevent `ArrayBuffer` `file`s from being detached by passing in a slice instead of the original buffer:

```jsx
const fileSlice = useMemo(() => file.slice(0), [file]);
...
return <Document file={fileSlice} />;
```

**Comment by JorisMARTIN** [comment]
Hello,
I'm in front of the same error. The error occurs when `Document` is unmounted & remounted.
I tried to pass an Uint8array as recommended in the doc instead of an arraybuffer like this :

```jsx 
const [pdfData, setPdfData] = useState<Uint8Array | null>(null);

useEffect(() => {
    setPdfData(new Uint8array(/*collectedData*/));
}, [])

const render = useMemo(() => (
    pdfData && 
        <Document file={{ data: pdfData }}>
        {/* ... */}
        </Document>
), [pdfData]);

return render;
```
But I the error `Failed to load PDF file.` occurs with the following warning in console : 
![image](https://github.com/wojtekmaj/react-pdf/assets/27498179/a1498052-0dac-426f-a876-0346a52453a8)

**Comment by wojtekmaj** [comment]
@JorisMARTIN First and foremost, memoize the hike object passed to Document, not just one of the properties.

**Comment by JorisMARTIN** [comment]
Thank you @wojtekmaj. It works fine now.

For the others, my code looks like this now
```jsx
const [pdfData, setPdfData] = useState<{data: Uint8array} | null>(null);

useEffect(() => {
    setPdfData({data: new Uint8array(/*collected data*/)});
}, [])

const render = useMemo(() => (
    pdfData && 
        <Document file={pdfData}>
        {/* ... */}
        </Document>
), [pdfData]);

return render;
```

**Comment by wojtekmaj** [comment]
Huh 🤔  Why not just

```
const pdfData = useMemo(() => ({ data: new Uint8array(/*collected data*/) }), []);

return (
  <Document file={pdfData}>
    {/* ... */}
  </Document>
);
```

**Comment by JorisMARTIN** [comment]
Because /*collected data*/ are from an async call. `pdfData` can't be a Promise.

**Comment by VigneshSonaiya** [comment]
I'm getting this error when I have already opened uint8Array and changed to file url

**Comment by efraimrodrigues** [comment]
None of the above worked for me as `numPages` is one of the dependencies of my "render method". For now, I decided to go with rendering all pages at once since state update is currently detaching the array buffer. Memoizing it didn't help. Here's what I have currently working for me (it invokes `readFile` twice):

Similar logic can be used for implementing navigation, but I don't see another way of doing it without avoiding invoking the `readFile` function every time.

```
function readFile(file) {
  return new Promise((resolve, reject) => {
    let reader = new FileReader();
    reader.addEventListener("loadend", e => resolve(e.target.result));
    reader.addEventListener("error", reject);
    reader.readAsArrayBuffer(file);
  });
}

export const PDFController = memo(({ file }) => {
  const [fileData, setFileData] = useState(null);
  const [numPages, setNumPages] = useState(null);

  const onDocumentLoadSuccess = ({ numPages: numPagesParam }) => {
    if (numPages !== numPagesParam) {
      setNumPages(numPagesParam);
      setFileData({ data: new Uint8Array() });
    }
  };

  useEffect(() => {
    if (file) {
      readFile(file).then(data => setFileData({ data: new Uint8Array(data) }));
    }
  }, [file, numPages]);

  return (
    <Document
      file={fileData}
      onLoadSuccess={onDocumentLoadSuccess}
      options={{
        cMapUrl: `https://unpkg.com/pdfjs-dist@${pdfjs.version}/cmaps/`,
        cMapPacked: true,
      }}
    >
      {[...Array(numPages)].map((_, i) => (
        <PDFPage key={i} pageNumber={i + 1} />
      ))}
    </Document>
  );
});
```

**Comment by wojtekmaj** [comment]
@efraimrodrigues Please read README and this thread carefully first. Extract options object definition to be outside of React component. Doesn't guarantee the error to go away, but failing to do so guarantees you'll be stuck.

**Comment by lancejpollard** [comment]
I give up, I tried doing it but it doesn't appear to work if you dynamically change the PDF array buffer content, and try to rerender.

```tsx
import '~/utilities/client/pdf'
import cx from 'classnames'
import React, { useEffect, useMemo, useRef, useState } from 'react'
import { Document, Page } from 'react-pdf'
import _ from 'lodash'
import { useSize } from '@termsurf/vine'

let KEY = 1

// https://github.com/wojtekmaj/react-pdf/issues/1539
// https://github.com/diegomura/react-pdf-site/pull/91/files
export default function PDF({
  data,
  error,
  className,
}: {
  data?: ArrayBuffer
  error?: string
  className?: string
}) {
  const containerRef = useRef(null)
  const size = useSize(containerRef)
  const [input, setInput] = useState<ArrayBuffer>()
  const [previousData, setPreviousData] = useState<ArrayBuffer>()
  const [documents, setDocuments] = useState<{
    previous: React.ReactNode | null
    current: React.ReactNode | null
    next: React.ReactNode | null
  }>({
    previous: null,
    current: null,
    next: null,
  })
  const [previousDocument, setPreviousDocument] =
    useState<React.ReactNode>()
  const [currentDocument, setCurrentDocument] =
    useState<React.ReactNode>()
  const [nextDocument, setNextDocument] = useState<React.ReactNode>()
  const [state, setState] = useState<
    'start' | 'changing' | 'ready' | 'complete'
  >('start')
  // const [numPages, setNumPages] = useState<number>(1)
  const [previousRenderValue, setPreviousRenderValue] =
    useState<ArrayBuffer>()

  useEffect(() => {
    if (previousData !== data) {
      if (data != null) {
        setInput(data.slice(0))
        setPreviousData(data)
      } else {
        setInput(undefined)
        setPreviousData(undefined)
      }

      setState('start')
    }
  }, [previousData, data])

  useEffect(() => {
    if (!input) {
      setInput(undefined)
      setPreviousData(undefined)
      setDocuments({
        previous: null,
        current: null,
        next: null,
      })
      // setPreviousDocument(undefined)
      // setCurrentDocument(undefined)
      return
    }

    console.log('rebuild', state)

    if (state === 'ready') {
      console.log('ready')
      setDocuments(documents => ({
        previous: null,
        current: documents.next,
        next: null,
      }))
      setState('complete')
    } else if (state === 'start') {
      // setPreviousDocument(<div/>)
      console.log('future')

      setState('changing')

      setDocuments(documents => ({
        previous: documents.current,
        current: null,
        next: (
          <Document
            file={input.slice(0)}
            loading={null}
            key={`pdf-${KEY++}`}
            // onLoadSuccess={handlePDFLoad}
          >
            <Page
              pageNumber={1}
              width={size?.width ?? 800}
              onRenderSuccess={() => {
                setState('ready')
              }}
            />
          </Document>
        ),
      }))
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [input, state])

  return (
    <div
      className={cx(className, 'w-full')}
      ref={containerRef}
    >
      {error ? (
        error
      ) : (
        <>
          <div className="invisibled">{documents.next}</div>
          {documents.current}
          {documents.previous}
        </>
      )}
    </div>
  )
}
```

I think the react-pdf library needs to keep better track of the Uint8Array between renders somehow... Or am I missing something.

**Comment by Eliav2** [comment]
i get this error after mount after unmount. someone knows what is the cause?

**Update: this fixed it for me: instead of using `blob.arrayBuffer()` i simply used `Blob` as a `file` to render the pdf.**

**Comment by mackenzie-baksh-isc** [comment]
> I've also noticed this after upgrading from v6.2.2 to 7.2.0. In our app, this error is thrown when unmounting and remounting `Document` with the same ArrayBuffer `file`. I haven't been able to repro this with URLs and File objects.
> 
> I'm not sure what's causing this either, but I've managed to prevent `ArrayBuffer` `file`s from being detached by passing in a slice instead of the original buffer:
> 
> ```js
> const fileSlice = useMemo(() => file.slice(0), [file]);
> ...
> return <Document file={fileSlice} />;
> ```

Crazy enough this worked for me in such an odd way
