### ISSUE TITLE
Long empty space after every rendered page

### ISSUE THREAD

**Issue by trsiddiqui** [wojtekmaj/react-pdf#1543]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I am using v7.1.2 as of 5th July with the following code. After each rendered page, its showing a large empty state due to which pages have a huge gap between them.

```
<Document
  file={activePDFURL}
  onLoadSuccess={document => {
    setNumPagesOfActivePDF(document.numPages)
  }}
>
  {Array.from(new Array(numPagesOfActivePDF), (el, index) => (
    <Page key={`page_${index + 1}`} pageNumber={index + 1} />
  ))}
</Document>
```

<img width="515" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/4200469/f6336579-eb3e-4bfb-855e-c05f901c038a">

### Steps to reproduce

Use any pdf url using the code above

### Expected behavior

It should not show empty whitespace between pages

### Actual behavior

It shows empty whitespaces between pages

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: 7.1.2
- **React version**: 17.0.2
- **Webpack version (if applicable)**:

**Comment by tactycadmin** [comment]
Same issue here.

**Comment by kieranbop1990** [comment]
I am observing the same behaviour

**Comment by Sharoof-Khan** [comment]
Same Issue

**Comment by wojtekmaj** [comment]
Make sure you add both of required CSS files:

```js
import "react-pdf/dist/esm/Page/AnnotationLayer.css";
import "react-pdf/dist/esm/Page/TextLayer.css";
```

Otherwise, can't reproduce: https://codesandbox.io/p/sandbox/react-pdf-all-pages-rwvq5m?file=%2Fsrc%2FApp.tsx

**Comment by wojtekmaj** [comment]
See also #1385, #1292

**Comment by JacobDel** [comment]
> Make sure you add both of required CSS files:
> 
> ```js
> import "react-pdf/dist/esm/Page/AnnotationLayer.css";
> import "react-pdf/dist/esm/Page/TextLayer.css";
> ```
> 
> Otherwise, can't reproduce: https://codesandbox.io/p/sandbox/react-pdf-all-pages-rwvq5m?file=%2Fsrc%2FApp.tsx

This only works in development, when exporting it for deployment it doesn't work anymore (`next build && next export`).

`next.config.js`:
```
module.exports = {
  webpack(config) {
    config.module.rules.push({
      test: /\.svg$/,
      use: ["@svgr/webpack"],
    });
    config.resolve.alias.canvas=false;
    config.resolve.alias['react/jsx-runtime'] = 'react/jsx-runtime.js';
    Object.defineProperty(config, 'devtool', { // https://github.com/vercel/next.js/discussions/21425#discussioncomment-7256984
      get() {
          return 'source-map';
      },
      set() {},
  });
    return config;
  },
  distDir: "build",
  output: "export",
  images:{
    unoptimized:true
  },
};

```

**Comment by franshuyadav** [comment]
Late to the thread, but on adding renderAnnotationLayer={false}, the scale attribute of Page stops working. Anyone else experiencing this?
