### ISSUE TITLE
Server Error TypeError: url.replace is not a function

### ISSUE THREAD

**Issue by BlankTurbo** [wojtekmaj/react-pdf#1554]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

```
import { useState } from 'react';
import { Document, Page, pdfjs } from 'react-pdf';
import { Logger } from '@/lib/logger';
import { Screens } from '@/pages/constants';

import 'react-pdf/dist/esm/Page/AnnotationLayer.css';
import 'react-pdf/dist/esm/Page/TextLayer.css';
//pdfjs.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;

pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url
).toString();
```
<img width="1470" alt="Screenshot 2023-07-11 at 5 24 01 PM" src="https://github.com/wojtekmaj/react-pdf/assets/56488757/51162a60-b2ad-4c99-8639-2a648957ab7b">

### Steps to reproduce

Simply I have just added the code and when I am refreshing my development environment it is throwing this error.

### Expected behavior

As per the documentation this code should work but it is throwing error.

```
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url
).toString();
```

### Actual behavior

It should not throw the error as it does not when we use cdn. 

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by vdo9** [comment]
I am having an issue with setting up the web worker as well.
```SyntaxError: Cannot use 'import.meta' outside a module```

**Comment by wojtekmaj** [comment]
@BlankTurbo You didn't give me too many info to work with, but if I have to guess, you're trying to render React-PDF on the server side which doesn't make a lot of sense, because you can't stream canvas over the network anyway.

**Comment by wojtekmaj** [comment]
@vdo9 If you're using ESM modules, I'd discourage you from using Jest altogether. It has numerous problems with ESM modules handling.

Personally, I was not able to make it work well for my use case and have decided to move on to more modern [Vitest](https://vitest.dev/). Migrating multiple repositories took me less time than trying to debug Jest bugs in one.

**Comment by ashwinsquadstack** [comment]
My `'pdfjs-dist/build/pdf.worker.min.js'` is relatively at this `../../../../../node_modules/pdfjs-dist/build/pdf.worker.min.js` position from the place of `import.meta.url`. When I am using this, it is throwing me `Warning: Setting up fake worker.`. 
If I am trying to copy the file `'pdfjs-dist/build/pdf.worker.min.js' `and use it my repo it is throwing again the same warning.

**Comment by wojtekmaj** [comment]
If you manually copied the file over and it's still giving you `Warning: Setting up fake worker…` message it means that the path you specified was not correct. Check the Network tab in your browser to see where the pdf.worker.min.js file is being requested from, compare to where it actually is, and debug it this way.

**Comment by BlankTurbo** [comment]
> If you manually copied the file over and it's still giving you `Warning: Setting up fake worker…` message it means that the path you specified was not correct. Check the Network tab in your browser to see where the pdf.worker.min.js file is being requested from, compare to where it actually is, and debug it this way.

Found out the solution using this approach Thanks a lot!

**Comment by BlankTurbo** [comment]
I have one more issue which I faced recently not that big, that I will raise it in another issue, tagging it here only. 

When I was using react-pdf 6.2.2 version my code was working perfectly fine, recently when I updated my version to 7.1.2 it is not working on deployment. What error it is showing on AWS Amplify is `Error is: build size exceeding amplify supported size 200MB.`. Is there any bigger change in react-pdf 7.1.2 that this error is occurring because it does not use to occur before.

**Comment by ashwinsquadstack** [comment]
> > > If you manually copied the file over and it's still giving you `Warning: Setting up fake worker…` message it means that the path you specified was not correct. Check the Network tab in your browser to see where the pdf.worker.min.js file is being requested from, compare to where it actually is, and debug it this way.
> > 
> > 
> > Found out the solution using this approach Thanks a lot!
> 
> Could you please share the solution, What you did? I am still unable to figure it out. I am also facing the same issue.

@praveengoswami1996 Just use the correct file location it will work.

For me when I did it like this
 `pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  '../../../../../node_modules/pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url
).toString();`

It worked because the location of my `pdf.worker.min.js` relative to the file where I was adding it was `'../../../../../node_modules/pdfjs-dist/build/pdf.worker.min.js'` this.

Try this your issue should get resolved.

**Comment by praveengoswami1996** [comment]
> > > > If you manually copied the file over and it's still giving you `Warning: Setting up fake worker…` message it means that the path you specified was not correct. Check the Network tab in your browser to see where the pdf.worker.min.js file is being requested from, compare to where it actually is, and debug it this way.
> > > 
> > > 
> > > Found out the solution using this approach Thanks a lot!
> > 
> > 
> > Could you please share the solution, What you did? I am still unable to figure it out. I am also facing the same issue.
> 
> @praveengoswami1996 Just use the correct file location it will work.
> 
> For me when I did it like this `pdfjs.GlobalWorkerOptions.workerSrc = new URL( '../../../../../node_modules/pdfjs-dist/build/pdf.worker.min.js', import.meta.url ).toString();`
> 
> It worked because the location of my `pdf.worker.min.js` relative to the file where I was adding it was `'../../../../../node_modules/pdfjs-dist/build/pdf.worker.min.js'` this.
> 
> For me it worked like this because I use a monorepo and node_modules are hoisted and they were not inside my root folder. So do check the location of file `pdf.worker.min.js`.
> 
> Try this your issue should get resolved.

Thanks Ashwin!! I appreciate your response. It perfectly worked for me. Thanks alot.

**Comment by muboshers** [comment]
`useEffect(() => {
    pdfjs.GlobalWorkerOptions.workerSrc = new URL(
      'pdfjs-dist/build/pdf.worker.js',
      import.meta.url,
    ).toString();
  }, []);`
  
  problem statement like this because next js can not render outside of i just wrap  pdf.js config in app tsx like this and problem fix

**Comment by wojtekmaj** [comment]
A better idea than useEffect appears to be:

```ts
if (typeof window !== 'undefined') {
  pdfjs.GlobalWorkerOptions.workerSrc = new URL(
    'pdfjs-dist/build/pdf.worker.min.js',
    import.meta.url,
  ).toString();
}
```

This would prevent the code from running on the server, while still running before render on the client.
