### ISSUE TITLE
onLoadSuccess not fired with Uint8Array data

### ISSUE THREAD

**Issue by GManzato** [wojtekmaj/react-pdf#156]
I'm using react-pdf in a specific environement ( electron ) so I cannot load the file via http/https but from fs.
It seems that the onLoadSuccess is not fired, is it normal ?
I need to get the number of pages prior of rendering the first page.

**Comment by wojtekmaj** [comment]
Definitely not normal! Does the file load perfectly otherwise? Can you share your implementation of React-PDF here?

**Comment by GManzato** [comment]
Yes , the file is perfectly loaded.

Tried on the stable release and the 3 alpha.

```

**Comment by wojtekmaj** [comment]
That looks perfectly okay! Wonder if you get at least onSourceSuccess callback...!
By the way, I think you don't need to do this much work.

1. I believe whatever you get form `fs.readFile` will also be accepted.
2. `file={this.file}` should also be okay.

**Comment by GManzato** [comment]
thanks for the hint , I've changed to `componentDidMount`
* 1. Yep it work without the `Uint8Array `
* 2. No, I have an error when I try to load directly the file without passing the object.

I've found an hack , I just need to know the number of pages after I've loaded the first page , so I'm waiting for the renderSuccess of the first page to get the number of pages in the document state. I'm a bit busy on my project so I didn't get the time to debug this. I'm not sure it's because I'm running on electron or because I'm loading a local file. Anyway , I will keep you updated when I get the time to debug this.

**Comment by ericywl** [comment]
I believe I've got a similar problem. The code below does not work.

```
import React from 'react';
import { Document, Page } from 'react-pdf'

class Test extends React.Component {
    constructor(props) {
        super(props);
        this.fileReader = null;
        this.state = {
            fileArr: null
        };
    }

    handleFileRead(e) {
        const content = this.fileReader.result;
        this.setState({ fileArr: new Uint8Array(content) });
        console.log(this.state.fileArr)
    }
    
    handleFileChosen(file) {
        this.fileReader = new FileReader();
        this.fileReader.onloadend = this.handleFileRead.bind(this)
        this.fileReader.readAsArrayBuffer(file);
    }
    
    render() {
        return (
            <div className='box'>
                <Document file={this.state.fileArr}>
                    <Page pageNumber={1} />
                </Document>
            </div>
        )
    }
}

```

I get the following error from it.

```
Error: Invalid parameter object: need either .data, .range or .url
```

Am I doing anything wrong here?

**Comment by kairiruutel** [comment]
Having same issue when loading single page PDF, the callbacks `onLoadSuccess` & `onRenderSuccess` are not fired although document and page are loaded. Using v5.2.0.

```
<div>
	<div>
		<Document file={templateContent} onLoadSuccess={() => console.log('I am here')} >
			<Page pageNumber={1} onRenderSuccess={() => console.log('I am here')} />
		</Document>
	</div>
</div>
```

**Comment by xijiale** [comment]
I have the same problem. Have you found a good solution to your problem?

**Comment by wojtekmaj** [comment]
Is anyone able to provide repro in CodeSandbox or similar?
