### ISSUE TITLE
Example of text selection and annotation

### ISSUE THREAD

**Issue by pseudoPixels** [wojtekmaj/react-pdf#1560]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

It would be great if there is any complete example of text selection and annotation. I tried to create one reading the documents, but failed. The text overlap does not seem to work for me for text selection or annotation. Having a complete and simple example of it would be great help to follow along the existing documentations. Thank you

**Comment by wojtekmaj** [comment]
There are complete, functional examples in the repository. Granted, they are a little basic, but text selection will definitely work there.

**Comment by pseudoPixels** [comment]
Thank you for your reply. Can you please refer where the example of annotation and text selection is. I looked here but could not locate excatly: https://github.com/wojtekmaj/react-pdf/tree/main/sample 
many thanks

**Comment by pseudoPixels** [comment]
OK found it. We need to import the required style for it to work correctly like (import 'react-pdf/dist/esm/Page/TextLayer.css';). 

Documentation: import 'react-pdf/dist/esm/Page/TextLayer.css';

**Comment by jlia0** [comment]
@pseudoPixels Hey can you let me know which example it is? Thanks!
