### ISSUE TITLE
Failed to load PDF via url

### ISSUE THREAD

**Issue by walifaizy** [wojtekmaj/react-pdf#157]
I am using the same example as published in the repo, but it is giving error `Failed to load PDF file.
`

![screen shot 2018-02-21 at 6 11 56 pm](https://user-images.githubusercontent.com/17082693/36484491-e79f9f64-1732-11e8-8f61-8d732a1b05e6.png)

![screen shot 2018-02-21 at 6 16 51 pm](https://user-images.githubusercontent.com/17082693/36484668-6f1b7940-1733-11e8-8102-20bd6920bd70.png)

**Comment by wojtekmaj** [comment]
Have you read this? https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions#when-im-trying-to-load-a-pdf-file-from-an-external-source-im-given-a-message-failed-to-load-pdf-file
