### ISSUE TITLE
pdf文件是能正常通过浏览器打开的但是onLoadError捕获错误_.has is not a function导致加载失败

### ISSUE THREAD

**Issue by YueJingGe** [wojtekmaj/react-pdf#1573]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

import React, { useState, useEffect } from "react"
import Cookies from 'js-cookie'
import { Document, Page, pdfjs } from "react-pdf";

pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cat.net/ajax/libs/pdf.js/2.16.105/pdf.worker.js`

import WaterMaker from "@/components/Global/GlobalWaterMaker";
import { PdfBoxPropsType } from './interface'
import styles from './index.module.less'

/**
 * 展示pdf的盒子
 * @param props
 * @returns
 */
const PdfPreview = (props: PdfBoxPropsType) => {
  const { file, height } = props || {}
  const [total, setTotal] = useState(0)
  const [name, setName] = useState('专家姓名')
  const [scale, setScale] = useState<number>()

  useEffect(() => {
    getUserData()
    getScale()
  }, [])

  const getUserData = () => {
    if (Cookies.get('userData')) {
      const userData = JSON.parse(Cookies.get('userData'))
      if (!userData) return
      setName(userData?.name)
    }
  }

  const getScale = () => {
    //获取页面宽度
    let clientWidth = window.screen.width;
    //计算缩放比例(595为浏览器控制台获取到的原pdf的canvas属性的宽度，该属性导致pdf宽度无法适配页面宽度)
    let scale = (clientWidth / 1200).toFixed(2)
    setScale(Number(scale))
  }

  const onLoadSuccess = ({ numPages }: { numPages: number }) => {
    setTotal(numPages)
  }

  const onLoadError = (data: any) => {
    console.log('onLoadError=====1', data);
  }

  console.log('file===========', file);

  return <div className={styles.pdf_preview} style={{ height: height ? height : '500px' }} >
    <WaterMaker text={name}>
      <Document
        file={file}
        loading="文件加载中"
        noData={null}
        error="加载失败"
        className={styles.pdf_container}
        onContextMenu={(e: any) => e.preventDefault()}
        onLoadSuccess={onLoadSuccess}
        onLoadError={onLoadError}
      >

      </Document>
    </WaterMaker>
  </div>
}

export default PdfPreview

### Steps to reproduce

测试和预发环境都无法复现，正式会出现

### Expected behavior

无

### Actual behavior

无

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
English please

**Comment by YueJingGe** [comment]
I have resolved the issue by fixing the react-pdf version number

**Comment by YueJingGe** [comment]
> English please




My previous dependence was like this
```json
{"react-pdf": "^6.2.2"}
```
Now my dependence is like this 
```json
{"react-pdf": "6.2.2"}
```
