### ISSUE TITLE
Module not found: Package path ./dist/esm/entry.webpack is not exported from package (...).github.io\node_modules\react-pdf

### ISSUE THREAD

**Issue by rroell** [wojtekmaj/react-pdf#1575]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When using the example code:
```"use client";
import { useState } from "react";
import { Document, Page } from "react-pdf/dist/esm/entry.webpack";

const App = () => {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  const onDocumentLoadSuccess = ({ numPages }) => {
    setNumPages(numPages);
  };

  const goToPrevPage = () =>
    setPageNumber(pageNumber - 1 <= 1 ? 1 : pageNumber - 1);

  const goToNextPage = () =>
    setPageNumber(pageNumber + 1 >= numPages ? numPages : pageNumber + 1);

  return (
    <div>
      <nav>
        <button onClick={goToPrevPage}>Prev</button>
        <button onClick={goToNextPage}>Next</button>
        <p>
          Page {pageNumber} of {numPages}
        </p>
      </nav>

      <Document file="document.pdf" onLoadSuccess={onDocumentLoadSuccess}>
        <Page pageNumber={pageNumber} />
      </Document>
    </div>
  );
};

export default App;
```

I get the following error:
```
./pages/cv.js:3:0
Module not found: Package path ./dist/esm/entry.webpack is not exported from package (...).github.io\node_modules\react-pdf (see exports field in (...).github.io\node_modules\react-pdf\package.json)
  1 | "use client";
  2 | import { useState } from "react";
> 3 | import { Document, Page } from "react-pdf/dist/esm/entry.webpack";
  4 | 
  5 | const App = () => {
  6 |   const [numPages, setNumPages] = useState(null);

https://nextjs.org/docs/messages/module-not-found
```

### Steps to reproduce

Run the code above.

### Expected behavior

Show the example PDF.

### Actual behavior

Returns the error.

### Additional information

react-pdf@7.3.0

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: react-pdf@7.3.0
- **React version**: react@18.2.0
- **Webpack version (if applicable)**: webpack@5.88.2

**Comment by wojtekmaj** [comment]
https://github.com/wojtekmaj/react-pdf/wiki/Upgrade-guide-from-version-6.x-to-7.x
