### ISSUE TITLE
Cannot set properties of undefined (setting 'workerSrc')

### ISSUE THREAD

**Issue by stauersbol** [wojtekmaj/react-pdf#1579]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The bug I'm encountered now is one that appeared after the ESM module compat and the latest release.

```json
- error Error [TypeError]: Cannot set properties of undefined (setting 'workerSrc')
    at file:///home/stauersbol/Projects/dws-drawing-viewer/node_modules/react-pdf/dist/esm/index.js:11:37
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  digest: undefined
}
```

### Steps to reproduce

1. Setup a basic Next project and implement the recommended way of setting up `react-pdf` (In this case I'm using the `unpkg.com` for this, but I have same issue using the new URL way) 
2. Run next dev
3. See the error when you load the site in your console

### Expected behavior

Site loads properly and the PDF loads in.

### Actual behavior

Next shows the error page with the error message.

### Additional information

![image](https://github.com/wojtekmaj/react-pdf/assets/9026132/6270b3ea-797c-4c28-9534-22937106e9d6)
This image should show the issue I'm facing.

![image](https://github.com/wojtekmaj/react-pdf/assets/9026132/87a838df-5373-42f8-ac69-dd07e05ba806)
Same error in Browser Console.

Extra info:
I'm using Next to run this. This is for a niche use case, due to the API.

How I setup workerSrc reference to the part where I mention unpkg:
`pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js``

### Environment

- **Browser (if applicable)**: Opera
- **React-PDF version**: 7.3.2
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
I just love dual ESM/CJS packages 🫠

Try v7.3.3, works for me!

**Comment by stauersbol** [comment]
I will give it a try tomorrow when I get it at work!
Thank you for fixing it so fast @wojtekmaj!

**Comment by stauersbol** [comment]
Hey @wojtekmaj
It is working as expected now, thank you for the quick fix!

**Comment by wojtekmaj** [comment]
<img width="419" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/5426427/8cbfe9a7-3703-4a5c-9981-8a761419c6b7">
