### ISSUE TITLE
Destination

### ISSUE THREAD

**Issue by fatmirsukaliq** [wojtekmaj/react-pdf#158]
Hi,
Is it possible to navigate to a certain destination name?
I see PDF JS has it using #dest link

**Comment by wojtekmaj** [comment]
Not at the moment, sadly. You need to figure out on your own what destination corresponds to what page. If you need a hand at that, OutlineItem component provided by React-PDF does just that, so you can implement it, if you have `pdf` object (which you do, from onLoadSuccess callback).

That should be your starting point: https://github.com/wojtekmaj/react-pdf/blob/master/src/OutlineItem.jsx#L51
