### ISSUE TITLE
Page onLoadSuccess does not receive PDFPageProxy

### ISSUE THREAD

**Issue by jacksteamdev** [wojtekmaj/react-pdf#159]
It seems that the object being passed to `Page onLoadSuccess` is a generic object. It has all the properties of a `PDFPageProxy`, but inherits directly from Object. Any methods like `getTextContent` or `pageNumber` are not available. Here's an error:

```
page.getTextContent is not a function TypeError: page.getTextContent is not a function
    at App._this.onPageLoad (App.js:52)
    at callIfDefined (util.js:151)
    at Page._this.onLoadSuccess (Page.js:90)
    at <anonymous>
```

In `Pages.jsx:161`, I think we're losing the page prototype in the `pageCallback` getter when we spread the page object:

```
get pageCallback() {
  const { page } = this.state;
  const { scale } = this;

  return {
    ...page,  //  the return object is not a PDFPageProxy anymore...
    // Legacy callback params
    get width() { return page.view[2] * scale; },
    get height() { return page.view[3] * scale; },
    scale,
    get originalWidth() { return page.view[2]; },
    get originalHeight() { return page.view[3]; },
  };
}
```

I was thinking about putting together a pull request. Do you have a preferred way to clone objects? Let me know, thanks!

**Comment by wojtekmaj** [comment]
I think legacy callbacks may be removed in version 3.0, so I'd just return plain page object. What do you think?

**Comment by jacksteamdev** [comment]
Sounds good!

**Comment by wojtekmaj** [comment]
Hi, sorry for the wait.
I'm looking into this and I think plain Object.assign, even though it adds methods to the original page object, works just fine. Do you have any smarter idea than this?
