### ISSUE TITLE
customTextRenderer is not called

### ISSUE THREAD

**Issue by mixeden** [wojtekmaj/react-pdf#1593]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Well, customTextRenderer is not called! 

My guess is because of this particular line:
https://github.com/wojtekmaj/react-pdf/blob/v7.3.3/src/Page/TextLayer.tsx#L222

It seems that this layer has some marked content, but it is above the text I'm talking about (see "steps to reproduce"). 
It should not affect the text being rendered in any way.

### Steps to reproduce

1. Load this https://arxiv.org/pdf/1905.09263.pdf, navigate to page 4, check if your customTextRenderer is called on a text that starts with "sequence in speech tasks. We evaluate", for example.

### Expected behavior

customTextRenderer is called

### Actual behavior

customTextRenderer is not called

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by picasocro1** [comment]
I have exactly the same problem. For [this](https://www.volvogroup.com/content/dam/volvo-group/markets/master/about-us/company-values/code-of-conduct-other-policies/vg-code-of-conduct-en.pdf) particular pdf defined `customTextRenderer` is not called.

The method was executed correctly on the other pdf I worked on so far  (using exactly the same code).

**Environment**
Browser (if applicable): Chrome ver. 116
React-PDF version: 7.3.3
React version: 18.2.0
Webpack version (if applicable): -

**Comment by mixeden** [comment]
What is even more funny, it works on the majority pages of the PDF I attached in the reproduction section except a page number 4. I guess this is because this particular page had elements with class "markedContent" in it somewhere to the top. Please check if your PDF from Volvo also has elements of the same class in problematic places

**Comment by frontendphil** [comment]
Yup, I can confirm that marked content seems to have something to do with it. AFAICT, the moment this lib sees `.markedContent,` it assumes that all text of that layer is inside the `.markedContent` element. However, in our case, these are just empty blocks. https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/src/Page/TextLayer.tsx#L207

**Comment by hdwatts** [comment]
Yes having this same issue with markedContent!
