### ISSUE TITLE
PageTextContent filtering functionality

### ISSUE THREAD

**Issue by apla** [wojtekmaj/react-pdf#160]
Hi, I would like to add filtering functionality to the `Page`'s `TextContent`. When `onGetTextSuccess` returns modified data, this data will be used for the text content of page.

It is will be really useful for badly exported PDF with text columns. For example, if pdf contains page with two columns, but text misplaced and PDF Text Contents have structure like 
```
[
{col:1, row:1}, 
{col:2, row:1}, 
{col:1, row:2}, 
{col:2, row:2}, 
]
```

or another weird cases (try to select text from `Device Information` to the table contents from [this](http://www.ti.com/lit/ds/symlink/ina219.pdf) PDF). I can detect those cases programmatically and correct them.

Another case is for rendering texts such as I²C or H<sub>2</sub>O

If you're ok with those additions I will submit pull request.

**Comment by wojtekmaj** [comment]
Hmmm. I have nothing against it, but I wonder how it would look like. Would you share some potential implementation for me to get the idea on what you're trying to achieve?

**Comment by wojtekmaj** [comment]
Hey @apla,
As of v3.0.0, react-pdf supports custom text rendering. You are given as much data as I have myself about text items to render. Sadly, there's no such thing as row/column in PDFs, only x and y positions, but I'd love to hear what you think!
