### ISSUE TITLE
Slavic characters

### ISSUE THREAD

**Issue by markoboras0712** [wojtekmaj/react-pdf#1603]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I can't render with any font (my font imported, from cdn imported and your default fonts as Courier, Helvetica) characters:
`čćđšž`

### Steps to reproduce

![image](https://github.com/wojtekmaj/react-pdf/assets/75808588/2f99ba34-d9bc-4d34-a6f7-9eef12e23dbc)

I get in my pdf

<img width="262" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/75808588/87631884-fe5f-4dfd-bb30-78a1ebe1688d">

### Expected behavior

I got in render čćđšž

### Actual behavior

I get šž

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: 3.1.12
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.

**Comment by markoboras0712** [comment]
Thanks. Both repos have same name but different author... 😄
