### ISSUE TITLE
SVG colors are changed on edges

### ISSUE THREAD

**Issue by mjpolak** [wojtekmaj/react-pdf#1607]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

SVG's edges colors are malformed - they are different than expected.

It looks like border shading but, the border is disabled.

![image](https://github.com/wojtekmaj/react-pdf/assets/10635037/22547383-3dc4-46bb-9f98-3f936e9e95bf)

### Steps to reproduce

Add SVG to a page:
```
    <Svg  style={{ width: "10mm", height: "7mm",backgroundColor:"yellow",borderWidth:0 }} viewBox="0 0 1000 700">
          <Path
            d="M 0 0 Q 0 1 1 1 Q 2 1 2 2"
            stroke={primeColor}
            strokeWidth="0.4"
            transform="translate(175 200)
            scale(250 255)
            "
          />
          <Circle
            cx="175"
            cy="175"
            r="150"
            fill={primeColor}
            stroke="white"
            strokeWidth="25"
          />
        </Svg>
```

### Expected behavior

Edge pixel's color aren't changed.

### Actual behavior

Colors on edge pixels are changed.

### Environment

- **Browser (if applicable)**: Chrome 116.0.5845.180
- **React-PDF version**: 3.1.12
- **React version**: 18.2.0
- **Webpack version (if applicable)**: Not used

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
