### ISSUE TITLE
react-pdf v7.4.0 significantly increased build time

### ISSUE THREAD

**Issue by keremcanb** [wojtekmaj/react-pdf#1618]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

We are developing a create-react-app based SPA. Before, our Bamboo builds took about 10 minutes to complete. After installing and began using react-pdf v7.4.0, builds are taking about 15-20 minutes to complete. 

### Steps to reproduce

1. Install react-pdf v7.4.0
2. Add this line to scripts section of package. json: 
`"prebuild": "cp ./node_modules/pdfjs-dist/build/pdf.worker.js public/js"`
3. Use it like this:
```
    useEffect(() => {
        pdfjs.GlobalWorkerOptions.workerSrc = `${process.env.PUBLIC_URL}/js/pdf.worker.js`;
    }, []);
```

### Expected behavior

Builds to complete in 10 minutes.

### Actual behavior

Builds to complete in 15-20 minutes.

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 7.4.0
- **React version**: 17.0.2
- **Webpack version (if applicable)**: 5.88.2

**Comment by wojtekmaj** [comment]
On my sample repo, I have not noticed build time jumping significantly. Certainly not by 5-10 minutes, where the build itself takes about 5 seconds. Might be something specific to your configuration. However, without any knowledge what happens during your build, and without a reproducible example, I will not be able to help you out with Webpack performance problem you're having.

Wild guess, you may be unnecessarily transpiling dependencies with some super slow tools. Double check your config.
