### ISSUE TITLE
Pdf Render Error, if any AdBlocker or VPN extension be activated in my browser.

### ISSUE THREAD

**Issue by Paiman-Rasoli** [wojtekmaj/react-pdf#1621]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi Guys, I have successfully rendered my PDF document using `react-pdf` but when I activate an ad blocker/VPN chrome extensions the PDF file will fail to render and the error code which I see in console is:
`net:ERR_BLOCKED_BY_CLIENT`

The file is coming from `s3`.
Why should add blockers or VPN extensions should be a problem for `react-pdf`?

Here is my code:
```javascript
'use client';

import 'react-pdf/dist/Page/AnnotationLayer.css';
import 'react-pdf/dist/Page/TextLayer.css';

import { useState } from 'react';
import { Page, pdfjs, Document } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

const options = {
  cMapUrl: 'cmaps/',
  cMapPacked: true,
  standardFontDataUrl: 'standard_fonts/',
};

interface PdfViewerProps {
  source: string;
}
interface PdfMeta {
  numPages: number;
  pageNumber: number;
  isLoaded: boolean;
}

export const PdfViewer = ({  source }: PdfViewerProps) => {
  
  const [pdfMeta, setPdfMeta] = useState<PdfMeta>({
    numPages: 0,
    pageNumber: 1,
    isLoaded: false,
  });

  const onDocumentLoadSuccess = () => {
    // set page number ..
  }

  return (
    <>
          <Document
            file={source} // https://storage-s3.com/file/fileName.pdf
            options={options}
            onLoadSuccess={onDocumentLoadSuccess}
          >
            <Page
              pageNumber={pdfMeta.pageNumber}
              scale={1.5}
              renderAnnotationLayer={true}
              renderTextLayer={true}
            />
          </Document>
    </>
  );
};
```

### Steps to reproduce

Install any Ad blocker or VPN for chrome.
Activate the extension and try to render the PDF document.

### Expected behavior

I expect that AdBlocker or VPN should not cause error.

### Actual behavior

Throws `net:ERR_BLOCKED_BY_CLIENT`

### Environment

- **Browser**: Chrome- Version 117.0.5938.92 (Official Build) (64-bit)
- **React-PDF version**: 7.0.0
- **React version**: 18.2.0
- **NextJs Version**: 13.4.1
- **Webpack version**: 5
- **NODE**: 18.17.1

**Comment by wojtekmaj** [comment]
Your ad blocker blocking network requests is not React-PDF concern. If you think some requests are mistakenly blocked, report it to whoever created the rulesets.
