### ISSUE TITLE
Performance rendering in canvas for certain pdf files

### ISSUE THREAD

**Issue by GunterJameda** [wojtekmaj/react-pdf#1634]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I'm not exactly sure this qualifies as a bug or not, but this is something I faced when parsing a pdf page to png, which uses the exact same method as to render the page in a canvas and after we export it to base64.

The warning message I'm getting is this:

```
Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently.
```

I fixed it by adding a prop in the canvas render context that indicated that it will be read often and the problem went away.

```typescript
const context = canvas.getContext("2d", {
  willReadFrequently: true,
});
```

Is it possible to find a way to pass this as a prop or something similar?

I can provide a file as a way to get the test done, but I can't assure the message will popup, since it's an on and off situation.

### Steps to reproduce

We need a file that would throw this error and then we should render it and check console.

### Expected behavior

Not having the warning message

### Actual behavior

We have the warning message

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 7.3.3
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by GunterJameda** [comment]
[brita-tapfilter-instruction-manual-EN.pdf](https://github.com/wojtekmaj/react-pdf/files/12894594/brita-tapfilter-instruction-manual-EN.pdf)

This file is a good way of seeing what's going on. Check console after opening it.

**Comment by Heilemann** [comment]
I see this error all the time, for what it's worth.
