### ISSUE TITLE
Getting sentry "t.split("+").at is not a function. (In 't.split("+").at(-1)', 't.split("+").at' is undefined"

### ISSUE THREAD

**Issue by harryi3t** [wojtekmaj/react-pdf#1638]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

We have been using react-pdf for a while now.
Recently we migrated from 5.5.0 -> 7.2.0 and we started seeing a lot of [sentry](https://sentry.io/) errors.

The error message in all these sentries is the same
> t.split("+").at is not a function. (In 't.split("+").at(-1)', 't.split("+").at' is undefined

Since the react-pdf code is minified, I couldn't find the exact line from where this error is coming up.
I then checked out the code in my local and tried searching for the keyword `split` but didn't find any useful there.
<img width="450" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/5207331/9d693e7e-9fdd-41fd-98d7-65d76c3be3c9">

Maybe the error is coming from some dependency of reacy-pdf itself? I wonder if anyone else is facing the same issue.

### Steps to reproduce

The issue happens without interacting with any pdf.
Just by loading our home page we are seeing this error.

### Expected behavior

We shouldn't see this error.

### Actual behavior

We see this error
>  t.split("+").at is not a function. (In 't.split("+").at(-1)', 't.split("+").at' is undefined

### Additional information

The stack trace from sentry 
<img width="1727" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/5207331/6f5e4cde-9781-4a57-b0ba-d8f00c79f7c2">

### Environment

- **Browser (if applicable)**: n/a
- **React-PDF version**: 7.5.0
- **React version**: n/a
- **Webpack version (if applicable)**: n/a

**Comment by wojtekmaj** [comment]
That may be 🤷‍♂️ `Array.at`, however, is [supported by all modern browsers](https://caniuse.com/array-flat), including all which React-PDF [currently supports](https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/README.md#browser-support).

> Browser (if applicable): n/a

Given that you didn't provide this info, I'm assuming the above response is correct and you're seeing these reports coming from legacy browsers. Happy to reopen if proven otherwise.
