### ISSUE TITLE
UMD Support

### ISSUE THREAD

**Issue by dima007arenko** [wojtekmaj/react-pdf#1639]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

Could you please add support of UMD packages, because I'm able to use it only through CDN and ESM and EJS is not an option :(

**Comment by wojtekmaj** [comment]
Hey! UMD is not something I have experience with, and I have no knowledge on how would I even test if the builds are working correctly. If you know how to do this, feel free to contribute.
