### ISSUE TITLE
Incorrect alignment in html list bullets

### ISSUE THREAD

**Issue by NatashaOsipenko** [wojtekmaj/react-pdf#1646]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi,
I am using react-pdf and react-pdf-html to create a pdf.
My pdf contains html text with list, wrapped in tag `<Html>`

`import { Document } from '@react-pdf/renderer'`
`import Html from 'react-pdf-html'`

`const htmlTextWithList = <div>Datenimport gem&auml;ss vorheriger Definition</div><ul><li>Definition Importformat</li><li>Import der angelieferten Kontaktdaten f&uuml;r weiteren Einsatz in colada</li><li>Anlieferung der Daten in Excel oder CSV</li><li>Qualit&auml;t der Daten muss durch Auftraggeber sichergestellt werden</li></ul>`

`<Document>`
`...`
`<Html>{htmlTextWithList}</Html>`
`...`
`</Document>`

As as result I have following problem. Bullets have incorrect alignment
<img width="490" alt="Screenshot 2023-10-19 at 18 52 44" src="https://github.com/wojtekmaj/react-pdf/assets/44640703/eb8dccb3-650e-4395-98ef-1124b961adc6">

Could you please assist with it?

### Steps to reproduce

`import { Document } from '@react-pdf/renderer'`
`import Html from 'react-pdf-html'`

`const htmlTextWithList = <div>Datenimport gem&auml;ss vorheriger Definition</div><ul><li>Definition Importformat</li><li>Import der angelieferten Kontaktdaten f&uuml;r weiteren Einsatz in colada</li><li>Anlieferung der Daten in Excel oder CSV</li><li>Qualit&auml;t der Daten muss durch Auftraggeber sichergestellt werden</li></ul>`

`<Document>`
`...`
`<Html>{htmlTextWithList}</Html>`
`...`
`</Document>`

### Expected behavior

Bullets should be aligned correctly

### Actual behavior

Bullets are aligned incorrectly

### Environment

- **Browser (if applicable)**: Chrome Version 116.0.5845.187
- **React-PDF version**: 3.1.12
- **React version**: 18.2.0
- **Webpack version (if applicable)**:5.75.0
- **react-pdf-html version**:1.1.18

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
