### ISSUE TITLE
QR code component

### ISSUE THREAD

**Issue by web-shoharab-pk** [wojtekmaj/react-pdf#1647]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

Last time I was working on one invoice solution system. I used the React-PDF package for PDF creation, printing, and downloading. I faced one issue when using a QR code on my pdf.  However, I didn't get any solution to using QR code in the React-PDF component. My request is If possible please creat a component link View or Text for QR code. 

Thank you

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.

**Comment by web-shoharab-pk** [comment]
How can I create the QR code in React PDF?
