### ISSUE TITLE
Pagination using react-pdf

### ISSUE THREAD

**Issue by terrabl** [wojtekmaj/react-pdf#165]
I was wondering if someone could help me get pagination set up with my PDF's, I tried to follow the steps from this [issue](https://github.com/nnarhinen/react-pdf/issues/47) but what unable to figure out a solution.  It also said that pagination would be coming with v2.0.0 but I was unable to find an example of it. 

I am currently loading my PDF onto the page successfully using the following code: 

```
       <Document
           file={`data:application/pdf;base64,${this.state.base64}`}
        >
          <Page pageNumber={this.state.pageNumber} />
        </Document> 
```

I was wondering if someone could help me set up pagination for my PDF's, or point me in the right direction.

**Comment by wojtekmaj** [comment]
Hey @terrabl,
what is your issue exactly? The code looks fine.

**Comment by terrabl** [comment]
@wojtekmaj My issue is that when I load the PDF it only shows the first page and does not allow for pagination.

Would following this example from the readme give me the results I want? 

```
class MyApp extends Component {
  state = {
    numPages: null,
    pageNumber: 1,
  }

  onDocumentLoad = ({ numPages }) => {
    this.setState({ numPages });
  }

  render() {
    const { pageNumber, numPages } = this.state;

    return (
      <div>
        <Document
          file="somefile.pdf"
          onLoadSuccess={this.onDocumentLoad}
        >
          <Page pageNumber={pageNumber} />
        </Document>
        <p>Page {pageNumber} of {numPages}</p>
      </div>
    );
  }
}
```

I notice it has that manipulart pageNumber but how does a user change the page of the PDF?

**Comment by wojtekmaj** [comment]
You need to write mechanism of changing `pageNumber` yourself. The easiest is

```js
<button onClick={() => this.setState(prevState => ({ pageNumber: prevState.pageNumber + 1 }))}>
Next page
</button>
```

I think you misunderstood what was implemented in 2.x branch. Starting with 2.x, you can display more than one page by placing several `<Page>` components. You decide which page is going to be rendered inside them using `pageNumber` prop.

**Comment by terrabl** [comment]
@wojtekmaj Well that was easy! Thanks for the help, I feel like I should have been able to figure that out on my own.

**Comment by wojtekmaj** [comment]
No worries ;) in test suite I have way much fun with this library for testing purposes, if you need to see what's also possible, check it out. https://github.com/wojtekmaj/react-pdf/blob/master/test/

**Comment by ffurkAn** [comment]
Is there anyway to get page number while scrolling the document ? I suppose this question is not react-pdf specific. But your experience might help :) @wojtekmaj

**Comment by 1Jesper1** [comment]
@wojtekmaj Nice! Thanks for the paging implementation.
Reference: https://github.com/wojtekmaj/react-pdf/blob/4073a31bf2bba6e48cf09e799d8f6f861cc92eac/test/Test.jsx#L303

**Comment by MeghanBibb** [comment]
> You need to write mechanism of changing `pageNumber` yourself. The easiest is
> 
> ```js
> <button onClick={() => this.setState(prevState => ({ pageNumber: prevState.pageNumber + 1 }))}>
> Next page
> </button>
> ```
> 
> I think you misunderstood what was implemented in 2.x branch. Starting with 2.x, you can display more than one page by placing several `<Page>` components. You decide which page is going to be rendered inside them using `pageNumber` prop.

How did you show the fancy arrow buttons in your example here https://projects.wojtekmaj.pl/react-pdf/ ?

**Comment by qaisershehzad** [comment]
@wojtekmaj  Can we add page navigation while displaying all pages.. like I want to show a modal or side outline with list of all pages and user can select any page number to navigate.. or user can scroll as well at the same time ?

tx

**Comment by mohnishmonu** [comment]
@wojtekmaj can we implement prev/next functionality when all the pages are loaded instead of single page load. something like below 

<Document
          file={url}
          onLoadSuccess={onDocumentLoadSuccess}
          options={{ workerSrc: "pdf.worker.js" }}
        >
          {Array.from(new Array(numPages), (el, index) => (
            <Page key={`page_${index + 1}`} pageNumber={index + 1} />
          ))}
        </Document>

for above snipper I want to implement prev/next

**Comment by wojtekmaj** [comment]
You will need to store references to each page, or assign them some IDs, and use [`Element.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) to scroll to a given page.
