### ISSUE TITLE
customTextRenderer not called on blob URLs?

### ISSUE THREAD

**Issue by jsong-eq** [wojtekmaj/react-pdf#1650]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi, I read up docs and the recipes for text highlight. 

I'm on version `"react-pdf": "^7.3.3",`

I'm using highlight text recipe as-is. It works if I test with a local pdf file - as

```
                         <Document file={"/public/sample.pdf"}>
```

text highlighting works. However, I'm rendering <Document> with url generated from blob - I do not see the text customTextRenderer called at all.

```
      api
        .getDocImage({
          uri,
        })
        .then((response: any) => response.blob())
        .then((blob: Blob | MediaSource) => {
          setPDFfile(blob); // type is application/pdf
          setPDFfile(URL.createObjectURL(blob)); // generated URL 
        });
```

I have tried highlight recipe on local pdf - that works great.
However, trying to use customTextRenderer on a return pdf blob like above, customTextRender is not called.

### Steps to reproduce

1. Copy code from highlight text recipe
2. Get a pdf file from blob 
3. save the blob as pdf OR createObjectURL (both do not work)
4. confirm customTextRenderer is not called

### Expected behavior

CustomTextRenderer should be called 

### Actual behavior

CustomTextRenderer is ignored on Page component. 

### Additional information

![image](https://github.com/wojtekmaj/react-pdf/assets/121055163/c9fc27d2-0aff-4c4c-bd9c-29cc61acd233)

Is sample screenshot to show pdf blob.

### Environment

- **Browser (if applicable)**: Chrome Version 118.0.5993.70 (Official Build) (arm64)
- **React-PDF version**: 7.3.3
- **React version**: 17.0.0
- **Webpack version (if applicable)**: N/A

**Comment by wojtekmaj** [comment]
Is there a chance you could create a reproducible example e.g. on CodeSandbox?

**Comment by jsong-eq** [comment]
https://codesandbox.io/s/pdf-js-createobjecturl-forked-ktlxkg?file=/src/App.js:0-2337

Is the closest I could get - but having trouble getting blob url working on codesandbox. Do you maybe have an example lying around that should work with blob URLs? If so, I should be able to quickly patch it in above ^

Thanks for checking the issue!

**Comment by jsong-eq** [comment]
Just on looking onto more - TextLayer is failing on blob pdf. 

![image](https://github.com/wojtekmaj/react-pdf/assets/121055163/0193aecb-7a38-4512-b8b6-170f9703f984)

Is the error I get, will update if I learn some more.

**Comment by jsong-eq** [comment]
I'm actually suspecting that TextLayer gets lost during PDF file -> bytestream -> blob -> react-pdf process, but not sure how I can prove

**Comment by wojtekmaj** [comment]
"TextLayer task cancelled" sounds to me like something caused the TextLayer to update mid-render. Now, what could it be... 🤔

**Comment by jsong-eq** [comment]
Yeah I doubt that this is actually a problem from the library itself - mb! At least until I can prove that the issues is from the react-pdf - I'll close this out. Thanks
