### ISSUE TITLE
TypeError: Cannot set property 'workerSrc' of undefined

### ISSUE THREAD

**Issue by srininmkl** [wojtekmaj/react-pdf#166]
Till yesterday our application was working fine.  When we deployed our application in a server today it throwing this "TypeError: Cannot set property 'workerSrc' of undefined" error.

we only included this 
`import { Document, Page } from 'react-pdf';` into our project. it was working fine. suddenly it is behaving dfifferent

Please help us to resolve this issue.
1. We are using create-react-app client.
2. I also tried to move pdf.worker.js into build folder. (this have not resolved our issue )
3. we are using react-pdf version 2.5.2

Please find attached file for reference. 
![error-react-pdf](https://user-images.githubusercontent.com/18455368/36972337-c0178d60-2094-11e8-97b0-58fc991789a2.PNG)

**Comment by srininmkl** [comment]
we are using react-pdf :  2.5.2 version.

**Comment by wojtekmaj** [comment]
Hi,
Mozilla introduced breaking changes in their library and React-PDF 2.5.2 can no longer work properly. Identical version but with fixed version of Mozilla's code is released here:

https://github.com/wojtekmaj/react-pdf/releases/tag/v2.5.3

Please update - this should help you.
