### ISSUE TITLE
Broken in pdfjs-dist  4.0.189

### ISSUE THREAD

**Issue by mashirozx** [wojtekmaj/react-pdf#1660]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

they are now using mjs in their build, which results in error.

### Steps to reproduce

```ts
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
    'pdfjs-dist/build/pdf.worker.min.mjs',
    import.meta.url,
  ).toString();
```

### Expected behavior

should load the worker normally

### Actual behavior

the browser complains about the mjs module

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
You should not use another pdfjs-dist version than the one that comes with React-PDF. 

With pdfjs-dist hitting 4.0 it's obvious some breaking changes are expected, but unfortunately Mozilla was notoriously not adhering to semver and introducing breaking changes in minor updates, therefore pdfjs-dist version is locked at a specific version.

Fear not though, we'll catch up!
