### ISSUE TITLE
The customTextRenderer function is not called for the page if PDF file has links in that page (reference paragraph in same pdf)

### ISSUE THREAD

**Issue by ShubhamSingh19** [wojtekmaj/react-pdf#1661]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The customTextRenderer function is not called for the page if PDF file has links in that page (reference paragraph in same pdf). Else it is working normal, highlighting conditional text.

### Steps to reproduce

1. Display a PDF that has links on few pages.
2. Use customTextRenderer as `<Page customTextRenderer={textRenderer}></Page>`
3. Mark every page (whole) using textRenderer function, sample below.
 `const textRenderer = useCallback(
        (textItem) =>
             <mark>{textItem}</mark>,
        [pageNumber]
    );`
5. You will see that pages with links will not be marked as customTextRenderer function is not called for that page. Other normal pages are marked properly.

### Expected behavior

All pages should be marked. Even with links.

### Actual behavior

Pages that contain link do not highlight the text layer.

### Additional information

"react-pdf": "^7.3.3",

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
First of all, this code can't work - the correct way to mark every single text would be:

```ts
  const customTextRenderer = useCallback(
    (textItem: { str: string }) => `<mark>${textItem.str}</mark>`,
    [],
  );
```

Secondly, I couldn't reproduce that with my test PDFs. Therefore I'm going to close this for now until a reproducible example is provided. Thanks for understanding.
