### ISSUE TITLE
Use 2 version of react-pdf in 1 project

### ISSUE THREAD

**Issue by nmaddp1995** [wojtekmaj/react-pdf#1663]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

I am using react-pdf v5 to display PDF files.
But when I applied text-layer, the v5 misaligned a lot of text so I decided to use react-pdf v7 instead.
Now I want to keep all other react-pdf instances at v5, only the component I apply text-layer apply v7.

Is there any way I can do that?

**Comment by prokutenb8x** [comment]
Yes, I also encountered this problem too. I try to set up but it didn't work

**Comment by wojtekmaj** [comment]
Why not go v7 all the way?

**Comment by prokutenb8x** [comment]
Currently, our app is really big and relevant to a lot of other apps in the same project so we don't want to affect

**Comment by prokutenb8x** [comment]
Currently, our app is really big and relevant to a lot of other apps in the same project, so we don't want it to affect other parts.
