### ISSUE TITLE
Error caused by conflict with react-file-viewer

### ISSUE THREAD

**Issue by themanojkum** [wojtekmaj/react-pdf#167]
I am trying to open a pdf file from a url, when i am opening the url directly on the browser it is opening fine, but using react pdf it is throwing an error : {name: "UnknownErrorException", message: "The API version "undefined" does not match the Worker version "2.0.305".", details: "Error: The API version "undefined" does not match the Worker version "2.0.305"."}

**Comment by wojtekmaj** [comment]
Do you use the newest stable release of react-pdf? There were important fixes in the last minor release.

**Comment by themanojkum** [comment]
i just install it again.. still the same error..

**Comment by themanojkum** [comment]
this is how i am importing : import { Document, Page, setOptions } from "react-pdf/build/entry.webpack";
version is: "react-pdf": "^2.5.3",

**Comment by themanojkum** [comment]
It turns out this is conflicting with this "react-file-viewer " module, i have another app i am using react pdf with the same way and it is working fine in there,
when i am importing using "react-pdf" only it is giving me the error of this "react-file-viewer " module.

**Comment by wojtekmaj** [comment]
I'm afraid react-file-viewer uses the old version of the same library, pdfjs-dist, which we use for rendering PDFs. For now, I can only suggest giving them a hind they should update (should be fairly easy!) or ( :( ) downgrade react-pdf to v2.1.7 - which used similar version of pdfjs-dist as react-file-viewer uses so it might just work.

**Comment by themanojkum** [comment]
I downgraded the react-pdf version, but making any changes

**Comment by wojtekmaj** [comment]
Anyways, you should probably let the guys from react-file-viewer know. Maybe they will upgrade so that there's no more version conflict.

I am a little uneasy about this, anyway. PDF.js is a very fragile thing to work with, I doubt running two instances simultaneously is a good idea.
