### ISSUE TITLE
Give option to remove hyphen when text wraps to a new line

### ISSUE THREAD

**Issue by RichMatthews** [wojtekmaj/react-pdf#1679]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I have an issue when displaying an email in a pdf. when it wraps over to a new line it adds a hyphen.
`test@gmail.com`
becomes
```
test@gm-
ail.com
```
so now it looks like the email contains a `-` when of course, it does not.

how is this fixed in react-pdf? I don't immediately see any good solution. 

```
Font.registerHyphenationCallback(word => {
  // Return entire word as unique part
  return [word];
});
```
doesn't seem to work as it applies it to all text but I just want it applied specifically to one string 
### Steps to reproduce

Render a string and cause it to wrap over multiple lines 

### Expected behavior

the option to at least say, do not show a hyphen 

### Actual behavior

it shows a hyphen 

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by SunnySze0000** [comment]
+1

**Comment by RichMatthews** [comment]
@wojtekmaj any solution for this?

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
