### ISSUE TITLE
UnknownErrorException

### ISSUE THREAD

**Issue by solaomosola** [wojtekmaj/react-pdf#169]
Hello Wojtekmaj,
I have successfully loaded my pdf in a browser. But when I used it in Cordova, it gave "UnknownErrorException: Failed to load".
Any ideas to help fix this? Or what can cause this kind of exception?
Thanks in advance.

**Comment by solaomosola** [comment]
Hi Wojtekmaj,
Updates - the error was as a result of "file not found", I think the path was changed after building the app for production. I tested it with a small pdf file, by converting the file to base64 string. It loaded well in the Cordova app. Now I need to include a 7mb pdf file as a base64 string. Any suggestions to make that work? React would not load the string directly because of the size. Thank you again for a great work you did with that.

**Comment by wojtekmaj** [comment]
Hello @solaomosola,
I sadly have no deep knowledge about Cordova. I think if it's possible to run Cordova app in the browser, you should look and see if network requests are going through properly.

You don't need to convert the file to base64, too. You can:
-Use fs.readFile/fs.readFileSync
-Use JavaScript's FileReader
-Pass the URL to the file

Perhaps something will work for you!

**Comment by solaomosola** [comment]
Thank you very much for your suggestions.
Warm regards.
