### ISSUE TITLE
Cannot find module '../build/Release/canvas.node' error when running jest test

### ISSUE THREAD

**Issue by courtneypattison** [wojtekmaj/react-pdf#1702]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

My Jest tests fail to run with the error message `Cannot find module '../build/Release/canvas.node'` when I have `react-pdf` installed. 

### Steps to reproduce

`pnpm test`

### Expected behavior

Tests should run

### Actual behavior

`Cannot find module '../build/Release/canvas.node'`

### Additional information

```
$ pnpm rebuild
node_modules/.pnpm/canvas@2.11.2/node_modules/canvas: Running install script, failed in 1.1s (skipped as optional)

$ pnpm why canvas
dependencies:
react-pdf 7.7.0
└─┬ pdfjs-dist 3.11.174
  └── canvas 2.11.2
```

### Environment

- **React-PDF version**: 7.7.0
- **React version**: 18.2.0
- **Next version**: 13.4.19

**Comment by wojtekmaj** [comment]
See also https://github.com/Automattic/node-canvas/issues/2135

**Comment by courtneypattison** [comment]
Thank you @wojtekmaj! It's a [pnpm issue](https://github.com/Automattic/node-canvas/issues/2135).

**Comment by johan44co** [comment]
@courtneypattison How did you solve this?

**Comment by courtneypattison** [comment]
> [@courtneypattison](https://github.com/courtneypattison) How did you solve this?

I think this was the final straw that got me to switch back to yarn. Sorry, I don't remember for sure!
