### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by sahinpathan** [wojtekmaj/react-pdf#1711]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I am currently using the versions "react-pdf": "4.1.0" and "react": "^16.1.1". Previously, my implementation with react-pdf was functioning correctly. However, yesterday, I deleted the node_modules directory and executed npm install. Since then, my code has encountered an error, and I am seeking assistance to resolve this issue. Any guidance or support would be greatly appreciated.

![image](https://github.com/wojtekmaj/react-pdf/assets/43176946/ab2993fb-bb8f-4a87-aaef-e40238893ceb)

### Steps to reproduce

do npm i 

### Expected behavior

it should show pdf

### Actual behavior

it is giving error

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by jd-carroll** [comment]
I think this is an issue with `@react-pdf/textkit`

The version you are using is incorrect, please validate my assertion that you are using `@react-pdf/textkit@4.4.0`
(Note: You may need to go into the `node_modules` folder to explicitly look at the dependency)

**Comment by sahinpathan** [comment]
@jd-carroll I have found this @react-pdf/textkit in my package-lock.json and it is correct i think 4.4.0. it is internal dependency of react-pdf.

![image](https://github.com/wojtekmaj/react-pdf/assets/43176946/adce67e7-7a06-4ae3-a23a-ddc7eb1df3c1)

**Comment by jd-carroll** [comment]
Wrong project: 
https://github.com/diegomura/react-pdf/issues/2603

**Comment by sahinpathan** [comment]
Do you have any workaround for this. like what can i do to fix this error temporary?

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
