### ISSUE TITLE
why not allow user use self pdfjs instance.

### ISSUE THREAD

**Issue by pk111and222** [wojtekmaj/react-pdf#1714]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

why not allow user use self pdfjs instance. In fact, both version and loading issues with pdfjs can be resolved on their own, simply allowing users to pass in pdfjs themselves during initialization with react pdf instead of default built-in functionality

**Comment by wojtekmaj** [comment]
Because of breaking changes, happening even between versions technically belonging to the same major. 🤷
