### ISSUE TITLE
Is there anyway to get metadata of the pdf file?

### ISSUE THREAD

**Issue by zzlyn** [wojtekmaj/react-pdf#172]
I am passing in pdf files using urls, wonder if there's a way to do this through this library. Thanks!
`<Document
              file={link}>
              <Page
                pageNumber={pageNumber}/>`

**Comment by wojtekmaj** [comment]
`onLoadSuccess` in `<Document />` component returns you the whole pdf object when loaded.

Under the hood, it's an object that `PDFJS.getDocument(yourfilegoeshere)` promise would return (head to PDF.js for more info if you're interested in knowing more than I share below). Inside it, you have a lot of fun methods to play with, including some that React-PDF itself uses.

- There's `pdf.pdfInfo` which gives you some basic data like number of pages
- There's `pdf.getMetadata()` promise that returns a LOT of info, sample:

```js
{
  "info": {
    "PDFFormatVersion": "1.7",
    "IsAcroFormPresent": false,
    "IsXFAPresent": false,
    "Title": "Sample document",
    "Author": "Wojciech Maj",
    "Creator": "Microsoft Word",
    "CreationDate": "D:20171003210151+00'00'",
    "ModDate": "D:20171003210151+00'00'"
  },
  "metadata": {
    "_metadata": {
      "dc:title": "Sample document",
      "dc:creator": "Wojciech Maj",
      "xmp:creatortool": "Microsoft Word",
      "xmp:createdate": "2017-10-03T21:01:51+00:00",
      "xmp:modifydate": "2017-10-03T21:01:51+00:00",
      "xmpmm:documentid": "uuid:476720A6-696E-4B73-B8EB-60122615DFBF",
      "xmpmm:instanceid": "uuid:476720A6-696E-4B73-B8EB-60122615DFBF"
    }
  }
}

So yeah. Happy coding ;)
```

**Comment by zzlyn** [comment]
Thank you!

**Comment by okilonet1** [comment]
How do we use it.. van you just show how you get the metadata and info

**Comment by wojtekmaj** [comment]
Over the years, pdfInfo became a private field you can no longer access, but you can get the same information through `pdf.getMetadata()` promise. 

Example:
https://codesandbox.io/s/react-pdf-metadata-6nsyq7

**Comment by prashant-deserve** [comment]
@wojtekmaj what is the date format of `CreationDate` & `ModDate` present inside `info` object ?
 I have been trying to parse it but getting `Invalid Value` error.

**Comment by wojtekmaj** [comment]
@prashant-deserve Looks like you will need to parse it using a custom function. AI built me this, untested:

```ts
/**
 * Transforms D:YYYYMMDDHHMMSS+HH'MM' to YYYY-MM-DDTHH:MM:SS+HH:MM
 * @param {string} strWithD Date string in D:YYYYMMDDHHMMSS+HH'MM format
 * @returns {string} Date string in YYYY-MM-DDTHH:MM:SS+HH:MM
 * @example
 * transformDate('D:20171003210151+00\'00\'')
 * // => 2017-10-03T21:01:51+00:00
 */
function transformDate(strWithD: string): string {
  const str = strWithD.replace('D:', '');
  const [dateAndTime, rawTimezone] = str.split('+');
  const [year, month, day, hour, minute, second] = [
    dateAndTime.slice(0, 4),
    dateAndTime.slice(4, 6),
    dateAndTime.slice(6, 8),
    dateAndTime.slice(8, 10),
    dateAndTime.slice(10, 12),
    dateAndTime.slice(12, 14),
  ];
  const timezone = rawTimezone.replace('\'', ':');
  return `${year}-${month}-${day}T${hour}:${minute}:${second}${timezone}`;
}
```

**Comment by prashant-deserve** [comment]
@wojtekmaj thanks for the solution. I built similar function to this and need to handle different values for timezone 👍
