### ISSUE TITLE
AnnotationLayer: scale undefined in this.context

### ISSUE THREAD

**Issue by renrizzolo** [wojtekmaj/react-pdf#173]
Hi, this is apparent in v3.x

In AnnotationLayer.jsx, this.context.scale is undefined
```
  get viewport() {
    const { page, rotate, scale } = this.context;
    console.log(this.context.scale) // undefined
    return page.getViewport(scale, rotate);
  }
```
So when the scale changes, the annotations do not resize with the pdf.

Ahh, I just realized scale is not defined as a contextType in AnnotationLayer.jsx

```
AnnotationLayer.contextTypes = {
  linkService: isLinkService,
  onGetAnnotationsError: PropTypes.func,
  onGetAnnotationsSuccess: PropTypes.func,
  page: isPage,
  rotate: isRotate,
};
```
^ needs `scale: PropTypes.number`

@wojtekmaj this one line is not worth me doing a PR (I can't get the lib to build because of some babel issue anyway).

**Comment by wojtekmaj** [comment]
Thank you for pointing that out! I'll fix this asap.

**Comment by wojtekmaj** [comment]
Hi, I just release version 3.0.2. The error should now been fixed :) Additional measures to prevent that from happening in the future were also taken. Let me know if everything works for you!

**Comment by renrizzolo** [comment]
@wojtekmaj thanks! All working now :)
