### ISSUE TITLE
Document Page rotates by default

### ISSUE THREAD

**Issue by valentimcanejo** [wojtekmaj/react-pdf#1736]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I'm using the document and page tags to render a pdf, but he's rotating my document by default, even if I put "0" in the rotate prop. How can I remove this default behavior?

### Steps to reproduce

Show a pdf in the document component.

### Expected behavior

Document page will keep it's original rotation

### Actual behavior

Document page ignores the pdf default rotation and creates another one

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by HaphuEdu** [comment]
I have an issue when a pdf file has a page horizontal and another is vertical. The lib makes the horizontal page rotate 90degs to become vertical. Is this issue close to yours and do any ideas for this? @wojtekmaj

**Comment by biennui1998mu** [comment]
I have an issue when a pdf file has a page horizontal and another is vertical. The lib makes the horizontal page rotate 90degs to become vertical. Is this issue close to yours and do any ideas for this? @wojtekmaj

**Comment by xavierh81** [comment]
@valentimcanejo I have the same behavior on some PDFs (not all).
Have you find a way to deal with that ?

**Comment by vladpoltorin1** [comment]
I just ran into similar issue - the pages of my file are rotated by 90deg. It's easy to check the page's rotation by:

```
const page = await pdf.getPage(index);
const pageViewport = page.getViewport({ scale: 1 }).rotation; 
const originalPageRotation = pageViewport.rotation; // 90
```

I did NOT specify `rotate` props neither on Document or Page, but my pages are displayed like its rotation is 0. So I guess the `Page/Document` component doesn't respect the original page rotation.

The workaround I see here is to use `originalPageRotation` for every page. If order to change rotation you have to use this value as base value.

let's say `originalPageRotation === 90`, so the rotation could be described like:

```
<Page
   --//--
    rotate={(originalPageRotation +/- 90) % 360}
/>
```
