### ISSUE TITLE
Annotation Layer redering issue

### ISSUE THREAD

**Issue by juancarlos-cynch** [wojtekmaj/react-pdf#1739]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When opening a PDF file with annotated info, the values are being shown misaligned.
I'm seeing this issue even in the library demos.
- Using the `react-pdf` library:
![Screenshot 2024-03-08 at 09 55 45](https://github.com/wojtekmaj/react-pdf/assets/144056869/16b193f0-e0a5-474b-9b50-10b8d9ce1018)

- Using any other PDF reader software:
![Screenshot 2024-03-08 at 09 55 00](https://github.com/wojtekmaj/react-pdf/assets/144056869/9f69440f-4a9f-42e6-9922-d86da0d32e1b)

### Steps to reproduce

1. Clone the `react-pdf` library
2. Go to `sample/vite/` folder and install the demo dependencies `npm install`
3. Run the demo: `npm run dev`
4. Choose the attached file in this issue, using the file selector and load a PDF file with annotations.
5. See the misaligned data and compare opening the file with another PDF reader (like Mac Preview)

### Expected behavior

The form values should be showed correctly aligned as any other PDF reader software.

### Actual behavior

The form values are incorrectly aligned.

### Additional information

Sample Demo: https://github.com/wojtekmaj/react-pdf/tree/main/sample/vite

Test File: [f1040--2022 (1).pdf](https://github.com/wojtekmaj/react-pdf/files/14539855/f1040--2022.1.pdf)

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: latest
- **React version**: 18
- **Webpack version (if applicable)**:

**Comment by Yatin07** [comment]
I am also getting similar issues:-

![1ex](https://github.com/wojtekmaj/react-pdf/assets/46103767/52b947f0-efe8-4d3f-8616-dd1915282470)
![2ex](https://github.com/wojtekmaj/react-pdf/assets/46103767/b4cb4b70-46cb-49e8-a878-7ddd698162e5)

**Environment:-**

- React version: 17
- React-PDF version: latest

**Comment by jigmeloday** [comment]
import 'react-pdf/dist/Page/TextLayer.css';
import 'react-pdf/dist/Page/AnnotationLayer.css';

you can import this two css which solved the issue but not sure where its good idea or not
