### ISSUE TITLE
onRenderAnnotationLayerSuccess callback executing before the annotation layer is rendered on the screen

### ISSUE THREAD

**Issue by Talha345** [wojtekmaj/react-pdf#1740]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi,

I have tried using the `onRenderAnnotationLayerSuccess` and `onRenderSuccess`  callbacks as I want to execute a function after the annotationLayer has rendered on my screen, however `onRenderAnnotationLayerSuccess` callback is executed before the paint is completed on the screen. The documentation says: _"Function called when annotations are successfully rendered on the screen."_, however this is not happening in my scenario.

### Steps to reproduce

1. Clone the react-pdf library
2. Go to sample/vite/ folder and install the demo dependencies `npm install`
3. Run the demo:` npm run dev`
4. Go to the file `sample/vite/Sample.tsx`
5. Update the page component call to:
```
              function test(): void {
                  alert("Annotation Layer Rendered");
              }
              
              <Page
                key={`page_${index + 1}`}
                pageNumber={index + 1}
                width={containerWidth ? Math.min(containerWidth, maxWidth) : maxWidth}
                renderAnnotationLayer={true}
                renderForms={true}
                onRenderAnnotationLayerSuccess={test}
              />
```

The alert will be shown before the document is displayed on the screen.

### Expected behavior

The `onRenderAnnotationLayerSuccess` function should be executed once the annotation layer is completed rendered on the screen. Same for onRenderSuccess.

### Actual behavior

The `onRenderAnnotationLayerSuccess` function is executed before the DOM is rendered on the screen.

### Environment

- **Browser (if applicable)**: Chrome 122.0.6261.111
- **React-PDF version**: 7.7.0
- **React version**: 18

**Comment by geoffharcourt** [comment]
A note here: In v8 we were able to use this to alter the content that gets rendered (in this case adding query params to hrefs in `a` tags. In v9 it seems to consistently execute fast enough that our approach no longer works.
