### ISSUE TITLE
any chance we can bump the pdfjs-dist version to a newer version?

### ISSUE THREAD

**Issue by ammmze** [wojtekmaj/react-pdf#176]
We're currently running a build that a little over a year old. It would be nice if we could bump that up to a newer version. One thing I'm looking for in the newer version is they've changed to bundle the compatibility.js in the main pdf.js which means we won't need to deal with importing that separately

Edit: Actually maybe our build already includes it. I don't see the compatiblity.js as a separate file. But still...i'd like to see about upgrading at some point. However, it doesn't look like they've been very good about their semver. In the latest version `pdfjs.PDFJS` no longer exists, so we'd need to see how we configure it in the newer versions

**Comment by wojtekmaj** [comment]
Actually, we're using a version far newer than any officially released. That's a newest PDF.js *pre-release* that I found stable. I'll obviously work on upgrading this, but we would need to wave goodbye to a non-worker version. They meesed it up pretty badly recently and there's close to no way of disabling it programatically. This creates major issues regarding unit testing and pottentially other issues to my users, and I'm not comfortable with giving them that.

I can confirm the version we're using has compatibility part included and you don't need to deal with this.

**Comment by ammmze** [comment]
Gotcha...thanks for confirming the compatibility piece. I think if we're already using a pre-release, then I'd say we're as up to date as possible. So I think I'll just close this. Thanks for all your work on this project!
