### ISSUE TITLE
Will docx, doc format be supported in future

### ISSUE THREAD

**Issue by gajju3588** [wojtekmaj/react-pdf#177]
I have a use-case where document could be pdf/docx, i tried docx here, that doesn't seem to be working correctly. Is there any chance docx, doc will be supported anytime in future ? Is there any other library which provides annotations for docx format doc ?

**Comment by wojtekmaj** [comment]
That would be a cool thing, but it's highly unlikely to happen in a foreseeable future, and has 0% chance of being implemented in this library :( React-PDF will be PDF-focused as the name suggests. If anything, I could create some other library (much) later, and maybe then create a wrapper for these two to work nicely together.
