### ISSUE TITLE
yarn dev in create-react-app-5 sample project fails with uncaught exception

### ISSUE THREAD

**Issue by teuber789** [wojtekmaj/react-pdf#1770]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The "create-react-app-5" sample project fails with an uncaught exception whenever running `yarn dev`.

```console
$ yarn dev

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
[Object: null prototype] {
  [Symbol(nodejs.util.inspect.custom)]: [Function: [nodejs.util.inspect.custom]]
}

Node.js v18.20.2
```

### Steps to reproduce

* Open a terminal and run the following:

```
# Start with a fresh copy of the repo
$ git clone git@github.com:wojtekmaj/react-pdf.git
$ cd react-pdf/sample/create-react-app-5

# Install
$ yarn install

# Run for local development
$ $ yarn dev

node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
[Object: null prototype] {
  [Symbol(nodejs.util.inspect.custom)]: [Function: [nodejs.util.inspect.custom]]
}

Node.js v18.20.2

```

### Expected behavior

The project should build and run on the local development server

### Actual behavior

It fails with the following error:

```
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^
[Object: null prototype] {
  [Symbol(nodejs.util.inspect.custom)]: [Function: [nodejs.util.inspect.custom]]
}

Node.js v18.20.2
```

### Additional information

<img width="1628" alt="Screenshot 2024-04-27 at 12 45 05" src="https://github.com/wojtekmaj/react-pdf/assets/8787798/eef08660-8c60-4ec6-8835-2be9159970cb">

### Environment

* Chrome: Version 124.0.6367.93 (Official Build) (x86_64)
* react-pdf: 7.7.1
* react: 18.2.0
* Node: 18.20.2
* Yarn: 4.1.1
* python: 3.12.3
* MacOS: Sonoma 14.4.1 (intel)

**Comment by wojtekmaj** [comment]
You're right! ts-node is a load of crap. Replaced it with much more reliable tsimp. Thanks!
