### ISSUE TITLE
PDF Resize

### ISSUE THREAD

**Issue by reesmanp** [wojtekmaj/react-pdf#178]
Not a huge issue since I don't expect many users to resize their windows during viewing but when I am sending the `width` prop, I expect the page to resize if the prop changes. As is, I need to cycle to a new page before the page resizes.

**Comment by KyleFoleyImajion** [comment]
I'm with you on that one, have you tried dynamically changing the scale as well? I can't get either of them to work for some reason

**Comment by reesmanp** [comment]
I have not tried using scale, as I assumed it was using similar logic and if one didn't dynamically resize, then the other wouldn't. Based off of your experience it looks like I was right.

**Comment by KyleFoleyImajion** [comment]
My stupid mistake, I was using it on <Document> instead of <Page> like it should be. It adjusts dynamically now

**Comment by KyleFoleyImajion** [comment]
Sorry, comment formatting is messed up. I was using it in the Document tag instead of the Page tag like it should be

**Comment by reesmanp** [comment]
I'm a moron. I didn't check to see if React was even calling the render function of the component on window resize. I switched to scale (for good measure) and added a function to window.onresize to dispatch and action to update props in my pure component... Thanks @KyleFoleyImajion

**Comment by wojtekmaj** [comment]
By no means you are a moron, Page should resize on `width` prop change. Would you please share the code that you expected to be working? I gotta make sure there's no bug.
