### ISSUE TITLE
"2 high severity vulnerabilities" just after installing react-pdf

### ISSUE THREAD

**Issue by jadejamig** [wojtekmaj/react-pdf#1791]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I am getting this vulnerability message after running ```npm install react-pdf```
<img width="396" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/57212583/a4cf57ff-f2b8-486b-8dbb-9f1d5c28c55d">

I have tried looking for fixes but can't see anyone talking about it.

```npm audit fix --force``` downgrades the package version to 0.0.10 from 8.0.2 which doesn't look pretty good

### Steps to reproduce

You can clone my repo here https://github.com/jadejamig/pdf-chatinator and try to install react-pdf

### Expected behavior

no vulnerabilities

### Actual behavior

2 high vulnerabilities

### Environment

- **Browser (if applicable)**: 
- **React-PDF version**: 8.0.2
- **React version**: 18
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
See https://github.com/wojtekmaj/react-pdf/discussions/1786
