### ISSUE TITLE
Update pdfjs-dist

### ISSUE THREAD

**Issue by VayneValerius** [wojtekmaj/react-pdf#1792]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

`pdfjs-dist` has a high level, arbitrary code injection vulnerability for versions <= 4.1.392.  react-pdf is still using a 3.x.x version.

I can see that the [ `isEvalSupported` option has been set to false](https://security.snyk.io/vuln/SNYK-JS-PDFJSDIST-6810403) in the [8.0.2 release](https://github.com/wojtekmaj/react-pdf/releases/tag/v8.0.2), which stops the vun from being possible, but for ci pipelines that use a tool like docker scout, it will fail deployments regardless.  

### Proposed solution

Update pdfjs-dist to 4.2.67

### Alternatives

The alternative has already been implemented, which is fine for users who don't give a hoot about security.

**Comment by wojtekmaj** [comment]
Duplicate of #1664
