### ISSUE TITLE
Are you planning on release a version to use the patched version of pdfjs-dist?

### ISSUE THREAD

**Issue by shye0000** [wojtekmaj/react-pdf#1794]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

HI, In my project, we have the npm audit check on CI, which currently fail on pdfjs-dist vulnerability:
https://github.com/advisories/GHSA-wgrm-67xf-hhpq
and by installing the patched versions of react-pdf doesn't fix that, because you've patched it by disable the "eval support" in your code, but still installing the unpatched verison of pdfjs-dist which is still a high vulnerability for npm audit.

So as the title, are you planning on releasing a new version to install the patched version of pdfjs-dist in the near future, please? thx a lot in advance.

**Comment by wojtekmaj** [comment]
Already covered both in Issues and Discussions
