### ISSUE TITLE
pdfjs-dist exports .mjs file that doesnt get transpiled by babel as its within node_modules

### ISSUE THREAD

**Issue by reedasha** [wojtekmaj/react-pdf#1795]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

We're importing pdfJsWorker through -

import pdfJsWorker from 'pdfjs-dist/build/pdf.worker.min.mjs'; 
pdfjs.GlobalWorkerOptions.workerSrc = pdfJsWorker;

When running unit test with jest, its failing as babel is not transpiling .mjs files, as node_modules folder is ignored by transformers.
The issue is blocking us from testing our component that renders pdf, so we're forced to look for another pdf library

### Steps to reproduce

Create a component that imports pdfJsWorker
Write a test
Run a test

### Expected behavior

Run tests successfully without errors

### Actual behavior

![image](https://github.com/wojtekmaj/react-pdf/assets/16371152/9216d322-212e-446a-b428-300acaa2ed68)

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 8.0.2
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by AndyAlkhawand** [comment]
The current `react-pdf` version is dependent on `pdfgs-dist` version `3.11.174` which causes a high security vulnerability https://github.com/advisories/GHSA-wgrm-67xf-hhpq

**Comment by wojtekmaj** [comment]
Yep. Read more at https://github.com/wojtekmaj/react-pdf/discussions/1786
