### ISSUE TITLE
white screen error in ios 17.4.1

### ISSUE THREAD

**Issue by melisaltunal** [wojtekmaj/react-pdf#1796]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I want to open my React project in the mobile application, in webView or in any mobile browser. I am using React-pdf and listing the pdfs in the stepper. However, when I open my project on iOS 17.4.1 devices, I get a white screen, or when I perform any scroll operation after it is opened, it turns into a white screen again and users cannot perform any operations.

This problem does not occur on Android devices and web browsers.

### Expected behavior

I should open my link in any browser on ios17.4.1 and I should not see a white screen.

### Actual behavior

White screen

### Environment

- **Browser (if applicable): Any browser in ios v17.4.1
- **React-PDF version: ^5.7.2
- **React version: 17.0.0
- **Webpack version (if applicable): 5.75.0

**Comment by wojtekmaj** [comment]
Do you have a public project I could look on by any chance?
