### ISSUE TITLE
PDF turns blank white after changing tabs 

### ISSUE THREAD

**Issue by Talha345** [wojtekmaj/react-pdf#1798]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Since 2 days I have encountered a bug that if a PDF is opened in a tab and I switch tabs and come back after a while, the loaded PDF turns transparent and only the form fields are visible. Rest of all the PDF content fades away. I have only reproduced this on Chrome and Edge. 

I was also able to reproduce the same on another website called https://simplepdf.eu/ which is also using react-pdf under the hood.

### Steps to reproduce

1. Open chrome.
2. Go to https://simplepdf.eu/
3. When the PDF loads move to another tab and open a YT video or something. Come back after a while and the PDF would have disappeared. 

### Expected behavior

PDF should not fade away.

### Actual behavior

PDF content fades away.

### Additional information

There is no error in the console.

### Environment

- **Browser (if applicable)**: Chrome, Edge
- **React-PDF version**: 7.7.0
- **React version**: 18.2.0
- **Webpack version (if applicable)**: 

Screenshot:

![image](https://github.com/wojtekmaj/react-pdf/assets/36226639/2ef0ee96-0f70-4862-81aa-dd2ce9e02202)

**Comment by Talha345** [comment]
UPDATE: Tested on some popular PDF related websites and the issue seems to be happening on all of them. Looks like it is a chrome PDF rendering related issue.

**Comment by longphung** [comment]
This is happening when I'm running version 8.0.2 as well

**Comment by anhducmata** [comment]
It might be a Chromium issue. Just wait for a new fixed version.
fmi: https://issues.chromium.org/issues/339654395

**Comment by longphung** [comment]
> It might be a Chromium issue. Just wait for a new fixed version.
> fmi: https://issues.chromium.org/issues/339654395
> https://issues.chromium.org/issues/328755781

It isn't happening for me anymore after I restarted my MacBook a few times. Doesn't look like Chrome updated itself, so could have been for Mac

**Comment by jiangxiaoqiang** [comment]
I am facing the same issue. The mac will have this issue, but windows seems fine.

**Comment by wojtekmaj** [comment]
Yep, it seems like a Chromium issue, so there's no action on my side that could be taken.

However, not to leave you all in the dark, may I suggest using [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) to perhaps force rerender every time the page becomes visible by e.g. setting a `key` on `Document` like so:

```ts
function MyApp() {
  const [visibilityCounter, setVisibilityCounter] = useState(0);

  useEffect(() => {
    function onVisibilityChange() {
      if (document.visibilityState === 'visible') {
        // Page just became visible
        setVisibilityCounter(prev => prev +1);
      }
    }

    document.addEventListener('visibilitychange', onVisibilityChange);

    return () => {
      document.removeEventListener('visibilitychange', onVisibilityChange);
    };
  }, []);

  return (
    <Document key={`document_${visibilityCounter}`} file={…}>
     <Page />
    </Document>
  );
}
```

(untested, raw written code, please use as inspiration, not a ready-to-use solution)

**Comment by Johnkhk** [comment]
I'm having the same issue

**Comment by longphung** [comment]
> I'm having the same issue

You will have to update Chrome or restart your machine, and the problem should go away

**Comment by XuanDuLe** [comment]
My solution like that. Hope it works for you:

```
const browserName = useDetectingBrowser();
const isDocumentActive = useDocumentActive();
const [pagePdfKey, changePagePdfKey] = useState(1);

useEffect(() => {
    if (browserName === "Chrome" && isDocumentActive) {
      changePagePdfKey((prev) => ++prev);
    }
}, [isDocumentActive, browserName]);
  
<Page
    key={pagePdfKey}
    className="pdf-page"
    width={widthPreview}
    renderTextLayer={false}
    pageNumber={currentPage}
/>
```

**Comment by yisiper** [comment]
Perhaps you can check blank canvas to avoid re-rendering every time the visibility changes. This works well for me.

```
if (document.visibilityState === "visible") {
  let blankCanvasFound = false;
  document
    .querySelectorAll("canvas.react-pdf__Page__canvas")
    .forEach((canvas) => {
      const ctx = canvas.getContext("2d");
      const pixelBuffer = new Uint32Array(
        ctx.getImageData(0, 0, canvas.width, canvas.height).data.buffer
      );

      // check for possible blank color
      const isBlank = pixelBuffer.every(
        (color) => color === 0 || color === 4278190080
      );

      if (isBlank) {
        blankCanvasFound = true;
      }
    });

  if (blankCanvasFound) {
    setVisibilityCounter((prev) => prev + 1);
  }
}

```

**Comment by Talha345** [comment]
This has been fixed in the Chrome update so no need to add un-necessary bloat to your code.

**Comment by yisiper** [comment]
This issue occurs on mobile browsers on my Android device:

    Chrome 126.0.6478.122
    Brave 1.67.123 (Chromium 126.0.6478.126)

There is no problem on the desktop.
