### ISSUE TITLE
Text highlighting recipe work for only for a single line text search.

### ISSUE THREAD

**Issue by muhammadbasitobaid** [wojtekmaj/react-pdf#1803]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The code in recipe https://github.com/wojtekmaj/react-pdf/wiki/Recipes#highlight-text-on-the-page only works if we try to search only a single row at a time!
![image](https://github.com/wojtekmaj/react-pdf/assets/79991232/41ee0aa0-80f0-466e-a831-a4d12244f3d3)
but the moment new line text is type the highlighting stops working:
![image](https://github.com/wojtekmaj/react-pdf/assets/79991232/cc375904-d709-41f9-aa35-7990c2b1b82b)
any help is highly appreciated.

### Steps to reproduce

Just fire up the script in give link and start searching when you reach the "newline text highlighting won't work.

### Expected behavior

Highlighting should work for multiple search as well.

### Actual behavior

only works for a single line.

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by MykolaRomaniv** [comment]
I'm struggling with the same problem on my project. Did you find a workaround? @muhammadbasitobaid

**Comment by muhammadbasitobaid** [comment]
> I'm struggling with the same problem on my project. Did you find a workaround? [@muhammadbasitobaid](https://github.com/muhammadbasitobaid)

hye @MykolaRomaniv thanks for reaching out, it was a year ago and i did struggle myself i actually created a repo for this issue, this issue has two parts:
- you need to use a specific version of `react-pdf-viewer` in order for all the functionality to work properly.
- as this package only support keyword search or single line at best you need to have a way of knowing where your line is ending i.e. newline character. each single line will become a keyword. hence, a paragraph of 8 line will have 8 keywords multi search. it'll give the notion that you are searching for a paragraph.
please feel free to take a look at my pdf viewer component:
[Link](https://github.com/muhammadbasitobaid/pdf-multiline-search-react/blob/main/src/components/PdfViewer/index.jsx)
Hope it helps, **Peace!**
