### ISSUE TITLE
PDF text and spaces are messy

### ISSUE THREAD

**Issue by eretztzvi** [wojtekmaj/react-pdf#1805]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Im using Nextjs 14, and while uploading a pdf file or display it from an external link, the text gets messy and spaces also.

The images below from a link that return a pdf, I've checked the file and it's ok

Also, I checked it in other devices to make sure it's not a problem in my machine 

This is how i use the package:

<Document file={pdf} onLoadSuccess={onDocumentLoadSuccess}>
        {Array.from({ length: numPages }).map((_, index) => (
          <Page
            pageNumber={index + 1}
            renderTextLayer={false}
            renderAnnotationLayer={false}
          />
        ))}
      </Document>

### Steps to reproduce

![WhatsApp Image 2024-05-27 at 12 33 25](https://github.com/wojtekmaj/react-pdf/assets/92538868/4f166f96-b5e3-433e-b1c2-7e48f69cf9c6)
![WhatsApp Image 2024-05-27 at 12 34 10](https://github.com/wojtekmaj/react-pdf/assets/92538868/2502fb0d-b5a7-42bb-8087-bddc1bab7059)
![WhatsApp Image 2024-05-27 at 12 34 59](https://github.com/wojtekmaj/react-pdf/assets/92538868/7d492666-43c2-4dcd-a106-23c3ddce64c0)

### Expected behavior

Render a normal PDF file with it's original style

### Actual behavior

Messy PDF file

### Environment

- **Browser**: 124.0.6367.158
- **React-PDF version**: 8.0.2
- **React version**: 18
- **Nextjs version**: 14

**Comment by thosil** [comment]
duplicate of #1684
