### ISSUE TITLE
updated pdfjs-dist to latest version and react-pdf to 8.0.2 but getting the error pdfjsModule not found

### ISSUE THREAD

**Issue by VijayaSaiRam** [wojtekmaj/react-pdf#1807]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I have updated the react-pdf to **8.0.2** and pdfjs-dist to **4.3.136** ,  
but  I am getting the following error. Could some one . please suggest to resolve this.

ERROR in ./node_modules/react-pdf/dist/esm/pdfjs.js 2:41-63

export 'default' (imported as 'pdfjsModule') was not found in 'pdfjs-dist' (possible exports: AbortException, AnnotationEditorLayer, AnnotationEditorParamsType, AnnotationEditorType, AnnotationEditorUIManager, AnnotationLayer, AnnotationMode, CMapCompressionType, ColorPicker, DOMSVGFactory, DrawLayer, FeatureTest, GlobalWorkerOptions, ImageKind, InvalidPDFException, MissingPDFException, OPS, Outliner, PDFDataRangeTransport, PDFDateString, PDFWorker, PasswordResponses, PermissionFlag, PixelsPerInch, RenderingCancelledException, TextLayer, UnexpectedResponseException, Util, VerbosityLevel, XfaLayer, build, createValidAbsoluteUrl, fetchData, getDocument, getFilenameFromUrl, getPdfFilenameFromUrl, getXfaPageViewport, isDataScheme, isPdfFile, noContextMenu, normalizeUnicode, renderTextLayer, setLayerDimensions, shadow, updateTextLayer, version)

### Steps to reproduce

-

### Expected behavior

It should not throw any error

### Actual behavior

giving the error

### Additional information

-

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
You're not supposed to manually update a secondary dependency.
