### ISSUE TITLE
Extra spaces added to pdf left, right and bottom

### ISSUE THREAD

**Issue by VijayaSaiRam** [wojtekmaj/react-pdf#1808]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I have upgraded to 8.0.2 version. when try to open pdf , it adds extra space bottom , left and right to the pdf.
Could some one please suggest how to fix this

### Steps to reproduce

-

### Expected behavior

-

### Actual behavior

-[](url)

### Additional information

-
![Uploading Screenshot 2024-05-29 at 3.31.50 PM.png…]()

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by VijayaSaiRam** [comment]
Got resolved. thank you. closing it

**Comment by winpeed** [comment]
> Got resolved. thank you. closing it

Hello @VijayaSaiRam Any insights into how this was resolved please? Currently facing same issue.

There's some extra spacing on the left and right when an image i have is suppsoed to cover the entire length of the page
