### ISSUE TITLE
 react-pdf 9.0.0 not working in an amplify server 

### ISSUE THREAD

**Issue by Aman1706** [wojtekmaj/react-pdf#1817]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When I updated to the latest version, the package would work in localhost, however when deployed it to Amplify it would fail

It looks like it was from   'pdfjs-dist/build/pdf.worker.min.mjs', earlier it was   'pdfjs-dist/build/pdf.worker.min.js',

Initially, I realised that amplify was ignoring mjs files so I added this in my amplify config 

```
 customHeaders:
    - pattern: '**/*.mjs'
      headers:
        - key: Content-Type
          value: application/javascript
```

But after that, I started getting this error now 

`Error: Setting up fake worker failed: "Unexpected token '<'"`

### Steps to reproduce

1. Deploy project 
2. When viewing PDFs, package fails with error 

### Expected behavior

the package should work in both localhost and deployed server

### Actual behavior

the package only works in localhost 

### Additional information

NOTE: I am using vite and deploying project in AWS amplify 

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: 9.0.0
- **React version**: 18.2.0
- **Vite version**: 4.5.3:

**Comment by numan787** [comment]
@wojtekmaj. any update on this issue?

**Comment by tbpzf** [comment]
I had a similar issue after build the project as production mode. `Uncaught SyntaxError: Invalid or unexpected token (at app.07a3d9b8.js)`

We solved the problem by compiling react-pdf and pdfjs-dist using babel-loader. Because pdfjs-dist use  new syntax [static #](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Either_be_both_static_or_non-static) of javascript, and this syntax is wrong after compression.

**Comment by Aman1706** [comment]
Update: I looked more into other users facing similar issues and found out that doing this worked for me

`pdfjs.GlobalWorkerOptions.workerSrc = '//unpkg.com/pdfjs-dist@4.3.136/build/pdf.worker.min.mjs';`

The doc also mentions using the CDNs as alternatives in case the suggested way fails

**Comment by wojtekmaj** [comment]
`Error: Setting up fake worker failed: "Unexpected token '<'"` suggest you're getting a HTML 404 page instead of your actual JS file. Double check your bundler config, or consider using external workerSrc as others suggest.
