### ISSUE TITLE
Annotation layer for images to allow copy and drag images etc

### ISSUE THREAD

**Issue by ed-sparkes** [wojtekmaj/react-pdf#1821]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

It would be great to be able to interact with images in react-pdf in the same way that you can images on a website. E.g. right click copy and drag them to add them to the DataTransfer object. 

### Proposed solution

Not really sure, but could the annotation layer be updated to create dom element with image sources somehow?

**Comment by wojtekmaj** [comment]
I don't think that's realistic unfortunately. The only thing you can do is to fiddle around and create a custom renderer, which is a really powerful, but also really work intensive feature.
