### ISSUE TITLE
Production build fails on Next.js

### ISSUE THREAD

**Issue by alexandernanberg** [wojtekmaj/react-pdf#1824]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Running `yarn build` fails on `/sample/next-app` (and all other Next apps)

```
                                                                           ^^^^^^
    `----

Caused by:
    0: failed to parse input file
    1: Syntax Error


> Build failed because of webpack errors
```

### Steps to reproduce

1. Go to the `next-app` sample
2. Run `yarn build`

### Expected behavior

Production builds work

### Actual behavior

Build throws a Webpack error

### Additional information

It's working on 8.x.x so likely something to do with the `.mjs` extension of the worker

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 9.0.0
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by danielbucher** [comment]
I have the same issue. I'm using the `app` router. Setting `experimental.esmExternals` to `loose` on next config did not solve it. I've setup a small project to help reproduce this at https://github.com/danielbucher/react-pdf-build-error-nextjs.

**Comment by danielbucher** [comment]
Btw, I also get the prod build error when building the `next-app` sample.

**Comment by wojtekmaj** [comment]
Related: https://github.com/vercel/next.js/discussions/61549

I found that 

```
    config.optimization.minimize = false;
```

fixes the issue, but _at what cost!_

I also found that the message is probably not coming from Terser, but SWC: https://github.com/swc-project/swc/blob/abcf21dfc27b61489b614ce4ec0ae6733700578f/crates/swc_ecma_parser/src/error.rs#L415

**Comment by wojtekmaj** [comment]
Caused by: https://github.com/vercel/next.js/issues/33914

**Comment by wojtekmaj** [comment]
Since it's a bug in Next.js not React-PDF, I'm closing this issue after updating upgrade guide wiki. Please kindly share your further feedback on importing ESM workers with Next.js team.

**Comment by 0livare** [comment]
[Using an external CDN](https://github.com/wojtekmaj/react-pdf/tree/main/packages/react-pdf#use-external-cdn) also works around this issue

```diff
import {pdfjs} from 'react-pdf'

-pdfjs.GlobalWorkerOptions.workerSrc = new URL(
-  'pdfjs-dist/build/pdf.worker.min.mjs',
-  import.meta.url,
-).toString();
+pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

**Comment by j3rryl** [comment]
> [Using an external CDN](https://github.com/wojtekmaj/react-pdf/tree/main/packages/react-pdf#use-external-cdn) also works around this issue
> 
> ```diff
> import {pdfjs} from 'react-pdf'
> 
> -pdfjs.GlobalWorkerOptions.workerSrc = new URL(
> -  'pdfjs-dist/build/pdf.worker.min.mjs',
> -  import.meta.url,
> -).toString();
> +pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
> ```

@0livare Thank you!
This worked for me as well!

**Comment by holdenmatt** [comment]
This was a head-scratcher to track down.

I was trying to switch from using the CDN to hosting myself but hit this webpack issue.

I went back to CDN but Firefox shows CORS errors. Finally figured out that adding "https" fixes the CORS issue and this seems to work in all browsers I've tested:
```
pdfjs.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
```

**Comment by legancode** [comment]
I solved it by using this directly:
```typescript
// In a component that needs to use this
import 'pdfjs-dist/build/pdf.worker.min.mjs';

// And delete this or some example implementation shown in the doc:
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.mjs',
  import.meta.url,
).toString();
```

Additionally, if you have errors in the tests as a result of this import, you can do the following:
```
// jest.config.ts
{
   ...
   moduleNameMapper:{
     'pdfjs-dist/build/pdf.worker.min.mjs': '<rootDir>/src/test/__mocks__/mock-pdf-worker.ts'
  } ,
  transformIgnorePatterns: ['/node_modules/(?!pdfjs-dist/)'],
}
```

```typescript
// Create the mock-pdf-worker.ts file and it must match the path that was placed in jest.config.ts
const mockPdfWorker = {};
export default mockPdfWorker;
```

**Comment by umairabbasDev** [comment]
> [Using an external CDN](https://github.com/wojtekmaj/react-pdf/tree/main/packages/react-pdf#use-external-cdn) also works around this issue
> 
> ```diff
> import {pdfjs} from 'react-pdf'
> 
> -pdfjs.GlobalWorkerOptions.workerSrc = new URL(
> -  'pdfjs-dist/build/pdf.worker.min.mjs',
> -  import.meta.url,
> -).toString();
> +pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
> ```

thanks

**Comment by islamCodehood** [comment]
> I solved it by using this directly:
> 
> ```ts
> // In a component that needs to use this
> import 'pdfjs-dist/build/pdf.worker.min.mjs';
> 
> // And delete this or some example implementation shown in the doc:
> pdfjs.GlobalWorkerOptions.workerSrc = new URL(
>   'pdfjs-dist/build/pdf.worker.min.mjs',
>   import.meta.url,
> ).toString();
> ```
> 
> Additionally, if you have errors in the tests as a result of this import, you can do the following:
> 
> ```ts
> // jest.config.ts
> {
>    ...
>    moduleNameMapper:{
>      'pdfjs-dist/build/pdf.worker.min.mjs': '<rootDir>/src/test/__mocks__/mock-pdf-worker.ts'
>   } ,
>   transformIgnorePatterns: ['/node_modules/(?!pdfjs-dist/)'],
> }
> ```
> 
> ```ts
> // Create the mock-pdf-worker.ts file and it must match the path that was placed in jest.config.ts
> const mockPdfWorker = {};
> export default mockPdfWorker;
> ```
Thanks you. 
This solution worked fine

```
// In a component that needs to use this
import 'pdfjs-dist/build/pdf.worker.min.mjs';

// And delete this or some example implementation shown in the doc:
// pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  '// pdfjs-dist/build/pdf.worker.min.mjs',
  // import.meta.url,
// ).toString();

**Comment by victormer** [comment]
> [Using an external CDN](https://github.com/wojtekmaj/react-pdf/tree/main/packages/react-pdf#use-external-cdn) also works around this issue
> 
> import {pdfjs} from 'react-pdf'
> 
> -pdfjs.GlobalWorkerOptions.workerSrc = new URL(
> -  'pdfjs-dist/build/pdf.worker.min.mjs',
> -  import.meta.url,
> -).toString();
> +pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

thanks mate!

**Comment by IonelLupu** [comment]
> [Using an external CDN](https://github.com/wojtekmaj/react-pdf/tree/main/packages/react-pdf#use-external-cdn) also works around this issue
> 
> import {pdfjs} from 'react-pdf'
> 
> pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;

On top of this, I had to also do this in `next.config.js` (Next.js 12.2):
```js
module.exports = {
  swcMinify: true
}
```

**Comment by wojtekmaj** [comment]
> > [Using an external CDN](https://github.com/wojtekmaj/react-pdf/tree/main/packages/react-pdf#use-external-cdn) also works around this issue
> > import {pdfjs} from 'react-pdf'
> > pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`;
> 
> On top of this, I had to also do this in `next.config.js`:
> 
> module.exports = {
>   swcMinify: true
> }

As per docs that should not be necessary in Next.js 15 and up. Which version are you on?

**Comment by IonelLupu** [comment]
@wojtekmaj , unfortunately, this project is on Next.js 12.2 😞
