### ISSUE TITLE
Document cannot be rendered after update to  v9.0.0

### ISSUE THREAD

**Issue by pk-bt** [wojtekmaj/react-pdf#1825]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

After the latest update I started to get the following errors:

![Unbenannt](https://github.com/wojtekmaj/react-pdf/assets/42238299/62510c80-42c6-40c0-a3f4-8fc96e15cdaa)

I am using cra.

### Steps to reproduce

I am importing the module and the pdf worker as following:

```
import {Document, Page, pdfjs} from "react-pdf";
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';
import 'react-pdf/dist/esm/Page/TextLayer.css';
import "./PDFViewer.scss";
import {TextItem} from "pdfjs-dist/types/src/display/api";
import {DocumentCallback} from "react-pdf/src/shared/types";

pdfjs.GlobalWorkerOptions.workerSrc = new URL(
    'pdfjs-dist/build/pdf.worker.min.mjs',
    import.meta.url,
).toString();

const options = {
    cMapUrl: '/cmaps/',
    standardFontDataUrl: '/standard_fonts/',
};

```
...

### Expected behavior

No errors.

### Actual behavior

The PDF document cannot be opened.

### Environment

- **Browser (if applicable)**: Chrome Android; 
- **React-PDF version**: 9.0.0;
- **React version**: 18.2.0;
- **Webpack version (if applicable)**: 5.91.0;

**Comment by wojtekmaj** [comment]
Can you provide a reproducible example? Can't reproduce it on my own samples.

**Comment by TheMoonDawg** [comment]
@wojtekmaj We noticed in our project that our `workerSrc` was getting overridden by your default here: https://github.com/wojtekmaj/react-pdf/blob/main/packages/react-pdf/src/index.ts#L23

We set ours up in the entry point of our app, and it's correct until we actually try to use the library. It's then overridden with `pdf.worker.mjs` instead of our version.

**Comment by wojtekmaj** [comment]
Doesn't seem to be related with the original issue.

**Comment by TheMoonDawg** [comment]
I'll make a separate issue then, thanks!

**Comment by pk-bt** [comment]
> Can you provide a reproducible example? Can't reproduce it on my own samples.

I was a little busy the past few days I didn't have time to provide an example, I will try to do it today.

Strangely, the problem is gone if I load the "unpkg" version of the "pdf-worker.min.mjs" and not the react-pdf version of the worker, but with this solution I have some delay of 1-2 seconds before the document starts loading.

**Comment by utkershrajvenshi** [comment]
@pk-bt Were you able to solve this issue without having the worker being fetched from "unpkg"? I'm having similar issues with v9 except the error I'm getting is:
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of “application/octet-stream”. Strict MIME type checking is enforced for module scripts per HTML spec`

**Comment by pk-bt** [comment]
> @pk-bt Were you able to solve this issue without having the worker being fetched from "unpkg"? I'm having similar issues with v9 except the error I'm getting is: `Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of “application/octet-stream”. Strict MIME type checking is enforced for module scripts per HTML spec`

Not yet, haven't had the time to work on the issue, I had to do other things in the meantime.

**Comment by pk-bt** [comment]
> Can you provide a reproducible example? Can't reproduce it on my own samples.

Page source here: https://github.com/pk-bt/react-pdf-example/ 
The page is deployed here: https://github.com/pk-bt/playground/ 
View it here: https://pk-bt.github.io/playground/

If I start the project locally in developer mode the component works without problems, I get errors on the production version.

I have noticed some lines at the beginning of the  "pdf.worker.min.mjs"  on the production that should not be there, in fact the files shown the error console.

**Comment by silvertae** [comment]
@pk-bt 
I have similar issue. When I run my application locally it doesn't matter, but pdf file was not loaded after deploy.

I think this code is not working for some enviroment.
```ts
// before
pdfjs.GlobalWorkerOptions.workerSrc = new URL(
    'pdfjs-dist/build/pdf.worker.min.mjs',
    import.meta.url,
).toString();
```
So I run below code on my terminal to copy workers bundle to my public folder
```
cp ./node_modules/pdfjs-dist/build/pdf.worker.min.mjs ./public/
```
and modify above code like this. 
```ts
// after
pdfjs.GlobalWorkerOptions.workerSrc =
  window.location.origin + "/pdf.worker.min.mjs";
```

after that it runs well in my deployed app.

I referenced this article https://pspdfkit.com/blog/2021/how-to-build-a-reactjs-viewer-with-pdfjs/
I hope this helps.

**Comment by goatrenterguy** [comment]
I am facing the same issue

**Comment by sureshsamanthapudi** [comment]
> @pk-bt I have similar issue. When I run my application locally it doesn't matter, but pdf file was not loaded after deploy.
> 
> I think this code is not working for some enviroment.
> 
> ```ts
> // before
> pdfjs.GlobalWorkerOptions.workerSrc = new URL(
>     'pdfjs-dist/build/pdf.worker.min.mjs',
>     import.meta.url,
> ).toString();
> ```
> 
> So I run below code on my terminal to copy workers bundle to my public folder
> 
> ```
> cp ./node_modules/pdfjs-dist/build/pdf.worker.min.mjs ./public/
> ```
> 
> and modify above code like this.
> 
> ```ts
> // after
> pdfjs.GlobalWorkerOptions.workerSrc =
>   window.location.origin + "/pdf.worker.min.mjs";
> ```
> 
> after that it runs well in my deployed app.
> 
> I referenced this article https://pspdfkit.com/blog/2021/how-to-build-a-reactjs-viewer-with-pdfjs/ I hope this helps.

@silvertae Getting the below error after making the change as you mentioned above. How did you solve this issue.

"Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec."

**Comment by silvertae** [comment]
@sureshsamanthapudi 
I've checked my app and I don't seem to be getting the error you mentioned.

In my case, I deployed as an Azure Static Web App using the Microsoft Teams Toolkit. It seems to load fine without the error you mentioned.

Reference this [link](https://stackoverflow.com/questions/72070748/failed-to-load-module-script-expected-a-javascript-module-script-but-the-server) I think it's worth checking how the path to load the module is set up.

I'm loading the module files like this.
![스크린샷 2024-07-04 오전 9 18 51](https://github.com/wojtekmaj/react-pdf/assets/76121068/8e91804f-bf75-4407-b0a3-b099897338a8)

**Comment by sureshsamanthapudi** [comment]
> @sureshsamanthapudi I've checked my app and I don't seem to be getting the error you mentioned.
> 
> In my case, I deployed as an Azure Static Web App using the Microsoft Teams Toolkit. It seems to load fine without the error you mentioned.
> 
> Reference this [link](https://stackoverflow.com/questions/72070748/failed-to-load-module-script-expected-a-javascript-module-script-but-the-server) I think it's worth checking how the path to load the module is set up.
> 
> I'm loading the module files like this. ![스크린샷 2024-07-04 오전 9 18 51](https://private-user-images.githubusercontent.com/76121068/345654781-8e91804f-bf75-4407-b0a3-b099897338a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDMwMjIsIm5iZiI6MTcyMDEwMjcyMiwicGF0aCI6Ii83NjEyMTA2OC8zNDU2NTQ3ODEtOGU5MTgwNGYtYmY3NS00NDA3LWIwYTMtYjA5OTg5NzMzOGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE0MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NDNlMDAyZDlkZWQwMzJjN2YzYzgzNjc3YzI1ZjExODk3NTViZDBjMDdlN2Y5YzYyM2U1M2VjN2I1M2UzYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yo4Fy_X_GzGZwHAuEQFN_p0AN46GupkARk94ECux0Sk)

It worked fine with the below mentioned code.

pdfjs.GlobalWorkerOptions.workerSrc = new URL(
'pdfjs-dist/build/pdf.worker.min.mjs',
import.meta.url,
).toString();

and add the below mentioned MIME type to nginx.conf

application/javascript mjs;

Thank you @silvertae

**Comment by jiangxiaoqiang** [comment]
> https://pspdfkit.com/blog/2021/how-to-build-a-reactjs-viewer-with-pdfjs/

did you fixed this issue?

**Comment by jiangxiaoqiang** [comment]
> @pk-bt Were you able to solve this issue without having the worker being fetched from "unpkg"? I'm having similar issues with v9 except the error I'm getting is: `Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of “application/octet-stream”. Strict MIME type checking is enforced for module scripts per HTML spec`

did you fixed this issue?

**Comment by jiangxiaoqiang** [comment]
by add :


```
include mime.types;
  types {
      application/javascript js mjs;
  }

```

fixed this issue. https://github.com/storybookjs/storybook/issues/20157

**Comment by oceangravity** [comment]
For some reason, pdfjs-dist version "4.4.168" is not being installed with react-pdf@latest, so I installed pdfjs-dist version "4.4.168" separately, and it works smoothly. ❤️

**Comment by 55Cancri** [comment]
> For some reason, pdfjs-dist version "4.4.168" is not being installed with react-pdf@latest, so I installed pdfjs-dist version "4.4.168" separately, and it works smoothly. ❤️

This fixed it for me as well, thank you!

**Comment by javiertorresm2000** [comment]
@utkershrajvenshi did you solve this issue?

> [@pk-bt](https://github.com/pk-bt) Were you able to solve this issue without having the worker being fetched from "unpkg"? I'm having similar issues with v9 except the error I'm getting is: `Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of “application/octet-stream”. Strict MIME type checking is enforced for module scripts per HTML spec`

I'm facing the same one with latests versions at March 13 2025, react pdf v9.21 and pdfjs-dist v4.8.69, locally it works but in production I get the same error, according to this question in StackOverflow https://stackoverflow.com/a/78949012/16589622 there's a thing with the nginx.config file, I tried the solution mentioned there but then as soon as I reload the page, the browser tries to save my page, like if you click "Ctrl + s", I cancel it and then it continues appearing, so did you manage to solve this issue?

**Comment by utkershrajvenshi** [comment]
> > [@sureshsamanthapudi](https://github.com/sureshsamanthapudi) I've checked my app and I don't seem to be getting the error you mentioned.
> > In my case, I deployed as an Azure Static Web App using the Microsoft Teams Toolkit. It seems to load fine without the error you mentioned.
> > Reference this [link](https://stackoverflow.com/questions/72070748/failed-to-load-module-script-expected-a-javascript-module-script-but-the-server) I think it's worth checking how the path to load the module is set up.
> > I'm loading the module files like this. ![스크린샷 2024-07-04 오전 9 18 51](https://private-user-images.githubusercontent.com/76121068/345654781-8e91804f-bf75-4407-b0a3-b099897338a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDMwMjIsIm5iZiI6MTcyMDEwMjcyMiwicGF0aCI6Ii83NjEyMTA2OC8zNDU2NTQ3ODEtOGU5MTgwNGYtYmY3NS00NDA3LWIwYTMtYjA5OTg5NzMzOGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE0MTg0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NDNlMDAyZDlkZWQwMzJjN2YzYzgzNjc3YzI1ZjExODk3NTViZDBjMDdlN2Y5YzYyM2U1M2VjN2I1M2UzYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yo4Fy_X_GzGZwHAuEQFN_p0AN46GupkARk94ECux0Sk)
> 
> It worked fine with the below mentioned code.
> 
> pdfjs.GlobalWorkerOptions.workerSrc = new URL( 'pdfjs-dist/build/pdf.worker.min.mjs', import.meta.url, ).toString();
> 
> and add the below mentioned MIME type to nginx.conf
> 
> application/javascript mjs;
> 
> Thank you [@silvertae](https://github.com/silvertae)

This solution worked for me @javiertorresm2000

**Comment by ComplexRalex** [comment]
@javiertorresm2000 the same is happening here. Did you manage to fix it?

**Comment by ComplexRalex** [comment]
Just for the record, I managed to fix my error by writing this in my `nginx.config`.

I first tried with @jiangxiaoqiang's solution, and I got the same problem as @javiertorresm2000. With some more research, I could find a solution to the problem (I'm new to `nginx`, if you are wondering...)

```sh
location / {
    try_files $uri /index.html;
    location ~* \.mjs$ { # This part from here!
        types {
            text/javascript mjs;
        }
    }
}
```

Thanks to this response in another issue! https://github.com/mozilla/pdf.js/issues/17296#issuecomment-2298713658.

**Comment by javiertorresm2000** [comment]
I think I'll try that solution, meanwhile I had to downgrade the version to make it work, fortunately I only needed to show a preview of the PDF, but maybe in a couple of weeks I'll try that solution, thanks @ComplexRalex!

**Comment by SkyC0der** [comment]
What's the solution if you deployed with vercel?

**Comment by lissettdm** [comment]
This worked for me: 
```
import { Document, Page, pdfjs } from "react-pdf";
import { WorkerMessageHandler } from "pdfjs-dist/build/pdf.worker.min.mjs";

pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  WorkerMessageHandler,
  import.meta.url
).toString();
```

**Comment by Gonzalo-Imprint** [comment]
Hi, following this thread I installed `pdfjs-dist` and `react-pdf`, added the 

```
import { Document, Page, pdfjs } from 'react-pdf';
import { WorkerMessageHandler } from "pdfjs-dist/build/pdf.worker.min.mjs";

pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  WorkerMessageHandler,
  import.meta.url
).toString();
```

to the component but I get the following error `react-pdf.js?v=e17c0247:41 Warning: UnknownErrorException: The API version "5.3.31" does not match the Worker version "5.4.54".`

**Comment by utkershrajvenshi** [comment]
> Hi, following this thread I installed `pdfjs-dist` and `react-pdf`, added the 
> 
> ```
> import { Document, Page, pdfjs } from 'react-pdf';
> import { WorkerMessageHandler } from "pdfjs-dist/build/pdf.worker.min.mjs";
> 
> pdfjs.GlobalWorkerOptions.workerSrc = new URL(
>   WorkerMessageHandler,
>   import.meta.url
> ).toString();
> ```
> 
> to the component but I get the following error `react-pdf.js?v=e17c0247:41 Warning: UnknownErrorException: The API version "5.3.31" does not match the Worker version "5.4.54".`

Try downgrading `pdfjs-dist` to 5.3.31. Share what happens...

**Comment by Gonzalo-Imprint** [comment]
> > Hi, following this thread I installed `pdfjs-dist` and `react-pdf`, added the
> > ```
> > import { Document, Page, pdfjs } from 'react-pdf';
> > import { WorkerMessageHandler } from "pdfjs-dist/build/pdf.worker.min.mjs";
> > 
> > pdfjs.GlobalWorkerOptions.workerSrc = new URL(
> >   WorkerMessageHandler,
> >   import.meta.url
> > ).toString();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to the component but I get the following error `react-pdf.js?v=e17c0247:41 Warning: UnknownErrorException: The API version "5.3.31" does not match the Worker version "5.4.54".`
> 
> Try downgrading `pdfjs-dist` to 5.3.31. Share what happens...

It worked doing the following:
Deleted node_modules folder and package-lock.json file.
`npm i react-pdf`
`npm i pdfjs-dist@5.3.31`
Do a hard refresh on the browser and try it again.
