### ISSUE TITLE
Text layer is omitting spaces in sentences than span multiple lines in annotation layer making multi line search and highlight difficult

### ISSUE THREAD

**Issue by ed-sparkes** [wojtekmaj/react-pdf#1827]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Each line of text is split into a separate span, where there would be a natural space between the end of one line and another, that space is included in neither the first of second span. 

in order to achieve this mark up i had to provide this lookup string 

`So I think it goes both ways,actually. On the one hand, you have Gen Z needingto`

whereas i would expect this to work with 

`So I think it goes both ways, actually. On the one hand, you have Gen Z needing to`

<img width="265" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/1023491/88d603aa-5d5a-43b9-bb25-e8431c6c3e4d">

### Steps to reproduce

Go to the demo https://projects.wojtekmaj.pl/react-pdf/
and inspect the source 

you can see in this screenshot there is no space between `solades` in one span and `placerat dui.` in the next span. given they are separate words in a sentence there should be 

to allow search across multiple spans.

<img width="2498" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/1023491/a5017403-c2cd-471d-9d08-2bad39f1d7fb">

### Expected behavior

the space at line breaks is included somehow

### Actual behavior

it is not

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: 8.0.0
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by nike1v** [comment]
I'll take some responsibility and answer this somehow:
This is not related to this library, instead this is how the PDF.JS library works (which is a heart of react-pdf). So this is a request for the PDF.JS library.

**Comment by wojtekmaj** [comment]
That's correct @nike1v - there's nothing we can do regarding text layer rendering itself. I can see how multi-line search could be improved though - despite space not being there, searching for "sodales placerat" should somehow work.
