### ISSUE TITLE
Text layer may contain overlapping areas (react-pdf 9.0.0)

### ISSUE THREAD

**Issue by obecker** [wojtekmaj/react-pdf#1828]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

After upgrading react-pdf from 8.0.2 to 9.0.0 I observed that consecutive spans in the same line within the text layer may overlap (i.e. the spans are too wide). This prevents the correct selection of text in the document.

This is an example from the provided sample.pdf (page 2, penultimate paragraph):

<img width="646" alt="Bildschirmfoto 2024-06-11 um 12 57 07" src="https://github.com/wojtekmaj/react-pdf/assets/197628/f6abe261-f91e-4c71-be16-189049ae6c79">

You can see the overlapping area at the word "bibendum".

Now, while I supposed that this must be something in the core pdf.js library, I am unable to reproduce the behavior in the pdf.js demo. I even downloaded the latest (4.3.136) release from https://github.com/mozilla/pdf.js/releases, ran `npx serve` in the extracted folder, and opened `web/viewer.html` with the sample.pdf - the issue is not there.

If you want to test it with a different PDF, try https://www.vbg.de/cms/_Resources/Persistent/7/0/d/c/70dc78bec739e6cbe27bc8ba77a16d15347461d7/M_Arzt_Anforderungen.pdf and here the last list item on the first page ("über Kenntnisse in der erforderlichen Röntgentechnik und Röntgendiagnostik verfügen.")

### Steps to reproduce

Run `yarn run dev` in [sample/create-react-app-5](https://github.com/wojtekmaj/react-pdf/tree/main/sample/create-react-app-5), scroll to page 2 and select the first line of the penultimate paragraph.

Try to select and copy the word `justo'

### Expected behavior

The selected areas don't overlap. The word 'justo' gets copied.

### Actual behavior

They do overlap. The copied text is 'utat'

### Environment

- **Browser (if applicable)**: Firefox 126.0.1, latest Chrome, Opera, MS Edge (all macOS)
- **React-PDF version**: 9.0.0
- **React version**: 18.2.0
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Hmmmm, I can reproduce this:

<img width="691" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/5426427/c9790a9d-4559-477f-b6f2-e85bfec179ab">

Oddly enough, this doesn't happen for me in all cases. Our test suite is free from this issue (it seems), but samples are not.

**Comment by huuphat1908** [comment]
Same issue

**Comment by obecker** [comment]
Apparently this issue is still present in 9.1.0. I would like to help resolving this issue, however I have no idea where to start and what might causing this.

By the way, I also tried https://github.com/wojtekmaj/react-pdf/tree/main/test/test.pdf, and it gives me a completely different result, where some text areas are too small/short:

<img width="681" alt="Bildschirmfoto 2024-08-11 um 19 39 04" src="https://github.com/user-attachments/assets/e67bcb0d-cdd2-44e6-82d3-37a0d086b698">

**Comment by obecker** [comment]
Seems to be related to (or even a duplicate of) https://github.com/wojtekmaj/react-pdf/issues/1848

**Comment by obecker** [comment]
Using the approach described in https://github.com/wojtekmaj/react-pdf/issues/1848#issuecomment-2325292501 also solved this issue, so I will close it as a duplicate.
