### ISSUE TITLE
`options` prop's type resolved as any

### ISSUE THREAD

**Issue by oceandrama** [wojtekmaj/react-pdf#1835]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

![image](https://github.com/wojtekmaj/react-pdf/assets/23439079/66e6e1f4-dea1-4939-ac26-12acc5542ad5)

### Steps to reproduce

-

### Expected behavior

Type resolved correctly

### Actual behavior

Type resolved as any

### Environment

- **React-PDF version**: 9.0.0

**Comment by wojtekmaj** [comment]
Works for me. Temporary TS server quirk? Corrupted npm install?

<img width="827" alt="image" src="https://github.com/wojtekmaj/react-pdf/assets/5426427/90e2eaf0-dba2-46f9-8dff-87b939574711">

**Comment by oceandrama** [comment]
Looks like the problem on my side, now everything is working fine
