### ISSUE TITLE
Pdf flickering issue on page change after upgrading to v9.0

### ISSUE THREAD

**Issue by anandmainali5** [wojtekmaj/react-pdf#1836]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

When changing pdf file page flickering occurs.. also, same file is fetched on each page change.
and some black screen is shown in buttom of the page.

Here's the screenshot attached:
<img width="1454" alt="Screenshot 2024-06-27 at 11 20 08 AM" src="https://github.com/wojtekmaj/react-pdf/assets/96724138/683cae25-f736-48da-9893-a61c14b7df0f">

### Steps to reproduce

Upload pdf file and try to change the page on pdf view. it'll show the flickering.

### Expected behavior

Smooth pdf page change without black screen in bottom of screen.

### Actual behavior

When changing pdf file page flickering occurs.. also, same file is fetched on each page change.
and some black screen is shown in buttom of the page.

Its adding ```<canvas class="hiddenCanvasElement" lang="en"></canvas>``` code above the body closing tag.

Sometimes it adds ```<canvas class="hiddenCanvasElement" lang="en" height="0" width="0"></canvas>``` which doesn't show the black canvas.

### Environment

- **Browser (if applicable)**: Chrome, Brave
- **React-PDF version**: v9.0.0
- **React version**: ^17.0.2

**Comment by pcwa-ahendricks** [comment]
Seems like upgrading to 9.1 fixed this issue for me but I didn't explcitly see anything like this in the Release Notes..
