### ISSUE TITLE
Getting current page number

### ISSUE THREAD

**Issue by HaswinVidanage** [wojtekmaj/react-pdf#184]
My app requires multiple pages to be rendered along with a table of content on the side. I got the multiple pages figured out, but wondering if if there's a way for me to get the current page the user is, in multiple page rendering option. Thanks in advance.

**Comment by HaswinVidanage** [comment]
I did take an approach similar to your option 1 and it was quite laggy with a large pdf. Will try option 2 and thanks for the tip on  lodash.throttle or lodash.debounce. :) 👍

**Comment by wojtekmaj** [comment]
Another option, much more modern one and probably the best, but haven't tried this one yet - happy experimenting :)

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by EbubeUd** [comment]
Hey, I have a react app that creates a PDF and generates a link for the user to download the document. I want every page in  the downloaded document to contain the page number. How do I achieve this using react-pdf? 

I have read the doc countless times but I dont seem to find a solution that works

**Comment by wojtekmaj** [comment]
React-PDF only reads the PDFs. It does not allow writing to PDFs. You will not be able to add page numbers to PDFs using this package.

**Comment by EbubeUd** [comment]
Hello, thanks for the reply.

Basically, I am not trying to write to an existing PDF document. I created
the document using @react-pdf/renderer. with <Document>, <View> and <Text>
I added texts and an image to the document. Now all I want is for the
document to bear the page numbers in the process of creating the
document. Liike the first page bears 1, the second bears 2, etc.
Do you mean this is not also possible?

**Comment by wojtekmaj** [comment]
Wrong repository.

**Comment by speix** [comment]
Using the **Intersection Observer API** to accomplish this is the better solution here:

Say you have a div under which you place the Document component: 
```
<div id="scrollArea">
   <Document ... />
</div>
```

All you have to do is attach the observer to check when the state of the **IntersectionObserverEntry.isIntersecting** attribute is changing from false, to true. 

For example if I wanted to see if a user scrolled to the last page of a 17-page user agreement document, I would do:
let options = {
    root: document.querySelector('#scrollAgreementArea'),
    rootMargin: '0px',
    threshold: 0.2
  }

let callback = (entries, observer) => {
    entries.forEach(entry => {
      console.log(entry);
      // Each entry describes an intersection change for one observed
      // target element:
      //   entry.boundingClientRect
      //   entry.intersectionRatio
      //   entry.intersectionRect
      //   entry.isIntersecting
      //   entry.rootBounds
      //   entry.target
      //   entry.time
    });
  };

let observer = new IntersectionObserver(callback, options);
let target = document.querySelector('.react-pdf__Page[data-page-number="17"]');

const pageRendered = () => {
    renderedPage += 1;
    if (renderedPage == 16) {
      observer.observe(target);
    }
  }

**Comment by worktechnotoil** [comment]
My Simple Solution 👍 

1 : Add event listener : 

         document.querySelector("#scrollArea").addEventListener("scroll", listener);

2 :  add listener function

     function listener(el) {
   
    console.log("scrollTop", el.target.scrollTop);
    console.log("scrollHeight", el.target.scrollHeight);
    console.log("scrollWidth", el.target.scrollWidth);
   
  }

3 : formula 👍 

    overall pdf height( scrollHeight ) / total number of pages = average or per page height .
   
  for example 
         20295  / 23 = 882
if scrollTop : 882 = page 1
if scrollTop : 1764 = page 2
