### ISSUE TITLE
Build not working with Next

### ISSUE THREAD

**Issue by ivanpajon** [wojtekmaj/react-pdf#1841]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Configuration for using workerSrc in Next is not working. In local development with `next dev` is working, but when you try to do `next build` it fails.
With the example of the [sample projects](https://github.com/wojtekmaj/react-pdf/tree/main/sample/next-app) also fails.

### Steps to reproduce

1. Try to do `next build`

### Expected behavior

1. It compiles and runs fine

### Actual behavior

1. It fails in building process

### Additional information

[Here](https://github.com/ivanpajon/react-pdf-build-error/blob/develop/app/Sample.tsx) is a sample repo. But literally you can use the official I mentioned above. And it fails with and without turbo mode enabled.

### Environment

- **Browser (if applicable)**: Any
- **React-PDF version**: 9.1.0
- **React version**: 18.3.1
- **Bundler name and version (if applicable)**:

**Comment by wojtekmaj** [comment]
- Next.js 15 is not out yet
- Next.js 15 contains breaking changes, specifically removes Terser minifier, while SWC minifier implementation was buggy
- The Next.js issue in question was not [resolved](https://github.com/vercel/next.js/pull/66817) until last week's canary, specifically [v15.0.0-canary.53](https://github.com/vercel/next.js/releases/tag/v15.0.0-canary.53), and v15.0.0-rc.0 is over 2 months old

**Comment by ivanpajon** [comment]
In Next 14 and React 18 it's not working either... I tried with Next 15 and React 19 so it can be reproduced in Stackblitz.

**Comment by wojtekmaj** [comment]
Well, samples included in the repo are definitely working for me; otherwise there would be no release. If you encounter any issues with it, please report it while sharing the error message you got, and we'll work from here.
