### ISSUE TITLE
Warning onload file and can't view on safari

### ISSUE THREAD

**Issue by raibann** [wojtekmaj/react-pdf#1846]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

![Untitled](https://github.com/user-attachments/assets/d419a057-442a-4c3e-8b40-4b33df63682f)

### Steps to reproduce

![Untitled](https://github.com/user-attachments/assets/d419a057-442a-4c3e-8b40-4b33df63682f)

### Expected behavior

![Untitled](https://github.com/user-attachments/assets/d419a057-442a-4c3e-8b40-4b33df63682f)

### Actual behavior

![Untitled](https://github.com/user-attachments/assets/d419a057-442a-4c3e-8b40-4b33df63682f)

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Bundler name and version (if applicable)**:

**Comment by wojtekmaj** [comment]
These warnings are fine and sometimes occur. On why it doesn't show up on Safari, you provided me with zero details to work on.
