### ISSUE TITLE
Why is the text of the PDF gone when using react-pdf?

### ISSUE THREAD

**Issue by Lsw-98** [wojtekmaj/react-pdf#1849]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

Why is the text of the PDF gone when using react-pdf?
<img width="975" alt="image" src="https://github.com/user-attachments/assets/6f3121da-7f13-4902-ace1-bd3df9281117">

**Comment by Sunset-Kim** [comment]
I found this helpful in issue #1684
