### ISSUE TITLE
Chrome 76 cannot work normally

### ISSUE THREAD

**Issue by ZtfCoder** [wojtekmaj/react-pdf#1859]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I use react-pdf 6.2.2 but  Chrome 76 cannot work normally

Chrome 76 cannot work normally

![image](https://github.com/user-attachments/assets/ccdea570-1a06-489d-b20d-5d8482b0a0e7)

![image](https://github.com/user-attachments/assets/9ce8f787-e633-4909-bf2f-1d497d1e82be)

### Steps to reproduce

no

### Expected behavior

Normal display

### Actual behavior

Normal display

### Environment

- **Browser (if applicable)**: chrome 76.0.3809.100
- **React-PDF version**: 6.2.2
- **React version**: react 17
- **Bundler name and version (if applicable)**:next 12

**Comment by wojtekmaj** [comment]
I don't have access to your app, so the message you provided doesn't allow me to understand which line it's crashing on.

**Comment by ZtfCoder** [comment]
> I don't have access to your app, so the message you provided doesn't allow me to understand which line it's crashing on.

Hello, I tried again and imported compatible ones according to the document pdfjs-dist/legacy/build/pdf.worker.min.mjs, But I am on Vite's local system, and the error message is still mine

![image](https://github.com/user-attachments/assets/55c959b6-8bbc-4986-9157-9cc428bdb0f0)
![image](https://github.com/user-attachments/assets/d625c0e2-54dd-4fd3-bcae-8f45867db2a3)

is chrome 87
"react-pdf": "6.2.2",
I went to check the source code and found that it might be this code
![image](https://github.com/user-attachments/assets/3a0788ec-e089-4db6-a5d4-c5bab6dabeb5)


This compatibility card has been stuck for a long time. If possible, could you please take a look at this issue? Thank you 🙏

**Comment by ZtfCoder** [comment]
I uploaded the first image incorrectly. Currently, I am using 

/**
 * @Date: 2024-06-27 11:42:43
 * @Description: PDF预览
 * https://github.com/wojtekmaj/react-pdf/blob/v6.x/README.md
 */

import { useState } from "react";
import styles from "./index.module.scss";
import { Document, Page, pdfjs } from "react-pdf";
import "react-pdf/dist/esm/Page/AnnotationLayer.css";
import "react-pdf/dist/esm/Page/TextLayer.css";
import { getYPCdnImgUrl } from "@yp/core/config";
import React from "react";
// pdfjs.GlobalWorkerOptions.workerSrc = getYPCdnImgUrl("wp/pdf.worker.min.js");
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/legacy/build/pdf.worker.min.mjs`;
console.log(pdfjs.GlobalWorkerOptions.workerSrc);

const Loading = (props: { text?: string }) => {
  const text = props.text || "正在加载中";
  return (
    <div className={styles.loading}>
      <img src={getYPCdnImgUrl("wp/file_loading.svg")} alt={text} />
      <div className={styles.text}>{text}</div>
    </div>
  );
};

const PdfView = ({ url, width, ...other }: { url: string; width?: number }) => {
  const [numPages, setNumPages] = useState(0);
  const [pagesToRender, setPagesToRender] = useState([1]);

  const onDocumentLoadSuccess = ({ numPages }: any) => {
    setNumPages(numPages);
    setPagesToRender([1]); // 初始化时只渲染第一页
  };

  const loadMorePages = () => {
    setPagesToRender((prevPages) => {
      const nextPage = prevPages.length + 1;
      if (nextPage <= numPages) {
        return [...prevPages, nextPage];
      }
      return prevPages;
    });
  };

  return (
    <Document
      file={url}
      onLoadSuccess={onDocumentLoadSuccess}
      options={{
        cMapUrl: "https://cdn.yupaowang.com/yupao_hybrid_h5/pdf-cmaps/cmaps/",
        cMapPacked: true,
      }}
      className={styles.pdfBox}
      loading={<Loading />}
      error={<Loading text="预览失败，请稍后重试" />}
      {...other}
    >
      {pagesToRender.map((pageNumber) => (
        <Page
          key={`page_${pageNumber}`}
          onRenderSuccess={() => {
            loadMorePages();
          }}
          pageNumber={pageNumber}
          className={styles.page}
          width={width || 687}
          loading={<></>}
        />
      ))}
    </Document>
  );
};
export default PdfView;

**Comment by ZtfCoder** [comment]
```react
/**
 * @Date: 2024-06-27 11:42:43
 * @Description: PDF预览
 * https://github.com/wojtekmaj/react-pdf/blob/v6.x/README.md
 */

import { useState } from "react";
import styles from "./index.module.scss";
import { Document, Page, pdfjs } from "react-pdf";
import "react-pdf/dist/esm/Page/AnnotationLayer.css";
import "react-pdf/dist/esm/Page/TextLayer.css";
import { getYPCdnImgUrl } from "@yp/core/config";
import React from "react";
// pdfjs.GlobalWorkerOptions.workerSrc = getYPCdnImgUrl("wp/pdf.worker.min.js");
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/legacy/build/pdf.worker.min.mjs`;
console.log(pdfjs.GlobalWorkerOptions.workerSrc);

const Loading = (props: { text?: string }) => {
  const text = props.text || "正在加载中";
  return (
    <div className={styles.loading}>
      <img src={getYPCdnImgUrl("wp/file_loading.svg")} alt={text} />
      <div className={styles.text}>{text}</div>
    </div>
  );
};

const PdfView = ({ url, width, ...other }: { url: string; width?: number }) => {
  const [numPages, setNumPages] = useState(0);
  const [pagesToRender, setPagesToRender] = useState([1]);

  const onDocumentLoadSuccess = ({ numPages }: any) => {
    setNumPages(numPages);
    setPagesToRender([1]); // 初始化时只渲染第一页
  };

  const loadMorePages = () => {
    setPagesToRender((prevPages) => {
      const nextPage = prevPages.length + 1;
      if (nextPage <= numPages) {
        return [...prevPages, nextPage];
      }
      return prevPages;
    });
  };

  return (
    <Document
      file={url}
      onLoadSuccess={onDocumentLoadSuccess}
      options={{
        cMapUrl: "https://cdn.yupaowang.com/yupao_hybrid_h5/pdf-cmaps/cmaps/",
        cMapPacked: true,
      }}
      className={styles.pdfBox}
      loading={<Loading />}
      error={<Loading text="预览失败，请稍后重试" />}
      {...other}
    >
      {pagesToRender.map((pageNumber) => (
        <Page
          key={`page_${pageNumber}`}
          onRenderSuccess={() => {
            loadMorePages();
          }}
          pageNumber={pageNumber}
          className={styles.page}
          width={width || 687}
          loading={<></>}
        />
      ))}
    </Document>
  );
};
export default PdfView;

```

**Comment by ZtfCoder** [comment]
![image](https://github.com/user-attachments/assets/60ff1915-e1fb-4931-bc14-2fd383d64757)
I may already know why, it's because this tools.js uses the Array at method, but this method only supports Chrome 96 and above. How can I be compatible with this

**Comment by ZtfCoder** [comment]
![image](https://github.com/user-attachments/assets/b7527992-aa07-40ca-aa04-f02285feec23)
