### ISSUE TITLE
onItemClick is not working

### ISSUE THREAD

**Issue by lakshmipm** [wojtekmaj/react-pdf#187]
Below is my code.When i click on the item click event is not working. 

```
onPageClick = ({ pageNumber }) => {
    alert('Clicked an item from page ' + pageNumber + '!')
}

 let display = [1,2,3,4,5].map((page, index) => {
        return (<Page key={index} onItemClick={this.onPageClick} pageNumber={index + 1} scale={1.0} width={100} />)
    });

<Document  file={this.state.fileDatapdf}               
           onItemClick={this.onPageClick}
           > {display}</Document>
```

**Comment by wojtekmaj** [comment]
Hey @lakshmipm, if you're on version older than v3.0.3 please update. If you are on the newest possible release I'd need to see a working example to help you, what you've sent looks perfectly okay to me.

**Comment by HugoGEORGET** [comment]
Hey there,

I am encountering the same problem on v3.0.5.
I also don't have any warning or error in the console.

Here's the code :
```
import React, {Component} from 'react';
import {Document, Page} from 'react-pdf/dist/entry.webpack';
import PropTypes from 'prop-types';

class Pdf extends Component {

    onItemClick = () => alert('Clicked an item !');

    render() {
        return (
            <div className="pdf">
                <Document
                    file={this.props.pdfUrl}
                    onItemClick={this.onItemClick}
                    error={"Le chargement du PDF a échoué."}
                    loading={"Chargement du PDF en cours..."}
                    noData={"Aucun fichier PDF spécifié."}
                >
                    <Page
                        pageNumber={this.props.pageNumber}
                        width={125}
                    />
                </Document>
            </div>
        );
    }

    // props validation
    static propTypes = {
        pdfUrl: PropTypes.string,
        pageNumber: PropTypes.number
    };
}

export default Pdf;
```

And the component called by App.js 

```
<Pdf
    pdfUrl={pdf_url}
    pageNumber={2}
/>
```

(You can see that I'm passing pageNumber as a prop)
The PDF correctly loads but doesn't seem clickable ?

Also, if I add parenthesizes to have `onItemClick={this.OnItemClick()}`, the alert is displayed once per PDF which means that the onItemClick function is correct !

I've tried on both Firefox 60 and Chrome 67.

Thank you for your help and the package !

**Comment by wojtekmaj** [comment]
Hey there,
ah yes. You're both not rendering any Outline, so `onItemClick` doesn't make any sense, really. `onItemClick` is a function which gives you a callback on an even of the user clicking on an outline item. It should have been called `onOutlineItemClick`, yeah. :(

**Comment by Praveen111** [comment]
Hey @wojtekmaj : It's not working for me as well, could you please give code example where this onItemClick works ?

**Comment by Praveen111** [comment]
This is my render method ---- >

render() {
    const { pageNumber, numPages } = this.state;
    const pages = [...Array(numPages)].filter((val,i) => i+1);
console.log(this.state,pages)
    return (
      <div>
        <Document
          file={this.props.file}
          onLoadSuccess={this.onDocumentLoad}
          onItemClick={this.onItemClick}
        >
<Outline />
        {pages.map((e,i) => <Page key={i} pageNumber={i}  />)}
         
        </Document>
        <p>Page {pageNumber} of {numPages}</p>
      </div>
    );
  }
}

**Comment by wojtekmaj** [comment]
@Praveen111 https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-interactive-table-of-contents
