### ISSUE TITLE
[workaround found] "Failed to load PDF file.", "The API version "4.4.168" does not match the Worker version "4.6.82".

### ISSUE THREAD

**Issue by sanjarcode** [wojtekmaj/react-pdf#1873]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

## Problem
Code:
```jsx
<Document file={fileAsBase64String} />
```

This renders "Failed to load PDF file."

## Workaround fix (found) ✅
In package.json, fix the version of `pdfjs-util`, from "^4.6.82" to "4.4.168" by running 
```sh
pnpm i --save --save-exact pdfjs-dist@4.4.168
```

### Steps to reproduce

1. Create a React project using Vite
2. Use the `Document` component
3. Do extra steps for latest React mentioned in [README](https://github.com/wojtekmaj/react-pdf?tab=readme-ov-file#configure-pdfjs-worker)

### Expected behavior

PDF should render

### Actual behavior

The PDF does not render.
`Failed to load PDF file.` is rendered.
`The API version "4.4.168" does not match the Worker version "4.6.82"` error is logged in the console

### Additional information

Vite + pnpm

### Environment

- **Browser (if applicable)**: Chrome on Macos
- **React-PDF version**: 9.1.0
- **React version**: 18.3.1
- **Bundler name and version (if applicable)**: esbuild + rollup (Vite)

**Comment by wojtekmaj** [comment]
In general, you shouldn't need to install pdfjs-dist manually. If you do, you risk having version conflicts like that.

**Comment by lnhrdt** [comment]
Hey @wojtekmaj! I think the important context here is pnpm intentionally prohibits the use of transitive dependencies (unless you circumvent the behavior with their "[shamefully hoist](https://pnpm.io/npmrc#shamefully-hoist)" setting).

Since this library's instructions depend on importing from pdfjs-dist as a transitive dependency, pnpm users will always have this issue, and probably end up needing to install exact versions as @sanjarcode indicated.

Any potential future improvements that you see to change the use transitive dependencies @wojtekmaj?

**Comment by wojtekmaj** [comment]
I've had this idea of making pdfjs-dist a peerDependency and allow a wider range of versions to choose from. I think that would fix it.

**Comment by sanjarcode** [comment]
> In general, you shouldn't need to install pdfjs-dist manually. If you do, you risk having version conflicts like that.

Okay. Can you suggest an alternative way, is it the steps here https://github.com/wojtekmaj/react-pdf?tab=readme-ov-file#vite ?
