### ISSUE TITLE
Failed to load PDF file

### ISSUE THREAD

**Issue by philigrane** [wojtekmaj/react-pdf#188]
Hey,
i test your module and y have this error "Failed to load PDF file"
I attach the log file and the pdf file.
Phil
[localhost-1523891510551.log](https://github.com/wojtekmaj/react-pdf/files/1915952/localhost-1523891510551.log)
[htmlcheatsheet.pdf](https://github.com/wojtekmaj/react-pdf/files/1915953/htmlcheatsheet.pdf)

**Comment by philigrane** [comment]
For information this work with the lastest prebuild
 stable (v1.9.426) from "mozilla.github.io/pdf.js/"
Y attach the files y uses for my test.
[mytest.zip](https://github.com/wojtekmaj/react-pdf/files/1920100/mytest.zip)

**Comment by wojtekmaj** [comment]
Hey there,
it loads just fine on [my test suite](http://projekty.wojtekmaj.pl/react-pdf/test/), so you must be doing something wrong. Would you share your implementation of React-PDF?

**Comment by philigrane** [comment]
Y attach the files of my app. Y use yarn for information.
[my-app.zip](https://github.com/wojtekmaj/react-pdf/files/1927551/my-app.zip)

**Comment by wojtekmaj** [comment]
Hi @philigrane,
thanks for the example.
The reason you're getting an error is that the path `"../public/tizenfordummies.pdf"` is not automatically resolved in any way. Since you have already included your PDF file in `public` folder, which is also your Parcel output folder, in `file` prop you should use a path *relative to output folder*, so in your case simply `"tizenfordummies.pdf"`.

Another way to do this is to configure your Webpack to use `file-loader` for PDF files, and import a PDF file as a module:

```js
import file from '../public/tizenfordummies.pdf'
// and then
<Document file={file} />
```

Hope it helps!

**Comment by philigrane** [comment]
Hi @wojtekmaj , 
it works. Thank you very much. Sorry for making you waste your time for this.
Another question: I used your test to display the button for managing pages.
My file is read since the number of pages is displayed but my page does not appear on the screen.
Here is the code:
```
import React, { Component } from "react";
import { Document } from "react-pdf";
class Pdf extends Component {
    state = {
      numPages: null,
      pageNumber: 1,
    }
    error(error) {
      console.log(error);
    }
    onDocumentLoad = ({ numPages, pageNumber }) =>
      this.setState({
      numPages, pageNumber
    })
    onItemClick = ({ pageNumber }) =>
      this.setState({ pageNumber
    })
    previousPage = () => this.changePage(-1)
    nextPage = () => this.changePage(1)
    changePage = offset =>
      this.setState(prevState => ({
        pageNumber: (prevState.pageNumber || 1) + offset,
    }))
    render() {
      const { pageNumber, numPages } = this.state;
      return (
        <div>
          <Document
            file = "tizenfordummies.pdf"
            onLoadSuccess={this.onDocumentLoad}
            onItemClick={this.onItemClick}
          >
          </Document>
                 <div>
                  <button
                    disabled={pageNumber <= 1}
                    onClick={this.previousPage}
                  >
                    Précedante
                  </button>
                  <span>Page {pageNumber || (numPages ? 1 : '--')} sur {numPages || '--'}</span>
                  <button
                    disabled={pageNumber >= numPages}
                    onClick={this.nextPage}
                  >
                    Suivante
                  </button>
                </div>
        </div>
      );
    }
}
export default Pdf;
```
Thanks for your help...

**Comment by wojtekmaj** [comment]
Your page does not appear on the screen because you didn't put it in Document.

**Comment by philigrane** [comment]
Thank, what a numbskull! That's working.
I've missing this : `<Page pageNumber={pageNumber} />` in Document.
For display the first page i put this `this.changePage(0)`  in 'onDocumentLoad'. I'm dont sure that's the best solution but that work.
Sorry for my English

**Comment by wojtekmaj** [comment]
You shouldn't need to use `this.changePage(0)` as you have default pageNumber set in your component's state. But this should work fine anyway.

**Comment by Abishek-Sudhakaran** [comment]
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 sir i'm getting the above warning and my pdf is not rendering

**Comment by shrutibakutra** [comment]
> Hey there, it loads just fine on [my test suite](http://projekty.wojtekmaj.pl/react-pdf/test/), so you must be doing something wrong. Would you share your implementation of React-PDF?

Hey @wojtekmaj , I checked your test suite. It doesnt work if we pass any url. I get message saying "Failed to load PDF file." It works only if we use file from our system. Can you please suggest something?
