### ISSUE TITLE
react/jsx-runtime.js in version > 8

### ISSUE THREAD

**Issue by leticiafontoura** [wojtekmaj/react-pdf#1881]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I updated react-pdf to 9 to solve the security issues on my project. However, when running tests, I get this error:

`Cannot find module '/etc/chronos-teste/node_modules/react/jsx-runtime' imported from /etc/chronos-teste/node_modules/react-pdf/dist/esm/Document.js
Did you mean to import react/jsx-runtime.js?`

I've tried so many things to fix this. I even started a vite project from 0 to see if I could catch the exact moment this errors happens. 

### Steps to reproduce

Update react-pdf to a version higher than 8

### Expected behavior

It should not fail my tests

### Actual behavior

It is failing my tests because of jsx-runtime

### Additional information

I read lots of reports about weird errors occurring and I noticed the claim to use Vitest instead of Jest. I switched my whole project from CRA to Vite and fixed my tests to run with vitest. Still getting this one error tho.

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 9.1.1
- **React version**: 17.0.2
- **Bundler name and version (if applicable)**: Vite 5.4.1 and Vitest 2.1.1

**Comment by SelimCanGuler** [comment]
I have encountered the same error. My stack is different from yours but I guess if I share my solution you can find the Vite counterpart of it. I solved it by adding the following to my webpack config file:

```js
resolve: {
  alias: {
    'react/jsx-dev-runtime': 'react/jsx-dev-runtime.js',
    'react/jsx-runtime': 'react/jsx-runtime.js',
  },
}
```

It practically fixes the imports in the `Document` and `Page` by providing the correct versions.

**Comment by wojtekmaj** [comment]
It seems like React 17 was not yet ready for working out-of-the-box in pure ESM environments. React 18 has `package.json` `exports` defined to prevent this error.

Best solution would be to upgrade to React 18, but if all else fails, @SelimCanGuler's solution is pretty clever.
