### ISSUE TITLE
Warnings in installation

### ISSUE THREAD

**Issue by sumy77** [wojtekmaj/react-pdf#1886]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

There are some warnings coming on installing this package.

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated gauge@3.0.2: This package is no longer supported.

### Steps to reproduce

Warnings come during installation.

### Expected behavior

Deprecated warnings and memory leaks should not come and should be resolved.

### Actual behavior

Package should get installed without any warning.

### Environment

- **Browser (if applicable)**: NA
- **React-PDF version**: 9.1.1
- **React version**: 18.3.1
- **Bundler name and version (if applicable)**: Vite v5.4.1

**Comment by wojtekmaj** [comment]
Most of them if not all are caused by canvas package, an indirect dependency added by pdfjs-dist. canvas v3 is coming, but is not out there yet. Once out, pdfjs-dist will need to have it updated, and then finally we will be able to update pdfjs-dist on our side. Until then, there's nothing I can do.
