### ISSUE TITLE
Flickering occuring when the Document is placed in a position scrolled down the page

### ISSUE THREAD

**Issue by kairoswealth** [wojtekmaj/react-pdf#1888]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I have placed the Document viewer at the bottom of a long page, and to view it, user needs to scroll down.
I have implemented page change buttons, and when I change page, the screen is flickering.
During the flicker, I can clearly see that the top portion of the page becomes briefly visible briefly before going back to see the scrolled down area where we were previously while clicking the button.

react-pdf v9.1.1
react v18.2

### Steps to reproduce

Make a page with some content that occupies more than 100vh
Add Document below that content
Change pages while viewing the document

### Expected behavior

Do not flicker

### Actual behavior

Flickers

### Additional information

```
 <Document
                    key={selectedDocument?.documentPath}
                    file={selectedDocument?.documentPath}
                    onLoadSuccess={onDocumentLoadSuccess}
                    onLoadError={onDocumentLoadFail}
                    loading={loadingDiv}
                    error={errorDiv}
                    renderMode="canvas"
                >
                    <Page
                        pageNumber={page}
                        renderAnnotationLayer={false}
                        renderTextLayer={false}
                        renderForms={false}
                        width="700"
                    />
                </Document>

```

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: 9.1.1
- **React version**: 18.2
- **Bundler name and version (if applicable)**:

**Comment by wojtekmaj** [comment]
This is likely because you don't keep the previous page rendered until the new one is rendered. See this general discussion on flicker on page switch: https://github.com/wojtekmaj/react-pdf/issues/418#issuecomment-660982983
