### ISSUE TITLE
Width property to accept percentage of parent container

### ISSUE THREAD

**Issue by kairoswealth** [wojtekmaj/react-pdf#1889]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

Today, react-pdf only uses pixels for the width property on the page Page element
It would be helpful to be able to use % for responsive design.

### Proposed solution

<Page width="90%">

**Comment by wojtekmaj** [comment]
That isn't possible as I need to pass absolute values to PDF.js. Try using [`useResizeObserver`](https://github.com/wojtekmaj/react-hooks/#useResizeObserver) instead?
