### ISSUE TITLE
"Internal error: Error: Element type is invalid: expected a string"

### ISSUE THREAD

**Issue by olliequ** [wojtekmaj/react-pdf#1891]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Using TypeScript in a NextJS project. Trying to do the barebones implementation of react-pdf but get this error: "_Internal error: Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports._" 

Tried v4.0.0, 3.4.5 and 3.4.4. All don't work.

Here's the file:

```
'use client'

import React, { useEffect } from 'react'
import { PDFDownloadLink, PDFDownloadLinkProps, Page, Text, View, Document, StyleSheet, PDFViewer } from '@react-pdf/renderer';

export default function PdfScreen() {
  const styles = StyleSheet.create({
    page: {
      flexDirection: 'row',
      backgroundColor: '#000000'
    },
    section: {
      margin: 10,
      padding: 10,
      flexGrow: 1
    }
  });

  const MyDoc = () => (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text>Section #1</Text>
        </View>
        <View style={styles.section}>
          <Text>Section #2</Text>
        </View>
      </Page>
    </Document>
  );

  return (
    <section className="flex h-full w-full bg-off-white">
      <div className="">
        <PDFViewer>
          {/* <MyDoc /> */}
        </PDFViewer>
      </div>
    </section>
  )
}
```

### Steps to reproduce

See above file, rendering this component results in an error.

### Expected behavior

No error.

### Actual behavior

Error produced.

### Additional information

![Screenshot 2024-10-01 at 2 22 11 PM](https://github.com/user-attachments/assets/3e298cbb-2e08-46ec-8506-3cc37863f85b)

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Bundler name and version (if applicable)**:

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
