### ISSUE TITLE
I am unable to include Charts  in PDF

### ISSUE THREAD

**Issue by malyalayoganath** [wojtekmaj/react-pdf#1896]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

I want to include a Chart in the react pdf. I am unable to do it.
I am using the libraries Chartjs , Tailwindcss, and React PDF. Can you please me?
I have converted the chart to images still not working, below is the sample code.
  const chart = chartRef.current;
    if (chart) {
      const imageURL = chart.toBase64Image();
      setImageUrl(imageURL);
    }

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
