### ISSUE TITLE
Promise.withResolvers is not a function in legacy worker on older Safari versions

### ISSUE THREAD

**Issue by mleister97** [wojtekmaj/react-pdf#1901]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Since a recent update, some of my users are encountering the following issue:

`Promise.withResolvers is not a function`

I am already using the legacy worker from `node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs`. However, it seems this worker still depends on the `Promise.withResolvers` function, which is not supported in Safari versions that are about one year old (Safari 17.3).

To ensure compatibility with older browsers, such as these versions of Safari, I suggest including an even more backward-compatible version of the legacy worker that avoids relying on Promise.withResolvers.

### Steps to reproduce

Use an iOS device with safari 17.3 or older

### Expected behavior

Rendering the PDF

### Actual behavior

Exception: `Promise.withResolvers is not a function`

### Environment

- **Browser (if applicable)**: Safari, 17.3 or lower
- **React-PDF version**: 9.1.1
- **React version**: 18.2.0
- **Bundler name and version (if applicable)**: vite 5.4.8

**Comment by TopBojan** [comment]
@mleister97 Is there any improvement on this? I am having the same issue.

**Comment by callumquirky** [comment]
@wojtekmaj @mleister97 Hi we are experiencing this same issue. Is there a fix/work around?

**Comment by wojtekmaj** [comment]
- Provide polyfill for Promise.withResolvers
- Use an older version of react-pdf, that used less modern pdfjs-dist

No other ways really

**Comment by cmocanu** [comment]
@wojtekmaj it would be very useful to let us know some known versions which support Safari, I imagine a lot of the users want to provide Safari support, as it's the default iOS browser

I tried using the legacy version, which from what I understand is supposed to have withResolvers polyfilled, but it still doesn't work.

Some instructions on how to polyfill withResolvers would also be useful, I tried 3-4 methods and none of them did the trick.

**Comment by 4lun** [comment]
For anyone else having the issue, the following worked for me

Add polyfill (`npm install core-js`) somewhere at the root:
```javascript
import "core-js/proposals/promise-with-resolvers";
```

And then I also needed to utilise the [legacy pdf.js build](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support), as the polyfill alone fixed the missing function type error, but PDFs didn't actually render

I use the unpkg CDN worker version (notice the `/legacy/` part in the URI):

```javascript
import { pdfjs } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/legacy/build/pdf.worker.min.mjs`;
```

**Comment by thibaultadet** [comment]
For your information, one of my user is having the same issue with Firefox 115.0

**Comment by richardr1126** [comment]
> Add polyfill (`npm install core-js`) somewhere at the root:
> 
> import "core-js/proposals/promise-with-resolvers";

This fixed my issue for Webkit Safari <18. Thank you!
