### ISSUE TITLE
Can't import from react-pdf

### ISSUE THREAD

**Issue by andyxmai** [wojtekmaj/react-pdf#191]
When I try to do `import { Document } from 'react-pdf/dist/entry.webpack'`, I get an Uncaught ReferenceError 
<img width="1280" alt="screenshot 2018-04-22 12 58 56" src="https://user-images.githubusercontent.com/987226/39099282-0aa7b964-462d-11e8-9d33-f2b5a944d07e.png">

I also get the following messages in my terminal. Any help would be appreciated.
```
./node_modules/pdfjs-dist/lib/display/api.js
109:4-11 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
3882:21-28 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
3883:12-19 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
3887:60-67 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/build/pdf.js
3897:10-17 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/lib/display/api.js
94:15-22 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/lib/display/api.js
95:6-13 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/lib/display/api.js
99:54-61 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**Comment by chulander** [comment]
What is your build process @andyxmai? My wild guess is you're in a node environment trying to use "import" instead of require. If that's the case, add the transpilation step

**Comment by wojtekmaj** [comment]
@andyxmai Please reply to @chulander 's question, and please share your configuration while you're at it! :) I'll try to help you.

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!

**Comment by kalfenxu** [comment]
same problem here, can you help? I use create react app create project and npm run start

**Comment by chulander** [comment]
Looking at this 4 month a later. It seems that dynamic-import plugin is required. The lib must be using some sort of conditional require

**Comment by wojtekmaj** [comment]
Indeed it does. It loads worker from specified location and from default one if not given. It was a normal require () though the last time I saw it.

**Comment by chulander** [comment]
@wojtekmaj, so my wild guess without peeking at the codebase was correct?
