### ISSUE TITLE
Annotation re-render problem

### ISSUE THREAD

**Issue by renrizzolo** [wojtekmaj/react-pdf#192]
Hi @wojtekmaj, 
it seems as though any update that isn't e.g resizing the page or changing the page is causing the annotations to be re-rendered (and multiplied).

I tested this by adding a button that set's an arbitrary state. Every time it's pressed, the annotations are duplicated.

**Comment by michaelfahmy** [comment]
Really great package, but this bug is annoying, pls fix soon

**Comment by wojtekmaj** [comment]
Hey guys.

I believe the issue is fixed in the newest 4.x pre-release. If you're on React 16.3 and up, have a look!

If you cannot use React 16.3 for some reason, I just cherry-picked the fix to 3.x branch, so I may release v3.0.6 with the fix in the coming days.

**Comment by renrizzolo** [comment]
@wojtekmaj nice, I'll check it out tomorrow!

**Comment by renrizzolo** [comment]
Looks good to me in the latest beta, thanks!
