### ISSUE TITLE
current sample webpack doesn't work with cmaps settings

### ISSUE THREAD

**Issue by banyan** [wojtekmaj/react-pdf#193]
Hi. I've just tested this directory: https://github.com/wojtekmaj/react-pdf/tree/master/sample/webpack

it works in this commit: https://github.com/wojtekmaj/react-pdf/commit/5dac7a6e3fbb09d9ecedfbfff4f9a512722ed78e
but latest doesn't work: https://github.com/wojtekmaj/react-pdf/commit/6cc17ca63d5742f23293e8379202a37787941f8f for cmap support.

**Comment by wojtekmaj** [comment]
Hey,
samples in this repository refer to version 4.0.0 which is not released yet. React-PDF is on constant development. To see examples for your version, use this.


![obraz](https://user-images.githubusercontent.com/5426427/39175825-944c9ce6-47ab-11e8-82e1-f28c32374b54.png)

**Comment by banyan** [comment]
@wojtekmaj 

ah thanks. so the latest is 3.0.4 at the moment!
