### ISSUE TITLE
Is it portable to Android & iOS?

### ISSUE THREAD

**Issue by rotencode** [wojtekmaj/react-pdf#194]
I mean performance & compatible.
Thanks.
by the way, I would try it on Android within few days.

**Comment by wojtekmaj** [comment]
Hi,
not sure what you mean. It's a package for React and all current web browsers should work fine on mobile devices, including Android and iOS. If you're asking about React Native though, then no, it's not a project for React Native.

**Comment by xcarpentier** [comment]
Hi,

I’m working on a solution to have a PDF offline viewer, Android capable, using Expo and this lib:

https://github.com/xcarpentier/rn-pdf-reader-js
