### ISSUE TITLE
numPages is always null

### ISSUE THREAD

**Issue by cjmafei** [wojtekmaj/react-pdf#195]
When i changed the pagination,i found the numPages is always null.And it was null when the pdf is loaded.why? 
`import * as style from './css/Pdf.less';
import logic from './PdfLogic';
import config from 'config/global';  // 全局
import { Link, Control } from 'react-keeper';
import { Component } from 'refast';
import { ActivityIndicator } from 'antd-mobile';
import {toast} from 'utils/ding';
import { Document, Page } from 'react-pdf';

class Pdf extends Component {
    constructor(props) {
        super(props, logic);
        this.state={
            animating:true,
            numPages: null,
            pageNumber: 1,
            pdfname: Control.state,
        }
    }
    
    componentWillMount(){
        
        document.setTitle('');
        
    }
    componentDidMount(){
        
    }
    onDocumentLoad = ({ numPages }) => {
        console.log('numPages', numPages);
        this.setState({ numPages });
    }
    goprev=()=>{
        let { pageNumber, numPages} = this.state;
        if (numPages == pageNumber || pageNumber==1){
            return;
        }else{
            this.setState({
                pageNumber: pageNumber - 1,
            });
            
        }
    }
    gonext=()=>{
        let { pageNumber, numPages } = this.state;
        if (numPages == pageNumber) {
            return;
        } else {
            this.setState({
                pageNumber: pageNumber + 1,
            });
        }
    }
    render() {
        const { pageNumber, numPages } = this.state;
        return (
            <div className="pdf">
                <div>
                    <Document
                        file={this.state.pdfname}
                        onLoadSuccess={this.onDocumentLoad}
                        error={<div className="empty">
                                <img src={require('./images/empty.png')} />
                                <p>出错了哦~</p>
                            </div>}
                        loading=""
                        noData={<div className="empty">
                                    <img src={require('./images/empty.png')} />
                                    <p>没有数据哦~</p>
                                </div>}
                        onLoadSuccess={() => { this.setState({ animating:false})}}
                    >
                        <Page pageNumber={pageNumber} />
                    </Document>
                    <div className="prev" onClick={this.goprev}>上一页</div>
                    <div className="next" onClick={this.gonext}>下一页</div>
                    <p>Page {pageNumber} of {numPages}</p>
                </div>
                
                <ActivityIndicator
                    toast
                    text="加载中..."
                    animating={this.state.animating}
                />
                <img className="goback" onClick={() => { Control.go(-1) }} src={require('./images/back.png')} />
            </div>
        );
    }
}

export default Pdf;
`

**Comment by cjmafei** [comment]
Sorry,it's my fault.I have solved it by myself.

**Comment by wojtekmaj** [comment]
Good! Would you share what's wrong in case someone else has the same problem?

**Comment by cjmafei** [comment]
I wrote the onLoadSuccess twice.So the first one was not taken effect.
