### ISSUE TITLE
Report error Warning: Error during font loading: CMap baseUrl must be specified, see "PDFJS.cMapUrl" (and also "PDFJS.cMapPacked

### ISSUE THREAD

**Issue by xiaosheng222** [wojtekmaj/react-pdf#197]
**OS:**
window

**React-pdf version:**
"react-pdf": "^3.0.2",

**Description:**

I was prompted to a mistake when loading PDF, seems to be caused by the font, I use Chinese fonts here, how should I set it?

my file can be opened at this site, but if I can not load the web using the component, the text will not be displayed at the time of printing

I also used CopyWebpackPlugin to copy cMaps, but I still did not solve this problem.

![_20180427192457](https://user-images.githubusercontent.com/19821241/39360418-b8b6062e-4a50-11e8-860a-a69edd036af6.png)

Warning: Error during font loading: CMap baseUrl must be specified, see "PDFJS.cMapUrl" (and also "PDFJS.cMapPacked

**Comment by juuuuuuuuuuuuuu** [comment]
how to solve this problem???

**Comment by juuuuuuuuuuuuuu** [comment]
@xiaosheng222  how to solve this problem??

**Comment by wojtekmaj** [comment]
@juuuuuuuuuuuuuu

https://github.com/wojtekmaj/react-pdf/blob/master/README.md#support-for-non-latin-characters

**Comment by lidianhao123** [comment]
@wojtekmaj I have used CopyWebpackPlugin to copy cMaps and add below code
```js
<Document
  options={{
    cMapUrl: 'cmaps/',
    cMapPacked: true,
  }}
/>
```
But, it still have problem.
```
Warning: Error during font loading: CMap baseUrl must be specified, see "PDFJS.cMapUrl" (and also "PDFJS.cMapPacked").
```
@xiaosheng222 how to solve the problem? please help sovled it.

**Comment by xiaosheng222** [comment]
If you haven't solved it, maybe you can try.

import { Document, Page, setOptions } from 'react-pdf/dist/entry.noworker';
import { personReport, companyReport } from '../../services/report/report';

try {
setOptions({
cMapUrl: 'static/cmaps/',
cMapPacked: true,
disableWorker: true
});
} catch (e) {
console.error(e);
}
import { Document, Page, setOptions } from 'react-pdf/dist/entry.noworker';
import { personReport, companyReport } from '../../services/report/report';

try {
setOptions({
cMapUrl: 'static/cmaps/',
cMapPacked: true,
disableWorker: true
});
} catch (e) {
console.error(e);
}

**Comment by wojtekmaj** [comment]
Aside from disabling the worker, this solution looks fine to me :)

**Comment by seunwoolee** [comment]
<Document
                  options={{
                    cMapUrl: `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/cmaps/`,
                    cMapPacked: true,
                  }}
                >

**Comment by thanhnt3105** [comment]
> ```
>             <Document
>               options={{
>                 cMapUrl: `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/cmaps/`,
>                 cMapPacked: true,
>               }}
>             >
> ```

you just save my life
