### ISSUE TITLE
Links are not clickable

### ISSUE THREAD

**Issue by kudlajz** [wojtekmaj/react-pdf#199]
Hey there!

I am currently implementing a PDF Reader using your library and so far everything works nicely, except for links, which are rendered as simple `div`s and thus not being clickable.

Is there an option that I need to turn on?

Component looks like this

```javascript
import React, { Component } from 'react';
import PropTypes from 'prop-types';

export default class PdfReader extends Component {
    static propTypes = {
        file: PropTypes.string.isRequired,
    };

    state = {
        isLoaded: false,
        numPages: 0,
    };

    componentDidMount = async () => {
        // Load the module asynchronously
        this.ReactPdf = await import(/* webpackChunkName: "react-pdf" */ 'react-pdf/dist/entry.webpack');

        this.setState({
            isLoaded: true,
        });
    }

    getPages = () => new Array(this.state.numPages).fill();

    handleLoadSuccess = ({ numPages }) => {
        this.setState({
            numPages,
        });
    };

    render() {
        const { ReactPdf } = this;
        const { file } = this.props;
        const { isLoaded } = this.state;

        if (!isLoaded) {
            return (
                <span className="">Loading..</span>
            );
        }

        return (
            <ReactPdf.Document
                file={file}
                className="pdf-reader"
                onLoadSuccess={this.handleLoadSuccess}
            >
                {this.getPages().map((_, index) => (
                    <ReactPdf.Page
                        key={`page_${index + 1}`}
                        pageNumber={index + 1}
                    />
                ))}
            </ReactPdf.Document>
        );
    }
}
```

React: 16.3.2
ReactPDF: 3.0.4
Webpack: 4.6.0

Issue happens with multiple PDFs, for example [this one](http://www.pdf995.com/samples/pdf.pdf).

Thanks!

**Comment by wojtekmaj** [comment]
Hey @kudlajz,
I have checked and in [test suite](http://projects.wojtekmaj.pl/react-pdf/test/) the file you attached works fine. Do you mean link in "Please visit us at www.pdf995.com to learn more" or anything else?

**Comment by richardjzhang** [comment]
@wojtekmaj I'm having this issue as well, using the sample pdf file from pdf995. I'm using test suite to

**Comment by wojtekmaj** [comment]
1. Do you see the link highlighted when hovering over with your mouse?
2. Do you have `a[href="http://www.pdf995.com/"]` rendered anywhere in the DOM when loading this PDF?
3. Does this happen on a specific browser? If yes, which one?

**Comment by richardjzhang** [comment]
@wojtekmaj 
1. It doesn't highlight when I over my mouse over it
2. Not sure what you mean by that (quite new to all of this). Could you explain a bit more what I need to do in that regard?
3. No it happens on all browsers

**Comment by wojtekmaj** [comment]
ad 2. That's a selector. What I meant is - if you were looking for `<a href="...">` in Elements tab in Developers tool, is it rendered anywhere or not?
You can check this by running in the console, for example:
```document.querySelectorAll('.react-pdf__Page a')``` or ```document.querySelectorAll('a[href="http://www.pdf995.com/"]')``` (if you're rendering the example PDF attached above).

What I'm trying to find out if you're having a styling issue where the links simply went somewhere on the screen, but are in fact properly rendered, or the links are not there at all.

**Comment by richardjzhang** [comment]
@wojtekmaj sorry for the delay in reply I just had a read over README again and it seems like I didn't import the Annotation css file. My bad!

**Comment by zendy199x** [comment]
Fixed: https://codesandbox.io/s/react-pdf-next-js-forked-6mmhg?file=/components/pdf-viewer.js
