### ISSUE TITLE
Rendering incomplete/faulty

### ISSUE THREAD

**Issue by ABrumm** [wojtekmaj/react-pdf#209]
## Before you start - checklist
 - [x] I followed instructions in documentation written for my React-PDF version
 - [x]  I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in Known issues

## Description
Rendered react-pdf document didn't looks like the original uploaded PDF.

## Preview original PDF
![tile](https://user-images.githubusercontent.com/26593410/39996071-a9fbceda-577e-11e8-9711-15e9bc729de7.PNG)

## Preview react-pdf document
![tiledocument](https://user-images.githubusercontent.com/26593410/39996084-af7001ec-577e-11e8-97c6-c07acb2e53a9.PNG)

## Javascript code
```javascript
<div key={"documentContainer" + page.toString()} className={"documentContainer"}>
				<Document key={'page-' + page}
				          file={{url: url, withCredentials: true}}
				          onLoadSuccess={() => this.handleDocumentComplete()}>
					<Page className="pdfPage" pageIndex={0} renderAnnotations={false} renderTextLayer={false}
					      renderMode={"svg"}/>
				</Document>
			</div>
```

## HTML rendered SVG
```
<svg:g transform="">
<svg:path d="M 514.44 370.8 L 530.52 370.8 L 530.52 386.88 L 514.44 386.88 Z" fill="rgb(143,206,255)" fill-rule="evenodd" fill-opacity="1"></svg:path>
</svg:g>
<svg:g transform>
**<svg:path d="M 514.44 370.8 L 530.52 370.8 L 530.52 386.88 L 514.44 386.88 Z" fill="none" stroke="rgb(126,126,126)" stroke-opacity="1" stroke-miterlimit="0" stroke-linecap="round" stroke-linejoin="" stroke-width="0.24px" stroke-dasharray="" stroke-dashoffset="0px"></svg:path>
<svg:path d="M 0.000014305 0 L 960.000014305 0 L 960.000014305 540 L 0.000014305 540 Z" fill="none"></svg:path>**
</svg:g>
<svg:g clip-path="url(#clippath104)"><svg:g transform="">
<svg:text transform="translate(516.91 375.05) scale(1, -1)" xml:space="preserve"><svg:tspan font-family="g_d7_f14" font-size="11.04px" y="0"></svg:tspan><svg:tspan x="0 5.63998" y="0" font-family="g_d7_f14" font-size="11.04px" fill="rgb(0,0,0)">10</svg:tspan></svg:text></svg:g>
</svg:g>
```

## Issue
The issue is that the right two tiles are not rendered the way it should be.
The bold text above this chapter is the missed element, which is filled="none" and not rotate like it should be. 

## Environment
- react 16.1.0
- react-pdf 3.0.5

## Attachement
The pdf: [Tile.pdf](https://github.com/wojtekmaj/react-pdf/files/2000577/Tile.pdf)

## Update
Similiar behavior on this pdf: 
[Tabellen_Darstellung.pdf](https://github.com/wojtekmaj/react-pdf/files/2003876/Tabellen_Darstellung.pdf)
The color is not rendered like it should be, hope you can help me out.

The main problem for the color issue is this generated svg-element:
```
<svg:g transform=""><svg:path d="M 35.511 94.215 L 920.031 94.215 L 920.031 483.375 L 35.511 483.375 Z" fill="#000000" fill-rule="" fill-opacity="1"></svg:path></svg:g>
```
This svg generates a dark overlay on the whole svg-element, i will take a look in your source if i can find the cause for this behaviour.

**Comment by ABrumm** [comment]
Checked the issue and get the problem maybe, the pdf i used was exported from ppt and in the ppt is a linear gradient with following values:
```javascript
linear-gradient(135deg, rgb(228, 245, 252) 0%, rgb(191, 232, 249) 50%, rgb(159, 216, 239) 51%, rgb(42, 176, 237) 100%);
```
But the problem is not solved, because i am missing the possibility to generate something like this in svg:

```
<svg viewbox="7.5 0 60 10">
  <defs>
    <linearGradient id="gradient">
      <stop offset="5%" stop-color="#FFC338" />
      <stop offset="95%" stop-color="#FFEA68" />
    </linearGradient>
  </defs>
  <path fill="url(#gradient)" d="M0 10 V5 Q2.5 2.5 5 5 t5 0 t5 0 t5 0 t5 0 t5 0 t5 0 t5 0 t5 0 t5 0 t5 0 t5 0 t5 0 t5 0 t5 0 V10" />
</svg>
```

**Comment by wojtekmaj** [comment]
Hello,
SVG rendering is still in development by Mozilla. I'm sorry, but I won't be able to directly help you with that.

React-PDF is just a bridge between React and Mozilla's [PDF.js](https://github.com/mozilla/pdf.js/). If you could kindly drop them a report with an example, I'm sure they would make a good use of it :)

**Comment by Xcellion** [comment]
Sorry to resurrect an old thread @wojtekmaj , but was gradients ever solved? I am using linear-gradient on one of my projects and it's not displaying at all using this library.

Thank you!

**Comment by wojtekmaj** [comment]
Refer to Mozilla :) Basically if it renders properly in Firefox, it should render properly in React-PDF.
