### ISSUE TITLE
Support get the width of the pdf when Pdf loaded ?

### ISSUE THREAD

**Issue by foisonocean** [wojtekmaj/react-pdf#21]
I'd like to use it like this:

```jsx
<Pdf
  onDocumentLoad={({ total, width }) => { /* do something */ }}
/>
```

**Comment by wojtekmaj** [comment]
Hi, thanks for your suggestion!
Unfortunately there's no such thing as PDF size, it's defined on per-page basis. Would you be satisfied if you got width and height in onPageLoad/onPageRender callbacks?
