### ISSUE TITLE
Warning: Error during font loading: CMap baseUrl must be specified, see "PDFJS.cMapUrl" (and also "PDFJS.cMapPacked")

### ISSUE THREAD

**Issue by ErricLu** [wojtekmaj/react-pdf#211]
**Before you start - checklist**
 - [v] I followed instructions in documentation written for my React-PDF version
 - [v] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**
Warning: Error during font loading: CMap baseUrl must be specified, see "PDFJS.cMapUrl" (and also "PDFJS.cMapPacked").

becasue our project use react v15.4.2, so I try to use react-pdf with v1.6.1,but we I meet the Warning,I find  the ways to solve this problem in high version react-pdf,but So how can I solve this problem in v1.6.1 react-pdf.

**Environment**
 - Browser [Chrome 66.0.3359.139]:
 - React-PDF version [1.6.1]:

**Comment by wojtekmaj** [comment]
You cannot. :( Support for cMap was introduced in [v2.3.0](https://github.com/wojtekmaj/react-pdf/releases/tag/v2.3.0).
