### ISSUE TITLE
The PDF won't display in a create-react-app

### ISSUE THREAD

**Issue by LivioGama** [wojtekmaj/react-pdf#216]
Hello,

I can't make it work in a fresh create-react-app project. Regardless of what I tried, the console log no error but the screen stays blank. Also, the div `react-pdf__Document` is always empty. It is the same problem than here : https://github.com/diegomura/react-pdf/issues/236
Do you have any idea why ?

![capture d ecran 2018-05-25 a 18 46 23](https://user-images.githubusercontent.com/6930498/40556179-f8418492-604b-11e8-9882-2742eb40116b.png)

**Comment by michaeldzjap** [comment]
It doesn't seem like you are rendering any `Page` components. So your document is loaded successfully, but its pages are not actually rendered. I'd suggest to read up [here](https://github.com/wojtekmaj/react-pdf#usage). It will probably solve your problem.

**Comment by LivioGama** [comment]
Thanks for your input. I managed to solved my problems thanks to it!
