### ISSUE TITLE
<Page> sometimes fails to re-render when passed a rotate prop

### ISSUE THREAD

**Issue by kilsen** [wojtekmaj/react-pdf#221]
**What are you trying to achieve? Please describe.**
The use case is a bit complex; I'll do my best to explain it.

I'm displaying a multi-page PDF and giving the user the ability to rotate each page that he views. I need to "remember" the rotation value of each page, because the user can view any page in the document at any time (via a set of pagination controls in my UI). So I maintain the rotation value for each page in an array in my component's state, and pass the rotate prop to the Page component. When a user clicks on a "Rotate" button in my UI, I change the rotation for the current page. (In my case, I'm rotating 90 degrees counter-clockwise; so I add 270 to the current rotation value, and then adjust the value modulo 360.) When I first open the document, I don't know the rotation value of each page (as defined in the PDF dictionary object). But I'm able to get the pageInfo of a page after it's loaded. So, on initial display of each page, I do NOT pass the rotate prop. Then, in the onLoadSuccess handler of the page load (only the FIRST load of each page), I record the initial rotate value for the page. For example, suppose page 1 is stored in the PDF rotated 180. If I'm displaying page 1, my render() method applies logic to display it like this the first time:
```
<Page pageNumber=1 onLoadSuccess={this.handlePageLoaded}/>
```
My handlePageLoaded(page) method sets the rotation of page 1 (from page.pageInfo.rotate) and then the render() method is re-invoked and this time it displays the page this way:
```
<Page pageNumber=1 rotate=180 />
```
(Effectively, this causes no change to the display, because the rotation value didn't actually change.) Then, when the user clicks my "Rotate" button, I update the rotation for page 1 by adding 270 (modulo 360), and this triggers my render() method to display the page like this:
```
<Page pageNumber=1 rotate=90/>
```
and the user sees the page rotate immediately. 

So far so good. With one exception: if the initial state of the page in the PDF is rotated 270 degrees. Then, my render() method produces the following:
```
<Page pageNumber=1 onLoadSuccess={this.handlePageLoaded}/>
```
followed by
```
<Page pageNumber=1 rotate=270/>
```
and finally, when the user clicks my "Rotate" button:
```
<Page pageNumber=1 rotate=0/>
```
but the page does not re-render on the display; the user does not see the page rotate! If the user then clicks my "Rotate" button a second time, the display updates as expected (it flips 180 degrees, to reflect the fact that the user clicked the button twice).

Note that this only happens if the initial rotation value for the page (as defined in the PDF) is 270. In that case, attempting to go from 270 to 0 fails to cause a re-render of the page on the display. The other 3 cases -- namely, an initial PDF-defined page rotation value of 0, 90, or 180 -- all work fine.
 
**Describe solutions you've tried**
I was able to work around the problem by rendering the <Page> component the first time (when I don't know the pre-defined rotation value for the page) with an invalid rotate prop value. Like this:
```
<Page pageNumber=1 rotate=-1 onLoadSuccess={this.handlePageLoaded}/>
```
I get a React warning in my browser console (only 0, 90, 180, and 270 are valid values for the rotate prop). But the page always rotates when I tell it to.

**Environment**
 - Browser [e.g. Chrome 57, Firefox 59]: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
 - React-PDF version [e.g 3.0.4]: 3.0.5

**Comment by wojtekmaj** [comment]
Hello,
sorry for late response, I completely missed it. Well this is an odd one for sure. I was not able to reproduce it with PDFs I own, do you have an example I could play with? I think Mozilla would want to have a look too, since there's no code I know of that could cause that on React-PDF side.

**Comment by kilsen** [comment]
It should happen with any PDF. Try this to reproduce it: Open a PDF, rotate one of the pages 270 (by setting the pageInfo setting for the page), and save the PDF. (I'm using the hummus library to modify the PDF.) Then, after you've saved the PDF with the page marked for rotation, re-open the PDF. It should show the page rotated the way you saved it. Change the prop to cause the page to rotate, and you should see the problem. Note that it only happens if the page was saved in the PDF with a rotation of 270. If it was saved with a rotation of 0, 90, or 180, everything works fine.

**Comment by kilsen** [comment]
I'm attaching two files. 

The file need-rotation.pdf consists of 4 pages that I constructed with MS-Word. I put a text box on each page indicating the required rotation to make the page appear "normal" (portrait mode, with text right-side-up).

The file rotated.pdf actually has the pages rotated as indicated.

So if you open the PDF and try rotating each page counterclockwise (add 270 to the existing rotation value and then adjust it modulo 360) you should see the issue.

[rotated.pdf](https://github.com/wojtekmaj/react-pdf/files/2460821/rotated.pdf)
[need-rotation.pdf](https://github.com/wojtekmaj/react-pdf/files/2460822/need-rotation.pdf)

**Comment by wojtekmaj** [comment]
Hmmm... So:

* I opened rotated.pdf,
* Opened Page 2 (270),
* It displayed the right side up
* I set rotate in its props using React DevTools from `null` to `270`
* The page didn't rotate as 270 was also a default value
* I set rotate in its props using React DevTools from `270` to `0` (clockwise rotation relative to page's original rotation)
* The page did rotate clockwise

I also went counterclockwise from `null` to `180`, from `null` to `0`. It all worked fine. Is something wrong in my reproduction steps?

**Comment by wojtekmaj** [comment]
Yes, it does. Setting `rotate` from `null` to `0` works just fine in the test suite. This is really odd 🤔

**Comment by kilsen** [comment]
OK, I believe I understand what I was doing wrong. I needed to catch the
onLoadSuccess event of the Page component and read the page.pageInfo.rotate
value, and store it in the state of my container component so that I could
send the proper rotation value when the user clicks the rotate button.

Your component is working as designed; sorry to trouble you!
