### ISSUE TITLE
Using CSP (Content Security Policy) prevents the PDF to render correctly

### ISSUE THREAD

**Issue by AdamOlevall** [wojtekmaj/react-pdf#223]
Hi! We have been using your package to display PDFs in our application which works fine! However, this week we discovered that we needed to implement CSP in order to fulfill the OWASP top 10. This prevents the application to use any form of inline styling. When added the CSP, the PDF stopped to render its content. We discovered that react-pdf was using some inline styling which probably is the reason for the outcome. 

Do you know if there is any way to make react-pdf work with blocked inline styling? 
We are using 3.0.4 and the CSP block the PDF to render in Firefox and IE11.

BR, Adam

**Comment by wojtekmaj** [comment]
Hello,
thanks for your report. I've been looking into this for a while. Looks like PDF.js itself would be CSP ready. However some functions of react-pdf (along with any PDF.js-based viewers, including Mozilla's) require inline styles to work. While some inline styles can be easily replaced (see: Page, PageSVG, PageCanvas), others cannot (TextLayer, TextLayerItem). I feel like a half-baked solution wouldn't be something worth the effort.
At the moment I cannot think of a good solution for you. :( Maybe the community would help?

In the meantime, maybe a fork with inline styles moved to a separate .css file and with TextLayer disabled would be a reasonable workaround?

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
