### ISSUE TITLE
PDF.JS Worker Threads

### ISSUE THREAD

**Issue by owlkaboom** [wojtekmaj/react-pdf#224]
Just looking at the Document.js code I didn't see an immediate way to stop pdf.js from spawning multiple worker threads. It looks like PDF.JS allows for you to declare an existing "worker" by passing {worker: worker} into the getDocument method (https://github.com/lambdabaa/pdf.js/blob/master/src/display/api.js#L219 for the pdf js code). Would this be something that could be supported or is there a better way to cut down on the worker threads?

Versions:
Browser: Firefox 60.0.1
React-PDF: 3.0.4

**Comment by wojtekmaj** [comment]
Hello @owlkaboom,

I think version 4.0.0 will be interesting for you :) In 4.0.0, you no longer use limited `setOptions`. [Instead, you pass options directly to getDocument method by `options` prop.](https://github.com/wojtekmaj/react-pdf/wiki/Upgrade-guide-from-version-3.x-to-4.x#setoptions-are-now-replaced-by-options-prop). It's not filtered in any way so it gets you even closer to the roots of PDF.js. So, you can pass your own `worker` in` options` now!

Frankly, I was not experimenting with this particular option, but I'd love to hear if you manage to do something interesting with it!

React-PDF 4.0.0-beta is considered stable by now. In fact, the only thing we're waiting for is Webpack 4 support, which will be possible as soon as Mozilla will release the new version of PDF.js, which is expected super soon. Check it out!

**Comment by owlkaboom** [comment]
Hey @wojtekmaj ,

It looks like after upgrading to 4.0.0 I am not having any issues with the worker threads.
