### ISSUE TITLE
PDF not getting displayed in react's Dialog

### ISSUE THREAD

**Issue by Sivachows** [wojtekmaj/react-pdf#225]
We need to display pdf in the "Dialog". We have used react-pdf(https://github.com/wojtekmaj/react-pdf). This code didn't throw any error and received "onLoadSuccess" callback, however, pdf not displayed in the "Dialog" and it is empty white background.

We are able to see pdf without "Dialogue". This problem occurring only when we try to display pdf in the "Dialogue".

Is it possible to display pdf in the react's Dialog?

render() {
    const { file, numPages } = this.state;

    return (
      <div className="Example">
        <header>
          <h1>react-pdf sample page</h1>
        </header>
          <div className="Example__container__document">
          {/* <Dialog modifier="material" isCancelable={true}> */}//If we want to display pdf inside Dialog, its not showing
          <Document
              file={file}
              onLoadSuccess={this.onDocumentLoadSuccess}
              options={options}
            >
              {
                Array.from(
                  new Array(numPages),
                  (el, index) => (
                    <Page
                      key={`page_${index + 1}`}
                      pageNumber={index + 1}
                    />
                  ),
                )
              }
            </Document>
          {/* </Dialog> */}
          </div>
        </div>
    );}

state = {
    file: './sample.pdf',
    numPages: null,
  }

  onFileChange = (event) => {
    this.setState({
      file: event.target.files[0],
    });
  }

  onDocumentLoadSuccess(numPages) {
  }

**Comment by wojtekmaj** [comment]
Hello there,
what is a Dialog here? It's certainly not a native React thing. Would you share more details?
Also, is onLoadSuccess callback properly called when <Document> is put inside the <Dialog>? Is it only the matter of not rendering?

**Comment by RudmanMario** [comment]
Hi. I'm have a similar problem. I'm fetching my pdf file from server using `Axios`. I can see that the response has `data` so I just path that to the `Document` component like this:

     <Document
        file={file}>
    </Document>

Simple as that, but I just see blank page and no error or warning messages in the console. What am I doing wrong?

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
