### ISSUE TITLE
On iOS device, after resuming the Cordova app onLoadSuccess is not firing

### ISSUE THREAD

**Issue by csKangGdcomm** [wojtekmaj/react-pdf#227]
**Before you start - checklist**
 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

the target version is 3.0.5

**Description**
I am using this library on my cordova app.
On testing web, It works fine however some situation on ios device, it is not working. 
while using the app, 
lock the app and then ( not home button )
resume the app and then
go to the pdf view page
pdf is not showing. ( showing Loading PDF... and nothing happen )
  `Warning: Setting up fake worker. ` log is printed.. 

I think onLoadSuccess is not calling on Document component

I am not sure it is library issues or not, and It doesn't happen on android device...

Can you give me some advice or check the library?

Thank you!

**Comment by wojtekmaj** [comment]
Hello,
if `onLoadSuccess` is not fired, then most certainly `onLoadError` will, and it will give you more details on what happened. If you have access to the console, it's also worth a look. I have no idea about Cordova :)

**Comment by wojtekmaj** [comment]
Hey @csKangGdcomm, if you still have this issue, let me know. I'll be happy to reopen.
