### ISSUE TITLE
Use in swagger-ui, with Blob

### ISSUE THREAD

**Issue by plutext** [wojtekmaj/react-pdf#228]
In swagger-ui, where an API returns a PDF when you hit the "try it out" button, I'd like to use react-pdf to render the PDF returned in the response Blob.

swagger-ui already uses react-pdf: "^3.0.5"

I tried to implement; see https://github.com/plutext/swagger-ui/commit/0429aa16fda1b11d4ea143c0b505862d57f4206d

But it doesn't quite work (with or without Page in Document).

(I've tried feeding it the Blob, and also window.URL.createObjectURL(content)

If I allow swagger-ui to instead display parsedContent, the PDF code looks OK (except for those 4 diamonds in line 2):

```
%PDF-1.4
%����
1 0 obj
<</Producer ()
/CreationDate (D:20180620055603+00'00')
/ModDate (D:20180620055603+00'00')>>
endobj
2 0 obj
<</Type /Catalog
/Metadata 3 0 R
/OutputIntents [<</Type /OutputIntent
/S /GTS_PDFA1
/RegistryName (http://www.color.org)
/OutputConditionIdentifier (sRGB IEC61966-2.1)
/DestOutputProfile 4 0 R>>]
/Pages 5 0 R>>
```

Any suggestions gratefully appreciated, thanks

**Comment by wojtekmaj** [comment]
> swagger-ui already uses react-pdf: "^3.0.5"

Really? :P I don't see it in package.json!

react-pdf supports Blob just fine. You should not have issues with that *client side*. However, you can't render a PDF server-side. You could try - using SVG rendering mode (mode in README), but you'd be the first to ever succeed. ;)

What else I can say...
* `<Page>` will be necessary if you actually want something to be rendered. `<Document>` just loads the document and waits for what you do with it.
* Loading PDF is asynchronous. Until you get a confirmation from `onRenderSuccess`, there will be indeed nothing meaningful rendered. Maybe a placeholder :)

**Comment by plutext** [comment]
Please see comments at https://github.com/swagger-api/swagger-ui/issues/4665

One of the comments says "You could convert the Blob to a Uint8Array yourself, but that would require an async FileReader operation, which you can't use in a React render method (**they must be synchronous**)."

Not sure how that squares with "Loading PDF is asynchronous"?

What's the easiest way to get detailed info out of react-pdf to diagnose the cause of a "Failed to load the page" error coming from:

``` <Document file={ content } > <Page pageNumber="1" /> </Document>```

thanks

**Comment by wojtekmaj** [comment]
Yeah, there's no way to run React-PDF synchronously. It relies super heavily on ansynchronous Mozilla's code.

> What's the easiest way to get detailed info out of react-pdf to diagnose the cause of a "Failed to load the page"

`on...Error` callbacks, as specified in README.

> Its running client side

:)
