### ISSUE TITLE
Can't test or use v4.0.0-beta

### ISSUE THREAD

**Issue by xcarpentier** [wojtekmaj/react-pdf#231]
**What are you trying to achieve? Please describe.**
I try to test v4.0.0-beta.

Can you please provide a way to test?

**Environment**
 - React-PDF v4.0.0-beta

**Comment by wojtekmaj** [comment]
Hey,
I need a little more details from you.

Did you use 3.x before successfully?
If so, what were your test cases?
What's failing now?
What are the error messages?

**Comment by xcarpentier** [comment]
Hi @wojtekmaj, 

thank you for your response.

I'm using 3.x successfully but I need to test 4.x to see if that fix some issues I have with this package: https://github.com/xcarpentier/rn-pdf-reader-js 

I have an issue with embedded images.

**Comment by wojtekmaj** [comment]
So, do you have tests running on 3.x successfully, but they broke on 4.x? If so, what are the tests? Paste the code here.

**Comment by xcarpentier** [comment]
Yes v3 is ok, I don’t have any error just the fact I can’t test v4. I guess I should build it from github or generate bundle differently than a published to npm version?

**Comment by wojtekmaj** [comment]
No, npm version should be fine.

I'm sorry, but I can't understand what is your problem. I still don't know what's stopping you from testing v4. Unless you provide specific description of your problem and preferably a sample of the test code that's failing, I won't be able to help you.

**Comment by wojtekmaj** [comment]
The only thing that comes to my mind is that React-PDF 4.x uses new Context API which is not yet supported by Enzyme, so if you do use Enzyme in your tests, they will crash. That shouldn't stop you from using it though, only Enzyme testing until they finally release an update.

**Comment by xcarpentier** [comment]
Sorry I missed the fact it's published on npm.
