### ISSUE TITLE
Getting the values from an interactive form

### ISSUE THREAD

**Issue by arnoldc** [wojtekmaj/react-pdf#232]
Hi
is there like a way to get the content from the Form Input when i set the renderInteractiveForms into true,
ive tried to check the readme docs and could not determine if there is a possible way

**Comment by wojtekmaj** [comment]
Hello,
renderInteractiveForms uses rendering that is outside React's and outside React-PDF's control (Mozilla's PDF.js). For now, the only way to get the content is by using DOM operations like:

```js
[...document.querySelectorAll('.textWidgetAnnotation input')].map(el => el.value);
```

Unfortunately, at the time, form inputs are not named in any way, so I can't get this information - only values.

**Comment by arnoldc** [comment]
ok thanks

**Comment by ssteuteville** [comment]
Does pdf.js have support for this? If so I would love to see that functionality exposed in react-pdf!

**Comment by wojtekmaj** [comment]
Not that I know of. If there is something we could "reactify", let me know, I'll be more than happy to tackle this. For now we're "stuck" with "the platform".

**Comment by kaitlynbrown** [comment]
Is there a way to save the modified pdf once a user has entered values into the form?

**Comment by NAccuardi** [comment]
@kaitlynbrown Did you ever find out if there was a way to save the user entered values into the PDF?

**Comment by kaitlynbrown** [comment]
Not yet, unfortunately, sorry
