### ISSUE TITLE
latest version does not work with blob url

### ISSUE THREAD

**Issue by moxun33** [wojtekmaj/react-pdf#233]
Hello!
I use ``file={blob:http://localhost:3000/5c01ef01-6a0d-4986-afb4-ea3ee24cd77b}``  to pass a file data, it   shows loading all the time but throws no errors! What is wrong with my blob url?

**Comment by wojtekmaj** [comment]
That doesn't look like a correct Blob URL to me. Correct would be something like: blob:d3958f5c-0777-0845-9dcf-2cb28783acaf

**Comment by wojtekmaj** [comment]
Do you get anything in the console?

**Comment by moxun33** [comment]
I build it myself with latest code. I found that  import Doucment like ``import { Document, Page, Outline } from "react-pdf";``, it works well. However, does not work with ``import { Document, Page, Outline } from "react-pdf/dist/entry.webpack";``,  nothing in the console as well.

**Comment by wojtekmaj** [comment]
That is odd, unless you're trying to open compiled project from file:/// protocol. Make sure to run a server for React-PDF to work.

entry.webpack loads React-PDF with a worker using Webpack's worker-loader, and renders PDF using that worker for performance reasons. There are no other changes, so if anything, *all* ways of loading PDF would fail. If that's the case, I'd look to network tab in Developer Tools to see if *.worker.js file loads correctly.

Please also mind that Webpack 4 will be supported soon, but we're not quite there yet.

If neither helped, I'd greatly appreciate if you could share your repo or minimum reproduction so I could have a look at the configuration.

**Comment by moxun33** [comment]
Unfortunately, I use Webpack4 in my project. 😂😂😂

**Comment by wojtekmaj** [comment]
In that case, you should wait for official 4.x release. Or try the beta :) It may work, although final Webpack compatibility changes may come in the next beta release.

**Comment by moxun33** [comment]
sure, thank you.

**Comment by aprilmintacpineda** [comment]
`blob:http://localhost:3000/db53d5c2-ff04-4794-99c6-46c139ff327c` is actually a valid blob url, the browser can understand that and that's the returned value of `window.url.createObjectUrl(await response.blob())`. You can also fetch that like so:

```js
fetch('blob:http://localhost:3000/db53d5c2-ff04-4794-99c6-46c139ff327c')
  .then(response => response.blob())
  .then(response => console.log(response))
```

I also need to load a PDF from that URL but it won't load saying `Failed to load PDF file.`

**Comment by jeyadharanigithub** [comment]
OnloadSuccess is loading continuously when I am loading this type of blob url https://ezitechdevkyc.blob.core.windows.net/ezitechdevkyc/2d478fde-12a5-4aeb-814f-c7822d3eda78.pdf?sv=2019-12-12&ss=bfqt&srt=sco&sp=rwdlacupx&se=2020-09-10T18:57:30Z&st=2020-09-03T10:57:30Z&spr=https&sig=HuzIa262NB%2BQNTVN55cs5rvWPPvVm7seLsw70qLW5Y0%3D
