### ISSUE TITLE
Incorrect generate pdf

### ISSUE THREAD

**Issue by mrNemoZero** [wojtekmaj/react-pdf#234]
I did all as in sample, but some pdf-files look like in screenshot.
File is loading from url.
Can you help me? Where i am must seek solve?

MacOS 10.13.5
Chrome 66
react-pdf 3.05

![image](https://user-images.githubusercontent.com/16408935/41950817-2f2a88f4-79f2-11e8-80a0-7e8abe2148f9.png)

**Comment by wojtekmaj** [comment]
Do they look correct if you open them in Firefox! If not, you should report it to Mozilla (mozilla/pdf.js) with a sample of a failing PDF. If yes, which is unlikely, we'll see if it's something on my side.

**Comment by mrNemoZero** [comment]
Problem solved. Big project and somebody changed prototype CanvasRenderingContext2D..... Thanks for help and library)

**Comment by wojtekmaj** [comment]
Would you please elaborate on what was your fix?
