### ISSUE TITLE
Can I highlight a particular word or phrase from a text in the rendered PDF?

### ISSUE THREAD

**Issue by Medsender-Jackson** [wojtekmaj/react-pdf#235]
**Before you start - checklist**
 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
Great library. I would like to be able to search for a particular text or phrase on the pdf and have it highlighted.

**Describe solutions you've tried**
I have used the `customTextRenderer` prop to implement a search and highlight funciton but I noticed  that what gets highlighted is the entire line instead of the actual word or phrase:
For example when I want to search and highlight any occurences of the word `patient`, this is what I get:
<img width="376" alt="screen shot 2018-06-28 at 13 16 43" src="https://user-images.githubusercontent.com/37417029/42028687-a5027b0c-7ad5-11e8-9ce3-b045d1cf3161.png">

this is the code I have used for that:
```js
customTextRenderer={({ str, itemIndex }) => {
                        console.log('str', str, 'index', itemIndex);
                        if (str.toLowerCase().includes('patient')) {
                          return (<mark>{str}</mark>)
                        }
                      }}
```

The result i am trying to get is something like this:
<img width="395" alt="screen shot 2018-06-28 at 13 19 06" src="https://user-images.githubusercontent.com/37417029/42028756-e537bea8-7ad5-11e8-9419-16ed5be6df7f.png">

I will appreciate any help you can give me.

**Environment**
 - Browser Chrome 67:
 - React-PDF version  3.0.5:

**Comment by wojtekmaj** [comment]
Hey there,
check out what I use for highlighting word "ipsum" in my test suite:

https://github.com/wojtekmaj/react-pdf/blob/master/test/Test.jsx#L126-L133

**Comment by naveenApplikation** [comment]
this solution not works right now
