### ISSUE TITLE
When is onItemClick called?

### ISSUE THREAD

**Issue by ras9841** [wojtekmaj/react-pdf#237]
**Problem**
I'm trying to understand when the onItemClick prop to the Document component gets fired.

**Attempted Solution**
I've tried adding a simple alert function `onItemClick = () => alert("CLICK")` to the document I'm working on (found here: [https://www.irs.gov/pub/irs-pdf/f1040.pdf](url)) and clicking around. The readme has the following information:

> Function called when an item has been clicked. 

Could you please clarify what an item is?

**Environment**
 - Browser Firefox 63.0a1
 - React-PDF version: 4.0.0-beta

**Comment by wojtekmaj** [comment]
"Item" is an Outline item. So if you put `<Outline />` inside your `<Document />` and click around it, you will get `onItemClick` callback called.

This has nothing to do with item being a part of a PDF file. You can't really do that. If anything, you can click annotations (links, form elements), but you can listen for it using normal onClick on your wrapper - propagation is not stopped.

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
