### ISSUE TITLE
Download Progress

### ISSUE THREAD

**Issue by SouhaibBenFarhat** [wojtekmaj/react-pdf#238]
before to start I would like to thank you for this awesome component.
Otherwise I'm wondering if there is anyway to track the file downloading progress. something like 

`<Document
 file={props.cv || props.resume}
onProgress={(progress)=>this.setState({progress})}>
          <Page pageNumber={1}/>
 </Document>`

**Comment by wojtekmaj** [comment]
Hey there!
Thanks for the kind words. Keeps me going! :)
At the moment it's not possible, but looking at the PDF.js API it would be quite easy to implement, actually. I'll keep it in backlog to implement!

**Comment by wojtekmaj** [comment]
Hi @SouhaibBenFarhat,
I've implemented this idea as `onLoadProgress` prop in `Document` component. It will be live with the next 4.0 (beta?) release. :)
