### ISSUE TITLE
does react-pdf 3.0.5 using canvas ?

### ISSUE THREAD

**Issue by Madasamy26** [wojtekmaj/react-pdf#239]
I am using react-pdf 3.0.5 and its showing pdf in **canvas** !!

Can I render with **SVG** resizable options?

**Comment by wojtekmaj** [comment]
Hi,
thanks for noticing this. You can use `renderMode` prop in `Page` component. Set it to `"svg"` and you will have page rendered in SVG.

Documentation for both 3.x and 4.x branches was updated.
