### ISSUE TITLE
Does the library work for other PDF standards like PDF/A, PDF/X?

### ISSUE THREAD

**Issue by jacksono** [wojtekmaj/react-pdf#240]
**Before you start - checklist**
 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I am trying to use the library to render and navigate PDF/A, PDF/X and PDF/E files 

**Describe solutions you've tried**
I am using the code below to simply increment the page number when a button is clicked which should then render the new page. it works well for normal PDF files but when I try other PDF standards like PDF/A the navigation after the first page is laggy.
```JS
  handleNextPage = () => {
    if (this.state.pageNum < this.state.numPages - 1) {
      this.setState(prevState => ({
        pageNum: prevState.pageNum + 1,
        nextPage: true,
      }));
    } else {
      toastr.warning('End of record reached');
    }
  }
```

**Environment**
 - Browser: Chrome 67
 - React-PDF version: 3.0.5

**Comment by jacksono** [comment]
Using the pdf.js worker has helped increase speed of my page transition. Theres still a bit of lag on actual rendering of new pages for OCR'ed pdf files (PDF/A formats). The viewer on firefox also had a similar performance. I will take it up with the guys at pdf.js as you suggested. Thanks for the help.

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
