### ISSUE TITLE
Support for password protected PDFs

### ISSUE THREAD

**Issue by aniketparab4** [wojtekmaj/react-pdf#241]
How handle the password protected pdf??....Till now is just throwing the error as "No password given".

"code:1
message:"No password given"
name:"PasswordException"

**Comment by wojtekmaj** [comment]
Hello,
this feature is coming in 4.0.0.

**Comment by wojtekmaj** [comment]
4.0.0-beta.3 with this feature was just released so I'm closing this issue. I'm listening for feedback if you have any :)

**Comment by slashvortal** [comment]
The callback is no longer triggered on onPassword:

```
PasswordException {name: "PasswordException", message: "No password given", code: 1}
code: 1
message: "No password given"
name: "PasswordException"
```

Any idea what has been changed recently?

**Comment by wojtekmaj** [comment]
@slashvortal Fixed in v4.0.5

**Comment by zeusservando** [comment]
Hi @wojtekmaj  good day, i have a pdf file with password but when the prompt box show i can't close it.

**Comment by leanesanity** [comment]
Just want to ask,
Is any way we can set password for the pdf to be downloaded using your library?
Thanks ahead for the answer

**Comment by wojtekmaj** [comment]
I don't quite understand what you mean. You mean downloading a file from a server that requires Basic Auth?

**Comment by leanesanity** [comment]
No sorry, I just want to download pdf file with password from browser. Is
it possible to add password to the actual PDF file using this library?

**Comment by wojtekmaj** [comment]
Add password to the PDF? No, this package only reads the PDF files.
