### ISSUE TITLE
Outline component is not loaded

### ISSUE THREAD

**Issue by zjhiphop** [wojtekmaj/react-pdf#242]
**Description**
Outline component is not loaded at all

**Steps to reproduce**
1. Just add the most simple example:
```

export default class QueryApi extends Component {
    state = {
        numPages: null,
        pageNumber: 1,
        pdf: null
    }

    onDocumentLoadSuccess = ({ numPages, pdf }) => {
        this.setState({ numPages, pdf });
    }

    render() {
        const { pageNumber, numPages, pdf } = this.state;

        return <div className={styles.page}>
            <Document
                file={apiDoc}
                onLoadSuccess={this.onDocumentLoadSuccess}
                loading="正在加载..."
                noData="API 文档"
            >

                {pdf && (<Outline pdf={pdf} />)}

            </Document>
        </div>
    }
}
```

**Expected behavior**
Outline should be loaded,

**Additional information**
I got the same issue, I installed the latest version("react-pdf": "^3.0.5",). After tried many times, the outline part is always not shown.

Any solutions? 

**Environment**
 - Chrome 67.0.3396.99 (Official Build) (64-bit)
 - React-PDF version : ^3.0.5

**Comment by wojtekmaj** [comment]
You're not supposed to provide pdf on your own to `<Outline>` component. You may, but the whole idea of `<Document>` component is that it handles all of that for you. 

If you place `<Page>` inside, does it work? If yes, try the above. If not, try and play with `/test` directory - which gives you tons of options, but most importantly loads the documents correctly.

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
