### ISSUE TITLE
No Demo?

### ISSUE THREAD

**Issue by karlkras** [wojtekmaj/react-pdf#244]
**Before you start - checklist**
 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**
Short description of the bug you encountered.
Your advertisement is promising a demo. Links to demo come up with information page that link back to the git repo, and the demo link from there goes back to the information page... no demo.

**Steps to reproduce**
1) go to https://www.npmjs.com/package/react-pdf
2) from here there's a link that stating "Online Demo" that goes here: 
http://projects.wojtekmaj.pl/react-pdf/
3) From here you have a nice description page, and two links to 1) Install 2) "See on GitHub"
4) Selecting "See on Github" this github readme, it states:
`Online demo is also available!`
6) Selecting this goes back to your nice description page. No Demo for you!

**Expected behavior**
A demo.

**Additional information**
 - NA

**Environment**
 - NA

**Comment by wojtekmaj** [comment]
The page being displayed on the demo page is actually a PDF rendered client side.

If you want to see some more advanced features, go to http://projects.wojtekmaj.pl/react-pdf/test
