### ISSUE TITLE
http://xxx/pdf.worker.js not found ERROR 404

### ISSUE THREAD

**Issue by Vanals** [wojtekmaj/react-pdf#245]
**Description**
Hi, I did set up react-pdf and it works perfectly, I did followed the instructions. But in development once I open a page that render a pdf file  i get an error 404. Saying that a request for a path "/pdf.worker.js" has been done ( not by me volontary) and an error 404 is returned.

![pdf.worker.js error](https://image.ibb.co/je8KuJ/Screen_Shot_2018_07_20_at_09_55_26.png)

Anyone knows why this error and how to fix it? thanks
I built the app using create-react-app, react router and express.js

**Steps to reproduce**
You can see it live here: http://www.lostudenteim.it/materie-infermieristica/file-fisiologia-umana

**Environment**
 - Browser: Chrome version [67.0.3396.99]
 - React-PDF version [e.g 3.0.5]:
"react": "^16.3.2",
"express": "^4.16.3",

**Comment by wojtekmaj** [comment]
Seeing that `pdf.worker.js` request is done suggests me you're using default entry file (import ... from 'react-pdf'). That means you need to take care of copying `pdf.worker.js` by yourself. You have more options available - automatic config for Webpack and Parcel.

**Comment by wojtekmaj** [comment]
ad 3. https://github.com/wojtekmaj/react-pdf#enable-pdfjs-worker
ad 1 & 2. https://github.com/wojtekmaj/react-pdf#browserify-and-others

**Comment by Vanals** [comment]
thanks, sorted :)
