### ISSUE TITLE
PDF wrongly rendered

### ISSUE THREAD

**Issue by tigran59** [wojtekmaj/react-pdf#246]
when rendering pdf losses quality, tried to change width or scale but nothing works
![capture](https://user-images.githubusercontent.com/37477945/43045512-ea19cc88-8dca-11e8-94ed-4e5c47c4c83f.PNG)

**Comment by wojtekmaj** [comment]
Please use the template for bugs and attach the file you're having the issues with.

**Comment by Vanals** [comment]
I am having the same issue. With some PDF files increasing the size by percentage it gets blurry.

**Comment by Vanals** [comment]
UPDATE: I noticed that If a PDF file is rendered in the LG screen I got at work the file gets blurry and not nice to read. If in the same moment I move the safari windows with the page open to my macbook screen and I switch page.. the PDF file get nice to read, not blurry anymore. I understand doesn't make any sense.. but this is what happen. The LG screen doesn't have such a bad resolution to render it blurry.
