### ISSUE TITLE
npm run start raise  error 

### ISSUE THREAD

**Issue by kalfenxu** [wojtekmaj/react-pdf#249]
I import react-pdf and use npm run start to preview the app, but in the chrome console. error raise: Uncaught ReferenceError: Invalid left-hand side in assignment

also in the npm console, some error like 

/node_modules/pdfjs-dist/lib/display/api.js
112:4-11 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/lib/display/api.js
97:15-22 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

./node_modules/pdfjs-dist/lib/display/api.js
98:6-13 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by wojtekmaj** [comment]
Please use [Bug report issue template](https://github.com/wojtekmaj/react-pdf/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) or provide all the details which are specified in it.

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
