### ISSUE TITLE
Is it possible add customTextRenderer to svg Pages?

### ISSUE THREAD

**Issue by gmaize** [wojtekmaj/react-pdf#253]
In canvas mode, I can use customTextRenderer to attach an onClick event to text layer elements when they're rendered. 
I'd like to do a similar thing when in svg mode: add on click events to svg text elements, to enable text highlighting.
Is this currently possible and/or what would it take to make it possible?

**Comment by wojtekmaj** [comment]
customTextRenderer actually is used by a layer built _on top_ of canvas. SVG as such doesn't need this layer, because it's build of text itself.
I have very limited control over how SVGs are rendered. The only thing that comes to my mind is creating a script which modifies SVG manually.

**Comment by gmaize** [comment]
Gotcha. Figured that might be the case. Thanks for the quick reply!
