### ISSUE TITLE
Wrong URL for PDF worker

### ISSUE THREAD

**Issue by SachaG** [wojtekmaj/react-pdf#254]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

When I try to use this library, it tries to load the worker file relative to the current path ( so `http://localhost:3000/booking/pdf.worker.js` instead of `http://localhost:3000/pdf.worker.js`). 

Is there a way to specify that path or at least make it absolute? I'm running Meteor btw, so I can't use the Parcel or Webpack configs.

**Comment by wojtekmaj** [comment]
You absolutely can! I can see you're starting with React-PDF so I suggest you to use 4.0.0 beta. Configuring it should be a breeze. You can pass configuration, including workerPath (I'm on mobile so it's from memory), as an object in `options` prop.

Have a look at the docs and let me know if anything about it is unclear. This package got too popular to have anything bad in documentation :)

**Comment by wojtekmaj** [comment]
Similar issues: #52, #164, #245

**Comment by wojtekmaj** [comment]
It's `workerSrc` @SachaG. Updated original comment.

**Comment by wojtekmaj** [comment]
Did you set up your build so that you *actually* have `pdf.worker.js`?

If yes, check the Network tab in developer tools to ensure you're loading `pdf.worker.js` from correct location.

If no, check README for instructions for your bundler of choice.

**Comment by SachaG** [comment]
Yes, the issue is the URL, not the file. The location in the Network tab is wrong, it's trying to load from `http://localhost:3000/booking/pdf.worker.js` (the current URL being `http://localhost:3000/booking/foo`) instead of `http://localhost:3000/pdf.worker.js`.

So it seems like the option is not doing anything.

**Comment by SachaG** [comment]
(For now I copied `pdf.worker.js` to the `http://localhost:3000/booking/` path to make it work, but this gave me a `Failed to load PDF file.` error. I'm not sure if it's related or not…)

**Comment by wojtekmaj** [comment]
So whatever value you put in workerSrc it does not change anything? Are you using 4.0 or 3.0 at the moment?

**Comment by wojtekmaj** [comment]
Sorry, I misinformed you. Please check updated instructions: https://github.com/wojtekmaj/react-pdf#browserify-and-others

**Comment by SachaG** [comment]
That seemed to work! Thanks!

**Comment by vishwanathsnayak** [comment]
Hi All,
I'm trying to implement react-pdf preview. i'm getting error "Failed to load PDF file."
could you please help here.
Here is the code

import { Document, Page, pdfjs } from 'react-pdf';
import 'react-pdf/dist/Page/AnnotationLayer.css';
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

this.state = {
   numPages: null,
   pageNumber: 1,
}
onDocumentLoadSuccess = ({ numPages }) => {
        console.log('numPages : ', numPages);
        this.setState({ numPages });
    }

    onDocumentLoadError = ({ error }) => {
        console.log('Error : ', error);
    }

render {
 const { pageNumber, numPages } = this.state;
const path = '/Checklist.pdf';
return (
           <div>
                <Document 
                  file={ path }
                  onLoadSuccess={ this.onDocumentLoadSuccess }
                  onLoadError={ this.onDocumentLoadError } 
                >
                  <Page pageNumber={ pageNumber } width={ 600 } />
                </Document>
                <p>Page {pageNumber} of {numPages}</p>
            </div>
)
}

I can see the pdf.worker file getting loaded under network tab from cloud link (cdnjs.cloudflare.com).
I see error "Failed to load PDF file." could you please help here guys.

**Comment by Mahagney** [comment]
> That seemed to work! Thanks!

Can you show me how did you solve the problem?
