### ISSUE TITLE
Tips me Invalid PDF structure InvalidPDFException {name: "InvalidPDFException", message: "Invalid PDF structure"}

### ISSUE THREAD

**Issue by xulayen** [wojtekmaj/react-pdf#256]
``` js

"react": "^16.4.1",
"react-pdf": "^3.0.5",

 render() {
        const { pageNumber, numPages } = this.state;
        return (
            <div>
                <Document
                    file="./CCN-虚拟商品充值服务文档1.0.0.0.pdf"
                    onLoadSuccess={this.onDocumentLoad}  >
                    <Page pageNumber={pageNumber} />
                </Document>
                <p>Page {pageNumber} of {numPages}</p>
            </div>
        )
    }

```

**Comment by xulayen** [comment]
could you help me

**Comment by wojtekmaj** [comment]
Does this PDF open in Firefox if you try it?

If yes, I think that the URL to the file is not valid. `./CCN-虚拟商品充值服务文档1.0.0.0.pdf` is not a valid URL. `/CCN-虚拟商品充值服务文档1.0.0.0.pdf` is. or `static/CCN-虚拟商品充值服务文档1.0.0.0.pdf` or something similar.

You can also pass it directly by writing `file={require('./CCN-虚拟商品充值服务文档1.0.0.0.pdf')}`, which I think in this case was what you were trying to achieve.
