### ISSUE TITLE
Setting page height does not have any effect

### ISSUE THREAD

**Issue by leahaense** [wojtekmaj/react-pdf#257]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I want to make the pdf viewer fit into the available space by setting the height property on the `Page` component

**Describe solutions you've tried**

I noticed that setting the `height` property of the `Page` component does not have any effect. Using `scale` works, but it's not very practical because I would have to first know the actual size of the PDF, and thus load it, before being able to calculate the scale.

**Environment**

 - Browser: Chrome 68.0.3440.106
 - React-PDF version: 3.0.5
 - React version: 16.3.14
 - Webpack version: 4.16.3

**Comment by wojtekmaj** [comment]
Hello,
as silly as it sounds, height was actually added in 4.0.0-beta.2 as a result of #236.
Seeing that you use React 16.3, you may give it a go :) Beta should be pretty stable now, it was a beta for a couple of months.

**Comment by macrozone** [comment]
can confirm that setting height does not work
