### ISSUE TITLE
After loading pdf ,nothing show

### ISSUE THREAD

**Issue by johnzhu12** [wojtekmaj/react-pdf#258]
I've  added it as below
1. import { Document } from 'react-pdf/dist/entry.webpack';

2. 
```jsx
 <div className="pdfContainer">
          <Document file="http://127.0.0.1:8080/demo.pdf" />
  </div>
```

the url 'http://127.0.0.1:8080/demo.pdf' is the folder where I run 'http-server' command
and first it will throw CORS error,and I fixed it by opened the chrome CORS extension

(I can check the pdf in browser)
 
![b9ef459c-6e80-4f00-bd74-c78ec5e7c053](https://user-images.githubusercontent.com/11485619/44577088-c119fd00-a7c2-11e8-8638-88aa900df738.png)

then the page show something below and nothing happen any more

![5d029721d0fd9a76005a99dc5a13ea26](https://user-images.githubusercontent.com/11485619/44576011-186a9e00-a7c0-11e8-8542-9a6a46e141de.jpg)

![1535101259717](https://user-images.githubusercontent.com/11485619/44576020-1f91ac00-a7c0-11e8-89de-136d42461c9b.jpg)

**Comment by wojtekmaj** [comment]
Please check README, even [tl;dr](https://github.com/wojtekmaj/react-pdf#tldr) section would be enough.

**Comment by johnzhu12** [comment]
I've done all the steps

**Comment by johnzhu12** [comment]
```jsx
import React from 'react';
import { Document } from 'react-pdf';
// import NoticeStore from '@models/notice'
import PdfBodyTag from './MyPdfViewer.css'


interface MyPdfViewerProps {
  myPdf: any
}

class MypdfView extends React.Component<MyPdfViewerProps, {}>{
  constructor(props) {
    super(props)

  }


  render() {
    return (
      <PdfBodyTag>
        <div className="pdfContainer">
          <Document file="http://127.0.0.1:8080/demo.pdf" />
        </div>

      </PdfBodyTag >
    )
  }
}


export default MypdfView;
```

 that's all my code as above. the 'file' property can be a url,right? I've added a url of pdf which  can be access in browser .
   sorry to bother you,any tips will be great!

**Comment by johnzhu12** [comment]
is it because that the http-server can't be the server to provide pdf url?

/Users/zhujohn/Desktop/F5CCE3FD-5A2E-423A-882A-15B8F4687D05.png

**Comment by johnzhu12** [comment]
all right,pages is a must. I got it
