### ISSUE TITLE
Slow text render on Android <= 6

### ISSUE THREAD

**Issue by robsco-git** [wojtekmaj/react-pdf#260]
The PDF viewer renders text word by word (slowly) with some PDFs on Android <= 6 and react-pdf 3.0.5.

Example PDF: http://www.pdf995.com/samples/pdf.pdf

Test env:
Browserstack, Galaxy S7 with Android 6.0.1. I've also tested and experienced the same behaviour on a Moto G4 Plus with Android 6 (not sure exact version right now) and a Samsung S4 i9500 with Android 5.1.1

Maybe this a PDF.js issue?

P.S. Thanks a lot for the project!

**Comment by wojtekmaj** [comment]
Most likely PDF.js "issue". In quotation marks, because in general rendering PDF is a very heavy task to do so slowness is expected if you open large PDFs, or multiple pages at once, or use a low end device.

See also: #94
