### ISSUE TITLE
How do I set pan position?

### ISSUE THREAD

**Issue by sallyhill** [wojtekmaj/react-pdf#261]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'd like to be able to use a calculated x and y value to change the position of the Page inside of the Document when zooming.

**Describe solutions you've tried**

I'm sure I could somehow do this with straight DOM manipulation, but I'm hoping I can keep it react.

Currently, panning doesn't work on ios when the scale has been set larger than the container. I need to figure out how to implement panning with this library... 

Thanks!

**Comment by wojtekmaj** [comment]
Hey there,
scrollbar position is not a DOM attribute controllable by React, so it's perfectly fine way - and the only way - to use `.scrollTop` or similar. :)
