### ISSUE TITLE
Open annotations in new tab

### ISSUE THREAD

**Issue by ssteuteville** [wojtekmaj/react-pdf#262]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'd like my pdf annotations to open in a new tab.

**Describe solutions you've tried**

I read the docs and didn't see anything about this. If there isn't support I'd be open to see if I could submit a PR for the functionality.

**Comment by ssteuteville** [comment]
https://github.com/wojtekmaj/react-pdf/blob/681f940a0948f795911850fa192ed6e2e1a8cf27/src/Document.jsx#L87

https://github.com/mozilla/pdf.js/issues/7779

seems to likely be an easy fix.

**Comment by wojtekmaj** [comment]
Well that was interesting to play with. Not so simple as it had to update itself with prop update, but I think it turned out pretty well.

**Comment by ssteuteville** [comment]
Wow thanks that was a fast turn around

**Comment by ssteuteville** [comment]
@wojtekmaj When do you think this will be available in NPM?

**Comment by wojtekmaj** [comment]
I think early next week :)

**Comment by wojtekmaj** [comment]
@ssteuteville in case you missed it, it's out from September 3rd :)

**Comment by ssteuteville** [comment]
We're already using it. :) Thanks again!
