### ISSUE TITLE
index.js:2178 Invalid PDF structure

### ISSUE THREAD

**Issue by Krashna-Saraswat** [wojtekmaj/react-pdf#264]
**Description**
Hi! We have been using your package to display PDFs in our application which is not working>
The error message is shown on Console **nvalid PDF structure InvalidPDFException {name: "InvalidPDFException", message: "Invalid PDF structure"}**
And on Screen it showing **Failed to load PDF file.**

**Comment by Shyroby** [comment]
Show details of error and your code please

**Comment by Krashna-Saraswat** [comment]
[import React, { Component } from 'react';
import { Document, Page } from 'react-pdf';
 
class App extends Component {
  state = {
    numPages: null,
    pageNumber: 1,
  }
 
  onDocumentLoad = ({ numPages }) => {
    this.setState({ numPages });
  }
 
  render() {
    const { pageNumber, numPages } = this.state;
 
    return (
      <div>
        <Document
          file="somefile.pdf"
          onLoadSuccess={this.onDocumentLoad}
        >
          <Page pageNumber={pageNumber} />
        </Document>
        <p>Page {pageNumber} of {numPages}</p>
      </div>
    );
  }
}

export default App;

![screenshot from 2018-09-03 15-40-49](https://user-images.githubusercontent.com/35986472/44981412-13f86f00-af90-11e8-8451-58f1139f373e.png)


Please check and let me know.

**Comment by Krashna-Saraswat** [comment]
What path you are talking about. As i check my code there is no options for PAth and there is no 404 error in Network tab. 

Can you please provide me its demo?

**Comment by Krashna-Saraswat** [comment]
And **somefile.pdf** is existing file or it will create new pdf by **somefile.pdf** this name?

**Comment by wojtekmaj** [comment]
If you're trying to *create* a PDF, then you have confused this package with `@react-pdf/renderer`.
