### ISSUE TITLE
Retrieve file from local folder (C:/temp/file.pdf) 

### ISSUE THREAD

**Issue by Shyroby** [wojtekmaj/react-pdf#265]
How can i retrieve the file to render from a local temporary folder? 

i tried this: 
`      <div>
        <Document file={URL('file:///C:/Users/marco/AppData/Local/Temp/file.pdf')}>
        </Document>
      </div>
`
also tried with import file from c:/...

But Always the same error was shown. Component not found.

How can i pass the file from the temporary local storage to the Document component? 

Thank you.

**Comment by wojtekmaj** [comment]
You can't. You will not be able to make any network requests to "file:///" protocol.

If you need an access to a locally stored PDF, best way is to simply import them to your bundle and pass to `file` prop.
If you need to get them by a dynamic address, you'd need to create a server with an endpoint which would return these PDFs for you. This could be a serious danger for your privacy and security, though. I would highly discourage storing PDFs outside of a dedicated server.
