### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by sansetty2510** [wojtekmaj/react-pdf#267]
Does React-Pdf support Pagination or we need to write a custom one.

If built in pagination is not available, is there any plan to add Pagination in the upcoming release. 
Please give me the information regarding this.

**Comment by wojtekmaj** [comment]
React-PDF is not trying to be a fully fledged PDF viewer. It only gives the developers easy access to PDFs. You will need to build pagination yourself, although it's very easy. You simply need to render `Page` inside `Document` like so:

```js
<Page pageNumber={pageNumber} />
```

where `pageNumber` is the page number saved in componen't state. You can have a look at my [Test suite](https://github.com/wojtekmaj/react-pdf/blob/master/test/Test.jsx) for a sample implementation.

**Comment by sansetty2510** [comment]
@wojtekmaj Thanks for quick update.
I have another question if the pdf contains any links which will redirect to some websites how to disable those links.

**Comment by wojtekmaj** [comment]
Links are created on annotations layer, so you can disable annotation layer. Another way would be to set a listener for `click` event somewhere higher on the DOM tree, and cancel the events. This way other annotations would be still rendered.
