### ISSUE TITLE
Text fragments on rendered SVG

### ISSUE THREAD

**Issue by Boby1988** [wojtekmaj/react-pdf#268]
Hello!

I'm using the latest version of this package with the following properties:
- renderMode: "svg"
- renderTextLayer: false
- renderAnnotations: false
Some of the PDF documents looks good but others have duplicated text fragments. These parts usually rendered into the latest svg:g child as svg:text element. With these the document is almost unreadable, but when I remove these fragments via CSS the document looks good. 

But! I can not use the CSS rule overal, because some of the documents (which rendered correctly) has no text. And I don't see any difference in the SVG structure (atleast in this relevant part) what can accept the CSS rule.
![sample](https://user-images.githubusercontent.com/5682574/45296122-50cce480-b501-11e8-8ddd-4a6b43057150.jpg)

I hope somebody can help me to fix this.
Thanks for considering my issue riport!

**Comment by wojtekmaj** [comment]
SVG mode does not render text layer, as it doesn't need it - you can select and even style text on SVG if you need to.

**Comment by Boby1988** [comment]
Do you have any ide why renders the red texts? I try to display invoices, and several type of pdf comes. I found few render this phantom texts and when I hide them with CSS invoice preview become perfect. But in few cases without CSS manipulation the whole preview is perfect (no phantom text) and the CSS rules hide the entire content of the invoce. And the 3rd group of the PDF is the best because they don't affected by this and always looks good.

**Comment by wojtekmaj** [comment]
It may be an issue with Mozilla's PDF.js. Maybe report it there with a sample PDF and they will be able to help!

**Comment by Boby1988** [comment]
Alright. I appreciate your help.
