### ISSUE TITLE
Scroll to a specific point using react-pdf

### ISSUE THREAD

**Issue by mNeevetha** [wojtekmaj/react-pdf#271]
@wojtekmaj Is possible to scroll/navigate to a specific position in a pdf using react-pdf? If yes, how can that be achieved?

**Comment by wojtekmaj** [comment]
Pages which you render are the same DOM elements as any others. You get a DOM element by using `ref`, and you can scroll to it by using [Element.scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView).

**Comment by frontr-uk** [comment]
amazing, would be good to add this to readme :)

**Comment by frontr-uk** [comment]
@wojtekmaj could I ask if possible for a plunker example?
Element.scrollIntoView().

**Comment by wojtekmaj** [comment]
Sure, for example if you want to render all pages and scroll the one with matching page number into view, you will need to write something like:

```js
Array.from(new Array(numPages), (el, index) => (
  <Page
    key={`page_${index + 1}`}
    inputRef={() => {
      if (ref && pageNumber === index + 1) {
        ref.scrollIntoView();
      }
    }}
    pageNumber={index + 1}
  />
)
```

**Comment by cneltyn** [comment]
@wojtekmaj is it possible to scroll into annotation? I mean to render some annotations info outside, click on one of it and scroll to the  appropriate annotation in the document.

**Comment by wojtekmaj** [comment]
There is customTextRenderer which allows you to render text layer using your custom logic, but that's not possible for annotations, unfortunately. You will need to dive into PDF data (provided in onLoadSuccess for Page and Document components) to achieve this.

**Comment by muka** [comment]
@wojtekmaj sorry for the dumb question, in your example you use `ref` but where is it initialized?

**Comment by wojtekmaj** [comment]
@muka Fixed the original example.

**Comment by Kazerian** [comment]
> Sure, for example if you want to render all pages and scroll the one with matching page number into view, you will need to write something like:
> 
> ```js
> Array.from(new Array(numPages), (el, index) => (
>   <Page
>     key={`page_${index + 1}`}
>     inputRef={(ref) => {
>       if (ref && pageNumber === index + 1) {
>         ref.scrollIntoView();
>       }
>     }}
>     pageNumber={index + 1}
>   />
> )
> ```

@wojtekmaj  So, if on click of a button I want the scroll to page 4 on an external button click 

will it be like 

`<button onClick={()=>setPageNumber(4)}>Scroll to view </button>`

```js
Array.from(new Array(numPages), (el, index) => (
  <Page
   key={`page_${index + 1}`}
    inputRef={(ref) => {
      if (ref && pageNumber === index + 1) {
        ref.scrollIntoView();
      }
    }}
     pageNumber={index + 1}
   />
) 
```

**Comment by krishnaacharyaa** [comment]
> remains

Did you get any answer for this? @wojtekmaj @Kazerian ?

**Comment by krishnaacharyaa** [comment]
> > Sure, for example if you want to render all pages and scroll the one with matching page number into view, you will need to write something like:
> > ```js
> > Array.from(new Array(numPages), (el, index) => (
> >   <Page
> >     key={`page_${index + 1}`}
> >     inputRef={(ref) => {
> >       if (ref && pageNumber === index + 1) {
> >         ref.scrollIntoView();
> >       }
> >     }}
> >     pageNumber={index + 1}
> >   />
> > )
> > ```
> 
> @wojtekmaj So, if on click of a button I want the scroll to page 4
> 
> will it be like
> 
> `<button onClick={()=>setPageNumber(4)}>Scroll to view </button>`
> 
> ```js
> Array.from(new Array(numPages), (el, index) => (
>   <Page
>    key={`page_${index + 1}`}
>     inputRef={(ref) => {
>       if (ref && pageNumber === index + 1) {
>         ref.scrollIntoView();
>       }
>     }}
>      pageNumber={index + 1}
>    />
> ) 
> ```
> 
> if this is right, then my next question is that example as a user i scrolled up to say page 8 using the mouse, again if i tap the `scroll to view` button my pdf doesn't go back to page 4, remains on 8.

Did you get any answer for this? @wojtekmaj @Kazerian ?

**Comment by PreciousNiphemi** [comment]
Please is it possible to scroll to a particular page where a paragraph is? if all I have is the paragraph text?

**Comment by vipierozan99** [comment]
@krishnaacharyaa I got something working

```ts
export function PdfViewer({ pdfUrl }: PdfViewerProps) {
	const [numPages, setNumPages] = useState<number>();
	const refs = useRef<HTMLDivElement[]>([]);

	function onDocumentLoadSuccess({ numPages }: { numPages: number }): void {
		setNumPages(numPages);
	}

	function scrollToPage(pageNumber: number) {
		refs.current[pageNumber - 1].scrollIntoView({
			behavior: "smooth",
			block: "start",
		});
	}

	return (
		<Stack
			sx={{
				overflowY: "scroll",
				...sx,
			}}
		>
			<Document file={pdfUrl} onLoadSuccess={onDocumentLoadSuccess}>
				{Array.from(new Array(numPages), (_el, index) => (
					<Page
						key={`page_${index + 1}`}
						inputRef={(ref) => {
							if (ref) refs.current[index] = ref;
						}}
						pageNumber={index + 1}
					/>
				))}
			</Document>
			<Button onClick={() => scrollToPage(1)}>Scroll to Page 1</Button>
		</Stack>
	);
}
```
