### ISSUE TITLE
Optimization Opportunity through using <link rel=preload> for the service-worker

### ISSUE THREAD

**Issue by thepiyushpandey** [wojtekmaj/react-pdf#272]
Hi,

First of all thank you for this. It was of great help. Really really helpful.

I am using this along with the webpack. Service worker runs and everything works fine.
However, when i run the Lighthouse tool, it suggest me that i could save upto 8.45 sec if i use `<link rel=preload>` for the pdf-js service worker.

I added the link, but now i want to add it to the document when needed. Otherwise it is anyway being fetched again. I don't know what is the best place to do it. Will really appreciate any help.

**Comment by wojtekmaj** [comment]
Well, it's entirely up to you and depends on your app. Once you're 100% sure that the resource will be used at some point, it makes sense to add `link`.  If you don't have many resources to preload and you are fairly certain that the user will see the PDF at some point, you can safely just add it at the very beginning. It will be loaded with the lowest priority anyway, so shouldn't affect overall page performance.

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!

**Comment by barrymichaeldoyle** [comment]
I've come across this too but I'm not sure how to implement it with `create-react-app` :/

I've got the following setup in my `index.html`:

```
<link
  as="script"
  href="%PUBLIC_URL%/9ee65873b323926b6182.worker.js"
  rel="preload"
/>
```

But the name of the `.worker.js` file changes every time I build. How can I work around that?
