### ISSUE TITLE
Named Webpack chunks of PDF.js

### ISSUE THREAD

**Issue by ccorcos** [wojtekmaj/react-pdf#274]
It would be nice if the webpack chunks created by this project were named so I can handle them separately.

**Comment by ccorcos** [comment]
Current names are:

```
3-b04cd683fded9adeb39f.js
4-cec33cb028f053c8861e.js
9e0e2a90ddf92457636e.worker.js
vendors~pdf-2f6389aff856401fb70c.js
```

**Comment by wojtekmaj** [comment]
Hello,
this project does not create any chunks. Your Webpack does. All React-PDF does is providing you with the modules, to bundle with whatever tool you prefer. How your chunks are called is controlled by `output.chunkFilename`.

**Comment by ccorcos** [comment]
In my code, I have `await import(/* webpackChunkName: "pdf" */ "react-pdf/dist/entry.webpack")` which does generates a `pdf-xxxxxxxxxxxxxxxxxxxx.js` file. But I'm also seeing these other four. My `chunkFilename` setting is `"[name]-[chunkhash].js"` so the webpack entry appears to be missing names for these other four files. That said, I'm not entirely sure how this project is supposed to work.

**Comment by wojtekmaj** [comment]
I'm afraid these are the chunks created by Mozilla's PDF.js which is our dependency. They shouldn't use Webpack magic comments though in case someone else would use the same webpackChunkName. So in this case it's best to use it as it is. You could also fork PDF.js and add your magic comments there, but I doubt if it's worth it.

**Comment by ccorcos** [comment]
Well you could create really specific magic comments that won't ever collide. Just something so I can reliably use a regex to move these files somewhere else. If I add another chunk, the mozilla chunks may end up turning into 5 and 6 making my code brittle and unreliable.

**Comment by wojtekmaj** [comment]
I agree that it might be an issue. Maybe it will be worth discussing with Mozilla on [their page](/mozilla/pdf.js)?
