### ISSUE TITLE
Uncaught Error: Requesting object that isn't resolved yet (font name)

### ISSUE THREAD

**Issue by rodobodolfo** [wojtekmaj/react-pdf#275]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

Hello! 
Some types of pdf throws those errors, cannot be sure what makes them distinct to others:

```
Uncaught Error: Requesting object that isn't resolved yet Times_path_ 
    at PDFObjects_get [as get] (pdf.js:8838)
    at FontFaceObject_getPathGenerator [as getPathGenerator] (pdf.js:9698)
    at CanvasGraphics.paintChar (pdf.js:10842)
    at CanvasGraphics_showText [as showText] (pdf.js:10990)
    at CanvasGraphics_executeOperatorList [as executeOperatorList] (pdf.js:10392)
    at InternalRenderTask__next [as _next] (pdf.js:8991)
```

The font name varies from files.
Some examples:
[pdf-test(working).pdf](https://github.com/wojtekmaj/react-pdf/files/2394604/pdf-test.working.pdf)
[test(not working).pdf](https://github.com/wojtekmaj/react-pdf/files/2394605/test.not.working.pdf)

I think they work ok on v3.

thanks!

**Environment**

 - React-PDF version "react-pdf": "^4.0.0-beta.4",
 - React version "react": "^16.4.2",
 - Webpack version (if applicable)  "webpack": "^4.17.2",

**Comment by wojtekmaj** [comment]
Hey there,
thanks for report.
I checked the PDFs you have attached, and it seems to work fine in my test suite (included in the repository) using the newest React-PDF beta.
Is that a full error stack? Does it happen on all browsers? Does it happen only in your project, or in the test suite too?

**Comment by rodobodolfo** [comment]
Hmm It seems to be something related to system fonts... 

Check this https://github.com/mozilla/pdf.js/issues/4244
Im trying in an electron project.
I will try with the  test suite and report back, thank you!
