### ISSUE TITLE
InvalidCharacterError on IE11

### ISSUE THREAD

**Issue by sparrowzhang28** [wojtekmaj/react-pdf#278]
I found it not working in IE11.(it's fine in chrome and Firefox)
![image](https://user-images.githubusercontent.com/40854484/45996086-7515ed00-c0cd-11e8-8706-910be6a0d834.png)
 
i have this message 

I've tried to change 'import { Document } from 'react-pdf/dist/entry.webpack';' to
'import { Document, Page } from 'react-pdf';'
but still not work

can you give me some advise , thanks very much

**Comment by sparrowzhang28** [comment]
when i was add onLoadError={console.log}  to <Document /> ,i get the message like fllowing
![image](https://user-images.githubusercontent.com/40854484/46052683-0ccd1700-c172-11e8-9bdc-bfe94751499c.png) 

i use this package as follow:
first :
![image](https://user-images.githubusercontent.com/40854484/46052851-bad8c100-c172-11e8-96b0-e641d107a249.png)
second:
![image](https://user-images.githubusercontent.com/40854484/46052868-d2b04500-c172-11e8-9690-4a8af340ef7f.png)

it work well in chrome and Firefox  but not good in IE11  ,thanks for your regard

**Comment by wojtekmaj** [comment]
Perhaps IE11 has a problem with too big base64 strings. How do you get `this.state.myPdf` loaded? You can also pass a binary, an URL, a File() to `file` prop.

**Comment by wojtekmaj** [comment]
Also, your `onLoadSuccess` is wrong in `<Page />` component. It's supposed to be a callback function if you need to do something after the page is loaded.

**Comment by sparrowzhang28** [comment]
I get the base64 data-flow by back end , i have delete onLoadSuccess in <Page /> , i just want to have a loading flag

**Comment by wojtekmaj** [comment]
Would you provide a sample PDF so I could debug it? It's almost certainly a problem in mozilla/pdf.js, but I can have a look first.

**Comment by sparrowzhang28** [comment]
[test.pdf](https://github.com/wojtekmaj/react-pdf/files/2422124/test.pdf)
thanks for your help.

**Comment by sparrowzhang28** [comment]
what should i do when i have the Uint8Array  in the file?   
this.props.myPdf is the base64 string;
but when i run the application ,i have got the error like the second img

![image](https://user-images.githubusercontent.com/40854484/48617880-9232b200-e9d2-11e8-8fc5-6669604f1664.png)

![image](https://user-images.githubusercontent.com/40854484/48617965-d1610300-e9d2-11e8-9157-2e079e1b7f4d.png)

![image](https://user-images.githubusercontent.com/40854484/48617981-de7df200-e9d2-11e8-87ab-13cf226f03b8.png)

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!

**Comment by Loveishax** [comment]
I have the same problem,i try to use the same method to get  Uint8Array by base64,It doesn't work,I got
 the same error like this.
![image](https://user-images.githubusercontent.com/40162315/138240692-e04d4f9a-7347-4bf7-8944-30458eaa705b.png)
and if i try to use the method like 
file={{uint8Array}} 
the page will crash,i want to know to use Uint8Array in react-pdf.Can u give me a sample?
