### ISSUE TITLE
Failed to load PDF from '../filename.pdf' file prop

### ISSUE THREAD

**Issue by romangorelik** [wojtekmaj/react-pdf#281]
Just wanted to put a pdf into my page, it seems to load forever though and doesn't render. Any issue for this?

I have a pdf in my directory, and I just put it in 

             <Document
                file="../Resume.pdf"
              >
              </Document>

It doesn't seem to want to load and was wondering what I was doing wrong. The pdf itself works.

**Comment by wojtekmaj** [comment]
Remember that the url passed as a string here will be resolved browser-side. So if your page is http://example.com/app, then this URL will point at http://example.com/Resume.pdf. I think this may be incorrect.

Check Network tab in developer tools to see where the file is loaded from.

**Comment by 5im15jogeorge** [comment]
I have the same problem. How can I solve it?

**Comment by wojtekmaj** [comment]
Does my comment above does not make it clear?

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
