### ISSUE TITLE
Change orientation from portrait to landscape

### ISSUE THREAD

**Issue by SevenSinS02** [wojtekmaj/react-pdf#282]
I'd like to change the orientation to that of landscape from the default portrait. How do I achieve this?

**Comment by wojtekmaj** [comment]
Please see README and search for `rotate` prop.

**Comment by SevenSinS02** [comment]
@wojtekmaj can we reopen this issue?

The rotate prop rotates the pdf and the content as well. 

This is the default  portrait mode.
![snip20181008_1](https://user-images.githubusercontent.com/14374646/46597138-89f67580-cafc-11e8-9a3d-0b35d29750d6.png)

What I expect is this when I rotate. Notice the pdf is now scrolled horizontally as in any popular ebook readers.
![snip20181008_2](https://user-images.githubusercontent.com/14374646/46597159-a5618080-cafc-11e8-94f1-98d6480eaa2f.png)

**Comment by wojtekmaj** [comment]
React-PDF does not build any kind of layout apart from the minimum amount of code to keep the layers of the page together. How you position the pages is entirely up to you, just like when you work with, for example, images.

**Comment by rahulsahni06** [comment]
@wojtekmaj rotate prop is not rotating the pdf. I tried it in the https://react-pdf.org/repl but there also its not working. Am I missing something?
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/21311235/212574623-e500888f-7f38-4d19-97f0-d8209374e879.png">

**Comment by NahuelOrselli** [comment]
@rahulsahni06 react-pdf.org is another package.
In the README you can view this:

Lost?
This package is used to display existing PDFs. If you wish to create PDFs using React, you may be looking for [@react-pdf/renderer](https://github.com/diegomura/react-pdf).
