### ISSUE TITLE
PDF not loaded from URL in electron

### ISSUE THREAD

**Issue by SevenSinS02** [wojtekmaj/react-pdf#284]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

To display a pdf on electron using electron-react-boilerplate.

**Describe solutions you've tried**

I've put the minimal sample code to load a pdf from a URL sent by the server. The code works independently when using in the browser. I'm not sure what's happening here.

**Additional information**

![image](https://user-images.githubusercontent.com/14374646/46496030-95b01680-c834-11e8-9e1e-c4271cc85896.png)

**Environment**
- Electron : 2.0.6
 - React-PDF version [e.g. 3.0.4]: 3.0.5
 - React version [e.g. 16.3.0]: 16.4.1
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.16.3

**Comment by wojtekmaj** [comment]
Well, I'm no expert in Electron, but I think that maybe network requests are handled in a different way. If I'm right, downloading the file automatically is not going to work.
I suggest downloading the file, reading it as ArrayBuffer/Uint8Array/File and passing it as such to `<Document />`.

**Comment by SevenSinS02** [comment]
@wojtekmaj thanks! I’ll give it a go and get back to you with the results.

**Comment by SevenSinS02** [comment]
@wojtekmaj I've tried what you suggested but have been unsuccessful. It displays the pdf when I use it in the web browser but it doesn't display it when I use it in electron. 
The pdf field in the Document state is null and hence no pdf is rendered. However, in the web browser, the pdf field in the Document state is set to an object.
Any idea why?

**Comment by SevenSinS02** [comment]
So I get, `ReferenceError: window is not defined`. So I assume that the pdf worker is not accessible.
It also points to the lines below in webpack : 
```
var parentHotUpdateCallback = window["webpackHotUpdate"];
return hotCreateRequire("./node_modules/pdfjs-dist/build/pdf.worker.js")(__webpack_require__.s = "./node_modules/pdfjs-dist/build/pdf.worker.js");
```
Any idea on what could fix this?

**Comment by SevenSinS02** [comment]
Clossing as it is in [known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues#referenceerror-window-is-not-defined)

**Comment by dakiesse** [comment]
@SevenSinS02 could you display PDF in Electron?
