### ISSUE TITLE
Fonts won't display in Internet Explorer but only with webpack in production mode

### ISSUE THREAD

**Issue by ssteuteville** [wojtekmaj/react-pdf#285]
I have a feeling this is likely a pdf.js or webpack issue. But I thought maybe you've seen the issue before and/or possible know a workaround. 

**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I want my pdfs to render in ie11 and edge properly in webpack production mode. My pdf has an embedded font subset that works fine in all browsers but ie11 and edge.

**Describe solutions you've tried**

- I've tried enabling cmaps as described in docs, didn't change anything.
- I've tried, `options={{ disableFontFace: true }}` that got me very close but there were still minor issues with the font.
- I put the pdf in your test page and it rendered fine, but when I inspected that page it seemed to be running in development mode. So, I'm not sure my pdf would render correctly if you switched to production mode. **Side note:** I tried running the test app myself but I get errors related to node_modules/react-pdf and class properties being initialized outside of methods/constructor. (seems like somehow the babel plugin isn't being applied)
- I tried added `onLoadError={console.log}` and I didn't get any additional output
- here is my console output: 
```
CSS3111: @font-face encountered unknown error.
8BgRFkrKysrKysrKysrKysrKysrKyt1KysrKysrK0NcWLkAgAK7swFAHgF0AHNZA7AeS1QCsBJLVFqwEkNcWli6AJ8CIgABAHNZACt0cwErAXMrKysrKysrK3Nzc3MrKysrKwArKysrKysARWlEc0VpRHNFaURzdHVFaURzRWlERWlERWlEc3RFaURFaURzKysrKytzKwArcyt0dSsrKysrKysrKysrKysrc3R1cytzdHVzdHUrKyt0KysAAA==
CSS3111: @font-face encountered unknown error.
wGBEWUNcWLZPLAFPHwE3K3R0WStzKysrc3N0KysrKysrKysrKysrdHMrKysrdCsAAA==
CSS3111: @font-face encountered unknown error.
8ACoLIcHTIrK1krcwErKysrACsrKysrKysrKysrKysrKysrKwErKysrKysrc3QrKysrKysrK3NzKysrKysrcytzKysrdCsrK3Nzc3NzK3NzKysrcysrACsrKytzdHMrcysrKyt1KysrKysrKyt1KysrKytzKysrK3N0dSsrc3NzKysrcytzc3R1KytzdHUrK3N0dSsrKysrKysrKysrK3R1KwAA
CSS3111: @font-face encountered unknown error.
PxgrEDwBL11DXFiyfwEBXVldQ1xYsu8BAV1ZBgywBiNCsAcjQrASQ1i5OyEYfhu6BAABqAALK1mwDCNCsA0jQrASQ1i5LUEtQRu6BAAEAAALK1mwDiNCsA8jQrASQ1i5GH47IRu6AagEAAALK1mwECNCsBEjQgArKysrKysrKysrKysrKysrKysrK3NzdCtzKysrKysrKysrKysrACsrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysAGEVpREVpREVpRBhFaUQYRWlEc3N0dXNzdHVzdHN0dHR0dHNFRHNFRHQAS7AqU0uwOFFaWLEHB0WwQGBEWQBLsC5TS7A4UVpYsQMDRbBAYESxCQlFsEBhRFlzc3Nzc3Nzcyt0dXQrKytDXFhAMUAqNDNAKjMzQCoyM0AqMTNAKjAzQCovM0AnNDNAJzMzQCcyM0AnMTNAJzAzQCcvM6BBCgLLAAEAoALIAAEAnwLLAAEAnwLIQDMBQCoqM0AqKTNAJyozQCcpM0AqEjNAJxIzQCooM0AnKDNAKiEzQCodNTJAJx01MkAnITMAKysrKysrKysrKysrc3NzcysrKysrKysrKysrK1kAK3N0dSsrK3N0dHUrcysrKysrdSsBcwArc3R1KysrKysrKysrKysrdCsA
```
My usage of react-pdf is very basic:
```
              import { Document, Page } from 'react-pdf/dist/entry.webpack';
........
........
              <Document
                externalLinkTarget="_blank"
                file={document1Url}
                loading={<CircularProgress />}
                onLoadSuccess={onLoad}
              >
                <Page onRenderSuccess={onDocumentRender} pageNumber={1} width={pageWidth} />
              </Document>
```
webpack.common.js
```
require('webpack');
const path = require('path');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: [
    'babel-polyfill',
    'whatwg-fetch',
    path.resolve(__dirname, 'src/index.jsx'),
  ],
  module: {
    rules: [{
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      loader: 'babel-loader',
      query: {
        presets: ['react'],
      },
    }, {
      test: /\.(css|scss)$/,
      loaders: ['style-loader', 'css-loader'],
    }, {
      test: /\.svg$/,
      include: [
        path.resolve(__dirname, 'assets/icons'),
      ],
      use: [
        {
          loader: 'babel-loader',
        },
        {
          loader: 'react-svg-loader',
          options: {
            jsx: true, // true outputs JSX tags
            svgo: {
              plugins: [
                { addAttributesToSVGElement: { attributes: ['aria-hidden="true"'] } },
              ],
            },
          },
        },
      ],
    }, {
      test: /\.(jpg|png|gif|pdf|ico|svg)$/,
      exclude: [
        path.resolve(__dirname, 'assets/icons'),
      ],
      use: [
        {
          loader: 'file-loader',
          options: {
            name: '[path][name]-[hash:8].[ext]',
          },
        },
      ],
    }, {
      test: /\.(woff|woff2)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 50000,
        },
      },
    }],
  },
  plugins: [
    new CleanWebpackPlugin(['dist']),
    new HtmlWebpackPlugin({
      title: 'Portal by SkySlope',
      template: path.resolve(__dirname, 'src/index.html'),
      filename: 'index.html',
      inject: 'body',
    }),
  ],
  output: {
    publicPath: '/',
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundle.[chunkhash].js',
  },
  resolve: {
    extensions: ['.js', '.jsx', '.svg', '.png', 'json'],
    modules: ['src', 'node_modules', 'assets'],
  },
};
```

webpack.prod.js
```
require('webpack');
const merge = require('webpack-merge');
const common = require('./webpack.common.js');

module.exports = merge(common, {
  mode: 'production',
});
```
webpack.dev.js
```
require('webpack');
const merge = require('webpack-merge');
const common = require('./webpack.common.js');
const path = require('path');

module.exports = merge(common, {
  mode: 'development',
  devtool: 'inline-source-map',
  devServer: {
    contentBase: path.resolve(__dirname),
    historyApiFallback: {
      disableDotRule: true,
    },
    host: '0.0.0.0',
  },
});
```
**Additional information**
Production webpack mode:
![image](https://user-images.githubusercontent.com/1413949/46757365-c81ba280-cc7e-11e8-96e8-f92541300c07.png)

Development webpack mode (nothing in console):
![image](https://user-images.githubusercontent.com/1413949/46757517-3e200980-cc7f-11e8-84db-581f499b6d71.png)

The pdf I'm testing with:
[repaired.pdf](https://github.com/wojtekmaj/react-pdf/files/2465981/repaired.pdf)

**Environment**

 - IE11, edge
 - React-PDF version: 4.0.0-beta.5
 - React version: ~16.3.0
 - Webpack version (if applicable) [e.g. 4.16.2]: ~4.20.2

**Comment by wojtekmaj** [comment]
To me, it looks like the fonts embedded in the PDF are not supported properly be Internet Explorer. Perhaps your page is rendered in a different document mode? Do you have `<meta http-equiv="X-UA-Compatible" content="IE=edge">` meta tag?

This seems to be related: https://stackoverflow.com/questions/33023461/ie-11-error-css3111-in-my-own-code-and-google-com-fonts-doesnt-render-any-fon

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
