### ISSUE TITLE
Browser freezes when rendering this pdf

### ISSUE THREAD

**Issue by SevenSinS02** [wojtekmaj/react-pdf#286]
**Before you start - checklist**

 - [X] I followed instructions in documentation written for my React-PDF version
 - [X] I have checked if this bug is not already reported
 - [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**
The browser freezes when rendering this pdf. It's small in size while there are other pdf's that are way bigger in size that renders smoothly.

**Steps to reproduce**

[pdf](https://drive.google.com/open?id=1x0aVYEQVk3hHnXHB99bp-PFjgb_o29KX)

**Expected behavior**

What you expected to happen?

Smooth rendering of the pdf.

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Version 69.0.3497.100 (Official Build) (64-bit)
 - React-PDF version [e.g. 3.0.4]: 3.0.5
 - React version [e.g. 16.3.0]: 16.5.2
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.19.1

**Comment by HughSunny** [comment]
I had the same problem! Have a solution?

**Comment by wojtekmaj** [comment]
Checked in our [test suite](http://projects.wojtekmaj.pl/react-pdf/test/) and everything seems to be in order. Check the same page if it's working for you.

**Comment by SevenSinS02** [comment]
@wojtekmaj I'm using CRA 2 and I followed your CRA setup. 

```
import { pdfjs, Document, Page } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.0.550/pdf.worker.js`;
```

The rest of the code is your example code with navigation. When i navigate it feels like the main thread is blocked. I do suspect that the worker isn't being used. Should I do some more additional setup?

**Comment by wojtekmaj** [comment]
Regarding "Uncaught Error: Requesting object that isn't resolved yet" - this is being logged under #275 and mozilla/pdf.js#4244.

Have you checked if the PDF renders any faster in our [test suite](http://projects.wojtekmaj.pl/react-pdf/test/)? If it's equally slow, then there's nothing we can do.

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!

**Comment by tanmay-cs13** [comment]
I am trying to genrate the pdf, it is of 250 pages and the browser gets freeze on running following code:

`
render() {
    let { pdfData } = this.props;
    let size = [toNumber(pdfData.pageInfo.pageWidth), toNumber(pdfData.pageInfo.pageHeight)];

    let templatePages = [];
    for(let i = 0; i < pdfData.pageNumber; i++) {
      templatePages.push((
        <Page key={ "page_" + i } size={ size } style={ styles.page }>
          <Image src={ *img_path* } />
          <Image src={ *img_path* } />
        </Page>
      ));
    }
    
    return (
      <Document>
        <Page size={ size }>
          <Image src={ *img_path* } />
        </Page>
        { templatePages }
        <Page size={ size }>
          <Image src={ *img_path* } />
        </Page>
      </Document>
    );
  }
`

**Comment by wojtekmaj** [comment]
@tanmay-cs13 That's not React-PDF, that's diegomura's react-pdf/renderer I believe.

**Comment by Siddhartha-chaki** [comment]
> Checked in our [test suite](http://projects.wojtekmaj.pl/react-pdf/test/) and everything seems to be in order. Check the same page if it's working for you.
> 
> If the rendering is smooth on the test suite, there might be something wrong with your implementation, e.g. you're not using worker.

Sir can you provide this test-suite source code, I also stuck in rendering big file in my case I want to show PDF from long base64 encoded string I got error as 

"./src/App.js
RangeError: Maximum call stack size exceeded
Occurred while linting F:\pdfrender1\src\App.js:8
    at String.match (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.forEach (<anonymous>)
    at Array.map (<anonymous>) "
"0: Module build failed (from ./node_modules/eslint-loader/index.js):
RangeError: Maximum call stack size exceeded
Occurred while linting F:\fossee\tests\pdfrender1\src\App.js:8
    at String.match (<anonymous>)
    at Literal (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\rules\no-octal-escape.js:35:40)
    at listeners.(anonymous function).forEach.listener (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\linter.js:752:32)
    at Array.forEach (<anonymous>)
    at runRules (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\linter.js:747:15)
    at Linter._verifyWithoutProcessors (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\linter.js:899:31)
    at preprocess.map.textBlock (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\linter.js:955:35)
    at Array.map (<anonymous>)
    at Linter.verify (F:\fossee\tests\pdfrender1\node_modules\eslint\lib\linter.js:954:42)"

code 

import React, { Component } from 'react';
//import { Document } from 'react-pdf/dist/entry.webpack';
import { Document, Page, pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

class PDFViewer extends Component {
    constructor(props) {
        super(props);
        this.state = {
            numPages: null,
            pageNumber: 3,
        };
    }

    onDocumentLoad = ({ numPages }) => {
        console.log("test1");
        this.setState({ numPages });
    }
    goToPrevPage = () =>
        this.setState(state => ({ pageNumber: state.pageNumber - 1 }));
    goToNextPage = () =>
        this.setState(state => ({ pageNumber: state.pageNumber + 1 }));
    onclick = () => {
        console.log(this.props.src);
    }
    render() {
        return (
            <div>
                <nav>
                    <button onClick={this.goToPrevPage}>Prev</button>
                    <button onClick={this.goToNextPage}>Next</button>
                </nav>
                <Document
                    file={this.props.src}
                    onLoadSuccess={this.onDocumentLoad}
                >
                    <Page pageNumber={this.state.pageNumber} onLoadError={e => { console.log(e) }} />
                </Document>
                <p>Page {this.state.pageNumber} of {this.state.numPages}</p>
                <button onClick={this.onclick}>click me</button>
            </div>);
    }
}

export default PDFViewer;


<PDFViewer src="data:application/pdf;base64,JVBERi0xLjcKJbe+raoKMSAwI.................."/>
The base64 encoded string `size 11.2 MB, length 11783021`  

please help

**Comment by wojtekmaj** [comment]
Test suite source code is here in the repository: https://github.com/wojtekmaj/react-pdf/tree/master/test

**Comment by Siddhartha-chaki** [comment]
sir, what cause the error "RangeError: Maximum call stack size exceeded"  while render PDF from base64 string. I fellow the test suit code which works find in case of pdf- < 5MBs 20 to 30 pages.
My main task is to show PDF from row base64 string data it can be of any size (100KBs to 50MBs ) with faster rendering time.

**Comment by wojtekmaj** [comment]
I'd need to see the call stack of this error message you're facing to be able to tell you more.

**Comment by tonsquemike** [comment]
I have the same problem while rendering a 272pages PDF file. My react App freezes on rendering and after 5 minutes the App unfreezes. Is thera a way to use a Promise in order to wait at the rendering finishes of PDFDownloadLink?

**Comment by wojtekmaj** [comment]
Are you rendering the whole PDF at once? Because this sounds like you're trying to do exactly that, which can be a bad idea on an army of Apple M1s.

**Comment by michaelwschultz** [comment]
I have an issue with a single 3 page PDF rendering slowly on page change. @wojtekmaj thanks for the note about the test-suite. Didn't realize that was a thing. Through it, I discovered that the text-layer was the issue for me. Turning that off made things instant! Guess this PDF has some wild stuff going on under the hood. Hope that helps @tonsquemike, @SevenSinS02.
