### ISSUE TITLE
Memory Leak when changing file prop while current file is still loading

### ISSUE THREAD

**Issue by barrymichaeldoyle** [wojtekmaj/react-pdf#288]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

Changing the `file` prop while it's still loading it's current document causes a memory leak.
[Link to error screenshot](https://ibb.co/eYgObL)

**Steps to reproduce**

Change the `file` prop while the current file is still loading.

**Expected behavior**

`this.setState(...)` on changing file should only occur when the current page is not loading.

**Additional information**

Attached a link to the console above, this problem doesn't cause the package to stop working. It's just a performance issue that should be looked at.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Chrome
 - React-PDF version [e.g. 3.0.4]: 4.0.0-beta.5
 - React version [e.g. 16.3.0]: 16.5.2
 - Webpack version (if applicable) [e.g. 4.16.2]: using CRA2

**Comment by ed-sparkes** [comment]
Hi, I see there was a beach with a fix for this but not merged. @barrymichaeldoyle did you ever get round to seeing if it solved the issue. @wojtekmaj any plans to merge the PR?

**Comment by wojtekmaj** [comment]
Please kindly check React-PDF [`v5.3.0-beta.2`](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.3.0-beta.2), in which improvements regarding memory management were made.

Let me know what you think in #748!
