### ISSUE TITLE
Im trying to pass url (https) as a parameter. But Im getting "No PDF file specified." as a response

### ISSUE THREAD

**Issue by ShivaprasadSuvarna45** [wojtekmaj/react-pdf#289]
**Before you start - checklist**

 - [ ] I have read documentation in README
 - [ ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [ ] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Rendering pdf inside react component

**Describe solutions you've tried**

```
<div style={{ width: 600 }}>
                        <Document
                            url="https://www.example.com/somefile.pdf"
                              
                            onLoadSuccess={this.onDocumentLoadSuccess}
                        >
                            <Page pageNumber={pageNumber} width={600} />
                        </Document>
                    </div>
```

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.5]:
 - React version [e.g. 16.5.2]:
 - Create react app 
****

**Comment by wojtekmaj** [comment]
Please fix your sample code as I can't see any place in which you would pass url as a parameter, so I can't help you.

**Comment by wojtekmaj** [comment]
1. Try and use `onLoadError` callback to get an error, if any. If that callback won't be called, then `onLoadSuccess` must be, no other way.
2. Is `pageNumber` defined?

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!
