### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by 8ctopotamus** [wojtekmaj/react-pdf#29]
Awesome package! :D

I am getting this warning when importing though:

```Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.```

**Comment by jjhamshaw** [comment]
also getting the same warning using version... `"react-pdf": "^1.6.1"`

**Comment by mrobrian** [comment]
I have version 1.6.1 (verified in package.json within node_modules/react-pdf) but my react-pdf/src/react-pdf.jsx file is different from what I see on github.  Maybe something went wrong with the npm repo?  Not sure.  But this issue would be resolved with the code that is currently on github with the version 1.6.1.

**Comment by wojtekmaj** [comment]
Hey,
I just updated master branch with new files, also built on Webpack 3.2 now. Have a look if this problem is resolved for you! Next release is coming shortly :)

**Comment by mrobrian** [comment]
I was able to test it using `"react-pdf": "git://github.com/wojtekmaj/react-pdf.git#c078b4a"` to grab a specific commit (the latest at the time) and it does resolve the prop types warnings 👍

**Comment by wojtekmaj** [comment]
Fixed in 1.7.0.

**Comment by 8ctopotamus** [comment]
I just tried updating to 1.7.0.

Now I am getting this error:

```
Error in ./~/pdfjs-dist/webpack.js
Module not found: 'worker-loader' in C:\Users\joshn\Documents\github\sabine-hill-tile-customizer\node_modules\pdfjs-dist

 @ ./~/pdfjs-dist/webpack.js 18:18-64
```

**Comment by wojtekmaj** [comment]
Hey @8ctopotamus , sorry for the inconvenience! Please try the latest (1.8.2).

**Comment by 8ctopotamus** [comment]
Awesome, works great! Thanks for the quick response!
