### ISSUE TITLE
create-react-app setup yields `Uncaught TypeError: Cannot read property 'GlobalWorkerOptions' of undefined`

### ISSUE THREAD

**Issue by donatoaz** [wojtekmaj/react-pdf#291]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I would like to setup the pdf worker on an un-ejected create-react-app application

**Describe solutions you've tried**

First I tried using the instructions on [Browserify and Others](https://github.com/wojtekmaj/react-pdf#browserify-and-others). This would give  me the error in the title: `Uncaught TypeError: Cannot read property 'GlobalWorkerOptions' of undefined`.

```javascript
import { pdfjs } from 'react-pdf'
pdfjs.GlobalWorkerOptions.workerSrc = process.env.PUBLIC_URL + '/pdf.worker.js'
```

Then I tried importing pdfjs directly from `pdfjs-dist`, which got me: `Uncaught TypeError: Cannot set property 'workerSrc' of undefined`

```javascript
import pdfjs from 'pdfjs-dist'
pdfjs.GlobalWorkerOptions.workerSrc = process.env.PUBLIC_URL + '/pdf.worker.js'
```

Since both these options did not work, I tried following [this comment](https://github.com/facebook/create-react-app/issues/1574#issuecomment-280436498), as such I got no errors, but the warnings below:

```javascript
window.PDFJS.workerSrc = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.0.305/pdf.worker.js'
```

warning:
```
./node_modules/pdfjs-dist/lib/display/api.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

And as a matter of fact I don't even know if it worked (how can I check if there is a worker running?)

**Environment**

 - Browser : Chrome Version 70.0.3538.67
 - React-PDF version 3.0.5
 - React version 16.5.2
 - Webpack version 4.19.1
- CRA version 1.5.2

Thanks for any tips and pointers!

**Comment by wojtekmaj** [comment]
From what I see you're using React-PDF 3.0.5. 4.0 which is on master branch will be out next week. Please see this :) --> https://github.com/wojtekmaj/react-pdf#before-you-continue

**Comment by Puspendert** [comment]
I am using `4.0.0-beta.5`
But I am getting `InvalidPDFException` for [this file](http://www.africau.edu/images/default/sample.pdf)
`InvalidPDFException {name: "InvalidPDFException", message: "Invalid PDF structure"`

My Component:
```
import React from "react"
import { Document, pdfjs } from "react-pdf"
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${ pdfjs.version }/pdf.worker.js`

class Sample extends React.Component {
  render(){
     return(
        <div>
          <Document file="/Users/laptop/Desktop/sample.pdf" />
        </div>
     )
  }
}
```
Also, there are lot of warning on console

**Comment by jmz7v** [comment]
Hi @wojtekmaj 
I think I'm hitting the same issue, also with `create-react-app`

Versions
```
"react-pdf": "4.0.0",
"react": "^16.4.1",
"react-scripts": "2.0.3",
```

My component imports `react-pdf` as follows:
```jsx
import { Document, Page, pdfjs } from 'react-pdf'
```

And my browser returns
```jsx
TypeError: Cannot read property 'GlobalWorkerOptions' of undefined
```
on the following line
```jsx
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`
```
I'm console logging `pdfjs` and it returns `undefined`.

Is there any chance the `pdfjs` export is not working?

**Comment by avrame** [comment]
Any update on this issue? I'm having the same problem as @jmz7v

**Comment by evanzombie** [comment]
I am also getting this warning: 

**Critical dependency: require function is used in a way in which dependencies cannot be statically extracted**

I'm using  "react-pdf": "^4.0.5", and "react": "^16.8.6".
Used the pdf.worker.js file from cdn as shown below:
```
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${
  pdfjs.version
}/pdf.worker.js`
```

**Comment by cmr624** [comment]
Am having this same issue! PDFs not loading

**Comment by 904492381** [comment]
> I am also getting this warning:
> 
> **Critical dependency: require function is used in a way in which dependencies cannot be statically extracted**
> 
> I'm using "react-pdf": "^4.0.5", and "react": "^16.8.6".
> Used the pdf.worker.js file from cdn as shown below:
> 
> ```
> pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${
>   pdfjs.version
> }/pdf.worker.js`
> ```

How did you solve it?

**Comment by wojtekmaj** [comment]
This is unrelated to this thread. see #280 for discussion on "Critical dependency: require function is used in a way in which dependencies cannot be statically extracted".

**Comment by wojtekmaj** [comment]
Please kindly check React-PDF [`v5.3.0-beta.2`](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.3.0-beta.2), in which improvements regarding loading PDF.js worker were made. 

With these changes you should be able to use Webpack entry file in Create-React-App, without the need of using external CDN for hosting worker.

Let me know what you think!

**Comment by erick-umc** [comment]
Hi, 

For anyone using react-rails and running into this problem. Check out this thread as well: 

https://github.com/wojtekmaj/react-pdf/issues/659#issuecomment-720351158

I copied the worker.js to my components directory and fixed the webpacker errors as described of the link above. After that, the library is working well.

**Comment by kudakwashe-pro** [comment]
* Mine works with no error only u should make sure u are using the correct `pdf-worker-min.js` for the version of your `react-pdf`
* Please not that in 
    ```jsx
     import * as PDFworker from 'assets/pdf-worker-min.js';
    ```
     ```jsx
     'assets/pdf-worker-min.js' // path to where file is stored 
                              // so u may change the path according to where you store your file
     ```

* Use this code as your guide line
```jsx 
import React from 'react';
import PropTypes from 'prop-types';
// react pdf viewer
import { PdfJs, Viewer, Worker } from '@react-pdf-viewer/core';
import '@react-pdf-viewer/core/lib/styles/index.css';
import { defaultLayoutPlugin } from '@react-pdf-viewer/default-layout';
import '@react-pdf-viewer/default-layout/lib/styles/index.css';
import { GlobalWorkerOptions } from 'pdfjs-dist';
import * as PDFworker from 'assets/pdf-worker-min.js'; // import from path to where file is stored 
// Custom PDF viewer component
const PDFViewer = ({ pdfUrl }) => {
    // Create new plugin instance
    const defaultLayoutPluginInstance = defaultLayoutPlugin();
    GlobalWorkerOptions.workerSrc = PDFworker

    // Render the PDF viewer component
    return (
        <div style={{ height: '750px' }}>
            {pdfUrl ? (
                // Render the PDF viewer with the custom plugin instance "https://unpkg.com/pdfjs-dist@3.4.120/build/pdf.worker.min.js"
                <Worker>
                    <Viewer fileUrl={pdfUrl} plugins={[defaultLayoutPluginInstance]} />
                </Worker>
            ) : (
                <div>No PDF file selected</div>
            )}
        </div>
    );
};
PDFViewer.propTypes ={
    pdfUrl: PropTypes.string.isRequired,
}

export default PDFViewer;
```
* Any error l can help on this
