### ISSUE TITLE
Loading from CDN with webpack

### ISSUE THREAD

**Issue by haf** [wojtekmaj/react-pdf#292]
- [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I've just added service workers, they sometimes request old index.html that in turn request old js files; hence I set up a more permanent storage domain, cdn.domain.com (and a CDN to go with it). Now I'm having trouble activating the code-splitted react-pdf worker when that file is loaded via the CDN.

Now the worker is not loading. Here's [why](https://github.com/medialize/sass.js/issues/84#issuecomment-317266289) as a side-note (you can skip the link).

The code (for webpack 4) looks like this:

```js
const Page = Loadable({ loader: () =>
  import(/* webpackChunkName: "react-pdf" */ 'react-pdf/dist/entry.webpack')
    .then(x => x.Page)
    .catch(e => console.error('Failed loading Page', e))
})
const Document = Loadable({ loader: () =>
  import(/* webpackChunkName: "react-pdf" */ 'react-pdf/dist/entry.webpack')
    .then(x => x.Document)
    .catch(e => console.error('Failed loading Document', e))
})
// usage here...
```

Which looks like this when loading:

<img width="1016" alt="screen shot 2018-10-25 at 22 04 33" src="https://user-images.githubusercontent.com/193115/47527111-02518a80-d8a2-11e8-933e-7965ac5bf723.png">

...and gives off this error:

<img width="1012" alt="screen shot 2018-10-25 at 22 00 35" src="https://user-images.githubusercontent.com/193115/47527121-08e00200-d8a2-11e8-982d-cfcc2f214e29.png">

I'd like:

 - To code-split both the lib and the lib's worker out from the main app and load it on demand

**Describe solutions you've tried**

 1. From what I understand, https://github.com/wojtekmaj/react-pdf#browserify-and-others could be a solution, even with webpack? Drawback: more moving parts, more things to configure, another CSP header statement to add.
    * **Now I tried this, after point 3, and with this, I have to configure the worker, hence load `react-pdf` as part of my main app bundle?**
 2. It would be optimal to be able to tell the import to load this from a different public path (cdn.domain.com's content is also present at domain.com with identical paths), but I can't find how to do that
 3. I could use this webpack plugin https://github.com/agoldis/webpack-require-from#methodname and defer the src lookup to a runtime function; that function would special-case react-pdf.
     * *I just tried this, but unfortunately this turns into this:* <img width="1004" alt="screen shot 2018-10-25 at 22 39 30" src="https://user-images.githubusercontent.com/193115/47529052-121f9d80-d8a7-11e8-9f7e-9b01149c3af5.png">

Which should I choose to be forward compatible and minimise friction and maintenance?
 
 - React-PDF version [e.g. 3.0.4]: 4.x/master
 - React version [e.g. 16.3.0]: latest
 - Webpack version (if applicable) [e.g. 4.16.2]: latest

**Comment by wojtekmaj** [comment]
1. Service worker URL returning HTML is an "Error 404" of a modern JS application. In this case it doesn't look like a cross-origin error to me.
2. How does your app works if you don't wrap react-pdf in Loadable? I suspect this may be affecting some things.
3. Yes, *Browserify and others* is a generic solution that should work for all 
4. I don't think it's necessary to resign from code splitting just because you need to configure PDFjs.dist. Only I'd load the whole ReactPDF asynchronously and forget about Loadable to achieve this. Or, perhaps wrapping a component one level higher in Loadable?
5. Loading workers from a custom URL is done via `pdfjs.GlobalWorkerOptions.workerSrc`.

**Comment by haf** [comment]
@wojtekmaj Service workers can't communicate across domain boundaries; I believe the error was correct in its statement. 2) Loadable doesn't interact at all; it's the splitting that preserves the `publicPath` URI path. 3) Yes, this corresponds to my solution 1., which had to go with your point 5 because of the domain-boundaries.

4) true, I managed to introduce code splitting, but setting `GlobalWorkerOptions` in the callback of the promise of the import of react-js in the `index.js` file.

So the solution I went for was 1. in my original question, and Loadable and code-splitting works just fine. Outstanding question is whether there's any way I can validate the worker script is offloading the UI thread @wojtekmaj ?

**Comment by wojtekmaj** [comment]
I guess you could load a PDF that takes ages to render and try and click some buttons on the UI to check if it's working ;)

**Comment by coreyja** [comment]
@haf Came across this while seeing the same or a very similar issue so thank you for the detailed write up!

I have a question about your setup, if you have a sec and remember the specifics lol.
I see from the screenshot that you were requesting from the `cdn.qvitoo.com` and hosting on `qvitoo.dev` (notice the `com` and `dev`)
Was this always how you were running it? Or did you ever have them both under the same root domain? Curious if having them both under the same root would also have the same issue. Might have to try it out for myself, but thought I'd drop you a line too!

And @wojtekmaj thanks for the great library!

**Comment by haf** [comment]
@coreyja I never released the broken code to production, but in prod it would have been ´qvitoo.com´and not ´qvitoo.dev´. Also since then I realised Google bought .dev, so now I'm all on .test ;)

**Comment by coreyja** [comment]
@haf Thanks for the reply!

I did some playing around today as well trying to load the Web Worker from a different sub-domain, from a consistent root, and ran into the same issue. So it does seem that even loading across sub-domains is NOT allowed, which isn't all that surprising the more I think about it lol
