### ISSUE TITLE
Edge browser does not render pdf files properly

### ISSUE THREAD

**Issue by qwaszx1230** [wojtekmaj/react-pdf#294]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**
    1：Rendering with cavans Part of the pdf can't be rendered normally, the display is not complete
    2：Using svg rendering mode, there will be garbled problems
    3：Part of the pdf can be rendered normally for the first time, and the second rendering will prompt "failed to load pdf file"

**Environment**
 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
   
 ![image](https://user-images.githubusercontent.com/22724660/47626534-92275b00-db66-11e8-85c4-ac498993ed5b.png)
 - React-PDF version:3.0.5
 - React version:16.5.2

The code (for webpack 4) looks like this:

```js
import * as React from "react";
import { Document, Page, setOptions } from "react-pdf/dist/entry.noworker";

export interface IAkPdfViewerProps {
    fileUrl?: string;
}

export interface IAkPdfViewerStates {
    fileUrl?: string;
    pageIndex: number;
}

export class AkPdfViewer extends React.Component<IAkPdfViewerProps, IAkPdfViewerStates>{
    constructor(props, context) {
        super(props, context);
        this.state={
            pageIndex:1
        }
        setOptions({
            cMapUrl: window["CDN"] + "js/pdfjs/cmaps/",
            cMapPacked: true,
        })
    }
    componentWillReceiveProps(nextProps) {
        if ("fileUrl" in nextProps && nextProps.fileUrl !== this.props.fileUrl) {
            this.setState({ fileUrl: nextProps.fileUrl });
        }
    }
    render() {
        const { pageIndex } = this.state;
        return <Document
        options={{
            cMapUrl: window["CDN"] + "js/pdfjs/cmaps/",
            cMapPacked: true,
        }}
        file={this.state.fileUrl}>
        <Page
            pageNumber={pageIndex}
            // renderMode="svg"
            renderTextLayer={true}
            renderAnnotations={true}
            />
    </Document>
    }
}
```

**Comment by wojtekmaj** [comment]
I don't see anything wrong with the code, apart from useless componentWillReceiveProps (you can just take fileUrl from props) and useless `options` object in `Document` (it's a way to set options in React-PDF 4.x, not 3.x.

Can you provide some screenshots or attach a PDF file that renders badly?

**Comment by urijah** [comment]
Browser is Edge as stated in the title, or IE11, as shown in the ticket body?  @qwaszx1230

**Comment by wojtekmaj** [comment]
Please also mind that **In React-PDF, there are some confirmed compatibility issues with Webpack 4** (see: #179).
