### ISSUE TITLE
Upgrade to v2.0.943 pdf.js version

### ISSUE THREAD

**Issue by valerii-cognite** [wojtekmaj/react-pdf#295]
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

It seems the new [v2.0.943](https://github.com/mozilla/pdf.js/releases/tag/v2.0.943) release of pdf.js contains a lot of great features, would be great to have them in `react-pdf`.

**Describe the solution you'd like**

Upgrade to a newer version

**Comment by wojtekmaj** [comment]
I'm monitoring this and expecting to release it with this update this week. So far the version you're talking about is not out on mom, Mozilla has some issues releasing:
https://www.npmjs.com/package/pdfjs-dist

**Comment by valerii-cognite** [comment]
Ok, I see, thank you for tracking those releases.

**Comment by wojtekmaj** [comment]
For more details, future news on that topic and to get notified when 4.0.0 is officially release please head to #269
