### ISSUE TITLE
Error: The API version does not match the Worker version 

### ISSUE THREAD

**Issue by SachaG** [wojtekmaj/react-pdf#297]
Making a note of this in case it helps others. I had the following error:

```
"The API version "2.0.943" does not match the Worker version "2.0.550"."
```

It turned out that `pdfjs` had been upgraded to a new minor version at some point, and the `pdf.worker.js` file I had manually copied to another location had gotten out of date. Took me a while to figure out because I knew I hadn't upgraded `react-pdf` itself.

**Comment by scottie-schneider** [comment]
Thanks for this. I needed to dig a bit further to solve this particular issue.
I'm using Next.js and can't use the normal worker import process, so need to use a CDN.

[React-PDF's documentation](https://www.npmjs.com/package/react-pdf)
"Alternatively, you could use pdf.worker.js from an external CDN:
import { pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`"

I found the correct CDN Version here:
https://cdnjs.com/libraries/pdf.js/2.1.266
