### ISSUE TITLE
Failed prop type: Cannot read property 'numPages' of undefined

### ISSUE THREAD

**Issue by anking** [wojtekmaj/react-pdf#298]
Just using the code from example I'm coming up with the following error:

> Warning: Failed prop type: Cannot read property 'numPages' of undefined
    in PageInternal (created by Context.Consumer)
    in Page (at ClosingProduct.js:1108)
    in div (created by Document)
    in Document (at ClosingProduct.js:1104)
    in div (at ClosingProduct.js:1103)
    in div (at ClosingProduct.js:1096)
    in div (at ClosingProduct.js:1087)
    in div (at ClosingProduct.js:1086)
    in TestSignComponent (at ClosingProduct.js:56)
    in div (at Home.js:151)
    in div (at Home.js:142)
    in Home (created by Route)
    in Route (at App.js:13)
    in div (at Layout.js:10)
    in Layout (at App.js:10)
    in App (at src/index.js:28)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:27)

However when the document is loaded the page numbers are being displayed correctly

`
    onDocumentLoad = ({ numPages }) => {
             this.setState({ numPages });
        }

    <div><button onClick={this.pagePrev}>Previous</button>Page {this.state.pageNumber} of {this.state.numPages}<button onClick={this.pageNext}>Next</button></div>

                        <div style={{position:relative}} className="noselect">
                            <Document
                                file={this.state.loadedPdf}//{this.state.loadedPdf}
                                onLoadSuccess={this.onDocumentLoad}
                            >
                                <Page pageNumber={this.state.pageNumber} scale={1.5} />
                            </Document>
                        </div>`

**Comment by idavidasilva** [comment]
I was having problem with webpack and version 3.0.5 (stable) when compiling `pdfjs` so I upgraded to 4.0.0-beta.5 and the compilation now works fine. I am getting also this error. But the document loads and works as expected for me too.

React-PDF = 4.0.0-beta.5
Pdfjs-Dist = 2.0.943

Let's wait for a fix. :)

**Comment by wojtekmaj** [comment]
How come you're on pdfjs-dist 2.0.943? Required version for React-PDF is 2.0.550 at the moment.

**Comment by idavidasilva** [comment]
> How come you're on pdfjs-dist 2.0.943? Required version for React-PDF is 2.0.550 at the moment.

The package.json has `"pdfjs-dist": "^2.0.550"`, so it is allowed to do minor upgrades.

pdfjs-dist is now at 2.0.943. That's why the installed version here is 2.0.943 and not 2.0.550. To set a fixed version you have to remove `^` from package.json `"pdfjs-dist": "2.0.550"`, correct ? :)

Thanks for your amazing work. 👍

**Comment by wojtekmaj** [comment]
Yeah, Mozilla isn't really doing semver here, so there were breaking changed between 2.0.550 and 2.0.943. I must pin down the version to 2.0.550.

**Comment by wojtekmaj** [comment]
Hi all, I pinned down pdfjs-dist version to 2.0.550. From this point on, pdfjs-dist version will always be pinned down because of Mozilla's lack of commitment to semver standards. I apologize for the trouble React-PDF beta has caused to you.

React-PDF 4.0.0-beta.6 is now released.
