### ISSUE TITLE
InvalidPDFException {name: "InvalidPDFException", message: "Invalid PDF structure"

### ISSUE THREAD

**Issue by Puspendert** [wojtekmaj/react-pdf#300]
I am using `4.0.0-beta.5` but still I am getting `InvalidPDFException` for [this file](http://www.africau.edu/images/default/sample.pdf)
`InvalidPDFException {name: "InvalidPDFException", message: "Invalid PDF structure"`

My Component:
```
import React from "react"
import { Document, pdfjs } from "react-pdf"
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${ pdfjs.version }/pdf.worker.js`

class Sample extends React.Component {
  render(){
     return(
        <div>
          <Document file="/Users/laptop/Desktop/sample.pdf" />
        </div>
     )
  }
}
```
Also, there are lot of warning on console

_Originally posted by @Puspendert in https://github.com/wojtekmaj/react-pdf/issues/291#issuecomment-438381865_

**Comment by iSunRise** [comment]
You just can't read a file from local filesystem, try any remote pdf, for example: http://www.pdf995.com/samples/pdf.pdf

**Comment by Puspendert** [comment]
> You just can't read a file from local filesystem, try any remote pdf, for example: http://www.pdf995.com/samples/pdf.pdf

I am using URL now. CORS error was stopping me to fetch the PDF, so I disable CORS using [this extension](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi/related?hl=en).
But now, nothing is getting rendered

**Comment by SHAPPY0** [comment]
Hi, 
Did you solved this issue?
I am also facing the same error. Please let me know the solution if you had fixed it.

**Comment by jp3492** [comment]
Im having the same issues and getting really desperate in trying to view pdfs in my React app. Maybe i need to eject my CRA to make this possible?

**Comment by SHAPPY0** [comment]
@jp3492 , I used pdf-image instead 'react-pdf' and its working fine for me.

**Comment by wojtekmaj** [comment]
Check if you can open this PDF file in Firefox. Firefox uses the same engine to render PDFs as we do in React-PDF.
If you can open the file just fine in Firefox, open your website and check in Network tab in Developer Tools, if you are *actually* downloading a file you're requesting, or as @Puspendert suggested you are hitting a CORS issue and end up getting an invalid/empty PDF file.

**Comment by Gui-Alucard** [comment]
Guys, react-pdf accepts only http protocols. So, if you are testing any pdf on your machine, the browser URL will likely be "file: //home/myComputer/localOfFiles/myPdf.pdf" and the correct path should be "http://localhost:3000/myPdf.pdf".

You don't need to use any extension or anything else, you just move a file.pdf to your public folder in React code and try this path "http://localhost:3000/myPdf.pdf" to see if your browser will render something. 

Here is some sample code:
```tsx
// ...previous code
    const local = `http://localhost:3000/original.pdf`

              <Document
                  file={local}
                  // file={server}
                  onLoadSuccess={this.onDocumentLoadSuccess}
                  options={{ workerSrc: `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js` }}
                >
                  <Page pageNumber={pageNumber} width={600} />
                </Document>

// ...rest of code
```

**Comment by bottxiang** [comment]
Try this `import file from './x.pdf';`
```javascript
import React, { useState } from 'react';
import { Document, Page } from 'react-pdf';
import file from './x.pdf';
export default function MyApp() {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  return (
    <div>
      <Document
        file={file}
        onLoadSuccess={onDocumentLoadSuccess}
      >
        <Page pageNumber={pageNumber} />
      </Document>
      <p>Page {pageNumber} of {numPages}</p>
    </div>
  );
}
```

**Comment by gayathri138** [comment]
<FileViewer fileType={type} filePath={'./Pbarn.pdf'} onError={onError}/>

save the file in public folder it works for me try this

**Comment by gayathri138** [comment]
const type = "pdf";

**Comment by mikelm23** [comment]
Hi all,

I recently updated the version from 9.1.0 to **9.2.0**, but I'm encountering an error in the console.
The PDF is coming from the server in base64 format.

The PDF view is rendering, but I get the following error in the console:
`InvalidPDFException: Invalid PDF structure. Error Component Stack`

I also tried converting the base64 to a Uint8Array, but the error persists.
What can I do to resolve this?

Here’s the relevant code snippet:

```
<Document
      file={`data:application/pdf;base64,${pdfData}`}
      onLoadSuccess={onDocumentLoadSuccess}
 >
     {Array.from(new Array(numPages), (el, index) => (
         <Page
            key={`page_${index + 1}`}
            pageNumber={index + 1}
            renderTextLayer={false}
            renderAnnotationLayer={false}
         />
      ))}
</Document>
```
