### ISSUE TITLE
loading prop of Page doesn't take in React element

### ISSUE THREAD

**Issue by up209d** [wojtekmaj/react-pdf#301]
I got this error when trying to put a React element into `loading` prop of `Page`. Per guide from React-pdf, it is supposed to be possible to do that. Did anyone get this problem?

```
<Page
    loading={<div>HELLO WORLD</div>}
    renderMode={'canvas'}
    pageNumber={state.pageNumber}
    onRenderSuccess={this.onPageRenderSuccess}
    renderTextLayer={false}
    scale={1}
    width={600}
/>
```

`Warning: Failed prop type: Invalid prop `loading` of type `object` supplied to `Page`, expected `string`.`

**Environment**

 - React-PDF version 3.0.5:
 - React version 16.6.1:
 - Webpack version 4.5.0

**Comment by wojtekmaj** [comment]
That was fixed in 7de2327ad1a48dbf39bc61a1b6d0279d2fa9cc85 via #293 but is not yet released.
I encourage you to try React-PDF 4.x beta which was released with this fix already!
