### ISSUE TITLE
Cannot install: permission denied, mkdir

### ISSUE THREAD

**Issue by manuelmager** [wojtekmaj/react-pdf#302]
**Before you start - checklist**

 - [X] I followed instructions in documentation written for my React-PDF version
 - [X] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

`npm install --save react-pdf` fails. I am not sure what is causing it, as it only fails on our development servers (user has no sudo permission), but works locally (having sudo permission). There are no globally installed npm packages (`npm list -g` returns empty). Any other information that might be helpful?

**Steps to reproduce**

1. Run `npm install --save react-pdf`

**Expected behavior**

React-pdf gets installed successfully.

**Environment**

 - Browser (if applicable): none
 - React-PDF version: 3.0.5
 - React version: 16.0.0
 - Webpack version: 3.7.1

**Additional information**

The application is run by user `frontend`.
Permissions:
`drwxrwxr-x 744 frontend frontend  36864 Nov 15 11:01 node_modules`
.. within node_modules, permissions are similar to:
`drwxrwxr-x  5 frontend frontend   4096 Nov 15 11:01 uglifyjs-webpack-plugin`

Output of `npm install --save react-pdf`:
```
17653 silly extract react-pdf@3.0.5
17654 silly pacote trying react-pdf@https://registry.npmjs.org/react-pdf/-/react-pdf-3.0.5.tgz by hash: sha1-xxx
...
17754 http fetch GET 200 https://registry.npmjs.org/react-pdf/-/react-pdf-3.0.5.tgz 338ms
...
17817 verbose unlock done using /home/frontend/.npm/_locks/staging-1f5bdb92c13111f7.lock for /home/frontend/instances/frontend_dev2/releases/20181115092614/node_modules/.staging
17818 warn 20181115092614 No repository field.
17819 warn 20181115092614 No license field.
17823 verbose stack Error: EACCES: permission denied, mkdir '/home/frontend/instances/frontend_dev2/releases/20181115092614/node_modules/.staging/react-pdf-e71dc602/coverage'
17823 verbose stack     at Error (native)
17824 verbose cwd /home/frontend/instances/frontend_dev2/releases/20181115092614
17825 verbose Linux 4.15.0-29-generic
17826 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "react-pdf"
17827 verbose node v6.14.4
17828 verbose npm  v5.0.3
17829 error path /home/frontend/instances/frontend_dev2/releases/20181115092614/node_modules/.staging/react-pdf-e71dc602/coverage
17830 error code EACCES
17831 error errno -13
17832 error syscall mkdir
17833 error Error: EACCES: permission denied, mkdir '/home/frontend/instances/frontend_dev2/releases/20181115092614/node_modules/.staging/react-pdf-e71dc602/coverage'
17833 error     at Error (native)
17833 error  { Error: EACCES: permission denied, mkdir '/home/frontend/instances/frontend_dev2/releases/20181115092614/node_modules/.staging/react-pdf-e71dc602/coverage'
17833 error     at Error (native)
17833 error   cause:
17833 error    { Error: EACCES: permission denied, mkdir '/home/frontend/instances/frontend_dev2/releases/20181115092614/node_modules/.staging/react-pdf-e71dc602/coverage'
17833 error        at Error (native)
17833 error      errno: -13,
17833 error      code: 'EACCES',
17833 error      syscall: 'mkdir',
17833 error      path: '/home/frontend/instances/frontend_dev2/releases/20181115092614/node_modules/.staging/react-pdf-e71dc602/coverage' },
17833 error   errno: -13,
17833 error   code: 'EACCES',
17833 error   syscall: 'mkdir',
17833 error   path: '/home/frontend/instances/frontend_dev2/releases/20181115092614/node_modules/.staging/react-pdf-e71dc602/coverage' }
17834 error Please try running this command again as root/Administrator.
17835 verbose exit [ -13, true ]
```

**Comment by manuelmager** [comment]
Updated to node 8.12.0 & npm 6.4.1, seems to work now.

**Comment by wojtekmaj** [comment]
It looks like an mom issue, not package issue.

**Comment by manuelmager** [comment]
Seems updating npm via operating system is not sufficient: `npm install npm@latest -g` did the trick. Thank you for having a look @wojtekmaj!
