### ISSUE TITLE
IE11 throwing error 'Warning: setState(…): Cannot update during an existing state transition....'

### ISSUE THREAD

**Issue by abelmark** [wojtekmaj/react-pdf#303]
**What are you trying to achieve? Please describe.**

I am trying to display links to download or preview the PDF then display it in a lightbox.  Preview links do in fact show a snapshot of the PDF, but when opened in the lightbox this error is thrown.  Works as expected in Chrome.

**Describe solutions you've tried**

Changing how I import the library, using service workers vs. not using service workers.  It behaves as expected in Chrome, but in IE11 the PDF just straight up doesn't show up.

**Additional information**

GOOD:
<img width="1283" alt="screen shot 2018-11-21 at 10 01 06 am" src="https://user-images.githubusercontent.com/8964333/48849451-6453c180-ed74-11e8-9414-466f70f61735.png">

BAD:
<img width="1276" alt="screen shot 2018-11-21 at 10 00 27 am" src="https://user-images.githubusercontent.com/8964333/48849412-4dad6a80-ed74-11e8-938e-199852edc9cf.png">

**Environment**

 - IE11 ran on a PC and in a VMware virtual environment
 - React-PDF version [e.g. 3.0.4]: 3.0.5
 - React version [e.g. 16.3.0]: 15.5.4
 - Webpack version (if applicable) [e.g. 4.16.2]: 2.4.1

**Comment by wojtekmaj** [comment]
@abelmark Since you closed that, would you share your fix for the next person to have this issue?

**Comment by abelmark** [comment]
Of course!

Make sure you follow the directions on how to set it up properly. This was total user error. I was maintaining a codebase that used an object tag to display PDFs on every browser but IE hence why it was only broken on IE. DOH!
