### ISSUE TITLE
File Prop Equality Check 

### ISSUE THREAD

**Issue by samcooke98** [wojtekmaj/react-pdf#308]
**Before you start - checklist**

 - [ x] I followed instructions in documentation written for my React-PDF version
 - [ x] I have checked if this bug is not already reported
 - [ x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

Short description of the bug you encountered.

In React PDF v3, the comparison check for updating the PDF was done deeply, if the file prop was an object. This is not the case in React PDF v4, and this results in an infinite update if the object passed as a prop to filename is created in the render function... 

**Steps to reproduce**
I can provide this later, but basically try to render a PDF with an object for the filename, and create the object in the render function. 

**Expected behavior**

I expected it to function the same as React-PDF v3, where it would only update if the underlying value change 

**Additional information**

I'm happy to provide a pull-request, if this is an unintended side-effect, as well as a test case demonstrating this. 

**Environment**

 - React-PDF version [e.g. 3.0.4]: 4.0.0
 - React version [e.g. 16.3.0]: 16.6.0
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.23.1

**Comment by wojtekmaj** [comment]
Generally, creating props on the fly during render is not a good idea. The best way to avoid it would be to create an object when you get the file data, assign it for example to state, and keep passing it as a prop in render function.

If you use an object which is referentially unequal on each render, it will result in less than ideal loading process, and I give you that. There's a room for improvement there.

Passing a referentially unequal object will cause Document component to check its props, and update itself as `file` props is, well, referentially unequal. This causes the file to be loaded again. Loaded file has its fingerprint - we compare the fingerprints and at this point decide whether or not we should update the Document component state.

I'll be looking into that more in the coming weeks.
