### ISSUE TITLE
Module not found: Error: Can't resolve 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by kozubikmichal** [wojtekmaj/react-pdf#310]
Hi,

I'm facing build error propably due to babel versions conflict.

This is output from Webpack:

```
ERROR in ./node_modules/pdfjs-dist/lib/web/ui_utils.js
Module not found: Error: Can't resolve 'babel-runtime/regenerator' in 'C:\Users\******\repos\la_client\node_modules\pdfjs-dist\lib\web'
 @ ./node_modules/pdfjs-dist/lib/web/ui_utils.js 29:19-55
 @ ./node_modules/pdfjs-dist/lib/web/pdf_link_service.js
 @ ./node_modules/react-pdf/dist/LinkService.js
 @ ./node_modules/react-pdf/dist/Document.js
 @ ./node_modules/react-pdf/dist/entry.js

```

I found this issue https://github.com/mozilla/pdf.js/issues/10280 so if I get it right this will be fixed with new version of pdfjs-dist.
But according to info/issues on react-pdf project it seems that for some people it is already working now with pdfjs-dist 2.0.943. Is there any additional step to make this working?

**Environment**

 - React-PDF version: 4.0.0
 - React version: 16.6.3
 - Webpack version: 4.26.1

Regards
Michal

**Comment by wojtekmaj** [comment]
I guess you could `npm i babel-runtime` or `yarn add babel-runtime` in the meantime, which would add the missing module and stop the error from happening. I updated pdfjs-dist to Babel 7 in mozilla/pdf.js#10293. Babel 6 or 7 though, doesn't really matter, I think this means babel-runtime is required by pdfjs-dist and as such should be listed in dependencies.

**Comment by rogordan** [comment]
I have a similar issue. If I add babel-runtime manually it causes an issue with duplicate packages because there is babel-runtime/regenerator and @babel/runtime/regenerator. My build only succeeded when I went into pdfjs and manually pasted the path to my @babel/runtime/regenerator. I think the less hacky hack would be to use webpack aliasing to resolve the right runtime-regenerator, but I can't figure that out.

I guess I'm wondering if there's some other way to address this.

**Comment by wojtekmaj** [comment]
Hi all,
this should be fixed with the next release.
Thanks for your patience.

**Comment by ebongso** [comment]
Thanks @wojtekmaj. We encountered the same issue today and did `npm i --save-dev babel-runtime`. The problem was resolved.

**Comment by allanchua101** [comment]
We also experienced same issue today. Using ```npm i --save-dev babel-runtime``` fixes the problem, but is it the best way to work around it?

**Comment by wojtekmaj** [comment]
@allanchua101 _that_ is the best way to work around it ;) Mozilla is about to release a new version of PDF.js though, so this workaround should no longer be needed soon.

**Comment by wojtekmaj** [comment]
All, React-PDF 4.0.3 is out and should have this issue resolved.

**Comment by benabbon** [comment]
I still have the error with React-PDF 4.0.3. Only now, I can't silence it anymore by adding babel-runtime as a dependency. This makes 4.0.3 unusable and have to stick with 4.0.2 and the babel-runtime workaround.

**Comment by wojtekmaj** [comment]
@benabbon Is that the exact error you're getting, or it mentions `@babel/runtime`?

**Comment by benabbon** [comment]
@wojtekmaj I created a seperate issue with more details, the error I get is : 
Module not found: Can't resolve '@babel/runtime/regenerator'

**Comment by sensoeurn** [comment]
****** My error :

This dependency was not found:

* babel-runtime/regenerator in ./node_modules/pdfjs-dist/lib/web/ui_utils.js

To install it, you can run: npm install --save babel-runtime/regenerator

****** after I run the commad => npm i --save-dev babel-runtime

It works for me
