### ISSUE TITLE
Error during font loading: unexpected EOF in bcmap

### ISSUE THREAD

**Issue by zhouyize** [wojtekmaj/react-pdf#312]
Warning: Indexing all PDF objects;
Warning: Unknown type 1 charstring command of "0";
Warning: Error during font loading: unexpected EOF in bcmap

**Comment by zhouyize** [comment]
Thank you so much for your response, I have added the pdf file. The pdf file displayed incorrectly with messy code, I don't know why the warning happened.
[Delphi5.pdf](https://github.com/wojtekmaj/react-pdf/files/2637717/Delphi5.pdf)

**Comment by wojtekmaj** [comment]
Passed to mozilla/pdf.js as it's their code which throws this warning. Track under: mozilla/pdf.js#5790
