### ISSUE TITLE
While installing npm install react-pdf after run the code i am getting this issue "TypeError: Cannot set property 'workerSrc' of undefined" Could you please help me what is the issue.?

### ISSUE THREAD

**Issue by niteshshah04** [wojtekmaj/react-pdf#313]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [ ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.

**Describe solutions you've tried**

Describe solutions you've already tried, if any. Make sure to include code samples if you're stuck on implementation.

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by niteshshah04** [comment]
![image](https://user-images.githubusercontent.com/9703082/49336371-00a87e80-f627-11e8-9eb9-2f8dd87fc48e.png)

**Comment by moffsugita** [comment]
It is ugly solution but I resolved like below.

```
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
import { Document, Page, pdfjs } from 'react-pdf'
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`
``

**Comment by moffsugita** [comment]
`npm install --save-dev pdfjs-dist`

and

`pdfjs.GlobalWorkerOptions.workerSrc = 'node_modules/pdfjs-dist/build/pdf.worker.js';`

or
https://github.com/mozilla/pdf.js/issues/8305

**Comment by niteshshah04** [comment]
Thank You So Much for solution. Its working now.

**Comment by wojtekmaj** [comment]
Also resolved in #291

**Comment by jp3492** [comment]
I was having the same issues and following the suggestions in this issue im receiving a: InvalidPDFException {name: "InvalidPDFException", message: "Invalid PDF structure"} - error now.
If i use a url im getting a Cors issue.
Any suggestions? Im really struggeling to get this work in my React app (CRA, TypeScript)

**Comment by wojtekmaj** [comment]
@jp3492, this issue was exclusive to React-PDF 3.x. Try 4.x.

**Comment by charkhaniakash** [comment]
//  It will work Now  use this 

import { pdfjs } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = `//unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.js`;
