### ISSUE TITLE
Problem with rendering PDF using SVG rendering mode

### ISSUE THREAD

**Issue by Buzja** [wojtekmaj/react-pdf#316]
When React pdf components renders on page, with **svg rendering mode** , i see warnings like "Warning: Unimplemented graphic state SMask" and "Warning: Unimplemented graphic state BM", and i see errors: "Error: <svg:rect> attribute height: A negative value is not valid. ("-841.89")".
Herewith: Negative value of height === positive value of first page height.

![screenshot_2](https://user-images.githubusercontent.com/22001420/49603743-29b96e00-f99d-11e8-8c1a-2e69a2ff57cb.png)

Current versions of React(16.4.2), react-pdf(4.0.0):

![screenshot_3](https://user-images.githubusercontent.com/22001420/49603864-78670800-f99d-11e8-9144-b9b7b476ca66.png)
I see this problem in all browsers.

**Environment**

 - Browser: All browsers
 - React-PDF version: 4.0.0
 - React version: 16.4.2
 - Webpack version: 3.8.1

**Comment by wojtekmaj** [comment]
Hi,
this issue is related to PDF.js which React-PDF uses internally. Please report this issue to [mozilla/pdf.js](https://github.com/mozilla/pdf.js/), and make sure to include the PDF in question to help them resolve the issue.
