### ISSUE TITLE
componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: PDF, PDFMenu

### ISSUE THREAD

**Issue by gshilin** [wojtekmaj/react-pdf#317]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

Short description of the bug you encountered.
I've installed 4.0.0-beta.6. While running in StrictMode I've got the following error:
```
Warning: Unsafe lifecycle methods were found within a strict-mode tree: in StrictMode

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: PDF, PDFMenu
```

though this code should include #174 

**Steps to reproduce**

My code is copy-paste from documentation

**Expected behavior**

There should be no warning

**Additional information**

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Chrome Version 71.0.3578.80 (Official Build) (64-bit)
 - React-PDF version [e.g. 3.0.4]: 4.0.0-beta.6
 - React version [e.g. 16.3.0]: 16.6.3
 - Webpack version (if applicable) [e.g. 4.16.2]: creacte-react-application-2

**Comment by wojtekmaj** [comment]
I think you got the wrong library, there's no PDF or PDFMenu component in this package.
