### ISSUE TITLE
Can't load pdf using URL/Data parameter

### ISSUE THREAD

**Issue by moacsjr** [wojtekmaj/react-pdf#319]
I'm trying to load a PDF file using data object or URL but react-pdf only output "Loading PDF".
I'm listening for events onLoadSuccess, onLoadError, onRenderSuccess, onRenderError but only onLoadSuccess has being fired.

![image](https://user-images.githubusercontent.com/2759074/49757010-86b96a80-fca2-11e8-8bb5-cf4ae8d37e91.png)

I'm also trying to load using data parameter {data: UIntArray} loaded with a fetch request (cors checked)

![image](https://user-images.githubusercontent.com/2759074/49758998-8ff90600-fca7-11e8-8f67-2f0aee05623b.png)

This is the object passed as parameter

**
![image](https://user-images.githubusercontent.com/2759074/49755878-730d0480-fca0-11e8-9152-a71ba2b55bbd.png)
**

The url used in this example is public

React-PDF Document renders "Loading PDF ..."

Can someone help?

**Comment by AntoninMarchardDev** [comment]
I have the same issue. I provide a `Uint8Array` to the `file` props of the Document component like this 
```js
<Document
    file={{ data: file }}
 >
```

where file is a `Uint8Array`.
I try to log each method :  onLoadSuccess, onLoadError, onSourceError, onSourceSuccess.
Only `onSourceSuccess` is fired.

Do you have an idea about this issue ?

**Comment by wojtekmaj** [comment]
@AntoninMarchardDev See the bottom of #190

**Comment by nijellab** [comment]
I would add that you should store the Uint8Array file in the format { data: file } directly in the props otherwise you could face an issue where the page keeps rendering (Issue #308 )

**Comment by ali-garajian** [comment]
> I would add that you should store the `Uint8Array` file in the format `{ data: file }` directly in the props otherwise you could face an issue where the page keeps rendering (see issue #308 for more information on this topic).

OMG, you're a life savior!
I had the exact same issue, and I was this close to giving up and starting to implement the whole thing from the ground up with pdf.js =))
Thanks a million

**Comment by karljinang** [comment]
> I would add that you should store the `Uint8Array` file in the format `{ data: file }` directly in the props otherwise you could face an issue where the page keeps rendering (see issue #308 for more information on this topic).

YES! I also had this issue. This fixed the continuous rerendering problem.
