### ISSUE TITLE
NPM pointing to the alpha version

### ISSUE THREAD

**Issue by lorenzos** [wojtekmaj/react-pdf#32]
I don't know if you are planning to release 2.0 soon, but I noticed NPM downloads the `2.0.0-alpha.7` listed here as "Pre-release", while this repo's master branch point to `1.8.3` which is marked as "Latest release".

    $ npm install react-pdf
    $ cat node_modules/react-pdf/package.json | grep version
      "version": "2.0.0-alpha.7"

**Comment by wojtekmaj** [comment]
Hey,
I believe you are on npm 3.4.1+? They changed the way installing works when you don't specify version then. I read a lot of articles now on how to avoid this problem in the future, but frankly, I'm not sure what I should do with existing versions...
I am planning to release 2.0 very soon, though, yes :)

**Comment by lorenzos** [comment]
I'm using NPM 3.10.10, yes. No problem, I just wanted to be sure you were aware.

**Comment by wojtekmaj** [comment]
Hey @lorenzos, thank you so much for bringing this up. This has now been fixed. You can now use @latest and @next as you are expecting them to work. :)
