### ISSUE TITLE
fixing rendering for text layer out of page

### ISSUE THREAD

**Issue by SevenSinS02** [wojtekmaj/react-pdf#320]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

As you can see the text is clipped off. Is there anything that can be done to correct the rendering?

**Describe solutions you've tried**

**Additional information**
![snip20181211_1](https://user-images.githubusercontent.com/14374646/49779511-59b39900-fd30-11e8-8713-a267396bb5d7.png)
![snip20181211_3](https://user-images.githubusercontent.com/14374646/49779512-5a4c2f80-fd30-11e8-8536-82b2a6028cc2.png)

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: 70.0.3538.110
 - React-PDF version [e.g. 3.0.4]: 4.0.0-beta.5
 - React version [e.g. 16.3.0]: 16.6.3
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.19.1

**Comment by wojtekmaj** [comment]
Hi,
text layer is rendered on top of a single-layered, rendered PDF, so sadly there's nothing you could do to clip the text on the text layer.
