### ISSUE TITLE
Failed to load PDF file

### ISSUE THREAD

**Issue by saadpasta** [wojtekmaj/react-pdf#321]
i am having trouble showing pdf file tried every way from importing as file and directory giving path it is giving an error **Failed to load PDF file.** And When I am using webpack or parcel it just showing loading PDF.
### Code
```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { Document, Page } from 'react-pdf'
import lesson2 from './lesson2.pdf'
class App extends Component {
  state = { numPages: null, pageNumber: 1 };

  onDocumentLoadSuccess = ({ numPages }) => {
    this.setState({ numPages });
  };

  goToPrevPage = () =>
    this.setState(state => ({ pageNumber: state.pageNumber - 1 }));
  goToNextPage = () =>
    this.setState(state => ({ pageNumber: state.pageNumber + 1 }));

  render() {
    const { pageNumber, numPages } = this.state;

    return (
      <div>
        <nav>
          <button onClick={this.goToPrevPage}>Prev</button>
          <button onClick={this.goToNextPage}>Next</button>
        </nav>

        <div style={{ width: 600 }}>
          <Document
            file={lesson2}
            onLoadSuccess={this.onDocumentLoadSuccess}
          >
            <Page pageNumber={pageNumber} width={600} />
          </Document>
        </div>

        <p>
          Page {pageNumber} of {numPages}
        </p>
      </div>
    );
  }
}

export default App;
```

### Folder Structure 
![capture1](https://user-images.githubusercontent.com/23307811/49854995-be7bfb80-fde3-11e8-89d9-b82a66f94a30.PNG)

**Comment by wojtekmaj** [comment]
1. Check the console for errors
2. Plug in to onLoadError with `onLoadError={console.error}` to see additional messages
3. Check Network tab of devtools to ensure that PDF.js downloads the worker file from a correct URL

**Comment by MichaelBlanchet** [comment]
I have a very similar (simple) App.js - as per your description - and not able to load a PDF document. Getting the following errors:

Uncaught SyntaxError: Unexpected token <
index.js:1452 

Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".
    at pdf.js:10999
function.console.(anonymous function) @ index.js:1452
consoleOnDev @ utils.js:188
errorOnDev @ utils.js:207
(anonymous) @ Document.js:291
_callee$ @ Document.js:229
tryCatch @ runtime.js:62
invoke @ runtime.js:288
prototype.(anonymous function) @ runtime.js:114
asyncGeneratorStep @ asyncToGenerator.js:3
_throw @ asyncToGenerator.js:29
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
componentDidMount @ Document.js:435
commitLifeCycles @ react-dom.development.js:16722
commitAllLifeCycles @ react-dom.development.js:18160
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:18365
completeRoot @ react-dom.development.js:19894
performWorkOnRoot @ react-dom.development.js:19817
performWork @ react-dom.development.js:19722
performSyncWork @ react-dom.development.js:19696
requestWork @ react-dom.development.js:19551
scheduleWork @ react-dom.development.js:19358
scheduleRootUpdate @ react-dom.development.js:20062
updateContainerAtExpirationTime @ react-dom.development.js:20088
updateContainer @ react-dom.development.js:20156
push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20435
(anonymous) @ react-dom.development.js:20589
unbatchedUpdates @ react-dom.development.js:19939
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20585
render @ react-dom.development.js:20652
./src/index.js @ index.js:7
__webpack_require__ @ bootstrap:782
fn @ bootstrap:150
0 @ serviceWorker.js:135
__webpack_require__ @ bootstrap:782
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
4

webpackHotDevClient.js:120 ./node_modules/pdfjs-dist/build/pdf.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by pxFIN** [comment]
@saadpasta @MichaelBlanchet  I reckon you are using create-react-app as a boilerplate ?

Add/change these to your code

import { Document, Page, pdfjs } from "react-pdf";
 pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

as instructed on the main page of this project. Also make sure pdf file is to be found for your project (public directory)

**Comment by wojtekmaj** [comment]
@MichaelBlanchet 

> Uncaught SyntaxError: Unexpected token <

See #52

**Comment by LukaszGrela** [comment]
I had similar issue, in my case it was incorrect file to be loaded

```
const path = './data/sample.pdf'
```

in my localhost dev the path was calculated relative to the current route not the root but local web server instead of responding with `404` it was returning the index.html content which couldnt be parsed :)

In the network tab it was showing as `sample.pdf` which was confusing, but looking at response content disclosed that it was in fact a web page not PDF.

**Comment by jtibrewal09** [comment]
Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

link to codesandbox.
https://codesandbox.io/s/kkq9zv96jo

**Comment by wojtekmaj** [comment]
@jtibrewal09 #52 might help you, sounds like a worker issue.

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!

**Comment by gundojuprashanth** [comment]
Hi
I have issue in loading pdf. Its just showing Loading PDF.
![Screenshot (40)](https://user-images.githubusercontent.com/44726650/63939352-b99bcc80-ca84-11e9-8b52-28d4270235c2.png)

**Comment by turetran** [comment]
> @saadpasta @MichaelBlanchet I reckon you are using create-react-app as a boilerplate ?
> 
> Add/change these to your code
> 
> ```
> import { Document, Page, pdfjs } from "react-pdf";
>  pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
> ```
> 
> as instructed on the main page of this project. Also make sure pdf file is to be found for your project (public directory)

I see that using
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
resolved the issue: "Failed to load PDF file."

**Comment by jhaanji035** [comment]
I am using base64 string, But still it says : "Setting up fake worker failed: "Loading chunk 0 failed"

**Comment by johndevedu** [comment]
Hope this command helps someone. In create-react-app, the instructions for this libs say:

> you will have to make sure on your own that pdf.worker.js file from pdfjs-dist/build is copied to your project's output folder.

If your build process uses cli commands, (i.e. aws buildspec), you can use this:

`mkdir -p build && cp ./node_modules/pdfjs-dist/build/pdf.worker.js build`

**Comment by koellemichael** [comment]
Using https in front of the url seems to resolve the problem for me:
<code>pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;</code>

**Comment by maxlxq** [comment]
```
import React, { PureComponent } from 'react'
import { Document, Page, pdfjs } from 'react-pdf';
...
pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

export default class PDFView extends PureComponent {
  ...
}
```
works well for me.

**Comment by pwhipp** [comment]
Same problem. Two small pdfs that open fine in viewers. One hangs loading and the other (after adding onLoadError={console.error} switched from hanging on 'Loading PDF' to displaying "Failed to load PDF file" with 

```
Warning: Setting up fake worker.
vendors~pdfjsWorker.js:3 Uncaught SyntaxError: Unexpected token '<'
2react_devtools_backend.js:6 Error: Setting up fake worker failed: "Loading chunk 0 failed.
(missing: http://localhost:8000/vendors~pdfjsWorker.js)".
    at main.js?ts=1592286747:81
```
in the console window. I don't need workers - the files are only a few MB each.

**Comment by wojtekmaj** [comment]
@pwhipp You _do_ need workers - PDF.js no longer works properly without them, so neither does React-PDF. If you don't want to use external worker, you can also [manually copy PDF.js worker to your build folder](https://github.com/wojtekmaj/react-pdf/issues/321#issuecomment-562764749) & set `pdfjs.GlobalWorkerOptions.workerSrc` to point at it.

**Comment by pwhipp** [comment]
Thanks. After many hours  (webpack paths seem to make getting worker loading working properly crazy and I only need them to present a couple of little pdfs) I gave up and used the simpler but more limited https://github.com/ansu5555/pdf-viewer-reactjs.

I will come back to this if I have some other need that forces us to start using workers.

**Comment by wojtekmaj** [comment]
What pdf-viewer-reactjs is doing is essentially the same. Only difference is how you set worker - they do it like this:

```js
import pdfjs from 'pdfjs-dist'
import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry'

pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
```

You can totally do this in React-PDF too :)

**Comment by pwhipp** [comment]
Yes, thanks. They just did it out of the box.

**Comment by WildSaoFeng** [comment]
Thank you sooooo much for the solution! Same issue and same solution here!

**Comment by wojtekmaj** [comment]
Sorry - I noticed something and had to edit my comment. What ansu5555/pdf-viewer-reactjs is doing is actually wrong and will harm your application's performance.

**Comment by nevres** [comment]
For these that use CRA, and do not want to use CDN, as is my case, you can perform following steps:

1. Create script within package.json:
"copy-pdfjs-worker" : "cp ./node_modules/pdfjs-dist/build/pdf.worker.js public/scripts"
Here we copy from node modules into public/scripts folder. During the build this folder would be copied into build folder.

2. And register it as follows:
pdfjs.GlobalWorkerOptions.workerSrc = `${process.env.PUBLIC_URL}/scripts/pdf.worker.js`;

This solution would work for both npm build and npm start commands (CRA already existing scripts).

**Comment by ajbee07** [comment]
> _Note: This comment previously said that we can totally do what pdf-viewer-reactjs is doing, which was technically true, but here's why you shouldn't:_
> 
> In pdf-viewer-reactjs, they import Worker like this:
> 
> ```js
> import pdfjs from 'pdfjs-dist'
> import pdfjsWorker from 'pdfjs-dist/build/pdf.worker.entry'
> 
> pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
> ```
> 
> Unfortunately, this module exports nothing and consequently works as if you didn't set workerSrc at all. This is invalid, causes an error and a "fake" worker to be loaded. This is a behavior that's no longer supported because of performance issues that loading "fake" worker causes and is highly discouraged by pdf.js team.

aside from importing via cdn and the solution of @nevres , is there other way to just simply import the worker?

**Comment by myfairshare** [comment]
> ```
> import React, { PureComponent } from 'react'
> import { Document, Page, pdfjs } from 'react-pdf';
> ...
> pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
> 
> export default class PDFView extends PureComponent {
>   ...
> }
> ```
> 
> works well for me.

Thanks buddy,  I was going crazy, this worked for me!!

**Comment by vehbirestelica** [comment]
Failed to open PDF fixed, but now it's showing InvalidPDFException: 
InvalidPDFException {message: "Invalid PDF structure.", name: "InvalidPDFException"}
Anyone knows how to fix it??

**Comment by jzskca** [comment]
@ajbee07

If you're using [craco](https://github.com/gsoft-inc/craco), you can add a webpack rule to create the worker as a separate chunk. Then you can import it and assign it to `workerSrc`, and avoid using a CDN-hosted version.

```javascript
// craco.config.js
module.exports = {
    webpack: {
        configure: {
            module: {
                rules: [
                    {
                        test: /pdf\.worker\.js/,
                        loader: "file-loader",
                        options: {
                            name: "static/js/[name].[hash:8].[ext]",
                        },
                    },
                ],
            },
        },
    },
};
```

```javascript
import { Document, Page, pdfjs } from "react-pdf";
import pdfjsWorker from "pdfjs-dist/build/pdf.worker";

pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;
```

**Comment by wojtekmaj** [comment]
@jzskca I actually love your solution here. Experimented with it in #756.

**Comment by paulmcconico** [comment]
If using Webpack 5 and react-pdf ^v5.7.2 you can use the following:

```
// webpack.config.js
const CopyPlugin = require('copy-webpack-plugin');

export default {
  ...
  plugins: [
    new CopyPlugin({
      patterns: [
        {
          from: path.join(
            path.dirname(require.resolve('pdfjs-dist/package.json')),
            'legacy',
            'build',
            'pdf.worker.js',
          ),
          to: resolvePath('build/public/assets'), // your public directory here
        },
      ],
    }),
  ],
}
```

```
// pdf viewer.jsx
import React from 'react';
import { Document, Page, pdfjs } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = '/assets/pdf.worker.js';

class PDFViewer extends React.Component {
  <Document ...>
    ...
  </Document>
}
```

**Comment by saadhashmi** [comment]
Hi, i am facing a similar issue but i dont have a file in the repo structure. Instead i am upload a file using input element file. I have the file object throught he file handler. When i feed that file by doing URL.createObjectURL(fileObject) ... i am getting that error.

**Comment by lewisMachilika** [comment]
Please advise what I am missing here it is not working at all. The error is Failed to load PDF file.
```
import { useState } from 'react';
// import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
import { Document, Page, pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
const ReactPdf = ({url}) => {
	const [numPages, setNumPages] = useState(null);
	const [pageNumber, setPageNumber] = useState(1);

	const onDocumentLoadSuccess = ({ numPages }) => {
		setNumPages(numPages);
	};

	const goToPrevPage = () =>
		setPageNumber(pageNumber - 1 <= 1 ? 1 : pageNumber - 1);

	const goToNextPage = () =>
		setPageNumber(
			pageNumber + 1 >= numPages ? numPages : pageNumber + 1,
		);

	return (
		<div>
			<nav>
				<button onClick={goToPrevPage}>Prev</button>
				<button onClick={goToNextPage}>Next</button>
				<p>
					Page {pageNumber} of {numPages}
				</p>
			</nav>

			<Document
				file="../assets/pdf/statement.pdf"
				onLoadSuccess={onDocumentLoadSuccess}
			>
				<Page pageNumber={pageNumber} />
			</Document>
		</div>
	);
};

export default ReactPdf;
```

**Comment by johnbabu021** [comment]
yes it worked for me

**Comment by kishore-s-15** [comment]
> @saadpasta @MichaelBlanchet I reckon you are using create-react-app as a boilerplate ?
> 
> Add/change these to your code
> 
> ```js
> import { Document, Page, pdfjs } from "react-pdf";
> pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
> ```
> 
> as instructed on the main page of this project. Also make sure pdf file is to be found for your project (public directory)

This worked for me. The issue occurred with the Codesandbox react typescript template.

**Comment by codiejay** [comment]
@saadhashmi please what do i do i if I wanted to load the PDF that doesnt exist on my file structure but a file on the internet like this one: https://www.africau.edu/images/default/sample.pdf 

This is what my code currently looks like: 

```<Document onLoadError={console.error} file="https://www.africau.edu/images/default/sample.pdf" onLoadSuccess={() => {console.log("ok")}}>
        <Page pageNumber={1} />
      </Document>```

**Comment by wojtekmaj** [comment]
@codiejay Looks like you may be dealing with what's explained in FAQ: https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions#when-im-trying-to-load-a-pdf-file-from-an-external-source-im-given-a-message-failed-to-load-pdf-file

**Comment by yagnesh16697** [comment]
![image](https://user-images.githubusercontent.com/40670389/206199531-ef604a1b-381e-4e4c-8a6e-3105ccdf0c41.png)

Working fine as separate app but getting this error while importing this app as npm package inside different app.

**Comment by zeus-singlifeph** [comment]
Hi @wojtekmaj i have a protected pdf file but the password has a `Ñ` and it stuck on the loading  and for my another file with no `Ñ` it's working do you have an idea on this issue? T.I.A

**Comment by keremcanb** [comment]
> For these that use CRA, and do not want to use CDN, as is my case, you can perform following steps:
> 
> 1. Create script within package.json:
>    "copy-pdfjs-worker" : "cp ./node_modules/pdfjs-dist/build/pdf.worker.js public/scripts"
>    Here we copy from node modules into public/scripts folder. During the build this folder would be copied into build folder. This script is manually triggered.
> 2. And register it as follows:
>    pdfjs.GlobalWorkerOptions.workerSrc = `${process.env.PUBLIC_URL}/scripts/pdf.worker.js`;
> 
> This solution would work for both npm build and npm start commands (CRA already existing scripts).

I followed this example. I only changed "copy-pdfjs-worker" with "prebuild" and it seems to work.

**Comment by wandersonce** [comment]
> @saadpasta @MichaelBlanchet I reckon you are using create-react-app as a boilerplate ?
> 
> Add/change these to your code
> 
> ```js
> import { Document, Page, pdfjs } from "react-pdf";
> pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
> ```
> 
> as instructed on the main page of this project. Also make sure pdf file is to be found for your project (public directory)

worked perfectly! thanks

**Comment by preveenraj** [comment]
For CRACO, 
This worked for me.

I used the version:
`"react-pdf": "5.0.0"`

```
import React, { useState } from 'react';
import { pdfjs, Document, Page } from "react-pdf/dist/esm/entry.webpack";

pdfjs.GlobalWorkerOptions.workerSrc = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  window.location.href,
).toString();

```

**Comment by feri-irawan** [comment]
> @saadpasta @MichaelBlanchet I reckon you are using create-react-app as a boilerplate ?
> 
> Add/change these to your code
> 
> ```js
> import { Document, Page, pdfjs } from "react-pdf";
> pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
> ```
> 
> as instructed on the main page of this project. Also make sure pdf file is to be found for your project (public directory)

I just tried this but error 404, i solved this error using jsdlivr
```ts
pdfjs.GlobalWorkerOptions.workerSrc = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`
```

**Comment by wojtekmaj** [comment]
> I just tried this but error 404

That's because "pdf.worker.js" changed to "pdf.worker.min.mjs" in the recent React-PDF update.

**Comment by marcioj-io** [comment]
Hi, you can do it this way:

The issue occurs because, in React, files in the public folder should be referenced directly as relative URLs, without using import. Instead of:

`import cvPDF from '../../../public/assets/cv.pdf';` 

You can simply use a relative URL in the downloadPDF function:

```
const downloadPDF = () => {
  const link = document.createElement('a');
  link.href = '/assets/cv.pdf'; // Relative path to the public folder
  link.download = 'CV-MJ-Full-Stack.pdf';
  link.click();
};
```

This way, React won't attempt to resolve the path dynamically, and it will directly fetch the file from the public folder.

**Comment by cotwitch** [comment]
I just can't believe how many people, without any worries, rely on external resources? I know it's a `cloudflare` and `jsdelivr` ... but anyway 🙄
