### ISSUE TITLE
Width prop is not multiplied by given scale

### ISSUE THREAD

**Issue by alexnez96** [wojtekmaj/react-pdf#322]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

I found a strange behavior, which I'm not sure is a bug or simply the readme is out of sync with the latest release. From the readme,

> If you define width and scale at the same time, the width will be multiplied by a given factor.

However, using the [multi-page example](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages) from Wiki, when I supply _both_ `width` (or `height`) and `scale` to `<Page />`, the `scale` seems to be ignored. In other words, the `width` does **not** get adjusted.

**_See [this sandbox](https://codesandbox.io/s/yqv4xl39x1) for a quick demo._**

**Steps to reproduce**

1. Use [this template](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages) from wiki
2. Pass both `width` and `scale`
```js
<Page
  key={`page_${index + 1}`}
  pageNumber={index + 1}
  width={800}
  scale={2}
/>
```
3. See the page doesn't get scaled

**Expected behavior**

The page width should be magnified x2 times.

**Actual behavior**

The page remains at the default `scale` of `1.0`.

**Additional information**

Note that when `scale` is used on its own, i.e. without `width` or `height`, the page gets scaled, as expected. As a workaround, I have to apply the scale manually, e.g.
```js
<Page
  key={`page_${index + 1}`}
  pageNumber={index + 1}
  width={800 * 2}
  scale={2}
/>
```
Also, same behavior with both `canvas` and `svg` `renderMode`.

**Environment**

 - Browser: any
 - React-PDF version: `^4.0.0`
 - React version: `^16.6.3`
 - Webpack version: `^4.27.1`

**Comment by alexnez96** [comment]
@wojtekmaj Could I ask for your input on this? :-)

**Comment by wojtekmaj** [comment]
Hi, thanks for your report. This has been fixed - expect it to be out with the next release. Sorry for the delay!
