### ISSUE TITLE
Failed to Load Pdf via URL

### ISSUE THREAD

**Issue by VikramMarsh** [wojtekmaj/react-pdf#323]
Hi Wojciech Maj,

I went through the issues related to CORS.

Need your advise in this.

I am using Node as my back-end server serving my index.html at 3000(using webpack) port where i am using react-pdf in one of my component.

URL which i am loading is from other Domain.

I tried enabling CORS from express .

**app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});**

It still throws error.

But when I enable CORS from chrome extension it works.

Hows that possible!!!??

Thanks

**Comment by wojtekmaj** [comment]
It's the domain you're requesting from that need to have these headers, not yours.

**Comment by kapso** [comment]
I am running into a similar issue `No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` 

...and tried adding the above headers in the response from the server, but no luck.

In our case, we are loading the PDF from a public URL on a Google (domain) server, so basically have no control over that server. Is that even possible?

Thanks

**Comment by wojtekmaj** [comment]
No it's not. You need to have control over the server.

Read more here: https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions#when-im-trying-to-load-a-pdf-file-from-an-external-source-im-given-a-message-failed-to-load-pdf-file
