### ISSUE TITLE
Get warning Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 253"

### ISSUE THREAD

**Issue by leonHk** [wojtekmaj/react-pdf#325]
HI, 
I have a Jersey Backend REST service to get the PDF from server to Client.
I set the response to React state so that this will not retrieve the PDF from backend again in state changed.
However, I got the error Warning: Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 253" in loading that PDF to Document. All content of PDF are lost.

May I know how to solve this?

Below is my code:

Server
```
        @Override
        @GET
        @Path("/pdf")
        @Produces(MediaType.APPLICATION_PDF_VALUE)
public Response testPdf() throws Exception {

    File file = new File("C:\\Desktop\\test.pdf");
    FileInputStream fileInputStream = new FileInputStream(file);

    ResponseBuilder response = Response.ok((Object) fileInputStream);
    response.type("application/pdf");
    response.header("Content-Disposition", "filename=test.pdf");

    return response.build();
}
```

Client

````
        import React, { Component } from 'react'; 
        import { Document, Page } from 'react-pdf';
        import axios from 'axios';

      class MyApp extends Component {
         state = {
             numPages: null,
            pageNumber: 1,
           pdfContent: null
       }

    componentDidMount(){
        var that = this;

        axio.get("url\Pdf).then((response) => {
             that.setState({pdfContent: response });
        }).catch((error) => {
             console.warn(error);
        });
    }

    onDocumentLoadSuccess = ({ numPages }) => {
        this.setState({ numPages });
    }

       printHandler(){
           window.print();
      }

      render() {
          const { pageNumber, numPages } = this.state;

      return (
          <div>
             <Document
                file={this.state.pdfContent}
                onLoadSuccess={this.onDocumentLoadSuccess}
             >
                 <Page pageNumber={pageNumber} />
             </Document>
             <p>Page {pageNumber} of {numPages}</p>

             <button onClick={() => this.setState(prevState => ({ 
                     pageNumber: prevState.pageNumber + 1 }))}>Next page</button>
             <button onClick={() => this.setState(prevState => ({ 
                     pageNumber: prevState.pageNumber - 1 }))}>Prev Page</button>

              <button onClick={this.printHandler}/>
          </div>
      );
} }
```

**Comment by wojtekmaj** [comment]
You're getting an error from [this line in PDF.js](https://github.com/mozilla/pdf.js/blob/6adeabbb66b8acf63dbd4e52f56a8cedfcfe21a4/src/core/stream.js#L418). Are you able to download the PDF generated by the server and open it in Adobe Reader and/or Firefox?

**Comment by leonHk** [comment]
Hi wojtekmaj,
Yes, I am able to open the PDF in Chrome. Also, PDF can display in react-pdf if I use direct url in file prop. e.g. <Doucment file = “http://domain/test/pdf” ...>

I don’t want to use url in file prop because this will retreive the PDF again if there is state changed to trigger render

**Comment by wojtekmaj** [comment]
Downloading a whole PDF just to display it in React-PDF is not a good idea - React-PDF supports partially downloading a PDF file, downloading only the pages it needs, to speed up loading time.

I don't know if I'll be able to help you here, unless you provide me with a valid PDF file that fails to load in React-PDF.  You have many 3rd party dependencies involved - some backend file streaming service, `axios` I don't know much about. The React part looks okay to me.

Besides, re-downloading a file shouldn't be the case, file should download once if source did not change 🤔

**Comment by leonHk** [comment]
In my case, the PDF is a report which will generate in server side and return to client to display using react-pdf. Therefore, the PDF may be different in different time.

You said  "re-downloading a file shouldn't be the case, file should download once if source did not change". Really??? I tested this before. This will retrieve the PDF from server again if re-rendered the component e.g. We press next button to next page, state numPages value changed. This will trigger render. In this case, I found the backend retrieve PDF service have called.

**Comment by wojtekmaj** [comment]
If the PDF may be different, I suggest using a hash in the URLs or just changing the filename each time the file is generated (which probably is a good idea because of caching).

React-PDF will definitely not re-download the same PDF twice, unless it's un-mounted and mounted again. We have tests for that in place. If the `file` prop remains the same, it won't start downloading the file again. There's nothing you need to config.

**Comment by leonHk** [comment]
Hi wojtekmaj. I found that If I code like this, the document will re-download.

` <Document
       file= {{ url: 'http://ce2-leon:8080/CMISonRampServerCommon/service/test/pdf', 
                 httpHeaders:  { 'authorization': 'Bearer .....'},
        }
>`

**Comment by wojtekmaj** [comment]
That's because you shouldn't create objects on the fly in render() function, see #308 for further discussion on that matter.

**Comment by leonHk** [comment]
hi wojtekmaj,
Is it mean that the PDF must re-download if I need to add http header to the url like my example?
Is it mean I must set the file data to state to avoid the PDF re-downloading?

In addition, is it possible to get the loaded file data from react-pdf if I using file = "http://localhost/pdf" ? because I want to implement a print function using the loaded pdf.

**Comment by wojtekmaj** [comment]
Please use #308 for questions regarding `file={{ ... }}` syntax. The solution for you problem is already there by the way.

Regarding the original issue, being "FormatError: Bad FCHECK":
* Check if your file loads in Firefox correctly
* If yes, try uploading it on React-PDF test page and check if it loads correctly
* If yes, the issue is with the 3rd party tools you're using to send/receive the data and/or your code.

**Comment by depiction** [comment]
I'm having the same problem. I'm getting the PDF from an API that returns an object with a data prop containing the file's binary.

![image](https://user-images.githubusercontent.com/2251157/52085191-cea59100-2571-11e9-889b-7ed459e1bcd0.png)

When I pass the entire object to Document as the file, I see multiple instances of `Warning: Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 253"` in the console. If I pass just the data as the file I get an error that the URL is bad.

I found the test page that you referred to (http://projekty.wojtekmaj.pl/react-pdf/test/). I'm not sure how to test the object on that page.

When I call my API in Postman, it returns a PDF that I'm able to open. I was able to upload that PDF to your test page without any problems. How do I resolve the format errors?

**Comment by depiction** [comment]
I finally figured out the problem. I fixed it by changing the response type on the API request that gets the file to 'blob'. The default is 'application/json'.

**Comment by LukaszGrela** [comment]
@depiction would you be able to describe in details what you did? I have similar issue with `Warning: Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 253"` messages in console log.
I'm sending (from PHP) the content of PDF file with the content type `application/octet-stream`.

**Comment by depiction** [comment]
As mentioned above, make sure the response type is set to 'blob'. Here is an example using Axios that calls an API, sets the response type, and create a blob url from the response.

`export function myService () {
  return axios.get('https://www.domain.com/api/, {
    responseType: 'blob',
    transformResponse: [function (data) {
      let blob = new window.Blob([data], { type: 'application/pdf' })
      return window.URL.createObjectURL(blob)
    }]
  })
}`

**Comment by LukaszGrela** [comment]
Thanks, I've in the end set the `responseType:'arraybuffer'` in `azios` config and then passed the `response.data` to the `Document`'s `file` prop as object `{data:...}`

```
    Axios.get('http://path/to/api', { responseType: 'arraybuffer' }).then(
      response => {
        this.setState(_ => ({ file: { data: response.data } }));
      }
    );
```

which then is used in `Document`
```
<Document file={this.state.file}
//...
```

**Comment by wojtekmaj** [comment]
So I guess this would be a solution for the OP. :) Thank you guys.

**Comment by mx4g** [comment]
> As mentioned above, make sure that the response type is set to 'blob'. Here is an example using Axios that calls an API, sets the response type, and creates a blob url from the response.
> 
> ```
> export function myService () {
>     return axios.get('https://www.domain.com/api/, {
>         responseType: 'blob',
>         transformResponse: [function (data) {
>             let blob = new window.Blob([data], { type: 'application/pdf' })
>             return window.URL.createObjectURL(blob)
>         }]
>     })
> }
> ```

Thank you

**Comment by mx4g** [comment]
> Thanks, I've in the end set the `responseType:'arraybuffer'` in `axios` config and then passed the `response.data` to the `Document`'s `file` prop as object `{data:...}`
> 
> ```
>     Axios.get('http://path/to/api', { responseType: 'arraybuffer' }).then(
>       response => {
>         this.setState(_ => ({ file: { data: response.data } }));
>       }
>     );
> ```
> 
> which then is used in `Document`
> 
> ```
> <Document file={this.state.file}
> //...
> ```

Thank you

**Comment by ynonra** [comment]
Thanks to you i also learned about _createObjectURL_ .. :) Thank guys!

**Comment by igloo1505** [comment]
> As mentioned above, make sure that the response type is set to 'blob'. Here is an example using Axios that calls an API, sets the response type, and creates a blob url from the response.
> 
> ```
> export function myService () {
>     return axios.get('https://www.domain.com/api/, {
>         responseType: 'blob',
>         transformResponse: [function (data) {
>             let blob = new window.Blob([data], { type: 'application/pdf' })
>             return window.URL.createObjectURL(blob)
>         }]
>     })
> }
> ```

For anyone coming across this issue now that next13 doesn't allow you to do something like:

```ts
const file = fs.createReadStream(pathToFile)
file.pipe(res)
```

The approach worked perfect. The whole flow looks like:

```ts
class SomeClass {
constructor(){}
    async getFile() {
        const res = await axios({
            method: "get", url: "/api/pdf",
            params: { file: this.file },
            responseType: 'blob',
            transformResponse: [function(data) {
                let blob = new window.Blob([data], { type: 'application/pdf' })
                return window.URL.createObjectURL(blob)
            }],
        })
        return res
    }
}
```

And then in the Next edge route:

```ts
const router = createEdgeRouter<NextRequest, RequestContext>();


router
    .get(async (req, ctx) => {
        try {
            const file = req.nextUrl.searchParams.get("file")
            if (!file) return new NextResponse(JSON.stringify({ success: false, toastError: "PDF was not found." }), { status: 404 })
            const fp = path.join(process.cwd(), `/content/bib/papers/${file}`)
            var stat = fs.statSync(fp);
            const data = fs.readFileSync(fp)
            let blob = new Blob([data])
            let res = new NextResponse(blob, getCorsHeaders(req, 200))
            res.headers.set('Content-Type', 'application/octet-stream');
            res.headers.set('Content-Disposition', `attachment; filename=${file}`);
            res.headers.set('Content-Length', `${stat.size}`)
            return res
        } catch (err) {
            console.error(err)
            return new NextResponse(JSON.stringify({ success: false }))
        }
    })


export async function GET(request: NextRequest, ctx: RequestContext) {
    return router.run(request, ctx);
}

export const OPTIONS = optionsMethodResponse
```

Definitely a huge help... this wasn't the easiest thing to figure out.
