### ISSUE TITLE
How can I add a scrollbar? 

### ISSUE THREAD

**Issue by bfang711** [wojtekmaj/react-pdf#327]
I would like to fix the showing area width, and in the meantime, can scroll the pdf page if it is beyond the area width. 

The way I use it now is ```<Document> <Page width={a fixed number} scale={a changeable number}/> </Document>  ```. But I don't think this is the right way.  plus if fix the width in Page, I cannot zoom in/out by changing the scale.

Can you please advise?

thank you.

**Comment by wojtekmaj** [comment]
Hi,
adding a scrollbar is up to you. Treat `<Page>` like you would treat `<img>` - there's no special functionality that allows a scrollbar in an image, and there is no such functionality in `<Page>` either. You need to wrap it in your own wrapper and style this wrapper in a way that would show the scrollbar.

I don't know if I understood correctly what you were trying to achieve, though.

**Comment by chinalwb** [comment]
@bfang711 , did you find a solution to add scrollbars? Is it possible to add the feature which enables drag on PDF to show the beyond area content? Which I think will provide a better user experience.

**Comment by ianzen** [comment]
> @bfang711 , did you find a solution to add scrollbars? Is it possible to add the feature which enables drag on PDF to show the beyond area content? Which I think will provide a better user experience.

You can wrap the Document/Page element in a <div> with a specified height and style={{overflow: "scroll"}}. If the pdf element overflows this <div> then a scrollbar will be added. I'm currently using this approach to my project. Rendering multiple pages for large pdfs and getting it to interact well with scrolling is non-trivial.

**Comment by chinalwb** [comment]
> Your JSX looks fine, the answer in your case would be in CSS. Perhaps your Page is cut off by `overflow: hidden` somewhere, or there's a negative margin, or there's `transform`. Hard to tell without actually looking at it IRL.

Thanks for your advice, I'll check.

**Comment by chinalwb** [comment]
Just an update for my issue. I need to add `transform: translate(0px, 50px)` and `overflow: scroll` to the <div> under the toolbar.

**Comment by Daryaei** [comment]
whay my react pdf hasn't  toolbar?

**Comment by RazaAkmal11** [comment]
@chinalwb Can You please tell me How You have managed to zoom in zoom out in Your pdf??

**Comment by abduljamac** [comment]
@chinalwb  same here how did you add zoom in/out func?

**Comment by abduljamac** [comment]
@chinalwb No worries, would be nice if you could post some snippet of your code on how you implemented it plus with the scrollbar if its not to much to ask?
