### ISSUE TITLE
Loading a page before the previous one loaded causes setState warning on an unmounted component

### ISSUE THREAD

**Issue by pxFIN** [wojtekmaj/react-pdf#328]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

When rendering one page at a time (first time, no batch loading of pages) state update is done on unmounted component

If renderTextLayer and renderAnnotationLayer is set to false there are no warning messages

**Steps to reproduce**

In the example code multiple quick clicks to PrevPage/NextPage buttons create warning messages. (if buttons are pressed in slower intervals there are no warning/error messages)

Trace:    [example.log](https://github.com/wojtekmaj/react-pdf/files/2728633/example.log)

If tried similarly on react-pdf test page (load from file (pdf file has to have multiple pages) 
[http://projekty.wojtekmaj.pl/react-pdf/test](url)

Click next button a couple of times quickly there is a error message

[react-pdf-test-site.log](https://github.com/wojtekmaj/react-pdf/files/2728719/react-pdf-test-site.log)

**Expected behavior**

No error messages

I think the question is though, Is this normal behaviour should application throttle page queries or a bug in react-pdf ?

Also i cant say if this is related but

https://github.com/wojtekmaj/react-pdf/issues/305#issuecomment-447293295

**Additional information**

Example code:

```
import React from "react";
import "./App.css";
import "react-pdf/dist/Page/AnnotationLayer.css";
import { Document, Page, pdfjs } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${
  pdfjs.version
}/pdf.worker.js`;

class MyPDF extends React.Component {
  constructor(props) {
    super(props);

    this.state = { numPages: null, pageNumber: 1 };
  }

  onDocumentLoadSuccess = ({ numPages }) => {
    this.setState({ numPages });
  };

  goToPrevPage = () => {
    if (this.state.pageNumber > 1) {
      this.setState(state => ({ pageNumber: state.pageNumber - 1 }));
    }
  };
  goToNextPage = () => {
    if (this.state.pageNumber < this.state.numPages) {
      this.setState(state => ({ pageNumber: state.pageNumber + 1 }));
    }
  };

  render() {
    const { pageNumber, numPages } = this.state;

    return (
      <div className="mypdf-container">
        <button onClick={this.goToPrevPage}>Prev</button>
        <button onClick={this.goToNextPage}>Next</button>

        <Document
          file="./example.pdf"
          onLoadSuccess={this.onDocumentLoadSuccess}
        >
          <Page pageNumber={pageNumber} width={600} />
        </Document>

        <p>
          Page {pageNumber} of {numPages}
        </p>
      </div>
    );
  }
}

export default MyPDF;
```

**Environment**

 - Browser: Chrome latest, Firefox latest
 - React-PDF version: 4.0.0
 - React version: 16.7
 - Webpack version: create-react-app/react-scripts 2.1.2, webpack 4.19.1

**Comment by wojtekmaj** [comment]
Hi,
thanks for your report. I see what was wrong - we were setting state even on planned exception thrown by cancelling a promise that was getting text layer items. Fixed - expect it to land with the next release.

**Comment by wojtekmaj** [comment]
Stunning report, BTW :) Took me seconds to understand and reproduce. 

🙏

**Comment by DragomirRhv** [comment]
I got the same issue now. 
Browser: Chrome latest, Firefox latest
React-PDF version: 5.0.0
React version: 16.12.0
Webpack version: 

![Screenshot at 2020-09-22 01-17-21](https://user-images.githubusercontent.com/52378777/93827799-bae0fe00-fc72-11ea-8572-12c217c8cd82.png)
4.42.0

It is imported in this way: 
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';

**Comment by DragomirRhv** [comment]
@pxFIN Do you have the same issue now !?
