### ISSUE TITLE
Can I render SVG only?

### ISSUE THREAD

**Issue by FrostyBonny** [wojtekmaj/react-pdf#329]
I dont what to show the text layers.Like your [demo ](http://projects.wojtekmaj.pl/react-pdf/test/)on this.when your demo use SVG the text layer disappeared,but when i set code like this:
 ```
<Document
 file={pdfTest}
onLoadSuccess={this.onDocumentLoadSuccess}
renderMode="svg"
>
<Page pageNumber={pageNumber} />
</Document>
```
it still render text layers.
i dont konw why and how to resovle it.
or can you share your [demo ](http://projects.wojtekmaj.pl/react-pdf/test/)source code? 

thanks
**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:71.0.3578.98
 - React-PDF version [e.g. 3.0.4]:4.0.2
 - React version [e.g. 16.3.0]:16.6.3

**Comment by FrostyBonny** [comment]
Another problem:how can i load local file?like the demo show.when I choose a local file, it show the file.

**Comment by wojtekmaj** [comment]
Look to the docs to find the props you're looking for. It's all there. Just look for "text layer" in README.

You can load a local file by adding a file picker, reading the data out of it and passing it to React-PDF. Sample is available in this repository.

**Comment by FrostyBonny** [comment]
thank you very much,It was my fault because I didn't read it all just read most of README.sorry about that.

**Comment by jvhoffbauer** [comment]
Hi @FrostyBonny, maybe I am doing it wrong, but adding the `renderTextLayer={false}` to the Document does not remove the text layer for me. Can you give an hint on how you did this?
