### ISSUE TITLE
Failed to load PDF file from Firebase

### ISSUE THREAD

**Issue by gebermax** [wojtekmaj/react-pdf#330]
Hi Wojciech Maj, 
I try to load a pdf from firebase storage using the download url. When I try to open the download url in google it works fine, but there is always the error "Failed to load PDF file". I am using the latest versions of react-pdf. 

Here we get the download url from firebase:

`serviceFunction.readDocument(this.props.id)
            .then(docRef =>

                docRef.data().instructionPDF && docRef.data().instructionPDF.length > 0 ?

                    this.setState({pdfUrl: docRef.data().instructionPDF, loading: false}) :

                    this.setState({pdfUrl: '', loading: false})
            );`

and here is my document:

`<Document                                       
    file={this.state.pdfUrl}
    onLoadSucces={({ numPages }) => this.setState({ numPages })}
   >
 <Page
   pageNumber={this.state.pageNumber}
   />
</Document>`

**Comment by jimmythompson** [comment]
Have you got a link to the document you're trying to download?

**Comment by gebermax** [comment]
Yes I have the link, but I don't know if it is a good idea to post this link here?!

**Comment by jimmythompson** [comment]
Maybe not, it's just hard to figure out what's going wrong with a particular file if nobody can download it.

Does your developer console tell you there are any problems, maybe involving CORS?

**Comment by gebermax** [comment]
Here is a link:
https://firebasestorage.googleapis.com/v0/b/pattarina-swp-65927.appspot.com/o/pdfDocuments%2Fb97eb876-09c9-40e6-8bc4-9ab570c38333.pdf?alt=media&token=bd1e8bfd-3b48-476a-b372-c177a4cffa91

Yeah I read which includes CORS.

**Comment by Rustastra** [comment]
Hi, have you figured out the solution? I am trying to display the pdf from Firebase storage too, and it fails with "unexpected token '<''. The file is there, and CORS is set up.

Thank you

**Comment by wojtekmaj** [comment]
@Rustastra search for "Unexpected token", this has been discussed many times. You're just getting a HTML error page where you were expecting a PDF.
