### ISSUE TITLE
Problems loading / rendering pages of certain document on iOS 12

### ISSUE THREAD

**Issue by michaeldzjap** [wojtekmaj/react-pdf#335]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

Using _react-pdf_ on _iOS_ 12 results in some pages not being rendered for certain documents.

**Steps to reproduce**

1. Load [19.pdf](https://github.com/wojtekmaj/react-pdf/files/2768504/19.pdf) document in the _react-pdf_ sample viewer (btw. only could get this to work with the _parcel_ version, _webpack_ version seems to fail without any errors or warnings, even after manually installing _babel-runtime_).
2. You will see that some pages are not rendered or loaded. I think [this](https://stackoverflow.com/questions/52532614/total-canvas-memory-use-exceeds-the-maximum-limit-safari-12) is related, but I cannot always seem to reproduce the `[Warning] Total canvas memory use exceeds the maximum limit ...` in the console. The fact that loading times on iOS 12 are extremely [slow](https://github.com/mozilla/pdf.js/issues/8954) probably doesn't help here. I am testing via _browserstack_ and I suspect that _browserstack_ refreshes when page loading takes too long, thus erasing any console output.

<img width="990" alt="screenshot 2019-01-17 at 13 13 17" src="https://user-images.githubusercontent.com/2669912/51318119-af7b0f80-1a59-11e9-89f5-268e538814eb.png">

**Expected behavior**

What you expected to happen?

All pages should be rendered / loaded. This problem only occurs (as far as I have been able to test) with both _Safari_ and _Chrome_ on _iOS_ 12. Other mobile platforms (e.g. _Android_) and _iOS_ 11 don't seem to be affected.

**Additional information**

I have also tried the _pdf-js_ viewer and the problem doesn't seem to occur for the same document strangely enough. Using the same test case (i.e. _Safari_ on _iOS_ 12) all pages of the document are loaded / rendered fine. So perhaps this problem is specific to _react_ or [this](https://github.com/wojtekmaj/react-pdf/issues/305) is related.

Furthermore, I have also tried to virtualise page rendering using my own _react-pdf_ and _react-window_ [solution](https://github.com/michaeldzjap/react-pdf-sample), but this doesn't solve the problem. In fact, it results in even more pages not being able to load.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Chrome and Safari
 - React-PDF version [e.g. 3.0.4]: latest
 - React version [e.g. 16.3.0]: 16.5.0 (whatever version the _react-pdf_ sample uses)

**Comment by wojtekmaj** [comment]
Hi @michaeldzjap,
sorry for late response. Busy time in private life lately.
This document is rather long and rendering 19 pages all at once doesn't seem like a good idea. You could use `react-window` or similar solutions folks are using in #94. I could think of a queue system of some kind to avoid rendering many pages at once. This is a huge task, but doable, I think 🤔

**Comment by michaeldzjap** [comment]
Hey @wojtekmaj. No worries, I understand. I appreciate all the time and effort you put into this library.

Using a windowing solution doesn't fix the problem unfortunately (I included a remark about this in my original posting, see additional information section). Windowing only makes the problem worse. Even more pages are not able to render for some reason. Also, the problem already starts with rendering 7 or 8 pages, depending on the document.

**Comment by wojtekmaj** [comment]
@michaeldzjap It seems like @robsco-git got it figured out :) Will be avail in next patch release.

**Comment by michaeldzjap** [comment]
@wojtekmaj  Nice! That is great to hear.
