### ISSUE TITLE
Add PDF test page to README.md

### ISSUE THREAD

**Issue by pxFIN** [wojtekmaj/react-pdf#336]
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

Add Advanced PDF test page to main README.md

**Describe the solution you'd like**

Add and/or change current section about Online Demo

This helps any new react-pdf customer to see the possibilities of react-pdf component

**What you want to happen?**

Add Advanced Online Demo link to react-pdf main page (README.md) (link) which is hard to find for any react-pdf user. Many users do not read old github issues.

http://projects.wojtekmaj.pl/react-pdf/test

https://github.com/wojtekmaj/react-pdf/issues/244
https://github.com/wojtekmaj/react-pdf/issues/328#issuecomment-451651260

**Describe alternative solutions or features you've considered, if any.**

Add link on http://projects.wojtekmaj.pl/react-pdf
page to advanced PDF page too

No reason to hide the advanced PDF page

**Comment by alexnez96** [comment]
I second this 👍 Can the source code for the advanced demo also be added to the repo please? Thanks

**Comment by wojtekmaj** [comment]
Hi,
the advanced demo is used for internal testing and I'm not sure whether it's designed in a way which would help developers to get a better understanding of React-PDF. Some of the most common use cases are covered on [Recipes Wiki page](https://github.com/wojtekmaj/react-pdf/wiki/Recipes), and if you think there's any other common use case that should be included there, I'll be more than happy to add a well written, understandable example focused on solving a specific problem, not all the problems at once.

**Comment by pxFIN** [comment]
Additionally Recipes perfectly OK if you point react-pdf learners there via README.md

**Comment by wojtekmaj** [comment]
It's in the repo because it makes sense for me to have a set of testing tools in the same place as the repo I'm testing, especially since the functionality of these testing tools vary from version to version. I have absolutely no reason to hide it from the world, but I question the value of it when you're learning how to use the library.
It's absolutely open source.

Good point on mentioning Recipes in README!
