### ISSUE TITLE
Can not adjust scale pdf when set Page renderMode'svg'

### ISSUE THREAD

**Issue by HelenZeng** [wojtekmaj/react-pdf#337]
Thank you for your react-pdf.

React: '16.3.2'
React-pdf： ‘3.0.5’
Webpack: '4.8.3'
Browser: Chrome, Safari(PC, iPad)

Page renderMode = “canvas”， can not see the pdf in the ipad browsers
There is a console warning : Canvas area exceeds the maximum limit (width * height > 16777216).

Page renderMode = "svg", can not scale the pdf.

**Comment by wojtekmaj** [comment]
Looks like you used some really really big scale factor which causes PDF.js to refuse to render the image. Perhaps you confused `scale` with `width` and wrote something like `scale={1000}`. Can't tell without the code, though.
