### ISSUE TITLE
Page throwing 'TypeMismatchError' in IE11 for PDF in new window

### ISSUE THREAD

**Issue by eragon512** [wojtekmaj/react-pdf#338]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

While trying to display a PDF in a new window by dynamically creating a new div and inserting the Document component, Page component throws a`TypeMismatchError`

**Steps to reproduce**

1. Create React Component to load a PDF using Document and Page components as shown in docs (using the [`<MyApp />`](https://github.com/wojtekmaj/react-pdf#usage) from the documentation as an example) 
2. Open new window using `var newWindow = window.open();`
3. Create a `div` and append it to the above window using 
```
var pdfDiv = newWindow.document.createElement('div');
newWindow.document.appendChild(pdfDiv);
```
4. Render the PDF component in the new window as follows:
`ReactDOM.render(<Document ...><Page pageNumber={1} /></Document>, pdfDiv)`

Combined code snippet should look like:
```
var newWindow = window.open();
var pdfDiv = newWindow.document.createElement('div');
newWindow.document.appendChild(pdfDiv);
ReactDOM.render(<MyApp />, pdfDiv);
```

**Expected behavior**

Should render the PDF in a new window

**Additional information**

Works in Firefox and Chrome, but not in IE11

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: IE11
 - React-PDF version [e.g. 3.0.4]: 4.0.2
 - React version [e.g. 16.3.0]: 16.6.1
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.25.1

**Comment by wojtekmaj** [comment]
Hi @eragon512,
sorry for late response - been very busy in private life recently.

I don't know what throws this error (do you have a call stack maybe?), so I'm only going to guess. It seems like Edge doesn't like the fact that script from one window fetches something in another. Consider loading the file before sending it to React-PDF and pass it as a `Blob` or `File` or (if all else fails) `base64`.

Just a wild guess though. Hope this helps 🤔

**Comment by eragon512** [comment]
hey @wojtekmaj ,
The issue is as you described, as `react-pdf` is able to render the PDF on the same page in IE, however, it fails to render it in the new window. I tried to render it as a Blob/base64, however, the issue still persists, as the `onLoadSuccess` callback after which the `onRenderError` callback gets executed
