### ISSUE TITLE
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined

### ISSUE THREAD

**Issue by JustinJKlein** [wojtekmaj/react-pdf#34]
I am trying to implement a pdf viewer using this module. I am providing the link and have done it in both string format to test and as an object. I am not sure how to correct  it and was hoping you could help. 

Here is the error:
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `TestResultsDetail`

I received this warning before the error too:
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. 

The module is installed and I imported just as described in the docs.

**Comment by wojtekmaj** [comment]
Hey,
I know what is up probably. You're most likely using 2.0.0-alpha version that recently got published and for some reason npm didn't catch that it's a pre-release. So likely you're following instructions for 1.x and in fact you're using 2.x.

Please follow README.md from this branch: https://github.com/wojtekmaj/react-pdf/tree/new-architecture
or simply from your node_modules installed package folder.

In the meantime I will work to fix npm issue and also make the transition smoother from 1.x to 2.x :)

**Comment by wojtekmaj** [comment]
One more question. Does using your version of the fix, with 'pdf.combined.js' does NOT result in this warning or only gets rid of 404's? If pdf.combined.js is working great maybe it's the path we should follow in 2.0.

**Comment by JustinJKlein** [comment]
Thanks for the quick response! This seams to have gotten me working!

 I will let you know how it works once I test the pdf.combined.js.

**Comment by wojtekmaj** [comment]
Hey @JustinJKlein, thank you for reporting this. I have now fixed NPM tags so they should work as you expect them to. latest, next are both there for your convenience.
Have a good day!

**Comment by davidworkman9** [comment]
I'm currently getting this as well with ```react-pdf@4.0.2```.

Document & Page variables are set properly. I'm not sure what I'm doing wrong..

Here's my component:

```
import React from 'react';
import { compose, withState } from 'recompose';
import { createPortal } from 'react-dom';
import { pdfjs, Document, Page } from 'react-pdf';

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

const enhance = compose(
    withState('numPages', 'setNumPages', null),
    withState('pageNumber', 'setPageNumber', 1),
);

const FileViewer = ({
    file, pageNumber, numPages, setNumPages,
}) => createPortal(
    (
        <div>
            <Document
                file={file.link()}
                onLoadSuccess={({
                    numPages,
                }) => {
                    setNumPages(numPages);
                }}
            >
                <Page pageNumber={pageNumber} />
            </Document>
            <p>Page {pageNumber} of {numPages}</p>
        </div>
    ), document.body,
);

export default enhance(FileViewer);
```

**Comment by davidworkman9** [comment]
@wojtekmaj I'm running ```react@16.7.0```.

**Comment by oyatek** [comment]
I'm getting this with`react-pdf v5.7.2`
