### ISSUE TITLE
How to disable image caching when using react-pdf

### ISSUE THREAD

**Issue by FriendlyUser** [wojtekmaj/react-pdf#341]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'm trying to make sure whenever someone goes to view their documents, their images aren't cached for security reasons. Is there a simple way to achieve this using react-pdf, or do I need to fiddle around with the endpoints that contain images and/or use some sort of cache policy.

**Describe solutions you've tried**

Describe solutions you've already tried, if any. Make sure to include code samples if you're stuck on implementation.

none. Not sure how to not cache these files.
**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - React-PDF version [e.g. 4.0.0]:
 - React version [e.g. 16.6.0]:
 - Webpack version (if applicable) [e.g. 4.27.0]:

**Comment by ravishan110** [comment]
Can we add no-cache while fetching a pdf document?
