### ISSUE TITLE
pdf.worker.js is being re-fetched when file prop changes

### ISSUE THREAD

**Issue by ghost** [wojtekmaj/react-pdf#342]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

When the `file` prop on `Document` changes, the `pdf.worker.js` is being re-fetched over the wire. Considering that the minified worker file is 750 KB (and 1.5 MB unminified), this puts extra traffic on the network, and particularly becomes an issue on slow and/or metered connections.

**Steps to reproduce**

1. Go to the [sandbox](https://935jzwv8oy.codesandbox.io/)
2. Open the network tab
3. Click "Toggle PDF URL" button
4. Observe `pdf.worker.js` being re-fetched
5. Subsequent clicks trigger further fetches

👉 **See [this sandbox](https://codesandbox.io/s/935jzwv8oy) for a repro** 👈

**Expected behavior**

It should _not_ re-fetch the PDF worker file. It should only fetch once and cache it for subsequent documents.

**Additional information**

The context for this is that I'm allowing the user to select a PDF document from a menu. When a document is selected, a new `file` prop trickles down to `Document` causing a re-render. Unfortunately, this also causes the worker file to be requested again.

On the same note, I noticed that the [react-pdf test page](http://projects.wojtekmaj.pl/react-pdf/test/) doesn't suffer from this when you load a file from the file system. Is this a different scenario, or am I approaching the problem from the wrong angle?

**Environment**

 - Browser: any
 - React-PDF version: `4.0.2` (latest)
 - React version: `16.7.0` (latest)
 - Create-React-App: `2.1.3` (latest)

**Comment by wojtekmaj** [comment]
Hi,
looks like some issue in PDF.js itself.
Does it happen only when you use workerSrc option, or when you use defauly entry files e.g. for Webpack, too?

**Comment by alexnez96** [comment]
@wojtekmaj You're right, it only happens when `workerSrc` is assigned manually. Works as expected with `react-pdf/dist/entry.webpack`. Is there any workaround? I see a few issues ([this](https://github.com/mozilla/pdf.js/issues/7057) and [this](https://github.com/mozilla/pdf.js/issues/7333)), but I'm not sure how to go about it with `react-pdf`.

**Comment by wojtekmaj** [comment]
I honestly have no idea how to approach this. I experimented - theoretically you can pass `file={{ url, worker }}` but it doesn't seem to detect that, even though this argument should have been passed to getDocument. Maybe the community will help.

**Comment by GautierT** [comment]
@alexnez96 : Hi ! Did you find a solution for this ? If i parse a lot of PDF the worker is reloaded everytime. Because i'm using Create React App i can't use `react-pdf/dist/entry.webpack`...
Thanks

**Comment by alexnez96** [comment]
@GautierT I did not. Not sure what can be done here.

**Comment by alex-shamshurin** [comment]
Same issue is here

**Comment by andreamisu** [comment]
hi guys, been afflicted by this "bug" today, as i saw the prd.worker.js being re-fetched and being re-initalized everytime i changed dinamically document, but i've resolved creating two differents functions.

initializeViewer

`    function initializeViewer(pdfData) {
        // Loaded via <script> tag, create shortcut to access PDF.js exports.
        var pdfjsLib = window['pdfjs-dist/build/pdf'];

        // The workerSrc property shall be specified.
        pdfjsLib.GlobalWorkerOptions.workerSrc = 'xxxxxxPATHxxxxxxx/pdf.worker.js';

        /**
         * If another page rendering in progress, waits until the rendering is
         * finised. Otherwise, executes rendering immediately.
         */
        function queueRenderPage(num) {
            if (pageRendering) {
                pageNumPending = num;
            } else {
                renderPage(num);
            }
        }

        /**
         * Asynchronously downloads PDF.
         */
        pdfjsLib.getDocument({ data: pdfData }).promise.then(function (pdfDoc_) {
            pdfDoc = pdfDoc_;
            document.getElementById('page_count').textContent = pdfDoc.numPages;

            // Initial/first page rendering
            renderPage(pageNum);
        });
    `
changeDocument
`    function changeDocument(pdfData)
    {
        pdfjsLib.getDocument({ data: pdfData }).promise.then(function (pdfDoc_) {
            pdfDoc = pdfDoc_;
            document.getElementById('page_count').textContent = pdfDoc.numPages;

            // Initial/first page rendering
            renderPage(pageNum);
        });
    }`

Both renderPage(num) and var pdfDoc = null... should be defined before them.
idk if its a right solution for it, but it works actually

**Comment by andreamisu** [comment]
hi guys, been afflicted by this "bug" today, as i saw the prd.worker.js being re-fetched and being re-initalized everytime i changed dinamically document, but i've resolved creating two differents functions.

```
function initializeViewer(pdfData) {
        // Loaded via <script> tag, create shortcut to access PDF.js exports.
        var pdfjsLib = window['pdfjs-dist/build/pdf'];

        // The workerSrc property shall be specified.
        pdfjsLib.GlobalWorkerOptions.workerSrc = 'xxxxxxPATHxxxxxxx/pdf.worker.js';

        /**
         * If another page rendering in progress, waits until the rendering is
         * finised. Otherwise, executes rendering immediately.
         */
        function queueRenderPage(num) {
            if (pageRendering) {
                pageNumPending = num;
            } else {
                renderPage(num);
            }
        }

        /**
         * Asynchronously downloads PDF.
         */
        pdfjsLib.getDocument({ data: pdfData }).promise.then(function (pdfDoc_) {
            pdfDoc = pdfDoc_;
            document.getElementById('page_count').textContent = pdfDoc.numPages;

            // Initial/first page rendering
            renderPage(pageNum);
        });
```

```
function changeDocument(pdfData)
    {
        pdfjsLib.getDocument({ data: pdfData }).promise.then(function (pdfDoc_) {
            pdfDoc = pdfDoc_;
            document.getElementById('page_count').textContent = pdfDoc.numPages;

            // Initial/first page rendering
            renderPage(pageNum);
        });
    }
```

Both renderPage(num) and var pdfDoc = null... should be defined before them.
idk if its a right solution for it, but it works actually

**Comment by vangelov** [comment]
I just stumbled upon this today. I'm using Vite. What do you mean by `react-pdf/dist/entry.webpack`?

**Comment by vangelov** [comment]
Thanks. I'm wondering -- won't using a service worker solve this? We can just cache the pdf.worker.js file with it.

**Comment by vangelov** [comment]
It seems to be working. The first time the `pdf.worker.js` file is loaded it's cached by the servive worker and all subsequent requests are fulfilled by the service worker without using the server.

Here's my code:

Put this in the your `index.js` / `main.js` file:

```
const registerServiceWorker = async () => {
  if ("serviceWorker" in navigator) {
    try {
      const registration = await navigator.serviceWorker.register(
        "/cache-sw.js",
        {
          scope: "/",
        }
      );

      if (registration.active && !navigator.serviceWorker.controller) {
        window.location.reload();
      }
    } catch (error) {
      console.error(`Registration failed with ${error}`);
    }
  }
};

registerServiceWorker();
```

Save this as `cache-sw.js` and add it to your `public` folder:

```
self.addEventListener("activate", (event) => {
  console.log("SW: Activate", event);
  event.waitUntil(self.clients.claim());
});

self.addEventListener("install", () => {
  console.log("SW: Install");
});

const putInCache = async (request, response) => {
  const cache = await caches.open("v1");
  await cache.put(request, response);
};

const cacheFirst = async (request) => {
  const responseFromCache = await caches.match(request);
  if (responseFromCache) {
    return responseFromCache;
  }
  const responseFromNetwork = await fetch(request);
  putInCache(request, responseFromNetwork.clone());
  return responseFromNetwork;
};

self.addEventListener("fetch", (event) => {
  if (event.request.url.includes("pdf.worker")) {
    event.respondWith(cacheFirst(event.request));
  }
});
```

`

**Comment by andrieshiemstra** [comment]
I ended up just caching the code in a blob
```javascript
// do this once somewhere...
const fetchResponse = await fetch("/path/to/pdf.worker.js");
const code = await fetchResponse.text();
const codeBlob = new Blob([code], { type: "text/javascript" });
const workerUrl = URL.createObjectURL(codeBlob);
pdfjsLib.GlobalWorkerOptions.workerSrc = workerUrl;
```

**Comment by criskell** [comment]
I'm facing the same issue with Vite

**Comment by DevJogger** [comment]
> It seems to be working. The first time the `pdf.worker.js` file is loaded it's cached by the servive worker and all subsequent requests are fulfilled by the service worker without using the server.
> 
> Here's my code:
> 
> Put this in the your `index.js` / `main.js` file:

This is super useful, to avoid pdf.worker script re-fetch while need to load new PDFs frequently. Thank you @vangelov !
