### ISSUE TITLE
Sample project doesn't work

### ISSUE THREAD

**Issue by depiction** [wojtekmaj/react-pdf#344]
**Before you start - checklist**

 - [X] I followed instructions in documentation written for my React-PDF version
 - [X] I have checked if this bug is not already reported
 - [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

The sample project doesn't work. When I run it, all I see is a dark gray screen with no errors in Chrome's console.

**Steps to reproduce**

1. Download the latest version (4.0.2)
2. Open the "sample" folder in Visual Studio Code
3. Run `npm install` then `npm run build`
4. Right-click on the index.html file in the "dist" folder and select "Open with Live Server".
5. When the page opens, verify that a page with nothing but a dark gray background appears. Look in the browser's console and verify that there are no errors.

**Expected behavior**

I expected to see the PDF viewer with a PDF displayed.

**Environment**

 - Chrome 71
 - React-PDF version 4.0.2

**Comment by wojtekmaj** [comment]
I don't know what "Live Server" is. What's the URL in the browser when you open index.html file?

**Comment by depiction** [comment]
The "Open with Live Server" feature in Visual Studio Code starts a local node server to view the site. It resolves path issues that often exist when running a site locally.

However, in this case I get the same result if I open the index.html file in the dist folder using Chrome.

**Comment by yanivkalfa** [comment]
I have a very similar issue that can be found "https://designboardz.com/board/599764ebf9327c6c1fc0c93a/pin/59979654f9327c6c1fc0c979"

no error, just grey page - when i inspect components/pages are there but they dont display.

This only happen on production. - doesnt happen on local.

**Comment by pxFIN** [comment]
Parcel version works but webpack version doesn't.. It's due to wrong entry point file in webpack.config.js file

I made PR https://github.com/wojtekmaj/react-pdf/pull/358
