### ISSUE TITLE
Failed to load PDF file from URL

### ISSUE THREAD

**Issue by aparna1413** [wojtekmaj/react-pdf#347]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
Unable to render pdf (url) 

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.
I'm trying to render pdf from url , but I get the following error in the browser

`failed to load pdf file`
`pages of`

**Describe solutions you've tried**
**SamplePdf.jsx**

```
 import React, {Component} from "react";
   import {Document, Page} from 'react-pdf';

class Sample extends Component {
    constructor(props) {
        super(props);
        this.state = {
            numPages: null,
            pageNumber: 1
        };
    }
 onDocumentLoad({numPages}) {
        this.setState({numPages});
    }
render() {
const {pageNumber, numPages} = this.setState;
        return (
            <div>
                <Document
                    file={{url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf'}}
                    onLoadSuccess={this.onDocumentLoad}>
                    <Page pageNumber={pageNumber}/>
                </Document>
                <p>Page {pageNumber} of {numPages}</p>
            </div>
        );
    }
}

export default Sample; 
```

**index.jsx**
```
import React from 'react';
import { storiesOf } from '@storybook/react';
import Sample from '../Sample';

const storyPath = 'TrialComponents/reactpdf';

storiesOf(storyPath, module)
  .add('Static', () => <Sample />);
```

**Additional information**

Error Screen in browser
<img width="864" alt="screen shot 2019-02-05 at 5 18 49 pm" src="https://user-images.githubusercontent.com/47370184/52307989-283efe80-296a-11e9-852e-9aa86540fbba.png">

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by aparna1413** [comment]
Sorry this is a duplicate issue. Closing it. Thanks

**Comment by dev-chr** [comment]
OK, so duplicate. Where is the answered or original?

**Comment by anton6** [comment]
I am also facing same problem... where is the original post?

**Comment by wojtekmaj** [comment]
This issue is not described well enough for me to point out a specific issue to seek help. I suggest either creating a new ticket describing exactly what happens, or seek for the issue on your own.

**Comment by chinku04** [comment]
when I try to load file from a URL (external pdf url like  for eg. : http://www.pdf995.com/samples/pdf.pdf )
 error "Failed to load PDF file". PDF is not rendered as expected.

**Comment by gachez** [comment]
Anyone found a solution?

**Comment by soorajvinodan** [comment]
Anyone found solution ?

**Comment by premkiran7** [comment]
Refer this - https://stackoverflow.com/questions/29670703/how-to-use-cors-anywhere-to-reverse-proxy-and-add-cors-headers

**Comment by PankajChaturvediDtechies** [comment]
> Sorry this is a duplicate issue. Closing it. Thanks

still looking for the fix or solution
