### ISSUE TITLE
Document text not rendering

### ISSUE THREAD

**Issue by aparna1413** [wojtekmaj/react-pdf#348]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Display document text

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.

**Describe solutions you've tried**

SampleText.jsx

```
import React from 'react';
import { Document, Page, View, Text } from 'react-pdf';

const SampleText = (
  <Document>
    <Page size="A4">
      <View>
        <Text>
          Display text here
        </Text>
      </View>
    </Page>
  </Document>
);

export default SampleText;
```
index.jsx

```
import React from 'react';
import { storiesOf } from '@storybook/react';
import SampleText from '../SampleText';


const storyPath = 'Components/SampleText';

storiesOf(storyPath, module)
  .add('Static', () => <SampleText />);
```
**Additional information**

error in console-
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by DimaRGB** [comment]
@aparna1413 looks like, you use another library https://github.com/diegomura/react-pdf, no ?

**Comment by aparna1413** [comment]
@DimaRGB , I used https://www.npmjs.com/package/react-pdf library.

**Comment by wojtekmaj** [comment]
@aparna1413 Original React-PDF (this one) is meant to display PDFs, not to create them, which you are trying to achieve, I believe. diegomura's React-PDF is to create PDFs.
