### ISSUE TITLE
'PDFJS' is not defined 

### ISSUE THREAD

**Issue by saman** [wojtekmaj/react-pdf#35]
I updated webpack of my project from `1.xx` to `2.xx`, But I could not make a build. I got this error. I could not find any solution. Do you have any idea?

Versions:
```
"webpack": "2.6.1",
"react": "15.4.*",
"react-pdf": "^1.8.3",
```
And errors:
```
./src/components/~/react-pdf/es5/react-pdf.js
(Emitted value instead of an instance of Error)
  Line 25:   'PDFJS' is not defined  no-undef
  Line 27:   'PDFJS' is not defined  no-undef
  Line 207:  'PDFJS' is not defined  no-undef
```

Thanks

**Comment by wojtekmaj** [comment]
Hey there!
Thanks for your report. The newest react-pdf 1.8.3 does not have /es5 folder. Not really sure how you ended up with that path then. Would you please completely remove react-pdf and make a clean install?

**Comment by saman** [comment]
> The newest react-pdf 1.8.3 does not have /es5 folder. Not really sure how you ended up with that path then.

I was installed version `1.6` and after that, I did update.
>  Would you please completely remove react-pdf and make a clean install?

Thanks for the answer. Now it works!
