### ISSUE TITLE
Relating "DPI" and "scale"

### ISSUE THREAD

**Issue by peterkmurphy** [wojtekmaj/react-pdf#351]
Dear Wojciech,

I'm trying to clarify what the relation is between "scale" (one of the props in the "Page" element), and the resolution of the page on the screen in Dots Per Inch. This is one of the areas where the documentation is unclear. 

> Defines the scale in which PDF file should be rendered. Defaults to 1.0.

The problem here is that no unit of measurement is provided, which I think is necessary. Page sizes are measured in mm (or inches), but screens and viewports are measured in pixels, and there is no natural relationship between the two.

I'll just explain the situation, so you know where I am coming from. I am a software developer who wants to design a tool where people can take PDFs (generally of building plans), show them on the canvas, produce PNGs from them, and annotate them with symbols. The quality I need is 300 DPI. The producing PNGs from the canvas isn't your problem; what I need is the canvas having enough size to render the original pages at enough quality. 

The PDFs I will be working with use A series paper sizes like A1 and A3, which are measured in mm. So 300 DPI is equal to 300px ÷ 25.4 mm or 11.811px/mm. An A3 size PDF is 297mm × 420mm. So my software aims to creates images of 3508 × 4961 px. 

So my problem is to provide a scale that always produces an image at a desired resolution. On my machine:

 - OS: Linux Mint 18.3
 - Browser:  Firefox 64 (64 bit)
 - React-PDF version: 4.0.0
 - React version: 16.6.0:

I try the following scale values with an A3 document, and measure the size of the canvas.

1.  When the scale is 1, the canvas is 842px × 1191px. 1191px/420mm is 2√2 px/mm. Is that how the scale should work, or am I overthinking things?
2. When the scale is 4.166237(a number found by trial and error), I get *sort of* 300 DPI behavior I expect: A3 pages producing  3507 × 4961 px (and A1 producing  9932 × 7015 px). But this is a *magic* number, and I'd really like to understand _why_ this number produces this results.  

If you could help with *why* a scale of 4.166237 results in a DPI of 300, that would be wonderful.

**Comment by wojtekmaj** [comment]
Looks like default DPI for PDFs is `72`. So given `scale=1` you will end up with 72 DPI by default (not sure if you can change this). `72*4.16=~300`. End of story :)

**Comment by peterkmurphy** [comment]
Thank you very much. Your answer makes complete sense. Do you think the documentation should be updated then? I do. :-)

**Comment by wojtekmaj** [comment]
I'm not sure. PDF DPI would depend on display DPI which in majority of cases is 72, but can be something else, too. So I don't know what I could even put in the documentation. Scale of 1 means just that, 1, or 100%. Nothing else 🤔

**Comment by peterkmurphy** [comment]
Could you give an example where the display DPI would differ from 72?

**Comment by wojtekmaj** [comment]
Hm. I know a few years ago Windows used 96 DPI, and Apple used 72 DPI. It's been a while I did a research in that matter...

**Comment by peterkmurphy** [comment]
Ubuntu Linux (which I'm using) also uses 96 DPI. From here:
[https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages)

> You can count yourself: a letter page size is 816⨉1056px at 96DPI (and if you have a HiDPI display, multiply each dimension by window.devicePixelRatio, e.g., 2), so you will need a canvas that takes up 816⨉1056⨉4 = 3,446,784 bytes (don't forget to multiply that by e.g., 2⨉2 = 4 if it's a HiDPI display). This requires you to allocate 3.5Mb (or 14Mb) per page. You need a decent amount of memory to hold the 100 canvases, and it does not count the time that is spent on rendering them.

This really needs further testing. I have an Apple machine, so I'm going to see what happens with the DPI tomorrow or the day after.

**Comment by peterkmurphy** [comment]
I tested my program on a Mac (using Firefox as well). Using a scale of 4.1666, images produced are     3507px × 4961px, which is 300 DPI; ergo, scale 1 is also 96 DPI.
