### ISSUE TITLE
Should the onLoadSuccess be called before last onLoadProgress?

### ISSUE THREAD

**Issue by LukaszGrela** [wojtekmaj/react-pdf#352]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I'm playing with the `react-pdf` and found that the `onLoadSuccess` before the `onLoadProgress` has finished coming in, is it correct?

```
onDocumentLoadProgress {loaded: 65536, total: 536823}
onDocumentLoadProgress {loaded: 131072, total: 536823}
onDocumentLoadProgress {loaded: 196608, total: 536823}
onDocumentLoadProgress {loaded: 196608, total: 536823}
onDocumentLoadProgress {loaded: 196608, total: 536823}
onDocumentLoadProgress {loaded: 196608, total: 536823}
onDocumentLoadProgress {loaded: 196608, total: 536823}
onDocumentLoadProgress {loaded: 196608, total: 536823}
onDocumentLoadProgress {loaded: 196608, total: 536823}
onDocumentLoadProgress {loaded: 262144, total: 536823}
onDocumentLoadProgress {loaded: 262144, total: 536823}
onDocumentLoadProgress {loaded: 262144, total: 536823}
onDocumentLoadProgress {loaded: 262144, total: 536823}
onDocumentLoadProgress {loaded: 262144, total: 536823}
onDocumentLoadProgress {loaded: 262144, total: 536823}
onDocumentLoadProgress {loaded: 327680, total: 536823}
onDocumentLoadProgress {loaded: 393216, total: 536823}
onDocumentLoadSuccess {loadingTask: PDFDocumentLoadingTask, _pdfInfo: {…}, _transport: WorkerTransport}
onDocumentLoadProgress {loaded: 393216, total: 536823}
onDocumentLoadProgress {loaded: 393216, total: 536823}
onDocumentLoadProgress {loaded: 393216, total: 536823}
onDocumentLoadProgress {loaded: 393216, total: 536823}
onDocumentLoadProgress {loaded: 393216, total: 536823}
onDocumentLoadProgress {loaded: 393216, total: 536823}
onDocumentLoadProgress {loaded: 393216, total: 536823}
onDocumentLoadProgress {loaded: 458752, total: 536823}
onDocumentLoadProgress {loaded: 458752, total: 536823}
onDocumentLoadProgress {loaded: 524288, total: 536823}

onDocumentLoadProgress {loaded: 589824, total: 536823}

onDocumentLoadProgress {loaded: 536823, total: 536823}

onDocumentLoadProgress {loaded: 589824, total: 536823}
onDocumentLoadProgress {loaded: 589824, total: 536823}
```

I can see now that progress also is not consistent, last few entries look incorrect (I've separated them with space in the above snippet).

**Additional information**

I've used `sample.pdf` from the sample (parcel) folder

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]: latest 4.0.2
 - React version [e.g. 16.3.0]: 16.7.0
 - Webpack version (if applicable) [e.g. 4.16.2]: CRA Scripts 2.1.3

**Comment by wojtekmaj** [comment]
My best guess is that PDF file doesn't need to be loaded fully in order for us to get basic information on the document. Hah, you can even stream PDF files partially, and React-PDF even supports that :) So, technically it would be possible to have partially loaded PDF file and still having it displayed perfectly (for example, just 1 of 3 pages).

**Comment by LukaszGrela** [comment]
Makes perfect sense:)
