### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by Kerumen** [wojtekmaj/react-pdf#353]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

With the following component, I have this warning:
> Warning: Can't perform a React state update on an unmounted component.

<img width="367" alt="screenshot 2019-02-13 at 18 59 36" src="https://user-images.githubusercontent.com/5436545/52732871-89498080-2fc1-11e9-960b-3f81ff6844ba.png">

**Steps to reproduce**

This is the problematic component:

```jsx
class Pdf extends Component {
  state = { numPages: 0 }

  onDocumentLoad = ({ numPages }) => this.setState({ numPages })

  render() {
    const { numPages } = this.state
    const { url } = this.props

    const headers = { withCredentials: true }

    return (
      <Document file={{ headers, url }} onLoadSuccess={this.onDocumentLoad}>
        {range(0, numPages).map(index => (
          <Page key={index} pageIndex={index} />
        ))}
      </Document>
    )
  }
}
```

**Expected behavior**

If I remove the `setState`, the PDF renders properly but I lose the information about the number of pages.

**Additional information**

This is the example from the README and this was perfectly working before I upgraded to v4.

**Environment**

 - React-PDF version: `4.0.2`
 - React version: `16.8.1`
 - Webpack version (if applicable): `4.29.3`

**Comment by Maxhou00** [comment]
Hello @Kerumen ,

try this:
```
onDocumentLoad = (document) => {
    const { numPages } = document;
    this.setState({
      numPages,
    });
  };
```
see the [example here](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages)

**Comment by qaisershehzad** [comment]
@Kerumen  did you get it working ? 

@Maxhou00 
It works fine when we load file directly from bundle. But when we load PDF from a URL same issue.

I tried the approach mentioned [here](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages) but facing same issue as mentioned above it  keeps on loading and keep making Network calls.
<img width="483" alt="screen shot 2019-02-18 at 1 35 51 pm" src="https://user-images.githubusercontent.com/11673425/52948798-452cf600-339c-11e9-8912-42e9d19c8c61.png">

"Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in PageInternal (created by Context.Consumer)
    in Page (at Test.js:30)"

**Comment by wojtekmaj** [comment]
@qaisershehzad Perhaps you're defining new `file` object with every render? See #308

**Comment by qaisershehzad** [comment]
@wojtekmaj  I am doing this :
<img width="630" alt="screen shot 2019-02-18 at 4 55 52 pm" src="https://user-images.githubusercontent.com/11673425/52949457-20d21900-339e-11e9-97f6-6043e425c5f8.png">

**Comment by qaisershehzad** [comment]
@wojtekmaj  I am able to get it work by doing like this : 
<img width="625" alt="screen shot 2019-02-18 at 5 20 07 pm" src="https://user-images.githubusercontent.com/11673425/52950617-883d9800-33a1-11e9-8964-d850a8c1ab36.png">

**Comment by peterkmurphy** [comment]
I also had the same "React state update on an unmounted component" message. However, this seemed to happen when I had a multiple page PDF open in react-pdf, and was shifting from one page to another before the first page was loaded.

My "fix" was to disable all controls until the "onRenderSuccess" event was fired on a page load. Try to load a new page: disable all controls, wait for "onRenderSuccess". However, I don't know if this is overkill. @wojtekmaj : does this sound like the right thing to do?

**Comment by wojtekmaj** [comment]
We should be able to cancel setting state on PageInternal unmount, so this sounds like a bug that would be relatively easy to tackle. I don't think disabling all controls is worth it - the bug itself won't cause anything to crash - but it's a workaround that should do it if you really don't like seeing this message for now :)

**Comment by peterkmurphy** [comment]
Thank you for your comment. I'd look forward to that bug being fixed.

**Comment by kevin-mon-liang** [comment]
Hi @peterkmurphy, i am having the same issue but am not sure what you mean by disabling controls until nnRenderSuccess gets called. I am doing this:
```
onRenderSuccess = () => {
  this.setState({
    renderSuccess: true
  });
};

...

{renderSuccess && numPages && numPages.lengh > 1 && (
  <>
    <p>
      Page {pageNumber || (numPages ? 1 : '--')} of{' '}
      {numPages || '--'}
    </p>
    <button
      type="button"
      disabled={pageNumber <= 1}
      onClick={this.previousPage}
    >
      Previous
    </button>
    <button
      type="button"
      disabled={pageNumber >= numPages}
      onClick={this.nextPage}
    >
      Next
    </button>
  </>
)}
```

Can you please elaborate on your solution? Thank you :)

**Comment by akuji1993** [comment]
Would also be interested in hearing the solution to this. Error is appearing in a component using React Hooks, so I'm not sure how that plays into the mix.

**Comment by hibearpanda** [comment]
I ran into this issue while using this library in a next.js project.

My understanding is that the error happens during rerenders - in my case, when `onLoadSuccess` is called to update `numberOfPages`.

My current solution is to use `useMemo` to memoize the file object. The error disappears completely if I do this.
```
function PreviewPDF(props) {
  const [numberOfPages, setNumberOfPages] = useState(null);
  const [pageNumber, setPageNum] = useState(1);
  const file = useMemo(
    () => ({ url: props.fileSrc, withCredentials: true }),
    []
  );

  return (
    <Portal>
      <Document
          file={file}
          onLoadSuccess={({ numPages }) => setNumberOfPages(numPages)}
          options={{ cMapUrl: '/_next/cmaps/', cMapPacked: true }}
        >
          <Page pageNumber={pageNumber} />
      </Document>
    </Portal>
  );
}
```
Where `props.fileSrc` is required.

Hope this helps.

**Comment by shtabnoy** [comment]
@qaisershehzad I've been struggling through it almost 2 days. Your approach with having the whole file object in state finally helped me. Thanks

**Comment by wojtekmaj** [comment]
Memoizing objects / keeping them in state is the correct, recommended solution.

**Comment by max-eb** [comment]
It will cancel request when unmount the component. The promise reject then.
https://github.com/wojtekmaj/react-pdf/blob/590077862132d86da44ac0dc59fc99aaf1e99224/src/Page.jsx#L77
```
  componentWillUnmount() {
    const { unregisterPage } = this.props;

    callIfDefined(
      unregisterPage,
      this.pageIndex,
    );

    cancelRunningTask(this.runningTask);
  }
```
In `loadPage`:
https://github.com/wojtekmaj/react-pdf/blob/590077862132d86da44ac0dc59fc99aaf1e99224/src/Page.jsx#L264
```
    try {
      const cancellable = makeCancellable(pdf.getPage(pageNumber));
      this.runningTask = cancellable;
      const page = await cancellable.promise;
      this.setState({ page }, this.onLoadSuccess);
    } catch (error) {
      this.setState({ page: false });
      this.onLoadError(error);
    }
```
But I think the error should be classified to determine it's a network error or cancelled tasks. If it's cancelled by unmount life cycle method, it should not setState or do anything else.
Like the code below:
```
    try {
      const cancellable = makeCancellable(pdf.getPage(pageNumber));
      this.runningTask = cancellable;
      const page = await cancellable.promise;
      this.setState({ page }, this.onLoadSuccess);
    } catch (error) {
        if (error.msg && error.msg === 'cancelled') {
            return;
        }

      this.setState({ page: false });
      this.onLoadError(error);
    }
```
@wojtekmaj

**Comment by pedrosimao** [comment]
I am also getting this error, while using pdf on a `http url` and `onPageChanged` prop/method. I am not sure what is the solution.

**Comment by wojtekmaj** [comment]
Hmm, reproduced your onDocumentLoadSuccess and I can't see the error @scottie-schneider :( Wanna take a look?

https://codesandbox.io/s/little-hooks-bbgek

**Comment by agustin-v** [comment]
Hi, 
I'm having the same issue but with a Buffer I'm loading from Redux, it gets into a loop. This only happens whenever I update the state on document load success.

**Comment by msgfxeg** [comment]
> Hmm, reproduced your onDocumentLoadSuccess and I can't see the error @scottie-schneider :( Wanna take a look?
> 
> https://codesandbox.io/s/little-hooks-bbgek

@wojtekmaj 
it is working with you because your pdf contains only one page the error/warning still exists on multipage pdfs!

**Comment by wojtekmaj** [comment]
@msgfxeg Don't think that's the case ([this repo](https://codesandbox.io/s/react-pdf-with-navigation-gxzbh) is not affected), but using file object without memoizing sure can cause the issue desribed.
