### ISSUE TITLE
Deprecated API usage warning

### ISSUE THREAD

**Issue by pxFIN** [wojtekmaj/react-pdf#354]
After updating to the latest react-pdf (4.0.3) this is seen on console

Deprecated API usage: RenderTask.then method, use the `promise` getter instead.   (pdf.js:726)

Anyone else seeing this ?

**Comment by wojtekmaj** [comment]
Hmmmm, thought I updated all of these in d2c851de41f0d81cf8483c43f3294ffca42747cb 🤔 Got a full stack trace?

**Comment by pxFIN** [comment]
It's just console.log from pdf.js

function deprecated(details) {
        console.log('Deprecated API usage: ' + details);
      }

Here's console screenshot


![screenshot from 2019-02-18 12-34-30](https://user-images.githubusercontent.com/45363091/52945277-05551700-337a-11e9-9e45-bed14c13d88c.png)

**Comment by wojtekmaj** [comment]
Figured it out, thanks :) Will be out with v4.0.4 Codename Not Found :)

**Comment by Bluejanis** [comment]
How did you solve it?

**Comment by olivierdelomez** [comment]
@Bluejanis with `page.render().promise` I guess. (see https://github.com/wojtekmaj/react-pdf/blob/master/src/Page/PageCanvas.jsx#L127 )
