### ISSUE TITLE
Rapid selection of attachments can cause the wrong attachment to load

### ISSUE THREAD

**Issue by swifttarrow** [wojtekmaj/react-pdf#357]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I want to be able to load different attachments based on navigating through a list of attachments. My problem seems similar to what is described in this issue: https://github.com/wojtekmaj/react-pdf/issues/122

**Describe solutions you've tried**
I have a working solution that is more-or-less the example in the documentation, without virtualization. In my PDFViewer component, I have an attachments array and a selectedIndex that is use to determine which attachment is selected for rendering. 

Lets say I have the following in the array:
[A, B, C]

The attachments array above has 3 attachments, A-C. The viewer has attachment A loaded. Now, lets assume attachment B takes longer to load than attachment C. If I rapidly select attachment B then C, it'll complete rendering of C in my viewer **then replace it with B**.

My guess is that I need to somehow cancel rendering of B. Is the only way to do this to unmount the component doing the rendering?

**Comment by wojtekmaj** [comment]
Thanks @kog13 - I think fix in 4f63fdb will fix this issue. You can try and use master branch until it's released, to confirm.
