### ISSUE TITLE
Can I Reuse an Existing React Component inside of react-pdf Document component?

### ISSUE THREAD

**Issue by thedanchez** [wojtekmaj/react-pdf#359]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Convert an existing React component (and all of it's styles) into a PDF document. For the purposes of this question, let's call this already existing component `<ProfilePage />`. This component is made up of your normal React element primitives: `<div>`, `<p>` etc.

**Describe solutions you've tried**

Putting `<ProfilePage />` as a child of `<Document>` and `<Page>`

```
<Document>
  <Page>
    <ProfilePage />
  </Page>
</Document>
```

**Additional information**

This is my first time getting into creating PDF printable pages on the web so I am a real newbie when it comes to this. The `react-pdf` documentation isn't really clear in answering certain questions for me. The biggest one being, when it comes to this idea of creating PDFs, do we have to essentially create **two** versions of our component -- one using normal React primitives and the other using `react-pdf` primitives?

Because in my mind, I already have a designed view in my web app. All I want to do is print out that component as is. I'm hoping I can reuse said component inside of `react-pdf` but I have a sinking feeling that I'm thinking about this all wrong and I may have to re-implement my view using the primitives of this library.

## Update 1 -- Another Sub-Question

Also, how would I go about adding a download PDF button experience using `react-pdf`? My thinking was if I have a download PDF button on my page, all I would have to do is trigger `ReactPDF.render(<DocumentWrappedProfilePage />, '${__dirname}/example.pdf');` in the button's `onClick` handler. 

Is this thinking correct?

**Comment by pxFIN** [comment]
Question, are you sure you are not mixing up two different projects using same name ?

Other one is:

https://github.com/diegomura/react-pdf

https://react-pdf.org

If I understood correctly you are talking about creating PDFs rather than like this library viewing PDFs ?

**Comment by thedanchez** [comment]
🤦‍♂️ 

Wow -- you are correct. I mixed up the two projects, hahaha! And to answer your other question, yes, I'm talking about creating PDFs from an existing React component.
