### ISSUE TITLE
"Failed to load PDF file." when using a URL.

### ISSUE THREAD

**Issue by theHasanas** [wojtekmaj/react-pdf#36]
Hello Wojciech Maj,

I have an issue trying to load PDFs from a URL.
I am using latest version react-pdf, with the latest version of create-react-app.

Console output: XMLHttpRequest cannot load "http://example.com/sample.pdf" due to access control checks.

Thank you in advance!

**Comment by theHasanas** [comment]
Ah, I realised I wasn't reading the full console message :D 
I think I just needed to enable CORS on my server.

**Comment by wojtekmaj** [comment]
Hey,
is that URL in the same origin as your app? If not, you're yet another victim of [Same-origin policy](https://en.m.wikipedia.org/wiki/Same-origin_policy). In this case, you would need to either copy PDF on your server or build a simple proxy to pass the file through your server. If your app has to display one specific PDF you can also include it via Webpack in your bundle (I'm doing that on test suite).

**Comment by theHasanas** [comment]
You're indeed right. I am retrieving the URLs from Firebase Storage.

I am a web development newbie; could you please link to a guide on how I could setup a proxy with create-react-app that would serve this purpose? Also, does it matter that I am using Firebase, or would any guide on connecting to an API _(for example)_ suffice?

Out of curiosity, why are images exempt from this policy?

Thank you for the quick reply 👍

**Comment by wojtekmaj** [comment]
Hey,
you won't be able to do it on front-end side. You will need a proxy in Node or PHP or something similar. That's completely not connected to the app you're building :( 

It doesn't matter which server you're connecting to. Basically, as long as it's not yours, you will have a problem.

**Comment by saman** [comment]
You run a server with [cors-anywhere](https://github.com/Rob--W/cors-anywhere/).

Or simply use 
```
https://cors-anywhere.herokuapp.com/http://any-url.com/any-file.pdf
```

**Comment by theHasanas** [comment]
Ahh, I was just an idiot. I thought Node was unhappy with the file, but it was Firebase. I just followed the [documentation](https://cloud.google.com/storage/docs/cross-origin) by Google.

Thank you anyway!
