### ISSUE TITLE
PDF not rendering despite onLoadSuccess triggered

### ISSUE THREAD

**Issue by acollazomayer** [wojtekmaj/react-pdf#360]
Hi Im having a problem. I load a pdf with this library. The onLoadSuccess is triggered. But the Document does not render.

I dont know what else to do. I just copy the example page.

Thanks

**Comment by wojtekmaj** [comment]
Any errors in the console?

**Comment by acollazomayer** [comment]
@wojtekmaj. No no errors on console. It might be a stupid thing. But its driving me crazy. There is nothing indicating that something goes wrong. The on error functions are not being called either.

**Comment by niktnikt** [comment]
I have a similar issue. Instead of rendering the Pdf it says "Failed to load PDF file"
In the console i get:

> pdf.worker.js:1 Uncaught SyntaxError: Unexpected token <
> index.js:1446 Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".
>     at eval (pdf.js:11664)

**Comment by BF-man** [comment]
Have the same issue. No errors at all. Some of pdf are rendered correctly, some not just white canvas instead of pages

**Comment by wojtekmaj** [comment]
@niktnikt See #52, #321 

If others have this precise message also see these issues I mentioned above.

**Comment by AmyshaDixon** [comment]
I have the same issue and it is very. very. frustrating.

**Comment by acollazomayer** [comment]
@AmyshaDixon yeah, I decided not to render anything.

**Comment by AmyshaDixon** [comment]
@acollazomayer I ended up using [react-pdf-js](https://www.npmjs.com/package/react-pdf-js) instead just until this issue gets fixed. It doesn't have all the bells and whistles that this one does, but it gets the job done in the meantime.

**Comment by wojtekmaj** [comment]
If the issues mentioned are not helpful at all, and you don't see any errors in the console, or any network errors, check this Wiki entry:

https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions#i-render-document-but-nothing-is-rendered-why

If that fails too, I'm going to need a minimum reproduction on something like CodeSandbox.

**Comment by jaquesgrobler** [comment]
If it's of any help to anyone, I had the exact problem - no errors, but nothing rendering.

Added 
```
<Page pageNumber={1} />
```

And it worked. Thanks @wojtekmaj for the links

**Comment by balu4k** [comment]
i am facing the same issue too. work around of adding the Page tag works but now how i do make it to display all the pages

**Comment by Ashutoshsardesai** [comment]
index.js:1375 Error: Setting up fake worker failed:
how do i fix this? plz help me i am stuck with this.

**Comment by wojtekmaj** [comment]
> i am facing the same issue too. work around of adding the Page tag works but now how i do make it to display all the pages

That's not a workaround, that's a solution.

Check this recipe: https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages

**Comment by wojtekmaj** [comment]
> i am facing the same issue too. work around of adding the Page tag works but now how i do make it to display all the pages

@balu4k That's not a workaround, that's a solution.

Check this recipe: https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages

**Comment by JaredClayborn** [comment]
@jaquesgrobler Thanks, that worked.

**Comment by rizwan92** [comment]
it occurs when we do ssr at backend and then server the page

**Comment by WebXPujan** [comment]
> If it's of any help to anyone, I had the exact problem - no errors, but nothing rendering.
> 
> Added
> 
> ```
> <Page pageNumber={1} />
> ```
> 
> And it worked. Thanks @wojtekmaj for the links

yes adding <Page pageNumber={1} /> inside <Document> component works like a charm

**Comment by tskweres** [comment]
I have tried everything, pageNumber={1} etc. 

No errors, nothing renders :(

**Comment by Muhamed23** [comment]
@tskweres add this one

import { pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js`;

**Comment by GabrielNexT** [comment]
Any solution?

I am using React 17 and react-pdf 5.7.2.
The source code is hosted together with a Django project.

```
Error: Setting up fake worker failed: "Cannot read properties of undefined (reading 'WorkerMessageHandler')".
    at pdf.js:12326:1
```

**Comment by tuannguyensn2001** [comment]
> If it's of any help to anyone, I had the exact problem - no errors, but nothing rendering.
> 
> Added
> 
> ```
> <Page pageNumber={1} />
> ```
> 
> And it worked. Thanks @wojtekmaj for the links

that works for me, thanks
