### ISSUE TITLE
Can't resolve '@babel/runtime/regenerator' in monorepo

### ISSUE THREAD

**Issue by benabbon** [wojtekmaj/react-pdf#361]
**Before you start - checklist**

 - [X] I followed instructions in documentation written for my React-PDF version
 - [X] I have checked if this bug is not already reported
 - [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**

The 4.0.3 version fails with runtime error on npm start (during webpack compilation):
```
pdfjs-dist/2.1.266/node_modules/pdfjs-dist/lib/web/ui_utils.js
Module not found: Can't resolve '@babel/runtime/regenerator' in '/pdfjs-dist/2.1.266/node_modules/pdfjs-dist/lib/web'
```

In 4.0.2, adding babel-runtime as a dependency did the trick. Now I'm unable to have it working any other way.

**Steps to reproduce**

Update from 4.0.2 to 4.0.3.
Not reproducible on the sample project.

**Expected behavior**

I don't expect a failure.

**Additional information**

I found some issues talking about a similar error, but nothing on 4.0.3 with no workaround.
I tried the webpack entry without any luck.

**Environment**

 - React-PDF version 4.0.3:
 - React version 16.8.3:
 - Webpack version 4.29.3:
 - Typescript version 3.3.3

**Comment by wojtekmaj** [comment]
That's very odd, we have [`@babel/runtime` explicitly added to dependencies](https://github.com/wojtekmaj/react-pdf/blob/master/package.json#L84) 🤔 

`/pdfjs-dist/2.1.266/node_modules/pdfjs-dist/lib/web` path looks odd, too. Normally, the file in question would have been found in `node_modules/pdfjs-dist/lib/web/ui_utils.js` or at least `node_modules/react-pdf/node_modules/pdfjs-dist/lib/web/ui_utils.js`. Something is wrong here.

**Comment by benabbon** [comment]
The code is in a mono repo with multiple packages. The reference is done inside one of the packages. I can provide more info, I just need to know what info to provide.

**Comment by benabbon** [comment]
I also tried forcing @babel/runtime as my package dependency but that didn't solve the issue.

**Comment by wojtekmaj** [comment]
This doesn't look typical to me at all!

In this case I guess that your resolver would look for `@babel/runtime` in `/pdfjs-dist/2.1.266/node_modules/@babel/runtime`. If you have it in `/node_modules/@babel/runtime`, it likely won't work.

Perhaps you could use Webpack's [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/) to work around this issue?

**Comment by benabbon** [comment]
Thank you @wojtekmaj . As you pointed it to be only a dependency issue when having react-pdf as a third level dependency, I was able to make it work, with adding @babel/runtime as a dependency of the root project (not the cleanest way, but works). I haven't tried the Provide plugin, but it looks like it would work for me as well, I'll give it a try as it would be cleaner.

**Comment by benabbon** [comment]
Appreciate your reactivity and thank you for this repository, it's really cool! I'll be happy to contribute if need be.
