### ISSUE TITLE
PDF background image with text elements in front

### ISSUE THREAD

**Issue by chamatt** [wojtekmaj/react-pdf#362]
**Before you start - checklist**

 - [V] I have read documentation in README
 - [V] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [V] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'd like to have a background image on my PDF, and have text elements appear in front of it.

**Describe solutions you've tried**

I've seen a similar bug report which said he was using like this: 
background: {
      position: "absolute",
      minWidth: "100%",
      minHeight: "100%",
      display: "block",
      height: "100%",
      width: "100%"
}

It worked, the image filled the whole page, and didn't force the text to the next page, BUT it appears in front of the text, instead of behind.
I tried using zIndex, with no luck.

**Environment**

 - Chrome 72
 - React-PDF 4.0.3
 - React 16.8

**Comment by wojtekmaj** [comment]
Hi,
there's no way of doing it. You could position the layers in a way you would "squeeze" a background image between `<canvas>` and `TextLayer`, but there's no way to make PDFs transparent.

**Comment by Dan-X** [comment]
Hi,
is it possible to use this API to set canvas transparent? so one can add the highlights 'behind' instead of 'above' the text?

https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L887
https://github.com/mozilla/pdf.js/pull/8413/files

**Comment by kenrhe** [comment]
Try below:
```
    backgroundImg: {
      position: 'absolute',
    },
```

```
   <Document>
      <Page size="LETTER" orientation="landscape">
        <Image
          src="...replace me ..."
          style={styles.backgroundImg}
        />
        <Text>
          Lorem Ipsum
        </Text>
      </Page>
   </Document>
```
