### ISSUE TITLE
Cannot Render PDF dynamically

### ISSUE THREAD

**Issue by mebitek** [wojtekmaj/react-pdf#365]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I use react-pdf with webpack. I have a form with file input but when I set the file parameter of Document I get no errors but no pdf rendering (it's stucked at "Loading PDF…")

if I normal import react-pdf as import { Document, Page } from 'react-pdf'; I get the pdf not rendered and this error:  Error: Setting up fake worker failed: "Cannot read property 'setup' of undefined".

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.

I'm trying to load a pdf from base64 string or ArrayBuffer because I have no pdf to save in a server, jsut a file to upload in memory.

**Describe solutions you've tried**
react-pdf is not owrking also if I put an url in the file parameter

function to handle pdf preview content. preview variable holds the pdf content.
```  private handlePdfPreview = () => {
    const content = this.fileReaderBase64.result as string;

    // const blob = new Blob([content], {type: 'application/pdf'});
    
    this.setState({preview:  content});

  };
```

her ethe html part:
```
                <Document file={this.state.preview} />
```

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]: ^4.0.3
 - React version [e.g. 16.3.0]:16.5.2
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.5.0

**Comment by diegohdez90** [comment]
Also, I am interested in how load pdf content dynamically.

**Comment by boehlke** [comment]
Hello,
judging from the source code in
https://github.com/wojtekmaj/react-pdf/blob/master/src/Document.jsx#L237 
your use case should be supported. Probably more information would be helpful... please provide a stacktrace or even the complete example code reproducing the problem.

> react-pdf is not owrking also if I put an url in the file parameter

This looks like there is a basic problem with your setup.

**Comment by jneuendorf** [comment]
Hey @mebitek, I have a similar scenario in Atom (edtior) which is Chrome-based. There I get 2 warnings:

1. `Loading PDF as base64 strings/URLs might not work on protocols other than HTTP/HTTPS. On Google Chrome, you can use --allow-file-access-from-files flag`
2. `You are running React-PDF from your local file system. PDF.js Worker may fail to load due to browser's security policies. If you're on Google Chrome, you can use --allow-file-access-from-files flag for debugging purposes.`

My problem seems to be related to trying to display local files (see https://github.com/wojtekmaj/react-pdf/issues/265) but for me a base64 data URI (`data:application/pdf;base64,...`) is not working either. So I am currently not sure if using data URIs as `file` prop in general is buggy. But as far as I've looked into the code, I agree to what @boehlke said...

**Comment by TroyWolf** [comment]
I am just starting my journey/struggle to create my "simple" PDF viewer solution in my app. I generate PDF's dynamically in the browser.

Reading the source code, it sure looks like the "file" property can accept a url, blob, arrayBuffer, dataURI, and more.

https://github.com/wojtekmaj/react-pdf/blob/master/src/Document.jsx#L224

I want to pass either an arrayBuffer of a dataURI, so we shall see! :coffee:

**Comment by louis123562** [comment]
I tried to pass an URL, but that does not work. A NodeJS script returns a PDF file as string, but i always get a 404. Putting the URL in Browser, it wants me to downlaod it. What do i need to do?

**Comment by iang0ld** [comment]
If a PDF is saved to local storage as a base64 string can we load it from there and then save back to local storage as a base64 string (after form fields are filled).  The purpose being to implement offline PDF forms.

**Comment by Vishwas-93** [comment]
I am trying to load the pdf document into my react application from an external source via Axios GET. But, facing issues passing the data into <Document/> as props. It complains if I convert it into Array Buffer/ Base 64. How do I pass the URL? Any help will be really appreciated.

**Comment by wollo** [comment]
On my side I pre-load the next pdfs from the server inside the memory as raw data during the user is reading the current pdf and supply this raw data later to the pdf renderer as raw data. So you might try to base64 decode your data before sending it to your pdf component?

**Comment by louis123562** [comment]
I got my problem fixed meanwhile... Make sure your webservice headers are really application/pdf and nothing else.

**Comment by robmarshall** [comment]
@louis123562 How did you fix this?

**Comment by robmarshall** [comment]
No worries @louis123562 

For anyone who needs this. I pulled my PDF in using Axios with the following GET options:

```
responseType: 'blob',
headers: {
       Accept: 'application/pdf',
},
```

Then converted the file into a base64 string using this function I had for something else:

```
export default async function fileToBase64(image) {
    return new Promise((resolve, reject) => {
        const reader = new FileReader()
        reader.onload = value => {
            resolve({ success: true, data: reader.result })
        }
        reader.onError = error => {
            resolve({ success: false, error })
        }
        reader.readAsDataURL(image)
    })
}
```

Then grabbed the base64 string and passed that into the file prop of the component.

Loverly.
