### ISSUE TITLE
Render PDF on button click

### ISSUE THREAD

**Issue by nilay-patel044** [wojtekmaj/react-pdf#366]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
So basically I want to load PDF's on request (button click?) rather than lazy loading via return.

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.
I want to display the content in different languages. So the user would click button 1 to load pdf in language 1 and button 2 to load pdf in language 2.
**Describe solutions you've tried**
I have tried abstracting the following excerpt into a function of the class component:

```
<Document
  file={this.state.album.pdfFILE}
  onLoadSuccess={this.onDocumentLoadSuccess}
  options={options}
>
{
  Array.from(
    new Array(numPages),
    (el, index) => (
      <Page
        key={'page_${index + 1}'}
        pageNumber={index + 1}
      />
    ),
  )
}
</Document>
```

and in the script loaded at the bottom of the file, I have a callback(?) as below:
```
handlePDFLoad={() => this.handlePDFLoad(this.state.PDFfile)} // or basically the location of the file.
```

No luck. I think I am missing the logic here. I would appreciate any help. Also, I am new to React so I could be missing a core concept.

Describe solutions you've already tried, if any. Make sure to include code samples if you're stuck on implementation.

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**
Mac OS Mojave

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Chrome 57.
 - React-PDF version [e.g. 3.0.4]: Latest (4.0.2)
 - React version [e.g. 16.3.0]: (React 16.3.2).
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by wojtekmaj** [comment]
So if I understand correctly, you wouldn't like to load React-PDF until the button is clicked?

**Comment by nilay-patel044** [comment]
Thank you for getting back to me and for maintaining this project.

Yes. That's correct. I was actually able to figure it out using a isFileDisplayed flag initiated as false in the state. Then wrote a function to check if the flag changed. If it did, then call this.setState on it. In the render call, I have wrapped the entire document tag within a ternary operator with appropriate checks for the flags. At the bottom, I have set an arrow function call to the above-mentioned function. Within the file which the script refers to, I am calling that function on onClick event listener.

Now I wonder whether It's possible for me to display the PDF in multiple languages (two different pdfs) using the same onClick event listener and the button?

**Comment by wojtekmaj** [comment]
So you would need something like this...

```js
const noComponent = () => null;
// For now, these components will be just placeholders
let Document = noComponent;
let Page = noComponent;

class MyComponent extends Component {
  state = {
    isLibraryLoaded: false,
  };

  // loads React-PDF asynchronously
  loadReactPDF = () => {
    const { isLibraryLoaded } = this.state;

    if (isLibraryLoaded) {
      // We don't need to load the library twice
      return;
    }

    import('react-pdf').then(ReactPDF => {
      // one of these lines should work, depending on your configuration:
      ({ Document, Page } = ReactPDF);
      ({ Document, Page } = ReactPDF.default);
     
      // let MyComponent know it's now okay to render React-PDF
      this.setState({ isLibraryLoaded: true });
    });
  }

  // on button click, set an URL in component state and load React-PDF
  onButtonClick = (urlToDisplay) => {
    this.setState({ urlToDisplay });
    this.loadReactPDF();
  };

  render() {
    return (
      <div>
        <button onClick={() => this.onButtonClick(URL_1)}>Load URL_1</button>
        <button onClick={() => this.onButtonClick(URL_2)}>Load URL_2</button>
        {isLibraryLoaded
          ? (
            <Document file={urlToDisplay}>
              {/* Put Page component(s) here, or whatever else you want to display */}
            </Document>
          )
          : (urlToDisplay ? "Loading React-PDF..." : "Choose a PDF to load")}
      </div>
    );
  }
}
```

This code is not tested at all, wrote it as I was thinking. Should give you an idea on how to do some stuff. :)

**Comment by wojtekmaj** [comment]
I'm closing this issue to give other issues more visibility. If you still need assistance with this matter, please do not hesitate to reply and I'll reopen.

Happy coding!

**Comment by santrajyadav196** [comment]
Hello,   

how can i do same things using functional components. but i have an array, which is mapped, i want to generate pdf of mapped item after button is clicked. but i dont want to render all the pdf docs before clicked. after clicked i want to render selected pdf and generates it and downloads it. i have array, which items is very large which make my application slow down. i also want that props will pass in pdfdocs component after user clicked to download. Please help me
