### ISSUE TITLE
Rendering extra stuff on canvas

### ISSUE THREAD

**Issue by boehlke** [wojtekmaj/react-pdf#367]
Hello,
I would like to have a hook for drawing onto the page canvas.
My use case is adding widgets to a PDF to support PDF based business workflows like digitally signing PDFs.
Thank you in advance. And thanks for maintaining this project.

**Comment by wojtekmaj** [comment]
You could wrap `<Page>` in your own wrapper with additional content 🤔

**Comment by boehlke** [comment]
Thank you for the help! I will try different approaches. Probably I will just render extra HTML on top of the pages instead of directly rendering in the canvas.

**Comment by wojtekmaj** [comment]
That's definitely the best way to go :) Treat Canvas like they were images.
