### ISSUE TITLE
I'm not able to see PDF in My web page. 

### ISSUE THREAD

**Issue by chinnasamya-tudip** [wojtekmaj/react-pdf#368]
**Before you start - checklist**

 - React-PDF version: 4.0.3 also tried with 3.0.6 and 3.0.5
 - React version: 16.2.0
 - Webpack version: 3.1.0
-copy-webpack-plugin: 5.0.0

**Description**
PDF is loaded. I'm able to see on the network tab(PDF loaded successfully).
But the Web page is not showing PDF UI.
But Loading PDF is showing after it shows blank

**Comment by wojtekmaj** [comment]
Can you provide a snippet from your implementation?

**Comment by chinnasamya-tudip** [comment]
![file](https://user-images.githubusercontent.com/33785083/53641487-23155c80-3c55-11e9-8136-75567e630e7f.png)
![file-structure](https://user-images.githubusercontent.com/33785083/53641493-29a3d400-3c55-11e9-9929-9fdd5155bb31.png)
![network-tab](https://user-images.githubusercontent.com/33785083/53641503-2dcff180-3c55-11e9-991c-3f941f71dbf7.png)
![ui-pdf](https://user-images.githubusercontent.com/33785083/53641509-36282c80-3c55-11e9-851e-990c9e03f94f.png)
![webpack-config](https://user-images.githubusercontent.com/33785083/53641513-39bbb380-3c55-11e9-9576-19cd513526a7.png)

**Comment by wojtekmaj** [comment]
You're "rendering" document with no pages. `<Document>` only gives you a context to read the pages from using `<Page>` components. Please read documentation carefully :)

**Comment by chinnasamya-tudip** [comment]
Ohhh..<Page  /> component is not optional.. 
It's working. 
Thanks, @wojtekmaj.
