### ISSUE TITLE
Getting cors error even though the fetch is returning 200

### ISSUE THREAD

**Issue by varand-pez** [wojtekmaj/react-pdf#370]
**Before you start - checklist**

 - [ x ] I have read documentation in README
 - [ x ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [ x ] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
Load a PDF via external URL. 
Both the external url and my localhost have the same origin path, that is configured in etc file. But I get CORS error. 

Here is the interesting part, in the networks tab I can see that the pdf is fetched with 200, but right after that the cors error is thrown in the console.

I'm sure of my localhost setup because I can finely import images to react components via same assets url.

**Describe solutions you've tried**
Tried passing it with url object {url: https//....} , but no luck.
Tried switching to regular import vs webpack, but no luck.
import { Document, Page } from 'react-pdf/dist/entry.webpack';
vs
import { Document, Page } from 'react-pdf';

**Additional information**
See attached screenshot.

**Environment**
 - Browser (if applicable) [Chrome latest]:
 - React-PDF version [4.0.5]:
 - React version [16.4.0]:
 - Webpack version (if applicable) [4.11.1]:

![cors](https://user-images.githubusercontent.com/47469980/53787515-f91d9d80-3ed3-11e9-8eac-ef2c8b326d02.png)

**Comment by varand-pez** [comment]
Any insight to this?

**Comment by varand-pez** [comment]
I gave the possibility that there is a CORS issue when trying to fetch from s3, but it fails on publicly available pdf too, such as `http://www.africau.edu/images/default/sample.pdf`. looking for other solutions, since I haven't received any response.

**Comment by wojtekmaj** [comment]
Hey,
I see that clearly you're downloading PDF from a different origin your app is on. In terms of CORS there's nothing that wasn't already told and there's nothing React-PDF specific. 

You need to download PDF from exact same domain. Or create a proxy. Or configure the server PDF is on to send appropriate headers to support CORS requests.

**Comment by prasagungg** [comment]
how to solve this problem ?, i have same error

**Comment by usamamashkoor** [comment]
Did anyone find a solution for this problem?

**Comment by Ali-Khamis** [comment]
This problem is from the PDF providers because they closing the CORS, for example, this [pdf](https://tetra4d.com/wp-content/uploads/2018/12/PartList-Helico.pdf) should work because they are not closing the CORS.
We had the same problem with our PDF providers and we fixed it by making the backend guy allow the CORS throw Nginx which we are using.

**Comment by little-buddy** [comment]
same issue. 
Some people told me that I need to modify the pdfjs source code, 
and others told me that I need to obtain the pdf through ajax first,
and then pass it in the form of blob. 
I think react-pdf can be encapsulated with another layer for corresponding processing and compatibility.

**Comment by wojtekmaj** [comment]
React-PDF can't work around browsers blocking requests according to Cross-Origin Resource Policy. As previously stated:

* _You need to download PDF from exact same domain_ - same origin, no cross-origin issues.
* _Or create a proxy_ - if file is on a different origin, create a proxy to it on the same origin. Browsers will be happy.
* _Or configure the server PDF is on to send appropriate headers to support CORS requests_ - If you have control over the server that hosts the PDF, you can add `Access-Control-Allow-Origin` HTTP header to let browsers know it's okay to download the file from this origin.
