### ISSUE TITLE
Works locally, but  on server preview shows loading ... and doesnt change.

### ISSUE THREAD

**Issue by sesanka** [wojtekmaj/react-pdf#371]
It works as expected when i run locally. But on my server it keeps saying loading PDF ... 
Also locally i see there is a get request to the url to get the pdf file, but on the server there is no request to get the pdf from url.

Code: 

```
this.state = {
      numPages: null,
      pageNumber: 1,
}

onDocumentLoadSuccess = ({numPages}) => {
    console.log(numPages);
    this.setState({numPages});
}

render() {
    return (
...
<Row>
          <Col xs={12}>
            Test Preview pdf.
          </Col>
          <Document
            file={"https://gsi.berkeley.edu/media/sample-recommendation-letter.pdf"}
            onLoadSuccess={this.onDocumentLoadSuccess}>
            <Page height={150} scale={1} pageNumber={1}
                  onLoadProgress={this.onLoadProgress}/>
          </Document>
</Row>
)
}
```
Local device: 
![image](https://user-images.githubusercontent.com/8713168/53961338-a2d57800-40e8-11e9-80c0-fbf1d883871c.png)

![image](https://user-images.githubusercontent.com/8713168/53961410-c8628180-40e8-11e9-9427-0b550c226aa2.png)

Server: 
![image](https://user-images.githubusercontent.com/8713168/53961536-2000ed00-40e9-11e9-9847-f4a73f4b20c3.png)

and no requests to fetch pdf.

**Comment by wojtekmaj** [comment]
No requests at all? Hmmm, did `pdf.worker.js` got loaded correctly on the server?

**Comment by sesanka** [comment]
![image](https://user-images.githubusercontent.com/8713168/54348302-0a3f7a80-4649-11e9-8c46-0aca78593bbc.png)
Yes I think so.

**Comment by wojtekmaj** [comment]
Any errors in the console? Any network errors? Try and hook to `onLoadError` prop to see if React-PDF is not crashing, perhaps?

**Comment by cbaron** [comment]
A similar thing is happening to me.

```
import { Page, Document } from 'react-pdf/dist/entry.webpack';
```

No request is being made to get the worker.

**Comment by alex-shamshurin** [comment]
Worker has been built built separately, outside of main entry and not included referenced from main.js and not linked from react-pdf.

**Comment by UX-Unicorn** [comment]
Did anyone figure out how to fix this?

**Comment by cbaron** [comment]
The following worked for me in webpack v4 production build:

```import { Page, Document } from 'react-pdf/dist/entry.webpack';```

For the webpack-dev-server we went with:

```import { Page, Document } from 'react-pdf';```

**Comment by UX-Unicorn** [comment]
@cbaron That worked thanks

**Comment by leonardo2204** [comment]
@cbaron How did you do that? Where can I put these different imports?
Thanks!
