### ISSUE TITLE
Cancel Rendering Task

### ISSUE THREAD

**Issue by seanfrisbey** [wojtekmaj/react-pdf#374]
Pages load and render properly for me, but when I skip pages quickly, they all load, and they all render, taking a long time to actually render the page I skipped to. The `<Page />` is being passed the page number, very much list the "single page with navigation" recipe.

Logging on page load and page render, it appears that the loage loads rather quickly, but the render takes a while, and never cancels the render for each page before it. Please see the attached GIF.

Am I doing something wrong? Is this a limitation of something?

![PageLoadAndRender](https://user-images.githubusercontent.com/19792336/54392302-86938700-4664-11e9-9f79-3bcfce5fdca6.gif)

**Environment**
Chrome: 72.0.3626.121
React-PDF: 3.0.6
React: 15.6.2
Webpack 2.6.1

**Comment by seanfrisbey** [comment]
😭

**Comment by wojtekmaj** [comment]
Hmmm, we already cancel rendering tasks, when I look at `PageCanvas.jsx` 🤔 Do you think there's something wrong with the implementation? Also have you tried the newest version?

**Comment by seanfrisbey** [comment]
With your implementation? There might it is a possibility. When I was trying to step through your code, when checking to see if it should cancel the render task, it appeared as though the reference to the render task when for the NEW page, not the page currently being rendered. Very rarely would I actually catch it checking the PREVIOUS page's render task.

I can't easily try out the new version, as our application is stuck on React 15 at the moment. I will see if I can try a demo app on the side to exercise this behavior.

**Comment by seanfrisbey** [comment]
I created a new sample app and tried with a generic PDF using React 16 and the latest version of react-pdf. The issue is still present. The log logs when a page is loaded and rendered, and it appears that all pages render, even if they were skipped over. Check out the link to the project below.

https://github.com/seanfrisbey/test-react-pdf

**Comment by seanfrisbey** [comment]
Heya! Have you had a chance yet to check out the demo app?
