### ISSUE TITLE
issue with pdf.worker.js not found

### ISSUE THREAD

**Issue by umakantp** [wojtekmaj/react-pdf#375]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
Load a simple base64 encoded pdf data. It shows the PDF but it throws error in console that "http://localhost:3000/test/pdf.worker.js 404 (Not Found)"

Well I do not really want to use worker for simply showing small one page document, it's already much faster for me.

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.
I would like to display simple one page pdf in react.

**Describe solutions you've tried**
I simply imported react-pdf's document and page. Included them in the render function and passed based64 encoded string to file attribute of document tag.

I do not want to use worker, how do I stop from throwing error in console. "http://localhost:3000/test/pdf.worker.js 404 (Not Found)"

**Environment**

 - Browser - Chrome (Any versiona literary)
 - React-PDF version - 4.0.5:
 - React version - 16.3.1 :
 - Webpack version (if applicable) - 4.17.1:

**Comment by wojtekmaj** [comment]
Hi,
are you using Webpack-specific entry (see README)?

If yes, that's an odd problem 🤔 

If no, then try it. If Webpack-specific entry file won't make it for you, try and use CopyWebpackPlugin to copy pdf.worker.js file manually (see README [Standard instructions](https://github.com/wojtekmaj/react-pdf#browserify-and-others)). If all else fails, try and use workerSrc to download worker from a CDN.

**Comment by morsmodr** [comment]
I am getting a 414 - Request URI Too Large error

What I have done so far:
Webpack config got updated to this:

```
entry: {
  main: './src/index.js',
  'pdf.worker': 'pdfjs-dist/build/pdf.worker.entry',
},
output: {
  filename: `[name].bundle.js`,
  path: path.resolve(__dirname, 'dist/'),
  publicPath: '/dist/',
},
```

This automatically updated my manifest.json to include pdf.worker.bundle.js.
I serve static assets for React SPA separately from my app server, which is not Node, or Next JS

In my PDFViewer Abstract component, I did this

```
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
import { pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = '/dist/pdf.worker.bundle.js';
```

And on page load, pdf.js is making some weird call like so:
![Screen Shot 2021-10-12 at 5 48 42 PM](https://user-images.githubusercontent.com/7231256/137048728-36b331cb-108a-41b5-bc7e-acab7ab80b4a.png)

Can someone provide a summary of steps with 5.x version? Thanks in advance :)
