### ISSUE TITLE
Problems with onLoadProgress

### ISSUE THREAD

**Issue by martin-gazzara** [wojtekmaj/react-pdf#376]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

Hello!! My name is Martin.

I have problems with Page’s prop onLoadProgress.

To test simply, I put two alerts as callback inside onLoadProgress and onLoadSuccess. When passed down a pdf file inside Document, only the alert inside onLoadSuccess was called.

```
import React, { Component } from 'react';
import { Document, Page, pdfjs } from 'react-pdf';
import './App.css';

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

class App extends Component {
	constructor(props) {
		super(props);
		this.state = {
			file: null
		};
		this.handleChange = this.handleChange.bind(this);
	}

	handleChange(e) {
		this.setState({ file: e.target.files[0] });
	}

	render() {
		const { file } = this.state;
		return (
			<div className="App">
				<div>
					<input type="file" onChange={this.handleChange} />
				</div>
				<Document file={file}>
					<Page
						pageNumber={1}
						width={300}
						onLoadProgress={() => alert('progress')}
						onLoadSuccess={() => alert('success')}
					/>
				</Document>
			</div>
		);
	}
}

export default App;

```

**VERSIONS**

React 16.8.4

React-PDF 4.0.5

 
Thanks so much!

**Comment by wojtekmaj** [comment]
Hey,
it's a wild guess, but I suppose there's no "progress" here. The file is already loaded when provided, so React-PDF is like "not loaded - BAM! - loaded". If you tried to download a file from an URL, I think you would get onLoadProgress callback.

**Comment by martin-gazzara** [comment]
I tried to link an URL (as result of FileReader.readAsDataURL), but the onLoadProgress never is called. Neither it is called if I import the pdf file and pass it down to Document.

**Comment by wojtekmaj** [comment]
In both cases you imported/loaded the file yourself, and you're passing it in loaded form to React-PDF. onLoadProgress would only kick in if there's something to load, meaning _download_.
