### ISSUE TITLE
Incorrect letter spacing

### ISSUE THREAD

**Issue by sarahabuteen** [wojtekmaj/react-pdf#377]
I'm displaying a PDF inside my app and it's getting displayed but I'm facing an issue with an odd letter spacing in it as shown in the attached screenshot, and below is the code of implementation, i would like to know what might be causing this issue and if there is a solution for it.

<img width="592" alt="Screen Shot 2019-03-21 at 5 12 54 PM" src="https://user-images.githubusercontent.com/38786874/54762948-c2e35c00-4bfd-11e9-9774-0e93bad04807.png">

```javascript
import { Page, pdfjs, Document } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${
  pdfjs.version
}/pdf.worker.js`;

  constructor(props) {
    super(props);
    this.state = {
      numPages: null,
      pageNumber: 1
    };
  }

  onDocumentLoadSuccess = ({ numPages }) => {
    this.setState({ numPages });
  };

  render() {
    const { pageNumber, numPages } = this.state;

       <Document
                  file="https://hemma.ams3.cdn.digitaloceanspaces.com/pdf/demo.pdf"
                  onLoadSuccess={this.onDocumentLoadSuccess}
                >
                  <Page pageNumber={pageNumber} />
                </Document>
}
```

 - Browser: Version 72.0.3626.121 (Official Build) (64-bit)
 - React-PDF version: 4.0.5
 - React version: 16.8.4
 - Webpack version: 4.28.3

**Comment by wojtekmaj** [comment]
How this PDF looks like when you open it in Firefox?

**Comment by sarahabuteen** [comment]
@wojtekmaj it looks the same as the attached image

**Comment by sarahabuteen** [comment]
@wojtekmaj any updates about this please?

**Comment by wojtekmaj** [comment]
If this looks the same in Firefox, then please [report it to Mozilla](/mozilla/pdf.js/issues/new) instead, and please attach the file you have issues with. It will be very helpful for them.

**Comment by wojtekmaj** [comment]
Closing as there's nothing we can do on React-PDF side.
