### ISSUE TITLE
Implementing text search with React-pdf

### ISSUE THREAD

**Issue by benrudolph** [wojtekmaj/react-pdf#379]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'm attempting to implement text search with React-PDF. I've gotten myself pretty far down a rabbit hole trying to determine how I can leverage `PDFFindController` with react-pdf. I have a working instance of a PDFFindController, but I'm trying to determine how to get it to wrap the text in spans of `highlight` as the example pdfjs viewer does: https://mozilla.github.io/pdf.js/web/viewer.html

I'm curious if I'm going down the wrong path as the `executeCommand` method on the `findController` does not seem to return anything. It seems to fire off an event. I'm not sure if I'm supposed to setup some sort of listener that will then store the result and use `customTextRenderer` to do the rest.

**Describe solutions you've tried**

See above

**Additional information**

N/A

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version 4.0.5
 - React version 16.8.3
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by benrudolph** [comment]
(realize there are a few open [tickets](https://github.com/wojtekmaj/react-pdf/issues/189) around this. just curious if you know if it's possible to use the PDFFindController)

**Comment by wojtekmaj** [comment]
I think it's highly unlikely for PDFFindController to be implementable. React-PDF uses PDF.js rendering mechanism, but the concept of "PDF Viewer" is simply not there. In fact React-PDF does not aim to be a fully-fledged PDF viewer at all, however it would certainly allow to make one powered by it.

**Comment by benrudolph** [comment]
Got it thanks for the feedback. Yea - I went down the route of reverse engineering what PDFViewer is doing and how it works. For now ended up just utilizing the PDFViewer though agree somewhat restrictive, but provides a lot of things for free, like scrolling to the matched word and lazy loading. Closing out.
