### ISSUE TITLE
Access to Worker using webpack

### ISSUE THREAD

**Issue by ramusus** [wojtekmaj/react-pdf#38]
Using react-pdf 1.8.3 with webpack in hot reload mode. When I do `import ReactPDF from 'react-pdf/build/entry.webpack'` I get this error in Chrome:

```
Uncaught DOMException: Failed to construct 'Worker': Script at 'http://xxx:1235/assets/bundles/2c5a72550051ee999dc4.worker.js' cannot be accessed from origin 'http://yyy:8886'.
```

In Safari: 

```[Error] SecurityError (DOM Exception 18): The operation is insecure.```

I found possible solution https://stackoverflow.com/questions/37718656/why-does-not-chrome-allow-web-workers-to-be-run-in-javascript but didn't check if it works

**Comment by ramusus** [comment]
If I switch to `import ReactPDF from 'react-pdf';` I get react-pdf working, pdf are displayed correctly, but in console I see errors:

`main-65994a5782162ef05092.worker.js:1 GET http://xxx:1235/assets/bundles/main-65994a5782162ef05092.worker.js 404 (Not Found)`

`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (main-65994a5782162ef05092.worker.js, line 0)`

Am I doing something wrong?

**Comment by wojtekmaj** [comment]
Hi! Interesting - are http://xxx:1235/ and http://yyy:8886 really different? If so, React-PDF will indeed fail to run. If they are different, your browser's security features will prevent it from executing the code. Loading it in a way you proposed won't really help because the script won't be able to load the file containing the worker anyway.
More about it here: https://en.wikipedia.org/wiki/Same-origin_policy

**Comment by ramusus** [comment]
@wojtekmaj yep, they are different, because I'm using node server in hot reload mode to serve static for Django application.

When I use regular import `import ReactPDF from 'react-pdf'` it tries to find `worker.js` file, but fails with 404 error due to absence of path - it searches in the same folder and obviously find nothing.

**Comment by wojtekmaj** [comment]
Oh boy. You will need to change the configuration of your http://xxxx:1235 server to pass a proper [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) header to allow http://yyy:8886 access. That should do the trick, but I'm not 100% sure - let me know if it worked, there should be a note on that in documentation :)

**Comment by ramusus** [comment]
I solved this issue by creating proxy in Django, which points to node server makes assets accessible under one host `http://yyy:8886`
