### ISSUE TITLE
sharepoint framework webpart

### ISSUE THREAD

**Issue by nilokillian** [wojtekmaj/react-pdf#382]
I am building a webpart using SharePoint SPFx and was wondering if you could help me with the issue I faced trying couple react-pdf and SharePoint framework.

When I try rendering pdf the error is : 

fetch_stream.js:100 GET https://[].sharepoint.com/_layouts/15/JVBERi0xLjQNCiX15Pb8DQoNCjkgMCBvYmoNCjw8IC9UeXBlIC9YT2JqZWN0DQovU3VidHlwZSAvSW1hZ2UNCi9OYW1lIC9JMQ0KL1dpZHRoIDExODINCi9IZWlnaH 4

UnexpectedResponseException {name: "UnexpectedResponseException", message: "Unexpected server response (400) while retrieving 

I get that the issue is about concatenating pdf base64 with domain name "https://[].sharepoint.com/_layouts/15/"

I'm not sure how to put the pdf directly to the worker.

This is how I handled import 

```
import { Document, Page, pdfjs } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${
  pdfjs.version
}/pdf.worker.js`;
```

**Environment**

 - React-PDF version:  4.0.5
 - React version : 16.7.0
 - @microsoft/sp-webpart-workbench: 1.8.0
 - @microsoft/rush-stack-compiler-3.0: 0.5.9
 - gulp: 3.9.1

**Comment by wojtekmaj** [comment]
Hi,
I don't think you can merge URLs and base64. Pick one.
