### ISSUE TITLE
Text Overlay on demo site doesn't match the pdf in chrome

### ISSUE THREAD

**Issue by aleyan** [wojtekmaj/react-pdf#388]
On http://projects.wojtekmaj.pl/react-pdf/ the text overlay extends over the bounds of the svg image in chrome 73, making it unselectable. It is also broken in Firefox 66, but because svg is selectable, it is less obvious.

**Comment by wojtekmaj** [comment]
Thanks for pointing that out! Indeed, I was not specifying current Page width and relied only on CSS, which works fine for SVG and Canvas but not for the text layer. Turns out you can forget how your own libraries work, too :D

Fixed in production.
