### ISSUE TITLE
noData does not accept function

### ISSUE THREAD

**Issue by b-asaf** [wojtekmaj/react-pdf#390]
Hi,
I am using `v4.0.5` of this package and according to the Docs `noData` prop can receive a function but when I tried it I got an error.

* I think that its not supported yet by looking at the `Document.jsx` code.

Thanks

**Comment by wojtekmaj** [comment]
Yeah, the way I documented it is wrong, I agree. I wrote that you can pass:

* React element: `<div>Please select a page.</div>`
* Function: `this.renderNoData()`

Mind the `()`. I meant that you could extract whatever logic you're using to render "No Data" and pass a *result* of this function like so: `noData={this.renderNoData()}`.

When in fact, in the latter example you are passing a React element, eventually, too. Gonna fix this.

**Comment by wojtekmaj** [comment]
Next version will support *actual* function passed to `error`, `loading` and `noData` props in Document and Page. Documentation was also fixed to reflect this.
