### ISSUE TITLE
I'm getting Module parse failed error in my react application

### ISSUE THREAD

**Issue by joshglenn** [wojtekmaj/react-pdf#391]
I'm getting this error:

```
./node_modules/react-pdf/src/Outline.jsx 22:8
Module parse failed: Unexpected token (22:8)
You may need an appropriate loader to handle this file type.
| 
| export class OutlineInternal extends PureComponent {
>   state = {
|     outline: null,
|   }
```

despite having read #146 despite overriding webpack's config as follows:

```
/* config-overrides.js */
module.exports = function override(config, env) {

  config.module.rules.push({
    test: /\.pdf$/,
    loaders: ['url-loader'],
  });
  return config;
}
```

Note: My react app was created with create-react-app. Rather than eject the app, I am overriding webpack's config as described at https://github.com/timarney/react-app-rewired

**Comment by joshglenn** [comment]
I have also tried

```
config.module.rules.push({
    test: /\.pdf$/,
    use: 'url-loader',
    
  });
```

**Comment by wojtekmaj** [comment]
How are you importing react-pdf exactly?

Looks like you're using source code and not compiled production code. You shouldn't do that.

If you for some reason insist of using source code instead of production code, e.g. you're experimenting with the code and would like to see your changes in action: Your solutions are completely unrelated and won't help with this issue. What you need is to configure Babel to parse your node_modules/react-pdf directory, and add @babel/plugin-proposal-class-properties.

But really, don't.

**Comment by joshglenn** [comment]
Ok.  I didn't know that. I just copy-and-pasted from the recipes section of the repo.

So I changed the import statement to `import { Document, Page } from 'react-pdf';`

Now, it just says **Failed to load PDF file.** in the part of the page where I want the PDF to be rendered.

So, at the moment, my entire code looks like this:

```
import React, { Component } from 'react';
import { Document, Page } from 'react-pdf';
import samplePDF from './sample.pdf';

class CatalogViewer extends Component {
  render() {
    return (
      <Document
        file={samplePDF}
        onLoadSuccess={this.onDocumentLoadSuccess}
      >
        <Page pageNumber={1} />
      </Document>
    );
  }
}

export default CatalogViewer;
```

I installed react-pdf using npm.

**Comment by joshglenn** [comment]
This might give a clue:

<img width="1225" alt="Screen Shot 2019-04-24 at 2 18 14 PM" src="https://user-images.githubusercontent.com/6953274/56687440-e8033880-669b-11e9-8e3b-7ac51230822e.png">

The pdf file is the sample.pdf from the repo example here: https://github.com/wojtekmaj/react-pdf/tree/master/sample/webpack

**Comment by joshglenn** [comment]
I have not figured out the solution to this. The error still happens when I try to use a pdf file using a local url (without the http://). So, the workaround was to use an absolute url (http://example.com/path/to/the/document.pdf). Going to close this issue now.

**Comment by wojtekmaj** [comment]
Thanks for the info - fixed the recipe not to use /src path.

Loading local files will not work in another way than through file input - browsers will prevent webpages from accessing your local machine.
