### ISSUE TITLE
Using Redux and connected components within <Document>

### ISSUE THREAD

**Issue by awlevin** [wojtekmaj/react-pdf#392]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Create a connected component with `connect(...)` for a component within `<Document>` so I can use Redux selectors/memoization to create `<View>`s that form a table within a PDF.

**Describe solutions you've tried**

The table populates and styles correctly when I pass props into the component that holds the `<Document>` or `<PDFViewer>`, for example:

```

const Container = ({ array }) => (
  <PDFViewer>
    <Document>
      <Page>
        <View style={styles.tableArea}>
          {array.map( data => <View><Text>data.text</Text></View> )}
        </View>
      </Page>
    </Document>
  <PDFViewer>
)

```

but with this approach, I can't use my selectors / memoization for the table entries. What I want is to do something like:

```
<View>
  {array.map( (_, index) => <ConnectedComponent rowIndex={index} />}
</View>
```

and have 

```
const ConnectedComponent = ({ computedFields }) => (
  <React.Fragment>
    <View>
      <Text>computedFields.leftColVal</Text>
    </View>
    // etc. for other column
  </React.Fragment>
)

const makeMapStateToProps = () => {
    const getComputedFields = makeGetComputedFields();
    const mapStateToProps = (state, props) => {
        return {
            computedFields: getComputedFields(state, props)
        }
    }
    return mapStateToProps;
}

export default connect(makeMapStateToProps)(ConnectedComponent)

```

But I keep getting `Could not find "store" in the context of "Connect(InvoiceDocument)"`. What's weird is that this error goes away when I omit the outer `<PDFViewer/>` or `<PDFDownloadLink>`, but then obviously the `<Document>` won't display with any of the styles I included.

I'm sorry if there's an obvious solution of which I'm unaware— I'm still fairly new to React/Redux. Also I just noticed that this library is intended for viewing PDF's rather than generating them.. but since I'm already 90% of the way there I'd really like to find a solution so I don't have to switch libraries 🙁.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: `Chrome 73.0.3683.103`
 - React-PDF version [e.g. 3.0.4]: `4.0.5`
 - React version [e.g. 16.3.0]: `16.8.6`
 - Webpack version (if applicable) [e.g. 4.16.2]: I think `4.28.3` (from checking `node_modules/webpack/package.json`'s `"_from: ..."` field ... I used `create-react-app` for this project)

**Comment by awlevin** [comment]
I was able to work around this by creating a container for my custom `<Document>`, connecting the container to redux, and then feeding the props naturally from the container. A little annoying, but it definitely works! :smiley:

**Comment by leonelmeque** [comment]
Hey, how are you, it looks I am having the same issue with react pdf and I quite can't seem to solve the issue, can you share and example of what you did to resolve this issue?

**Comment by maitedev** [comment]
Hello I am having the same issue with react pdf, can you share and example of what you did to resolve this issue?

**Comment by wojtekmaj** [comment]
Hello, this ticket is invalid because it's raised in an invalid repository. This is not @react-pdf/renderer, this is the original React-PDF which quite the opposite purpose.

**Comment by AmadaWeldTechEU** [comment]
> I was able to work around this by creating a container for my custom `<Document>`, connecting the container to redux, and then feeding the props naturally from the container. A little annoying, but it definitely works! 😃

This works for me. I guess the the component of react-pdf does not act like what a normal component works by rendering.
