### ISSUE TITLE
PDFlink service for internal links fails in pdf document

### ISSUE THREAD

**Issue by CyranMS** [wojtekmaj/react-pdf#393]
**What are you trying to achieve? Please describe.**

I have a pdf that has a link to another page in the same pdf. I can click the link` (a href="#%5B%7B%22num%22%3A17%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C0%2C540%2C0%5D"), `
but then my viewer fails with error msg:
`"PDFLinkService.navigateTo: "[object Object]" is not a valid page reference, for dest="[object Object],[object Object],0,540,0"."`

My code:
```
          <Document
            externalLinkTarget="_blank"
            file={file}
            loading={<Loader invertColor />}
            onItemClick={this.onItemClick}
            onLoadSuccess={this.onDocumentLoadSuccess}
            onLoadError={error =>
              this.renderError(`Error while loading document: ${error}`)
            }
            options={{
              cMapUrl: 'cmaps/',
              cMapPacked: true
            }}
          >
            <Hammer onSwipe={this.handleSwipe} onTap={this.handleTap}>
              <div
                style={{
                  width: '100%',
                  height: '100%',
                  alignItems: 'center',
                  justifyContent: 'center',
                  userSelect: 'text'
                }}
              >
                {isThumbnailViewOpen && thumbnailView}
                {cachedPageDimensions && (
                  <Page
                    {...this.getPageDimensions(currentPage)}
                    scale={scale}
                    pageNumber={currentPage}
                    loading={<Loader />}
                    renderInteractiveForms={true}
                    // eslint-disable-next-line react/jsx-boolean-value
                    renderTextLayer={true}
                    onLoadError={
                      error =>
                        console.error(
                          error
                        ) /* eslint-disable-line no-console */
                    }
                  />
                )}
              </div>
            </Hammer>
          </Document>
```

**Describe solutions you've tried**

So far I have no idea how to solve it, because I am confused why the link href looks so weird. I have checked documentation and found nothing helpful.

**Additional information**

I used this file:
[Balblablalbala2.pdf](https://github.com/wojtekmaj/react-pdf/files/3116760/Balblablalbala2.pdf)

**Environment**

 - Chrome 73
 - React-PDF: 4.0.5
 - React version: 16.3.1

**Comment by wojtekmaj** [comment]
Hi,
PDFLinkService will work only if the page you're trying to link to is already rendered. Since it's up to you which pages to render using React-PDF, if you don't have the page you're trying to link to already rendered, you will need to make that happen.

In such cases, internal links can be handled using `onItemClick`. Here's a simple recipe: https://github.com/wojtekmaj/react-pdf/wiki/Recipes#handle-external-links

Let me know if this helped you.

**Comment by CyranMS** [comment]
True, I completely missed that. Thanks @wojtekmaj

**Comment by wojtekmaj** [comment]
You didn't :D I added that just before I commented in this post. It's just that I thought it's a good thing to keep in recipe book since a lot of people would benefit from knowing it, so I wrote the answer there!
