### ISSUE TITLE
Can't render with blob

### ISSUE THREAD

**Issue by dkrefta** [wojtekmaj/react-pdf#394]
Hey guys, 

Can somebody help to render my pdf :/ 
I tried a lot of ways, but without luck, here my code:

```js
import { Document, Page } from 'react-pdf/dist/entry.webpack'

import { pdfjs } from 'react-pdf'

import 'react-pdf/dist/Page/AnnotationLayer.css';

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${
  pdfjs.version
}/pdf.worker.js`

// bla bla bla react code

           <Document
              file={uploadedFile.preview}
              onLoadSuccess={onDocumentLoadSuccess}
            >
              <Page 
              pageNumber={numPages} 
              />
            </Document>

```

the file comes like this: blob:56ce3c6d-67f5-4dea-8b9c-085624df494a

What I doing wrong right here?! :/

 -  "react-pdf": "^4.0.5",
 - "react": "^16.8.6",

**Comment by wojtekmaj** [comment]
The only thing I see wrong in your sample is that you're importing React-PDF twice - you should just import it using one of the entry files, so:

```js
import { Document, Page, pdfjs } from 'react-pdf/dist/entry.webpack'
```

**Comment by dkrefta** [comment]
Still not working :/

**Comment by dkrefta** [comment]
I forget to close, worked when I changed to Base64 👍

**Comment by rosgeorg** [comment]
Hello @dkrefta, I have the same issue, could you help me? what did you change to base64 to make it work??
