### ISSUE TITLE
PDF File not rendering if 'chrome' dev console not open?

### ISSUE THREAD

**Issue by Vanals** [wojtekmaj/react-pdf#396]
When opening  a page which renders a pdf file and the chrome console is closed I get an error:

/b898199c77b935089e6c.worker.js:1 Uncaught SyntaxError: Unexpected token }

If the DEV console is open this console error doesn't show in the console and the pdf file renders as expected.

1. Go to http://www.lostudenteim.it/procedure-infermieristica/procedura-preparazione-carrello-medicazione-ferite'

Then you should not see the PDF.
And you should see an error in the console(opening it after the refresh)

If you refresh the page with the dev console open the pdf file renders correctly.

**Expected behavior**

PDF file rendering indipendntly by the dev console open or not.

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser:  Chrome
 - React-PDF version [e.g. 3.0.4]: ^3.0.5
 - React version: 
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.4"

The app has been built using create-react-app originally.

UPDATE:   Now the issue seems gone, I don't anyway understand why it was keep happening.. and If I have to do something to avoid this happening randomy?  Thank you

**Comment by wojtekmaj** [comment]
Huh, tested on Firefox and Chrome newest versions, couldn't see the issue.

Opening dev console oftenly applies some additional rules, like always loading data from the server and not using cache, and similar. So maybe it was the case of some cached data in your browser, some time has passed and now you have your bundles up to date and always working? :)

I'm going to close this and if you need some React-PDF specific help I'll be happy to reopen.
