### ISSUE TITLE
Unable to load file from aws s3 pre signed URL

### ISSUE THREAD

**Issue by omitewary** [wojtekmaj/react-pdf#399]
Hello Wojciech Maj,

I have gone through existing issues related to  CORS. The domain I am requesting to has enabled CORS and has GET as well as POST in allowed method. I am still getting following error.
<img width="1440" alt="Screenshot 2019-05-08 at 9 42 54 PM" src="https://user-images.githubusercontent.com/7983935/57390557-47a02e80-71da-11e9-832c-7f6bef1e752e.png">

Now, here is what I am doing. I am basically fetching pre signed URL from aws s3 and then using this url in file props of Document. 

In my network tab I see that in pre flight request allowed method is POST. However pdf.js uses GET to load PDF. 

<img width="1440" alt="Screenshot 2019-05-08 at 9 50 05 PM" src="https://user-images.githubusercontent.com/7983935/57391614-846d2500-71dc-11e9-8cc3-369d94f04436.png">

As you can see **Access-Control-Request-Method: POST** . 
I tried sending httpHeader in file props as 

    <Document file= {{ url: 'URL',httpHeaders: {'Access-Control-Request-Method': 'GET', 
    "Access- 
    Control-Allow-Origin": "*"}, withCredentials: true }}
     onLoadSuccess={this.onDocumentLoadSuccess}
    renderMode="canvas">
    </Document>

But if I send like this then I am not seeing any pre flight request in network tab and CORS issue persist. 

Thank you in advance!

**Comment by gabrielnoal** [comment]
I had the same issue.
I solved using html iframe tag instead of using react-pdf.
```
<iframe style={{ <add your style here> }} src={'https://s3-sa-east-1.amazonaws.com/......'}/>
```

**Comment by pat-schoeps** [comment]
We're having the same issue, the service worker and library initialize correctly but fail to load resources from a presigned url. These files can otherwise be loaded successfully.

**Comment by MariuszKogut** [comment]
We came across this issue, using Azure BlobStorage and shared access signature.

**Comment by danpan1** [comment]
Solved the problem by changing CORS policy in s3 bucket https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-cors-configuration.html
CORS policy should be 
`<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Authorization</AllowedHeader>
</CORSRule>
</CORSConfiguration>

`

**Comment by frankyjuang** [comment]
Looks like the same as https://github.com/wojtekmaj/react-pdf/issues/370
Adding CORS policy to s3 bucket works. Thanks @danpan1

**Comment by jonahallibone** [comment]
For anyone here having this issue still, even with the correct CORS policy, we used the `source` option on the `Image` component to construct this:

`<Image
  style={styles.logo}
  source={{
    uri: logo,
    method: "GET",
    headers: {
    "Cache-Control": "no-cache"
    }
  }}
/>`

**Comment by clement-faure** [comment]
Still having issues on my side using : 

```
<Image
      source={{
        uri,
        header: {
          'Access-Control-Allow-Origin': '*',
          crossOrigin: 'anonymous',
        },
      }}
    />
```

Randomly working ...

CORS policy has been defined on S3 bucket : 

```
[
    {
        "AllowedHeaders": [],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```

**Comment by hwoo3303** [comment]
> I had the same issue. I solved using html iframe tag instead of using react-pdf.
> 
> ```
> <iframe style={{ <add your style here> }} src={'https://s3-sa-east-1.amazonaws.com/......'}/>
> ```

thank you I've tried several methods, but this is the one that helped me the most. 👍👍
