### ISSUE TITLE
`onParseError` and `onParseSuccess` seem to be abandoned

### ISSUE THREAD

**Issue by CodeDaraW** [wojtekmaj/react-pdf#400]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

In the document, `onParseError ` and `onParseSuccess` can be provided as props for `Outline` component, but they are not implemented in the source code.

**Describe solutions you've tried**
Nothing.

**Additional information**
Nothing.

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**
 - React-PDF version: 4.0.5

**Comment by wojtekmaj** [comment]
That's true - gone with a8064f2d51a156ef0549b580a9971d6ade91fbab. It shouldn't be in the documentation anymore. Thanks!
