### ISSUE TITLE
getting 2 pages instead of one

### ISSUE THREAD

**Issue by munichfeels** [wojtekmaj/react-pdf#402]
![Bildschirmfoto 2019-05-22 um 16 03 14](https://user-images.githubusercontent.com/35969989/58180931-2bf15980-7cab-11e9-8feb-7aa0b7ce763e.png)
I'm trying to iterate over an array of objects an create a single page for each, which works fine but somehow (even with just one <Page/> Element) i'm getting two pages for each iteration. One of them is completely empty.

```
const SingleTicket = () => {
            let pages = tickets.map((ticket) => (
               <Page size="A6" orientation="landscape">
                   <View>
                       <Text style={{}}>{ ticket.ticketname }</Text>
                   </View>
               </Page>
            ));

            return (
                <Document>
                    { pages }
                </Document>

            )
 };
```
Any idea what might cause this issue?
Thanks, Alex

**Comment by wojtekmaj** [comment]
Wrong repository. You probably mean @diegomura's `@react-pdf/renderer`.
