### ISSUE TITLE
Re-Render Error JS appendChildBefore after modify state

### ISSUE THREAD

**Issue by jbrat** [wojtekmaj/react-pdf#403]
Hello wojtekmaj, 

I have a problem with the @react-pdf/renderer functions : 
![image](https://user-images.githubusercontent.com/15637356/58559034-8433d880-8222-11e9-8c93-6ee8d72c1d74.png)

When i try to reload the PDFViewer Document when state update, the reac-pdf function try to do a "appendChildBefore" but it isn't a function in Javascript ? 

My Component : 
![image](https://user-images.githubusercontent.com/15637356/58559174-c9580a80-8222-11e9-9067-24d5089694de.png)

I have an array of pages, when i click on a checkBox (handleCheckPage) i can hide or show a page in the pdf. When the action of loadPages was call (modify status show on my pages) the state was updated and render the component, i have the error. 
At start the PDF loading correctly but when i try update state, it's fail. 

You should probably don't use a "appendChildBefore" function that doesn't exist in JS ? 

Thank you for answering,
Bye

**Comment by wojtekmaj** [comment]
Wrong repository. You probably mean @diegomura's `@react-pdf/renderer`.
