### ISSUE TITLE
How can i render the PDF file from input type file?

### ISSUE THREAD

**Issue by PrasannaBrabourame** [wojtekmaj/react-pdf#404]
I am having a website in react to upload PDF after uploading i just want to show the file in React PDF without saving the file to server is its possible? I am trying it out but i cant able to achieve this

**Comment by wojtekmaj** [comment]
Hi,
you need to use FileLoader to get File/Blob from a file input. Then you can pass the result to React-PDF.

**Comment by badazzdev** [comment]
> Hi,
> you need to use FileLoader to get File/Blob from a file input. Then you can pass the result to React-PDF.

First of all, many thanks for this great package.

Since a PDF upload with React is, in my opinion, one of the most used features of this package, should there be a little "guide" in the readme?

Unfortunately, I can't find any information on this, and I don't understand how I can load a PDF via an input field and display it with the preview.

Thanks!

**Comment by wojtekmaj** [comment]
That info is already outdated. You can pass file from `<input>`'s `event.target.files[0]` directly.

See sample:

https://github.com/wojtekmaj/react-pdf/blob/master/sample/webpack5/Sample.jsx

**Comment by badazzdev** [comment]
> That info is already outdated. You can pass file from `<input>`'s `event.target.files[0]` directly.
> 
> See sample:
> 
> https://github.com/wojtekmaj/react-pdf/blob/master/sample/webpack5/Sample.jsx

Thanks for your reply but that also does not work for me.

In the browser i get: `Failed to load PDF file.`
In the console i get: `Warning: Setting up fake worker.`

**Comment by badazzdev** [comment]
> > That info is already outdated. You can pass file from `<input>`'s `event.target.files[0]` directly.
> > See sample:
> > https://github.com/wojtekmaj/react-pdf/blob/master/sample/webpack5/Sample.jsx
> 
> Thanks for your reply but that also does not work for me.
> 
> In the browser i get: `Failed to load PDF file.`
> In the console i get: `Warning: Setting up fake worker.`

<img width="519" alt="Screenshot 2021-08-18 at 18 01 46" src="https://user-images.githubusercontent.com/26936893/129887222-4fbd49fc-4e9c-4109-83c0-27877e2f867f.png">

I have this but can't figure out how get things to work. Hope someone can help me out.

If i use:
`import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';`

I get this:

<img width="793" alt="Screenshot 2021-08-18 at 18 04 31" src="https://user-images.githubusercontent.com/26936893/129887514-e9808f0e-cfa3-46a5-8fbc-b6dce091c7fa.png">
