### ISSUE TITLE
Change Document.file url doesn't cancel the running task

### ISSUE THREAD

**Issue by chinalwb** [wojtekmaj/react-pdf#406]
In short: 
----
I read the [commits of 4.0.5](https://github.com/wojtekmaj/react-pdf/compare/v4.0.5...master), and I found there is a [commit: Cancel loading a document if we started loading another one](https://github.com/wojtekmaj/react-pdf/commit/4f63fdb0393c53143fb707b0cde5ba4df54a3d0a).
However this change has not been included into the release of 4.0.5.
I checked both my node_modules version and the [source code.zip](https://codeload.github.com/wojtekmaj/react-pdf/zip/v4.0.5), in both cases, there is no this statement:
```
try {
      // If another loading is in progress, let's cancel it
      cancelRunningTask(this.runningTask);
```
Which I can see in the master of Github version.

**Description**
Change the Document.file url still download and show the original file.

**Steps to reproduce**
Part of my code:
```
componentWillReceiveProps(nextProps) {
  const { url: thisUrl } = this.props
  const { url: nextUrl } = nextProps

  if (thisUrl !== nextUrl) {
    this.setState({
      pdfFile: { url: nextUrl }
    })
  }
}

...

render() {
  const { pdfFile } = this.state
  return (
   <Document
    file={pdfFile}
    onProgress={this.onLoadProgress}
    onLoadSuccess={this.onDocumentLoadSuccess}
    />)
}
```

1. I init this component with url A (file size 2 MB)
2. Then I update the component with url B (20 KB)

**Expected behavior**
1. Document A should stop loading when update url with document B
2. Document A won't be loaded, as the last request document is B

**Actual behavior**
1. Document A doesn't stop loading
2. Document A comes later than B, so user actual sees Document A, which is wrong

**Environment**

 - Browser (if applicable) [e.g. Chrome 74]:
 - React-PDF version [e.g. 4.0.5]:
 - React version [e.g. 16.8.6]:

** I think the issue will be resolved if 4.0.5 release with the correct code? **
Please help advise, thanks.

Thanks again for the lovely library.

**Comment by wojtekmaj** [comment]
This will be released in the next version. Indeed if you look at commit history, this commit was added after 4.0.5 release.

**Comment by chinalwb** [comment]
Thanks, I'll pay attention to the next release.

**Comment by wojtekmaj** [comment]
It's out! 4.1.0

**Comment by chinalwb** [comment]
Thanks.
