### ISSUE TITLE
Strange blank pages behavior

### ISSUE THREAD

**Issue by Angelk90** [wojtekmaj/react-pdf#409]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'm trying to create a pdf in which I have to put information like text and an image, the image will be of type "data: image/png;base64,VBORw0KG ....".

**Describe solutions you've tried**
```
<Text2>....<Text2>//Text2 as React text in page
<PDFViewer>
    <MyDocument />
  </PDFViewer>
```

**Additional information**

I get a pdf file of three pages, empty with nothing written.

@wojtekmaj : congratulations for the module, I hope to be able to use it.

**Comment by wojtekmaj** [comment]
Hi,
you've mistaken React-PDF for diegomura's react-pdf/renderer.
