### ISSUE TITLE
outline bug

### ISSUE THREAD

**Issue by ZevveZ** [wojtekmaj/react-pdf#412]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

**Description**
Outline not work when it is placed outside Document

**Steps to reproduce**
```
render(){
const { pdf } = this.state
return (
<div>
{pdf &&<Outline pdf={pdf} />}
<Document onLoadSuccess={(pdf)=>this.setState({pdf})}>
  <Page pageNumber={1}/>
</Document>
</div>
);
```

**Expected behavior**
I can see the outline content, but click not work, and there are some errors in console:
![image](https://user-images.githubusercontent.com/17964973/59625047-e66d6280-916a-11e9-93dd-5cadf362f5b7.png)
when I click the outline item, it shows this error:
![image](https://user-images.githubusercontent.com/17964973/59625065-f5541500-916a-11e9-8624-5bb3d1bcc00f.png)

**Additional information**
see above
**Environment**
 - Browser: Chrome 75.0.3770.80
 - React-PDF version : v4.1.0
 - React version: 16.8.6
 - Webpack version: 4.32.2

**Comment by wojtekmaj** [comment]
Please read README - https://github.com/wojtekmaj/react-pdf#outline

Outline needs to be inside `<Document>`.
