### ISSUE TITLE
Rendering PDF issue in MS Edge

### ISSUE THREAD

**Issue by leonHk** [wojtekmaj/react-pdf#416]
Hi,

I have an issue to display the PDF using react-pdf under MS Edge (MS Edge 44, MS EdgeHTML 18)
I found that the PDF text will be garbled in first time rendering.

Below is the example of displaying the PDF using react-pdf but garbled.
![1231231231](https://user-images.githubusercontent.com/46306814/60087631-f6d79b80-976f-11e9-8a0a-205976358bbc.png)

The PDF will be garbled in first time rendering only. PDF will resume normal If I zoom in or zoon out the PDF after first rendering.

May I know how to solve this? 

I checked that original PDF is fine and everything work fine under Chrome and Safari. The PDF will garbled MS Edge 44 only.

My react-pdf version is 4.0.2

Thanks,

Leon

**Comment by wojtekmaj** [comment]
Is the PDF displaying correctly in Firefox (I mean natively if you open the PDF in Firefox, not via React-PDF)? If yes, then we have some React-PDF issue, but if not, you should [report it to Mozilla](https://github.com/mozilla/pdf.js/issues/new).

Let me know!

**Comment by leonHk** [comment]
> Is the PDF displaying correctly in Firefox (I mean natively if you open the PDF in Firefox, not via React-PDF)? If yes, then we have some React-PDF issue, but if not, you should [report it to Mozilla](https://github.com/mozilla/pdf.js/issues/new).
> 
> Let me know!

Hi wojtekmaj,

Thanks. Firefox is display the PDF correctly.  
I try FIrefox like below code:
(var dataURI = "data:application/pdf;base64," +base64EncodedPDF;
  window.open(dataURI);)

This issue occur in MS Edge 44 (we updated to MS Edge 44 recently. Anything were fine in MS Edge 42 and 42 version)

**Comment by leonHk** [comment]
More information I found.

In my project, I need to copy pdf.worker.js to the root (if not, I will get the 404 error in pdf.worker.js)
![1312](https://user-images.githubusercontent.com/46306814/60311878-ac326b00-998b-11e9-9d00-125e25779496.JPG)

Therefore, I added the below code to webpacke
           new CopyWebpackPlugin([
                {
                  from: path.resolve('./node_modules/pdfjs-dist/build/pdf.worker.js'),
                  to: './'
                },
              ]),

I found that, the issue will disappear(seem) if I commented this CopyWebpackPlugin config.

**Comment by CyranMS** [comment]
I have the same issue with Edge 
Version: 
Microsoft Edge 44.18362.387.0. 
Microsoft EdgeHTML 18.18362
Text gets replaced by weird symbols. IE/Chrome/Firefox work fine.

**Comment by leonHk** [comment]
@CyranMS 
Yes, same problem.

**Comment by wojtekmaj** [comment]
I'm afraid I won't be able to help you if Mozilla isn't going to actively support IE11/Edge. React-PDF relies completely on Mozilla's work to render PDFs. I'm really sorry about that.
