### ISSUE TITLE
Add pdfjs to @types/react-pdf

### ISSUE THREAD

**Issue by jazzdragon** [wojtekmaj/react-pdf#417]
**Before you start - checklist**

 - [*] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [*] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

When importing pdfjs from the package (to define the remote worker) typescript can't compile because the definition doesn't exist on DefinitelyTyped

**Describe the solution you'd like**

Add the definition to the package

**Comment by wojtekmaj** [comment]
Maybe @CodeDaraW who created the types could be of any help?

**Comment by CodeDaraW** [comment]
You can import pdfjs from `pdfjs-dist` directly, that's the same thing.  
I didn't import the type definition of `pdfjs-dist`, you may can create a Pull Request for it.

**Comment by nikuda** [comment]
I added basic support for this by exporting `version` and `GlobalWorkerOptions` from `@types/pdfjs-dist`, and then exporting `pdfjs-dist as pdfjs` from `@types/react-pdf`.

```ts
import { Document, Page, pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc =
  `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
```

Example above now works in TypeScript.

**Comment by andredantasrocha** [comment]
Thanks for that! any idea when the new version will be released?

**Comment by nikuda** [comment]
This has been merged as is now available in `@types/react-pdf@^4.0.3`. Make sure to delete your `yarn.lock` file to get `@types/pdfjs-dist@^2.1.1` type changes as well.

Thanks @CodeDaraW for review.

**Comment by CodeDaraW** [comment]
Maybe @wojtekmaj can close the issue now.

**Comment by wojtekmaj** [comment]
Wow! Thanks so much to everyone involved.
