### ISSUE TITLE
How to prevent the white 'flash' while changing slides?

### ISSUE THREAD

**Issue by igoroctaviano** [wojtekmaj/react-pdf#418]
- [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

I'd like to display multiple pages of my PDF and move through them without white flash (dark background).

I tried changing the CSS.

**Environment**

 - React-PDF version: 4.0.5
 - React version: 16.8.6

**Comment by wojtekmaj** [comment]
You could render the new Page hidden using CSS, wait for `onRenderSuccess` on it, and only then remove the old page and show the new one.

**Comment by igoroctaviano** [comment]
Thank you.

**Comment by AkshayHere** [comment]
Can you please help me how to do this ?

**Comment by igoroctaviano** [comment]
> Can you please tell me how to do this?

So, in their **Page** component I have added the onRenderSuccess prop that sets a loading boolean state that I have created in my PDF component that uses their components:
`onRenderSuccess={() => { this.setState({ loading: false }); }}`
*The loading boolean default value is true.

Also, I added my custom default class to their page component: 
`className="react-pdf__Page"`
Which basically sets the Page component to display none until the loading boolean is false.

Then.. on their **Document** component I have added the native className prop:
`className={`pdf-document-viewer ${ !this.state.loading ? 'pdf-loaded' : '' }`}`
...which adds my custom css based on the loading state I created.

My custom CSS to remove the white flash: 
```
.react-pdf__Page {
  display: none;
}

 .pdf-loaded .react-pdf__Page {
  display: inline-block;
}
```

Summary: Start the Page component as display none until the onRenderSuccess is executed and sets the loading to false, then the pdf-loaded class is added in the page component which sets the display to inline-block, avoiding the whole flash thing.

**Comment by saadq** [comment]
Kinda similar so I wanted to avoid opening a new issue, is there a way to prevent the white flash when changing the `file` that is passed to the `<Document>` component? Right now I have [a website](https://resumake.io/generator/profile) that creates a PDF on the backend when you press the Make button and then sends that to the client which then updates the `file` attribute that is passed to `<Document>` with that new PDF. 

I'm not sure what would be the best solution to handle this, maybe a similar solution to switching pages (keeping the old document rendered until the new one has finished loading) but im not sure if that's possible.

**Comment by AkshayHere** [comment]
@saadq i follow the method mentioned for generating pdf where u generate a pdf file in backend server and render it my ui side. Actually if u notice u will get the white flash for the initial rendering of each pages & subsequent changes wont give u the flicker. 

I dont think there is a workable solution on this at the moment

**Comment by casulit** [comment]
@igoroctaviano can you share the codes regarding this issue? I follow your instruction still getting the flash when slide changes.

**Comment by wojtekmaj** [comment]
The best way to avoid flashing is to keep the previous page rendered on top of current page, until the next one is fully rendered:

[CodeSandbox](https://codesandbox.io/s/react-pdf-prevent-flash-nbikj)

```jsx
function Test() {
  const [numPages, setNumPages] = useState(null);
  const [prevPageNumber, setPrevPageNumber] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
    setPageNumber(1);
  }

  function onPageRenderSuccess() {
    // Now that the next page is rendered, we can get rid of previous page rendered on top of it
    if (prevPageNumber !== null) {
      setPrevPageNumber(null);
    }
  }

  function changePage(offset) {
    // Set current page number as previous page number
    setPrevPageNumber(pageNumber);
    setPageNumber(prevPageNumber => prevPageNumber + offset);
  }

  function previousPage() {
    changePage(-1);
  }

  function nextPage() {
    changePage(1);
  }

  return (
    <>
      <Document file={samplePDF} onLoadSuccess={onDocumentLoadSuccess}>
        {prevPageNumber && (
          <Page
            {/** 
              * IMPORTANT: Keys are necessary so that React will know which Page component
              * instances to use.
              * Without keys, on page number update, React would replace the page number
              * in 1st and 2nd page components. This may cause previously rendered page
              * to render again, thus causing a flash.
              * With keys, React, will add prevPage className to previously rendered page, 
              * and mount new Page component instance for the new page.
              */}
            key={prevPageNumber}
            className="prevPage" 
            pageNumber={prevPageNumber}
          />
        )}
        <Page
          key={pageNumber}
          pageNumber={pageNumber}
          onRenderSuccess={onPageRenderSuccess}
        />
      </Document>
      <div>
        <p>
          Page {pageNumber || (numPages ? 1 : "--")} of {numPages || "--"}
        </p>
        <button type="button" disabled={pageNumber <= 1} onClick={previousPage}>
          Previous
        </button>
        <button
          type="button"
          disabled={pageNumber >= numPages}
          onClick={nextPage}
        >
          Next
        </button>
      </div>
    </>
  );
}
```

```css
.react-pdf__Page.prevPage {
  position: absolute !important;
  z-index: 1;
}
```

**Comment by casulit** [comment]
@wojtekmaj awesome! thank you.

**Comment by unclebay143** [comment]
Still works! Thanks @wojtekmaj

**Comment by varunKT001** [comment]
@wojtekmaj 

Instead of positioning the `prevPage` absolutely, hiding the page while loading works better in my case.

```javascript
{isLoading && renderedPageNumber ? (
  <Page
    key={renderedPageNumber}
    pageNumber={renderedPageNumber}
  />
) : null}
<Page
  className={`${isLoading ? 'loadingPage' : ''}`}
  key={pageNumber}
  pageNumber={pageNumber}
  onRenderSuccess={() => setRenderedPageNumber(pageNumber)}
/>
```

```css
.react-pdf__Page.loadingPage {
  display: none;
}
```

_BTW, awesome library, I'm loving it!_

**Comment by Againyunn** [comment]
@wojtekmaj @varunKT001 
Thank a lot!

**Comment by BeaComp** [comment]
@wojtekmaj @varunKT001
thanks

**Comment by tducloc** [comment]
> The best way to avoid flashing is to keep the previous page rendered on top of current page, until the next one is fully rendered:
> 
> [CodeSandbox](https://codesandbox.io/s/react-pdf-prevent-flash-nbikj)
> 
> ```js
> function Test() {
>   const [numPages, setNumPages] = useState(null);
>   const [pageNumber, setPageNumber] = useState(1);
>   const [renderedPageNumber, setRenderedPageNumber] = useState(null);
> 
>   function onDocumentLoadSuccess({ numPages }) {
>     setNumPages(numPages);
>   }
> 
>   function changePage(offset) {
>     setPageNumber(prevPageNumber => prevPageNumber + offset);
>   }
> 
>   function previousPage() {
>     changePage(-1);
>   }
> 
>   function nextPage() {
>     changePage(1);
>   }
> 
>   const isLoading = renderedPageNumber !== pageNumber;
> 
>   return (
>     <>
>       <Document file={samplePDF} onLoadSuccess={onDocumentLoadSuccess}>
>         {isLoading && renderedPageNumber ? (
>           <Page 
>             {/** 
>               * IMPORTANT: Keys are necessary so that React will know which Page component
>               * instances to use.
>               * Without keys, on page number update, React would replace the page number
>               * in 1st and 2nd page components. This may cause previously rendered page
>               * to render again, thus causing a flash.
>               * With keys, React, will add prevPage className to previously rendered page, 
>               * and mount new Page component instance for the new page.
>               */}
>             key={renderedPageNumber}
>             className="prevPage" 
>             pageNumber={renderedPageNumber} 
>             width={400} 
>           />
>         ) : null}
>         <Page
>           key={pageNumber}
>           pageNumber={pageNumber}
>           onRenderSuccess={() => setRenderedPageNumber(pageNumber)}
>           width={400}
>         />
>       </Document>
>       <div>
>         <p>
>           Page {pageNumber || (numPages ? 1 : "--")} of {numPages || "--"}
>         </p>
>         <button type="button" disabled={pageNumber <= 1} onClick={previousPage}>
>           Previous
>         </button>
>         <button
>           type="button"
>           disabled={pageNumber >= numPages}
>           onClick={nextPage}
>         >
>           Next
>         </button>
>       </div>
>     </>
>   );
> }
> ```
> 
> ```css
> .react-pdf__Page.prevPage {
>   position: absolute !important;
>   z-index: 1;
> }
> ```

I have tried this solution but it will not work if you render more than one page. The second page will still be flicked. This is the [sandbox that I re-produce bug](https://codesandbox.io/p/sandbox/react-pdf-prevent-flash-with-scale-forked-6g82cd?file=%2Fsrc%2FApp.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clx2xpjxh00063b6mjtj7nfy7%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clx2xpjxg00023b6mjsa25ehk%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clx2xpjxh00033b6m7pp0r4ax%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clx2xpjxh00053b6mifsxu0aj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B64.6897092570924%252C35.3102907429076%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clx2xpjxg00023b6mjsa25ehk%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx2xpjxg00013b6mcu2dbqt0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clx30897l00733b6m5b61g54t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A89%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A89%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clx2xpjxg00023b6mjsa25ehk%2522%252C%2522activeTabId%2522%253A%2522clx30897l00733b6m5b61g54t%2522%257D%252C%2522clx2xpjxh00053b6mifsxu0aj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clx2xpjxh00043b6mfsme3xi6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clx2xpjxh00053b6mifsxu0aj%2522%252C%2522activeTabId%2522%253A%2522clx2xpjxh00043b6mfsme3xi6%2522%257D%252C%2522clx2xpjxh00033b6m7pp0r4ax%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clx2xpjxh00033b6m7pp0r4ax%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Escenda** [comment]
I handled it as follows:
By reducing the transparency during loading, I can make the user believe that the page is not switching because it is loading.

```jsx
<Document
  file={file}
  onLoadSuccess={onDocumentLoadSuccess}
>
  <Page
    className={`${isLoading ? 'opacity-50' : ''}`}
    key={renderedPageNumber}
    pageNumber={renderedPageNumber}
  />
  <Page
    className="hidden"
    key={pageNumber}
    pageNumber={pageNumber}
    onRenderSuccess={() => setRenderedPageNumber(pageNumber)}
  />
</Document>
```

**Comment by vitexikora** [comment]
Is this ever planned to get fixed and not have to use two <Page /> components? We have them inside a carousel and it is already pretty heavy to render.

**Comment by wojtekmaj** [comment]
There's nothing that can reasonably be done here on the react-pdf package side I'm afraid. As soon as the pageIndex/pageNumber prop changes, the component has to clean its state and display what's requested from it (or nothing while it's still rendering). Displaying stale content would create more problems than it would solve.

**Comment by vitexikora** [comment]
When you browse a PDF directly in pdfjs, there is no flicker issue on re-scaling. So I supposed there can be some better handling in react-pdf (e.g. only rescaling the text layer or so).
But even if not, I think it could at least shadow the current workaround of having to have two Page components over each other and cycle which one is visible. I think at least this could be included (maybe with a flag) in react-pdf if it is the only way to resolve the issue. And on some sunny day an update of pdfjs would fix it completely :)
