### ISSUE TITLE
View first page before entire document is loaded - support range header

### ISSUE THREAD

**Issue by joepio** [wojtekmaj/react-pdf#419]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

In our project ([issue](https://github.com/ontola/ori-search/issues/46), [demo](http://ori.argu.co/search?zoekterm=%22bundel%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F174530)), I'd like to load only the pages that I'm viewing, and render the first page before the entire document is loaded. 

From my understanding, PDF.js [supports Range headers](http://localhost:3000/search?zoekterm=%22bundel%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F174530) and the `react-pdf` API [describes](http://localhost:3000/search?zoekterm=%22bundel%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F174530) that it's possible to include a `PDFDataRangeTransport` object in the `file` property. I fail to see what to do to actually send these Range headers, though!

**Describe solutions you've tried**

- [x] Check if the source PDF is optimized for the web
- [x] Check if the hosting service supports HTTP Range headers 

**Environment**

- Chrome 75
- MacOS 10.14.5
- React-PDF 4.0.5
- React-scripts 3.0.1
- React 16.8.6

**Comment by wojtekmaj** [comment]
Hi,
Yeah, PDFDataRangeTransport should be supported, as React-PDF just passes it to pdf.js, does not much else with it. I found [this topic](https://github.com/mozilla/pdf.js/issues/10452) on PDFDataRangeTransport objects creation.

It seems like the easiest way to get the behavior you want is to simply pass an URL as `file` prop. This should work just fine: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#range

**Comment by joepio** [comment]
Thanks for the reply (and the awesome library, for that matter) @wojtekmaj!

Unfortunately, I do pass the URL as a file prop ([source](https://github.com/ontola/ori-search/blob/master/front/src/Components/PDFViewer.tsx), [demo](http://ori.argu.co/search?zoekterm=%22bundel%22&showResource=https%253A%252F%252Fid.openraadsinformatie.nl%252F240204)), but it only renders after the entire document has been fetched.

Also, the request for the PDF file does not appear have any range headers.

**Comment by joepio** [comment]
According to PDF.js developers, PDF.js [does not support `gzip` encoding of range responses](https://github.com/mozilla/pdf.js/issues/11027#issuecomment-518180185), so it needs to be set explicitly. According to the PDF.js [docs](https://mozilla.github.io/pdf.js/api/draft/global.html), you can set [custom headers](https://github.com/mozilla/pdf.js/blob/be70ee236d73e7d387bd7b08424436ede2f34b76/src/display/api.js#L133). Since Document passes the `options` object to `PDFjs.getDocument`, this should work:

``` jsx
<Document
  options={{
    httpHeaders: {
      'Accept-Encoding': 'Identity',
    }
  }}
  file={"https://example.com/some.pdf"}
>
```

**Comment by angel-langdon** [comment]
@joepio Did you manage to solve this issue?

I am using `FastAPI` as backend in `Python` and I think the problem is that `pdf.js` has an implementation of case-sensitive headers on the other hand, `FastAPI` has case insensitive headers and I think this is what is causing the problem

I have tried passing to `<Document/>` this sample URL (2 GB PDF) https://s3.amazonaws.com/pdftron/downloads/pl/2gb-sample-file.pdf 
and it loads the first page immediately

**Comment by joepio** [comment]
@angel-langdon never managed to get it working, unfortunately...

**Comment by angel-langdon** [comment]
@joepio Well I finally managed to do it, it was failing because of case-sensitive headers. Also, you need to specify all these headers to work properly:

```python
    headers = {
        "Content-Type": "application/pdf",
        "Accept-Ranges": "bytes",
        "Content-Encoding": "identity",
        "Access-Control-Expose-Headers": (
            "Accept-Ranges, Content-Length, Content-Range"
        ),
        "Content-Length": str(end-start +1),
        "Content-Range": f"bytes {start}-{end}/{file_size}"
    }
```

I would strongly recommend reading the Range Requests RFC https://datatracker.ietf.org/doc/html/rfc7233 to understand everything, there are a few gotchas

**Comment by bolosea** [comment]
> 



> @joepio好吧，我终于设法做到了，由于区分大小写的标头而失败了。此外，您需要指定所有这些标头才能正常工作：
> 
> ```python
>     headers  = {
>          "Content-Type" : "application/pdf" ,
>          "Accept-Ranges" : "bytes" ,
>          "Content-Encoding" : "identity" ,
>          "Access-Control-Expose-Headers" : (
>              "Accept-Ranges , 内容长度, 内容范围" 
>         ), "内容长度" : str ( end - start + 1 ),
>          "内容范围" : f"字节{开始} - {结束} / {
>          文件大小} "
>     }
> ```
> 
> 我强烈建议阅读 Range Requests RFC https://datatracker.ietf.org/doc/html/rfc7233以了解所有内容，有一些陷阱

hello are you write like this ？ 
` <Document
                        onSourceError={(error) => {
                            console.log('onSourceError', error)
                        }}
                        onLoadError={(error) => {
                            console.log('pdf load error', error)
                        }}
                        options={{
                            httpHeaders: {
                                'Content-Type': 'application/pdf',
                                'Accept-Ranges': 'bytes',
                                'Content-Encoding': 'identity',
                                'Access-Control-Expose-Headers': 'Accept-Ranges , Content-Length, Content-Range',
                                'Content-Length': '1000000',
                                'Content-Range': `bytes 0 - 999999 / 1000000`,
                            },
                        }}
                        file={'https://s3.amazonaws.com/pdftron/downloads/pl/2gb-sample-file.pdf'} />`

I found it dosen't work。。

**Comment by bolosea** [comment]
> @joepio好吧，我终于设法做到了，由于区分大小写的标头而失败了。此外，您需要指定所有这些标头才能正常工作：
> 
> ```python
>     headers  = {
>          "Content-Type" : "application/pdf" ,
>          "Accept-Ranges" : "bytes" ,
>          "Content-Encoding" : "identity" ,
>          "Access-Control-Expose-Headers" : (
>              "Accept-Ranges , 内容长度, 内容范围" 
>         ), "内容长度" : str ( end - start + 1 ),
>          "内容范围" : f"字节{开始} - {结束} / {
>          文件大小} "
>     }
> ```
> 
> 我强烈建议阅读 Range Requests RFC https://datatracker.ietf.org/doc/html/rfc7233以了解所有内容，有一些陷阱

hello, Are you write like this ？
`javascript 
 <Document
                       
                        options={{
                            httpHeaders: {
                                'Content-Type': 'application/pdf',
                                'Accept-Ranges': 'bytes',
                                'Content-Encoding': 'identity',
                                'Access-Control-Expose-Headers': 'Accept-Ranges , Content-Length, Content-Range',
                                'Content-Length': '1000000',
                                'Content-Range': `bytes 0 - 999999 / 1000000`,
                            },
                        }}
                        file={'https://s3.amazonaws.com/pdftron/downloads/pl/2gb-sample-file.pdf'}/>
`
I found it doesn't work for me。。

**Comment by angel-langdon** [comment]
@bolosea I don't know if not english characters are valid, see my updated answer for full details

**Comment by bolosea** [comment]
> @bolosea I don't know if not english characters are valid, see my updated answer for full details

thanks for your reply，but I don't backend。 and I found that url ' https://s3.amazonaws.com/pdftron/downloads/pl/2gb-sample-file.pdf'  in pdf.js example project can works as expected in [this]( https://mozilla.github.io/pdf.js/web/viewer.html?file=https%3A%2F%2Fs3.amazonaws.com%2Fpdftron%2Fdownloads%2Fpl%2F2gb-sample-file.pdf) 
what's happend?  
The weird thing is that it doesn't work when I download the pdf.js source code and run it with pdf.getDocument, I want to cry，QAQ
