### ISSUE TITLE
Base64 example

### ISSUE THREAD

**Issue by alphiii** [wojtekmaj/react-pdf#42]
The docs says that this lib supports base64 format, can some one show me an example.

**Comment by alphiii** [comment]
I already figure it out it is like: file={`data:application/pdf;base64,${<actual PDF base64 content here - starts with JVBER....> }`}

**Comment by gshilin** [comment]
My pdf file starts with
```
%PDF-1.6\r%����\r\n246 0 obj <</Linearized 1/L 473828/O 249/E 31049/N 64/T 468860/H [ 956 736]>>\rendobj\r             \r\nxref\r\n246 33\r\n0000000016 00000 n\r\n0000001692 00000 n\r\n0000001847 00000 n\r\n
```

**Comment by gshilin** [comment]
I my case I've got content of pdf file as %PDF and, as it includes non-latin1 characters I cannot convert it to base64.

**Comment by wojtekmaj** [comment]
@gshilin, you're reading binary file as a text file. That's a no-no :)

**Comment by gshilin** [comment]
Actually I receive it from server

**Comment by gshilin** [comment]
Actually I receive it from server (not node)

**Comment by wojtekmaj** [comment]
It doesn't matter what the source is. If you receive it from URL, then you should pass URL to `file` prop and you are done. If you want to read it yourself for some reason, you need to read it properly as a binary file.

**Comment by wojtekmaj** [comment]
@AdamOlevall, please provide me full error (with error stack) as well as your React-PDF version.

**Comment by AdamOlevall** [comment]
I get the following error stack when using `file="data:application/pdf;base64,JVBERSGVsbG8gV29ybGQh" ` :  
![error](https://user-images.githubusercontent.com/11074668/38237070-5e85b182-3726-11e8-9de4-23bf7f1493c4.PNG)
I updated React-PDF yesterday to 3.0.4

**Comment by wojtekmaj** [comment]
If that's really the whole thing you put in `file` prop, then the error is expected. `JVBERSGVsbG8gV29ybGQh` decodes to `%PDE!]ɱ` which certainly is not a valid content of PDF file as it should be :)

The easiest way to check if your PDF in base64 is valid is to paste the whole `data:application...` into your browser addres bar. If it "downloads" or opens the PDF, then you did it well.

On a side note, If you have a binary file, you don't need to encode it to base64. You can just pass it to `file` as is. It should be smart enough to figure it out.

**Comment by AdamOlevall** [comment]
Thanks for helping me out, the use of the browser address bar was a nice suggestion!
The base64 string I tried to use, SGVsbG8gd29ybGQ=, was the encoded string of "Hello world", and then I added the "JVBER" in front. Apperently that was something that it did not like. When I tried with a base64 string not generated by myself, it worked fine. Thanks once again :)

**Comment by praveenkgoswami** [comment]
I was facing the same issue.
Thanks for the solution, but I also need to download this pdf file after the conversion like an invoice.

**Comment by abtx** [comment]
Late to the party, but any ideas how can I use a base64 encoding to get an image inside of my `Document`? I have some Highcharts data in browser, and try to render it alongside other text on the client side. I successfully converted the Highcharts data to base64, but struggle to find a way to use it with react-pdf.

**Comment by wojtekmaj** [comment]
You can render anything within `<Document>`. `<Document>` just provides a context with a loaded PDF file to any `<Page>` components within.

**Comment by sbitproz** [comment]
I think you probably just need to update the documents with an example of using Base64.  I ran into the same issue but didn't realise I need to add **data:application/pdf;base64,** - no doubt - down to my own stupidity:

```
<Document
          file={`data:application/pdf;base64,${fileBase64}`}
          onLoadSuccess={onDocumentLoadSuccess}
>
```

Perhaps in the User guide > Document > File - add the following:

```
Base64 encoded:
          `data:application/pdf;base64,${fileBase64}`
or 
          ...file={`data:application/pdf;base64,${fileBase64}`}
```

Underneath:
```

Parameter object:
{ url: 'http://example.com/sample.pdf', httpHeaders: { 'X-CustomHeader': '40359820958024350238508234' }, withCredentials: true }
```

**Comment by wojtekmaj** [comment]
Added more detailed instructions to [Wiki](https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions#how-do-i-load-a-pdf-from-base640.

**Comment by sbitproz** [comment]
You are awesome!!!

**Comment by OOlashyn** [comment]
Hi @wojtekmaj ,
I have the issue when trying to use base64 - DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.".  I even tried to use your example from Wiki, but still got the same error. Attached you can find full error stack. I am on the 5.3.0 version of react-pdf.
[full-error-stack.txt](https://github.com/wojtekmaj/react-pdf/files/6452902/full-error-stack.txt)

**Comment by Jahangiralamice** [comment]
> If that's really the whole thing you put in `file` prop, then the error is expected. `JVBERSGVsbG8gV29ybGQh` decodes to `%PDE!]ɱ` which certainly is not a valid content of PDF file as it should be :)
> 
> The easiest way to check if your PDF in base64 is valid is to paste the whole `data:application...` into your browser addres bar. If it "downloads" or opens the PDF, then you did it well.
> 
> On a side note, If you have a binary file, you don't need to encode it to base64. You can just pass it to `file` as is. It should be smart enough to figure it out.

When I paste the whole base64 value into chorme browser its show my pdf file but face this problem and pdf file can not show..
Its show Loading PDF.........

![image](https://user-images.githubusercontent.com/31815273/122869267-d5edb500-d34d-11eb-895a-eb4eb868b0c3.png)

**Comment by Jahangiralamice** [comment]
Could anybody help me above error?

**Comment by Zeroxys** [comment]
@Jahangiralamice,I have the same log, did you find the solution ?

**Comment by BMwanza** [comment]
> I think you probably just need to update the documents with an example of using Base64. I ran into the same issue but didn't realise I need to add **data:application/pdf;base64,** - no doubt - down to my own stupidity:
> 
> ```
> <Document
>           file={`data:application/pdf;base64,${fileBase64}`}
>           onLoadSuccess={onDocumentLoadSuccess}
> >
> ```
> 
> Perhaps in the User guide > Document > File - add the following:
> 
> ```
> Base64 encoded:
>           `data:application/pdf;base64,${fileBase64}`
> or 
>           ...file={`data:application/pdf;base64,${fileBase64}`}
> ```
> 
> Underneath:
> 
> ```
> 
> Parameter object:
> { url: 'http://example.com/sample.pdf', httpHeaders: { 'X-CustomHeader': '40359820958024350238508234' }, withCredentials: true }
> ```

Thank you for this. I was inches away from giving up on this component.

The solution that is working for me is as follows:
```
import { Document, Page, pdfjs } from 'react-pdf'
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

....

<Document file={`data:application/pdf;base64,${contractPDF}`} onLoadSuccess={onDocumentLoadSuccess}>
    {Array.from(new Array(numPages), (el, index) => (
        <Page key={`page_${index + 1}`} pageNumber={index + 1} />
    ))}
</Document>
```
The server was returning `dataapplication/pdfbase64` as the base64 prefix, and I assumed that it would work this way. However, the base64 prefix needs to be formatted as `data:application/pdf;base64`.

Using `react-pdf@6.1.0`
