### ISSUE TITLE
Proposal of another solution for CMap not using CopyWebpackPlugin to support non-italic characters

### ISSUE THREAD

**Issue by johejo** [wojtekmaj/react-pdf#420]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Hi,
I am a software engineer in non-English speaking areas. So I read the README suggestion to display non-latin characters.

**Describe solutions you've tried**

However, setting CopyWebpackPlugin is troublesome, so I set the remote URL of CDN to cMapUrl.
It went well to great things!
Isn't it worthwhile to include this method in README or other documentation?
Except that unnecessary HTTP requests are required.

**Additional information**

```tsx
<Document
    file={props.foo}
    onLoadSuccess={(pdf: PDFDocumentProxy) => { setNumPages(pdf.numPages); }}
    options={{
        cMapUrl: `https://cdn.jsdelivr.net/npm/pdfjs-dist@2.1.266/cmaps/`,
        cMapPacked: true,
    }}
>
```

If you feel that it is unnecessary, you may close the issue immediately.

(From Tokyo on the edge of East Asia)

**Comment by wojtekmaj** [comment]
Hi,
thanks, yeah, I think it's worth mentioning, definitely!

**Comment by qqhann** [comment]
I could not configure cMap as readme well.
And this works fine like a charm! Thanks!
