### ISSUE TITLE
provides Responsive Document/Page

### ISSUE THREAD

**Issue by mraiguo** [wojtekmaj/react-pdf#427]
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

Hope can provide the responsize layout，not a fixed width and height

**Comment by wojtekmaj** [comment]
Hi,
just like with images, you can use CSS or JavaScript to make the pages responsive. React-PDF is meant to be simple wrapper over Mozilla's pdf.js. pdf.js needs some width to render the page in the first place, but you can then resize canvas/PDF any way you like.
