### ISSUE TITLE
`dist` directory not installed.

### ISSUE THREAD

**Issue by reachtoakhtar** [wojtekmaj/react-pdf#433]
Hi,

I have forked the library and trying to install using git url since I need to do some customisation. It doesn't install the `dist` directory but when I use npm to install the original library it installs it.
Please help.

**Comment by wojtekmaj** [comment]
`dist` is not meant to be checked out. It's dynamically built code created during release only. You can build it yourself using `yarn build`, but I can't provide you with more support.
