### ISSUE TITLE
How do I run the test site

### ISSUE THREAD

**Issue by jmchn** [wojtekmaj/react-pdf#438]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I want to test react-pdf by using the test site. 

**Describe solutions you've tried**

I clean cloned the repo. npm update && npm install in both root dir and test dir. npm i yarn as well. It now builds in the root dir but doesn't build in ./test/ dir. 

**Additional information**
These are the two errors I got doing npm run build.
ERROR in ./Test.jsx
Module not found: Error: Can't resolve 'react-pdf/src/Page/AnnotationLayer.css' in 'C:\git\react-pdf\test'
 @ ./Test.jsx 26:0-48
 @ ./index.jsx
 @ multi ./index

ERROR in ./Test.jsx
Module not found: Error: Can't resolve 'react-pdf/src/entry.webpack' in 'C:\git\react-pdf\test'
 @ ./Test.jsx 25:0-70 373:29-37 388:39-46 394:35-39 401:31-35
 @ ./index.jsx
 @ multi ./index

**Environment**

 - React-PDF version [e.g. 3.0.4]: 4.1.0
 - React version [e.g. 16.3.0]: 16.9.0.
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.39.1

**Comment by wojtekmaj** [comment]
Hi there; below you can find a draft of `CONTRIBUTING.md`. Happy to hear your comments.

**Comment by wojtekmaj** [comment]
# Contributing to React-PDF

## Prerequisites

* [Node.js](https://nodejs.org/en/download/)
* [Yarn](https://yarnpkg.com/lang/en/)
* IDE of your choice (we're recommending [Visual Studio Code](https://code.visualstudio.com/))

## Before you start

* Search if the thing you'd like to work on has already been requested/reported in GitHub Issues.
  * If yes, note the issue number for later
  * If no, raise a new issue.
* Create a separate branch you will work on.

## Installation

* Fork the repository and clone it to your device.
* Run `yarn` command in `/` directory to install dependencies and dev dependencies.

## Development

[Test app](#manual-tests) should come in handy during development.

Your code should be covered by unit tests.

If you're fixing a bug, it's a good idea to start from writing a failing unit test (thus proving there is a bug), fix a bug and ensure that the test now passes.

You can run `yarn test-eslint --fix` to automatically format your code.

## Testing

React-PDF is tested using automated and manual tests.

### Automated tests

Run `yarn test` to run linter and unit tests.

### Manual tests

There is an app in `/test` directory which renders React-PDF with a few options you can play with. It's a separate project which requires React-PDF, but there's an easy way to see your changes there live as you code.

* Run `yarn link` in `/` directory.
* Run `yarn` in `/test` directory.
* Run `yarn link react-pdf` in `/test` directory.

Once you're done, running `yarn start` in `/test` directory should give you access to the test app under http://localhost:3000/.

Run the test app in several browsers and play around with different options.

### Committing

Make sure that [tests](#testing) are passing before you commit.

Commit message should preferably have the following format

```
Fix thing

Fixes #1234
```

where `#1234` is the number of the issue your contribution is related to.

**Comment by jmchn** [comment]
Manual testing works! Thanks !
