### ISSUE TITLE
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType

### ISSUE THREAD

**Issue by Filipvdb321** [wojtekmaj/react-pdf#44]
Hi,
When using the latest version I suddenly get this error which results in the pdf not loading:
The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType

When moving back to 1.6.1 the problem is solved.

**Comment by wojtekmaj** [comment]
Hey! I believe that's a problem with pdf.js itself and there's not much I can do.

See: https://github.com/mozilla/pdf.js/issues/6306
