### ISSUE TITLE
Provide a way to enable textLayerMode=2

### ISSUE THREAD

**Issue by jmchn** [wojtekmaj/react-pdf#440]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
From both the test & my local work I saw flicker in text selection. 
https://github.com/mozilla/pdf.js/issues/9168
I also found your reply in the pdf.js repo and I wonder if there is a way to enable the enhanceTextSelection/ textLayerMode = 2(lastest version). The  textLayerMode = 2 demo's selection was pretty smooth and would be ideal. 
Any idea how to achieve it?

**Describe solutions you've tried**
I've tried expanding the text span to make the selection more smooth but it's going to be very hacky. Right now if you click and drag to a point where the curse is out of a span, the selection would jump to the top. 

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

React-PDF version [e.g. 3.0.4]: 4.1.0
React version [e.g. 16.3.0]: 16.9.0.
Webpack version (if applicable) [e.g. 4.16.2]: 4.39.1

**Comment by jmchn** [comment]
https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf
The example that uses textLayerMode = 2 .

**Comment by wojtekmaj** [comment]
Hmmm. We use our own text layer creation system, so I don't think we could just switch modes like that. I'd need to investigate what are the main differences.
