### ISSUE TITLE
Print the PDF 🖨️

### ISSUE THREAD

**Issue by TroyWolf** [wojtekmaj/react-pdf#441]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
A "Print" button to do the same thing [PDF.js](https://mozilla.github.io/pdf.js/) does to enable a print option.

**Describe solutions you've tried**
Don't know where to start

**Additional information**
I wanted to ask for this as a feature, but:

> I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one

:coffee:

**Comment by gatno** [comment]
+1

**Comment by TroyWolf** [comment]
@gatno as it seems we are both on this journey, let's help each other if we figure any of this out. PDFjs provides the example `viewer.html` that requires their 15,559 line `viewer.js`--which is also just an "example" script showing how to use PDFjs. The magic of printing is buried in those 15K+ lines. See also: https://github.com/mozilla/pdf.js/issues/9318

**Comment by wojtekmaj** [comment]
Think of React-PDF as `<img>` tag for a PDF file. Page with a rendered PDF is still just a page, so you should approach PDF printing the same way you would approach printing any other page.

**Comment by TroyWolf** [comment]
@wojtekmaj,

I wish it was that simple. `window.print()` will print the entire page including any toolbars or other elements in the page. Of course we can use CSS to create a print-specific stylesheet that does `display: none;` on everything but the PDF output, but even then, you would be printing the HTML representation of the PDF rather than the PDF directly.

This could result in low-quality images and not-so-crisp text when you print vs the full-dpi PDF.

With the example viewer.html/js from the PDF.js library, when you click their print button, a lot of magic happens--dark magic I am yet to understand. For example, notice you don't end up with the standard browser header & footer--suggesting to me they are printing the PDF directly.
:coffee:

**Comment by Nestoro** [comment]
You can access the data behind the pdf like this:

```
			<Document
				file={url}
				onLoadSuccess={async (successEvent) => {
					// tslint:disable-next-line:await-promise
					const data = await successEvent.getData();
				}}
			>
```

this is how you can open the pdf in a new window where you can print/download without any losses:

```
						const blob = new Blob([data], { type: 'application/pdf' });
						window.open(URL.createObjectURL(blob));
```

**Comment by Runnic** [comment]
I have got the same problem when I was working on my project and, with the comment above I make a simple solution if you'd only want to save (download) the PDF.
First you just need to make a blob from the data just like the comment above says:

`async function onLoadSuccess(successEvent) {`
`>const data =  await successEvent.getData()`
`>const blob = new Blob([data], { type: 'application/pdf' })`
`}`

And then, with the lib [FileSaver.js](https://github.com/eligrey/FileSaver.js#readme) you will pass the blob var as the first parameter in the function "saveAs":

`async function onLoadSuccess(successEvent) {`
`>const data =  await successEvent.getData()`
`>const blob = new Blob([data], { type: 'application/pdf' })`
`>saveAs(blob, 'document_name.pdf')`
`}`

You can divide this function in 2 parts and make the "saveAs" part as a callback and use it in a button or event as you like.

**Comment by wojtekmaj** [comment]
> I wish it was that simple. window.print() will print the entire page including any toolbars or other elements in the page. Of course we can use CSS to create a print-specific stylesheet that does display: none; on everything but the PDF output, but even then, you would be printing the HTML representation of the PDF rather than the PDF directly.

Well that's correct, just like for `<img>` files embedded on the page :)

As an alternative suggestion you can look into [`react-new-window`](https://github.com/rmariuzzo/react-new-window) which allows you to render stuff in a new window. If you mix that with React-PDF, what you might end up is a new window with PDF only, without any 3rd party styles or other elements.

**Comment by georgezouq** [comment]
@TroyWolf so did you find the magic of print?

**Comment by TroyWolf** [comment]
@georgezouq, I never did. I punted and am just letting the browser's built-in PDF viewing/printing do it's thing. My original goal had been complete control over the UI. I gave up. That project was this: https://envelope.sawmilldesign.com/

**Comment by jonasschaude** [comment]
This issue has already been marked as closed but I recently got the same problem why I want to share the outcome if anyone is still searching for a possible solution.

Generally, you can implement your own print button with a lazy loading mechanism to display the print dialogue without relying on the browser's built-in PDF viewer. Follow these steps:
1. Generate the pdf when pressing the print button
2. Create and hide an iframe where you are going to load the generated pdf
3. Print the content of the iframe (f.e. using `iframeElement.contentWindow.print()`)

Step 2 and 3 could be accomplished using the [printjs](https://github.com/crabbly/Print.js/) library.

Feel free to double check the following snipped:
```
import { Document } from '@react-pdf/renderer';
import printJS from "print-js";
const PrintButtonExample: React.FC = ({}) => {
    const [pdfInstance, updatePdfInstance] = usePDF({});
    const [isPrinting, setIsPrinting] = useState(false);

    const handlePrintClick = async () => {
        setIsPrinting(true);
        const myPdfDocument = <Document><Page size="A4">Hello</Page></Document>
        updatePdfInstance(myPdfDocument);
    }

    useEffect(() => {
        if (isPrinting && pdfInstance.url) {
            printJS(pdfInstance.url);
            setIsPrinting(false);
        }
    }, [isPrinting, pdfInstance.url]);

    return (
        <>
            <Button type="primary" disabled={isPrinting} onClick={async () => { await handlePrintClick() }}>Print</Button>
        </>
    );
};
```

**Comment by pedrogrammer** [comment]
In your functional component you can use this code:

  ```
  const frameRef = useRef<HTMLIFrameElement>(null);

  return `(`
    <>
      <PDFViewer width="100%" height="100%" innerRef={frameRef}>
        <ReceiptDocument data={data} />
      </PDFViewer>
      <button
        onClick={() => {
          frameRef?.current?.contentWindow?.print();
        }}
      >
        print
      </button>
    </>
  );
```

**Comment by pedrogrammer** [comment]
In your functional component you can use this code:

```typescript
  const frameRef = useRef<HTMLIFrameElement>(null);

  return (
    <>
      <PDFViewer width="100%" height="100%" innerRef={frameRef}>
        <ReceiptDocument data={data} />
      </PDFViewer>
      <button
        onClick={() => {
          frameRef?.current?.contentWindow?.print();
        }}
      >
        print
      </button>
    </>
  );
```

**Comment by pedrogrammer** [comment]
In your functional component you can use this code:

```typescript
const frameRef = useRef<HTMLIFrameElement>(null);

return (
  <>
    <PDFViewer width="100%" height="100%" innerRef={frameRef}>
      <ReceiptDocument data={data} />
    </PDFViewer>
    <button
      onClick={() => {
        frameRef?.current?.contentWindow?.print();
      }}
    >
      print
    </button>
  </>
);
```

**Comment by pedrogrammer** [comment]
In your functional component you can use this code:

```tsx
const frameRef = useRef<HTMLIFrameElement>(null);

return (
  <>
    <PDFViewer width="100%" height="100%" innerRef={frameRef}>
      <ReceiptDocument data={data} />
    </PDFViewer>
    <button
      onClick={() => {
        frameRef?.current?.contentWindow?.print();
      }}
    >
      print
    </button>
  </>
);
```

**Comment by ngocxxu** [comment]
> In your functional component you can use this code:
> 
> ```tsx
> const frameRef = useRef<HTMLIFrameElement>(null);
> 
> return (
>   <>
>     <PDFViewer style={{ display: "none" }} innerRef={frameRef}>
>       <Document>
>         <Page size="A4">
>           <View>
>             <Text>Section #1</Text>
>           </View>
>         </Page>
>       </Document>
>     </PDFViewer>
>     <button
>       onClick={() => {
>         frameRef?.current?.contentWindow?.print();
>       }}
>     >
>       print
>     </button>
>   </>
> );
> ```

Omg, you save my life, so thanks 👯

**Comment by telecare-zeno** [comment]
> This issue has already been marked as closed but I recently got the same problem why I want to share the outcome if anyone is still searching for a possible solution.
> 
> Generally, you can implement your own print button with a lazy loading mechanism to display the print dialogue without relying on the browser's built-in PDF viewer. Follow these steps:
> 
> 1. Generate the pdf when pressing the print button
> 2. Create and hide an iframe where you are going to load the generated pdf
> 3. Print the content of the iframe (f.e. using `iframeElement.contentWindow.print()`)
> 
> Step 2 and 3 could be accomplished using the [printjs](https://github.com/crabbly/Print.js/) library.
> 
> Feel free to double check the following snipped:
> 
> ```
> import { Document } from '@react-pdf/renderer';
> import printJS from "print-js";
> const PrintButtonExample: React.FC = ({}) => {
>     const [pdfInstance, updatePdfInstance] = usePDF({});
>     const [isPrinting, setIsPrinting] = useState(false);
> 
>     const handlePrintClick = async () => {
>         setIsPrinting(true);
>         const myPdfDocument = <Document><Page size="A4">Hello</Page></Document>
>         updatePdfInstance(myPdfDocument);
>     }
> 
>     useEffect(() => {
>         if (isPrinting && pdfInstance.url) {
>             printJS(pdfInstance.url);
>             setIsPrinting(false);
>         }
>     }, [isPrinting, pdfInstance.url]);
> 
>     return (
>         <>
>             <Button type="primary" disabled={isPrinting} onClick={async () => { await handlePrintClick() }}>Print</Button>
>         </>
>     );
> };
> ```

print-js is easy to use, it supports printing pdf with base64 or URL. 
It is easy to do when I create the URL using Blob data.

**Comment by koriner** [comment]
@minikN Your solution works great, thanks!

Just a side note, probably because of a version update, but I had to use this method instead:

```
<Document
    onRender={(data) => {
      void onDocumentRender(data.blob);
    }}
  >
```
