### ISSUE TITLE
Can I do byte-streaming on large linearized PDF files?

### ISSUE THREAD

**Issue by geochanto** [wojtekmaj/react-pdf#442]
I have large PDF files, more than 30mb in size, 100+ pages.

So ideally I don't want to wait until the full file download before I start rendering pages. I'd like to render page 1 immediately, and then render rest of the pages as user requests.

Generally, it looks like **linearized** PDFs allow for partial downloads, as long as the server supports **byte-sized streaming**.  

If I take care of those two things, I'd like to know whether react-pdf can support this kind of rendering, or if there's anything else to be aware of. Perhaps I would need to create a new method, because `onDocumentLoadSuccess` waits for the full document to load.

**Comment by wojtekmaj** [comment]
Hmmm, AFAIK pdf.js should be okay with byte-streaming,and thus React-PDF should be as well. You can always try that online on supported servers using [our test suite](http://projects.wojtekmaj.pl/react-pdf/test)!
