### ISSUE TITLE
Ability to place custom HTML elements on a rendered page

### ISSUE THREAD

**Issue by michaeldzjap** [wojtekmaj/react-pdf#45]
This might be a bit of a niche use case, but it would be really nice if you could place custom HTML elements on a rendered page (i.e. relative to the element with class ReactPDF__Page). Something like:
```javascript
...
render() {
    return (
        <Document
            file={getPDFURL()}
            loading={<LineLoader />}
            error={this.renderError()}
            onLoadSuccess={this.onLoadSuccess.bind(this)}
        >
            [...Array(this.state.numPages)].map((item, i) => (
                <Page key={`page-{i + 1}`} pageNumber={i + 1}>
                    <input type="text" name="text-field"  style={{position: 'absolute', left: 10, top: 10 width: '100px', height: '30px'}}  />
                </Page>
            )
        </Document>
    );
}
...
```
Wouldn't be too hard to implement I think?

**Comment by lorenzos** [comment]
That's what I'm using react-pdf for :) I my app I have different kind of interactive semi-trasparent components placed on top of the PDF. IMHO this is so easy to do that shouldn't be this component "responsibility". Just place an absolute positioned container on top of this component, and than render its content depending on already available props such as page numbers, zoom level, etc.

**Comment by michaeldzjap** [comment]
@lorenzos Maybe I'm misunderstanding you (I'm definitely no CSS expert), but you mean something like:
```javascript
render() {
    return (
        <Document
            file={getPDFURL()}
            loading={<LineLoader />}
            error={this.renderError()}
            onLoadSuccess={this.onLoadSuccess.bind(this)}
        >
            [...Array(this.state.numPages)].map((item, i) => (
                [
                    <Page key={`page-${i + 1}`} pageNumber={i + 1} />,
                    <div key={`container-${i}`} style={{position: 'absolute', top: someComputedTop, left: 0, width: '100%', height: someComputedHeight}}></div>
                 ]
            ))
        </Document>
    );
}
```
But that would place the containers relative to the enclosing element with class `ReactPDF__Document` right? I'd like to place it relative to each page container, as otherwise I would have to calculate the correct top offset for each container, plus I'm afraid that this calculation might not be really accurate anymore if you have a lot of pages. And also this gives me a `Warning: Unknown prop `pdf` on <div> tag.` warning now.

Being able to have an absolutely positioned child container inside a Page component would make the positioning a lot simpler I think. But maybe I am misunderstanding you? Would you be willing to give a small example perhaps?

**Comment by lorenzos** [comment]
I don't think you can place a component inside `<Document/>` that is not `<Page/>`. Anyway what I meant is something like:

```javascript
render() {
  return (
    <div id="container">

      <Document ...>
          <Page ...>
      </Document>

      <div id="my-ui">
        ....
      </div>

    </div>
  );
}
```

```css
#container {
    position: relative;
    width: @same-as-PDF;
    height: auto;
}

#my-ui {
    position: absolute;
    top: 10px;
    left: 0;
    right: 0;
}
```

**Comment by michaeldzjap** [comment]
Ah yes, ok. I understand what you mean. I guess I could use your solution and adjust the `top` property based on page number and page height, but thats not really an ideal solution in case of more than 1 page per document component I think. For a couple of pages maybe, but if you have lots of pages I'm just afraid the placement will become increasingly more inaccurate. But in all fairness I guess I don't know until I try. 

Still though, it would be nice if you could it on a page by page basis, just by being able to pass child components to `ReactPDF__Page`. I actually managed to do this in [my](https://github.com/michaeldzjap/react-pdf-scroll) fork of the v1 version of `react-pdf`, but I'd prefer to use the new v2 version. Especially since it supports text context now.

**Comment by michaeldzjap** [comment]
For anyone interested; I [forked](https://github.com/michaeldzjap/react-pdf/tree/new-architecture) this repo and modified `Page.jsx` sightly by now allowing for passing a child component to the Page component, which in my case is an absolute positioned container (with width equal to the Page component) where you can place your custom UI components in. Works like a charm. 

Would be cool to see this merged into the original repo, but not sure if the original authors would want this...

**Comment by wojtekmaj** [comment]
Hey!
I actually think it's a good idea. It makes sense to make text layers optional and I need to rethink the architecture a tiny tiny bit within Page to make it more customizable. Definitely on my list then! Thanks!

**Comment by wojtekmaj** [comment]
Implemented in 2.1.0.

**Comment by michaeldzjap** [comment]
Great! Thanks a lot.

**Comment by wojtekmaj** [comment]
Always glad to help @michaeldzjap . Keep the ideas coming! ;)

**Comment by michaeldzjap** [comment]
Could I suggest one little enhancement? It would be nice if the page dimensions were passed as a property to any child components. So instead of just passing `{this.props.children}` if you would do something like this in the `render()` of `Page`:

```javascript
const childProps = {
    scale: this.scale,
    width: page.pageInfo.view[2],
    height: page.pageInfo.view[3]
};
...
{Children.map(children, child => React.cloneElement(child, childProps))}
```
It would be quite convenient to have access to these properties in any children. For instance if you want to give a child component the same dimensions as the parent (page) component.
