### ISSUE TITLE
react-pdf keep redownloading pdf file if component is rerendered by hooks change/props change

### ISSUE THREAD

**Issue by mfakhrusy** [wojtekmaj/react-pdf#451]
**Description**

I keep seeing my PDF file being redownloaded multiple times if the component have either changing props/state (via hook).

**Steps to reproduce**

My component:
```import React, { useState } from "react";
import { Document, Page } from 'react-pdf';
import Loading from 'components/Loading';

const DocumentReaderContent = React.memo(({ fileUrl }) => {
  const [numPages, setNumPages] = useState(0);

  const onDocumentLoadSuccess = (document) => {
    const { numPages } = document;
    setNumPages(numPages);
  }

  return (
    <div className='document-reader-content'>
      <Document
        file={{ url: fileUrl }}
        onLoadSuccess={onDocumentLoadSuccess}
        loading={(
          <div style={{ height: "90vh", display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column"}}>
            <div>
              <Loading />
              <span>Downloading your document... (might take a while)</span>
            </div>
          </div>
        )}
        noData="PDF Returned Empty"
      >
        {Array.from(
        new Array(numPages),
        (el, index) => (
          <Page
            key={`page_${index + 1}`}
            pageNumber={index + 1}
            loading={null}
          />
        ),
      )}
      </Document>
    </div>
  )
}, (prevProps, nextProps) => {
  return prevProps.fileUrl === nextProps.fileUrl
});

export default DocumentReaderContent;
```

I even have to use memo to reduce the redownloading count of the PDF file, by returning true if `fileUrl` props is not changing. If I don't use `React.memo`, PDF file can be redownloaded up to 5 times due to redux store change on the parent component.

And because `numPages` state changes after the pdf is downloaded, the component actually redownload the PDF before displaying it. My PDF can have up to 20 MB and it really bothers me.

Is this the default behaviour? Since you mention that [here](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages): "Please note that this approach may cause performance issues."

**Expected behavior**

PDF file is not being redownloaded on state change/props change.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: firefox 69.0 (64-bit)
 - React-PDF version [e.g. 3.0.4]: 4.1.0
 - React version [e.g. 16.3.0]: 16.8.0

Thank you so much.

**Comment by wojtekmaj** [comment]
Hi,
please see https://github.com/wojtekmaj/react-pdf/issues/308#issuecomment-443538284.
