### ISSUE TITLE
Invalid CFF header

### ISSUE THREAD

**Issue by patryk2703** [wojtekmaj/react-pdf#455]
Hello I am using this package from quiet some time and this error occurred first time. 
While trying to load preview of the following pdf 
[KANGU-08-07-2019.pdf](https://github.com/wojtekmaj/react-pdf/files/3642459/KANGU-08-07-2019.pdf) 
i got this: Unhandled Rejection (UnknownErrorException): Invalid CFF header

stack: 
UnknownErrorExceptionClosure
node_modules/pdfjs-dist/build/pdf.js:830
(anonymous function)
node_modules/pdfjs-dist/build/pdf.js:833
__w_pdfjs_require__
node_modules/pdfjs-dist/build/pdf.js:79
(anonymous function)
node_modules/pdfjs-dist/build/pdf.js:287
__w_pdfjs_require__
node_modules/pdfjs-dist/build/pdf.js:79
(anonymous function)
node_modules/pdfjs-dist/build/pdf.js:271
(anonymous function)
node_modules/pdfjs-dist/build/pdf.js:273
webpackUniversalModuleDefinition
node_modules/pdfjs-dist/build/pdf.js:23
(anonymous function)
node_modules/pdfjs-dist/build/pdf.js:24
./node_modules/pdfjs-dist/build/pdf.js
http://localhost:3004/static/js/0.chunk.js:92850:30

Full error:
UnknownErrorException {name: "UnknownErrorException", message: "Invalid CFF header", details: "FormatError: Invalid CFF header"}

Additional logs:
Warning: Not enough parameters for hstem; actual: 0, expected: 2
Warning: Found too many parameters for stack-clearing command
Warning: Missing subrsIndex for callsubr
Warning: Failed to compile font g_d0_f1
Warning: Failed to load font 'g_d0_f1': 'SyntaxError: Invalid font data in ArrayBuffer.'.

**Comment by oze4** [comment]
@patryk2703 I downloaded the PDF file in question and [uploaded it to the test site](http://projects.wojtekmaj.pl/react-pdf/test/), where it works just fine.

In order to assist further, we would need to see the code you are using to load the PDF file.

**Comment by patryk2703** [comment]
<img width="1661" alt="example" src="https://user-images.githubusercontent.com/48811207/65485779-0bc4e780-dea3-11e9-8719-ae1525791a4a.png">
i doesn't really work on that test site either, text isn't visible

and here is my code to load pdf preview:
<Document file={pdfPreviewData.body} onLoadSuccess={this.onDocumentLoadSuccess} onLoadError={console.error}>
    <Page pageNumber={pageNumber} width={pdfWidth} scale={pdfScale} onLoadError={console.error}/>
</Document>

onDocumentLoadSuccess = ({ numPages }) => {
    this.setState({ numPages });
}

pdfPreviewData.body is base64 string and it works fine for every other file we have

**Comment by oze4** [comment]
Oh ok. I didn't know that was not intended. Also, that code does not really help. The most important parts are missing.

**Comment by patryk2703** [comment]
What do you mean by those most important parts ? 
It's literally just this and:
`import { Document, Page, pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc=//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js;`
Thats all I have


Plus I don't reali think its a problem with my code since on test site it doesn't work either and I think it might throw the same error because with my code it loads till this point where no text is visible and then crushes.

**Comment by oze4** [comment]
One of the most important parts would be to show how you are pulling in the data for the PDF. Are you using a URL, Base64 data, etc..

Essentially, how do you go about getting the data behind this variable: `pdfPreviewData`..

**Comment by oze4** [comment]
@patryk2703 after testing out this issue for a bit, the problem seems to reside with [pdf.js](https://github.com/mozilla/pdf.js), which is what this package wraps around.  Specifically, the issue seems to have to do with loading the font.. [Here](https://github.com/mozilla/pdf.js/issues/4244) is a link to a similar issue.

Perhaps, you can try to change the font being used?

Even when using the built in version of PDF.js (that comes with Firefox) I am unable to open your PDF file.. this is also what makes me believe the issue is with PDF.js and not react-pdf.

Lastly, the console is full of errors when trying to load your file.. This is using the built in PDF.js that comes with Firefox, but these same errors are in the console when using react-pdf:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/21092343/65559672-35146080-df01-11e9-998a-da2cebdf141c.png">

**Comment by patryk2703** [comment]
Thank you for the information 
In that case could you please tell me quick how to stop rendering without react throwing that error ? Im trying to .catch() in onLoadError but doesn't seem to work as I would like it to and im still getting this screen
<img width="1094" alt="Screenshot 2019-09-25 at 10 23 08 2" src="https://user-images.githubusercontent.com/48811207/65582996-b65e0880-df7e-11e9-881d-24bf63ccefd7.png">

**Comment by oze4** [comment]
Unfortunately, I do not know how to prevent that error... Although, I know it has to do with `webpack` hot-reloading..

That error only occurs in `development` mode - it does not happen in `production`.

Feel free to fork [this repository](https://github.com/oze4/react-pdf-issue-455), which I created as a demo, as it demonstrates how that error only happens in `development` mode.
