### ISSUE TITLE
Dynamic Scaling

### ISSUE THREAD

**Issue by ajess33** [wojtekmaj/react-pdf#457]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I have PDFs in many different sizes, but want to keep the same aspect ratio no matter what the size of the screen is. The majority of the time this app will be used on an ipad so I would guess I need to somehow dynamically set the scale so the pdf actually fits on the screen.

**Describe solutions you've tried**

I have looked around at other issues and haven't found any answers that fixed my problem. If you would like to see some code of some solutions I've tried I can post those.

Has anyone else ran into this problem and how did you solve it?

**Environment**

 - Browser Chrome 77
 - React-PDF version [e.g. 4.1.0]:
 - React version [e.g. 16.8.6]:

**Comment by wojtekmaj** [comment]
After you load the document, in `onLoadSuccess` callback in `<Document />` you get access to `pdf` argument, which allows you to get list of all pages that were loaded, and also to their original dimensions. You can use this information to calculate desired dimensions for each page based on window width & height, and pass it to each `<Page />` component you render inside `<Document />`.
