### ISSUE TITLE
How to use getTextContent

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [wojtekmaj/react-pdf#462]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I need to get the text of the page in PDF, I saw a discussion #94, but I do not know if this functionality was implemented, I did not find in the documentation

how can i use `page.getTextContent ()`?

**Environment**

 - Browser Chrome: 77.0.3865.90
 - React-PDF: ^4.1.0
 - React: ^16.9.0

**Comment by wojtekmaj** [comment]
`page` is not "our" object, it's an object returned by pdf.js. Best I can do is give you this link: https://mozilla.github.io/pdf.js/api/
