### ISSUE TITLE
 where can I find the advanced examples page

### ISSUE THREAD

**Issue by AngeelRdz** [wojtekmaj/react-pdf#463]
hello good afternoon dear @wojtekmaj  ... a few moments ago I saw that there is no information on the advanced examples that were in this link: https://github.com/wojtekmaj/react-pdf/wiki/Recipes could you help me visualize them new or as I can see all the pages of my PDF file.
Regards

**Comment by wojtekmaj** [comment]
Hi,
wiki vandalism. You should see it now. Thanks for the heads up. The asshole was reported and blocked :)

**Comment by AngeelRdz** [comment]
Thank you very much dear @wojtekmaj  !!! And if indeed I can visualize it!
