### ISSUE TITLE
Want to convert Document to Base54 pdf encoding so that I can display in an iframe

### ISSUE THREAD

**Issue by Mortuie** [wojtekmaj/react-pdf#464]
Hi guys,

I'm using     "react-pdf": "^4.1.0",

and I was wondering if there was a way to convert a document that I have no created back into a base 64 encoded pdf so that I can easily show it in an iframe?

Thanks!

**Comment by wojtekmaj** [comment]
https://lmgtfy.com/?q=file+to+base+64+converter ;)
