### ISSUE TITLE
Beginner instructions?

### ISSUE THREAD

**Issue by burton666** [wojtekmaj/react-pdf#467]
I am pretty new to react and just want to create a small demo app that loads a local pdf that I have put in the src-directory.

I have created a react-app using "npx create-react-app" and have also installed react-pdf with "npm install react-pdf".

I copied pdf.worker.js to the src directory
what more steps do I need to do before I can get the pdf to show up after starting with "npm run start" ?

**Comment by wojtekmaj** [comment]
You will need to get this worker, well, working. After that, you're ready to code. So:

1. Follow [README instructions](https://github.com/wojtekmaj/react-pdf#create-react-app)
2. Check [sample directory](https://github.com/wojtekmaj/react-pdf/tree/master/sample) to get a simple implementation.
