### ISSUE TITLE
adding zoom?

### ISSUE THREAD

**Issue by jonathanphz** [wojtekmaj/react-pdf#47]
Any way of adding a zoom functionality?

**Comment by lorenzos** [comment]
There is a`scale` prop you can use to do that.

**Comment by wojtekmaj** [comment]
Yup, lorenzos is right.

Please mind that you'll have to build controls of your own - React-PDF only loads, renders and displays PDFs.

**Comment by 1Jesper1** [comment]
Maybe we can create an PR to add this optional functionality?

**Comment by wojtekmaj** [comment]
This is like attempting to add zoom controls to <img> tag. It's just not a good idea in such high level package as React-PDF. React-PDF is NOT a PDF viewer. It's only a tool to build one.

**Comment by 1Jesper1** [comment]
@wojtekmaj I understand, so functionality like previous/next PDF buttons should only exist outside this package?

**Comment by wojtekmaj** [comment]
Yes, you are correct.
