### ISSUE TITLE
AnnotationLayer always left bound

### ISSUE THREAD

**Issue by CyranMS** [wojtekmaj/react-pdf#473]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I want to center a pdf page (svg/canvas) inside a div, because height is 100% and width is auto. 
Works, but the annotation layer is always left-bound. Meaning if I do this then the link boxes are moved to the left and not at the right position.

**Describe solutions you've tried**

Trying to hack it with css, but so far the annotationLayer annoys me because it has width:100% and transform in css. Not giving the right results.

**Additional information**

![image](https://user-images.githubusercontent.com/10713004/67761002-aedcc400-fa42-11e9-81fc-3078d10985da.png)

**Environment**
 - React-PDF version: 4.1.0

**Comment by CyranMS** [comment]
Stupid mistake. Solved it.

```
<div className="center_div">
<Page className="center_page" />
</div>

.center_page {
  display: inline-block;
}

}

.center_div{
  text-align: center;
}

```

**Comment by kantharaju-ds** [comment]
Hi CyranMS,
Can you please point me to document or some sample code to display some Annotations on a Page, As i need to mark mostly few rectangles on top of pdf document page. Thanks

**Comment by kantharaju-ds** [comment]
> Stupid mistake. Solved it.
> 
> ```
> <div className="center_div">
> <Page className="center_page" />
> </div>
> 
> .center_page {
>   display: inline-block;
> }
> 
> .center_div{
>   text-align: center;
> }
> ```

Hi CyranMS,
Can you please point me to document or some sample code to display some Annotations on a Page, As i need to mark mostly few rectangles on top of pdf document page. Thanks

**Comment by CyranMS** [comment]
Hi @kantharaju-ds in component Page there is the parameter renderAnnotationLayer. I have it enabled so that links are clickable (behavior that comes right out of the bnox). But I haven't used it with custom annotations.

**Comment by kantharaju-ds** [comment]
> Hi @kantharaju-ds in component Page there is the parameter renderAnnotationLayer. I have it enabled so that links are clickable (behavior that comes right out of the bnox). But I haven't used it with custom annotations.

Thank you!
