### ISSUE TITLE
Importing from react-pdf breaks my app

### ISSUE THREAD

**Issue by Bennyz811** [wojtekmaj/react-pdf#475]
**Before you start - checklist**

 - [x ] I have read documentation in README
 - [x ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x ] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'd like to build a npm module. My module uses react-pdf. aka: myLibrary.
In my library I: import { Document, Page } from 'react-pdf';
As test: console.log(Document, Page).

npm install myLibrary into myMainApp.
myMainApp output:

Uncaught TypeError: Cannot read property 'bind' of undefined

**Describe solutions you've tried**

Comment out all react-pdf related code.. including import { Document, Page } from 'react-pdf' in myLibrary.
Rerun myMainApp: error gone.

**Additional information**

![Screen Shot 2019-10-30 at 5 11 56 PM](https://user-images.githubusercontent.com/30328018/67899317-6acbeb00-fb38-11e9-8aeb-66615a995528.png)

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Chrome(latest)
 - React-PDF version [e.g. 3.0.4]: ^4.1.0
 - React version [e.g. 16.3.0]: ^16.4.2
 - Webpack version (if applicable) [e.g. 4.16.2]: ^4.35.0

**Comment by wojtekmaj** [comment]
Does this still occur?
