### ISSUE TITLE
Is it possible to concat different pages into one image?

### ISSUE THREAD

**Issue by yehia123** [wojtekmaj/react-pdf#476]

**Comment by Rodolpho-Cunha** [comment]
I don't know if I understood your question exactly, but I had a simmilar question a few minutes ago. In any case, here you go, buddy.

<Document className="pdf-document" file={`data:application/pdf;base64,${base64File}`}>
  {
    Array.from(
      new Array(numPages),
      (el, index) => (
        <Page
          key={`page_${index + 1}`}
          pageNumber={index + 1}
          width={1068}
        />
      ),
    )
  }
</Document>

**Comment by wojtekmaj** [comment]
It's not possible out of the box, but you can copy image from canvases and paste it into your own canvas programmatically.
