### ISSUE TITLE
Line-height is calculated improperly and shifts the text layer

### ISSUE THREAD

**Issue by alex-mironov** [wojtekmaj/react-pdf#477]
I've got a PDF document having a line-height set to the value different from the browser's defaults. Apparently, when the text layer is being rendered it doesn't take into account the font size of the 
PDF document.
Original:
<img width="1202" alt="Screen Shot 2019-11-04 at 16 47 41" src="https://user-images.githubusercontent.com/2544767/68130698-79dddf00-ff24-11e9-8f63-a272ace88465.png">
After setting line height to the actual PDF's size:
<img width="1190" alt="Screen Shot 2019-11-04 at 16 55 51" src="https://user-images.githubusercontent.com/2544767/68130705-7d716600-ff24-11e9-8ba8-a23dfcf4af51.png">

Does anyone know if there is a way to retrieve PDF font size settings so I can adjust Page styles on the fly (set line-height of Page to the value coming from PDF)? 🙏

**Comment by wojtekmaj** [comment]
Hi, would you mind sharing the PDF with me? I'll try and see if line-height can be programaticallly extracted.

**Comment by sudhir-pradhan** [comment]
hi, I want to set font-size so that pdf page texts will look bigger in small screen devices? any idea how to achieve this?

**Comment by wojtekmaj** [comment]
May be fixed by #944.
