### ISSUE TITLE
Custom Annotations Layer (Dynamic drawings like rectangle on top of pdf Pages)

### ISSUE THREAD

**Issue by kantharaju-ds** [wojtekmaj/react-pdf#479]
Dear all,
I want to draw some dynamic rectangles on top of PDF Pages Images like highlighting some portions of the PDF Image. If this can be achieved please point me to document or a sample code to do the same.
Thanks

**Comment by kantharaju-ds** [comment]
Dear all,
I want to draw some dynamic rectangles on top of PDF Pages Images like highlighting some portions of the PDF Image. If this can be achieved please point me to document or a sample code to do the same.
Thanks

**Comment by wojtekmaj** [comment]
In order to create custom layers, you'd need to put `<Page>` and your custom element within one wrapper and position them by using `position: absolute`. Just like you would do it over an image.
