### ISSUE TITLE
Please add a table option in the pdf

### ISSUE THREAD

**Issue by Sumana-Raikar** [wojtekmaj/react-pdf#482]
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

Describe what the problem is. Ex. I'd like to do […] with my PDFs.

**Describe the solution you'd like**

What you want to happen?

**Describe alternatives you've considered**

Describe alternative solutions or features you've considered, if any.

**Additional information**

**Comment by wojtekmaj** [comment]
What do you mean? React-PDF renders tables just fine.
