### ISSUE TITLE
Text selection issue

### ISSUE THREAD

**Issue by Gopes396** [wojtekmaj/react-pdf#483]
Hi,
I am working on a project that requires text selection. After trying out the suggestions from previous issues, I still have an issue with text later. It flickers when the text is selected. Could you tell me the possible scenarios so that I can eliminate them/ solve them.

**Comment by wojtekmaj** [comment]
Can you please provide a minimum reproduction repo (perhaps on Code Sandbox) so I could have a look on your situation?

**Comment by Gopes396** [comment]
Resolved

**Comment by DLevai94** [comment]
@Gopes396 how do you managed to resolve it?
