### ISSUE TITLE
Error when load base64

### ISSUE THREAD

**Issue by andrewyohanes123** [wojtekmaj/react-pdf#488]
- [*] I followed instructions in documentation written for my React-PDF version
 - [*] I have checked if this bug is not already reported
 - [*] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)

i was trying to load base64 file from an API. when i log the error on event onLoadError, i got this error

`Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".`

here's my code :
`<Document onLoadError={e => console.log(e)} file={file} onLoadSuccess={({ numPages }) => this.setState({ numPages })}>
            <Page pageNumber={this.state.page} />
          </Document>`

the string is 

>data:application/pdf;base64,JVBERi0xLjcNCiW1tbW1DQoxIDAgb2JqDQo8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFIvTGFuZyhlbi1VUykgL1N0cnVjdFRyZWVSb290IDEzIDAgUi9PdXRsaW5lcyAxMCAwIFIvTWFya0luZm88PC9NYXJrZWQgdHJ1ZT4+L01ldGFkYXRhIDcwIDAgUi9WaWV3ZXJQcmVmZXJlbmNlcyA3MSAwIFI+Pg0KZW5kb2JqDQoyIDAgb2JqDQo8PC9UeXBlL1BhZ2VzL0NvdW50IDEvS2lkc1sgMyAwIFJdID4+DQplbmRvYmoNCjMgMCBvYmoNCjw8L1R5cGUvUGFnZS9QYXJlbnQgMiAwIFIvUmVzb3VyY2VzPDwvRXh0R1N0YXRlPDwvR1M1IDUgMCBSL0dTNiA2IDAgUj4+L0ZvbnQ8PC9GMSA3IDAgUj4+L1Byb2NTZXRbL1BERi9UZXh0...

**Comment by cworf** [comment]
I am also experiencing this exact issue, Ive confirmed my base64 code converts just fine in an online base64 to pdf converter, 

the error stack is as follows

additionally i also receive the following error

> Uncaught SyntaxError: Unexpected token '<'       pdf.worker.js:1

**Comment by wojtekmaj** [comment]
@cworf -> #97
