### ISSUE TITLE
Text layer rendered upside down

### ISSUE THREAD

**Issue by crowlKats** [wojtekmaj/react-pdf#490]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I am showing all pages of a PDF, and each page is centered with flexbox. One page tho has the selection not matching with the content, even so much that one line goes so far to the right, expanding to the right, but it isnt even visible, so it just enlarges the container and adds empty space to the right side of the page.

**Describe solutions you've tried**

Removing scrolling on the X axis, but that will not work well with zooming and panning around to view the rest of a zoomed in pdf.

**Additional information**

<img width="1033" alt="Screenshot 2019-11-25 at 06 49 39" src="https://user-images.githubusercontent.com/13135287/69516228-5f11ef80-0f51-11ea-87df-a54a0b8b4252.png">

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Firefox 70.0.1
 - React-PDF version [e.g. 3.0.4]: 4.1.0
 - React version [e.g. 16.3.0]: 16.12.0
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.41.2

**Comment by wojtekmaj** [comment]
Well, Page consists of multiple layers, so to align them you gotta make sure that:

1) All styling is applied to .react-pdf__Page and not, for example, .react-pdf__Page__canvas
2) You use proper width and your canvas/svg is not getting shrunk, because we can't shrink text layer

It looks from your picture like the text layer is actually upside down, so I would really like to look into your file, to see what the problem is.

**Comment by crowlKats** [comment]
i checked the pdf in different viewers, and everywhere the text was highlighting as it should

**Comment by wojtekmaj** [comment]
Can you provide me with PDF you have these issues with? It's really hard to debug without it. Every PDF file is different.

**Comment by crowlKats** [comment]
sure, [here](https://github.com/wojtekmaj/react-pdf/files/4257536/turismo_a_matera__panorama_padula.pdf) it is

**Comment by toinhao1** [comment]
I am having a similar issue, any update on this?

**Comment by 1Jesper1** [comment]
I also have this problem with renderMode "svg".
