### ISSUE TITLE
Loading PDF issue

### ISSUE THREAD

**Issue by shashiachar** [wojtekmaj/react-pdf#491]
Hi
I'm trying to load the pdf but its showing **Loading PDF...** please help me where i went wrong

![pdfCode](https://user-images.githubusercontent.com/58202211/69600328-3152a680-1036-11ea-886e-429742b2ce73.png)

**output** 
![pdfLoadingIssue](https://user-images.githubusercontent.com/58202211/69600362-521afc00-1036-11ea-80af-f91fd4721e45.png)

Thanks in advance

**Comment by wojtekmaj** [comment]
Anything in the console?

**Comment by wojtekmaj** [comment]
Closing because of lack of information
