### ISSUE TITLE
No text in PDF

### ISSUE THREAD

**Issue by WangJM001** [wojtekmaj/react-pdf#492]
[MYPDF.pdf](https://github.com/wojtekmaj/react-pdf/files/3900300/2015.853.2015.2016.pdf)
![image](https://user-images.githubusercontent.com/20501316/69784356-8a663a00-11f0-11ea-80e5-a06b3fb161a0.png)

this file can not view, show empty page!

**Comment by wojtekmaj** [comment]
This is way too few information to help you.

1. Does this PDF works fine in Firefox?
2. Did you copy and configure cmaps as instructed in README?
3. If so, upload sample PDF with sample code so we could have a look.

**Comment by WangJM001** [comment]
thanks, solved by cmaps

**Comment by xiaofsu** [comment]
Hello everyone, I am new to using React. I also encountered this problem, and successfully used cmaps to successfully display PDF, but currently using CDN, how can I do it locally? I read the README in detail, But I did n’t understand how to use it, thank you.

![image](https://user-images.githubusercontent.com/46067472/82891470-5f328c80-9f80-11ea-8ab5-27250d8e3d46.png)
