### ISSUE TITLE
Feature request for v5.0.0 , enable webGL rendering

### ISSUE THREAD

**Issue by NawarA** [wojtekmaj/react-pdf#494]
I noticed you're working on v5. I'm wondering if you can allow a flag to pass the pdf.js renderer, to allow users to enable WebGL rendering? It speeds up the library's performance by >37%, which is huge. So a simple flag in v5 to enable it would be great 🙏

**Comment by wojtekmaj** [comment]
Related: https://github.com/mozilla/pdf.js/issues/5161

**Comment by wojtekmaj** [comment]
Actually, you should be able to do it this way today:

```js
import { pdfjs } from 'react-pdf';
pdfjs.disableWebGL = false;
```

**Comment by NawarA** [comment]
🥇
