### ISSUE TITLE
Compilation error...'PDFJS' is not defined no-undef

### ISSUE THREAD

**Issue by jaspreetcj** [wojtekmaj/react-pdf#497]
I am not able to compile my code. using react-pdf @3.0.6 and react version @16.12.0
```
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  }
```

using import statement as.
```
import * as React from 'react'
import { Document } from 'react-pdf/dist/entry.webpack';
import { callIfDefined, makeCancellable } from 'react-pdf/dist/shared/utils';
```
line which fails compilation
```
if (!PDFJS) {
          throw new Error('Could not load the document. PDF.js is not loaded.');
        }
```
```
this.runningTask = makeCancellable(PDFJS.getDocument(source));
```
error
```
./src/components/search/CustomDocument.jsx
  Line 12:14:  'PDFJS' is not defined  no-undef
  Line 29:44:  'PDFJS' is not defined  no-undef 
```

**Comment by wojtekmaj** [comment]
Why are you using so old React-PDF version? Have you tried 4.x or 5.0 beta?

**Comment by jaspreetcj** [comment]
I did try react-pdf 4.0.0 and upwards, but the build script (react-script) started throwing error:

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

I was able to resolve this by bumping up the memory via command:

react-scripts --expose-gc --max-old-space-size=8192.

But again after the above command was executed,it threw the original error:
'PDFJS' is not defined  no-undef.
So the higher versions of react pdf 400 and above are also throwing the same error.

Can you please confirm if this is a bug with react pdf library?

thanks

**Comment by wojtekmaj** [comment]
Looks like the error you're talking about is in your own component, ./src/components/search/CustomDocument.jsx. You must have edited something wrong.

**Comment by jaspreetcj** [comment]
The same CustomDocument.jsx is working absolutely fine when build script is react-script-ts.
The same code throws error when the build script is changed to react-script.

Thing worth mentioning is  react-script-ts transitively installs webpack 3.8.1, where as react-script installs webpack 4.41.2.

It is apparent that react-pdf has issues working along with webpack > 3.8.1.

Can you please confirm react-pdf is compatible with webpack >3.8.1, if no, are there any plans of looking into it?

**Comment by wojtekmaj** [comment]
React-PDF is compatible with Webpack 4, I'm using it myself on React-PDF demo page.

**Comment by jaspreetcj** [comment]
Only 2 places where PDFJS is being used is as follows:(also this works fine when build script is react-script-ts instead of react-script)
--
if (!PDFJS) {
          throw new Error('Could not load the document. PDF.js is not loaded.');
        }
--
this.runningTask = makeCancellable(PDFJS.getDocument(source));
--
Do you see anything wrong in above usage, and these are the lines where error is being thrown.

**Comment by wojtekmaj** [comment]
You don't import PDFJS anywhere in your code, judging by the first post of yours.

**Comment by jaspreetcj** [comment]
following are the imports:

import * as React from 'react'
import { Document } from 'react-pdf/dist/entry.webpack';
import { callIfDefined, makeCancellable } from 'react-pdf/dist/shared/utils';

**Comment by wojtekmaj** [comment]
`import { Document } from 'react-pdf/dist/entry.webpack';` doesn't make PDFJS available in this module. You don't import PDFJS variable here.

**Comment by jaspreetcj** [comment]
but the exact same code (with same imports)compiles and runs when it is being build by react-script-ts, can you advice what could be going wrong, when I use react-script build?

**Comment by wojtekmaj** [comment]
I don't know what magic react-script-ts does. I suggest sticking to standards. If you want to have PDFJS defined, you gotta import it.
