### ISSUE TITLE
There are memory leak phenomenon related to pdf.worker.js

### ISSUE THREAD

**Issue by ganadara135** [wojtekmaj/react-pdf#504]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Short description of the bug you encountered.
=> There are momery leak whenever I call a pdf document by react-pdf. In the end, my program suddenly stop and reload.

**Steps to reproduce**

=>  I checked this result by Chrome devtool on Memory profiles VM instance.
      The number of VM instances start to increase whenever I reload a web page which use React-pdf
      module
1. `import { Document, Page, pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = '//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js';
` 
2. 
<img width="731" alt="스크린샷 2019-12-31 00 01 05" src="https://user-images.githubusercontent.com/24896007/71588554-43f45a00-2b65-11ea-9ae2-6321d6587c6b.png">

3. even if I didn't use pdfjs.GlobalWorkerOptions.workerSrc, the number of VM instances is not increased at all, but it stop and reload like above. It looks like internally increasing pdf.worker.js 
`import { Document, Page } from 'react-pdf'`

**Expected behavior**

What you expected to happen?
=> On the moment of refreshing(F5) web page which has pdf function, react-pdf just adds another pdf.worker.js and don't stop previous pdf.worker.js. After all, the current web page was stoped by chrome by force

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [Chrome 79.0.3945.88 ]
 - React-PDF version [ 4.1.0 ]:
 - React version [ 16.9.0 ]
 - Webpack version (if applicable) [ 4.40.2]:

**Comment by ubeytdemirr** [comment]
Solved check out my solution : https://gist.github.com/ubeytdemirr/740bd627e7aafbf66acf0dcd80351f89

**Comment by ganadara135** [comment]
> Solved check out my solution : https://gist.github.com/ubeytdemirr/740bd627e7aafbf66acf0dcd80351f89

I applied your solution, but it didn't stop to memory leak. Continually pdf.worker.js increases. Thanks anyway.

**Comment by weifans** [comment]
@ganadara135 Are there any new developments?

**Comment by brentmitch** [comment]
This seems related to issue #452 _Lingering Worker BLOB_    @oze4 has a solution and put a pull request ( #505 ) it just hasn't been approved yet.  I did my own build and tried it out.  It did remove the web workers after the component unmounted.

**Comment by wojtekmaj** [comment]
Fixed by #505.
