### ISSUE TITLE
Is pinch zoom support built in?

### ISSUE THREAD

**Issue by danwt** [wojtekmaj/react-pdf#508]
?

**Comment by wojtekmaj** [comment]
No it's not. Think of React-PDF as of an `<img>` tag for PDFs.

**Comment by TomHerman11** [comment]
Is there an official or recommended way to handle cases of pinch to zoom?
Or one should render a "zoom in/out" controller? (using the ```scale``` prop).

Thank you.

**Comment by wojtekmaj** [comment]
There's no official recommendation. The only thing that I could recommend is to use SVG rendering because it should remain sharp regardless of the scale and potentially reduce the amount of rendering. Other than that - implement it as you would with an img tag.

**Comment by KingAmo** [comment]
is there anyone could provide a recommended way to implement pinch and zoom ?

**Comment by 27pchrisl** [comment]
For those following up on this issue, https://github.com/prc5/react-zoom-pan-pinch appears to work well.

**Comment by moshfeu** [comment]
@27pchrisl the zoom itself works but it's not possible to scroll in multiple pages document, at least for me.
Did you face such an issue?

**Comment by Anhaachan** [comment]
I have no clue why this package is removing the SVG render mode, but that mode rendered very well. I loved it, but it will no longer be available in the future. However, even the SVG mode had an issue: it could not handle multiple pages of a document. I wish this package would add pinch-to-zoom functionality or a higher resolution mode.
