### ISSUE TITLE
Link to Document Options is dead

### ISSUE THREAD

**Issue by kchetan92** [wojtekmaj/react-pdf#509]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

The link to options in the User Guide is dead. The link is https://mozilla.github.io/pdf.js/api/draft/global.html#DocumentInitParameters

**Steps to reproduce**

1. Go to https://github.com/wojtekmaj/react-pdf
2. Scroll to options in User Guide > Document
3. Click on link for ""

**Expected behavior**

See the relevant page with option description

**Comment by wojtekmaj** [comment]
Thanks!
