### ISSUE TITLE
PDFJs worker CDN support

### ISSUE THREAD

**Issue by JensDebergh** [wojtekmaj/react-pdf#510]
**Before you start - checklist**

 - [X] I followed instructions in documentation written for my React-PDF version
 - [X] I have checked if this bug is not already reported
 - [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

I'm experiencing some problems when trying to use assets served from CDN.

**Steps to reproduce**

1. Use webpacker
2. Import 
3. Use any CDN like (cloudfront, cloudflare, etc...)

```
import { Document } from 'react-pdf/dist/esm/entry.webpack';
```

Will result:

```
Cannot load worker "Worker", same origin policy.
```

**Expected behavior**

I expected PDFJs to follow the loader rules I have for my webpack setup.

**Comment by wojtekmaj** [comment]
I don't understand what you're doing here. If you used Webpack-specific entry, there's no point of using external CDN. Can you give me the full example?
