### ISSUE TITLE
Is there a way to access a page's dimensions?

### ISSUE THREAD

**Issue by SandMoshi** [wojtekmaj/react-pdf#512]
**What are you trying to achieve? Please describe.**

I am displaying a PDF file, they are single-page files, but I would like to be able to access the file's dimensions so I can calculate the zoom level. I didn't see anything in the documentation about reading a file's data once loaded.

**Additional information**

I would like to read the data from the file anytime before it's rendered.

**Environment**
 - React-PDF version  4.1.0
 - React version 16.8
 - Webpack version (CRA 3.2.0)

**Comment by wojtekmaj** [comment]
Yes, absolutely. `<Page />`'s `onLoadSuccess` callback gets `page` object as an argument, and said object contains everything you need: `width`, `height` (scaled - as rendered), `originalWidth`, `originalHeight` (original).

**Comment by SandMoshi** [comment]
Would you be interested in having me add this as an example to the README in a pull request?

**Comment by wojtekmaj** [comment]
Hmmm, I'd need not to be picky and document all the interesting arguments. I'll tackle it, but not right now - swimming in notifications 😞
