### ISSUE TITLE
Module not found: Error: Can't resolve 'react-pdf' 

### ISSUE THREAD

**Issue by JosephG3001** [wojtekmaj/react-pdf#515]
Getting this error:

_Module not found: Error: Can't resolve 'react-pdf'_ 

I've run the following: 

- npm install react-pdf
- npm install @types/react-pdf

There's no compile errors in VSCode, only when I try to run the application.

Please help.

**Comment by wojtekmaj** [comment]
Not React-PDF issue, but try removing your `node_modules`, clean npm cache and run `npm install` again. If that doesn't help, consider asking on npm support forum instead.

**Comment by tskweres** [comment]
Same issue, tried the above. Any ideas?

**Comment by wojtekmaj** [comment]
Doesn't seem to be package related, rather your package manager related. Do you have node_modules/react-pdf directory?

**Comment by PaulPCIO** [comment]
I just did a fresh install on using nextjs and getting the same error

**Comment by ECWireless** [comment]
I'm also getting this issue using `snowpack`. Any ideas how to resolve this? Tried removing `node_modules`, cleaning caches, and reinstalling already.

**Comment by luccasmaso** [comment]
Same here

**Comment by ECWireless** [comment]
As a follow-up, the issue is identified here: https://github.com/snowpackjs/snowpack/discussions/2370#discussioncomment-400148

Since `@react-pdf/unicode-properties` is archived, it could be a while before this is resolved/

**Comment by Fanny94-star** [comment]
vbn,klkhgghjklm:;,nbn,;:

**Comment by OumaymaBoudaouara123** [comment]
Same here

**Comment by ColtonMori** [comment]
Same here

**Comment by armansnorkel** [comment]
Definitely package related 🤣

**Comment by Acquah-Kingsley-Segu** [comment]
I had the same issue and it got resolved when I did `npm i`

**Comment by karljinang** [comment]
for pnpm users. 
- Delete node_modules and for the particular package. 
- run `pnpm store prune`
- pnpm install

This fixed it for me.

**Comment by RichardOro01** [comment]
same
