### ISSUE TITLE
get all text for highlighting/annotating

### ISSUE THREAD

**Issue by chrisb911** [wojtekmaj/react-pdf#516]
I'm using the standard example of customTextRenderer to mark up the text of my PDF with search terms.
```javascript
      <Page
             key={`page_${index + 1}`}
              pageNumber={index + 1}
              customTextRenderer={this.makeTextRenderer(this.state.searchText)}
             onMouseUp={this.selectText}
      />
```
What i'm noticing is that there seem to be arbitrary breaks in the searchText - including breaks in the middle of a word. This means the example using : 

```javascript
makeTextRenderer = searchText => textItem => this.highlightPattern(textItem.str, searchText);
    
    highlightPattern = (text,pattern) => {
        console.log("text : " + text);
        const splitText = text.split(pattern);
        if (splitText.length <=1){
            return text;
        }

        const matches = text.match(pattern);
        return splitText.reduce((arr,element,index) => (matches[index] ? [...arr,element,<mark>{matches[index]}</mark>,
        ] : [...arr,element]),[]);
    };

```
... doesn't work reliably as my search tokens won't necessarily match if the text is broken on a search term. Is there any way to get all the text for the document, process it for the annotations and provide it back?

thanks,

Chris

**Comment by psawa** [comment]
This issue has been open for a little while. Do you have a solution to share now @chrisb911 ?

**Comment by wojtekmaj** [comment]
For this you will need to dive in into pdf.js's internals a little bit. React-PDF provides hooks to these internals in onDocumentLoad, onPageLoad etc.

Here's what I found on this topic: https://stackoverflow.com/questions/40635979/how-to-correctly-extract-text-from-a-pdf-using-pdf-js

**Comment by kunalsawhney** [comment]
@chrisb911 Did you find any solution for this ? I am facing the same issue but haven't been able to figure out anything around it.
