### ISSUE TITLE
Is there a way to pass a UTF-8 string to Document?

### ISSUE THREAD

**Issue by dompham** [wojtekmaj/react-pdf#517]
- [X] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

The data we have is a string with: `:type=>"application/pdf; charset=utf-8"`
Is there a parameter we can pass into document with this text string to render the PDF?
The string starts with `%PDF-1.5....`

**Describe solutions you've tried**

I've tried a few combinations, the one I was most hopeful about was:
```
Document file={`data:application/pdf;utf-8,${str}`}...
```

**Environment**

 - React-PDF version: 4.1
 - React version: 16.7.0

**Comment by dompham** [comment]
Update: Splitting the string and filling a Uint8Array with the charcodes seems to work, but is there a more "correct" way?

**Comment by LoganArnett** [comment]
@dompham  running into the same issue, are you able to illustrate your work around or have you found a better solution?

**Comment by wojtekmaj** [comment]
As long as the [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) you're creating opens fine in the browser, it should be opened just fine by React-PDF, too.

**Comment by JIACHENG135** [comment]
> As long as the [Data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) you're creating opens fine in the browser, it should be opened just fine by React-PDF, too.

Hello wojtekmaj,

I met an issue which is quite same as this one. I can load a Data URL perfectly but when I pass that url into the Document, it failed. The error message saying "PDFDocument: Stream must have data". Here is an example url: [https://vue-aplayer-django.herokuapp.com/api/downloadlib/36000/405E21359CC97FCD49DF2D12B582DE81/Is.pdf](url). Can you give some hint s?

My current react-code is
```
    return (
      <div>
        <Document
          file={{
            url:
              'https://vue-aplayer-django.herokuapp.com/api/downloadlib/' +
              locator +
              '/' +
              md5 +
              '/' +
              filename,
          }}
          onLoadError={console.error}
          class="pdf-wrapper"
        ></Document>
      </div>
    )
```
