### ISSUE TITLE
Ability to include via. <script>

### ISSUE THREAD

**Issue by cyrusbowman** [wojtekmaj/react-pdf#518]
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

- Required to increase node memory limit to build project.
- Slow build times

**Describe the solution you'd like**

- Include a separate bundle in /dist that can be imported separately via. a <script> tag into html. Then you would access `Document`, `Page`, etc. via. window. `window.PDFJS.Document`.

**Additional information**

- This issue seems to keep popping up #61 and I believe it'd be a good compromise. 
- Currently I am building with `--max-old-space-size=8192` but the 2 min build times and large memory usage while building (~6 GB) is not ideal.

**Comment by wojtekmaj** [comment]
It's a good idea, but I don't know how we could implement that, frankly. If anyone's willing to contribute, I'm happy to have it merged.
