### ISSUE TITLE
Is it possible to render an svg image?

### ISSUE THREAD

**Issue by zommerberg** [wojtekmaj/react-pdf#525]
I am trying to download the pdf that i am creating. But i am not sure how to add an svg file to it.

Is it possible to pass an SVG file/image to < MyDoc / > component or i have to encode it into base64 image and pass it into < Image/> component?

```
  <PDFDownloadLink document={<MyDoc />} fileName="somename.pdf">
          {({ blob, url, loading, error }) =>
            loading ? 'Loading document...' : 'Download now!'
          }
   </PDFDownloadLink>
```

**Comment by wojtekmaj** [comment]
Wrong repository :) You likely wanted to ask this question in @diegomura's project.

**Comment by zommerberg** [comment]
Closing because the question is for another repo.
