### ISSUE TITLE
Last short page - is it possible?

### ISSUE THREAD

**Issue by Rongrs** [wojtekmaj/react-pdf#526]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I have a doc that I want to render, it has multiple pages and the last page has only 1 row
the output is such that after the first line we have a very long blank area with no data

it makes sense, because this is the actual pdf I'm rendering, but I was wondering if there is an option to have the last page truncated at the end of the last line, instead of having this blank area

**Describe solutions you've tried**
- Reading the README
- setting page height changed the actual size of the text (of course)
- trying to set the height of the containers to 'auto' in the inspector-view and playing around there

Awesome package, really saved us from a ton of work :-) thanks for all the time you put into it

**Comment by wojtekmaj** [comment]
React-PDF renders pages as-is, without any modifications, so you would need to change your PDF page dimensions in order for it to be rendered without the white space.
