### ISSUE TITLE
Invalid PDF Exception !

### ISSUE THREAD

**Issue by gunner963** [wojtekmaj/react-pdf#527]
**Before you start - checklist**

 - [yes] I have read documentation in README
 - [yes] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [yes] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
trying to render the pdf in my react app but getting the **invalidpdfexception**

I am trying with the same pdf from the example sample.pdf and have the same folder structure 
i.e. storing pdf at the same component level reffering as **file='./sample.pdf'**

**Describe solutions you've tried**
I have tried looking similar issues but none have helped so far 
[#123 ](https://github.com/wojtekmaj/react-pdf/issues/123)
[#264 ](https://github.com/wojtekmaj/react-pdf/issues/264)

**Additional information**

Attached are the screen shot of the **network** tab
How I am calling the file in my **Component**
and the Actual Error on **Console**

![fetch](https://user-images.githubusercontent.com/37613936/75496409-a9f33700-5986-11ea-8193-c3edca9dbb1f.png)
![component](https://user-images.githubusercontent.com/37613936/75496412-acee2780-5986-11ea-825c-6f28832cdd3f.png)
![console](https://user-images.githubusercontent.com/37613936/75496416-aeb7eb00-5986-11ea-8b15-09402913aab0.png)

**Environment**

 - Browser (if applicable)   **Version 79.0.3945.130 (Official Build) (64-bit)**
 - React-PDF version  **4.1.0**
 - React version  **16.12.0**
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by thebetternewt** [comment]
@gunner963 Same issue here!

**Comment by gunner963** [comment]
so I tried importing them as module and it loaded the pdf !!!

`import myPdf from ''.../assets/pdfs/myDoc.pdf`
and then storing it in a var and passing that var to Document 
`const pdf = myPdf `
`<Document file={pdf}>`  
`<Page pageNum...></Page>`

**BUT**  then it will have so many imports in the component one for each pdf and the application I am working on can have more pdfs added to them later on and path is stored in JSON related to the current directory structure 

so may be I will look into if I can do dynamic imports  based on props -- that's the route I am looking to and asking for if you know any solution for that cause again as I said don't want imports for each and every pdf

Thanks

**Comment by gunner963** [comment]
if you're using CRA just store pdf in public folder and it works !

**Comment by cfthody** [comment]
@gunner963 I have a similar problem and I tried to import the pdf as using a URL based one but I'm getting the same error. How did u solve yours? None of the options above worked for me.

**Comment by shafisyed** [comment]
@gunner963 Error while opening the document !
 InvalidPDFException {message: 'Invalid PDF structure.', name: 'InvalidPDFException'} how to solve this problem

**Comment by AlaaL** [comment]
same issue here

**Comment by eleventhaus** [comment]
same
