### ISSUE TITLE
React PDF preview is not loading in Mobile browser

### ISSUE THREAD

**Issue by shashiachar** [wojtekmaj/react-pdf#528]
_PDF preview is working in desktop browser._

When I opened in **Mobile chrome browser** it's showing **error: setting up fake worker failed**
![1583327490638](https://user-images.githubusercontent.com/58202211/75882794-deb03400-5e47-11ea-917d-a5f66f334b46.jpg)

**Comment by wojtekmaj** [comment]
Looks like a network problem. Consider checking the Network tab in developer tools to find out why this file is not being loaded, or try hosting the worker yourself.
