### ISSUE TITLE
pdf is rotated by default

### ISSUE THREAD

**Issue by xiaoyangzi** [wojtekmaj/react-pdf#53]
when a pdf page's width is larger than height the page is rotated.
here is the render result:
<img width="965" alt="qq20170904-164443 2x" src="https://user-images.githubusercontent.com/6845793/30018686-6ff4e208-9190-11e7-9d05-ee8f5f9471ac.png">
and here is the file opened in Chrome:
<img width="1164" alt="qq20170904-164648 2x" src="https://user-images.githubusercontent.com/6845793/30018776-c79f4f5c-9190-11e7-9cf0-f91db13def5d.png">
here is the config:
`<ReactPDF
                      file={fileHeaders}
                      pageIndex={pageIndex}
                      onDocumentLoad={this.onDocumentLoad.bind(this)}
                      onPageLoad={this.onPageLoad}
                      loading={<div><Spin/></div>}
                      width={width}
                      style={{width:width, height:single?(height-40):'100%',overflowY:'auto', overflowX:'hidden',margin:'0 auto'}}
                  />`

**Comment by wojtekmaj** [comment]
Hey! That is one of the issues that have been fixed in version 2.0. It's currently nearing release and you can try the beta already! The update should be relatively easy and it's definitely worth checking out all the new functionalities and improvements :)

**Comment by xiaoyangzi** [comment]
thanks a lot

**Comment by wojtekmaj** [comment]
@xiaoyangzi, for your information - v2.0.0 (non-beta) just went live!
