### ISSUE TITLE
React PDF working with the response from a POST

### ISSUE THREAD

**Issue by sbitproz** [wojtekmaj/react-pdf#532]
**Objective**

I'm trying to load a PDF into react-pdf viewer following a POST request to the backend. I'm sending some DOM elements to the backend to render a PDF, this is being sent through the POST body.

**Solutions I've tried**

On the README section the document has a file prop, which has three possible input formats.  I've tried making the request for the PDF file and passing the response contents into the Document file prop via the React component state.  Currently I just receive "Failed to load PDF file.".
  
```
  const print = () => {
    const domElement = document.querySelector('html');
    printDomElements(domElement, setFile);
  }
```
```
      <button onClick={print}>Print this page</button>
      {!file ? null : (
        <Document file={file}></Document>
      )}
```
printDomElements makes an axios request and sets the state through the callback function.

I've also considered using the structure below, but it looks like this is probably for a GET request only (maybe I'm wrong): 

`{ url: 'http://example.com/sample.pdf', httpHeaders: { 'X-CustomHeader': '40359820958024350238508234' }, withCredentials: true }
`

Any ideas how I can pipe the response of the POST request into React PDF?

**Environment**
 - Chrome 80
"react-pdf": "^4.1.0",
"react": "16.8.6",

**Comment by wojtekmaj** [comment]
The correct approach here would be to fetch the file yourself and pass it into file prop directly. For more detailed response I'd need to know how exactly the response from the server looks like, but if you manage to create a Blob with PDF then you're almost golden.

**Comment by sbitproz** [comment]
Thanks for coming back to me so quickly.

That's great, because that's what I'm doing at the moment.  However when I drop the blob response into the <Document file={response.data}>... tag it says 'Failed to load PDF file.' 

![image](https://user-images.githubusercontent.com/48489724/76251010-3f6fb000-623e-11ea-8694-84a5f7316b3d.png)

I thought that it might require some transformation to base64, but I'm having a few issues there too.  I'm using CRA and I've copied the pdf.worker.js file (that error is no longer popping up).

![image](https://user-images.githubusercontent.com/48489724/76251198-907fa400-623e-11ea-81ff-c554b514a348.png)

Any ideas?

**Comment by wojtekmaj** [comment]
Well you'll only need actual data from `data` key, that's for sure. I'm worried it's a text, because PDF is definitely a binary. Once you concert it to Blob or base64vit should be fine. You can easily verify Blob because they get these temporary URLs you can simply load in your browser. When you do this and it either opens your PDF or downloads it and it's opening fine, then there shouldn't be a problem with React-PDF opening it either.

**Comment by sbitproz** [comment]
I recognise that **unescape** is deprecated, but I just want to get a working model first.  So this is how things are looking.  
```
  API.post('https://XYZ/api/render', domElements, config ).subscribe(
    response => {
      //btoa(response.data);
      let b64 = btoa(unescape(encodeURIComponent(response.data))); 
      console.log(b64);
      debugger;
      callback(b64);
    }
  )
```
The request goes out, I get a response and convert it to base64.  I've taken the console output and dropped it in here [base64 guru](https://base64.guru/converter/decode/pdf) - on conversion I get a blank PDF back.  To make sure that isn't a default erroneous conversion, I removed some characters from the base 64 and reconverted it - which obviously doesn't work. 

The callback function set's the state.  It appears then react-pdf tries to make a request for the data.  How do I tell it that this file is a base64?

GET http://localhost:3000/ppm/JVBERi0xLjQKJdPr6eEKMSAwIG9iago8PC9DcmVhdG9yIChDaHJvbWl1bSkKL1Byb2R1Y2VyIChTa2lhL1BERiBtNzkpCi9DcmVhdGlvbkRhdGUgKEQ6MjAyMDAzMDUxMTEyNTYrMDAnMDAnKQovTW9kRGF0ZSAoRDoyMDIwMDMwNTExMTI1NiswMCcwMCcpPj4KZW5kb2JqCjMgMCBvYmoKPDwvY2EgMQovQk0gL05vcm1hbD4+CmVuZG9iago0IDAgb2JqCjw8L1R5cGUgL1hPYmplY3QKL1N1YnR5cGUgL0ltYWdlCi9XaWR0aCAyNzIKL0hlaWdodCA5MgovQ29sb3JTcGFjZSAvRGV2aWNlUkdCCi9TTWFzayA1IDAgUgovQml0c1BlckNvbX...

![image](https://user-images.githubusercontent.com/48489724/76307988-ca45be80-62c1-11ea-8543-561eec259c28.png)

**Comment by SailleshPawar** [comment]
@sbitproz Were you able to resolve this?

**Comment by sbitproz** [comment]
Hi @SailleshPawar i was by doing the following:

```
 <Document
            file={`data:application/pdf;base64,${fileBase64}`}
            onLoadSuccess={onDocumentLoadSuccess}
          >
          <Page pageNumber={documentPages.pageNumber} />
</Document>
```
The key being **data:application/pdf;base64,** - base64 sufficed for me.

I think the documentation needs to be updated address the base64 format.

**Comment by SailleshPawar** [comment]
@sbitproz can you share codepen I am currently looking into the solution to post the pdf to the api.
Your implementation might help me solve my problem. As I am not able to find this in docs.

**Comment by sbitproz** [comment]
@SailleshPawar I haven't got a codepen, if you have one I could review it.  But my issue was related to the PDF rendering on react-pdf component specifically.

**Comment by SailleshPawar** [comment]
@sbitproz  I want to send the pdf in base 64 or other format to the API.
              

` <BlobProvider document={<PdfDocument data={movieDetails} />}>
         {({ blob, url, loading, error }) => {
           // Do whatever you need with 
           debugger;
           if(blob!==null){
           const reader = new FileReader()
           reader.readAsDataURL(blob);
           console.log(reader.result);
           
          }
          {blob && console.log(blob.arrayBuffer())} 
           return <div>There's something going on on the fly</div>
         }}
       </BlobProvider>`

I was trying to get the base 64 of the PdfDocument

**Comment by sbitproz** [comment]
I used the following to convert my source to base64 

`Buffer(pdfBytes).toString('base64')`

I'm not sure if that will help you though.

**Comment by SailleshPawar** [comment]
@sbitproz  can you share any small code snippet with component.
For example I am not clear from where you are getting pdfBytes.
I would really grateful to you if you can share example with code snippet that I can test.

**Comment by Kasunthilina** [comment]
@SailleshPawar 
when you do a post request to get data. you should pass bellow parameter in header section 
responseType: 'arraybuffer',
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/pdf',
      }
