### ISSUE TITLE
Can't resolve '@babel/runtime/helpers/getPrototypeOf'

### ISSUE THREAD

**Issue by VinhVu0412** [wojtekmaj/react-pdf#537]
**Before you start - checklist**

 - [x] I have read the documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real-life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
Version 4.1.0 fails on `yarn start`. The error message is `Module not found: Can't resolve '@babel/runtime/helpers/getPrototypeOf' in '[project-path]/node_modules/react-pdf/dist'`
The @babel/runtime exists in  `[project-path]/node_modules/` but not in  `[project-path]/node_modules/react-pdf/dist`

**Describe solutions you've tried**

I tried the solution in this https://github.com/wojtekmaj/react-pdf/issues/361 but it doesn't work.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]: 4.1.0
 - React version [e.g. 16.3.0]: 16.4.0
 - Webpack version (if applicable) [e.g. 4.16.2]: 3.10.0

**Comment by wojtekmaj** [comment]
Hmmm, looks like your installation is messed up for some reason. react-pdf (or Node, to be exact) should be perfectly able to pick up @babel/runtime from your main node_modules folder.

Try:
```sh
rm -rf node_modules
npm i
```

If that doesn't help, I'd manually check if @babel/runtime/helpers/esm/getPrototypeOf actually exists in your node_modules directory. If that's not the case, you may be running an incompatible version of @babel/runtime which we were not aware that it doesn't have the helper in question. I know some @babel/runtime betas were having this issue, but I'm not aware of any stable release having it.

**Comment by VinhVu0412** [comment]
I tried
```
rm -rf node_modules
yarn install
```
but it doesn't work. I think the problem is about conflicting @babel/runtime version, then I fix it with
```
  "resolutions": {
    "@babel/runtime": "7.8.7"
  },
```
Eventually, I met this error `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`. It is still [an open issue](https://github.com/wojtekmaj/react-pdf/issues/280) and hasn't had a proper solution yet.
Some hacks which modify the webpack config don't work in my case. I use an internal scripts library (similar to react-scripts) which has a fixed webpack config.

**Comment by wojtekmaj** [comment]
`Critical dependency: …` error is unrelated so if you see it that means the issue with @babel/runtime was resolved.

**Comment by VinhVu0412** [comment]
Yes, we need to close this issue
