### ISSUE TITLE
passing in just a base 64 data set is not working.. nor a blob

### ISSUE THREAD

**Issue by rchancey** [wojtekmaj/react-pdf#539]
Is there a way to just pass in the blob of data? And not have to download anything?

I have the base64 data in hand.. just want to pass it to the report.. and it keeps saying 403 and not  able to download the file.

Failed to load resource: the server responded with a status of 403 (Forbidden).. something with pdf workers.

I don't need it to download .. I need it to process the base64 content or I can leave it encoded.. any ideas?

**Comment by rchancey** [comment]
I tried this: 

  const file = new Blob([report], { type: 'application/pdf' });
            const fileUrl = URL.createObjectURL(file);


 <Document
                        file={{ data: fileUrl }}
                        onLoadSuccess={this.onDocumentLoadSuccess}
                        loading={'Please wait, the document is loading!'}
                        onLoadError={console.error}
                    />

and get this error:
details: "Error: The API version \"2.1.266\" does not match the Worker version \"2.3.200\"."

**Comment by rchancey** [comment]
@wojtekmaj a lot of us are trying to pass in a base64 document.. not from a URL.. not all apps allow download from URLS.. If you could provide an example it would help quite a few of us..

**Comment by wojtekmaj** [comment]
You can't just pass base64 as an URL. You need to prefix it with `data:application/pdf;base64,`, otherwise it's not a valid URL. A good way to check if it's gonna work or not is just paste the URL you created in the browser and see if it opens or downloads a valid PDF.

**Comment by wojtekmaj** [comment]
@rchancey the error with versions not matching is unrelated. You configured React-PDF worker wrongly. Perhaps you hardcoded the worker version, or forgot to update manually hosted worker after React-PDF update.

**Comment by rchancey** [comment]
@wojtekmaj I did not configure a PDF worker. 

import { Document } from 'react-pdf'

report = "data:application/pdf;base64," + report

 <Document file={report}/>

I made the change you suggested and now I am getting this forbidden error
I did not set up any worker.. I am just running a vanilla React app.. not using web pack or parcel 
Is there a default pdf worker that I can configure.. I am not even sure what that is :-( 


pdf.js:11096 GET http://localhost:3000/pdf.worker.js 403 (Forbidden)
pdf.js:549 Warning: Setting up fake worker.

**Comment by wojtekmaj** [comment]
Absolutely no idea based on the information you have me.

* Use onSourceError, onLoadError to be informed about errors when loading the file
* If this isn't helpful, send me full exact example of what ends up in `file` prop.

**Comment by rchancey** [comment]
WOOT!! that worked. I guess I needed to have a Page element inside the document.

so the trick was adding the "data:application/pdf;base64," as the prefix to the bas64 content, and adding a Page element with a default pageNumber to the Document.

Thanks @wojtekmaj for the help.. I did have a question on the width but will ask that separatly
