### ISSUE TITLE
Pdf-url  showed in component   is not at  the same with the Original graph .

### ISSUE THREAD

**Issue by valiantandheroicinbearing** [wojtekmaj/react-pdf#540]
**Before you start - checklist**

  

**Description**
Pdf-url  showed in component   is not at  the same with the Original graph .
 

**Steps to reproduce**

1.  <Document
          file= 'https://gw.alipayobjects.com/os/bmw-prod/87ed81f6-c2ab-4d72-9263-411444ed236c.pdf'
          onLoadSuccess={onDocumentLoadSuccess}
          className={`${styles.pdfWrap} ${'agreement_preview'}`}
        >
            <Page pageNumber={1}  />
        </Document>
2 .     This is the effects.
![image](https://user-images.githubusercontent.com/18433428/77642434-9db7c500-6f98-11ea-8a04-66b1bdc94083.png)

**Comment by valiantandheroicinbearing** [comment]
> **Before you start - checklist**
> 
> **Description**
> Pdf-url showed in component is not at the same with the Original graph .
> 
> **Steps to reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. <Document
>    file= 'https://gw.alipayobjects.com/os/bmw-prod/87ed81f6-c2ab-4d72-9263-411444ed236c.pdf'
>    onLoadSuccess={onDocumentLoadSuccess}
>    className={`${styles.pdfWrap} ${'agreement_preview'}`}
>    >
>    
>    
>    2 .

**Comment by wojtekmaj** [comment]
I'm not sure what you mean... Pdf-url? Graph?

**Comment by wojtekmaj** [comment]
Note: This works in the up-to-date React-PDF.
