### ISSUE TITLE
How to get base 64 of the pdf from blobprovider or pdfdocument

### ISSUE THREAD

**Issue by SailleshPawar** [wojtekmaj/react-pdf#541]
I want to send the pdf generated with multple pages to be converted to base64 or memory stream to 
 be send to the server side API

**Comment by wojtekmaj** [comment]
PDF generation is not this library's responsibility, so I won't be able to help you. Sorry.

**Comment by SailleshPawar** [comment]
@wojtekmaj I might have asked the question in a wrong way, it there any way I can get base64 for pdfdocument or blobprovider in react-pdf that I can send to the backend api?

**Comment by wojtekmaj** [comment]
You might be talking about diegomura's @react-pdf/renderer...
