### ISSUE TITLE
Generating table of content

### ISSUE THREAD

**Issue by kierstejn** [wojtekmaj/react-pdf#542]
Hey! I am trying to create a table of content in the top of my Document with name and page index. I have tried creating my own promise that i call when i know where the main sections are, and what page index they have, but i cant seem to get it to work. Any workaround or way to achieve this?

**Comment by wojtekmaj** [comment]
Hi!
You can use Outline component to render ToC. 
If you want to implement it by yourself, it should be relatively easy. In onDocumentLoad, you get entire `pdf` or `document` (can't remember how I called it, on mobile) object with all the methods usually returned by PDF.js available. You can use Outline component source code to see how it's being used, and even copy the entire thing and experiment on it, why not :)
