### ISSUE TITLE
React-Pdf cannot load pdf file. It keeps saying 'Failed to load PDF file.'

### ISSUE THREAD

**Issue by Malieh** [wojtekmaj/react-pdf#546]
I want to use react-pdf to read pdf files in my react project. I installed react-pdf. I copied the code in sample.jsx in the GitHub repo and added it to my project. I provided the link of a valid document to the file prop of the document component but the pdf is not loading. It keeps saying  'Failed to load PDF file.'

 - React-PDF version 4.1.0
 - React version  16.13.1

**Comment by haihninit** [comment]
Try to import this one, bro.
`import { Document, pdfjs } from "react-pdf";`
`pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js``

**Comment by wojtekmaj** [comment]
⬆️ This and https://github.com/wojtekmaj/react-pdf/wiki/Frequently-Asked-Questions#when-im-trying-to-load-a-pdf-file-from-an-external-source-im-given-a-message-failed-to-load-pdf-file

**Comment by IanChok** [comment]
@wojtekmaj I have the same issue but I'm using create-react-app with typescript. 
`pdf.tsx`: 
```ts
import React, { useState } from 'react';
import { Document, Page, pdfjs } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
 
function PDF() {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);
 
  //@ts-ignore
  const onDocumentLoadSuccess = ({ numPages }) => {
    setNumPages(numPages);
  }
 
  return (
    <div>
      <Document
        file="/dummy.pdf"
        onLoadSuccess={onDocumentLoadSuccess}
      >
        <Page pageNumber={pageNumber} />
      </Document>
      <p>Page {pageNumber} of {numPages}</p>
    </div>
  );
}

export default PDF
```

![image](https://user-images.githubusercontent.com/33184246/90298566-9e69ce80-de47-11ea-8d81-5cc19137efd5.png)

![image](https://user-images.githubusercontent.com/33184246/90298607-bf322400-de47-11ea-91af-40ef132f2bf0.png)

![image](https://user-images.githubusercontent.com/33184246/90298634-d83ad500-de47-11ea-9f5a-ff9b53e14e00.png)

Not sure if this might be a typescript issue or a react-pdf issue 🤔 Any suggestions?
Thanks 😄

**Comment by wojtekmaj** [comment]
Well, neither. Clearly PDF file is not there, so you need to put it there on the server.

**Comment by IanChok** [comment]
Ah got it, I had to put the pdf file in the `./public` folder 🤦‍♂️
