### ISSUE TITLE
Can't get customTextRenderer result and collect some info during text layer render

### ISSUE THREAD

**Issue by matolg** [wojtekmaj/react-pdf#547]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'm trying to get search matches count after component rendered

**Describe solutions you've tried**

I'm using an example from recipes for this purpose https://github.com/wojtekmaj/react-pdf/wiki/Recipes#highlight-text-on-the-page;
the only what I've added is counter outside of `highlightPattern` like this:
```javaScript
let searchCount = 0;
const highlightPattern = (text, pattern) => {
  ...
  searchCount += matches.length;
  return highlightedText;
}

useEffect(() => {
   onSearchCountChanged(searchCount);
}, [searchCount, onSearchCountChanged]);
```
**Question:** It appears during debug, that first code in `useEffect` runs and then `highlightPattern` performed, so I can't get highlight statistics. **_Is there any way to do this?_**

**Environment**

 - Browser: 80.0.3987.149
 - React-PDF version: 4.0.3
 - React version: 16.9.26
 - Webpack version: 4.4.24

**Comment by wojtekmaj** [comment]
Since your searchCount isn't in state, then useEffect can't be reliably run, because it will not know about searchCount value change. You'd need to use state to keep the search count, but that could result in an infinite loop of updates... I guess the best way would be to run onSearchCountChanged directly in highlightPattern 🤔

**Comment by matolg** [comment]
Thanks. I've ended up extracting all text content from pages beforehand and counting matches in advance, this worked for me fine.

**Comment by samscarsella** [comment]
I have a similar use case. In addition to results count, I'd like to implement a 'scroll to prev/next occurrence'. But I can't figure out a way to attach a ref to that <mark> element from highlightPattern().

**Comment by wojtekmaj** [comment]
@samscarsella I think given that you would end up with multiple, unknown number of occurrences, ref is not the way. You could add something like `data-occurrence data-occurrence-index="0"` to your `mark` elements and keep the counter somewhere to be able to find these elements later using `document.querySelector`. Hell, even `getElementsByTagName('mark')` should be enough in most cases.
