### ISSUE TITLE
canvas 

### ISSUE THREAD

**Issue by premsonbaby** [wojtekmaj/react-pdf#548]
Hi,

Is it possible to change the flowing element to use "width: 100%;height: 100%;"
instead of current hard coded values. Due to this the canvas is not staying inside the parent element. It's affecting responsiveness when viewed in small screens. 

<canvas class="react-pdf__Page__canvas" style="display: block;user-select: none; width="595" height="841"></canvas>

Thank you.

**Comment by premsonbaby** [comment]
also noticed the same for below div

<div class="react-pdf__Page__textContent" 

this is also going beyond parent elements, due to element style.

**Comment by premsonbaby** [comment]
making canvas 100% will stretch the pdf content. 
any suggestions to solve this issue?

**Comment by premsonbaby** [comment]
looks like its the width prop controlling this.

**Comment by wojtekmaj** [comment]
No, not possible. Canvas needs to have some width and height defined. You can, however, use CSS to apply styling you desire.
