### ISSUE TITLE
Cancel a network request while downloading

### ISSUE THREAD

**Issue by jayqizone** [wojtekmaj/react-pdf#549]
Sometimes a pdf file is too large to download, but there is seems no way to cancel this network request

I've found PDFDocumentLoadingTask.destroy() could terminate all I/O operations and it does work for me, but I can't fetch the original pdfjs.getDocument() object while loading since which is wrapped as a promise, is there an API could expose this before onLoadSuccess?

thanks 🙏

**Comment by wojtekmaj** [comment]
Unmounting Page component should stop it from being loaded.

**Comment by NooAn** [comment]
Can you give some example? I think it's pretty useful 
I mean, I have a big pdf file(100-150 mb) I would stop it after 30-50 % downloading

**Comment by wojtekmaj** [comment]
Loaded != downloaded. We can't stop a network request. However, if a server supports [HTTP range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests), then you should be able to browse PDF without downloading it fully.

**Comment by jayqizone** [comment]
![image](https://user-images.githubusercontent.com/8263369/82013192-44246a80-96ac-11ea-9159-1fb1aa32b4ec.png)
I hope it's ok I uploaded this snippet as an img

I tried to override loadDocument function by ref (very disturbing I know 🙈 ), then when I switch to an new pdf, the former request is terminated

Someway somehow it works, just an FYI
