### ISSUE TITLE
Links not clickable in the rendered pdf. 

### ISSUE THREAD

**Issue by rishabhbatra10** [wojtekmaj/react-pdf#552]
I did read the previous issue #199 which had explained some of the possible reasons links are not working and hence I imported the AnnotationLayer.css. But still, I am facing this issue of links not being clickable.

Here is my code 

```javascript
import React, { Component } from 'react';
import { pdfjs, Document, Page } from "react-pdf";

import 'react-pdf/dist/Page/AnnotationLayer.css';
import './__style.css';

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

class Catalogue extends Component {
  constructor(props){
    super(props);
    this.state = { numPages: null, pageNumber: 1 };
  }

  onDocumentLoadSuccess = ({ numPages }) => {
    this.setState({ numPages });
  };

  goToPrevPage = () => {
    const { pageNumber } = this.state
    if (pageNumber !== 1) {
      this.setState(state => ({ pageNumber: state.pageNumber - 1 }));
    }
  }
  goToNextPage = () => { 
    const { pageNumber, numPages } = this.state
    if (pageNumber !== numPages) {
      this.setState(state => ({ pageNumber: state.pageNumber + 1 }));
    }
  }
  getPages = () => {
    const items = []
    let i = 1
    let { numPages } = this.state
    while (i <= numPages) {
      items.push(<Page pageNumber={i} key={i * Math.floor(Math.random() * 1000) + 1} style=""/>);
      i++;
    }  
    return items
  }

  render() {
    return (
      <div class="magazine">
        <div>
          <Document
            file={process.env.PUBLIC_URL + '/files/' + this.props.pdfFile}
            onLoadSuccess={this.onDocumentLoadSuccess}
          > 
            {this.getPages()}
          </Document>
        </div>
      </div>
    );
  }
}

export default Catalogue
```

Please let me know if I am missing out anything. Thanks!

<img width="1402" alt="Screenshot 2020-04-15 at 4 08 17 PM" src="https://user-images.githubusercontent.com/15319538/79328279-61420e00-7f33-11ea-8123-ec648330ff4a.png">

**Environment**

 - React-PDF version [e.g. 3.0.4]: 4.1.0
 - React version [e.g. 16.3.0]: 16.12.0

**Comment by wojtekmaj** [comment]
Try adding 
```jsx
onRenderAnnotationLayerSuccess={console.log}
onRenderAnnotationLayerError={console.error}
onGetAnnotationsError={console.error}
```

to your `<Page />` component. Maybe it will tell us something. If not, we'll need to make an interactive codepen to see what the problem might be.

BTW:
```jsx
key={i * Math.floor(Math.random() * 1000) + 1}
```

that's a horrible, horrible idea.

**Comment by rishabhbatra10** [comment]
Thank you for your reply @wojtekmaj. I added the event listeners but nothing is logged on any of the above listeners. 
While onLoadSuccess logs this 
<img width="1402" alt="Screenshot 2020-04-15 at 4 08 17 PM" src="https://user-images.githubusercontent.com/15319538/79336015-9e60cd00-7f40-11ea-81c5-5f00e062728b.png">

Is there anything we should make sure to add in pdfs to make the links like this work?

**Comment by wojtekmaj** [comment]
If neither onRenderAnnotationLayerSuccess nor onRenderAnnotationLayerError were called, then no annotations were loaded. Check is onGetAnnotationsSuccess callback returns something (it should).

Attach PDF file if it still fails.

**Comment by rishabhbatra10** [comment]
onGetAnnotationsSuccess callback returns blank arrays, here is the pdf file. 
[pankhuri-issue_1-vol_1.pdf](https://github.com/wojtekmaj/react-pdf/files/4481169/pankhuri-issue_1-vol_1.pdf)

**Comment by tjsudarsan** [comment]
@rishabhbatra10 I too faced the same problem, but this is nothing to do with the @wojtekmaj's react-pdf library. 

I just converted my pdf to word which has links that's not working and found that the hyperlinks are not added to those texts. So, I added the hyperlinks in the word documents and then converted to PDF, hosted it on my server again. 

Now, it's working fine and I get the links in onGetAnnotationsSuccess callbacks too.

The problem is we got confused that the links without hyperlinks works both on Adobe Reader and also on the Chrome PDF Viewer. It seems, they detect the links that are not hyperlinked and hyperlink the same, thus working.

**Comment by zendy-nguyen-goldenowl** [comment]
[Lương-Thị-Thu-Hương-Xây-dựng-chiến-lược-TMĐT-1-1.docx.pdf](https://github.com/wojtekmaj/react-pdf/files/7615405/L.ng-Th.-Thu-H.ng-Xay-d.ng-chi.n-l.c-TMDT-1-1.docx.pdf)

**Comment by asharafshahi** [comment]
I'm on version 5.7.1 and `import 'react-pdf/dist/Page/AnnotationLayer.css'` doesn't work.  I tried `import 'react-pdf/dist/esm/Page/AnnotationLayer.css'` but get this: 
<img width="552" alt="image" src="https://user-images.githubusercontent.com/30377967/172906283-e278bb8b-4489-42a4-b94b-2df853efc7fe.png">

Any other options for getting links to actually work in the rendered PDF?

**Comment by Mabule** [comment]
> > I'm on version 5.7.1 and `import 'react-pdf/dist/Page/AnnotationLayer.css'` doesn't work. I tried `import 'react-pdf/dist/esm/Page/AnnotationLayer.css'` but get this: <img alt="image" width="552" src="https://user-images.githubusercontent.com/30377967/172906283-e278bb8b-4489-42a4-b94b-2df853efc7fe.png">
> > Any other options for getting links to actually work in the rendered PDF?
> 
> This import got it working for me. `import 'react-pdf/dist/esm/Page/AnnotationLayer.css'; `

Thanks, it perfectly work for me !
