### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by freestyle09** [wojtekmaj/react-pdf#553]
Hi,

I want to ask you if there's any way to implement progress bar on generating pdf ? Actually I am creating some big pdfs now and sometimes generating takes almost 30s so I have decided to display progress bar from it but actually I can't find any information on how to do it and whether it can be done at all. Greetings

**Comment by wojtekmaj** [comment]
Check onLoadProgress in README. It's a simple example with `alert` but should be enough to get you going.

**Comment by freestyle09** [comment]
Thanks! :)
