### ISSUE TITLE
Silent failure to render PDF

### ISSUE THREAD

**Issue by ryandrew14** [wojtekmaj/react-pdf#557]
**Description**

On Firefox, with CRA (using CDN for pdfworker), I am getting a silent failure to load my PDF. I see no error messages in the console, I definitely have data as Uint8Array, and I see the "Loading PDF..." text in the Document component, but I 

**Steps to reproduce**

Start project with CRA. Get Uint8Array PDF data, feed into Document component through `{ data: <array> }`.

**Expected behavior**

I'd expect the PDF to render as normal, or an error message to be displayed in either browser or console, but I see nothing.

<img width="1440" alt="Screen Shot 2020-04-24 at 7 16 04 AM" src="https://user-images.githubusercontent.com/13836027/80207145-a03f2600-85fb-11ea-96aa-da48ae5edeff.png">

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: FF 75
 - React-PDF version [e.g. 3.0.4]: 4.1.0
 - React version [e.g. 16.3.0]: 16.12
 - Webpack version (if applicable) [e.g. 4.16.2]: CRA w/ react-scripts 3.4.0

**Comment by wojtekmaj** [comment]
Your implementation seems correct, at least from the descripton. Try attaching debug props like `onSourceError`, `onLoadError`, `onRenderErrora` (the simplest is to `on...Error={console.error}`) and maybe some additional information will emerge.

**Comment by streetguy911** [comment]
same issue on version 5.0.0.
file loaded normally, onSourceSuccess and onLoadSuccess called callbacks, onSourceError and onLoadError didn't.
console is clear.
what do you think about it?

react v16.13.1 (same as in your live demo)
and also I am using the same document

**Comment by streetguy911** [comment]
here is an example of usage
https://codesandbox.io/s/modest-chatterjee-orx4p?file=/src/App.jsx

could you please check it?

**Comment by streetguy911** [comment]
@wojtekmaj is there any chance you can check this issue at the nearest future?

**Comment by SevenZark** [comment]
I have basically the same issue, though I am using webpack (and a bit of TypeScript).

In the example code below, props.imageSrc.original is a base64 string. When run, the onSourceSelect event gets fired and returns undefined for event.

```
import React, { FC } from 'react';
import {
    Button,
    Dialog,
    DialogContent,
    DialogTitle,
    Grid
} from 'componentlib';
import { pdfjs, Document, Page } from 'react-pdf/dist/esm/entry.webpack';

interface Props {
    imageSrc: {
        cropped,
        original
    };
    onClose: Function;
    onSave: Function;
}

const SelectPdfPageDialog: FC<Props> = props => {

    const {
        imageSrc,
        onClose,
        onSave
    } = props;

    const onLoadSuccess = event => {
        console.log("LOAD SUCCESS", {event})
    }

    const onLoadError = event => {
        console.log("LOAD Error", {event})
    }

    const onPassword= event => {
        console.log("Password", {event})
    }

    const onSourcError = event => {
        console.log("Source Error", {event})
    }

    const onSourceSuccess = event => {
        console.log("Source Success", {event})
    }

    return <Dialog
        onClose={onClose}
        open={true}
        fullScreen
    >
        <DialogTitle onClose={onClose}>
            Select PDF Page
        </DialogTitle>
        <DialogContent>
            <Document
                file={imageSrc.original}
                onLoadSuccess={onLoadSuccess}
                onLoadError={onLoadError}
                onPassword={onPassword}
                onSourceError={onSourcError}
                onSourceSuccess={onSourceSuccess}
                options={{
                    cMapUrl: `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/cmaps/`,
                    cMapPacked: true,
                }}
            >
                <Page pageNumber={0} />
            </Document>
        </DialogContent>
    </Dialog>
}

export default SelectPdfPageDialog;
```

**Comment by wojtekmaj** [comment]
@streetguy911 Your issue is unrelated. You created Document context, but decided not to render any pages inside. [Here's](https://codesandbox.io/s/peaceful-pine-7dbsr?file=/src/App.jsx) your example complemented with [recipe to display all pages](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages).

**Comment by wojtekmaj** [comment]
@SevenZark There's no such thing as `pageNumber={0}`. You confused it with `pageIndex`.

**Comment by streetguy911** [comment]
> @streetguy911 Your issue is unrelated. You created Document context, but decided not to render any pages inside. [Here's](https://codesandbox.io/s/peaceful-pine-7dbsr?file=/src/App.jsx) your example complemented with [recipe to display all pages](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages).

Thanks you! I really missed that
