### ISSUE TITLE
Use pdf.js inside a Web Worker

### ISSUE THREAD

**Issue by tandat2209** [wojtekmaj/react-pdf#558]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Using pdf.js inside a WebWorker?

**Describe solutions you've tried**

I'm using pdf.js to generating images from pdf documents .

It works OK. But during the generating process, it's blocking the main thread which is causing some UI issues.

So then I want to move all the logic to a Web Worker to free the main thread.

But when running in the web worker, there is an error:

> pdf.js:11210 Uncaught (in promise) Error: Setting up fake worker failed: "webpack_require(...).ensure is not a function".

It's thrown from this function [setupFakeWorkerGlobal](https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L1627-L1675)

My guess is it can not load the `workerSrc`, so it has to use fake worker with throw error. :(

I'd appreciate any helps.

**Environment**

 - Browser: Chrome 81
 - React-PDF version: 4.1.0
 - React version: 16.8.6

**Comment by tandat2209** [comment]
I asked a question in StackOverflow here: https://stackoverflow.com/questions/61409061/using-pdf-js-inside-a-webworker

**Comment by wojtekmaj** [comment]
Please kindly check React-PDF [`v5.3.0-beta.2`](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.3.0-beta.2), in which improvements regarding loading PDF.js worker were made. 

These changes should result in 10-15 seconds faster Webpack builds, as well as you should be able to use Webpack entry file in Create-React-App, without the need of using external CDN for hosting worker.

Let me know what you think in #748!
