### ISSUE TITLE
Digital signature is not visible

### ISSUE THREAD

**Issue by shashiachar** [wojtekmaj/react-pdf#559]
Digital signature is not visible in PDF preview. Request you to guide me in this.

**Comment by wojtekmaj** [comment]
Please follow [Bug report template](https://github.com/wojtekmaj/react-pdf/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md).

Then, try enabling `renderAnnotationLayer` and perhaps even `renderInteractiveForms` 🤔 

If that doesn't help, attach PDF and we'll see.

**Comment by shashiachar** [comment]
I tried but its not working Please help me 
[Sample1.pdf](https://github.com/wojtekmaj/react-pdf/files/4711043/Sample1.pdf)

**Comment by shashiachar** [comment]
I tired but its not working please help me 
[sample (1).pdf](https://github.com/wojtekmaj/react-pdf/files/4711084/sample.1.pdf)

**Comment by wojtekmaj** [comment]
If you followed bug template you would see that this also happens in Firefox, and as such this is a bug you should rather raise against pdf.js library, not React-PDF.

**Comment by wojtekmaj** [comment]
Support for Sig type has been added in [v5.4.0-beta.2](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.4.0-beta.2).
