### ISSUE TITLE
IE11 not able to load PDFJS worker

### ISSUE THREAD

**Issue by FrederickEngelhardt** [wojtekmaj/react-pdf#560]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

IE11 does not render PDFs with 5.0.0-beta.3 or latest version 4.1

**Steps to reproduce**

1. Use IE11
2. Load any PDF using a URL (or local file)
3. See the following error
![Screen Shot 2020-04-30 at 7 56 38 AM](https://user-images.githubusercontent.com/31741411/80725589-20600280-8ab8-11ea-8f8a-952a1dc4c59c.png)

Also noting that with this library I have to add a worker SRC otherwise the PDF will not load.
```
import { Document, Page, pdfjs } from 'react-pdf'
...
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`
```

**Expected behavior**

IE11 should load PDF js documents. Also noting that `@mikecousins/react-pdf` will load. So perhaps there is a method or configuration to support IE11 that is missing.

**Additional information**

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: IE11 (chrome & firefox have no issue)
 - React-PDF version [e.g. 3.0.4]: 4.1 and also tested on 5.0.0-beta.3
 - React version [e.g. 16.3.0]: 16.13.0
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.42.0

**Comment by FrederickEngelhardt** [comment]
Side note, 5.0.0-beta.2 works.

**Comment by wojtekmaj** [comment]
If you use beta.3 with forced version of pdf.js that was used in beta.2 (`yarn set resolution pdfjs-dist@2.3.200 2.2.228`), does it work?

**Comment by FrederickEngelhardt** [comment]
Not using yarn. But going into the package.lock and making the change in pdf-js should be the same. Did not see a different error. Got the same worker error.

Tried this as well.
```
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.2.228/pdf.worker.js`
```

```
    "react-pdf": {
      "version": "5.0.0-beta.3",
      "resolved": "https://registry.npmjs.org/react-pdf/-/react-pdf-5.0.0-beta.3.tgz",
      "integrity": "sha512-+5JXiER6DDOiyCLvYjjLPyqTb1eKANFOS0v6IjxYXctC2uMG/jvD5wcTlqLlB2WAwgRtdcZYWZ2lyWDteRGvmw==",
      "requires": {
        "@babel/runtime": "^7.0.0",
        "make-cancellable-promise": "^1.0.0",
        "make-event-props": "^1.1.0",
        "merge-class-names": "^1.1.1",
        "prop-types": "^15.6.2"
      },
      "dependencies": {
        "pdfjs-dist": {
          "version": "2.2.228",
          "resolved": "https://registry.npmjs.org/pdfjs-dist/-/pdfjs-dist-2.2.228.tgz",
          "integrity": "sha512-W5LhYPMS2UKX0ELIa4u+CFCMoox5qQNQElt0bAK2mwz1V8jZL0rvLao+0tBujce84PK6PvWG36Nwr7agCCWFGQ==",
          "requires": {
            "node-ensure": "^0.0.0",
            "worker-loader": "^2.0.0"
          }
        }
      }
    },
```

**Comment by FrederickEngelhardt** [comment]
Also noting that the demo url http://projects.wojtekmaj.pl/react-pdf/ does not load for ie11.

**Comment by stlst** [comment]
Faced the same error. Does react-pdf support ie11?

**Comment by wojtekmaj** [comment]
It does, but IE11 doesn't support Promises. So you either need to add all necessary polyfills until it stops crashing, or configure Babel properly to do it for you.

**Comment by david-pulse** [comment]
Facing issues with IE11 as well... I do think it needs to be a babel configuration problem... It appears that my webpack configuration is not compiling the `react-pdf` import of `pdfjs-dist` to es5.

When I look at the compiled code, it is still using es6 code which is why it's failing on IE11. It would be great if we could get an IE11 compatible config.

**Comment by wojtekmaj** [comment]
Unfortunately, in v5, support for IE 11 has been dropped. There's nothing we can do about it. Sorry about that!

If you still need to continue support IE 11, you're stuck at v4.x.

See thread: https://github.com/wojtekmaj/react-pdf/issues/495#issuecomment-662036968
