### ISSUE TITLE
Render custom HTML markup inside pdf document

### ISSUE THREAD

**Issue by abollam** [wojtekmaj/react-pdf#563]
Hi all, I am trying to render HTML inside the `<View>/<Text>` component while rendering the PDF inside the  `<PDFViewer>` using a Template.

I'd like to render my custom HTML code shown below in my pdf

`<p><span style="font-size: 24px;">Pre Interview Notes</span></p><p><br></p><p><strong style="font-size: 14px;"><u>This is a test Pre Interview Notes:</u></strong></p><p><br></p><p><em style="font-size: 14px;">The Guest requires a wheel chair for the show</em></p><p><br></p><p><br></p>`

**Environment**

 - Browser  [e.g. Chrome ]:
 - React-PDF version [1.6.8]:
 - React version [e.g. 16.8.6]:

**Comment by wojtekmaj** [comment]
Wrong repository. You likely mean @diegomura's @react-pdf/react-pdf.
