### ISSUE TITLE
Mocking or resolve loading of pdf in tests

### ISSUE THREAD

**Issue by Adaxelx** [wojtekmaj/react-pdf#564]
I have a problem with testing. I'm using jest with react-testing library. When i trying to create a snapshot of my component in which I want to render pdf i'm facing 'loading...' message. Is there any way to mock whole module or just part to simulate rendering pdf?
I attach my simple snapshot test and output of it.
<img width="354" alt="Zrzut ekranu 2020-05-5 o 01 04 32" src="https://user-images.githubusercontent.com/48855027/81021937-a25f7b00-8e6c-11ea-9e49-ef068e16c77b.png">
<img width="461" alt="Zrzut ekranu 2020-05-5 o 01 06 02" src="https://user-images.githubusercontent.com/48855027/81022036-e2bef900-8e6c-11ea-8605-b734e0d70c18.png">

**Comment by CXZ7720** [comment]
I have exactly same issue with this topic. I use jest and enzyme to test PDF loading component.
I tried to use `async / await` function to load pdf files and added 5000ms timeout interval to wait whole files are loaded from online. but it doesn't helped me.

Is there any updates about this?

**Comment by Adaxelx** [comment]
`jest.mock("react-pdf", () => ({
  pdfjs: { GlobalWorkerOptions: { workerSrc: "abc" } },
  Document: ({ onLoadSuccess = (pdf = { numPages: 4 }) => pdf.numPages }) => {
    return <div>{onLoadSuccess({ numPages: 4 })}</div>;
  },
  Outline: null,
  Page: () => <div>def</div>,
}));`

This is what I done some time ago. Idk if it's proper a way to mock this package but its works for me. It's returning successful answer as if pdf is loaded properly and it's enough for me because mainly I want to test pagination in this component and get snapshot without loading message.

**Comment by ortigozamatias** [comment]
I've tried your approach @Adaxelx but I get an error stating that I cannot update a component while rendering another. It's caused due to `setNumPages` being called inside the `onLoadSuccess` handler.

Did you have the same problem?

**Comment by Adaxelx** [comment]
@ortigozamatias  Yes, I have same problem but I hadn't enough time for resolving it. Can you show your solution?

**Comment by ortigozamatias** [comment]
@Adaxelx sorry for the delay, it's been a tough week. I ended up having two different components. One is in charge of setting up all the logic such as pagination and the other is just a wrapper around `Document`.
Since that wasn't enough to avoid the problem I had to use `enzyme` for shallow rendering the bigger container. As I said before it's far from being the best approach but it was the only thing that came to my mind at the time. 
It's similar to this:

```typescript
const PDFViewer = ({ fileUrl }: IPDFViewerProps) => {
  const [pages, setPages] = useState<number[]>([]);

  const handleDocumentLoadSuccess = useCallback(({ numPages }) => {
    setPages([...Array(numPages)].map((_, index) => index + 1));
  }, []);

  // other callbacks

  return (
    <div className={css(styles.container)}>
      <PDFRenderer fileUrl={fileUrl} onLoadSuccess={handleDocumentLoadSuccess} pageList={pages} />
       {...}
    </div>
  );
};
``` 

When testing this component I mocked `react-pdf` as follows:
```typescript
jest.mock('react-pdf', () => {
  const Page = () => <div>page</div>;

  return {
    pdfjs: {
      GlobalWorkerOptions: {
        workerSrc: 'abc'
      }
    },
    Outline: null,
    Page,
    Document: ({ onLoadSuccess = (pdf = { numPages: 4 }) => pdf.numPages }) => {
      return <div>{onLoadSuccess({ numPages: 4 })}</div>;
    }
  };
});
```

Had to use `shallow` from `enzyme` to avoid having the warning.
The mock for the `Document` wrapper had the module mocked like this:

```typescript
jest.mock('react-pdf', () => {
  const Page = () => <div>page</div>;

  return {
    pdfjs: {
      GlobalWorkerOptions: {
        workerSrc: 'abc'
      }
    },
    Outline: null,
    Page,
    Document: () => {
      return <Page />;
    }
  };
});
```

I guess that with this approach you could test the pagination logic distributed in other components as well.

**Comment by rlarner-quizlet** [comment]
Thanks for the tips, all. This is what worked for me:
```
jest.mock('@react-pdf/renderer', () => ({
  Document: () => <div>Document</div>,
  Image: () => <div>Image</div>,
  Page: () => <div>Page</div>,
  PDFViewer: jest.fn(() => null),
  StyleSheet: { create: () => {} },
  Text: () => <div>Text</div>,
  View: () => <div>View</div>,
}));
```
