### ISSUE TITLE
Render multiple PDFs as a single Document

### ISSUE THREAD

**Issue by nicodelpiano** [wojtekmaj/react-pdf#565]
## Description

For loading performance issues, I have separated PDFs for each page of a document: `page_1.pdf`, `page_2.pdf`, ..., `page_n.pdf`. To display these, I'm currently creating a document for each PDF with a single `<Page>` inside, likewise:

```javascript
pages.map(page =>
  <Document file={...}>
    <Page pageNumber={1} />
  </Document>
)
```

While this works fine, I'd like to load them into a single `<Document />`. Is that possible? Or better, is there a way to improve loading a big PDF?

Thanks!

**Comment by FrederickEngelhardt** [comment]
@nicodelpiano Perhaps having a single pdf would be more efficient? PDF.js does a bunch of this optimization under the hood. 

https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#range perhaps disabling 
```
/** 
  * Disable pre-fetching of PDF file data. When range requests are enabled 
  * PDF.js will automatically keep fetching more data even if it isn't needed 
  * to display the current page. This default behavior can be disabled. 
  * 
  * NOTE: It is also necessary to disable streaming, see above, 
  *       in order for disabling of pre-fetching to work correctly. 
  * @var {boolean} 
  */ 
 PDFJS.disableAutoFetch = (PDFJS.disableAutoFetch === undefined ? 
                           false : PDFJS.disableAutoFetch); 
```

Comes from here: https://github.com/mozilla/pdf.js/blob/ba219965760d8521a7f3794184b653f93c65c5b9/src/display/global.js#L185

For this library you should be able to do the same like this 
```
import { pdfjs } from 'react-pdf
pdfjs.disableAutoFetch = true
```

**Comment by wojtekmaj** [comment]
Absolutely, it's much better to have 1 PDF rather than a bunch of them. 

You can also use packages like [react-window](https://github.com/bvaughn/react-window) in order not to render pages that are not currently visible on the screen, which probably will give you the biggest performance gains.

**Comment by nicodelpiano** [comment]
Thanks for the answers and sorry for my delayed response! In reality, we are rendering a heavy PDF and waiting for it to complete the load isn't an option for us. What we ended up doing is to have a `Document` for every single page to speed it up and loading pages on demand, which worked pretty well.

**Comment by wojtekmaj** [comment]
PDF.js, and consequently React-PDF, supports [HTTP range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests). This is your way to go for heavy PDFs.
