### ISSUE TITLE
Showing only a portion of the pdf

### ISSUE THREAD

**Issue by ismaelrumzan** [wojtekmaj/react-pdf#567]
I want to display only one portion of the PDF file (like crop in an image file). I have the x,y and width and height of the portion

I've tried using width and scale prop of the page

I've testing on the latest chrome and using create-react-app
 - React-PDF version [e.g. 3.0.4]: 4.1.0
 - React version [e.g. 16.3.0]: 16.13.1

**Comment by wojtekmaj** [comment]
Just like a normal image, you may:

* Use `width: auto; height: auto; overflow: hidden;` on page container + negative margins on the svg/canvas inside
* `position: absolute; clip: rect(10px,200px,200px,0px);` appliled to svg/canvas

**Comment by ismaelrumzan** [comment]
Excellent, that works but without using the "overflow:hidden". However, the problem is that I am applying this in app css. I cannot apply a className on the svg/canvas layer in the react code. I need to clip the pdf based on values that I read at runtime from react. Any suggestions?

**Comment by wojtekmaj** [comment]
You can't apply className to svg/canvas, but you can to Page component. So `.myPage svg` / `.myPage canvas` selectors should be good enough.

You can use libraries like styled-components do create dynamic styles in React code, or you can do to yourself by essentially [reimplementing what such libraries are doing](https://stackoverflow.com/questions/707565/how-do-you-add-css-with-javascript).
