### ISSUE TITLE
Issue on displaying Image from link

### ISSUE THREAD

**Issue by mhkasif** [wojtekmaj/react-pdf#568]
I'm facing a problem with the Image.
I'm receiving a link from firebase storage and on placing it in src it shows some CORS error.
I even tried placing headers etc but nothing changed
[FIREBASE IMAGE LINK](https://firebasestorage.googleapis.com/v0/b/slectus-c37f6.appspot.com/o/order_images%2FIOkCLvDCG4d8XzHebeiE1fkghJk1%2FtGwULU?alt=media&token=acea7c32-6011-4267-9e5e-3ac5e817d3be)

![Screenshot 2020-05-11 at 1 48 21 AM](https://user-images.githubusercontent.com/30750191/81510355-78a1ca80-932a-11ea-9a3d-067adadabb68.png)
![Screenshot 2020-05-11 at 1 48 45 AM](https://user-images.githubusercontent.com/30750191/81510356-7a6b8e00-932a-11ea-977a-14751f53f2ee.png)

**Comment by wojtekmaj** [comment]
Looks like a wrong repository to me 🤔 Perhaps you meant @diegomura's @react-pdf/react-pdf?
