### ISSUE TITLE
Provide Style props to Document component

### ISSUE THREAD

**Issue by arunkumar509** [wojtekmaj/react-pdf#571]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Describe what are you trying to achieve.

Trying to load PDF in a modal. Once I load the PDF in the modal, I'm getting two scrolls one inside the modal and another for the modal. I was able to bring two scroll to one by setting max-height based on the user's browser height. But on doing so I'm seeing a the PDF scroll is getting hidden, when i try to scroll after certain height. This is because I have given a maximum height of 700px for the Document Component. I want this max height property to be set dynamically to the component.

**Describe solutions you've tried**

Solution I tried is to set Max height to Document Component. But it is not reflecting on the div with class 'react-pdf__Document'.

Describe solutions you've already tried, if any. Make sure to include code samples if you're stuck on implementation.

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

Not able to bring the scroll in screenshot :(
<img width="1023" alt="Screen Shot 2020-05-12 at 5 36 46 PM" src="https://user-images.githubusercontent.com/63615210/81748173-5ec1ce00-9477-11ea-99c2-afefce3509f8.png">

<img width="666" alt="Screen Shot 2020-05-12 at 5 37 32 PM" src="https://user-images.githubusercontent.com/63615210/81748207-6da88080-9477-11ea-9870-d0c59f4e37c9.png">

<img width="353" alt="Screen Shot 2020-05-12 at 5 37 39 PM" src="https://user-images.githubusercontent.com/63615210/81748217-71d49e00-9477-11ea-9cb8-6ecc8f6aef5c.png">

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version: ^4.1.0
 - React version [e.g. 16.3.0]: ^16.12.0
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by arunkumar509** [comment]
Got a workaround. Thank you

**Comment by squalvj** [comment]
@arunkumar509 Hello, im experiencing same issue, i got duplicate scroll on modal component, could you share your workaround here ?

**Comment by arunkumar509** [comment]
@squalvj Sorry for the delayed response. Not sure why I wasn't getting any notification :(. 

Workaround: I tried using window.innerHeight. Based on this value I was able to set the maximum height to the modal which holds PDF viewer.
