### ISSUE TITLE
Cannot use 'data' for file AT ALL

### ISSUE THREAD

**Issue by anshgupta1234** [wojtekmaj/react-pdf#573]
I have a UInt8Array of a .pdf file, which I obtain from `react-dropzone`

```
processPdf = files => {
    const file = files[0]
    if(file.name.includes(".pdf")) {
      const reader = new FileReader();
      reader.onload = (event) => {
        const uint = new Uint8Array(event.target.result)
        this.setState({ pdf: uint })
        console.log(this.state.pdf);
      };
      reader.readAsArrayBuffer(file);  
      this.setState({ file, selected: file.name })
    }
  }
```

Now, I have a UInt8Array of this file. However, when I upload this array into my Document with
`<Document file={{ data: this.state.pdf }}/>`,

Doing this gives me an extremely weird error saying:
`Error: Invalid parameter object: need either .data, .range or .url`

but clearly, I'm passing in a data! Even if the Uint8Array is wrong, it should NOT be giving me that error, and I can't find a solution.

Appreciate any help!
Thank you.

**Comment by tue-tran** [comment]
> I have a UInt8Array of a .pdf file, which I obtain from `react-dropzone`
> 
> ```
> processPdf = files => {
>     const file = files[0]
>     if(file.name.includes(".pdf")) {
>       const reader = new FileReader();
>       reader.onload = (event) => {
>         const uint = new Uint8Array(event.target.result)
>         this.setState({ pdf: uint })
>         console.log(this.state.pdf);
>       };
>       reader.readAsArrayBuffer(file);  
>       this.setState({ file, selected: file.name })
>     }
>   }
> ```
> 
> Now, I have a UInt8Array of this file. However, when I upload this array into my Document with
> `<Document file={{ data: this.state.pdf }}/>`,
> 
> Doing this gives me an extremely weird error saying:
> `Error: Invalid parameter object: need either .data, .range or .url`
> 
> but clearly, I'm passing in a data! Even if the Uint8Array is wrong, it should NOT be giving me that error, and I can't find a solution.
> 
> Appreciate any help!
> Thank you.

Having the same issue. Would be nice to get a reply.

**Comment by wojtekmaj** [comment]
This must mean that `this.state.pdf` is actually falsy. Looking at your code (`this.setState({ file, selected: file.name })`), you should be rather using `this.state.file`.
