### ISSUE TITLE
Error in componentWillUnmount

### ISSUE THREAD

**Issue by andreme** [wojtekmaj/react-pdf#574]
**Description**

I got into the situation where ```<Document />``` gets unmounted before loadingTask is set.
Should be a quick fix to only destroy loadingTask when it's set.

https://github.com/wojtekmaj/react-pdf/blob/master/src/Document.jsx#L78

**Comment by wojtekmaj** [comment]
Fixed in https://github.com/wojtekmaj/react-pdf/commit/badeb90d86e2df92c5429e8e108348af4df45afb.
