### ISSUE TITLE
PDF scale 3.5 taking longer to load in 4K responsive screen

### ISSUE THREAD

**Issue by NethraRaghu** [wojtekmaj/react-pdf#578]
I would like to zoom (scale 3.5) to a particular coordinate on the click of a button. It works fine on the laptop but it takes really long time in bigger screens like 4k responsive (2560 x 950). It's taking up a lot of system memory too.

    onButtonClick = () => {
        this.setState({ scale: 3.5, pageNumber: 3, pdfLoader: true },
            () => {
                setTimeout(function () {
                    var canvasHolder = document.querySelector('.document-holder');
                    canvasHolder.style.overflow = 'auto';
                    canvasHolder.scroll({
                        top: 600,
                        left: 500,
                        behavior: 'smooth'
                    })
                }, 800)
            }
        )

    }

    renderSuccess = (page) => {
        if (page.pageIndex === this.state.pageNumber - 1) {
            this.setState({
                pdfLoader: false
            })
        }
    }
    render() {
        var { pageNumber, scale, url } = this.state;
        const override = css` display: block; margin: 0 auto; top:250px;z-index:100; height:0 !important`;
        return (
            <div>
                <button onClick={this.onButtonClick}>test</button>
                <FadeLoader css={override} height={15} width={5} radius={2} margin={2} color={"#4183C5"} loading={this.state.pdfLoader} />
                <div id="doc-holder" className="document-holder" >

                    <Document file={url}>
                        <Page key={pageNumber} pageNumber={pageNumber} renderAnnotationLayer={false}
                            renderTextLayer={false}
                            noData='No file found'
                            className="canvas-pdf-page"
                            scale={scale}
                            width={window.innerWidth * 0.9}
                            onRenderSuccess={(page) => this.renderSuccess(page)}
                        />
                    </Document>

                </div>
            </div>
        )
    }

**Environment**
 - React-PDF version: 4.1.0
 - React version: 16.12.0

**Comment by wojtekmaj** [comment]
Well, 4K screens has 4x the pixels, so 4x the amount of work to rendering.

**Comment by NethraRaghu** [comment]
But it doesn't take long in [https://mozilla.github.io/pdf.js/web/viewer.html](url) (pdf.js) when I view in 4K screen and change pages

**Comment by donysukardi** [comment]
Having the same issue when changing the scale, it takes very long to rerender the document with new scale and it's blocking my event handlers.
