### ISSUE TITLE
Prompt for password for password protected PDF keeps popping up

### ISSUE THREAD

**Issue by zeusservando** [wojtekmaj/react-pdf#581]
Hi @wojtekmaj  good day i have a pdf file with password protected, but when the prompt box shows up i cant close it.

**Comment by helios1138** [comment]
you can define a custom password behavior using `onPassword` handler

**Comment by wojtekmaj** [comment]
Yeah, the default `onPassword` is a little limited. But this is because there are so many different use cases. React-PDF might handle PDFs that are meant to be "closeable" or not.

If you want to cancel loading the file if the user presses "Cancel" on password prompt and do something with it, do something like this:

```js
function onPassword(callback, reason) {
  function callbackProxy(password) {
    // Cancel button handler
    if (password === null) {
      // Reset your `document` in `state`, un-mount your `<Document />`, show custom message, whatever
    }

    callback(password);
  }

  switch (reason) {
    case PasswordResponses.NEED_PASSWORD: {
      const password = prompt('Enter the password to open this PDF file.');
      callbackProxy(password);
      break;
    }
    case PasswordResponses.INCORRECT_PASSWORD: {
      const password = prompt('Invalid password. Please try again.');
      callbackProxy(password);
      break;
    }
    default:
  }
}
```

**Comment by SwapnaleePatil** [comment]
Can we have a sample for password protected PDF example?

**Comment by SwapnaleePatil** [comment]
@wojtekmaj

**Comment by wojtekmaj** [comment]
Looks like you confused the repositories. This is React-PDF which is used to display PDFs.

**Comment by sebastam97** [comment]
Hello, I have a problem when I try to close the alert, it is not allowed, I could give a clear example of how to close it when they give it to cancel

**Comment by wojtekmaj** [comment]
@sebastam97 It is allowed, but you need to handle that like described in https://github.com/wojtekmaj/react-pdf/issues/581#issuecomment-654741296.

**Comment by wojtekmaj** [comment]
@hilmanski It's open source :P 

https://github.com/wojtekmaj/react-pdf/blob/c2012f86862b7253db970cc3363cf295b94ab4e1/src/Document.jsx#L347-L363

**Comment by hilmanski** [comment]
thanks for pointing out the file @wojtekmaj 
have  a good day!

**Comment by NikhilAgarwal05** [comment]
some the above solution code error, at that point this code is working:-

onHandleCallback(callback, password) {
    // Cancel button handler
    if (password === null) {
        return this.props.onCancel();
    }

    callback(password);
}

onPassword(callback, reason) {
    const { PasswordResponses } = pdfjs;
    switch (reason) {
        case PasswordResponses.NEED_PASSWORD: {
            const password = prompt('Enter the password to open this PDF file.');
            this.onHandleCallback(callback, password);
            break;
        }
        case PasswordResponses.INCORRECT_PASSWORD: {
            const password = prompt('Invalid password. Please try again.');
            this.onHandleCallback(callback, password);
            break;
        }
        default:
            break;
    }
}


visit https://github.com/wojtekmaj/react-pdf/issues/581#issuecomment-654741296 for more reference.
Thanks @wojtekmaj

**Comment by jmedelliin** [comment]
> @hilmanski Sure, it's open source :P
> 
> https://github.com/wojtekmaj/react-pdf/blob/c2012f86862b7253db970cc3363cf295b94ab4e1/src/Document.jsx#L347-L363

i try this but open two windows 

this is my code :

  function onPassword(callback, reason) {
    const PasswordResponses = {
      NEED_PASSWORD: 1,
      INCORRECT_PASSWORD: 2,
    };
    function callbackProxy(password) {
      // Cancel button handler
      if (password === null) {
        // Reset your `document` in `state`, un-mount your `<Document />`, show custom message, whatever
      }

      callback(password);
    }

    switch (reason) {
      case PasswordResponses.NEED_PASSWORD: {
        const password = prompt("Enter the password to open this PDF file.");
        callbackProxy(password);
        break;
      }
      case PasswordResponses.INCORRECT_PASSWORD: {
        const password = prompt("Invalid password. Please try again.");
        callbackProxy(password);
        break;
      }
      default:
    }
  }

return (
    <div ref={componentRef}>
      <Document
        file={data.url}
        error={error()}
        noData={error()}
        loading={loading()}
        onLoadSuccess={onDocumentLoadSuccess}
        onPassword={onPassword}
        onSourceError={onSourcError}
        onSourceSuccess={onSourceSuccess}
      >
        {arr.map((pages) => (
          <div
            style={{
              paddingLeft: 5,
              paddingRight: 5,
              paddingTop: 5,
              paddingBot: 5,
            }}
            key={pages}
          >
            <Page
              key={pages}
              pageNumber={pages}
              customTextRenderer={textRenderer}
              loading={loading()}
              scale={scale.id}
              rotate={rotate}
              inputRef={
                listaRefer.current === pages
                  ? (ref) => ref && ref.scrollIntoView()
                  : null
              }
            />
          </div>
        ))}
      </Document>
    </div>
  );


open the first 
![image](https://user-images.githubusercontent.com/106602828/234996987-4f2de8a7-5c35-4f66-97a6-5db16d815df7.png)

I enter the password and opened the second 

![image](https://user-images.githubusercontent.com/106602828/234997334-197e15a4-bab9-4bbf-9999-2f2848d1b5d8.png)

**Comment by sanjiv-sahani** [comment]
> Hello, I have a problem when I try to close the alert, it is not allowed, I could give a clear example of how to close it when they give it to cancel

this is the How its work 
                            <Document
					loading={'Loading...'}
					file={fileUrl}
					onLoadError={onLoadError}
					onPassword={(callback, reason, PasswordResponses) => onPassword(callback, reason, 
                                          PasswordResponses)}
				>
then the Simple Call back Function 
	function onPassword(callback, reason,PasswordResponses) {
		function callbackProxy(password) {
			// Cancel button handler
			if (password === null) {
				// Reset your `document` in `state`, un-mount your `<Document />`, show custom message, whatever
			}
			callback(password);
		}

		switch (reason) {
			case PasswordResponses?.NEED_PASSWORD: {
				const password = prompt('Enter the password to open this PDF file.');
				// callbackProxy(password);
				break;
			}
			case PasswordResponses?.INCORRECT_PASSWORD: {
				const password = prompt('Invalid password. Please try again.');
				callbackProxy(password);
				break;
			}
			default:
		}
	} 
this is working for me while i am uploading a Password Protected File it gets not get poping Out

**Comment by pstevovski** [comment]
> @hilmanski Sure, it's open source :P
> 
> https://github.com/wojtekmaj/react-pdf/blob/c2012f86862b7253db970cc3363cf295b94ab4e1/src/Document.jsx#L347-L363

@wojtekmaj Where does the `PasswordResponses` variable comes from? I tried accessing it, tried importing it from 'react-pdf' but it does not exist.

**Comment by wojtekmaj** [comment]
Well that's really stupid - would you mind raising a PR for that?

**Comment by pstevovski** [comment]
@wojtekmaj Sure thing, will open a PR now. Seems like the `PasswordResponses.ts` file exists and has a default export, but in the exported modules from `index.ts` is not present. Will send a PR now.

**Comment by atologistChiragRathod** [comment]
`import { PasswordResponses } from 'pdfjs-dist';
`
From `'pdfjs-dist'` you can import  `PasswordResponses `

**Comment by wojtekmaj** [comment]
PasswordResponses is exported from react-pdf since #1615 ([v7.4.1](https://github.com/wojtekmaj/react-pdf/releases/tag/v7.4.1) and up).
