### ISSUE TITLE
SecurityError: The operation is insecure. on Cordova

### ISSUE THREAD

**Issue by Piero87** [wojtekmaj/react-pdf#584]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

I have add react pdf in my web app, and in the browser works with no problem at all, when I build this app on Cordova, Android works well, iOS instead with WKWebView give me an error, the error is this:
![Schermata 2020-06-03 alle 15 35 53](https://user-images.githubusercontent.com/768952/83643337-2f9f0800-a5b0-11ea-8e30-d4de2788fe04.png)

And the code give me the error is this:
![Schermata 2020-06-03 alle 15 36 01](https://user-images.githubusercontent.com/768952/83643358-375eac80-a5b0-11ea-8420-385d9efeabed.png)

I use this import in the code:

`import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';`

Anyone knows how can I avoid this problem? 

**Environment**
 - React-PDF version 5.0.0-beta.3:
 - React version 16.8.6
 - Webpack 4.29.6

**Comment by Piero87** [comment]
Using this type of import:

import { Document, Page } from 'react-pdf';

On Cordova there is no error, and in console I see Fake worker loaded

**Comment by haustraliaer** [comment]
Fairly certain workers are not supported in WkWebView - came here looking for the same error and I just realised I have workers in my code.

**Comment by haustraliaer** [comment]
Update for anyone who finds there way here as I did...

You _can_ get workers working (lol) in WkWebView - but they have to be inlined, the security issue is due to the way `new Worker(...)` loads in the script from the iOS filesystem.
