### ISSUE TITLE
Problem with annotation import

### ISSUE THREAD

**Issue by kss943** [wojtekmaj/react-pdf#585]
Hello.
I have a problem with annotations support.
When I make import of css like :
`import 'react-pdf/dist/esm/Page/AnnotationLayer.css';`.
an error appears :
`Can't resolve 'react-pdf/dist/esm/entry.webpack' in  'project/src'`.
Also it appears while importing react-pdf as ` 'react-pdf/dist/esm/entry.webpack'`.
How can this be fixed?

 - React-PDF version 4.1.0
 - React version 16.12.0
 - Webpack version  4.6.0

**Comment by tewe11** [comment]
I just had the same problem. In the latest version you can just use
```
import 'react-pdf/dist/Page/AnnotationLayer.css';
```

**Comment by wojtekmaj** [comment]
You were looking at latest README, instead of README for the specific React-PDF version you're using.
