### ISSUE TITLE
Source Code for Demo Site

### ISSUE THREAD

**Issue by kennydifiore** [wojtekmaj/react-pdf#591]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Could you please share the source code for your demo site: https://projects.wojtekmaj.pl/react-pdf as it pertains to the react-pdf portion?  I'm trying to replicate your page controls, but each time I click a new page that hasn't been loaded yet, the `<Document>` element flashes and if I have a large view for the `<Document>` element, it also forces the page to scroll up if I'm already scrolled down.  Your demo site doesn't seem to jitter or flash when changing pages and I would like to replicate that behavior.

**Comment by wojtekmaj** [comment]
It's taken straight from the Recipes we have in Wiki. That plus custom CSS.

**Comment by kennydifiore** [comment]
@wojtekmaj What webpack loader is being used for the PDF file?  What is the custom CSS?  How do I stop the Document element from jumping if using a PDF from a URL?

**Comment by wojtekmaj** [comment]
file-loader is used to load the PDF.

Custom CSS is not a part of this open source project.

Document is not jumping because the loader is exactly the size of the PDF being loaded.
