### ISSUE TITLE
Cannot "import { Document } from 'react-pdf/dist/esm/entry.parcel';" because react-pdf/dist/esm does not exist

### ISSUE THREAD

**Issue by pwhipp** [wojtekmaj/react-pdf#592]
**Before you start - checklist**

 - [ x] I have read documentation in README
 - [x ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x ] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Get any pdf to display

**Describe solutions you've tried**

Followed readme installation and experimented

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser 83.0.4103.97
 - React-PDF version [4.1.0]:
 - React version [16.12.0]:
 - Webpack version (if applicable) [4.41.5]:

It either hangs or I get:
```
PDFHelp http://localhost:8000/static/SOS_User_Guide.pdf
main.js?ts=1592290201:81 Warning: Setting up fake worker.
vendors~pdfjsWorker.js:3 Uncaught SyntaxError: Unexpected token '<'
main.js?ts=1592290201:23 Error: Setting up fake worker failed: "Loading chunk 0 failed.
(missing: http://localhost:8000/vendors~pdfjsWorker.js)".
    at main.js?ts=1592290201:81
```
Clicking on the file reference in the console.log statement instantly opens the pdf verifying that the url for it is correct.

I'm guessing this requires a worker after all so I looked to the readme which says I can use:
import {Document} from 'react-pdf/dist/esm/entry.webpack';

There is no esm (or udm) folder  under react-pdf/dist. Is there something else I need to do to import it?

**Comment by wojtekmaj** [comment]
You're looking at README for version 5.x (current work in progress). Check README for links to documentation regarding your version of React-PDF.
