### ISSUE TITLE
Productoin error

### ISSUE THREAD

**Issue by EkaterinaAksenchik** [wojtekmaj/react-pdf#594]
**Before you start - checklist**

 - [+] I have read documentation in README
 - [+] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [+] I have checked if this question is not already asked

In our project we are using react-pdf (v4.1.0), which depends on `pdf.js`. On our production we got following error:

`EVENT ACTION: 02/05/2020 20:01:45 - TypeError: Undefined Is Not an Object (Evaluating 'n.renderTasks.length')`

It looks like the error was in `pdf.js`, because I found few lines with this code in this file https://github.com/mozilla/pdfjs-dist/blob/master/lib/display/api.js. 
I don't have steps to reproduce it, becuase it was on production, but maybe you have faced the same problem? Because `pdf-js` is decline my bug report.

**Comment by wojtekmaj** [comment]
No, sorry, I didn't face this issue. We would likely need to get a PDF to reproduce it.

**Comment by wojtekmaj** [comment]
Closing for now before we have any steps to reproduce that we could evaluate this on.
