### ISSUE TITLE
Issue loading Image src

### ISSUE THREAD

**Issue by grantburnham** [wojtekmaj/react-pdf#595]
I have been unable to correctly load images via the <Image src /> component in React PDF.

I had issue locally in my code but have also been able to replicate the same issue on the image test page
https://react-pdf.org/repl?example=images

This works and renders (test image)
`https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg`
<Image src="https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg" />

This will not render (test image)
`https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_default_1x.png`
<Image src="https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_default_1x.png" />

Is there something that the <Image> component needs to support this?

The images I wish to load for my project will be PNG but these look to be supported.

Any help would be greatly appreciated

**Comment by wojtekmaj** [comment]
Wrong repo :)

**Comment by grantburnham** [comment]
Hi, What do you mean by 'Wrong Repo'?
