### ISSUE TITLE
How to investigate the reason of some pdf blocks being not rendered with react-pdf

### ISSUE THREAD

**Issue by quarryman** [wojtekmaj/react-pdf#596]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I am rendering particular private pdf file and I have particular block missing that are visible when viewing with desktop pdf reader.
These might be blocks of text or background objects (text is visible but background square behind it is not)

What are the tools I can use to try debug pdf itself to see how are particular blocks implemented/inserted in pdf?

**Describe solutions you've tried**

Updated to the latest react-pdf version with no success. Guessing its pdf.js issue, but my question remains so maybe someone can shed a light on how sort of to debug pdf file.

**Additional information**
file is considered private and can not be attached.
No investigation on particular example wanted, just asking for proper tools to investigate on my own.

**Environment**

 - Browser (if applicable) Chrome  83.0.4103.97 
 - React-PDF version: latest
 - React version 16.x:

**Comment by wojtekmaj** [comment]
Does the problem exist if you open the file in Firefox? If yes, I won't be able to help you, you would need to contact Mozilla via [their repo](https://github.com/mozilla/pdf.js).

**Comment by quarryman** [comment]
@wojtekmaj thanx for your attention.
I totally understand you should not  address specific pdf issues.
Was just wandering if you use specific tools for pdf debugging when resolving other issues that you can advice.
Thanx

**Comment by wojtekmaj** [comment]
No, vast majority of rendering is done by pdf.js and I trust them on that part :) React-PDF is merely a wrapper around this library. We do have some of our own logic, like for rendering text layer, but nothing more than that.
