### ISSUE TITLE
MIME type ('text/html') is not executable

### ISSUE THREAD

**Issue by gregorispielmann** [wojtekmaj/react-pdf#597]
**What are you trying to achieve? Please describe.**

I'd like to display a PDF by a URL comming from API (Node.js + Express).

**Describe solutions you've tried**

I've tried a lots of options. The last one is a sample pdf locally and doesn't work.

**Additional information**

The problems is that the pdf doesn't display, only the message "Failed to load PDF file" and the console messages below:

```
Refused to execute script from 'http://localhost:3000/pedido/pdf.worker.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
pdf.js:721 
Warning: Setting up fake worker.
4502338897:1
Refused to execute script from 'http://localhost:3000/pedido/pdf.worker.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
index.js:1437
Error: Setting up fake worker failed: "Cannot load script at: http://localhost:3000/pedido/pdf.worker.js". at pdf.js:11664
```

**Environment**

 - Chrome 83
 - React-PDF version 4.1.0
 - React version 16.8.4

**Component Code**

```
import React from 'react';
import { Modal, ModalBody, ModalHeader } from 'reactstrap';
import './Modal.scss';
import { ClockLoader } from 'react-spinners';
import { Document, Page } from 'react-pdf';
import samplePDF from './sample.pdf';

export default function ModalPDF({ isOpen, toggle, url, title }) {
    const [pdf, setPdf] = React.useState(null);

    const [numPages, setNumPages] = React.useState(null);
    const [pageNumber, setPageNumber] = React.useState(1);

    const onDocumentLoadSuccess = ({ numPages }) => {
        setNumPages(numPages);
    };

    return (
        <Modal isOpen={isOpen} toggle={toggle} className='modal-dialog modal-dialog-centered fullscreen-modal'>
            <ModalHeader toggle={toggle}>
                <b>{title}</b>
            </ModalHeader>
            <ModalBody style={{ height: '100%', padding: '5px' }}>
                <Document file='http://africau.edu/images/default/sample.pdf' onLoadSuccess={onDocumentLoadSuccess}>
                    <Page pageNumber={pageNumber} width={600} />
                </Document>
            </ModalBody>
        </Modal>
    );
}
```

**Screenshot**
![localhost_3000_pedido_4502338897(Galaxy Tab A8 Menor)](https://user-images.githubusercontent.com/41961920/85067779-a1b64600-b187-11ea-92d9-79246a822532.png)

**Comment by wojtekmaj** [comment]
Same cause as #52 & #443 but different error message. Your worker JS file isn't actually _the_ file it's supposed to be. Likely your index.html or 404 page.

**Comment by emorling** [comment]
@gregorispielmann were you able to solve this?

**Comment by tarochipz** [comment]
@wojtekmaj experiencing the same issue (after updating `react-pdf` from version 4.x to 5.x, and updating the pdfjs script from v2.1.266 to v2.9.359) and would appreciate if you can help with the questions below:

1. Why would Index.html or 404 page be loaded instead of the actual worker file? Also want to note that for my specific issue index.html is loaded on first render. If I unmount and remount the component _without reloading the page_, the correct worker file is loaded. If I refresh the page, index.html is loaded.
2. We're fetching the JS worker file on the backend due to same origin policy, and setting the pdfjs workerPort to our worker in the onmessage (see examples below). This is not covered in the README, do you have any suggestions on how to fix the issue ?

when PDF viewer component mounts:
```
  this.pdfjsWorker = new Worker('/api/public/pdfjs-worker');
      this.pdfjsWorker.onmessage = () => {
        if (this.state.pdfjsWorkerIsSet) {
          return;
        }
        (pdfjs.GlobalWorkerOptions as any).workerPort = this.pdfjsWorker;
        this.setState({
          pdfjsWorkerIsSet: true,
        });
      };
```

Route to fetch script:
```
app.get('/pdfjs-worker',
  ...
  endpointWrapper(async (req, res) => {
    res.setHeader('Content-type', 'text/javascript');
    const workerScript = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.9.359/pdf.worker.min.js'
    const scriptStream = await fromCallback(cb => fileStore.downloadUrl(workerScript, cb));
    scriptStream.pipe(res);
  }, { piped: true }),
);
```

**Comment by wojtekmaj** [comment]
@tarochipz Why don't you just use static worker file copied over like any other static asset? This looks like working around an issue that shouldn't be there in the first place.

index.html or 404 page will pop up if you get the URL to the file wrong. That's nothing related to React-PDF, it's just how the web works. Well at least the 404 part, index.html served instead sounds like Webpack/SPA server configuration so you could support users entering your app from different paths that don't actually exist in file structure like /login.

**Comment by EldinZaimovic** [comment]
I am getting same error after updating to version 7
