### ISSUE TITLE
TextLayerItem causing performance issues in Chrome

### ISSUE THREAD

**Issue by iamshubh** [wojtekmaj/react-pdf#599]
**Before you start - checklist**

- [x] I followed instructions in documentation written for my React-PDF version
- [x]  I have checked if this bug is not already reported
- [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering in chrome, PDF renders better in Mozilla Firefox

**Description**

PDF Scroll is quite slow in latest chrome version
**83.0.4103.106 (Official Build) (64-bit)**
--

**Expected behavior**

What you expected to happen?

**Additional information**
Scrolling in other Firefox browser works quite well, but in chrome if user scrolls to see other pages, renderer becomes unresponsive. It takes a lot of time to render it.

I have attached the screenshot for the same, please have a look.
![Screenshot 2020-06-21 at 1 53 19 AM](https://user-images.githubusercontent.com/4703670/85211188-560cc380-b364-11ea-87c4-15b9c4dce847.png)

I inspected this issue performance tools in chrome-devtools. I found out that 
[TestLayerItem.jsx](https://github.com/wojtekmaj/react-pdf/blob/v3.x/src/Page/TextLayerItem.jsx) takes lots of time to recalculate its width and height.

![Screenshot 2020-06-21 at 1 54 57 AM](https://user-images.githubusercontent.com/4703670/85211240-ca476700-b364-11ea-9816-99294a7ea092.png)

**Environment**

 - Browser: Google chrome: 83.0.4103.106 (Official Build) (64-bit)
 - React-PDF version: "react-pdf": "^3.0.5",
 - React version: 16.4.0
 - Webpack version: 3.8.1

**Comment by iamshubh** [comment]
> **Before you start - checklist**
> 
>     * [x]  I followed instructions in documentation written for my React-PDF version
> 
>     * [x]   I have checked if this bug is not already reported
> 
>     * [x]  I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
> 
>     * [x]  If I have a problem with PDF rendering in chrome, PDF renders better in Mozilla Firefox
> 
> 
> **Description**
> ## PDF Scroll is quite slow in latest chrome version
> **83.0.4103.106 (Official Build) (64-bit)**
> 
> **Expected behavior**
> 
> What you expected to happen?
> 
> **Additional information**
> Scrolling in other Firefox browser works quite well, but in chrome if user scrolls to see other pages, renderer becomes unresponsive. It takes a lot of time to render it.
> 
> I have attached the screenshot for the same, please have a look.
> ![Screenshot 2020-06-21 at 1 53 19 AM](https://user-images.githubusercontent.com/4703670/85211188-560cc380-b364-11ea-87c4-15b9c4dce847.png)
> 
> I inspected this issue performance tools in chrome-devtools. I found out that
> [TestLayerItem.jsx](https://github.com/wojtekmaj/react-pdf/blob/v3.x/src/Page/TextLayerItem.jsx) takes lots of time to recalculate its width and height.
> 
> ![Screenshot 2020-06-21 at 1 54 57 AM](https://user-images.githubusercontent.com/4703670/85211240-ca476700-b364-11ea-9816-99294a7ea092.png)
> 
> **Environment**
> 
>     * Browser: Google chrome: 83.0.4103.106 (Official Build) (64-bit)
> 
>     * React-PDF version: "react-pdf": "^3.0.5",
> 
>     * React version: 16.4.0
> 
>     * Webpack version: 3.8.1

@wojtekmaj

**Comment by wojtekmaj** [comment]
You're using a really old React-PDF version. Newer versions should perform much better, especially on modern browsers.

**Comment by iamshubh** [comment]
@wojtekmaj I tried updating the react-pdf version and used steps as described in documentation, but still it is slow in latest chrome (**Google chrome: 83.0.4103.106 (Official Build) (64-bit)**)

I tried the same pdf scrolling by following steps on https://mozilla.github.io/pdf.js/examples/
It was relatively much better.

**Comment by sovanyio** [comment]
I'm seeing this on two separate 2-page image based PDFs.

I am tempted to drop down and implement pdf.js directly for UX.
