### ISSUE TITLE
issue installing

### ISSUE THREAD

**Issue by Solitaryo** [wojtekmaj/react-pdf#6]
If i run `npm install --save react-pdf` i got the @nnarhinen version, not yours, any idea why?

**Comment by wojtekmaj** [comment]
@nnarhinen is the owner of npm package of that name which, in his case, is the same as the name of GitHub repository, but that's not the case for this repo. As long as this name is taken by him in npm, as a workaround, you can add this repo to your package.json by adding this line:

`"react-pdf": "git://github.com/wojtekmaj/react-pdf.git"`

And you should be good to go!

**Comment by jarekwg** [comment]
https://github.com/nnarhinen/react-pdf/commit/c0d1df5647441ac0ef67f1aa5f6cff9ddbee7a67

Would be nice if this fork could become the official version, or at least get merged back in again.

**Comment by wojtekmaj** [comment]
@jarekwg Since I got no reply from him on several email, I've emailed npm team. We'll see what we can do :)

**Comment by nnarhinen** [comment]
Oh sorry. I did not notice any emails! I have now given you push rights to my repository. What's your NPM username, will add publish rights there too!

**Comment by wojtekmaj** [comment]
@jarekwg @Solitaryo You should be able to enjoy the latest & greatest without any hacks now!
