### ISSUE TITLE
"Failed to load PDF" on the iPad

### ISSUE THREAD

**Issue by ujjwalbanka** [wojtekmaj/react-pdf#60]
Hello,
Thank you for this very awesome package :)

I'm using it in my React app but I'm getting some error. It's working for every browser but not working only in **Ipad** (both chrome and safari browser)
**Failed to load PDF**

I am using your sample.jsx file. No modification in that file from your its an exact copy.
Loading base64 PDF string in {file} props.

react-pdf version : 2.1.1
react version : 15.6.1

Any idea about this issue? Am I doing something wrong?

**Comment by wojtekmaj** [comment]
Hey,
thanks for the kind words! Could you provide me specific error you're getting? You may want to use on....Error callbacks to get more detailed info and display error message in a dialog.
Thanks!

**Comment by ujjwalbanka** [comment]
Page props
onLoadError : (error) => alert('Error while loading page! ' + error.message) 
Responce : **Error while loading page: undefined**

**Comment by wojtekmaj** [comment]
Thanks for the info. One more thing: Does the demo page (link in README) works for you on the iPad?
If not, I'll have a look asap and get back to you.

**Comment by wojtekmaj** [comment]
@ujjwalbanka I'm closing this in effort to keep Issues page clean of issues that are no longer discussed. I will be happy to reopen in case you still have this issue and you're willing to work together to reproduce it!

**Comment by kentferolino** [comment]
Do we have any idea what version would work for an iPad 12.5.5?

**Comment by kentferolino** [comment]
This issue fixed for me by updated react-pdf from 5.3.0 to 5.7.2
