### ISSUE TITLE
Failed to load pdf file

### ISSUE THREAD

**Issue by shamimfahad** [wojtekmaj/react-pdf#600]
I'm having trouble displaying pdf file in the react app. I strictly followed the rules provided, basically I copied the example code from the repo. As soon as I load the page, it says failed to load pdf file but the browser starts downloading the pdf. And this is the error I get in the console

> UnexpectedResponseException
message: "Unexpected server response (204) while retrieving PDF "http://localhost:3000/CV_Shamim.pdf"."
name: "UnexpectedResponseException"
status: 204

Code 

```js
import React, { useState } from 'react';
import { Document, Page, pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

const Resume = () => {
  const src = './CV_Shamim.pdf';
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  const onDocumentLoadSuccess = ({ numPages }) => {
    setNumPages(numPages);
  };

  return (
    <div>
      <Document file={src} onLoadSuccess={onDocumentLoadSuccess}>
        <Page pageNumber={pageNumber} />
      </Document>
      <p>
        Page {pageNumber} of {numPages}
      </p>
    </div>
  );
};

export default Resume;
```

**Comment by wojtekmaj** [comment]
204 is HTTP code for No Content. This means your development server failed to serve you the file properly.

If that's Webpack, Webpack needs to know about the file to include it in your bundle - either as a separate file, or as the part of the bundle.

You can use:
* CopyWebpackPlugin to copy the PDF file to your final build, and carefully set `src`
* `file-loader` for PDF files in Webpack config, `import` your PDF file into the module, and use the imported variable as `src`
* same ⬆️ , but using `url-loader`

I'm actually using the latter in my test suite:

https://github.com/wojtekmaj/react-pdf/blob/534383716a4150c8417e7a99386db03b40fee3f9/test/webpack.config.js#L62-L65

https://github.com/wojtekmaj/react-pdf/blob/534383716a4150c8417e7a99386db03b40fee3f9/test/LoadingOptions.jsx#L4
