### ISSUE TITLE
Text selection Flickering

### ISSUE THREAD

**Issue by DLevai94** [wojtekmaj/react-pdf#602]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

While selecting text, every time my cursor is between 2 lines, selection flickers to the top of the page. 

Screen recording: https://www.loom.com/share/7867568f4de347f295bfb3a0b7202e44

**Additional information**

It works with Firefox

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Chrome 83 & Safari 14
 - React-PDF version [e.g. 3.0.4]: 4.1.0
 - React version [e.g. 16.3.0]: 16.13.1
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.43.0

**Comment by lucasbordini** [comment]
Same here, any solution ?

**Comment by wojtekmaj** [comment]
See https://github.com/wojtekmaj/react-pdf/issues/101#issuecomment-345846047
