### ISSUE TITLE
Font.register not working

### ISSUE THREAD

**Issue by AnkitBagaria24** [wojtekmaj/react-pdf#605]
I need to use Roboto font in my pdf. When I register the font and use it in my stylesheet, the pdf download link becomes inactive.

If I remove fontFamily:'roboto' from page style element I am able to download the pdf but with its default font. 

I have downloaded ttf files of both Roboto Regular and Roboto Thin in a seperate folder 'sylesheet' as evident from src path. Someone please help me out. 

```
Font.register({
    family: 'Roboto', fonts: [
        { src: `./sylesheet/Roboto-Regular.ttf` },
        { src: `./sylesheet/Roboto-Thin.ttf`, fontWeight: 'thin' }
    ]
});

const styles = StyleSheet.create({
    page: {
        display: 'flex',
        alignItems: 'center',
        border: '2px solid grey',
        fontSize: '12px',
       fontFamily: 'Roboto'
    },
.....
```

**Comment by wojtekmaj** [comment]
Looks like you logged this in a wrong repository.

**Comment by AnkitBagaria24** [comment]
@wojtekmaj this is related to reactpdf. Want to generate pdf in custom font. Font.register is not working.

**Comment by wojtekmaj** [comment]
Yeah wrong repo. This package is not generating PDFs.
