### ISSUE TITLE
How to set PDF password or how to encrypt pdf using this library ?

### ISSUE THREAD

**Issue by leanesanity** [wojtekmaj/react-pdf#606]
Good day,

Really need your help.
Would just like to confirm if possible to encrypt pdf file using this library?
It would also be helpful you can provide a simple example.

Your answer will be a big help thanks!

**Comment by wojtekmaj** [comment]
React-PDF is a package to read, not write PDFs. So no, it's not possible to encrypt or otherwise modify the PDFs being read.
