### ISSUE TITLE
onDocumentLoadError undefined in build

### ISSUE THREAD

**Issue by casulit** [wojtekmaj/react-pdf#610]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Error returns undefined in **build** (production)
```
  const onDocumentLoadError = (error) => {
    console.log(error);
    setNumPages(null);
  };
```

**Environment**

 - React-PDF version: 5.0.0-beta.4
 - React version: 16.13.1

**Comment by wojtekmaj** [comment]
There's no such prop but I assume you mean `<Document />`s `onLoadError`. :)

The only way this could be happening is pdf.js throwing undefined. That's quite odd - will need to check.

**Comment by casulit** [comment]
> There's no such prop but I assume you mean `<Document />`s `onLoadError`. :)
> 
> The only way this could be happening is pdf.js throwing undefined. That's quite odd - will need to check.

Sorry I forgot to include the prop for Document to handle error.

This is my setup. I agree I think this is pdf.js problem.

 ```
 const onDocumentLoadError = (error) => {
    console.log(error);
    setNumPages(null);
  };

<Document onLoadError={onDocumentLoadError }></Document>
```

**Comment by reabreu** [comment]
Hello,

Thanks for your work on this library. I also came up across the scenario reported above, seems like errors on `onLoadError` come up as undefined on production build. When node env is development seems to work fine though. Just wondering if there are plans to address this? 

Have a nice week!

**Comment by 957739315** [comment]
Hello, is there a solution for this? I also encountered this problem. It is normal to start the service locally, but after packaging, an error was reported in the production environment.

react-pdf: 5.2.0
 pdfjs.GlobalWorkerOptions.workerSrc = `${STATIC_RESOURCES_VENDORS}react-pdf/pdf.worker.v2.5.207.js`;
