### ISSUE TITLE
File thumbnail covering all pages after rendering

### ISSUE THREAD

**Issue by vibhav2799** [wojtekmaj/react-pdf#612]
**Description**

I am using `react-pdf` in my react app and calling it via react-native using WebView. The PDF contents are being sent as base64 data from react native to react. The pages load correctly but once all pages are loaded, a file thumbnail icon covers all pages.

**Note: `renderMode='svg'` as of now. Upon commenting out this line, the pdf loads fine. I want it to load fine despite it being rendered as svg.**

Initial Page Render
![Screenshot_1595432483](https://user-images.githubusercontent.com/30392601/88198043-e63e7100-cc60-11ea-8f6b-71b2b8e458f9.png)

After ~10 secs

![Screenshot_1595432513](https://user-images.githubusercontent.com/30392601/88198116-feae8b80-cc60-11ea-9a5e-ed8529a19511.png)

**Expected behavior**

PDF should render as expected without File thumbnail icon

**Comment by wojtekmaj** [comment]
Can you reproduce this issue on https://projects.wojtekmaj.pl/react-pdf/test/ ?

**Comment by wojtekmaj** [comment]
Closing as no info on reproduction was provided.
