### ISSUE TITLE
Worker cannot be imported from different origin.

### ISSUE THREAD

**Issue by ppascualv** [wojtekmaj/react-pdf#613]
**What are you trying to achieve? Please describe.**

I have a web page under domain.com that uses a CDN for the JS files, the problem is that the origin is different then when I tri to import the worker Chrome says: 
Uncaught DOMException: Failed to construct 'Worker' 'https://cdn.com' cannot be accessed from origin 'https:domain.com' and CORS are well configured.

I'm using this import
`import { Document } from 'react-pdf/dist/esm/entry.webpack';
`

This is not happening in Firefox

**Describe solutions you've tried**

I tried to use a subdomain for the CDN like cdn.domain.com but not working neither.

**Comment by vijayapalponram** [comment]
Am also facing the same kind of error while loading the worker from different origin.
![image](https://user-images.githubusercontent.com/14360032/97695263-c9200680-1ac9-11eb-8344-7a94fe109ab5.png)

**Comment by wojtekmaj** [comment]
Well, you shouldn't do that. Loading scripts from different origins is usually a bad idea.

**Comment by vijayapalponram** [comment]
As per Micro Front end architecture, i can load my one of the module script from another origin.
https://single-spa.js.org/

**Comment by simy307** [comment]
Same problem here. We are using the new Module Federation in webpack 5 and we have the same issue.

**Comment by milesmao233** [comment]
Does any resolve this problem?

**Comment by wojtekmaj** [comment]
Please kindly check React-PDF [`v5.3.0-beta.2`](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.3.0-beta.2), in which improvements regarding loading PDF.js worker were made. 

These changes should result in 10-15 seconds faster Webpack builds, as well as you should be able to use Webpack entry file in Create-React-App, without the need of using external CDN for hosting worker.

Let me know what you think in #748!

**Comment by sbodi10** [comment]
> **What are you trying to achieve? Please describe.**
> 
> I have a web page under domain.com that uses a CDN for the JS files, the problem is that the origin is different then when I tri to import the worker Chrome says:
> Uncaught DOMException: Failed to construct 'Worker' 'https://cdn.com' cannot be accessed from origin 'https:domain.com' and CORS are well configured.
> 
> I'm using this import
> `import { Document } from 'react-pdf/dist/esm/entry.webpack'; `
> 
> This is not happening in Firefox
> 
> **Describe solutions you've tried**
> 
> I tried to use a subdomain for the CDN like cdn.domain.com but not working neither.

Updating version to v5.3.0-beta.2 worked for me! 🎉
Thanks @wojtekmaj
