### ISSUE TITLE
How to highlight sentence over multiple lines?

### ISSUE THREAD

**Issue by psawa** [wojtekmaj/react-pdf#614]
**Before you start - checklist**

 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have read documentation in README
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I would like to highlight patterns which are spread over multiple lines.

If I try to highlight a sentence which is broken by a line break, nothing will be highlighted since each line belongs to its own <span> tag.

**Describe solutions you've tried**

I thought of looking for the rest of the sentence in the following span in the DOM, but this solutions seems to be really laborious.

**Comment by wojtekmaj** [comment]
Hah, that's a good one!

For this to work you need to:
 
* Get all page text items, which you can do in `<Page />`'s `onLoadSuccess` callback
* Implement `customTextRenderer` to hook into text rendering mechanism
  * Try finding full match in current text item.
    * If found, use [highlightPattern](https://gist.github.com/wojtekmaj/f265f55e89ccb4ce70fbd2f8c7b1d95d) to highlight the match.
    * If not, try finding full match in current text item with `n` previous/next neigbours together (in my case, `n` was 1).
      * If found, find out what part of this highlight, if any, is in current text item. Use [highlightPattern](https://gist.github.com/wojtekmaj/f265f55e89ccb4ce70fbd2f8c7b1d95d) to highlight the partial match.
      * If not, return text item untouched, nothing to do here.

And this is a simplified version, since it only supports single matches! For multiple matches, you will need to make it even more complicated. Anyway, in code it would look like so:

```js
const stringToHighlight = 'Donec sodales placerat dui';

function Test() {
  const [textItems, setTextItems] = useState();

  const onPageLoadSuccess = useCallback(async page => {
    const textContent = await page.getTextContent();
    setTextItems(textContent.items);
  }, []);

  const customTextRenderer = useCallback(textItem => {
    if (!textItems) {
      return;
    }

    const { itemIndex } = textItem;

    const matchInTextItem = textItem.str.match(stringToHighlight);

    if (matchInTextItem) {
      // Found full match within current item, no need for black magic
      return highlightPattern(textItem.str, stringToHighlight);
    }

    // Full match within current item not found, let's check if we can find it
    // spanned across multiple lines

    // Find the prev/next text item
    const prevTextItem = textItems[itemIndex - 1];
    const nextTextItem = textItems[itemIndex + 1];

    // Merge text item strings together
    // You might want do it a little smarter than that
    // Also note there's nothing stopping you from attempting to find matches
    // in sentences spanned across more than 3 text items
    const textItemWithNeighbors = [
      prevTextItem, textItem, nextTextItem
    ].filter(Boolean).map(item => item.str).join('');

    const matchInTextItemWithNeighbors = textItemWithNeighbors.match(
      stringToHighlight,
    );

    if (!matchInTextItemWithNeighbors) {
      // No match
      return textItem.str;
    }

    // Now we need to figure out if the match we found was at least partially
    // in the line we're currently rendering
    const matchIndexStart = textItemWithNeighbors.indexOf(stringToHighlight);
    const matchIndexEnd = matchIndexStart + stringToHighlight.length;

    if (
      // Match entirely in the previous line
      (prevTextItem && matchIndexEnd < prevTextItem.str.length) ||
      // Match entirely in the next line
      (nextTextItem && matchIndexStart > nextTextItem.str.length)
    ) {
      return textItem.str;
    }

    // Match found was partially in the line we're currently rendering. Now
    // we need to figure out what does "partially" exactly mean

    // Find partial match in a line
    const indexOfCurrentTextItemInMergedLines = textItemWithNeighbors.indexOf(
      textItem.str,
    );
    const matchIndexStartInTextItem = Math.max(
      0,
      matchIndexStart - indexOfCurrentTextItemInMergedLines,
    );
    const matchIndexEndInTextItem =
      matchIndexEnd - indexOfCurrentTextItemInMergedLines;

    const partialStringToHighlight = textItem.str.slice(
      matchIndexStartInTextItem,
      matchIndexEndInTextItem,
    );

    return highlightPattern(textItem.str, partialStringToHighlight);
  }, [stringToHighlight, textItems]);

  return (
    <Document file={samplePDF}>
      <Page
        customTextRenderer={customTextRenderer}
        onLoadSuccess={onPageLoadSuccess}
        pageNumber={1}
      />
    </Document>
  );
}
```

[CodeSandbox working demo](https://codesandbox.io/s/react-pdf-multiline-highlight-wijzk)

Yeah, I hate it too.

**Comment by psawa** [comment]
Thank you for the algo and the piece of code. 

However I noticed that depending on how the pdf is rendered, it may not work. 

Do you know why in some PDFs, each line will be wrapped in a <span> tag, and why in some other, each token is wrapped ? In the second case, it's hard to make the algo work.

**Comment by pedro-surf** [comment]
Tried to implement this and no matter what I do it leads to an infinite re-render loop. Please consider having a look

**Comment by wojtekmaj** [comment]
@pedro-surf You have a working example in my comment above, so you need either share the full code with us or find the differences yourself. Perhaps you're creating your custom text renderer with every render because you forgot to use useCallback? Just a blind guess though.

**Comment by githubdebo** [comment]
The code sand box example link is not opening up

**Comment by thijssdaniels** [comment]
Hello, 

Thank you for providing the cod for highlighting text spread over multiple lines! Works great. 

I have another questions. When working with pdf's with multiple pages, how would that look like? Just implementing the code above doesn't seem to work. 

Thanks

**Comment by nickjohnsonucsb** [comment]
This would probably be more efficient if instead of trying to use nearest-neighbor for every `textItem`, we could just iterate through the `textItems` list and concatenate strings line by line to search for the `stringToHighlight`. Is there any alternative we have other than using `customTextRenderer` for this? 

I see there is a PR for this, but how can I use that PR?

**Comment by goughjo02** [comment]
I am just running into this property. On the items there is a transform matrix. it looks like it might be possible to get the bounding box of each item https://github.com/mozilla/pdf.js/issues/5643#issuecomment-239993212

**Comment by hoangForThePeople** [comment]
anyone able to get this working in 2024? I am trying the code above but it isn't working as expected. The demo is not working either.

**Comment by hhn005** [comment]
Anyone got this working in 2024? i'm unable to use the code above and the demo is not working either. @wojtekmaj

**Comment by sneakysquidd** [comment]
I'm looking for a solution for this if there are multiple quotes from the pdf to highlight

**Comment by imabp** [comment]
This issue has caused lot of pain. Any plan to include this in react-pdf out of the box @wojtekmaj ?

**Comment by imabp** [comment]
@sneakysquidd @hhn005 , here is a working solution which I tried in my project and currently used by multiple clients. I have shown the outputs generated with the highlights. Most of the times, it highlights with 98% accuracy.
 
---

Output

<img width="738" height="115" alt="Image" src="https://github.com/user-attachments/assets/4e01f8b9-4cf8-4066-bd05-e7432445610f" />


## Step 1: Extract Text Content from PDF Pages

First, you need to get the text content from each PDF page. PDF.js provides a `getTextContent()` method that returns text items with position data:

```typescript
import { Page } from 'react-pdf';
import type { PDFPageProxy } from 'pdfjs-dist';

// Inside your Page component's onLoadSuccess callback
<Page
  pageNumber={pageNumber}
  onLoadSuccess={async (page: PDFPageProxy) => {
    // Get text content with position information
    const textContent = await page.getTextContent();
    
    // Filter to get only valid text items
    const textItems = textContent.items
      .filter((item): item is TextItem => 'str' in item)
      .filter(item => item.str.trim() !== '');
    
    console.log('Text items:', textItems);
    // Each item contains: { str, transform, width, height, ... }
  }}
/>
```

### Understanding TextItem Structure

```typescript
type TextItem = {
  str: string;           // The actual text
  transform: number[];   // [scaleX, skewY, skewX, scaleY, translateX, translateY]
  width: number;         // Width in PDF units
  height: number;        // Height in PDF units
  // ... other properties
};
```

## Step 2: Understanding the Transform Matrix (Affine Transformation)

The `transform` array is an **affine transformation matrix** in the format `[a, b, c, d, e, f]`:

```
[scaleX,     skewY,      0]     [a, b, 0]
[skewX,      scaleY,     0]  =  [c, d, 0]
[translateX, translateY, 1]     [e, f, 1]
```

### What Each Value Means:

- **`a` (scaleX)**: Horizontal scaling (usually font width factor)
- **`b` (skewY)**: Vertical skewing (usually 0 for normal text)
- **`c` (skewX)**: Horizontal skewing (usually 0 for normal text)
- **`d` (scaleY)**: Vertical scaling - **this is your font size in PDF points**
- **`e` (translateX)**: X position from bottom-left of page
- **`f` (translateY)**: Y position from bottom-left of page

### Key Points:

1. **PDF uses bottom-left origin**, but browsers use top-left
2. **Font size = `scaleY` value** (element [3] of transform array)
3. **Positions are in PDF points**, not pixels (need to multiply by scale)

```typescript
const [scaleX, skewY, skewX, scaleY, translateX, translateY] = textItem.transform;
const fontSize = scaleY;  // Font size in PDF points
const xPosition = translateX;  // X from left
const yPosition = translateY;  // Y from bottom
```

## Step 3: Finding Multi-Line Text Matches

When text spans multiple lines, it's split across multiple text items. You need to match across them:

```typescript
/**
 * Finds text that may span multiple PDF text items
 */
function findTextItemRanges(
  textItems: TextItem[],
  searchText: string
): Array<{
  item: TextItem;
  matchStartInItem: number;
  matchEndInItem: number;
}> {
  const results = [];
  
  // Join all text with spaces
  const joinedText = textItems.map(item => item.str).join(' ');
  
  // Find the match in joined text
  const matchIndex = joinedText.toLowerCase().indexOf(searchText.toLowerCase());
  if (matchIndex === -1) return results;
  
  const matchEnd = matchIndex + searchText.length;
  
  // Map back to individual text items
  let currentPosition = 0;
  
  textItems.forEach(item => {
    const itemStart = currentPosition;
    const itemEnd = currentPosition + item.str.length;
    
    // Check if this item overlaps with the match
    const hasOverlap = !(itemEnd < matchIndex || itemStart >= matchEnd);
    
    if (hasOverlap) {
      results.push({
        item,
        matchStartInItem: Math.max(0, matchIndex - itemStart),
        matchEndInItem: Math.min(item.str.length, matchEnd - itemStart)
      });
    }
    
    currentPosition = itemEnd + 1; // +1 for the space
  });
  
  return results;
}
```

## Step 4: Creating a Custom Highlight Layer

Now create an overlay that positions highlights based on the transform matrices:

```typescript
import { forwardRef } from 'react';
import type { CSSProperties } from 'react';

type HighlightArea = {
  pageIndex: number;
  pageHeight: number;  // Original PDF height in points
  textItems: Array<{
    item: TextItem;
    matchStartInItem: number;
    matchEndInItem: number;
  }>;
};

type CustomHighlightLayerProps = {
  highlightAreas: HighlightArea[];
  totalPages: number;
  scale: number;  // Current page scale (e.g., 1.0, 1.5)
};

export const CustomHighlightLayer = forwardRef<HTMLDivElement, CustomHighlightLayerProps>(
  ({ highlightAreas, totalPages, scale }, ref) => {
    return (
      <div ref={ref} style={{ position: 'absolute', top: 0, left: 0, pointerEvents: 'none' }}>
        {Array.from({ length: totalPages }).map((_, pageIndex) => {
          const pageHighlights = highlightAreas.filter(h => h.pageIndex === pageIndex);
          
          // Get the actual rendered page element
          const pageElement = document.querySelector(
            `div.react-pdf__Page[data-page-number="${pageIndex + 1}"]`
          ) as HTMLDivElement;
          
          if (!pageElement) return null;
          
          return (
            <div
              key={pageIndex}
              style={{
                position: 'absolute',
                top: pageElement.offsetTop,
                left: pageElement.offsetLeft,
                width: pageElement.clientWidth,
                height: pageElement.clientHeight,
              }}
            >
              {pageHighlights.map((highlight, idx) =>
                highlight.textItems.map((textItem, itemIdx) => {
                  const style = calculateHighlightStyle(
                    textItem.item,
                    textItem.matchStartInItem,
                    textItem.matchEndInItem,
                    scale,
                    highlight.pageHeight
                  );
                  
                  return (
                    <div
                      key={`${idx}-${itemIdx}`}
                      style={style}
                      title={textItem.item.str.substring(
                        textItem.matchStartInItem,
                        textItem.matchEndInItem
                      )}
                    />
                  );
                })
              )}
            </div>
          );
        })}
      </div>
    );
  }
);
```

## Step 5: Calculate Precise Highlight Positions

The magic happens here - converting PDF coordinates to pixel coordinates:

```typescript
function calculateHighlightStyle(
  textItem: TextItem,
  matchStart: number,
  matchEnd: number,
  pageScale: number,
  pageHeight: number
): CSSProperties {
  const [, , , scaleY, translateX, translateY] = textItem.transform;
  
  // 1. Get font size from transform matrix
  const fontSize = scaleY;
  
  // 2. Calculate character-level positioning
  const fullTextWidth = textItem.width;
  const avgCharWidth = fullTextWidth / textItem.str.length;
  
  // Width of text before the match
  const beforeMatchWidth = matchStart * avgCharWidth;
  // Width of the matched text
  const matchWidth = (matchEnd - matchStart) * avgCharWidth;
  
  // 3. Convert from PDF coordinates (bottom-left origin) to CSS (top-left origin)
  const pdfTop = pageHeight - translateY - fontSize;
  
  // 4. Apply scale and convert to pixels
  const scaledLeft = (translateX + beforeMatchWidth) * pageScale;
  const scaledWidth = matchWidth * pageScale;
  const scaledHeight = fontSize * pageScale;
  const scaledTop = pdfTop * pageScale - scaledHeight * 0.75; // Adjust for baseline
  
  return {
    position: 'absolute',
    backgroundColor: 'rgba(255, 235, 59, 0.5)',
    border: '1px solid rgba(255, 193, 7, 0.8)',
    left: `${scaledLeft}px`,
    top: `${scaledTop}px`,
    width: `${scaledWidth}px`,
    height: `${scaledHeight}px`,
    pointerEvents: 'none',
  };
}
```

## Step 6: Putting It All Together

```typescript
function PDFViewer({ searchText }: { searchText?: string }) {
  const [highlightAreas, setHighlightAreas] = useState<HighlightArea[]>([]);
  const [scale, setScale] = useState(1.0);
  const [numPages, setNumPages] = useState(0);
  
  return (
    <div style={{ position: 'relative' }}>
      <Document file="sample.pdf" onLoadSuccess={({ numPages }) => setNumPages(numPages)}>
        {Array.from({ length: numPages }, (_, i) => (
          <Page
            key={i}
            pageNumber={i + 1}
            scale={scale}
            onLoadSuccess={async (page) => {
              if (searchText) {
                const textContent = await page.getTextContent();
                const textItems = textContent.items.filter(item => 'str' in item);
                
                const matches = findTextItemRanges(textItems, searchText);
                
                if (matches.length > 0) {
                  setHighlightAreas(prev => [...prev, {
                    pageIndex: i,
                    pageHeight: page.height,
                    textItems: matches,
                  }]);
                }
              }
            }}
          />
        ))}
      </Document>
      
      <CustomHighlightLayer
        highlightAreas={highlightAreas}
        totalPages={numPages}
        scale={scale}
      />
    </div>
  );
}
```

## Key Takeaways

1. **Text items are individual fragments** - text on multiple lines = multiple items
2. **Transform matrices contain position data** - element [3] is font size, [4] is X, [5] is Y
3. **PDF uses bottom-left origin** - must convert: `cssTop = pageHeight - pdfY - fontSize`
4. **Everything must be scaled** - multiply all dimensions by the page scale
5. **Character-level precision** - divide text width by string length for approximation

**Comment by mgkeen** [comment]
@imabp this saved me so much brain ache. Thank you so much for posting! I switched up a few things in my implementation to better align with how we're using the document, but this gave me such a good basis to go off.

The one thing that I had to alter from a algorithm point of view was the CSS top. Subtracting the font size meant the highlight didn't line up with the text. So i went from:
` const pdfTop = pageHeight - translateY - fontSize;`
to:
` const pdfTop = pageHeight - translateY;`

Perhaps it was due to some other changes I made elsewhere, not sure. But putting that out there for others just in case.

**Comment by imabp** [comment]
@mgkeen happy the solution helped it out.

Font-size addresses for the cases, when you have different ligatures and font systems in your pdf. It varies from system to system. What you see on Mac, may not work on Windows, just because they use different font technology. So better to have an generalized offset based on your use case

**Comment by tevinch** [comment]
For the fragment-boundary and repeated-match cases discussed here, a useful approach is to search one page-wide text stream and map the hits back to the original item offsets. That avoids a fixed number of neighboring items and avoids estimating character widths for an overlay.

I made a small [MIT mapping module and runnable React-PDF example](https://github.com/tevinch/data-shape-kit/tree/main/examples/pdf-fragment-highlight) using this approach. Its integration is:

```tsx
// Keep the exact array from onGetTextSuccess, including empty entries.
const result = highlightTextItems(items, phrases);

const customTextRenderer = ({ itemIndex }) => result.html[itemIndex];
```

The mapper concatenates text fragments without adding spaces between them, adds a whitespace boundary for `hasEOL`, normalizes whitespace, finds all literal occurrences, and intersects each match with the original item ranges. It preserves `itemIndex` even when non-text entries are present. Overlapping marks merge for display, while the match count still reports occurrences. The returned HTML escapes the original text before adding fixed `mark` tags.

The complete component wires the public callbacks and keeps each page's mapping separate. The included two-page fixture covers repeated phrases across three lines and several font fragments, using React-PDF 10.5.0 with its matching PDF.js 5.4.296 worker.

This follows PDF.js extraction order and explicit line endings. It does not infer missing spaces, reconstruct multi-column reading order, remove line-end hyphens, or add OCR; those require a separate normalization or extraction policy.
