### ISSUE TITLE
Document dissapears on page reload

### ISSUE THREAD

**Issue by laclance** [wojtekmaj/react-pdf#615]
- [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

PDF, from a s3 url, shows fine the first time but if I refresh the page it dissapears, onDocumentLoadSuccess fires and onLoadError does not. I found this in my terminal though `require function is used in a way in which dependencies cannot be statically extracted`

```
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

<Document
    file="https://s3-eu-west-1.amazonaws.com/....pdf"
    onLoadSuccess={onDocumentLoadSuccess}
    onLoadError={console.error}
>
    <Page pageNumber={pageNumber} />
</Document>
```

**Environment**

 - Browser: Chrome 84
 - React-PDF: 4.1.0
 - React version: 16.13.0
 - react-scripts version: 3.4.1

**Comment by wojtekmaj** [comment]
Check Network tab for any errors. I don't think anything in React-PDF itself can cause this behavior, reloading a page is essentially doing the same thing over again 🤔

**Comment by laclance** [comment]
no errors, everything looks fine.

**Comment by wojtekmaj** [comment]
Can you copy your code and create a reproduction repo on CodeSandbox?

**Comment by laclance** [comment]
fount the problem, sorry, thanks.
