### ISSUE TITLE
PDF text not displayed correctly when embedded in popup window using React Portal

### ISSUE THREAD

**Issue by lifan0127** [wojtekmaj/react-pdf#616]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

My use cases involves using React Portal to display PDF in a new popup window, more or less following this blog post: https://medium.com/hackernoon/using-a-react-16-portal-to-do-something-cool-2a2d627b0202

However, text will not display correctly in the popup window, when the same PDF is displayed properly in the main browser window. This seems to happen for all my PDF files.

![image](https://user-images.githubusercontent.com/7218193/88487539-eafe7000-cf53-11ea-90e4-ba2c42eb097c.png)

**Steps to reproduce**

Please see the sandbox https://codesandbox.io/s/objective-noether-7nplp?file=/src/App.js

Note that you need to choose "Open in New Window" to avoid the iframe security error.

**Environment**

 - Browser (if applicable): Chrome, Firefox
 - React-PDF version [e.g. 3.0.4]: 4.1.0
 - React version [e.g. 16.3.0]: 16.13.1
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by lifan0127** [comment]
I have realized that if I set pdfjs option `disableFontFace: true`, the sample PDF will render correctly in the __popup__ window. However some other PDFs will fail with text completely missing, for example:

![image](https://user-images.githubusercontent.com/7218193/88999644-15895980-d2c3-11ea-899e-7993d5b0e5af.png)

Note that all the PDFs are rendered correctly if the `react-pdf` component is in the __main__ window with `disableFontFace: false`.

Based on some potentially related discussions:

https://github.com/mozilla/pdf.js/issues/4244

https://github.com/mozilla/pdf.js/issues/11955 (very helpful)

and the definition of the `disableFontFace` parameter:

```
By default fonts are converted to OpenType fonts and loaded via font face rules. 
If disabled, fonts will be rendered using a built-in font renderer that constructs the glyphs 
with primitive path commands. The default value is `false`
```

I suspect my issue is caused by a font face loading problem in the __popup__ window. But I don't know this topic well enough to further troubleshoot.

**Comment by wojtekmaj** [comment]
Yeah, since fonts are added to the document that loads React-PDF, you would need to load React-PDF in popup. Otherwise the popup doesn't have access to the fonts, and consequently displays gibberish.

Not sure how to achieve this using this specific library, so I'm going to leave this open for the community to help.

**Comment by Sharcoux** [comment]
Notice that we have the exact same issue in electron

**Comment by wojtekmaj** [comment]
Ok, I have a promising update:

There is `options` prop in `<Document />` which you can pass some options to:
https://github.com/wojtekmaj/react-pdf/blob/99a0fcf3090cf665d5f23b219f680249d8a15a72/README.md#L277

It looks like DocumentInitParameters has something called `ownerDocument`:
https://github.com/mozilla/pdf.js/blob/403baa7bbab555c2a84e6787bc3dc2ab49724467/src/display/api.js#L200-L202

So if you could pass a reference to popup window using this option, fonts should render properly.

**Comment by wojtekmaj** [comment]
Pardon my French but fuck yes! Here's a working example:

https://codesandbox.io/s/react-pdf-popup-vco8p

Note: This works with React-PDF 5.7.0. React-PDF 4.1.0 used by OP does not support this option.

**Comment by lifan0127** [comment]
Thank you so much for your persistent effort!! It is great to know this problem has been addressed and learned a lot from your solution!
