### ISSUE TITLE
Where to get code for demo?

### ISSUE THREAD

**Issue by lhuang61** [wojtekmaj/react-pdf#618]
Trying to create something similar to the demo (https://projects.wojtekmaj.pl/react-pdf/), specifically a view that displays one page and the user can jump between pages with the buttons. Can someone please let me know which configuration is needed for this?

**Comment by wojtekmaj** [comment]
See Recipes in Wiki.

**Comment by lhuang61** [comment]
Thanks @wojtekmaj. Just noticed a small issue: when the 'Next' button is clicked, the whole browser page scrolls to the top (this only occurs at the first instance of loading each page).
