### ISSUE TITLE
 Invalid element of type input passed to PDF renderer

### ISSUE THREAD

**Issue by mihir-kanzariya** [wojtekmaj/react-pdf#620]
I want to create pdfForm like this. 
[samplePdfForm.pdf](http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf)

this is my code: https://prnt.sc/ttr1z5

`  <Document><Page
      size="A4"
      style={styles.page}
      renderAnnotationLayer={true}
      renderInteractiveForms={true}
      debug={true}
    >
      <View style={styles.tableR}>
        <View style={styles.tableRow}>
          <View styles={styles.tableCol}>
            <input type="text" />
          </View>
        </View>
      </View>
    </Page>
  </Document>`
![image](https://user-images.githubusercontent.com/35109112/89282600-673a3700-d669-11ea-9830-21fe8f454eb3.png)

**How to add form element in pdf?**

**Comment by wojtekmaj** [comment]
Wrong repository.
