### ISSUE TITLE
Doesn't render the PDF from url

### ISSUE THREAD

**Issue by webguru103** [wojtekmaj/react-pdf#622]
Hi @wojtekmaj Thanks for your updates of 5.0.0.0-beta.5
I fixed globalEventBus issue using this version.
But Document component doesn't render the PDF from url.
![image](https://user-images.githubusercontent.com/24473200/89339525-9c14b100-d69e-11ea-82b3-55593920faaf.png)

**Comment by webguru103** [comment]
Here is the code for it.
import React, { useState } from "react";
import { Document } from 'react-pdf';
import Loading from "../Loading";

const PDFViewer = ({ url }) => {
  return (
    <div className="PDFViewContainer">
      <Document
        file={url}
        loading={<Loading />}
      />
    </div>
  );
};

export default PDFViewer;

**Comment by wojtekmaj** [comment]
You're only loading document, but are not displaying any pages. Use Page component as per docs and Wiki.

**Comment by ksuess** [comment]
See simple example displaying first page of PDF: https://github.com/wojtekmaj/react-pdf#usage

As @wojtekmaj  mentioned, it's necessary to call 
`<Page pageNumber={pageNumber} /> `
for **displaying** a page of your PDF.
