### ISSUE TITLE
PDF displaying boxes and images but no font. Warning: Unimplemented operator paintImageMaskXObjectGroup

### ISSUE THREAD

**Issue by namedoc** [wojtekmaj/react-pdf#624]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I am trying to view PDFs but there are select PDFs that do not render the font on the pdf. Only outlines, boxes, and images. I can download the response as a PDF file and open it with adobe and it works as expected.

**Describe solutions you've tried**

I have tried updating the versions of react-pdf and renderer. I am now using "react-pdf": "^4.2.0" and "@react-pdf/renderer": "^1.6.10". The PDF viewer works for most documents but certain PDFs are causing this issue. I've verified that the PDF itself opens and displays fine in adobe.

**Additional information**
Any time I try to view these documents I am getting this warning in the console and I cannot find anything on it. Sounds like a masking issue but I am not entirely sure what it means. I've added some screenshots of what the PDFs look like when they are not showing the details/fonts.

Warning: Unimplemented operator paintImageMaskXObjectGroup

![consoleWarning](https://user-images.githubusercontent.com/7495104/89559692-a4bed180-d7db-11ea-9e71-a8204bead7f8.PNG)
![pdfviewermissingfont](https://user-images.githubusercontent.com/7495104/89559696-a5576800-d7db-11ea-81e4-bfd3adfc7d31.PNG)

**Environment**

 - Browser (if applicable) [Chrome 81]:
 - React-PDF version [e.g. 4.2.0]:
 - React version [e.g. 16.12.0]:

**Comment by wojtekmaj** [comment]
Verify if the PDFs you have issues with are working in Firefox. If they don't, you may want to report the issue to PDF.js project.

**Comment by namedoc** [comment]
I was able to verify that these issues exist in Firefox as well. I also opened in issue on the PDF.js project here:

https://github.com/mozilla/pdf.js/issues/12181

Attach (recommended) or Link to PDF file here: Sensitive data.

Without a test-case, the issue is unfortunately not actionable/valid.

PDF.js version: "react-pdf": "^4.2.0", pdfjsVersion = '2.1.266';

Please note that React-PDF is a different project, which we cannot provide support for here.
Furthermore, the quoted PDF.js version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases

I get this error in the console Warning: Unimplemented operator paintImageMaskXObjectGroup.

That suggests that you're using the SVG-backend, which as mentioned in the Wiki is not officially supported; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

**Comment by wojtekmaj** [comment]
In this case, there's nothing we can do, until pdf.js team implements said operator. Sorry about that!

**Comment by namedoc** [comment]
Hi wojtekmaj - Here is the latest on the pdf.js issue. They said that this issue should not happen if we were using the default canvas back-end instead of the SVG rendering back-end. Is there a version of react-pdf that uses the default canvas back-end and not the SVG rendering back end? 

-----------------------------------------------

Again, without a test-case there's nothing that anyone can do here!

Also, the particular error quoted here won't happen if you (as mentioned previously) use the default canvas back-end instead (or at least use a fully up-to-date version of the PDF.js library).

Edit: The fact that the React-PDF project apparently uses the officially unsupported SVG rendering back-end of the PDF.js library is a "bug" in that project; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

**Comment by wojtekmaj** [comment]
@namedoc, by default React-PDF uses canvas rendering. You need to opt in to SVG rendering manually.

**Comment by namedoc** [comment]
Currently working on getting a pdf that I can upload to reference...  

Wondering if there is any chance that fonts could come into play here and may need to be imported for the react-pdf to use? I would have thought we'd see a font error of some sort in the console if that was the case but figured I'd ask anyways.

**Comment by wojtekmaj** [comment]
Frankly I lack knowledge in how PDF.js works exactly when rendering stuff. I know its public API, maybe slightly better than a common user being a maintainer of this package for a few years, but still it's mostly magic to me :D

**Comment by namedoc** [comment]
I am attaching an example PDF. If you open it in Adobe you'll see what it should look like.
[QTFRStmtsEmail- redacted.pdf](https://github.com/wojtekmaj/react-pdf/files/5063524/QTFRStmtsEmail-.redacted.pdf)

Screenshots of the difference:
![react-pdf](https://user-images.githubusercontent.com/7495104/90030466-b1cb3d00-dc81-11ea-81ce-a4b94ee5a69c.PNG)
![adobe](https://user-images.githubusercontent.com/7495104/90030467-b263d380-dc81-11ea-98cb-b770cc793156.PNG)

**Comment by wojtekmaj** [comment]
Yep, pdf.js doesn't render that correctly with SVG rendering. It renders fine with default canvas rendering.

**Comment by namedoc** [comment]
Just found out a property was indeed being set to not use the default canvas rendering mode and I changed it and it works now! Thank you for your help!

Do you know what the benefit of changing from canvas to svg is??
