### ISSUE TITLE
Saving the PDF to backend

### ISSUE THREAD

**Issue by MarErnest** [wojtekmaj/react-pdf#625]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I want to save the pdf displayed to the backend

**Describe solutions you've tried**
I have not seen any solution

**Comment by wojtekmaj** [comment]
React-PDF only reads the PDF, so I won't be able to help you. You need to save the PDF yourself, as any other file.
