### ISSUE TITLE
Copy/paste text selection not working correct from rendered pdf

### ISSUE THREAD

**Issue by frontSoftFront** [wojtekmaj/react-pdf#627]
**Before you start - checklist**

 - [+] I have read documentation in README
 - [+] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [+] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'd like to copy/paste the text of my PDF.

**Describe solutions you've tried**

On canvas mode, I can't correct select text. On SVG mode incorrect pdf rendering.

**Additional information**

Please, see my screens and file I working on
[Coyote #20262583 LC.pdf](https://github.com/wojtekmaj/react-pdf/files/5056082/Coyote.20262583.LC.pdf)
![Screenshot from 2020-08-11 12-29-01](https://user-images.githubusercontent.com/64895890/89881815-abc85400-dbce-11ea-8413-c078918ec8e3.png)
![Screenshot from 2020-08-11 12-28-41](https://user-images.githubusercontent.com/64895890/89881820-ac60ea80-dbce-11ea-8eae-cf8fad226e57.png)
![Screenshot from 2020-08-11 12-07-05](https://user-images.githubusercontent.com/64895890/89881823-acf98100-dbce-11ea-96f7-dcc14406399c.png)
![Screenshot from 2020-08-11 12-06-27](https://user-images.githubusercontent.com/64895890/89881826-acf98100-dbce-11ea-9933-7da7b0c5e648.png)
![Screenshot from 2020-08-11 12-06-12](https://user-images.githubusercontent.com/64895890/89881828-ad921780-dbce-11ea-9666-01f1f36ddc10.png)

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Chrome 72
 - React-PDF version [e.g. 3.0.4]: 3.0.6
 - React version [e.g. 16.3.0]: 15.6.2
 - Webpack version (if applicable) [e.g. 4.16.2]: 3.3.0

**Comment by wojtekmaj** [comment]
Just like on Canvas layer, text on SVG isn't meant to be copied.

Use `renderTextLayer` to render selectable text.

See also https://github.com/mozilla/pdf.js/issues/10205

**Comment by wojtekmaj** [comment]
Unfortunately this PDF is not properly encoded. Copying text on Firefox, Chrome and Adobe Reader all results in gibberish.

**Comment by basile-savouret** [comment]
@wojtekmaj it's been a while since this issue was created. Is there any update on this thread: https://github.com/mozilla/pdf.js/issues/10205? Or in which version can i go back to have the text in svg rendering correctly?

**Comment by basile-savouret** [comment]
Thanks a lot for the answer :) . I'll try the older versions and see if it's good enough. I wish you great week anyway!
