### ISSUE TITLE
I can't not display Vietnamese and Japanese .

### ISSUE THREAD

**Issue by tranvu14** [wojtekmaj/react-pdf#629]
**Before you start - checklist**

 - [ x] I followed instructions in documentation written for my React-PDF version
 - [ x] I have checked if this bug is not already reported
 - [ x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [ x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

The pdf does not display Japanese and Vietnamese in the right way. 

**Steps to reproduce**

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

What you expected to happen?

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by wojtekmaj** [comment]
Please provide details, examples, reproduction repository if applicable, otherwise I'll need to close the ticket.

**Comment by inahsanjuan** [comment]
@tranvu14 Any updates regarding this? How did you solve your problem? 🙏

**Comment by wojtekmaj** [comment]
https://github.com/wojtekmaj/react-pdf#support-for-non-latin-characters
