### ISSUE TITLE
Special fonts cannot be parsed

### ISSUE THREAD

**Issue by onreadystatechange** [wojtekmaj/react-pdf#63]
![image](https://user-images.githubusercontent.com/21106077/30631348-7df515ca-9e16-11e7-8ffb-a1fa807fa2b1.png)
![image](https://user-images.githubusercontent.com/21106077/30631374-986ea470-9e16-11e7-974d-716fc30f136e.png)

**Comment by wojtekmaj** [comment]
Hey, thank you! This has already been reported just before you at #62. I'm closing it and I'd suggest you to follow the thread in #62 to get info about it being fixed.
