### ISSUE TITLE
Migrate to pdfjs version 2.5.207

### ISSUE THREAD

**Issue by druzhchenko** [wojtekmaj/react-pdf#631]
Hi. I have some documents which spontaneously rotate on version pdfjs 2.4.456 and below. Are you planing to migrate to pdfjs version 2.5.207 in the near future? 2.5.207 doesn't have this issue, so that's why it's kind of critical to know the roadmap for updating to one

**Comment by wojtekmaj** [comment]
Yes, absolutely.

Mozilla's pdf.js team was always a little... "liberal" when it comes to following semver, that's why we have exact versions set in our dependencies. I think the plan would be to release React-PDF 5.0 with most up-to-date dependencies at the moment of release.

**Comment by wojtekmaj** [comment]
Sorry, actually the latest is not 2.5.207 - it's a pre-release. We will continue upgrading pdfjs in the future, but not to this specific version.
