### ISSUE TITLE
How to set current page while users scroll through document?

### ISSUE THREAD

**Issue by pedro-surf** [wojtekmaj/react-pdf#632]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

On recipes there is one where we set the current page by clicking on a Next/Prev button.
How could I get the current focused page from a Document with **overflow: auto** ?
I want to change current page when user is scrolling as well, not only when clicking that button.
Since we cannot have a onMouseOver or such Dom events on Page component I have no insights for that.

[Code on stackoverflow](https://stackoverflow.com/questions/63562159/how-to-get-current-scrolled-element-key-react-pdf)
Thanks!

**Environment**

 - Browser: Electron 
 - React-PDF: latest
- React: latest (CRA)

**Comment by wojtekmaj** [comment]
Try leveraging IntersectionObserver. This would let you track which page is currently displayed in viewport.

**Comment by wojtekmaj** [comment]
This is how I'd do it:
https://codesandbox.io/s/react-pdf-intersection-observer-90gvy

**Comment by kaiwenxiao** [comment]
> This is how I'd do it: https://codesandbox.io/s/react-pdf-intersection-observer-90gvy

Hi Sir, is it any possible this example can be using in 4.x? Because I need to compatible with suck ie 11.

Thank and waiting for your reply.

**Comment by wojtekmaj** [comment]
@kaiwenxiao Very similar, but since you can't use canvasRef in 4.x, you need to attach ref to `<div>` wrapping `<Page>`, instead of passing it to `<Page>`.

https://codesandbox.io/s/react-pdf-intersection-observer-v4-y3qjxy

**Comment by kaiwenxiao** [comment]
Thanks, it works!

**Comment by kaiwenxiao** [comment]
> @kaiwenxiao Very similar, but since you can't use canvasRef in 4.x, you need to attach ref to `<div>` wrapping `<Page>`, instead of passing it to `<Page>`.
> 
> 
> 
> https://codesandbox.io/s/react-pdf-intersection-observer-v4-y3qjxy?file=/src/index.jsx:869-959

Hello, sir. I'm confused about this code about `ref={setPage}`, why it will be the identifier? Thanks!
