### ISSUE TITLE
How to create and display annotations?

### ISSUE THREAD

**Issue by pedro-surf** [wojtekmaj/react-pdf#633]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'm trying to add some annotations to my document.

**Describe solutions you've tried**
  All I found was an instruction to pass these props to Page component:
```
     onGetAnnotationsSuccess={console.log}
     onGetAnnotationsError={console.error}
```
They return me an empty array. How can I add to them? I already have imported the CSS.

`import "react-pdf/dist/Page/AnnotationLayer.css";`

 Once it seems like we cannot have a onMouseUp or such Dom events on Page component I have no insights for that.

Code: 

```
  <Document
              className="viewer"
              onLoadError={() => toast.error("Error loading document")}
              onLoadSuccess={({ numPages }) => setNumPages(numPages)}
              noData={<Loader />}
              file={{ data }}
              options={{
                cMapUrl: `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/cmaps/`,
                cMapPacked: true,
              }}
            >
              {Array.from(new Array(numPages), (el, index) => (
                <Page
                  key={`page_${index + 1}`}
                  pageNumber={index + 1}
                  customTextRenderer={makeTextRenderer(searchText)}
                  onGetAnnotationsSuccess={console.log}
                  onGetAnnotationsError={console.error}
                  inputRef={
                    pageNumber === index + 1
                      ? (ref) => ref && ref.scrollIntoView()
                      : null
                  }
                />
              ))}
            </Document>
```

**Environment**

 - Browser: Electron:latest
 - React-PDF: latest
 - React version: latest CRA

**Comment by wojtekmaj** [comment]
You can't add any annotations. React-PDF reads, not writes PDFs.
