### ISSUE TITLE
Unexperienced (github) users may go to astray the really helpfull wiki

### ISSUE THREAD

**Issue by ksuess** [wojtekmaj/react-pdf#634]
I think adding a toc to the index page or a hint to the toc on the right would help a lot.
https://github.com/wojtekmaj/react-pdf/wiki

Thank you @wojtekmaj for your geat work!

**Comment by wojtekmaj** [comment]
Hmmm, Recipes from wiki are mentioned in README, but indeed maybe the wiki itself isn't visible enough!
