### ISSUE TITLE
Code breaks in production server

### ISSUE THREAD

**Issue by SwapnaleePatil** [wojtekmaj/react-pdf#635]
Hello @wojtekmaj ,

**Code:**
`<View> {text ? text : ''} </View>`

This code works fine on the development server.
But the same code brakes page on a production server

**Fixed Code:**
`<View> {text ? text : ''} </View>`

Why we are not getting errors in the development server?

Is there anything related to build?

Thank you in advance!

**Comment by wojtekmaj** [comment]
What's `<View>`? I don't know what you are talking about 🤔

**Comment by SwapnaleePatil** [comment]
<Document>
    <Page style={styles.body}>
      <View>{""}</View>
    </Page>
  </Document>

**Comment by wojtekmaj** [comment]
Doesn't look like React-PDF to me. There's no `<View>` in React-PDF.
