### ISSUE TITLE
Is it possible to drop components on top of each pdf page?

### ISSUE THREAD

**Issue by reggie-it** [wojtekmaj/react-pdf#638]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'd like to be able to drop html elements / components on the pdf. 

**Describe solutions you've tried**

I tried to create wrapper for <Page/> and converted that wrapper into a droppable are. But it just sits at the back of the page when rendered

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.
![Screen Shot 2020-08-31 at 1 43 09 PM](https://user-images.githubusercontent.com/46663727/91680854-f9adf780-eb8f-11ea-9e13-49c808781187.png)

I am trying to achieve something similar to this.
https://codepen.io/mozez/details/KKKoWjW

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by choukrus** [comment]
Heey, I'm trying to do the same thing, did you found a solution to this problem ?

**Comment by reggie-it** [comment]
> Heey, I'm trying to do the same thing, did you found a solution to this problem ?

Hey @choukrus, Yeah I was able to. Basically you need to create a wrapper for `<Page/>` 
Add an overlay on top of it and that will be your drag and droppable where you can render basically anything.

**Comment by kandelin16** [comment]
@reggie-it Does this approach force rerenders of the Document element when the state of your overlay changes?
