### ISSUE TITLE
is it possible to disable text mark in the pdf viewer?

### ISSUE THREAD

**Issue by eliransu** [wojtekmaj/react-pdf#640]
hi, 

trying to find a way to disable the option to mark the pdf text (in order to prevent data copying in my system).
someone can help with it?

thanks!

**Comment by wojtekmaj** [comment]
* Check `renderTextLayer` in documentation. 
* Use canvas rendering.
* Add pointer-events: none to elements rendered by React-PDF

**Comment by sohamdata** [comment]
> * Check `renderTextLayer` in documentation.
> * Use canvas rendering.
> * Add pointer-events: none to elements rendered by React-PDF

Tried, doesn't work. Any other options ?

**Comment by ByNetherdude** [comment]
Adding `renderTextLayer={false}` to the `<Page>` should do the trick.
