### ISSUE TITLE
Error: Unknown action from worker: undefined

### ISSUE THREAD

**Issue by karthik-v-dev** [wojtekmaj/react-pdf#644]
×
Error: Unknown action from worker: undefined
Worker.MessageHandler._onComObjOnMessage
D:/react site copy/site/pdfjs-dist/build/pdf/src/shared/message_handler.js:114

**Comment by SamuelMS** [comment]
I also receive this error when upgrading to `5.0.0` (from `beta-2`).

**Comment by wojtekmaj** [comment]
I'll need a way to reproduce the issue, it doesn't happen on my configuration.

**Comment by SamuelMS** [comment]
I was actually able to resolve this on my end – it was a silent version mismatch with the PDF.js worker file that we were serving (i.e. an old version). Still getting a massive performance degradation though, and I finally got around to creating a sample app that has the same issue – will post in the other thread.

**Comment by Sahero** [comment]
This will work if you use the previous version of the pdf.worker.js file. That is [https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.js](https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.js)

**Comment by occult** [comment]
> This will work if you use the previous version of the pdf.worker.js file. That is https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.js

Thank you so much! The issue was that I updated react-pdf to 5.0.0 and didn't update the version of the service worker 🤦
