### ISSUE TITLE
Sample (webpack) Cannot resolve module 'react-pdf/dist/entry.webpack' [version 5]

### ISSUE THREAD

**Issue by puneetverma05** [wojtekmaj/react-pdf#645]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [ ] I have checked if this bug is not already reported
-  [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**
 `Can't resolve 'react-pdf/dist/Page/AnnotationLayer.css'`
 `Can't resolve 'react-pdf/dist/entry.webpack'`

**Steps to reproduce**

Build sample (webpack) project

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.
![image](https://user-images.githubusercontent.com/3938044/92948431-fca1c580-f476-11ea-860e-848c635d1685.png)

**Environment**

 - React-PDF version: 5.0.0
 - React version: ^16.5.0
 - Webpack version: 4.44.1

**Comment by puneetverma05** [comment]
hey @wojtekmaj , when you back can you please have a look into this, enjoy your holidays!

**Comment by meehaws** [comment]
@puneetverma05 have you solved this issue? Facing the same one.

**Comment by wojtekmaj** [comment]
A breaking change was introduced in v5.0.0 that requires you to adjust the paths to Webpack-specific entries.

Indeed, sample repo was not updated to use the new paths. Thanks for reporting. Fixed that in 8083003f447acd633f2cb8363074003b7969050d.
