### ISSUE TITLE
Hide the Delete and Print buttons on PDFViewer

### ISSUE THREAD

**Issue by YordanovDnA** [wojtekmaj/react-pdf#647]
Is there a possibility to hide the delete and print buttons and maybe disable the right click on PDFViewer so the user can't download the file before it's not signed from the higher authority?

I'm trying to build a project where a document is created by the user and send for signing (confirmation) from the boss before is sent to the customer or printed out.

**Comment by wojtekmaj** [comment]
I don't think that's the right repo. We don't have PDFViewer component, in fact no UI whatsoever.
