### ISSUE TITLE
Rectangles rendered instead of characters in PDF exported by Word

### ISSUE THREAD

**Issue by isaaccruzitc** [wojtekmaj/react-pdf#648]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? 
I want to render a very simple pdf exported by Word, but when I do so, the text is displayed as horrible rectangles.

**Describe solutions you've tried**

I've tried changing pdfjs property disableFontFace to false and true, and neither option renders correctly the text.

**Additional information**

![Captura de pantalla de 2020-09-14 00-28-48](https://user-images.githubusercontent.com/68034159/93049577-e9cdf300-f626-11ea-9d04-0794f1baf6b4.png)

**Environment**

 - Browser:  Chrome 84.0.4147.125
 - React-PDF version: 5.0.0
 - React version: 16.13.1
 - Webpack version: 4.19.1

**Comment by wojtekmaj** [comment]
Is the text latin alphabet? If not, did you add cmaps (instructions in README)?

**Comment by isaaccruzitc** [comment]
> Is the text latin alphabet? If not, did you add cmaps (instructions in README)?

Yes, the text latin alphabet.
This is what it should have rendered:

![Captura de pantalla de 2020-09-14 12-41-24](https://user-images.githubusercontent.com/68034159/93119584-a8b9fb00-f687-11ea-9193-f4e2dbb47083.png)

Thanks in advance.

**Comment by isaaccruzitc** [comment]
I've managed to render this document, I was adding the property  "disableFontFace" in the wrong place. 
But I have another problem now, the rest of my pdf files are not rendering text.
Here is an example of how it should look like:

![Captura de pantalla de 2020-09-14 13-00-31](https://user-images.githubusercontent.com/68034159/93121462-7c53ae00-f68a-11ea-9707-63a40a13b354.png)

And here is how its rendered now:

![Captura de pantalla de 2020-09-14 13-00-44](https://user-images.githubusercontent.com/68034159/93121475-837abc00-f68a-11ea-9a52-3dc44b568c24.png)

On the console I can see the following messages:

Warning: getPathGenerator - ignoring character: "Error: Requesting object that isn't resolved yet Helvetica_path_Q.".
Warning: getPathGenerator - ignoring character: "Error: Requesting object that isn't resolved yet Helvetica_path_G.".
Warning: getPathGenerator - ignoring character: "Error: Requesting object that isn't resolved yet Helvetica_path_X.".
Warning: getPathGenerator - ignoring character: "Error: Requesting object that isn't resolved yet Helvetica_path_B.". 

I really appreciate your help.

**Comment by wojtekmaj** [comment]
Is that canvas rendering (default), or SVG rendering?

**Comment by isaaccruzitc** [comment]
> Is that canvas rendering (default), or SVG rendering?

It's a canvas rendering.

**Comment by wojtekmaj** [comment]
@isaaccruzitc Does it render correctly in Firefox? If yes, then we have a problem… 🤔  If not, I guess this must be fixed at PDF level unfortunately.

**Comment by Furuyah** [comment]
I have exactly this issue:

![sss](https://github.com/wojtekmaj/react-pdf/assets/4260358/cb096ade-efd4-4330-bead-c935a52009cb)

I'm sorry for posting this here as this has nothing to do with react-pdf. I'm just using standard Firefox on PC but the issue is exactly the same as described here.
