### ISSUE TITLE
Do we have a behavior where we can load all the pages plus we can use pagination 

### ISSUE THREAD

**Issue by monikadeshmukh72** [wojtekmaj/react-pdf#649]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I want to give the functionality of scrolling plus pagination to a pdf file

**Comment by wojtekmaj** [comment]
Sure you can implement it. Here's a starting point:

https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-all-pages

And from there, you can add whatever GUI you need.
