### ISSUE TITLE
Throwing AbortException when unmounting react-pdf components before PDF is finished rendering

### ISSUE THREAD

**Issue by taylorbf** [wojtekmaj/react-pdf#651]
**What are you trying to achieve? Please describe.**

I'd like to be able to unmount my PDF viewer component before the PDF is finished rendering, without having an unhandled promise exception.

**Describe solutions you've tried**

I have tried using the available onRenderError, onLoadError, etc props. I've also tried wrapping the component in an ErrorBoundary, however it does not catch this error.

**Additional information**

This is an unhandled promise exception from within PDF.js. I wonder if this exception could be handled within your library or if a prop could be exposed to handle this error.   I imagine others have come across this error and I wonder how others have solved this.

When unmounting the `<Document>` and `<Page>` before it is finished rendering:
```
Uncaught (in promise) pdf.js:1153 
AbortException: {
  message: "Worker was terminated."
  name: "AbortException"
}
```

Using this worker: `'react-pdf/dist/esm/entry.webpack.js'`

**Environment**

 - Browser Chrome 85:
 - React-PDF version 5.0.0:
 - React version 16.10.2:
 - Webpack version 4.41.0:

**Comment by dmanaster** [comment]
Did you ever figure out how to handle this? I am getting the same error.

**Comment by taylorbf** [comment]
I did not fix it.  What I did, for a variety of reasons, was show the PDF one page at a time and I do not show the 'close' controls until the page is loaded.

**Comment by Darono87** [comment]
Have the same issue. Very annoying if you have some quite big pdf-s. Unhandled exception basically crashes the app so it's quite an issue when you want to implement some navigation :)

**Comment by kevinmamaqi** [comment]
I receive this error when I am opening several pages in a modal, for example, and I close it before all are loaded. Is there any way to lazyload on scroll?

**Comment by ioveracker** [comment]
Has anyone come up with a non-blocking solution or workaround for this?

**Comment by landorid** [comment]
I have the same issue too.

**Comment by AmmarMohamadIsmaeel** [comment]
I did not find a solution for the problem, but luckily the crash is happening in the development mode only and not in the production :)

**Comment by zxlin** [comment]
@wojtekmaj This may be relevant https://github.com/mozilla/pdf.js/pull/12144/files

**Comment by TugboatTanner** [comment]
Still getting this error React PDF version 5.2.0

**Comment by sokoloveugene** [comment]
I was able to skip this problem in react-pdf v5.2.0

Try the next steps.
- copy file from node_modules/pdfjs-dist/build/pdf.worker.js to public/pdf.worker.js
- import { Document, Page } from 'react-pdf';
- I did not set any options to "Document" component. 

Check chrome dev tools/task manages. It should use worker from the public folder.

Here is a tutorial I found for react-pdf v4.1.0. 
https://levelup.gitconnected.com/displaying-pdf-in-react-app-6e9d1fffa1a9

**Comment by TugboatTanner** [comment]
> I was able to skip this problem in react-pdf v5.2.0
> 
> Try the next steps.
> 
> * copy file from node_modules/pdfjs-dist/build/pdf.worker.js to public/pdf.worker.js
> * import { Document, Page } from 'react-pdf';
> * I did not set any options to "Document" component.
> 
> Check chrome dev tools/task manages. It should use worker from the public folder.
> 
> Here is a tutorial I found for react-pdf v4.1.0.
> https://levelup.gitconnected.com/displaying-pdf-in-react-app-6e9d1fffa1a9

I'll try this out. Thank you @sokoloveugene!

**Comment by TugboatTanner** [comment]
@zxlin Yeah, it didn't seem to fix my issue either. I did try installing the v5.3.beta.3 version and it seems it's fixed there. At this point I've resigned myself to waiting for 5.3 to be released to fix this

**Comment by zxlin** [comment]
Oh that's promising to hear about v5.3! thanks for the update!

**Comment by wojtekmaj** [comment]
v5.3.0 is now released. Glad to know it helped!

**Comment by renaoliv** [comment]
> 🤔 Not seeing the same results here. On `react-pdf` 5.2.0, if you navigate away from a PDF mid load on slow internet, it'll still throw the following error. No special options, using vanilla sample code
> 
> <img alt="Screen Shot 2021-05-07 at 2 51 10 PM" width="444" src="https://user-images.githubusercontent.com/5447705/117495525-bf2d0380-af43-11eb-86a5-0cfaae5316cb.png">

I'm getting the same error, using the 5.3.0 version... 
does anyone have the solution?

**Comment by melvingm101** [comment]
I am also getting the same error, this time in version 5.6.0. When loading the pdf, if we navigate to a new page or so, it throws this error. Isn't there a way to safely stop loading the pdf worker without causing any errors?

**Comment by goodlana** [comment]
5.7.0 version also has same problem.
why did he close this issue....

**Comment by goodlana** [comment]
If there is anyone still suffered from this issue, just change the import-alias.
I'm using v5.7.3, and it doesn't seem like they solved this issue...
below code saved my life. hope it helps you 😄 

```js
import { Document, Page } from "react-pdf/dist/esm/entry.webpack";
```

from https://github.com/wojtekmaj/react-pdf/issues/729

**Comment by angel-langdon** [comment]
@goodlana solution did not work for me. It only worked when launching the app with `yarn start`. However, when I served the static files of `build` folder with my `FastAPI` backend `PDF` were unable to load

**Comment by nicolasiscoding** [comment]
Sorry for the bump but is there any known solutions to this? Seems as if the issue is stale and have a newer build then what is referenced here. It does not appear to be caught in the onLoadError. 

<img width="398" alt="image" src="https://user-images.githubusercontent.com/9352910/194730875-58eab568-e2f8-49f5-a1ce-0c90ef2ecc4c.png">

<img width="388" alt="image" src="https://user-images.githubusercontent.com/9352910/194730829-0faebdec-06d4-490f-b407-ebeca42f1bfe.png">

![image](https://user-images.githubusercontent.com/9352910/194730846-70f3fb61-94f6-4263-a9ac-7cd1c65c5480.png)

![image](https://user-images.githubusercontent.com/9352910/194730854-580ecd7b-6a70-4abd-98c3-28149ad64049.png)

**Comment by codeWriter6** [comment]
See the same error using v5.7.2, any solution how to resolve?

**Comment by lagroms** [comment]
I also have the same problem on 5.7.2

**Comment by frontendphil** [comment]
We started seeing this in 7.4.0 when running our tests. It almost seems like something is faster now which causes this to kick in.

**Comment by chomamateusz** [comment]
Same issue on 7.6.0

**Comment by AlfredMadere** [comment]
same issue on v9, why is this closed?

**Comment by Jaime02** [comment]
Friendly reminder that this bug is still alive😭

**Comment by tmokmss** [comment]
This seems working.

```ts
import { pdfjs } from 'react-pdf'

const workerUrl = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/build/pdf.worker.min.mjs`

const workerCode = `
self.addEventListener('unhandledrejection', (event) => {
  if (event.reason?.message === 'Worker was terminated') {
    event.preventDefault();
  }
});
await import("${workerUrl}");
`

pdfjs.GlobalWorkerOptions.workerSrc = URL.createObjectURL(
  new Blob([workerCode], { type: 'text/javascript' }),
)
```
