### ISSUE TITLE
How to get page number while scrolling the document?

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-pdf#653]
Is there anyway to get page number while scrolling the document ? I suppose this question is not react-pdf specific. But your experience might help :) @wojtekmaj

_Originally posted by @ffurkAn in https://github.com/wojtekmaj/react-pdf/issues/165#issuecomment-696581312_

**Comment by wojtekmaj** [comment]
Indeed that's not React-PDF specific. Treat React-PDF as img tag for PDFs. How would you do it if you had 10 images displaying pages 1-10?

You would probably use something like IntersectionObserver hooked to these imgs, or, if img height was known, calculate the currently displayed img based on scroll position.

**Comment by ffurkAn** [comment]
Hi @wojtekmaj , I have finally managed to handle pagechange event in my component. However, I needed to modify pure viewer.js a bit. 

Here is my solution:

viewer.js:
`
function webViewerPageChanging(evt) {
  const page = evt.pageNumber;
  PDFViewerApplication.toolbar.setPageNumber(page, evt.pageLabel || null);
  PDFViewerApplication.secondaryToolbar.setPageNumber(page);

  if (PDFViewerApplication.pdfSidebar.isThumbnailViewVisible) {
    PDFViewerApplication.pdfThumbnailViewer.scrollThumbnailIntoView(page);
  }

  if (typeof Stats !== "undefined" && Stats.enabled) {
    const pageView = PDFViewerApplication.pdfViewer.getPageView(page - 1);

    if (pageView && pageView.stats) {
      Stats.add(page, pageView.stats);
    }
  }

    const event = document.createEvent("CustomEvent");
    event.initCustomEvent("pagechanged", true, true, {
        source: window
    });

    try {
        parent.document.dispatchEvent(event);
    } catch (ex) {
        console.error(`pagechanged: ${ex}`);
        document.dispatchEvent(event);
    }

}
`

MyReactComponent:
`
 // Add an event listener to page changed in pdfjs
        document.addEventListener("pagechanged", () => {
            // get the current page and brodcast
            var currentPageNumber = getCurrentPageNumber();
            if (currentPageNumber != null && this.state.isControlPresentationChecked) {
                this.props.onChangeCurrentPageNumberOnShareDocument(currentPageNumber);
            }
        });
`

**Comment by bhargawananbhuyan** [comment]
How to access the page number on scroll? I know it's not the library specific. But has anyone implemented it?
