### ISSUE TITLE
Can't perform a React state update on an unmounted component. Reported as bug #328

### ISSUE THREAD

**Issue by DragomirRhv** [wojtekmaj/react-pdf#654]
**Before you start - checklist**

 - [Yes] I have read documentation in README
 - [Yes] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [Yes and it was reported as a bug #328 ] I have checked if this question is not already asked

It looks like this issue is not solved or I am doing something wrong. 
In the example code multiple quick clicks to PrevPage/NextPage buttons create warning messages. (if buttons are pressed in slower intervals there are no warning/error messages).

**Additional information**
![Screenshot at 2020-09-22 01-17-21](https://user-images.githubusercontent.com/52378777/93931379-65b2f400-fd27-11ea-86cf-41b14e3c275e.png)

Example code for my pdf wrapper:
```
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';

export default function PDFWrapper({ data, onDocumentLoadSuccess, pageNumber }) {

  return (
    <Box
      className={classes.documentWrapper}
    
      <Box id="pdfWrapper" style={{ width: '100%', padding: '60px 0px' }} ref={pdfWrapper}>
        <Document
          className={classes.pdfDocument}
          file={data}
          onLoadSuccess={onDocumentLoadSuccess}
          noData=""
          loading=""
        
          <Page pageNumber={pageNumber} loading=""  />
        </Document>
      </Box>
    </Box>
  );
}
```

Example code for my pdf for desktop:
```
import React, { useState } from 'react';
import PDFWrapper from '../PDFWrapper';

export default function PDFViewerDesktop({ data }) {
  const [numPages, setNumPages] = useState(0);
  const [pageNumber, setPageNumber] = useState(1);
  const classes = useStyles();

  // eslint-disable-next-line no-shadow
  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  function setPreviousPage() {
    setPageNumber((prevPageNumber) => prevPageNumber - 1);
  }

  function setNextPage() {
    setPageNumber((prevPageNumber) => prevPageNumber + 1);
  }

  return 
      <AppBar
        position="fixed"
        className={classes.appBar}>
      
          <Box className={classes.navMenu}>
            <Button
              id="prevPage"
              className={clsx(classes.navButton, classes.prevButton)}
              disabled={pageNumber <= 1}
              onClick={setPreviousPage}>
    
              <ArrowLeftIcon className={classes.arrowIcon} />
              <Typography className={classes.pdfPages}>Previous</Typography>
            </Button>
            <Box className={classes.boxPages}>
              <Typography className={classes.pdfPages}>
                Page
                {' '}
                {pageNumber}
                {' '}
                of
                {' '}
                {numPages}
              </Typography>
            </Box>
            <Button
              id="nextPage"
              className={clsx(classes.navButton, classes.nextButton)}
              disabled={pageNumber >= numPages}
              onClick={setNextPage}>
  
              <Typography className={classes.pdfPages}>Next</Typography>
              <ArrowRightIcon className={classes.arrowIcon} />
            </Button>
          </Box>
        </Toolbar>
      </AppBar>
      <main className={classes.content}>
        <PDFWrapper data={data} onDocumentLoadSuccess={onDocumentLoadSuccess} pageNumber={pageNumber} />
      </main>
```

**Environment**
Browser: Chrome latest, Firefox latest
React-PDF version: 5.0.0
React version: 16.12.0
Webpack version: 4.42.0

**Comment by rpellerin** [comment]
I am affected too.

**Comment by wojtekmaj** [comment]
Does this still occur in 5.4.0?

**Comment by wojtekmaj** [comment]
I would need to look at your code to tell what's wrong. Please create code sandbox.

**Comment by asurmenev** [comment]
@wojtekmaj, thank you for your quick reply. I managed to solve it by updating @react-pdf/renderer to the latest version (I use it to generate PDFs). Though I'm still not quite sure what was causing the issue because it works as it should in the sandbox.
In any case, if anyone is struggling to preview PDFs generated using @react-pdf/renderer in Next API Routes, I just leave the code that finally works for me [here](https://codesandbox.io/s/agitated-chaum-1303p).

**Comment by wojtekmaj** [comment]
Oh, looks like you're in a completely wrong repo.

**Comment by asurmenev** [comment]
No-no. There was no issue with generating a pdf, but with switching pages while previewing what was generated :) I just use react-pdf and @react-pdf/renderer together
