### ISSUE TITLE
How to prevent multiple renders

### ISSUE THREAD

**Issue by pedro-surf** [wojtekmaj/react-pdf#656]
**Before you start - checklist**

 - [ x ] I followed instructions in documentation written for my React-PDF version
 - [ x ] I have checked if this bug is not already reported
 - [ x ] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [ x ] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Everytime I change anything in my app, React-PDF render process is triggered again, need to prevent this somehow

**Steps to reproduce**

I render Document as following:

`   

         onLoadSuccess={({ numPages }) => setNumPages(numPages)}

         noData={<Loader />}

         file={{ data }}

         options={docOptions}

         >
              {Array.from(new Array(numPages), (el, idx) => (
                <div
                  className="border"
                  key={`page_container_${idx + 1}`}
                >
                  <Page
                    key={`page_${idx + 1}`}
                    scale={currentZoom}
                    pageNumber={idx + 1}
                    customTextRenderer={makeTextRenderer(searchText)}
                    onGetAnnotationsSuccess={(a) => loadFileAnnotations(a)}`

**Expected behavior**

I would like to prevent multiple renders, it's happening constantly

**Environment**

 - Browser: Electron 9.2
 - React-PDF version: latest
 - React version: CRA latest

**Comment by rootlinux2** [comment]
Hi @pedro-surf I think your problem is with the key `key={`page_container_${idx + 1}`}` you are using the index of the array as part of the key. each time you refresh your app your array will be generated and the index will change this implies the key for the page will be different each time. Here there is [documentation](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md) talking about

**Comment by wojtekmaj** [comment]
I think `key` is fine in this specific use case, in which it will remain constant when loaded. Your problem is `file={{ data }}`. This is a bad idea. `file` prop would effectively change with every render, which will cause `Document` to reload the file.

**Comment by wojtekmaj** [comment]
See https://github.com/wojtekmaj/react-pdf/issues/308#issuecomment-443538284.
