### ISSUE TITLE
Version 5: Document > Prevent subsequent "loading" indicators?

### ISSUE THREAD

**Issue by joncursi** [wojtekmaj/react-pdf#658]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Let's say I have the following setup:

```jsx
const SomeComponent = () => {
  const [file, setFile] = React.useState(null);

  return (
    <>
      ...
      {file && (
        <Document file={file}>
          <Page ... />
        </Document>
      )}
      ...
    </>
  );
};
```

In version 4, the loading indication for `Document` would only be triggered when the first `file` is set (via `setFile()`). This produced a UX that we liked, because when the `file` changes, PDF.js will re-fetch behind the scenes and show the new file once the fetch had been completed. The old file would still be visible while the new file is being fetched. No UX jank of showing the loading indication between file renders.

However in version 5, this UX has been changed. When the `file` changes, the loading indication gets triggered, so the old file disappears during fetch, and a loading indication appears between `file` renders now.

Is it possible to prevent this / to achieve the old behavior and UX? Even if it is not desirable to support this at the library level, is there something I can do in my app code to do it?

**Comment by wojtekmaj** [comment]
Hm, I was not aware of this side effect actually.

What I would do is load new file in separate `<Document>` (remember about `key`s!!!), hide it behind the old one, and only remove the old one once the new one is fully loaded (`onLoadSuccess`) and rendered (`onRenderSuccess`).
