### ISSUE TITLE
Certain emojis appear cut off/condensed

### ISSUE THREAD

**Issue by alliyfrauenpreis** [wojtekmaj/react-pdf#662]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Certain flag emojis display cut off with a green top border.

**Steps to reproduce**

1. Visit the emoji example Repl (https://react-pdf.org/repl?example=emoji) or set up a local react-pdf implementation
2. Register an emoji source using the URL provided in the documentation (https://twemoji.maxcdn.com/2/72x72/)
3. Add an emoji for the flag for France, Italy, or Greece to a page in the PDF document, wrapped in `<Text>`

**Expected behavior**

Flag emojis display consistently, at full size.

**Additional information**

Here is an example of the bug occurring in the Repl. Only certain flags have this problem. Unsure if this is a Twemoji issue or a React-Pdf issue, but the Twemoji example HTML file does not show this version of those flags.

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/8595926/95528208-4e614100-098c-11eb-9f69-3d8dfc271106.png">

**Environment**

 - Chrome  85.0.4183.121, Firefox 81.0.1
 - React-PDF 1.6.10

**Comment by wojtekmaj** [comment]
Wrong repository, React-PDF is not creating PDFs, it's reading and displaying them.

**Comment by alliyfrauenpreis** [comment]
Got it, thank you!
