### ISSUE TITLE
Invalid parameter object: need either .data, .range or .url

### ISSUE THREAD

**Issue by DonovanTT** [wojtekmaj/react-pdf#665]
I am trying to render a PDF that I have retrieved from a MongoDB collection. I’ve read the documentation, and it seems like the way for me to go is going to be rendering with a Uint8Array. I'm using Chrome and I'm on React 16.13.1 and React-PDF 5.0.0.

I’ve gotten React-PDF to work just fine when attempting to render a PDF from a file or from a URL, but it doesn’t seem to want to work when I use a Uint8Array. 

The following code will simultaneously console log the Uint8Array and fail to render a PDF with it:

```js
<Document file={file.data} onLoadSuccess={console.log("Here's the Uint84Array you asked for...",file)}>
     <Page pageNumber={1} />
</Document>
```

This is the error I get:

```
Error: Invalid parameter object: need either .data, .range or .url
```

This is the file object:

```
{type: "Buffer", data: Array(158)}
     data: (158) [158, 0, 0, 0, 2, 110, 97, 109, 101, …]
     type: "Buffer"
     __proto__: Object
```

Now, I looked at the documentation, and it seems that I need to pass an object instead of just the array by itself, and the file object I’m passing through doesn’t work. Based on the README, it looks like I need an object with parameters URL, data, range, httpHeaders, and withCredentials. It also indicates that I need to memoize the file object.

Because my PDF is coming from the database, it doesn’t have a URL, at least to the best of my knowledge. I’m also not sure what I would put in for range, and I think I would prefer to leave httpHeaders and withCredentials blank for now if that is possible.

I also don’t know what memoizing even is. Should I familiarize myself with Hooks?
Please let me know if I’m on the right track or if there would be a better way for me to go about doing this.

Thank you!

PS Sorry I don't know how to make my code pretty for ya.

**Comment by wojtekmaj** [comment]
> Error: Invalid parameter object: need either .data, .range or .url

Passing an object to `file` requires it to have one of these parameters. So pass `{ data: <your data here> }` object to `file` instead.

> I also don’t know what memoizing even is. Should I familiarize myself with Hooks?

Depending on where you got the data from, you could either set it in component state, or indeed familiarize yourself with hooks, useMemo specifically. `file={{ data: … }}` is a bad idea.

**Comment by cameronridderikhoff** [comment]
Hello wojtekmaj, I am doing something similar, and was wondering why doing `file={{ data: myData }}` is a bad idea? I don't fully understand how useMemo works (or when to use it), but when I looked up how to use it, I found this blog post: [https://blog.logrocket.com/rethinking-hooks-memoization/](url) that says that one should only use useMemo for computationally expensive operations.

Could you please elaborate?

**Comment by wojtekmaj** [comment]
See https://github.com/wojtekmaj/react-pdf/issues/308#issuecomment-443538284 for explanations on why it's a bad idea.

**Comment by alizarei22** [comment]
Hello wojtekmaj, I call my PDF using an API which returns me a byte array
I give the byte array to 
` <Document
          file={pdf}
          onLoadSuccess={onDocumentLoadSeccess}
          onContextMenu={(e) => e.preventDefault()}
          className="pdf-container"
        >`
 but I have the error 
`Error: Invalid parameter object: need either .data, .range or .url`
 I tried different methods but it didn't work.
Sample byte array that I get from the server:
`JVBERi0xLjQNCiW1tbW1DQoxIDAgb2JqDQo8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFIvTGFuZyhlbi1VUykgL1N0cnVjdFRyZWVSb290IDEwNyAwIFIvTWFya0luZm88PC9NYXJrZWQgdHJ1ZT4+L091dHB1dEludGVudHNbPDwvVHlwZS9PdXRwdXRJbnRlbnQvUy9HVFNfUERGQTEvT3V0cHV0Q29uZGl0aW9uSWRlbnRpZmllcihzUkdCKSAvUmVnaXN0cnlOYW1lKGh0dHA6Ly93d3cuY29sb3Iub3JnKSAvSW ...`
Please guide me

**Comment by Anhaachan** [comment]
@alizarei22 Did you tried `<Document file ={{data : pdf}}...`

**Comment by alizarei22** [comment]
Yes i did, but i found a solution
`          file={`data:application/pdf;base64,${YOUR_BASE64_CONTENT}`}
`
this is work for base64

**Comment by Anhaachan** [comment]
Do you mind give some your code. how fetches data etc. i am sending bytes (or binary data ) literally from my backend. but can't handle it in frontend.

**Comment by alizarei22** [comment]
i have 2 suggestion for you, first you check your base64 code with online tools and ensure that the server side and your response is true, second is ensure that your byteArray is not in the string and be sure to `.parse` your response.

in my app i just give byteArray (Base64) from the server and keeping in variable and then use like this:
`
        <Document
          file={`data:application/pdf;base64,${pdf}`}
          onLoadSuccess={onDocumentLoadSuccess}
          onContextMenu={(e) => e.preventDefault()}
          className="pdf-container"
        >
          <Page pageNumber={pageNumber} />
        </Document>
`

**Comment by Anhaachan** [comment]
Thanks for the suggestion dude. But it works another way. I used `useMemo` and pass it to `file`. it worked somehow. Now i got new error. That everytime i resize my screen then instantly fall this error `Uncaught TypeError: Cannot read properties of null (reading 'sendWithPromise')`. I searched whole internet and couldn't find solution.
