### ISSUE TITLE
Expose page canvas ref

### ISSUE THREAD

**Issue by SamuelMS** [wojtekmaj/react-pdf#666]
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

Currently, there's no convenient way to access the internal canvas ref on the `Page` element – even though this would be extremely helpful for rendering additional content on top of the PDF that is loaded and is scrollable at the same time.

Quick example – imagine you've developed a machine learning pipeline that extracts the text of a document (OCR, NLP, etc), then runs a model to highlight relevant clauses of a legal document for review. We can use this library to render the PDF quickly and efficiently, but it's inconvenient to superimpose bounding boxes for these highlights on the PDF without direct access to the existing canvas element.

**Describe the solution you'd like**

The `Page` element supports both a `ref` and an additional `inputRef` for the `<div>` *around* the `<canvas>` element. I propose adding a third property, `canvasRef`, so that applications can render additional content on top of the PDF without needing to worry about scroll performance / syncing, conflicting mouse events, etc.

**Describe alternatives you've considered**

We work around this by creating a new, second `<canvas>` element that sits on top of the existing one and rendering application content there, but this is inconvenient and less performant.

**Comment by SamuelMS** [comment]
I'm happy to work on a PR for this if you agree with the direction.

**Comment by wojtekmaj** [comment]
I think that's a good idea! Implemented in #668.
