### ISSUE TITLE
PDF rendering every second time

### ISSUE THREAD

**Issue by joensuua** [wojtekmaj/react-pdf#667]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I have react-pdf running on a div. It receives its PDF files as base64 props. These props come by clicking on separate menu on another div in another React Component. When I load the page and click on a button, the PDF is rendered fine. Console says: `Warning: Indexing all PDF Objects` from `bundle.worker.js`. If I now click on another button pointing to another base64 PDF, it never finishes loading (says'Loading PDF...'. Console says nothing. If I click the same button again, nothing changes. Now if I click on another button, it renders correctly. Console again says: `Warning: Indexing all PDF Objects`. This thing happens every second time. Every second re-render it hangs on loading, and every second re-render it works correctly. Any idea what's going on?

**Describe solutions you've tried**

I've tried `Page` props: 
- `onLoadSuccess`. Is called only when re-rendering happens
- `onLoadError`, it is never called
- `onLoadProgress`, it's called every time
- `noData`, it is never called.

Could the problem be in the worker somehow, as it has some correlation with the occurrence of this problem?

**Environment**

 - React-PDF version: 5.0.0
 - React version: 16.13.1

**Comment by vishalsureify** [comment]
@wojtekmaj Can you comment on that, I am also getting a similar issue.

**Comment by Raftos18** [comment]
Me too, I have exactly the same error

**Comment by wojtekmaj** [comment]
Can you share the code on CodeSandbox or as a snippet here?

**Comment by joensuua** [comment]
Unfortunately I have moved on to using other libraries on this subject, and don't have the code anywhere as it was. Perhaps the other commenters can share, as their issues have occurred more recently.

**Comment by Raftos18** [comment]
In my case it is like this. A component that uses the lib
```javascript
export default function DocumentPreview(props) {
  const [file, setFile] = React.useState(props.file);
  const [numPages, setNumPages] = React.useState(null);

  const options = {
    cMapUrl: 'cmaps/',
    cMapPacked: true
  };

  function onFileChange(event) {
    setFile(event.target.files[0]);
  }

  function onDocumentLoadSuccess({ numPages: nextNumPages }) {
    setNumPages(nextNumPages);
  }

  return (
    <div>
      <Document
        file={file}
        onLoadSuccess={onDocumentLoadSuccess}
        options={options}
        >
        {Array.from(new Array(numPages), (el, index) => (
          <Page key={`page_${index + 1}`} pageNumber={index + 1} />
        ))}
      </Document>
    </div>
  );
}
```

And the snippet that uses it
```javascript
<div className={classes.root}>
        <AppBar position="static">
          <Tabs
            className="tabs"
            value={this.state.value}
            onChange={this.handleChange}
            aria-label="Documents">
            {this.state.files.map((f, i) => {
              return (
                <Tab key={i} label={`Document ${i + 1}`} className="tab" />
              );
            })}
          </Tabs>
        </AppBar>
        {this.state.files.map((f, i) => {
          return (
            <DisplayDocument
              key={i}
              index={i}
              value={this.state.value}
              file={f}
              onDownloadClick={this.handleDownloadClick}
              onShareClick={this.handelShareClick}
            />
          );
        })}
      </div>
```
