### ISSUE TITLE
Support get the size of the pdf when Pdf loaded?

### ISSUE THREAD

**Issue by PayamSiami** [wojtekmaj/react-pdf#669]
hello,

is there a way to find page size like A3, A4, A5 ..., in react pdf?

thank you!
payam

**Comment by chihhungl** [comment]
You can pass `onLoadSuccess` callback as a prop to `<Document />` component. The input parameter of your callback will be an object containing the information about this pdf. Then you can call `getPage(pageIndex)` which will return a promise that contains the page information.
Something like:
```javascript
```

**Comment by chihhungl** [comment]
You can pass `onLoadSuccess` callback as a prop to `<Document />` component. The input parameter of your callback will be an object containing the information about this pdf. Then you can call `getPage(pageIndex)` which will return a promise that contains the page information.
Something like:
```javascript
import { Document } from 'react-pdf';

// In your react component

handleLoadSuccess = async (pdfObject) => {
  // If you want to get the dimension for page 1 (1-indexed)
  const page = await pdf.getPage(1);
  console.log(page.width);
  console.log(page.height);
};

render() {
  <Document
    onLoadSuccess={handleLoadSuccess}
    // Other props
  />
};
```
Once you get the height/width, you'll be able to figure out if it's A3, A4, A5 or letter.

Similarly you can also pass your callback as the `onRenderSuccess` for `<Page />` component. In that case, the parameter you'll get in your callback is _page_  as oppose to the pdf.
Watch out for rotation too as you may need to flip the width and height, and an issue here for a small set of pdfs: https://github.com/wojtekmaj/react-pdf/issues/672

**Comment by PayamSiami** [comment]
thanks

**Comment by j-perl** [comment]
It seems that height and width are not accessible anymore on the page object obtained through getPage. Have they been removed ?

**Comment by wojtekmaj** [comment]
Just tested that and you can totally still get width and height from page object obtained from `pdf.getPage`.

<img width="575" alt="image" src="https://user-images.githubusercontent.com/5426427/159092984-00c7a9a0-e14b-43b8-81de-ee2799879e19.png">

**Comment by psychopatt** [comment]
> It seems that height and width are not accessible anymore on the page object obtained through getPage. Have they been removed ?

Just hit the same problem. Using typescript, `await document.getPage(1)` yields a `PdfPageProxy`, which doesn't have width and height. 
Thanks @j-perl for the `view` hint.

**Comment by wojtekmaj** [comment]
Check out the code we're using to expose these handy attributes in React-PDF callbacks:

https://github.com/wojtekmaj/react-pdf/blob/7740ef6d446b50d71c25a979586c315b54175f0c/src/shared/utils.ts#L112-L135

So, width is just `page.view[2]`, and height is `page.view[3]`, if rendered at default scale.
