### ISSUE TITLE
Scale moves position of the document.

### ISSUE THREAD

**Issue by mawais78** [wojtekmaj/react-pdf#670]
I'm working on the react-pdf and it worked fine and all of my use cases were covered but the only issue I'm facing is when I change the scale after loading the document it scrolls up or down. For example, if I zoom in it scrolls up and when I zoom out it scrolls down.

Can anyone help me why is this happening and how can I resolve this?

**Comment by KingAmo** [comment]
@mawais78  how to zoom and pinch? could you help me please?

**Comment by Loctary** [comment]
any updates on this?
