### ISSUE TITLE
html page content blink when change PDF page

### ISSUE THREAD

**Issue by rootlinux2** [wojtekmaj/react-pdf#671]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Each time I change the PDF page the content around (Section Up, section Down) the PDF blink. on Google Chrome the problem is bigger than Mozilla Firefox 

What did you expect to happen?

I expect the PDF change pages without affecting its height 

**Environment**

 - Browser [Chrome 86, Firefox 81]:
 - React-PDF version [4.2.0]:
 - React version [16.13.1]:
 - GatsbyJS version [2.24.73]

**Comment by ssjunior** [comment]
Same here...

**Comment by wojtekmaj** [comment]
Check https://github.com/wojtekmaj/react-pdf/issues/308 - it might help. Can't tell for sure since you provided no code for reproduction.
