### ISSUE TITLE
API version "2.0.943" does not match the Worker version "2.5.207

### ISSUE THREAD

**Issue by sandhyakhadakhade** [wojtekmaj/react-pdf#674]
UnknownErrorException {name: "UnknownErrorException", message: "The API version "2.0.943" does not match the Worker version "2.5.207".", details: "Error: The API version "2.0.943" does not match the Worker version "2.5.207"."}
details: "Error: The API version "2.0.943" does not match the Worker version "2.5.207"."
message: "The API version "2.0.943" does not match the Worker version "2.5.207"."
name: "UnknownErrorException""

Getting this error while using react-pdf

**Comment by wojtekmaj** [comment]
Looks like you imported worker file from an external source incorrectly or your build process didn't update it properly if you're hosting it yourself.
