### ISSUE TITLE
Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

### ISSUE THREAD

**Issue by yudongli413301** [wojtekmaj/react-pdf#677]
**Before you start - checklist**

 - [ ] I followed instructions in documentation written for my React-PDF version
 - [ ] I have checked if this bug is not already reported
 - [ ] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Short description of the bug you encountered.

**Steps to reproduce**

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

What you expected to happen?

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by yudongli413301** [comment]
1.lastest version
2.Document file params is base64

**Comment by Tingwei-Justin** [comment]
same error

**Comment by ennerlopez** [comment]
same error here too!

**Comment by tomhands1** [comment]
Same error. Has this been resolved?

**Comment by tomhands1** [comment]
I have added this to my componentDidMount and it has fixed the issue. In their ReadMe docs.
https://github.com/wojtekmaj/react-pdf#standard-browserify-and-others

**Comment by aguspray001** [comment]
Testing:
s

- asdawd

**Comment by Nataliasem** [comment]
I use Pdfjs v2.8.335 with legacy supporting in this way:

import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf'
import PDFJSWorker from 'pdfjs-dist/legacy/build/pdf.worker.entry'

pdfjsLib.GlobalWorkerOptions.workerSrc = PDFJSWorker

**Comment by jarommadsen** [comment]
Following the [webpack instructions](https://github.com/wojtekmaj/react-pdf#webpack) worked for me.

`import { Document } from 'react-pdf/dist/esm/entry.webpack';`

**Comment by itxshakil** [comment]
Fixed by adding folowing code(WORKING ON ALL PAGES)
```
import { pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js`;
```

Read Detail here : [https://github.com/wojtekmaj/react-pdf#standard-browserify-and-others](https://github.com/wojtekmaj/react-pdf#standard-browserify-and-others)


Surprisingly I was using earlier (WORKING ON SOME PAGE)
```
import { pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc ='pdf.worker.min.js';
```
It worked on one page but not on other.

Preety weird.

**Comment by AlphonseRDSouza** [comment]
> Just updated from v4 to v5 and got this error. Following the [webpack instructions](https://github.com/wojtekmaj/react-pdf#webpack) worked for me.
> 
> `import { Document } from 'react-pdf/dist/esm/entry.webpack';`

Thanks a ton, this worked for me. I have updated 
   `"react-pdf": "^5.5.0"` from "^4.1.0",
