### ISSUE TITLE
Document.componentWillUnmount() causes loading issue when working with 2 Documents

### ISSUE THREAD

**Issue by fsommers** [wojtekmaj/react-pdf#679]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I have 2 Documents in an app. Essentially, I need to present two completely different views of the same PDF that the user can toggle. Since these views are very different, I defined 2 components that each contain a Document, and then there's a parent that allows the user to toggle between the 2 views. Simple stuff. Some as follows:

```
function Component 1 = ({ documentURL }) => {
  return <div>
   <Document....file={documentURL}... />
 </div>
}

// In a separate file
function Component2 = ({ documentURL }) => {
  return <div>
   <Document....file={documentURL}... /> // very different way to render pages
 </div>
}

// A parent that allows toggling between the two Documents
function Parent = () => {
const documentURL .... 
const [toggle, setToggle] = useState(false)

return toggle ? <Component1 documentURL={documentURL}/> 
                           :  <Component2 documentURL={documentURL}/>
}

```

The first view to load and render the document has no problems. However, when the user switches to the second view, the document loading gets halted. Upon some debugging, I found that the following expression does not return in Document:

`const pdf = await cancellable.promise;`

https://github.com/wojtekmaj/react-pdf/blob/c3af32ac34bdc7db81b98db4d36c0dd70a5e4943/src/Document.jsx#L119

It just keeps awaiting the promise forever. 

Even if I switch the 2 document view order, the same thing happens upon the second rendering.

**Describe solutions you've tried**

Having looked around the code a bit, I found that when the second Document component renders and loads the PDF, the `PDFDocumentLoadingTask`'s `_transport` field becomes null.

I see that the Document's `componentWillUnmount()` includes a call to `loadingTask.destroy()`, which ultimately sets the `_transport` to null. When I comment out the following line, the problem I'm describing disappears and both Documents render correctly (in Document's componentWillUnmount()): 

`if (this.loadingTask) this.loadingTask.destroy();`

Obviously, there is a reason `loadingTask.destroy()` is called on unmount, but I'm not sure why. 

Further, I'm not sure how and why these 2 Documents interact - they are defined as 2 separate components, with independent lifecycles.

Any help would be appreciated.

Thank you.

**Environment**

 - Browser (if applicable) Chrome, Safari
 - React-PDF version: 5.0.0
 - React version: 16.13.1

**Comment by thiagopsnfg** [comment]
same problem here

**Comment by fsommers** [comment]
Any update on this? I wonder if others encountered this too. Thanks.

**Comment by Graymark** [comment]
i have the same problem by updating my list with a filter. On the first rendering, every Document loads well, but after changing the Document list, react-pdf is unable to load the new documents List.

**Comment by bnewcomer** [comment]
I encountered this issue upgrading from `4.1.0` to `4.2.0`. 

My application has two views which each have their own `<Document />` instance. When switching directly from one view to the other React appears to be mounting the second `<Document />` instance before unmounting the first. When the first instance is unmounted it destroys the `loadingTask` (and the worker that is shared between both instances) which causes the second `<Document />` instance to never finish loading.

I am able to work around the issue in this case by putting a delay, `window.setTimeout(openSecondInstance, 0)`,  in the transition from one instance to the next to ensure that React unmounts the first instance before mounting the second instance. However, my app has other usages of multiple `<Document />` components and it's not possible to implement this workaround in all of them.

**Environment**

Browser (if applicable) Chrome
React-PDF version: 4.2.0
React version: 16.13.0

**Comment by Raftos18** [comment]
Having the same problem, setTimeout did not seem to fix it for me.

**Comment by oli-gra** [comment]
Similar problem loading a new <Document> instance from thumbnail <Document>s.

**Comment by wojtekmaj** [comment]
In this case, I would suggest adding `key` to your components to hint to React to completely remove the previous Document and create a new Document instance from scratch.
