### ISSUE TITLE
display PDF in full screen

### ISSUE THREAD

**Issue by nnals** [wojtekmaj/react-pdf#68]
hello,

is there a more convenient way to display a PDF in full screen than to calculate the width based on the file's aspect ratio and the window size?

thank you!
nicolai

**Comment by wojtekmaj** [comment]
Hey @nnals. React-PDF is only a "bridge" between Mozilla's PDF.js and React enabling you to use it with little to no configuration. React-PDF does not provide UI or really any features intended for end user. I plan to make such thing in the future, but for now, you will need to figure that out yourself.
