### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by wasyster** [wojtekmaj/react-pdf#680]
HI

I am using react with typescript and I cant get this to work.
I have a form component where I want to display the selected pdf file.
The file got loaded, I got the File variable data. I tried to pass it is as a File to a Document file property, tried it to convert to base64 string, but always got the error:

Uncaught SyntaxError: Unexpected token '<'
Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".

I put here my relevant code

```js
    const [image, setImage] = useState<string>();
    const [imageFile, setImageFile] = useState<File>();

    const [pdfFile, setPdfFile] = useState<File>();
    const [pdf, setPdf] = useState<string>();

    const [pageNumber, setPageNumber] = useState<number>(1);
    const [numPages, setNumPages] = useState<number>();

const onPdfPickHandler = (e: React.FormEvent<HTMLInputElement>): void =>
    {
        if (e.currentTarget.files?.item(0) )
        {
            const file = e.currentTarget.files.item(0);
            setPdfFile(file!);

            fileToPDF(file!);
        }
    }

const fileToPDF = async (data: File): Promise<void> =>
    {
        const reader = new FileReader();
        reader.readAsDataURL(data);
        reader.onload = async () =>
        {
            setPdf(reader.result as string);
        }
    }
{
                                            pdf && <React.Fragment>
                                                <Document file={pdf}
                                                          onLoadSuccess={ (e) => onDocumentLoadSuccess(e)}>
                                                    <Page pageNumber={pageNumber} />
                                                </Document>
                                                {numPages && <p>Page {pageNumber} of {numPages}</p>}
                                            </React.Fragment>
                                        }
```

**Comment by wasyster** [comment]
this worked for me

import { Document, Page, pdfjs   } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

**Comment by wojtekmaj** [comment]
See https://github.com/wojtekmaj/react-pdf/issues/97 and [others](https://github.com/wojtekmaj/react-pdf/issues?q=Uncaught+SyntaxError%3A+Unexpected+token+%27%3C).

**Comment by olefrank** [comment]
> this worked for me
> 
> ```js
> import { Document, Page, pdfjs   } from "react-pdf";
> pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
> ```

Oh boy, this is ugly 🤮
