### ISSUE TITLE
How to get page width and height in which it is rendered...?

### ISSUE THREAD

**Issue by akbar1214** [wojtekmaj/react-pdf#682]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.

**Describe solutions you've tried**

Describe solutions you've already tried, if any. Make sure to include code samples if you're stuck on implementation.

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by wojtekmaj** [comment]
In `Page`'s `onLoadSuccess` you get access to `page` object which contains width and height, both rendered at scale and the original.
