### ISSUE TITLE
How to print the rendered PDF?

### ISSUE THREAD

**Issue by Anenth** [wojtekmaj/react-pdf#69]
Any idea how to print the pdf?

**Comment by wojtekmaj** [comment]
Hey @Anenth,
just like you would handle printing any other page. <canvas> kinda behaves like <img> so it shouldn't be an issue.

Please mind that React-PDF is only a "bridge" between Mozilla's PDF.js and React enabling you to use it with little to no configuration. React-PDF does not provide UI or really any features intended for end user. For now, you need to scale the page to your liking on your own.
