### ISSUE TITLE
Digital Signature Not Showing

### ISSUE THREAD

**Issue by CervarlCG** [wojtekmaj/react-pdf#691]
Hi, i like know if there is support to digital signature?
Actually i try to render a PDF but the signature is not rendering.

**Comment by GoranStoyanov** [comment]
I am facing the same problem. The solution I found is commenting out this piece of code in of `pdf.worker.js`, part of `pdfjs-dist` package:

```javascript
if (data.fieldType === "Sig") {
      data.fieldValue = null;
      this.setFlags(_util.AnnotationFlag.HIDDEN);
}
```

It works but I am not sure if that's the best way to show the signatures :)

**Comment by wojtekmaj** [comment]
It looks like Mozilla PDF.js team has decided not to implement this annotation feature just yet. A comment around this block explains more:

https://github.com/mozilla/pdf.js/blob/4ba28de2608866dcb10d627d77dc19ff3d017c17/src/core/annotation.js#L995-L1002

Given that, we won't be able to do anything about it until Mozilla implements Sig annotation support. Sorry about that.

**Comment by axl-axl** [comment]
> I am facing the same problem. The solution I found is commenting out this piece of code in of `pdf.worker.js`, part of `pdfjs-dist` package:
> 
> ```js
> if (data.fieldType === "Sig") {
>       data.fieldValue = null;
>       this.setFlags(_util.AnnotationFlag.HIDDEN);
> }
> ```
> 
> It works but I am not sure if that's the best way to show the signatures :)


hi, what`s version you use. I use react-pdf@4.2.0 and commenting out this piece of the code, but it not work

**Comment by fabrii** [comment]
@wojtekmaj 

The new version of pdf.js now supports signature display: https://github.com/mozilla/pdf.js/releases/tag/v2.9.359
Does react-pdf have plans of upgrading in the near future? Thanks

**Comment by wojtekmaj** [comment]
That's not a new version. That's an unstable pre-release. Once they actually release a new version I'm usually not far behind.

**Comment by babytiger0929** [comment]
> @wojtekmaj
> 
> The new version of pdf.js now supports signature display: https://github.com/mozilla/pdf.js/releases/tag/v2.9.359
> Does react-pdf have plans of upgrading in the near future? Thanks
Supporting digital signature visualization will be very great!!!

**Comment by wojtekmaj** [comment]
Support for Sig type has been added in [v5.4.0-beta.2](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.4.0-beta.2).

**Comment by babytiger0929** [comment]
Thank you very much. It works properly for me.

**Comment by duylinhdang1998** [comment]
How to display it @wojtekmaj ? thanks
