### ISSUE TITLE
Unhandled Rejection (AbortException): Worker was terminated.

### ISSUE THREAD

**Issue by samebt15** [wojtekmaj/react-pdf#692]
There is a problems with rendering pdf files, I have to resize the page so that the file appears, otherwise eternal download. And there is a solution of this problem here https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js
You need to add code from this compatibility.js file to pdfjs-dest/lib/shared/compatibility.js and pdf files will be rendering normal

**Comment by samebt15** [comment]
Problem was on my webpack

**Comment by 957739315** [comment]
Excuse me, what is the problem on your webpack ? I also encountered the same problem.

**Comment by samebt15** [comment]
> Excuse me, what is the problem on your webpack ? I also encountered the same problem.

So now I don't sure that the problem was in my webpack. I thought so, cause my friend didn't have any problems with his own webpack (my webpack was made not by me). So that, after some manipulations, the pdf reader worked normally, but i don't remember what exactly I did, sry. It was hard and long(
