### ISSUE TITLE
It is not opening in IE11 it throws WeakSet undefined error

### ISSUE THREAD

**Issue by AnjaliPatodia** [wojtekmaj/react-pdf#693]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Short description of the bug you encountered.

**Steps to reproduce**

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

What you expected to happen?

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:
![Weakset](https://user-images.githubusercontent.com/57519075/101760164-8574df80-3b00-11eb-950f-179f21cfcf8e.png)

**Comment by wojtekmaj** [comment]
You didn't fill required information on versions. Please do that and I'll review your issue.

**Comment by AnjaliPatodia** [comment]
My issue is : after include the package my application is not loaded on IE11 at all . It break at chunck.js level .I mean chunck.js is not able to load properly to load or start the application

**Comment by wojtekmaj** [comment]
Ah, I see. [v5.0.0](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.0.0) does not support IE11 anymore. You'll need to stick to v4.x if you still need to support IE11.
