### ISSUE TITLE
PDF not rendering in IE 11

### ISSUE THREAD

**Issue by anusha-bhat-roostify** [wojtekmaj/react-pdf#696]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I have a base64 content which I want to render. 
I have prepended "data:application/pdf;base64," to it and passing it to file prop of Document. 
It is getting rendered correctly in chrome and firefox. However, in IE its stuck at  "Loading PDF". 
There is no error message in browser console 

**Describe solutions you've tried**
I am using version 4.2.0 of react-pdf and importing Document and Page from ```react-pdf/dist/entry.webpack```

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

![pdf-viewer-IE](https://user-images.githubusercontent.com/73970097/102226604-93669e00-3f0e-11eb-98e3-0c42e5d81c14.JPG)

 - Browser (if applicable) [Internet Explorer 11.572.19041.0]:
 - React-PDF version [4.2.0]:
 - React version [16.11.0]:
 - Webpack version (3.12.0):

**Comment by wojtekmaj** [comment]
Try attaching logging to `onSourceError`, `onLoadError` callback props in Document component, as well as `onLoadError` and `onRenderError` callback props in Page component.

**Comment by anusha-bhat-roostify** [comment]
Got invalid character error for ```onSourceError``` callback in Document. 
Following is the screenshot:- 

![IE-pdf-viewer-2](https://user-images.githubusercontent.com/73970097/102252212-d1be8600-3f2b-11eb-875a-d3d91005a0e1.JPG)


Following is the content of file prop-
 
```data:application/pdf;base64,JVBERi0xLjUKJb/3ov4KMiAwIG9iago8PCAvTGluZWFyaXplZCAxIC9MIDEw\nNjUyIC9IIFsgNjg3IDEyNiBdIC9PIDYgL0UgMTAzNzcgL04gMSAvVCAxMDM3\nNiA+PgplbmRvYmoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKMyAwIG9iago8\nPCAvVHlwZSAvWFJlZiAvTGVuZ3RoIDUwIC9GaWx0ZXIgL0ZsYXRlRGVjb2Rl\nIC9EZWNvZGVQYXJtcyA8PCAvQ29sdW1ucyA0IC9QcmVkaWN0b3IgMTIgPj4g\nL1cgWyAxIDIgMSBdIC9JbmRleCBbIDIgMTUgXSAvSW5mbyAxMSAwIFIgL1Jv\nb3QgNCAwIFIgL1NpemUgMTcgL1ByZXYgMTAzNzcgICAgICAgICAgICAgICAg\nIC9JRCBbPDE5NjViNDBiMDM2MDkyM2VlMjkwNDJhOGUwOGNkOGE2PjwxOTY1\nYjQwYjAzNjA5MjNlZTI5MDQyYThlMDhjZDhhNj5dID4+CnN0cmVhbQp4nGNi\nZOBnYGJgOAkkmJaCWEZAgrEORNwHERJAQuERiOXLwMR4aztICQMjNgIAE2oG\nMAplbmRzdHJlYW0KZW5kb2JqCiAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg\nICAgICAgCjQgMCBvYmoKPDwgL1BhZ2VzIDE0IDAgUiAvVHlwZSAvQ2F0YWxv\nZyA+PgplbmRvYmoKNSAwIG9iago8PCAvRmlsdGVyIC9GbGF0ZURlY29kZSAv\nUyAzNiAvTGVuZ3RoIDQ5ID4+CnN0cmVhbQp4nGNgYGBlYGBazwAEqjEMcABl\nMwMxC0IUpBaMGRjuM/AyMPDVsbE9WN3AAAB5MAVZCmVuZHN0cmVhbQplbmRv\nYmoKNiAwIG9iago8PCAvQ29udGVudHMgNyAwIFIgL01lZGlhQm94IFsgMCAw\nIDYxMiA3OTIgXSAvUGFyZW50IDE0IDAgUiAvUmVzb3VyY2VzIDw8IC9FeHRH\nU3RhdGUgPDwgL0czIDEyIDAgUiA+PiAvRm9udCA8PCAvRjQgMTMgMCBSID4+\nIC9Qcm9jU2V0IFsgL1BERiAvVGV4dCAvSW1hZ2VCIC9JbWFnZUMgL0ltYWdl\nSSBdID4+IC9TdHJ1Y3RQYXJlbnRzIDAgL1R5cGUgL1BhZ2UgPj4KZW5kb2Jq\nCjcgMCBvYmoKPDwgL0ZpbHRlciAvRmxhdGVEZWNvZGUgL0xlbmd0aCAyMDkg\nPj4Kc3RyZWFtCnictZDLCgIxDEX3/YqsBWvSNk0L4kJQ10rBD/AFgoL6/2Cm\nMz42A6LYQB/3pDdtCFBjSDpJdrA5mYtplEiuCtedWQ/grKoVrrmPVVMJmlgt\noN1cD2a08HC4VYdEEQg5Nhb7j5Slxnt1so5/fwB/a95ZTYsZzQNQsJGzjgRl\nb+jVNoRyMjnqATOULYwRvUygHE2ymV101Di2IKQOEBOhpCfgWIFY7xK51wVu\nnYJFoSwsT4C+B7DvKRGkD+QKZuXPPaKgDfF6961T3Te62ne8RoURZW5kc3Ry\nZWFtCmVuZG9iago4IDAgb2JqCjw8IC9GaWx0ZXIgL0ZsYXRlRGVjb2RlIC9M\nZW5ndGgxIDE2NDY0IC9MZW5ndGggODA3NSA+PgpzdHJlYW0KeJztewtcVVX2\n/9r7nPuEC+fyvtwL98CFi3JRlIcgElyeZoRvDQwSRBJRE8RXkxVO2oMsHSt7\nTJP2tpqmC5ih1chkNWUP7T05paY21RRpTdkTzu97zkVBrN/HX7/5//+f/p85\nh/Xda+299tr7rLP22vvYjRgRSQCRaNK01LSNUzqDiVggamfOLC6vmLyx8WvI\nc4msN9ctqm3i69hdRCHfor2qbvlSeVPT68uJQqcT6Udd3DRv0Yqkh6BvW0Ok\n882rbWmiKDIROTPUUeYtvPTi7e8/B1keRWT8c8PcRSt3X/fN9UTDjkPe2lBf\nO3fP2BProa/aH9OAipBFgfuJRt8GOaFh0dKV8R/xP0N+CnOqWbi4rjZWcfig\nX4z2jkW1K5vEvsCbiNIdkOVLahfVu1cVQj89F/pfNS1uWaok0yaizFFqe9OS\n+qZPH20+DHkykbmXmHAt20A6zP0OXTp62P2l8BpdzEOMOh6gF7l6wVck0KCr\nfPEli8lLMm3RvdE3haUb8liHl5iiKP0KAglMvXSCwDhjFKX7LKCbvjUqZCSj\n0gcfmZReMpMZGEABwEAKBFrIAgzSMJiCgBIFA63AHymErMBQCgGGUSgwHPgD\nRVAYMJLCgVHA78lGkeCjyQbeTtFAh4YxZAfGkkP5jpwayhQDjCMnMJ5koAv4\nLSVQHDCR4oFu4DeURC7gMEoADic3MFlDDyUpJyiFhgFHaDiSkoGp5AGOohHA\n0cCvKY1GAtMpFZhBo5SvKFPDMTQamEXpwGzKUP5FYzXMoUzgOA1zaQzwHMoC\n5lE2MJ/GKl/iLeQAC2gcsJBygUXAL6iYzgGWUB6wlPKV4zSevMBzqQA4gQqB\n52lYRkXA86kYWE6lyjGaqOEkGg+cTOcCp9AE5XOaquE0Og84ncqUHppB5cCZ\nGl5AE4EVNEn5jCppMnAWsIcupCngq2gasJqmAy/ScDbNUD6lGpoJrKULgHOA\n/6Q6qgTOpVnAeroQeDFVKZ/QPA0bqBo4ny5SPqZGqgG/QMOFVAtcRHNQfwnV\nARdr2ERzlY+omeqBS2gesEXDpdSg/IOW0XzgcmoErgB+SCtpAfBSWgT8DV0C\nvEzDVbQYeDk1Aa+gZuUoXalhK7UAV9NS4G9pmXKErqLlwDUarqUVymG6mlYC\nr6FLgdfSb4DX0WXKB9RGq4DX0+WoWQf8gG6gK4A30pXA9bQauAF4iH5HvwVu\npKuAN9Ea5SDdrOEttBa4ia4B3krXovU24EG6na4D3kFtygH6PV0PvJPWAf+g\n4V10I3AzrQduoQ3Au4Hv0z30O+C9tBF4H90EvJ9uVt6jB+gW5e/0IG0CbqVb\ngQ9p+DDdBnyEbgf+kX4PfFTDP9GdwMfoD0Af3QVsB+6nDtoM7KQtwG10j/Iu\nPU73Kn+j7Ro+QfcBu+h+4A56ALhTwydpK/Apekh5h56mh4F/1nAXPQLspj8C\n/0KPAp+hPwF302PK2/Qs+YDPUbvyFj2v4V+pA/gCdSpv0ou0DbiHHge+RNuB\nL9MTwFeoC/gq7QDu1XAf7QS+Rk8BX6enlTfoDeDr9Cb9GfgW7QK+Td3Ka/SO\nhn+jZ4Dv0m7gfnoW+HcN36PngO/T88AD9FdlHx3U8BC9qOylD2gP8DC9BDyi\n4VF6GfghvQL8B70K/Ij2Ka/Sxxp+Qq8B/0mvK6/Qp/QG8DMNe+hN4Of0tvIy\nHaN3gMc1/IL+BvyS3gX+i/YDv9Lwa3pPeYlO0PvAb+gA8FvgHvqODgK/p0PA\nH+gD4I8a9tIR5UXqo6NAhT4E/ien/5/P6V/8ynP6p2ed0z/5mZz+yRk5/eOf\nyekfnZHT/3EWOf3oqZy+5LScfuRncvoRLacfOSOnH9Zy+uFBOf2wltMPazn9\n8KCc/sEZOf2QltMPaTn90K8wp7/7/yinv/mfnP6fnP6ry+m/9nP6rzen/9w5\n/T85/T85/adz+gv/H+R0It7/rzhhQKaVIrIMIYsb0aZHhp2OFdyEFbdF+3cc\nVZ4LuUWVlSOn7jqt96BLt5NsoGjdg2QT3cjshBVLWM0o++YrH6vtasn/CeWu\nfiJE6KNsPiJxFz3DjqPXY4imbXjvkciJd2Id34yVqEduegGrcCpuHepvZjZl\nGzL23XiGuxEFkchmVyD+IlgU8smVtFZ4A73WYn+KR66djNxyAztfWYasdlC8\nCpn7fOScJtaqVCg3KhuV+7BudggvaHtbNPJZHd7i57q/YSWNQI9bsDoPso2m\nx5G7L0D+2CH8AZnpDqFaZMo87E4CdqMVmIOIbPwK6+YeWK+nj1gUWyUUwcq9\nik95FloOZNMGrPGdLJON53G6KqUc7z4CY6yE1dux2rbj7sKa2c8CdceV+5Df\nbdinJuB5ttGrrFvo613dl686Gl4ajj1nAp7rz1gn+5iL/YUv1gXq0nRe3W8Q\n+WHYwWZgtg+i5z/YN/wK3FcKz4ulSiHe81rkJ3gbq+0DFs1S2SQ2kw/ni/ld\nwhLEQAr6jsYbnw9/3wbrB5iHbeeBfK9wr/iI+IM+pu+QEoQ34kam+gP9hVnw\npDJrYb9lb7MjvIjP5r/nh4WbxYfE1w21eOqLkOVvQNb5hoWwbDaFXcga2Cp2\nDfsdu529wvaxj3kBn84X8GNCg9AsPC0W4p4mtohX6a7WXa//uK+i79m+1/q+\nUdKUq7GvrULu/h3eyV14sh1Y8+/iPkiHmY4FsCDcMotjM9hluK9gN7B72Fb2\nENuGUfaxw+wT9iX7mv3AEeZcz+08jsfjdvElfAW/md/J9+Lexz/j3wmRQrzg\nETKFXKFSWIxZXSNswP248IEYLe4VFfg5TbdJt1m3VfeI7hndcX2g4bc4KL38\n4729yb0H+qjv2r5NfR1927AThOMdRsMLTpwIpmDfrMUuuBI7wP2I8zdYIHwX\nzZJZHjsfnpnNGlkzWwlPrmF3sPu1uf+JPQUvvcOOYc4W7tDmPJJn8kI+CfdF\nvJ438w18I9/G3+bfCwYhQAgWwoVkYbxQLdQLS4VLhU2CT3hZeF84LJwQfsSt\niGbRKcaLbtEjjhdni8vEu8SPxI90VbqXdB/qzfpF+qv1XfovDGMMeYbJhimG\nasN6w3bDm8YaROdu7ABPDF7z7JCwWigRHqcbebpo46/yVxHPs2muUM4RqXwr\nu5ZfzrbxBN1K/Tg+jk2k46Ibvn6eb+Yn+DihnJWxadTIR/ut6cPEh1Hkirup\nR3wKz/YqLK/UB7Ir+DF9IHUw4mMx5nPCKNEjvET7hYPMIN5NfxfNLJL18AeF\nyYiCp8U8XQXFCXfSn4Rmdjk9zkuIzD8Y1yGOJ7KHkRemszT2raCQwCciirIE\n9QywgP8N2XgF9vtb2VxxHvb0dLYKOfwBrIrhukv0yfpw9iKfL7bxULaNuPgQ\nnm4sS2CCLozWsGrhDv0x/i7OJ3tFMx0Q/ojZ7+V/EsrF47qprAEr4HKcKpqV\n1XSprkJ8nc0jgc2kRFE9F6wS0sQ4lDifINukwstRyGRdVCCUoyYKkXM+4mIG\nMsQduG9DnhARQfOxxi9AFnuVtumn8y6apwtiyDpE4kt9U3EWewC7/DychDbi\nJPsmzhurYHEr9qf1tJWt7bsM+TwWK+cAO19XyvfqSpURvI2/y6fxTae/X3g7\nkUVh5/onTgmllKd7ktrEd3CmzFfWYY8Ox/k6HjObg7PpUTzl5xjhXKGb0vsm\n8nalVGjC8x7EefJBxcnMOMEtxCn1KbrfoKNag8dbUODNzzsnd1zO2OyszIz0\ntNGjUkeOSPEkDx+W5E5McMXHyc7YGIc92hYVGREeFhpilYKDLIEBZpPRoNeJ\nAmeUUuIqrZF97hqf6Hade+4IVXbVoqJ2UEWNT0ZV6ek6PrlGU5NP1/RC8+Ih\nml6/pveUJpPkXModkSKXuGTfK8UuuYvNmlIB/oZiV6Xs69H4co3foPEW8HFx\n6CCXRDUUyz5WI5f4Spc3tJXUFMNce4C5yFVUbx6RQu3mALAB4HyRrqZ2FpnH\nNIZHluS0czJaMClftKu4xGdzFasz8AmJJbVzfZOnVJQU2+PiKkek+FhRnWuO\nj1yFvmCPpkJF2jA+fZHPoA0jz1efhq6X21O629Z1STSnxhM41zW3tqrCJ9RW\nqmNYPRi32Bf5m6NRAyKMhxRVXDO41S60lUTNl1Wxre0a2bdlSsXg1jgVKyth\nA315YmlNWymGXgcnlk2TMRpfW1nhY2sxpKw+ifpU/uerd5WoNTWNss/kKnQ1\ntDXW4NVEt/lo6qVxHdHR3h04PEeXyG3TK1xxvny7q7K22NEeRm1TL+20eWXb\n6S0jUtolq9+x7UHB/UygZTBTf6pN4zR1lSubesqzTJ2RawICwifXyZhJhQvP\nlK1CfTa11WVDDVclQy/fXLyR+T5TUU2blKPWq/19ukTJJbd9TYgAV89np9fU\n9tfoE6WvSWXVODkVamg/yfs8Hl9yshoihiK8U8wxT5MzR6Qs7+IuV5Mko4D7\naDJ8W1uZkwr3x8WpL/j6Li/NgeBrnVLhl2WaY+8gb6qn0sdr1Jbuky3hM9SW\n1pMtp7rXuBDJ27TDX7jP6D71FyxFhJY05PhYxH/TXO9vL5vmKpsyq0Iuaavp\n923Z9NMkf3v2qbZ+zhdaVCHYeT/H7YLWiqCsOqWsChWBPjERf3otqOd2GYyI\nSq2GyaU+qeZcP1aa4+LOslOXclztpRUD3fqn6cvxnC6PO00+bXqBbQImjE2w\nbPqstjbzaW0INf+AE/oLRDxNr4iTi3w0AyszEX9dSne2SpV2nxcuK1IVEH/+\nqn7xNEV7P1+JS43OESmlSHRtbaUuubStpq22S2md45IlV9sO/gx/pq2ppOZk\n4HQpO6+3+0rXVcJXDSxnhPbdoH4jWNX/xKt9Q4z5v3o3/fc3M7PHeMpP3M+q\nt/CdOFvdztQvoNc+o+r652YH535ttBu1Xe6eI0nJavn4OR0vfP9Y7zwpx3g+\nRNOpbxzOtIO3TvWBgQq3cXZUb+jit3tDSSceFchsEI8yshn1uqNceAoHGhOO\ntyMpyiOdyO3NnSh9lVvem0v54KUfAaNHxVnjrIkAhu38R1no/tGrw6ebLHar\ncxyFfXwnvpcMNMlr0fFYbHakbXqmLt7SKYtM7GLsCb3MeKrABPCPMyajn9pq\n3H67Omp1rvQVqPdo9T+kXAlD558cNjMuPM7KQ/tixLY+u87y6KPf/0v9KixV\nPhYOYkwrxdDb3kfMXLQkWjIsxRZdZlim4wI+3Tw1bJpjHp+rqzfVhdU4up1v\n6t4Kfd/2YeiHYcciP7V9GHPIqTgjnE5PdG5EbnRZdJNzg9MwkidYRkbk8ExL\nGS+xlIZNcFxgnmmZZ/lQ/1HE9+yrIImFC0EBUjDZHQEGK5nDHUJAVDqjRGtw\noiTtszLJ6rXWWFutonVpSMIuw17DQYNiEJ2GfMMkg2CwxWZMjvLAvdXN5T29\n1c25Uo/Um3uU8nvyc1WyjrWGjB09iqpZczU1x2XqXfFud2ZGyJj0tIhIa7qV\nhUWkp43JzHC74vVCdv2zV761rPHNq2o2pXb2yn9ctvz+rZetvPvqu9b9cO9m\nJrRNKeBB35fykJf3/OX5/S8/C5+VKR+LsWIezkExdMA710mOcD5DqNZVm2YE\n1AsLdItN9QFGiSQm8aSQd3Xfh52INowOybGNdhSElEcXOKaEVNmmOmpDFkXX\nOlbqV4af4CeiJHzFBlsiIydH1EQ0RQgRjuAN0haJS5Jod5gNeMUPe03sllCH\nGBDptWBle01JyRk+C7NEOyF1Jroz1NIbE+vKGOVkzoh0KcHgTUjOGOSyLL/L\nPOW9RydKzR7PiWZPeQ981ns0vydkbGp1bm9zLoPjxqq+Y9Wq95awSD2cR1aJ\n0tPIGmaIi1A9x+LcSZrvLtqZ8vmOT/qOsbD33sJn2I8fmzvW1q3r3c+nBGbP\nvG7VQ2xm5L3bmJMJ+OYZ1neg7ztJfmxnA7vl6qKGB9SID0UIturewJd8pzc2\nzMSCbam2UTavrcn2+8A7LQ9ZjNGWYRafrdsm2tSnGxbtzIgxWoTAYIeZhXNP\nWKgo6Mm8OYyFKaFeMTJRxOl+I8OKgEtGZ2eopdfscGZswFj3RtmeYjvx2X4C\nh9IoPH61x4PVglXSI/X0VKtLJReLJb9nrBXPX3SpN0yy6k0GvVHP9ZIpxE5W\nfbAdXxOe5NWrmQeBtSTd6spMz8zIGoO4ijSoDgkPTw93WTs2bw6Nvmr5+VX2\n7LSpxXv3Cnesa16QUXpByB/MpTVz1v14MWLomr75YhxiKAQn8r3e+wOlEdI5\nUpkk5ss+mTvl4YGumLTwtJjCmCZ5g2zMicyxnxd5nr3SeGFgVWSVvdG4IHC+\ntChygb1bfiPs/aj3o9+IPRp2NPaQrMgRLtEjecIzxRypVDxPmiV9GPBpTJ8U\nYA1CVDn0BqaPcAQFUJAtYZ+ZSWavucbcahbNS1loOk8PSSTqZmwD28J87DgT\nnSyfTcLrsznHZ0Ux/5Jbklsu9X51VMLCQ/hgveX3WMf2rze0UnOoNT1c9UkE\nzu9cXXtJVmHQirvmvpyNDdfua1x28LJZ60daH1i+8pEHl7a0983XPd02Zco6\n5bZ7+364/vyc3h+E+1559qW3XtrzDt5ePvJUO/w1ir3rvUyMD4vPMZ1nKk6Y\nGV8fv8p0o2lNwgOhj6Q8I1hMkdFRkaPKUt6O1Nn5DM6lNGaOqjJWmarMVQFV\ngVWWRmOjqdHcGNAY2GjZ5t6WFJzkTkhKGD4mYZa5MmCue+6wpa6lCa0JN5nv\nDNw47NaUW0bdZ34o8N6k+4Z1up9zR8R0KQe8IbFjZxmTEgPNYrTsDhcDRsZE\nq+vT4bTl2ybZZtses+216YNtTtti20Gb6LStt3Hbk3wG8gVBTZKYl3GJ7WOc\nmMQ4U4M1LCJDLb2xQdYMxkZWxSyM4TGOcIPoGBngjGbRCTZvaFSGrYtf2GFI\nSIbmE46x+5JZcnSa2suNXFCT1p3G89Na03iaxBhLIDkhOP4gsXx8fHGyjT65\n/JvLv0K8L5koVTf7M8BXnp4laubsaUYS8HjwBrVXu+QoUgH+kBEi/evBmzQi\n1qULS3FbpRApVBL08RbZTqZhBjvTjQDEhkGMC3LZKd5lCTQON9vZsCSTWe8R\n7eSUYuyMPB51U/ID8+BK9qxevZowJqte0lwdmhXhj5Ikd9JInpkxJssfRVhb\n2uIKi4zAHcvDw9Sk5M7vCL7uslUrMxNvev72SQXZyb+bdvnTs6y+wJb5qxoj\nIlLta3bdOnP+85fvfZed41iwpL74HFdUYtqE1RPHXzrM6Tn3snlRU6umZrkc\nMaHmhPSCVVWzNl/wRzUnJShf8mTd7chJrTvIjHfjcmeYVC8XgGm1MWKBFjMT\nKEIyeYLNWExCQLAUT/HMEpIYyBSDscRUUmNoMrQaNhhEMsiGLQafoduwz6A3\n7OSNFMXGtF+sbdXNWEM96tHg6Fe52tbVm6uuI2t6uvSimoA9nsRI/86l5hlr\nllXNLWGqi7gUfX7unIUpa9Z0Pv54qGdY7N2bpbz6e3jdOmZY2HfDut6bylOi\n/SeYKPW3iwFG45Df8J3lpR8q68XBbXrYDDSZfpltw1DZIAxuUyWL2az9VvPf\nbhs2gwMCfplt0xDZaBywAjerkhQY+O+xbTKJg9tU21aLRT2S/jts6wa3qbZD\ng4J+me3AIXJAwEDkwM1m2AyXpDPj6RfZDjzNtjpSVEjIme/8bK6gobLFMLgt\nEJI9LEx7r//jSxoiBwcP2A6GediMiYj4ZbZDh44lDVjBuMGQ5KioM9/5L7Ft\ntZoHeJiHzTib7ZfZDh8ihwyyjVdohc1EhwMB8wtsRw4dK2zACsYNgZQsy2fG\n09lc0UPHirQMHjcMNke6XEhYv8C2Y+hY0QNRiXHVkdLc7jNj9Wwu59CxHANW\nMK4N0pjhw7V4/B9fcUPk2NgBK7FYN5ByUlLOXAdncyUMkWV5wIqMdQOpKC3t\nzFg9m2v4EDkxccAKTr/xkMqys8+M1bO5RgyRk5MHrCQTuSFNy8s7M1bP5soY\nIo8cGTXAwzxsVpWUnBmrZ3ONHSKnp9sHeJiHzbllZWfG6tlceUPk7OyYAR6x\nrdpkSN95fROpSKLvH+tLl3KG/ldmqtAPquJD5/srv8Qj6r/9/C/6t1ApqAx+\nOasVAd1rTvFE+eiXoLm3ApBPdTgDcKzbVCpEe6C5F+c79fcDBpql/npAVDN/\nH93ZzzNk6439PEeWWtPPC3QRuft5cZCO+t+xg/p5vZbVCmgJzadaWkjlNJ1m\nUj3kFtQspkuw2tMQ3dnAck1eTEvpUmqCTs6gfjJNRc08Wqb+wgi1OT9rRaZh\nsDQfz7gELS2gi2Fx+JD+A5an9492MaQ6lDI9pP02okHjh85JpiJIS8CrWIv6\nk+M3wVYd5iBTsVZf+7+0lHpqZjJNQ8tCzP2kTgvqJqi/r9LGG43VPVb9hVs/\nl6bVFqCH32/z8dwN6NvS78UWzXPLgXNPnuuVJPX/IzrzKnBRsBBJx0AKSCAn\nMBU0CTQbtB60GaTX9NSaxaArQbtAx7UWrxDZsTHd24Xieq3obFyYpom1frGq\nWhM7L6j0l+VT/GXxBL9ajl9tdIa/emShv0xK8ZchiWmtamm2pHUXRAgRtA/E\nqQnI+LMUzBi2yS1COPlAXND313iFkM4Ed9rmXYJITOACgzucSrfAOizWtAIz\nV/gxHFmc/HPe42/hPZ1B1rTNBefxw/QYaBdI4Idxf8A/oCv5IayUYGA+aDNo\nF2gv6BhIzw/hPoj7AD8ArfcpFZQPmg3aDNoFOgYy8PeBEn9PXa8aqnw+iPP3\ngBL/Ox7r78Bgvh/cfr4fU3ujI2ts2g6N8aT2M87EfibS3s+ERKR18dc7vhvu\n7OJHOmWPc0vBKP4m+UBY/kAJJIMmg2pATSA9uLfBvU2toA2gLSAfCAdzoASS\n+R7Qy6C3aRTIC5oMMvJ9HRimi+/tcBc6CyL4q/yv2Bud/BX+gla+zJ/Xypf4\nc1r5IspYlHv48x2xTioIQDuhj4RSQpmKdh3/S2dCiFMpsPJdcI8TmArKB00C\nzQatB+n5Lh7fMdcZAiNP0h6cmJ28gz7RygfoHiN5G51edxFiTFbBnXMOOMBm\nebObe92bboeogvvGjeBUcK9ZB04F929Wg1PBvXA5OBXccxvBqeCeNRucCu5J\n08EBuvhdTyQkObMmLWByQTBfAS+tgJdWwEsrSOQr1Ju+E9W5/b4jORkeu8Pr\nGZ7sbN3JWp9irVNZ6z2stZ61XsFaV7PWXNZ6EWv1sFYHa41lrV7W+iTLhita\nmXfbaeJYbxRr3cNaH2WtLazVzVoTWWsCa5VZlreLx3VMSNeKEq3oLFDXFcpz\n8tKCMcc4eDQOYR2HZb8LuBekaJIXSnK8X9kWq5bxncn5fnlkTtrignP5bnTc\njdewmw6CRLyg3Qij3TCyGwaCgfmg2aBu0DGQAtJDOx4TX69hMDAVlA+aDboS\ndAyk16ZzDMRpcf8UH9Mmlto/6UmqxHfjVn8JFMfjvDGSQ/JI5wrrHSw4lk2K\nVWJ5FqkfZ/hCMVq7mGX7N5Zvv7GQqcDEb+TrKQYvYkN/ub7juxhnF7utw/2k\nsyCc3UqxIqKOjSU3S0SZTS2anEkOo1pmkIM/gjKtwzET3YI73CnOnSxI7bXd\n+Z3jqPMTRxcH+7HjSec7cpfIOpxvoeaR7c43Hdc5X0ztMqLmKXcXQ7FT1lR3\nOLKdj+7RVFej4Y4O5xVqsd15uWO8c4FDa6j3N1zUAskb7JzqnuU8F/aKHXOc\n3hbY3O7Md1zkzPVrZap9tjtHYQoeP5uMyQ53aIO6YjWDM7K6WIM3xbDJUGGY\nZBhjSDOkGOIMTkOMwW4IM4YYJWOQMdBoNhqNeqNo5EYyhnUph7we9bAXppfU\nQv3HJEaixktcRfWUoeY1ZuR0HvlChTJeNq2Qlfm666hsjuw7Mc3VxcxTZvl0\nrkLmCymjsumFvmxPWZdBmerL8pT5DJMvrGhn7MZK1Pr4tV2Mpld0MUWtWmtX\nf8awgxizrr3BrpbD1t5QWUlREcvzo/JD8qxjS4t/Amr60TNwRZ3Gx/g2lU2r\n8D0cU+lLUxklprLMd5P6O4cd7Et2vKR4B/tCLSordgh57MuSqWq9kFdcWVnW\nxWZqeiSzL6CHiPlC0zPGkqzqkWyM9evd4ddLRH/oJagF9EwmStT0Ek0mTU9k\nql57S0JJcXtCgqYTKVOLptMSKQ/W2ZMIncRETSeilfZoOnsiWlUdX56m4nBA\nJdahqbBocmgqDhatqcwcUEntV7nulMp12kgCG9Bx+HUsh07qWA5Bx3O2V32h\nx8M6x1XWVam/EalxldSDanzXL2+I8rXOkeX2usr+H4+4a+bUNahlbb2v0lVf\n7KtzFcvt46p+orlKbR7nKm7Hh9P0ivYqb31xxzjvuBJXbXFl5/jJGVmnjXXd\nqbEyJv+EscmqsQx1rPFZP9GcpTaPV8fKUsfKUsca7x2vjUVajE+uaDdSYWVR\nlb/s5AFmxGuNPa6yMEJqytOCd1xc1BX2nTiQbKUAT6Uv0FXos4DUphEFIwrU\nJqwptSlI/SFQf1PUFePi7DvZ1v4mCdVWVyF5li5rWUZRJfOL/X8tuFC1dJnq\ncD96Wn7uQluJz1tb3LIUn8u+5GllvvwpsyraDQbU1qiP5Ms5WRcQUNKldPsr\nR6IyR60UhFOKal2uWmcy9Sue+f6X9ZdF6ipo5U92Mm8sw5m1UvDFlk3nSAXT\n+39xsRPHJXV7aKnEA7YwD2s5aUObNvl5Up/3JC1d1s/1+2Fpf+nvhS4tJ91x\n6kIfpKr/AsIR6ShlbmRzdHJlYW0KZW5kb2JqCjkgMCBvYmoKPDwgL0ZpbHRl\nciAvRmxhdGVEZWNvZGUgL0xlbmd0aCAyNjIgPj4Kc3RyZWFtCnicXZHNasQg\nFIX3PsVdTheDTpKZoRACZUohi/7QtA9g9CYVGhVjFnn7+pOmUEHlcO539Cq9\ntY+tVh7omzOiQw+D0tLhbBYnEHoclSanAqQSflNpFRO3hAa4W2ePU6sHQ+oa\ngL4Hd/ZuhcODND3eEfrqJDqlRzh83rqgu8Xab5xQe2CkaUDiEJKeuX3hEwJN\n2LGVwVd+PQbmr+JjtQhF0qd8G2EkzpYLdFyPSGoWRgP1UxgNQS3/+WWm+kF8\ncZeqy1DNWMGaqMprUucqqXP2riwlbUzxm7AfWGWouk/bZWMvOSl713KLyFC8\nV3y/vWmxOBf6TY+cGo0tKo37P1hjIxXnDxIJhhhlbmRzdHJlYW0KZW5kb2Jq\nCjEwIDAgb2JqCjw8IC9UeXBlIC9PYmpTdG0gL0xlbmd0aCA0NjUgL0ZpbHRl\nciAvRmxhdGVEZWNvZGUgL04gNiAvRmlyc3QgMzggPj4Kc3RyZWFtCnicfVJN\nb9pAEL33V7wjHPB+eM3aUhQJQmlQRYICbQ4Vh429dVc1tmUvUvn3nTUJIT1U\nlr3yzJt5b96sEOAQErGAiJEkEApC05FAigxiCqX4p5sbsE3XFMfcdhhtfzvD\nNoslDmk6xu3tkJ6vwR6a7mAqsNxAXOKmt8um9mCzzplqvQNb2D63dWFqHxI9\nfgQajifswT7XeVO4ugRbFbb2zp8m92Db44s/tRZsR19OR/OtdgS0yIbCIQ42\n8Lzy3jVH+hFgX10RKC4MZ+jGlLZ/w86CHo+MJ5HUsVJUbdp768pfHlokUSo5\n+fOq22MihYgyofiUKCtT9lBn7vm8+UNUk+lURUnCdYpJLFWkueYxJJdpFFMn\nCB7rSPAsToOeULh0lZVIz7OEwIM52CvHVt5ULp/VZWUJw7beHr5DkbAsVdTl\navygsXOtb7r/LOButdieemqyqn82CKDHrrBdsH30ZvsY7MmWrvfdCaNZ0bzY\ncdhD21b2EEzg1H/otGu+rBZr075vjJx6DjL/0UNXapjvskwqDpAgXn5YIXsm\nFzm9OuEIj9Q6Sgfv9uGO0jYFpwBNTwEtoCWFp5FIZKygYwJcV6Qh8J4PDRP+\nsek+uPUXyfvUh2VuZHN0cmVhbQplbmRvYmoKMSAwIG9iago8PCAvVHlwZSAv\nWFJlZiAvTGVuZ3RoIDE2IC9GaWx0ZXIgL0ZsYXRlRGVjb2RlIC9EZWNvZGVQ\nYXJtcyA8PCAvQ29sdW1ucyA0IC9QcmVkaWN0b3IgMTIgPj4gL1cgWyAxIDIg\nMSBdIC9TaXplIDIgL0lEIFs8MTk2NWI0MGIwMzYwOTIzZWUyOTA0MmE4ZTA4\nY2Q4YTY+PDE5NjViNDBiMDM2MDkyM2VlMjkwNDJhOGUwOGNkOGE2Pl0gPj4K\nc3RyZWFtCnicY2IAAiZGjU4GAAG2ALcKZW5kc3RyZWFtCmVuZG9iagogICAg\nICAgICAgICAgICAKc3RhcnR4cmVmCjIxNgolJUVPRgo=\n```

**Comment by wojtekmaj** [comment]
Following the instructions here https://github.com/wojtekmaj/react-pdf/issues/278#issuecomment-424605266 - try and use something different than Base64 as IE 11 seem to have issues with createObjectUrl.

**Comment by anusha-bhat-roostify** [comment]
@wojtekmaj Thanks, It worked after converting it to a blob.
