### ISSUE TITLE
PDF is not rendering correctly, Highlighted words are displayed at wierd places 

### ISSUE THREAD

**Issue by akash-agr** [wojtekmaj/react-pdf#699]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

![Screenshot 2020-12-26 at 4 34 50 PM (2)](https://user-images.githubusercontent.com/57613792/103150273-8b252300-4798-11eb-910a-c65787f4331f.png)

When you open the pdf, and search something, highlighted text is displayed at weird places. I have noticed this is happening in odd no. of pages. Kindly help.

Please see https://elastic-aryabhata-7db629.netlify.app/. Here is the code repository https://github.com/akash-agr/modal-materailUI. 

**Describe solutions you've tried**
I have tried to use different css. Actually I do not have any clue how i can remove the extra space on pages.

Describe solutions you've already tried, if any. Make sure to include code samples if you're stuck on implementation.

**Comment by akash-agr** [comment]
.react-pdf__Page
{
  overflow: hidden;
}

Solves the problem,

**Comment by pilvikala** [comment]
That did not really fix it for me.
