### ISSUE TITLE
loading object%20object instead of specified file

### ISSUE THREAD

**Issue by grgr** [wojtekmaj/react-pdf#7]
Hello, 

i tried loading a pdf-file from url. All possibilities to include it failed with same error (file="http://localhost:3000/some/path/some.pdf", file={{ url: "http://localhost:3000/some/path/some.pdf"}}).

I tried using  pdfjs-dist@1.6.313 after  pdfjs-dist@1.6.401 failed. But the same error.

Here is what I get in chromium console: 

Warning: Setting up fake worker.  @ pdf.js: 273 
GET http://localhost:3000/[object%20Object] @  pdf.js:893 
Util_loadScript @ pdf.js:893
loader @ pdf.js:9418
setupFakeWorkerGlobal @ pdf.js:9422
PDFWorker_setupFakeWorker @ pdf.js:9641
(anonymous function) @ pdf.js:9554
(anonymous function) @ pdf.js:9561

My app is running on localhost:3000, but the path is different, as you might imagine.
Any help appreciated!

**Comment by wojtekmaj** [comment]
Hey,
thank you for this report, I'm on it :)

**Comment by grgr** [comment]
Thank you very much for your effort! But ... I still get the error :(
Sorry for the late reply!

**Comment by grgr** [comment]
Here is what I get from Chromium:

pdf.js:817GET http://localhost:3000/[object%20Object] Util_loadScript @ pdf.js:817loader @ pdf.js:8081setupFakeWorkerGlobal @ pdf.js:8085PDFWorker_setupFakeWorker @ pdf.js:8267PDFWorker_initialize @ pdf.js:8260PDFWorker @ pdf.js:8166getDocument @ pdf.js:7646loadDocument @ react-pdf.js:194handleFileLoad @ react-pdf.js:183componentDidMount @ react-pdf.js:89(anonymous function) @ ReactCompositeComponent.js:264measureLifeCyclePerf @ ReactCompositeComponent.js:74(anonymous function) @ ReactCompositeComponent.js:263notifyAll @ CallbackQueue.js:67close @ ReactReconcileTransaction.js:81closeAll @ Transaction.js:204perform @ Transaction.js:151perform @ Transaction.js:138perform @ ReactUpdates.js:90flushBatchedUpdates @ ReactUpdates.js:173closeAll @ Transaction.js:204perform @ Transaction.js:151batchedUpdates @ ReactDefaultBatchingStrategy.js:63enqueueUpdate @ ReactUpdates.js:201enqueueUpdate @ ReactUpdateQueue.js:25enqueueSetState @ ReactUpdateQueue.js:210ReactComponent.setState @ ReactComponent.js:64_onChange @ Pages.jsx:24EventEmitter.emit @ events.js:74emitChange @ PageStore.js:58(anonymous function) @ PageStore.js:78_invokeCallback @ Dispatcher.js:198dispatch @ Dispatcher.js:174handleServerAction @ AppDispatcher.js:15loadedPages @ PageActionCreators.js:10(anonymous function) @ WebAPIUtils.js:66Request.callback @ client.js:721(anonymous function) @ client.js:536Emitter.emit @ index.js:133xhr.onreadystatechange @ client.js:825

**Comment by wojtekmaj** [comment]
Closed via #9
