### ISSUE TITLE
page-scrolling-spy

### ISSUE THREAD

**Issue by yichenlivened** [wojtekmaj/react-pdf#70]
Help wanted.

Hi there, I want to build a feature that shows page number when user scrolling the pdf document. I tried insert <Link to={}> from `react-scroll`  into Page child but the Link component is parsed into text.... I wonder if there is a suggested way to implement it. Thank you!
```
<Document
	file={this.props.document.url}
	onLoadSuccess={pdf => this.initPDF(pdf)}
>
	{
		pages.map((page) => {
			return (
				<Page
					key={page + 1}
					pageNumber={page + 1}
					scale={scale}
				/>
			);
		})
	}
</Document>
```

**Comment by wojtekmaj** [comment]
Hey @yichenlivened, thanks for contacting me.
Would you please include some full example? The code you pasted seems to be perfectly fine to me.

One hint that might help you:

If you want to put `<Page>` component not directly within `<Document>` component, you have to make sure to pass all required props through your wrapper component to it. For example:

```js
<Document file={file}>
    <MyWrapper>
        <Page pageNumber={1} />
    </MyWrapper>
</Document>
```

won't work, unless `<MyWrapper>` would do something like this:

```js
class MyWrapper extends Component {
   ...
    render() {
        return (
            React.Children.map(
                children,
                child => React.cloneElement(child, this.props)
            )
        );
   }
```

the code above would ensure that all props passed to `<MyWrapper>` by `<Document>` are passed to `<Page>` component.
