### ISSUE TITLE
Type declarations help

### ISSUE THREAD

**Issue by kylemh** [wojtekmaj/react-pdf#703]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'm trying to improve the definitions within `@types/react-pdf`, but want to make sure I've got everything handled before opening a pull request.

**Additional information**

For the `Page` prop `onLoadSuccess` (and for most props that are called "page callbacks"), console logging the argument of the methods yields the following shape:

![Screen Shot 2021-01-04 at 4 25 43 PM](https://user-images.githubusercontent.com/9523719/103594028-5279fd80-4eac-11eb-86ff-02b31fe17587.png)

This doesn't match up with the types outlined [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-pdf/dist/Page.d.ts#L105) which leverages an interface from `@types/pdfjs-dist` called [`PDFPageProxy`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e97033115b98cf91f4d9752f387584e09ccb5675/types/pdfjs-dist/index.d.ts#L414).

For example, `_pageIndex` is exposed even though the types indicate that `pageIndex` is exposed.

Is there some parsing on page callbacks occurring beyond [this method](https://github.com/wojtekmaj/react-pdf/blob/master/src/shared/utils.js#L120)? If not, which of the two packages (pdfjs-dist / react-pdf) have the incorrect typing?

**Comment by wojtekmaj** [comment]
makePageCallback only extends PdfPageProxy with these 4 additional handy properties.

Chances are something has been changed in pdfjs dist itself and that's why the other properties are different.

**Comment by kylemh** [comment]
So you're saying if pdfjs-dist was upgraded in this package, that the properties available would change?

**Comment by wojtekmaj** [comment]
Yeah. Mozilla is yet to discover wonders of semver, which is the reason for me refraining from updating pdf.js in minor React-PDF versions. 

Chances are we have missed something during [v5.1.0](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.1.0) update. If that's the case and e.g. `pageIndex` was available in 5.0 and now isn't, let me know and I'll fix that and add unit tests so that it wouldn't happen again.

**Comment by kylemh** [comment]
Sad to hear regarding non-Semver...

Okay, [indeed](https://github.com/mozilla/pdf.js/blob/6516ff20b504eae3280c52f67a8277bebceb2537/src/display/api.js#L1046) they've since changed it. This is very helpful thank you.

Mind if I leave this open as a means for myself and others to gain context when adjusting types?
