### ISSUE TITLE
Smooth transitions when setting pageNumber

### ISSUE THREAD

**Issue by emorling** [wojtekmaj/react-pdf#704]
I wonder if anyone has manage to create a smooth transition when setting a new pageNumber for the Page component?

**Comment by wojtekmaj** [comment]
On [demo page](https://projects.wojtekmaj.pl/react-pdf/), I deal with this by keeping the old page rendered while the new one is still rendering underneath. See https://github.com/wojtekmaj/react-pdf/issues/418#issuecomment-660982983 for details.

**Comment by emorling** [comment]
Perfect, thank you!
