### ISSUE TITLE
PDF Hyperlinks not working

### ISSUE THREAD

**Issue by Jackmt9** [wojtekmaj/react-pdf#705]
Similar to #199, I'm having trouble getting hyperlinks from my pdf clickable after rendering to page. I have imported the Annotation Layer, no <a> tags appear, and my mouse does not change when hovering over. Is this something others are having issues with as well?

**Comment by Jackmt9** [comment]
Here's my code: 
```
import React, { useState } from 'react';
import { Document, Page, pdfjs } from 'react-pdf';
import pdf from './Resume.pdf'

// import 'react-pdf/dist/esm/Page/AnnotationLayer.css';
import 'react-pdf/dist/umd/Page/AnnotationLayer.css';

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;


export default function Resume(){
    const [numPages, setNumPages] = useState(null);
    const [pageNumber, setPageNumber] = useState(1);

    function onDocumentLoadSuccess({ numPages }) {
        setNumPages(numPages);
    }

  return (
    <div className='resume'>
      <Document
        file={pdf}
        onLoadSuccess={onDocumentLoadSuccess}
        // options={{ workerSrc: "/pdf.worker.js" }}
        externalLinkTarget='_blank'
        // loading={this.renderLoader()}
      >
        <Page pageNumber={1}
        width={window.innerWidth} 
        />

      </Document>
      {/* <p>Page {pageNumber} of {numPages}</p> */}
    </div>
  );
}
```

**Comment by mikigraf** [comment]
Hi, I have this issue probably due to using this component with Direflow. For some reason my annotations are not being rendered correctly.. 

I did a try with just a react app and react-pdf and hyperlinks worked, so I think it's an issue with Direflow in my case.

**Comment by Jackmt9** [comment]
Seems I fixed the issue, not exactly sure. Too many variables to isolate. I exported my document from MS Word using the pdf export option "best for electronic distribution and accessibility". That may have done it. Seems to be working fine now, thanks!

**Comment by zendy199x** [comment]
https://codesandbox.io/s/react-pdf-next-js-forked-6mmhg?file=/components/pdf-viewer.js
