### ISSUE TITLE
Time Stamp / PDF Edit

### ISSUE THREAD

**Issue by Jackmt9** [wojtekmaj/react-pdf#708]
I'd love for a way to better interact with a PDF, such as adding a timestamp to the pdf text when downloaded. I don't believe this feature is incorporated in this project but may already exist as a stand alone project elsewhere (but unsure).

**Comment by wojtekmaj** [comment]
Are you sure this is the right repo? Downloading a PDF from React-PDF doesn't make a lot of sense. It's a PDF-reading package.

**Comment by Jackmt9** [comment]
My apologies, you're right. Not the place for this post
