### ISSUE TITLE
Display PDF loaded from server

### ISSUE THREAD

**Issue by MarcosCunhaLima** [wojtekmaj/react-pdf#709]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I want to show a previously downloaded PDF using react-pdf. It seems that all examples that I could get either load it from a file or download it from a URL. In this project, we already have fetch logic, authentication and I cannot change that. So, I successfully get the PDF from the server (binary) and don't know how to display it.

Simple code:
```
function ShowPDF(props) {
   const dataBinary = props.data;

   const toArray = (pdfBin) => {
      if (!pdfBin) { return new Uint8Array(0) }
      const len = pdfBin.length;
      const bytes = new Uint8Array(len);
      for (var i = 0; i < len; i++) {
         bytes[i] = pdfBin.charCodeAt(i);
      }
      
      return bytes
   }
   

   return (
      
      <Document file={{ data: toArray(dataBinary) }}>
         <Page pageNumber={1} />
      </Document >
   )


}
```
In the console, it shows:

Warning: Indexing all PDF objects
pdf.worker.js:1031 Warning: Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 253"
pdf.worker.js:1031 Warning: Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 253"
pdf.worker.js:1031 Warning: Invalid stream: "FormatError: Bad FCHECK in flate stream: 120, 253"

and it shows nothing.

Is there any example that would show a previous downloaded PDF?

**Environment**

 - Browser : Chrome  87.0.4280.141
 - React-PDF version:  5.1 
 - React version : 17.0.1

**Comment by MarcosCunhaLima** [comment]
The only way it works is by converting (at server) to Base64 and using:

`<Document` file={`data:application/pdf;base64,${base64codedPDF}`} >

where **base64codedPDF** is the Base64 pdf data provided from server.

**Comment by redday059** [comment]
@MarcosCunhaLima  what about multiple pages?
I was passing just an url to base64 and it worked;
I was passing it in the way that you suggested, and it workes.
The only problem is that numberOfPages is undefined, so I always have only 1 page.

```
  function onDocumentLoadSuccess({ numberOfPages }) {
    console.log('numberOfPages?: ', numberOfPages);
    setNumPages(numberOfPages);
  }

```
