### ISSUE TITLE
Incompatible with react v16

### ISSUE THREAD

**Issue by lionvs** [wojtekmaj/react-pdf#71]
The current react-pdf version is incompatible with the newest react v16. In the newest version React.PropTypes were deleted. 

But because in package.json we have "react": ">=15.5" we load this library with the incompatible version of react.

React v16 changes: 

https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html

"The deprecations introduced in 15.x have been removed from the core package. React.createClass is now available as create-react-class, React.PropTypes as prop-types, React.DOM as react-dom-factories, react-addons-test-utils as react-dom/test-utils, and shallow renderer as react-test-renderer/shallow. See 15.5.0 and 15.6.0 blog posts for instructions on migrating code and automated codemods."

**Comment by lionvs** [comment]
My bad. I was using react-pdf v1.6.1

**Comment by wojtekmaj** [comment]
No worries :) If you will have any issues, especially after the update, feel free to contact me. :)
