### ISSUE TITLE
Some confusion about the performance when a pdf has so many letters

### ISSUE THREAD

**Issue by OJAccepted** [wojtekmaj/react-pdf#710]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

i have a pdf has about 30 thousand letters in only 3 pages(447KB), when load it cost so much time, i want to ask how many letters in one page or how many letters in a file it will performance normally?
i clone the source and run local, i find that render every letter as a span, so i think this cost so much time

**Describe solutions you've tried**

i load much pdf, i can success when it has less than one thounsand letters in one page, i just want to know the Upper limit of performance

**Environment**

 - Browser (if applicable) [e.g. Chrome 84]:
 - React-PDF version [e.g. 4.0.1]:
 - React version [e.g. 16.8.6]:
 - Webpack version (if applicable) [e.g. 4.35.2]:

**Comment by RangoEnvy** [comment]
![image](https://user-images.githubusercontent.com/50538883/104794545-4c0c4f80-57e3-11eb-9567-eb61b89a890e.png)
like this pictrue, i parse the text to an array of letters, so that it render every letters a span label, so that reduce the performance of render

**Comment by wojtekmaj** [comment]
I don't think there's an upper limit of DOM elements, but the more, the worse, that's for sure. Some low-end devices could struggle with rendering PDFs _at all_, without "help" from these letters rendered on text layer.

This looks like a horribly encoded PDF by the way. It should be one line or at the very least one word per item.

**Comment by MattL75** [comment]
@wojtekmaj Hi! Found this ticket by accident and wanted to chime in. Our app currently uses a fork of this package because we needed to limit the amount of DOM element rendered. Customers' pdfs are not always great and many were complaining of bad performance when the number of elements was very large.

How would you feel about an option to limit this?

**Comment by wojtekmaj** [comment]
Can you please provide me with a PDF on which performance is particularly bad? I'll see what I can do.

I feel like limiting the number of rendered items is hiding the problem, not fixing it.

**Comment by MattL75** [comment]
@wojtekmaj I sent it to you via the email listed on your profile.
