### ISSUE TITLE
"regeneratorRuntime is not defined" for pdf.worker.js

### ISSUE THREAD

**Issue by xxx** [wojtekmaj/react-pdf#711]
**Before you start - checklist**

 - [X] I followed instructions in documentation written for my React-PDF version
 - [X] I have checked if this bug is not already reported
 - [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

When I try to load a page that renders a PDF, I see this error in my console, and the PDF does not render.

![Screenshot from 2021-01-19 13-29-38](https://user-images.githubusercontent.com/41678/105095389-6f8cff80-5a5a-11eb-8b29-2b1f92f0c0cf.png)

**Steps to reproduce**

Even this most basic of examples causes the issue.

```javascript
import React from 'react';
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';

const PDFPage = () => {
  return (
    <Document file="https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf">
      <Page pageNumber={1} />
    </Document>
  );
};

export default PDFPage;
```

**Expected behavior**

The document renders on the page.

**Additional information**

I originally had this error from react-pdf itself, which was resolved by explicitly importing `core-js/stable` and `regenerator-runtime/runtime` in the app root file. Now it's coming from the worker, but I don't see how to resolve it.

I've already gone down the large babel / plugin-transform-runtime / polyfill / etc. rabbit hole with no luck.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: both Firefox 84.0.2 and Chrome 87.0.4280.88 have this issue.
 - React-PDF version [e.g. 3.0.4]: 5.1.0
 - React version [e.g. 16.3.0]: 17.0.1
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.44.2

**Comment by wojtekmaj** [comment]
Is there any chance you could share your repo with me, preferably stripped down to just the config and your React-PDF usage? I'll try and look for the differences that could have lead to this error.

**Comment by xxx** [comment]
Unfortunately I'm unable to share the repo. I'm not even sure where to start attacking this.

**Comment by wojtekmaj** [comment]
Then would it be possible to share your Babel and Webpack config?

**Comment by xxx** [comment]
Sure, I've put both files in gists [here](https://gist.github.com/xxx/0f9f08688fbee2fbfc4ec5487fc88334)
Note that this is a Rails app, so [webpacker]() is sitting in front of webpack itself, and is configured via the yml file in the fist.

In other news, I *was* able to get the pdf to load with the following (based on [this comment](https://github.com/mozilla/pdf.js/issues/7612#issuecomment-576807171):

```javascript
import React, { useEffect } from 'react';

// Note that this method does *not* work when importing from react-pdf/dist/esm/entry.webpack
import { Document, Page, pdfjs } from 'react-pdf';
import PDFJSWorker from '!!file-loader!pdfjs-dist/build/pdf.worker.min.js';

const PDFPage = () => {
  useEffect(() => {
    pdfjs.GlobalWorkerOptions.workerSrc = PDFJSWorker;
  });

  return (
    <Document file="https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf">
      <Page pageNumber={1} />
    </Document>
  );
};

export default PDFPage;
```

**Comment by xxx** [comment]
I think I can close this. I'm pretty sure this is just a weird special case.

I was able to get rid of the inline loader via some [webpacker config](https://github.com/rails/webpacker#webpack-configuration), left here for anyone that shows up here in the future:

```javascript
environment.loaders.append('pdfjs-worker', {
  test: /pdf\.worker(\.min)?\.js$/,
  loader: 'file-loader'
});
```
