### ISSUE TITLE
How to display from aws s3 file url?

### ISSUE THREAD

**Issue by pyDjangoDev** [wojtekmaj/react-pdf#712]
Here is my code.
```
<Document
              file={{
                url: 'Document URL with aws accesskeyid, signature and expire',
              }}
              onLoadSuccess={this.onDocumentLoadSuccess}
            >
              <Page pageNumber={pageNumber} />
</Document>
```
The file get request was successful and request repeatly.
And, It always shows "Loading PDF"
Please help me.
Thanks.

**Comment by varunkamanibosc** [comment]
You need to enable cross-origin requests in your s3 bucket.

**Comment by mridul911** [comment]
Hey, @pyDjangoDev did you find a way to do so?

**Comment by wojtekmaj** [comment]
Not related to React-PDF itself. Please refer to Amazon S3 documentation.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html
