### ISSUE TITLE
Jest encountered an unexpected token - "import *"

### ISSUE THREAD

**Issue by Skylerdw** [wojtekmaj/react-pdf#714]
Hi, while trying to run tests, I'm getting an issue. I tried solutions including installing multiple babel packages, configuring them in packages.json, adding .babelrc files, but nothing seems to work.

Jest complains, that the webpack.js from the react-pdf package is not a correct javascript file. Has anyone else had this issue or knows a workaround for the issue?

` Error Message:
Jest encountered an unexpected token`

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Code\harmo\my-application\node_modules\react-pdf\dist\esm\entry.webpack.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as pdfjs from 'pdfjs-dist';
                                                                                                    ^`

**Comment by wojtekmaj** [comment]
Sounds like your Babel/Jest is misconfigured.

Note this part:

>  By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

You're using ESM modules version of React-Date-Picker. You will want your ESM modules to be transpiled using @babel/preset-env for Jest to consume, if your environment does not support it natively.

In my project, I have it configured like so:

```json
{
  "presets": [
    …
  ],
  "plugins": [
    …
  ],
  "env": {
    …
    "test": {
      "presets": [
        ["@babel/preset-env", {
          "targets": {
            "node": "current"
          }
        }]
      ]
    }
  }
}
```

and this is enough to make it work.

Also ensure you're running newest version of Jest, although they still work on native support for ESM modules: https://github.com/facebook/jest/issues/9430

**Comment by VincentNewkirk** [comment]
I have this exact same problem. I've used the config @wojtekmaj has suggested, but has not solved my problem. @Skylerdw , any updates on resolving this?

**Comment by Skylerdw** [comment]
I don't have access to this code anymore, but I think it was something related to importing the library incorrectly. Can't remember any details though, sorry.

**Comment by Skylerdw** [comment]
@VincentNewkirk  @up

**Comment by madelineurl** [comment]
Also having this issue, but only when importing pdfs from 'react-pdf-dist/esm/entry.webpack' for performance as instructed in the documentation. Importing PDF and Document directly from 'react-pdf' works in Jest, but fails in the browser. Vice versa for importing as instructed in the docs

**Comment by VincentNewkirk** [comment]
I resolved this by not using the ```react-pdf-dist/esm/entry.webpack``` entry point and just importing from components from ```react-pdf```.
It failed in the browser for me at this point. How I fixed this was by specifying to worker like mentioned in the docs:
```pdfjs.GlobalWorkerOptions.workerSrc = 'pdf.worker.min.js';```

I needed to copy this min file from pdf-js in my node modules. I'm using webpack dev server which can serv files from ```public``` directory. So i created that directory and put the minified pdf js file inside there.

**Comment by jlarmstrongiv** [comment]
That’s a great tip!  Workaround for `create-react-app` in `package.json`:
```json
{
  "jest": {
    "moduleNameMapper": {
      "react-pdf/dist/esm/entry.webpack": "react-pdf",
    }
  }
}
```

**Comment by wojtekmaj** [comment]
You could also try Jest-specific entry:

```json
{
  "jest": {
    "moduleNameMapper": {
      "react-pdf/dist/esm/entry.webpack": "react-pdf/dist/esm/entry.jest",
    }
  }
}
```

**Comment by woozay** [comment]
```
{
  "jest": {
    "moduleNameMapper": {
      "react-pdf/dist/esm/entry.webpack": "react-pdf/dist/esm/entry.jest",
    }
  }
}
```
Worked for me. However I then got the error `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))` and `Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)`. To fix that, I needed to install jest-canvas-mock, then in the jest.config.js I added
```
{
...
   setupFilesAfterEnv: ["jest-canvas-mock"],
...
}
```
