### ISSUE TITLE
Failed to load PDF file when Import files from other server

### ISSUE THREAD

**Issue by usuarez** [wojtekmaj/react-pdf#717]
**Before you start - checklist**

 - [ok ] I have read documentation in README
 - [ ok] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [ok] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
i'm trying to import files from other server, for example, react server is localhost:3000 and y try to render a pdf from localhost:3009/pdf/file.pdf
i can open the link directly and its works but not in react. ¿why?

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.
I'd like to display multiple pages of my PDF.

**Describe solutions you've tried**
i try to fix:
 *using the url on the prop file of the <Document />
*import file from 'url....'
*const file = require('url....')

**Environment**

 - Browser: chrome, firefox, edge, opera  all updated versions...
 - React-PDF version: 5.1.0
 - React version: 17.0.1

**Comment by wojtekmaj** [comment]
Likely a CORS issue.
