### ISSUE TITLE
Scale to Fit

### ISSUE THREAD

**Issue by emorling** [wojtekmaj/react-pdf#718]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I have set the page to fill 100% of the browser width, and to update if the window resizes.
I want to display the contents of the page as "scale to fit" within the designated width/height.

**Describe solutions you've tried**

I tried using object-fit, but that doesn't seem to work. My guess is that the 100% width of the page is conflicting.

Any ideas or pointers would be helpful.

**Comment by wojtekmaj** [comment]
You would need to listen for both window width and height changes. Then you need to implement your own algorithm to pass given width or height to Page.

As a starting point, I'd use page to window size ratio for both width and height and check which is larger.

Say your window is 1000 x 1000 and page is 2400 x 1200. You will get two ratios here: 2.4 for width and 1.2 height. Based on that, you know that page width is the one more "concerning" so you need to set width to 1000.

Say your window is 1000 x 2000 and page is 1000 x 600. Ratios are 1 and 0.3. Here width will also be more "concerning" so you set width to 1000.

Say your window is 1000 x 1000 and page is 400 x 600. Ratios will be 0.4 and 0.6. From this you know that as the PDF gets larger it's the height that will cease to fit first, so you set height to 1000.

**Comment by emorling** [comment]
Wow, thank you! That was very helpful and painless to implement! I am sharing some code here in case someone needs it:

`
 const [wrapperWidth, setWrapperWidth] = useState(0);
  const [wrapperHeight, setWrapperHeight] = useState(0);
  const [pageWidth, setPageWidth] = useState(0);
  const [pageHeight, setPageHeight] = useState(0);

 const fitHorizontal = useMemo(() => {
    const wRatio = pageWidth / wrapperWidth;
    const hRatio = pageHeight / wrapperHeight;
    if (wRatio < hRatio) {
      return false;
    }
    return true;
  }, [pageHeight, pageWidth, wrapperHeight, wrapperWidth]);

  const setWrapperDimensions = useCallback(throttle((w, h) => {
    setWrapperWidth(w);
    setWrapperHeight(h);
  }, 500), []);
`

And the rendering:

`<Measure
        bounds
        onResize={(contentRect) => setWrapperDimensions(contentRect.bounds.width, contentRect.bounds.height)}
      >
        {({ measureRef }) => (
          <DocumentWrapper ref={measureRef}>
            <Document>
              <Page
                key="page"
                onLoadSuccess={(page) => {
                  setPageWidth(page.width);
                  setPageHeight(page.height);
                }}
                width={fitHorizontal ? wrapperWidth : null}
                height={!fitHorizontal ? wrapperHeight : null}
                scale={scale}
              />
            </Document>
          </DocumentWrapper>
        )}
      </Measure>`

**Comment by DovahBrownies** [comment]
@emorling Amazingly clean answer! Hats off to you, dude!
Quick question; Why did you implement a variable `scale`? I noticed that you didn't share the value and / or logic behind it. Setting the scale at the default `1.0` seems to work fine.
What did you set it as?

**Comment by emorling** [comment]
@DovahBrownies  great question! We have some zooming controls as well, which I removed to keep the example clean. But if you did pass another scale, such as 0.5 or 2.0 it will also work very well

**Comment by annjawn** [comment]
hey @emorling , this looks pretty enticing. Would you mind putting it into a gist?

**Comment by emorling** [comment]
Sure, it is available as a gist here:
https://gist.github.com/emorling/227644effd10eea1ac2366426ab60543

**Comment by anjanvb** [comment]
Wonderful.... Here's what I have using [usehooks-ts](https://github.com/juliencrn/usehooks-ts) native hooks implementation for dimension listener (responsive, and responds to resize).


```javascript
import React, { useState,  useMemo } from 'react';
import { useElementSize } from 'usehooks-ts';

const [pageWidth, setPageWidth] = useState(0);
const [pageHeight, setPageHeight] = useState(0);
const [ref, { width: wrapperWidth, height: wrapperHeight }] = useElementSize(); 

const fitHorizontal = useMemo(() => {
        const wRatio = pageWidth / wrapperWidth ; 
        const hRatio = pageHeight / wrapperHeight;
        if (wRatio < hRatio) {
          return false;
        }
        return true;
}, [pageHeight, pageWidth, wrapperWidth, wrapperHeight]);

<div ref={ref} className="container">
    <Document>
        <Page
              key="page"
              onLoadSuccess={(page) => {
                       setPageWidth(page.width);
                       setPageHeight(page.height);
                }}
              width={fitHorizontal ? wrapperWidth : null}
              height={!fitHorizontal ? wrapperHeight : null}
              scale={scale}
      />
    </Document>
</div>
```

CSS

```css
.container {  
    height: 100%;
    width: 100%;
    overflow: auto;
    background: #ECEFF1;
    border: 1px solid #ECEFF1;    
}
```

**Comment by daveleee** [comment]
> plementation for dimension listener (r

This is a great solution saved my time thanks!

**Comment by daveleee** [comment]
> Wonderful.... Here's what I have using [usehooks-ts](https://github.com/juliencrn/usehooks-ts) custom hooks implementation for dimension listener (responsive, and responds to resize).
> 
> ```js
> import React, { useState,  useMemo } from 'react';
> import { useElementSize } from 'usehooks-ts';
> 
> const [pageWidth, setPageWidth] = useState(0);
> const [pageHeight, setPageHeight] = useState(0);
> const [ref, { width: wrapperWidth, height: wrapperHeight }] = useElementSize(); 
> 
> const fitHorizontal = useMemo(() => {
>     const wRatio = pageWidth / wrapperWidth ; 
>     const hRatio = pageHeight / wrapperHeight;
>     if (wRatio < hRatio) {
>         return false;
>     }
>     return true;
> }, [pageHeight, pageWidth, wrapperWidth, wrapperHeight]);
> 
> <div ref={ref} className="container">
>     <Document>
>         <Page
>             key="page"
>             onLoadSuccess={(page) => {
>                        setPageWidth(page.width);
>                        setPageHeight(page.height);
>             }}
>             width={fitHorizontal ? wrapperWidth : null}
>             height={!fitHorizontal ? wrapperHeight : null}
>             scale={scale}
>         />
>     </Document>
> </div>
> ```
> 
> CSS
> 
> ```css
> .container {  
>     height: 100%;
>     width: 100%;
>     overflow: auto;
>     background: #ECEFF1;
>     border: 1px solid #ECEFF1;    
> }
> ```

@anjanvb This is a great solution saved my time thanks!
