### ISSUE TITLE
Render full screen

### ISSUE THREAD

**Issue by emorling** [wojtekmaj/react-pdf#719]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Is it possible to display the PDF in full screen? I don't mean to fill the edges of the browser, but rather the entire screen.

It seems to be available in PDF.js: https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by wojtekmaj** [comment]
React-PDF is not a PDF viewer. It's merely a tool to build one.

You'll have to use https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API to make your page work fullscreen.
