### ISSUE TITLE
UnknownErrorException SyntaxError: Unexpected token % in JSON at position 0

### ISSUE THREAD

**Issue by dgkm** [wojtekmaj/react-pdf#720]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

We are able to successfully render the local file using the import.  However when we try to display the remote file based on the URL e.g, https://d1.awsstatic.com/whitepapers/AmazonS3BestPractices.pdf, we are getting either of the following errors:

- Unexpected token % in JSON at position 0 - on  Chrome browser
- Unexpected character at line 1 and column 1 - on Firefox

On both the browsers we can notice on the developer console that the remote file is getting downloaded without any problem.

**Steps to reproduce**

Using "react-pdf": "^5.1.0",

```
  function onDocumentLoadSuccess({ numPages: nextNumPages }) {
    setNumPages(nextNumPages);
  }

  const onLoadError = (error) => {
    console.log('Error while loading document! ', error)
  }

...
...
<Document
            file={"https://d1.awsstatic.com/whitepapers/AmazonS3BestPractices.pdf"}
            onLoadSuccess={onDocumentLoadSuccess}
            onLoadError={onLoadError}
            options={options}
          >
            <Page
              pageNumber={1}
            />
</Document>
```

In the end the PDF loading is failing with the UnknownException and the JSON.parse syntax error as mention above.

Looks like an issue with the pdf.js worker, however unable to find any information on the internet.

**Expected behavior**

What you expected to happen?

**Additional information**
![image](https://user-images.githubusercontent.com/2730311/106483523-9fb1b500-64d4-11eb-8391-27b4b9766d3b.png)

**Environment**

 - Browser (if applicable) [Chrome: Version 88.0.4324.96 (Official Build) (x86_64), Firefox 4.0.2 (64-bit)]
 - React-PDF version [5.0.1]:
 - React version [@16.12.0]:
 - Webpack version [4.43.0]:

**Comment by wojtekmaj** [comment]
I'm unable to reproduce.

https://codesandbox.io/s/react-pdf-remote-url-025lu

**Comment by 15270877438** [comment]
I had the same problem.

**Comment by 15270877438** [comment]
I had the same problem.
1. React-PDF version [5.2.0]
2. React version [@16.8.6]

To solve the
