### ISSUE TITLE
Unable to use certain Google Fonts

### ISSUE THREAD

**Issue by guisers** [wojtekmaj/react-pdf#722]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

The "Inter" Google Font does not work. There are missing letters.

**Steps to reproduce**

A minimally reproducible example:
```
import { Document, Font, Page, PDFViewer, StyleSheet, Text } from '@react-pdf/renderer'
import React from 'react'

Font.register({
  family: 'Inter',
  src: 'https://fonts.gstatic.com/s/inter/v3/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZg.ttf',
})

Font.register({
  family: 'Roboto',
  src: 'https://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5Q.ttf',
})
const styles = StyleSheet.create({
  inter: {
    fontFamily: 'Inter',
  },
  roboto: {
    fontFamily: 'Roboto',
  },
})
export const MinimalReproducibleExample = () => (
  <PDFViewer width='100%' height='800'>
    <Document>
      <Page size='A4'>
        <Text style={styles.inter}>abcdefghijklmnopqrstuvwxyz</Text>
        <Text style={styles.roboto}>abcdefghijklmnopqrstuvwxyz</Text>
      </Page>
    </Document>
  </PDFViewer>
)

```

Rendering the above results in:
![image](https://user-images.githubusercontent.com/8797909/107077989-a9306b00-67bb-11eb-8434-618cc1d8eb16.png)

No console errors.

As you can see, Roboto works fine but Inter is missing letters.

**Expected behavior**

All google fonts should work

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser: Chrome 88, Firefox 72 (both don't work)
 - React-PDF version: 1.6.13
 - React version: 17.0.1
 - Webpack version: 4.16.1
 - Storybook: 5.3.19 (for rendering the example)

**Comment by wojtekmaj** [comment]
Wrong repo, see README
