### ISSUE TITLE
Input document to `PDFDocument.load` is encrypted. Opens up normally in any other reader.

### ISSUE THREAD

**Issue by KrynaS** [wojtekmaj/react-pdf#724]
Hello, just encountered problem that some of the PDFs do not load properly, lib is complaining about encryption, while any other readers works fine and can open PDF.

What I'm getting:
"Input document to `PDFDocument.load` is encrypted. You can use `PDFDocument.load(..., { ignoreEncryption: true })` if you wish to load the document anyways."

I didn't find an option to pass that flag in <Document> tag

**Comment by wojtekmaj** [comment]
This seems like it's coming from pdf-lib, not react-pdf.

https://github.com/Hopding/pdf-lib#encryption-handling

**Comment by anaguit** [comment]
o pudiste solucionar? me está pasando que hice u copilado de pdf con pdf-lib y si llega un pdf encriptado no me funciona. En el caso que le agregue { ignoreEncryption: true } al pdfDocument.load() que tiene el documento encriptado deja las hojas de ese archivo en blanco en el archivo copilado

**Comment by nedovleonid1** [comment]
I have same issue, `PDFDocument.load` is encrypted but is not. Any solution?

**Comment by wojtekmaj** [comment]
Any reproducible example?

**Comment by nedovleonid1** [comment]
try this pdf

[buletin_2022_4_18_2022_6758_6758_2022.pdf](https://github.com/wojtekmaj/react-pdf/files/9433464/buletin_2022_4_18_2022_6758_6758_2022.pdf)

**Comment by harish-cynch** [comment]
I have the same issue with a doc that has sensitive info. So can't share it here. But the [above PDF](https://github.com/wojtekmaj/react-pdf/files/9433464/buletin_2022_4_18_2022_6758_6758_2022.pdf) is a good example of where a non-encrypted doc is still being interpreted by `PDFDocument.load` as encrypted

**Comment by harish-cynch** [comment]
> I have the same issue with a doc that has sensitive info. So can't share it here. But the [above PDF](https://github.com/wojtekmaj/react-pdf/files/9433464/buletin_2022_4_18_2022_6758_6758_2022.pdf) is a good example of where a non-encrypted doc is still being interpreted by `PDFDocument.load` as encrypted

I digged a bit more. The reason it's happening is that these docs are still open password protected to prevent edits while most PDF viewers can actually still render them without password. A quick solution is to 

1. Use a chrome browser PDF viewer to open the PDF that's getting the error
2. Click `Print`
3. Select `Save as PDF` instead of actually printing a physical output
4. The saved PDF will not be password protected and can be used without this issue

**Comment by agamm** [comment]
```
await PDFDocument.load(fileBuffer, {
   ignoreEncryption: true,
});
```

**Comment by ianmartorell** [comment]
I tried using `ignoreEncryption` to load the PDF anyway, but copying pages from it results in blank pages. Shouldn't that work as I'm only reading and not editing the PDF?

**Comment by agamm** [comment]
It still behaves funky to me, it would be good to just be able to read the contents or pass a password to decrypt it for reading.

**Comment by wojtekmaj** [comment]
@agamm You can try passing ignoreEncryption to options prop, while to provide password, use onPassword callback.

**Comment by ianmartorell** [comment]
In my case I want to split a PDF in multiple files. I don't have the password but that's just for editing the file, and I know I can read it because I can open it in a viewer, so my thinking is I should be able to load it to extract pages as well. Is that wrong?

**Comment by MaxiSanchez600** [comment]
Same issue, it just doesnt make sense not to be able to load the pages if the PDF is protected just for editing.
