### ISSUE TITLE
Please split named exports into separate files to have possibility to lazy load react-pdf library

### ISSUE THREAD

**Issue by mariia-kulakova** [wojtekmaj/react-pdf#725]
It would be great to import not just in this way:
`import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';`
but also something like:
```
import Document from '@react-pdf/renderer/Document';
import Page from '@react-pdf/renderer/Page';
...
```
to have a possibility to lazy load react-pdf library

**Comment by wojtekmaj** [comment]
Wrong repo, see https://github.com/wojtekmaj/react-pdf#lost
