### ISSUE TITLE
Chrome (iOS): The File Could Not Be Downloaded at This Time

### ISSUE THREAD

**Issue by lbourbon** [wojtekmaj/react-pdf#726]
**Before you start - checklist**

 - [✅ ] I have read documentation in README
 - [✅ ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [ ✅  ] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

 When I try to download pdf on Chrome for iOs, an error message appears: "The File Could Not Be Downloaded at This Time"
It works fine on Safari(mobile) and desktop (both Chrome and Safari), but doesn't work on Chrome for iPhone. Anyone having the same issue? Any idea? Thanks in advance

**Describe solutions you've tried**

I've tried both PDFDownloadLink and BlobProvider with the same results.

**Environment**

 - Browser (if applicable) [Chrome iOs Mobile]:
 - React-PDF version [5.1.0]:
 - React version [e.g. 16.13.1]:

**Comment by wojtekmaj** [comment]
Downloading PDFs isn't part of React-PDF.
