### ISSUE TITLE
Shadow when highlighting

### ISSUE THREAD

**Issue by Akaban** [wojtekmaj/react-pdf#727]
**Before you start - checklist**

 - [x ] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

When I highlight any text on the rendered PDF the text is duplicated all over the highlighting, making it unreadable. Since this does not happen on online demos of react-pdf that I can find on the net I expected the problem to be related to versions. But I used many differents versions of react-pdf and pdf.js and nothing seem to fix the problem.

This problem is referenced as well in #132 , where the last post is refereing to the same problem.

This is probably related to upstream (pdf.js).

**Steps to reproduce**

1. Load a PDF using React PDF
2. Highlight some text
3. Text is duplicated all over the highlighting

**Expected behavior**

I didn't expect text to be duplicated

**Additional information**

![Capture de 2021-02-11 12:03:31](https://user-images.githubusercontent.com/10995524/107634834-0f0c6f00-6c62-11eb-9f7d-e493d8acb860.png)

**Environment**

 - Browser (if applicable): google-chrome 88.0.4324.150-1 and firefox 85.0.2-1
 - React-PDF version: 5.1.0
 - React version : 17.0.1

**Comment by zhzhang** [comment]
Hello @Akaban, I'm now running into this issue as well, did you find a resolution to it?

**Comment by Akaban** [comment]
Hello,

Yes in my case it was because of CSS rules that I was importing from my CSS framework semantic-ui. I figured it out after disabling every CSS rule one by one. So maybe that can be the same for you, try to disable every CSS rule and I think that you could even do it from your browser.

Best luck !

**Comment by snimstice** [comment]
Hello.@AKaban, I want to know that how did you highlight some text on the canvas(in your steps 2). thanks
