### ISSUE TITLE
No proper error log

### ISSUE THREAD

**Issue by hurkanyakay** [wojtekmaj/react-pdf#73]
I am trying to load pdf.js example file: [https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf](https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf)
but example only shows

> Failed to load PDF file.

I also tried webpack version of worker but i don't get it why it is failing. I wish there is something in the logs about failure.

**Comment by wojtekmaj** [comment]
Hey @hurkanyakay,
thanks for your report.
The message you're getting is intended for end users, not for developers. Should you want to read detailed error messages, potentially catch them and/or log them with your automatic error reporting, please use the callbacks we have set up in case of an error. For instance, `<Document />` has the following:

* onLoadError
* onSourceError

Please see the documentation for the full explanation and example of use.

Also you can check against my official [test suite](http://projekty.wojtekmaj.pl/react-pdf/test/) that should work just fine. If THAT is not working, then we definitely have an issue with either React-PDF itself or with Mozilla's PDF.js. In that case, I'd much appreciate a report :)

**Comment by wojtekmaj** [comment]
Hey @hurkanyakay,
I've decided to answer for you and I felt like all these callbacks were really not enough. So I'm happy to say that in version 2.1.4 all errors are thrown in the console, as long as you are on development build. :)

If you have any more issues, let me know!
