### ISSUE TITLE
onRenderSuccess  return   PDFPageProxy.view with negative height

### ISSUE THREAD

**Issue by druzhchenko** [wojtekmaj/react-pdf#730]
**Before you start - checklist**

 - [+] I have read documentation in README
 - [+] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [+] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I have one problem document, when onRenderSuccess callback return  PDFPageProxy with "view" field where height is negative value like this [0, 0, 612, -792].  Other documents return it correct like this [0, 0, 612, 792]. I can't understand what is the reason?

**Describe solutions you've tried**

I tried change version react-pdf and react. Еach time I had same result.

**Environment**

 - Browser Chrome 88:
 - React-PDF version 3x and 5x:
 - React version [e.g. 16.8.0]:

**Comment by wojtekmaj** [comment]
`PDFPageProxy.view` comes directly from Mozilla's pdf.js and I can't tell you why exactly you see that. Perhaps it has to do with the software that encoded the PDF.

However, you also have `PDFPageProxy.width`/`height`/`originalWidth`/`originalHeight` which should return positive numbers at all times. If that's not the case, and I think it might not be, we'll fix these params. `view`, however, will be left untouched.

**Comment by druzhchenko** [comment]
Thanks I got it. I checked "height" it also is negative but it is another value who depends on the scale. For example if view[3] = -500 and scale 2 then height = -1000.
Strange but page render goes without problem.
Formally negative height value I may will convert to positive. It solve my problem right now. But I'm not sure that this will not lead to problems in the future.
