### ISSUE TITLE
canvasRef is undefined on first render

### ISSUE THREAD

**Issue by JannikSt** [wojtekmaj/react-pdf#731]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

We use the canvasRef to render the pdf to a video stream. Unfortunately the ref.current stays undefined on the first render and gets defined on the second render (e.g. when you switch the page). 

**Steps to reproduce** 
We simply added an effect that runs on the change of pdfRef.current. When we change the pagenumber of a multipage pdf the pdfRef changed console log is fired with a canvas element. 
The page itself renders fine on every try. 
```
const pdfRef = React.useRef() 

useEffect(() => {
    console.log("pdfRef changed ", pdfRef)
  }, [pdfRef.current]) 

 <Document
    file={pdfContent}
    onLoadSuccess={({ numPages }) => {
      setNumPages(numPages); 
      setDocumentLoaded(true);
    }}
  >
  // @ts-ignore
  <Page pageNumber={pageNumber} canvasRef={pdfRef} onRenderSuccess={() => console.log('Render success')} />
</Document> 
```

**Expected behavior**
The canvasRef.current should be defined on the first render. 

**Environment**

 - Browser (if applicable): Firefox 85
 - React-PDF version: 5.2.0
 - React Version: 17.0.1

**Comment by wojtekmaj** [comment]
It's not valid to use refs as useEffect dependency, so this won't work the way you intend it to. If it works for you in other places it is by pure luck.

https://twitter.com/dan_abramov/status/1093497348913803265

**Comment by JannikSt** [comment]
Thank you @wojtekmaj, 
we were able to resolve this using a callback.

**Comment by virinchi-manepalli-trysolvio** [comment]
if you want to access the canvas ref of a page just do 
create an useRef 
`const pageRef = useRef<HTMLCanvasElement>(null!);`

add pageRef inside <Page/> 
`<Page pageNumber={pageNumber} canvasRef={pageRef} />`

using GetRef function you can Canvas reference , in my case I m getting base64 of particular page using canvas Ref.

```
 const GetRef = () => {
     if (pageRef !== null) {
       const dataURL: any = pageRef?.current?.toDataURL("image/png");
     }
   };

```
