### ISSUE TITLE
React-pdf always bundling pdf.js worker

### ISSUE THREAD

**Issue by jljorgenson18** [wojtekmaj/react-pdf#733]
**Description**

With the recent update to 5.1.0 (https://github.com/wojtekmaj/react-pdf/commit/eec72c5da2c83342732cdebfb64885c45534804e), the import for pdfjs was updated to use a star import

`import * as pdfjs from 'pdfjs-dist';`

If you consume react-pdf by supplying your own worker inside of the Document options, then this means you are adding a ton of extra bulk to your builds. This did not appear to be a problem in 5.0.0 (though I may need to confirm that).

**Expected behavior**

The pdf.js worker should only be bundled if you are using one of the standard entry points.

**Additional information**

The extra, unused worker bundle:

<img width="480" alt="Screen Shot 2021-02-18 at 3 44 18 PM" src="https://user-images.githubusercontent.com/5751354/108425668-64b3bf00-7200-11eb-81dc-879909a74a36.png">

Our own worker bundle:

<img width="390" alt="Screen Shot 2021-02-18 at 3 44 32 PM" src="https://user-images.githubusercontent.com/5751354/108425705-6f6e5400-7200-11eb-8fa3-0b1166935194.png">

**Environment**

 - React-PDF version [5.2.0]:

**Comment by wojtekmaj** [comment]
Please do confirm that because I'm pretty sure that this was the behavior before, too. And the reason for that was that if React-PDF fails to load the worker, it launches a "fake" worker that does worker's job, using, you guessed it, exactly the same code. So yeah, I'm not surprised that the worker code is bundled twice.

**Comment by jljorgenson18** [comment]
Sorry for any confusion here, but I'm seeing mixed results and I'm trying to figure out why. I have bundler analyzer screenshots from back in April 2020 showing it bundled once (which would have been v4.1.0) but if I downgrade pdfjs and react-pdf, I now see two bundles. I'll try to figure out why.

I think regardless though, it would be great if there was an entry point that somehow skipped including the worker. I'm not sure how that could be done but it's fairly inconvenient to double load pdfjs, especially when you use pdfjs outside of this library. I was trying to also get something working with the webpack IgnorePlugin but I haven't been able to hook that up yet.

Maybe if I can get that IgnorePlugin approach working, we could add something to docs that shows how not to bundle the pdfjs worker?

**Comment by jljorgenson18** [comment]
Yea I'm not sure how the IgnorePlugin approach will work. I can investigate a bit more tomorrow and try to figure out how it was even working to begin with and I'll try to find a potential workaround. I'm open to suggestions if you guys want a general solution in react-pdf as I'm sure this might affect others, but I can try to just get a workaround without a change in react-pdf in the meantime.

**Comment by jljorgenson18** [comment]
Ok, sorry about this. Turns out, our worker loader was generating an inline fallback (hence the double loading). This is an issue on our end and I apologize for any confusion.
