### ISSUE TITLE
AnnotationLayer error and not sure why that is

### ISSUE THREAD

**Issue by resistorsoftware** [wojtekmaj/react-pdf#735]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

React-PDF 5.2

Trying to display some Base64 PDF as a document, but getting this instead:

    ./node_modules/react-pdf/dist/esm/Page/AnnotationLayer.js 195:8-29
    "export 'AnnotationLayer' (imported as 'pdfjs') was not found in 'pdfjs-dist'

followed by numerous other errors... 

    ERROR in ./node_modules/react-pdf/dist/esm/eventBus.js 2:19-27
    15:26:11 webpack.1 | "export 'EventBus' was not found in 'pdfjs-dist/lib/web/ui_utils'

    ERROR in ./node_modules/react-pdf/dist/esm/entry.webpack.js 14:2-27
    15:26:11 webpack.1 | "export 'GlobalWorkerOptions' (imported as 'pdfjs') was not found in 'pdfjs-dist'

My setup code in my JSX file is:

    import { Document } from 'react-pdf/dist/esm/entry.webpack';
    import 'react-pdf/dist/Page/AnnotationLayer.css';

My Component looks like this:

 <Document file={`data:application/pdf;base64,${data}`}>

What am I doing wrong to earn that message about AnnotationLayer and all the other problems?

My package.json shows yarn installed the package:

       "react-pdf": "^5.2.0",

**Comment by StevenGoland** [comment]
Your error has the correct path, but you're saying the JSX is import 'react-pdf/dist/Page/AnnotationLayer.css';

It should be: import 'react-pdf/dist/**esm**/Page/AnnotationLayer.css';

**Comment by resistorsoftware** [comment]
I do not know how that happened, but the error occurs with these exact paths. 

    import { Document } from 'react-pdf/dist/esm/entry.webpack';
    import 'react-pdf/dist/esm/Page/AnnotationLayer.css';

So as you can see, I am using the path as per the ESM aspect...

**Comment by resistorsoftware** [comment]
So no one else ever gets this error. I am not amused. How do I run into these kinds of issues... yay!! I figured out how to render a PDF without this node package. In the meantime... was hoping anyone had some advice about what might be causing this package to die this way.

**Comment by vvav3** [comment]
@resistorsoftware you are not alone. I am also getting this error, but I don't even import AnnotationLayer.css anywhere. Local development works but it breaks build.

**Comment by resistorsoftware** [comment]
@vvav3 Thank you for confirming that I am not alone in this. Means alot to me.!!

**Comment by leandrocrs** [comment]
> @resistorsoftware you are not alone. I am also getting this error, but I don't even import AnnotationLayer.css anywhere. Local development works but it breaks build.
> 
> Edit: it happens if I use "craco" to override CRA config.
> 
> ```
> // craco.config.js
> const path = require('path');
> const { getLoader, loaderByName } = require('@craco/craco');
> const absolutePath = path.join(__dirname, '../uikit');
> 
> module.exports = {
>   webpack: {
>     alias: {},
>     plugins: [],
>     configure: (webpackConfig, { env, paths }) => {
>       const { isFound, match } = getLoader(webpackConfig, loaderByName('babel-loader'));
>       if (isFound) {
>         const include = Array.isArray(match.loader.include)
>           ? match.loader.include
>           : [match.loader.include];
>         match.loader.include = include.concat[absolutePath];
>       }
>       return webpackConfig;
>     }
>   }
> };
> ```

Exact same situation here: CRACO

**Comment by leandrocrs** [comment]
I don't exactly why, but it seems to be a question of order.

Inverting the order of includes solved the issue for me:

```js
const path = require('path');

const { getLoader, loaderByName } = require('@craco/craco');

const absolutePath = path.join(__dirname, '../shared');

module.exports = {
	webpack: {
		alias: {},
		plugins: [],
		configure: (webpackConfig, { env, paths }) => {
			const { isFound, match } = getLoader(webpackConfig, loaderByName('babel-loader'));
			console.log({ isFound, match });

			if (isFound) {
				const include = Array.isArray(match.loader.include)
					? match.loader.include
					: [match.loader.include];
                                 // this way I put my includes at beginning
				match.loader.include = [absolutePath].concat(include);
			}

			return webpackConfig;
		},
	},
};
```

**Comment by mattzuckermann** [comment]
I'm having the same issue getting this error on react-pdf 5.3.0 without having imported AnnotationLayer.css.

**Comment by ndnenkov** [comment]
I was having the same issue using Webpacker. [This](https://github.com/wojtekmaj/react-pdf/issues/659#issuecomment-720351158) solved it for me.

**Comment by IrinaVolkhonskaya** [comment]
> Так что больше никто не получает эту ошибку. Я не удивлен. Как мне столкнуться с подобными проблемами ... ура !! Я понял, как визуализировать PDF без этого пакета узлов. А пока ... надеялся, что у кого-нибудь есть совет о том, что могло стать причиной такой смерти этого пакета.
> 
> Просто перепроверил, и даже когда я думаю, что это могло быть связано с чем-то еще, нет ... все еще озадачен. Не компилируется вообще.
> 
> ОШИБКА в ./node_modules/react-pdf/dist/esm/Page/AnnotationLayer.js 195: 8-29
> 09:35:23 webpack.1 | "экспорт 'AnnotationLayer' (импортированный как 'pdfjs') не был найден в 'pdfjs-dist'

у меня такая же сейчас ошибка. всю сборку ломает.
Можете поделиться Вашим решением "как визуализировать PDF без этого пакета узлов"

**Comment by wojtekmaj** [comment]
Use English please.

**Comment by IrinaVolkhonskaya** [comment]
> Use English please.

Sorry)
I writed, that I have the same problem.

**error  in ./node_modules/react-pdf/dist/esm/Page/AnnotationLayer.css

Module parse failed: Unexpected token (16:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders       
|  */**

and I get a mistake: **webpack-dev-server/client?http://localhost:undefined**

I dont understand what happens

**Comment by wojtekmaj** [comment]
That seems like a different issue. Please have a look: https://github.com/wojtekmaj/react-pdf/issues?q=%22Module+parse+failed%22

**Comment by IrinaVolkhonskaya** [comment]
> That seems like a different issue. Please have a look: https://github.com/wojtekmaj/react-pdf/issues?q=%22Module+parse+failed%22

ok. thanks a lot

**Comment by EngineersWorld475** [comment]
Warning: TextLayer styles not found. Read more: https://github.com/wojtekmaj/react-pdf#support-for-text-layer - i have gone through multiple solutions. can not figure out what is happening

**Comment by sedhha** [comment]
For the version ^10.1.0 and above:
```
import 'react-pdf/dist/Page/AnnotationLayer.css';
import 'react-pdf/dist/Page/TextLayer.css';
```
worked for me.

**Comment by JosephRana11** [comment]
> For the version ^10.1.0 and above:
> 
> ```
> import 'react-pdf/dist/Page/AnnotationLayer.css';
> import 'react-pdf/dist/Page/TextLayer.css';
> ```
> 
> worked for me.

Worked me for me too. Thanks
