### ISSUE TITLE
Regression from 4.2.0 to 5.2.0 in loading pdf from ArrayBuffer?

### ISSUE THREAD

**Issue by Sharcoux** [wojtekmaj/react-pdf#737]
**Before you start - checklist**

 - [*] I followed instructions in documentation written for my React-PDF version
 - [*] I have checked if this bug is not already reported
 - [*] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [*] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Short description of the bug you encountered.

Updating the version from 4.2.0 to 5.2.0 broke my code, but I couldn't find anything about a breaking change in the doc.

**Steps to reproduce**

1. get the pdf file content as `content`
2. return `<Document file={Buffer.from(content, 'binary').buffer}><pageNumber={1} /></Document>`
3. Try with v4.2.0 -> works
4. Try with v5.2.0 -> failed to load pdf file

If it's necessary I can try to create a project to reproduce

**Expected behavior**

What you expected to happen?

Should show the pdf in the last version

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Firefox 86.0 (64 bits)
 - React-PDF version [e.g. 3.0.4]: 5.2.0
 - React version [e.g. 16.3.0]: 16.13.1
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.44.1

**Comment by wojtekmaj** [comment]
Could you also check 5.1.0? I have some suspicion.

If that doesn't work, I'd appreciate CodeSandbox repro to work on.

**Comment by Sharcoux** [comment]
@wojtekmaj I've just tried with 5.1.0 and 5.0.0 to no avail. I'll try to create a repro. I'm just not sure if I can do it this week. Thanks a lot ;)

**Comment by peterdee** [comment]
Hi. I am using version 5.2.0 and I have the same issue.

My use-case is the following: I've got an Electron app that loads the PDF file as `Unit8Array` and then I pass this loaded PDF to the renderer (i. e. my React component).

I get infinite loading when doing so.

The data itself is passed properly.

What is the best solution here? Should I downgrade to version 4.2.X for now?

**Comment by Sharcoux** [comment]
I forgot about this issue.
Try downgrading. If it solves the issue, it's the same thing, but I'm not sure that it is really the same.

**Comment by peterdee** [comment]
@Sharcoux 
I've tried version 4.2.0, it's working as expected.

**Comment by Sharcoux** [comment]
Actually, I was using a non-matching version of pdf.worker.js. I'm still not sure on how and why. But using the mentioned import for webpack users quickly solved the issue:

![image](https://user-images.githubusercontent.com/797545/132104437-718bb3fc-ec07-401c-8ace-41776a15ce3b.png)
