### ISSUE TITLE
Positioning of text layer inconsistent with canvas on given sample

### ISSUE THREAD

**Issue by jvhoffbauer** [wojtekmaj/react-pdf#738]
First of all: Thanks for creating this library, it is just an awesome project! 

Positioning of text layer is inconsistent with the canvas. It seems to be centred, while the canvas is left bound. Thus copying does not work. See screenshots. 
My code is basically the sample given in this repository with the react-pdf package installed via npm. Also, I am pretty new to web development so I am not exactly sure if this is some stupid mistake on my side, but I tried to follow your instructions as thorough as possible. 

**Steps to reproduce**

1. Clone https://github.com/jvhoffbauer/textlayer_problem_reproducer
2. `npm install` and `npm start` the project

**Expected behavior**

Text layer should align perfectly with the canvas, so that copying works nicely

**Additional information**

<img width="400" alt="Screenshot 2021-03-01 at 00 03 58" src="https://user-images.githubusercontent.com/9884254/109437165-c277b080-7a23-11eb-8641-54c17c183659.png">
<img width="400" alt="Screenshot 2021-03-01 at 00 03 20" src="https://user-images.githubusercontent.com/9884254/109437170-c86d9180-7a23-11eb-92e1-2e4aaf816e53.png">

**Environment**

 - Browser Chrome: 88.0.4324.192 (Official Build) (x86_64)
 - Browser Firefox: 86.0 (64-bit)
 - React-PDF version "^5.2.0"
 - React version "^17.0.1"
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by jvhoffbauer** [comment]
When deselecting the `position: absolute` and transform: `translate(-50%, -50%) rotate(0deg)` in the style of the text layer div, it works nicely. See screenshot. 

![Uploading Screenshot 2021-03-01 at 00.55.38.png…]()

I could also reproduce the same error with directly running the provided sample.

**Comment by jvhoffbauer** [comment]
Solved. Most probably the error was, that the styles were not loaded properly.

**Comment by frdwhite24** [comment]
I'm also experiencing this problem @SmrutiSikha, i'll update here if I find a solution. Did you find a solution?

**Comment by frdwhite24** [comment]
> @jvhoffbauer Hi, can you tell me how you solved the problem?

i thought maybe [this](https://github.com/wojtekmaj/react-pdf/issues/556#issuecomment-874648471) might solve it, but it didn't for me
