### ISSUE TITLE
During printing a PDF file which is added into iFrame on the fly, does not render in browser previewer.

### ISSUE THREAD

**Issue by amigup** [wojtekmaj/react-pdf#739]
**Before you start - checklist**

 - [ x] I have read documentation in README
 - [ x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [ x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
Unable to print the PDF being rendered.

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.

I've a website where PDF file is being displayed using react-pdf. I want to provide the option to user to print the PDF file so I've used a hidden iFrame and on the fly setting the content of it as shown below in the code:

Code :

```
import React, { useState } from 'react';
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';

import './Sample.less';

const options = {
  cMapUrl: 'cmaps/',
  cMapPacked: true,
};

export default function Sample() {
  const [file, setFile] = useState('./sample.pdf');
  const [numPages, setNumPages] = useState(null);
  const [contentRef, setContentRef] = useState(null)
  const ref = React.useRef();

  function onFileChange(event) {
    setFile(event.target.files[0]);
  }

  function onPrint() {
    contentRef.contentDocument.write(ref.current.innerHTML);
    contentRef.contentWindow.print();
  }

  function onDocumentLoadSuccess({ numPages: nextNumPages }) {
    setNumPages(nextNumPages);
  }

  return (
    <div className="Example">
      <header>
        <h1>react-pdf sample page</h1>
      </header>
      <div className="Example__container">
        <div className="Example__container__load">
          <label htmlFor="file">Load from file:</label>
          {' '}
          <input
            onChange={onFileChange}
            type="file"
          />
          <button onClick={onPrint} type="button">Print</button>

        </div>
        <div className="Example__container__document">
          
        <p>Pages {numPages}</p>
          <Document
            inputRef={ref}
            file={file}
            onLoadSuccess={onDocumentLoadSuccess}
            options={options}
          >
            {
              Array.from(
                new Array(numPages),
                (el, index) => (
                  <Page
                    key={`page_${index + 1}`}
                    pageNumber={index + 1}
                  />
                ),
              )
            }
          </Document>

          <iframe
            ref={setContentRef}
      ></iframe>
        </div>
      </div>
    </div>
  );
}
```

On click on Print, the content is added in iFrame's Content window but when browser print dialog appears then every thing displayed as white screen in previewer.

**Additional information**

![image](https://user-images.githubusercontent.com/16287600/109976701-1505e500-7d22-11eb-8964-69bacb55cd97.png)

Screenshot of sample application when renders:
![image](https://user-images.githubusercontent.com/16287600/109977451-d6245f00-7d22-11eb-9eb5-ff0f06d02f78.png)

**Environment**

 - Browser (if applicable) - Chrome 88 / Edge 88
 - React-PDF version -  latest:
 - React version - ^17.0.0
 - Webpack version  - latest

**Comment by wojtekmaj** [comment]
That doesn't look like it should work.. cloning HTML won't clone canvas contents. 
You _might_ get a little bit more lucky with SVG renderMode (try it!).

**Comment by amigup** [comment]
Thanks @wojtekmaj for your input. The SVG also does not render. Following is the output of using svg as renderMode.

![image](https://user-images.githubusercontent.com/16287600/110066764-3e615800-7d98-11eb-8db8-e8b30ec4d847.png)

Is there way to achieve to print file being rendered in Document?

**Comment by amigup** [comment]
@wojtekmaj - following on this old thread. Is it possible to hook into PDF.js print service and to initiate the print of loaded PDF (without creating any additional iFrame and cloning the HTML)?

**Comment by sm3sher** [comment]
I would also be interested in a solution for this, I have the exact same case.

**Comment by sm3sher** [comment]
@amigup I reproduced your example with canvas rendering mode and found out that the pages appear to be white cause of the auto generated inline style of the textContent `color: transparent`. If you turn them black you can see the text.

**Comment by sm3sher** [comment]
I am using print.js instead. You can pass in the pdf as url or base64 and it works on all browsers except IE.

**Comment by amigup** [comment]
@sm3sher - is print.js another package?
