### ISSUE TITLE
Setting dynamic scale based on page width

### ISSUE THREAD

**Issue by atermenji** [wojtekmaj/react-pdf#74]
### Description
I want to scale PDF pages dynamically, based on page width and parent container `<div/>` width.
### Question
Is this possible?
### What I've tried
* I've added `scale` variable to a state.
* Then I recalculate scale in `onPageLoad()`
* scale is calculated correctly but page is not rerendered correctly. Page component `render` is invoked but canvas is not being repaint.
* When I change page, second page is being rendered correctly if scale was not changed.
Code for my component below:
```jsx
export default class PdfDocument extends React.PureComponent {
  constructor(props) {
    super(props);

    this.state = {
      numPages: null,
      pageNumber: 1,
      scale: 1.0
    };
  }

  // Custom pagination component
  onPageChange(pageNumber) {
    this.setState({ pageNumber: pageNumber + 1 });
  }

  onDocumentLoad({ numPages }) {
    this.setState({ numPages });
  }

  onPageLoad(page) {
    const parentDiv = document.querySelector('#pdfDocument')
    let pageScale = parentDiv.clientWidth / page.originalWidth
    if (this.state.scale !== pageScale) {
      this.setState({ scale: pageScale });
    }
  }

  render() {
    return (
      <div>
        <div id="pdfDocument">
          <Document
            file={url}
            onLoadSuccess={this.onDocumentLoad}
          >
            <Page
              pageNumber={this.state.pageNumber}
              onLoadSuccess={this.onPageLoad}
              scale={this.state.scale}
            />
          </Document>
        </div>
      </div>
    );
  }
}
```

**Comment by wojtekmaj** [comment]
> When I change page, second page is being rendered correctly if scale was not changed.

You mean that after changing the page, the next page is rendered correctly with the correct scale, or that scale is ignored entirely? Hope it's the second.

That's definitely a bug anyway. Thanks for reporting. I'll fix this in the next minor release.

**Temporary workaround**: Add ``key={`${this.state.pageNumber}_${thia.state.scale}`}`` to cheat React into replacing `<Page/>` element entirely when pageNumber or scale changes.

**Comment by atermenji** [comment]
@wojtekmaj thanks for the suggestion of adding `key`! it solved my problem. In the meantime I've opened a PR with this fix for `PageCanvas` - https://github.com/wojtekmaj/react-pdf/pull/75

**Comment by wojtekmaj** [comment]
Closed #74 via #75. Thanks/1

**Comment by wojtekmaj** [comment]
Hi, I've just added manual testing of `scale` option to my manual test suite found in `/test` directory, and everything appears to be working correctly. I think if you have an issue it may be a separate one, but I'll need to see some code of yours to tell something. Although I encourage you to have a look on test suite, maybe it will give you some ideas :)

**Comment by valerii-cognite** [comment]
Thank you for your reply, it seems I've been expected for `scale` to work started from specified `width`, which turned out both props should not be specified together since `width` will override `scale`. BTW test suite helped, but I can't make it work until I changed import from `'react-pdf/src/entry.webpack'` to `'react-pdf/dist/entry.webpack'` because of the error `Module parse failed: Unexpected token (23:8) You may need an appropriate loader to handle this file type.`

**Comment by ionizer** [comment]
on v4.0.5, there does not seem to be `page.originalWidth` in the `onLoadSuccess` callback object, and therefore unable to calculate scale from there

**Comment by wojtekmaj** [comment]
> BTW test suite helped, but I can't make it work until I changed import from `'react-pdf/src/entry.webpack'` to `'react-pdf/dist/entry.webpack'` because of the error `Module parse failed: Unexpected token (23:8) You may need an appropriate loader to handle this file type.`

Good. You shouldn't be using /src, until you are ready to build the code yourself ;)
