### ISSUE TITLE
How to access the value entered in the annotation layer?

### ISSUE THREAD

**Issue by ajaij** [wojtekmaj/react-pdf#740]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Access the user entered value in an interactive pdf file.

**Describe solutions you've tried**
Accessed the annotation layer using `onGetAnnotationsSuccess` prop when the page is loaded for the first time, but was not able to capture the form field values once entered.

**Additional information**
I have an interactive pdf, which basically acts as a form field, am trying to render the pdf using react-pdf and capture the values entered.

![Screenshot 2021-03-10 at 12 41 03 PM](https://user-images.githubusercontent.com/45552514/110590691-2295f180-819e-11eb-8351-c83e500673b5.png)

As you can see on the above image, I have entered `test` as the value for `Submission Identification Number`, which is highlighted in red color, now the problem is am not able to access the entered value. Similarly I have different type of inputs like checkbox, integer input, etc.

**_Question_:** Is there any function which I can use to get the user entered value from the annotation later ?

**Environment**

 - Browser [Firefox 86]:
 - React-PDF version [4.0.0]:
 - React version [16.12.0]:
 - Webpack version [3.8.1]:

**Comment by wojtekmaj** [comment]
I'm afraid interactive forms support in PDF.js is rather primitive at the time; to get form data you will need to use good ol' `document.querySelector` and his friends.

**Comment by ajaij** [comment]
@wojtekmaj I tried that as well, when targeting via querySelectorAll, the input value is "", even though I have entered some value. The weird thing is when I inspected the html I don't see the value appended in the html. I think the txt is sitting on a different layer, is there any other way access those values ?

**Comment by wojtekmaj** [comment]
Wrap it in form and iterate over fields inside. e.g. `formElement[0]`, `formElement[1]` and so on.
