### ISSUE TITLE
Page turn animation

### ISSUE THREAD

**Issue by BPouncey** [wojtekmaj/react-pdf#741]
What is the best approach to get a page turn animation onto my PDF Document? I have tried marrying the library with various flip book libraries with no luck. My client has requested it as a must have.

**Comment by wojtekmaj** [comment]
How would you do it for just plain images? Because React-PDF output isn't much different if you render multiple pages at once.

**Comment by BPouncey** [comment]
Thanks for the quick reply, I was looking at the following [example](https://nodlik.github.io/react-pageflip/) If somehow I can wrap all the output images in the **HTMLFlipBook** component.

**Comment by BPouncey** [comment]
@wojtekmaj Thanks for this, it's a great start. Yes some styling issues but I can work on it from here. Thanks for the help!

**Comment by wojtekmaj** [comment]
Make sure to share it later! Interesting topic :)1

**Comment by annjawn** [comment]
I am curious if there is a way to implement slide-in/out effect using something similar.
