### ISSUE TITLE
Viewing word documents

### ISSUE THREAD

**Issue by achamsanjeeva** [wojtekmaj/react-pdf#744]
Is there a plan to support the word document?
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

Describe what the problem is. Ex. I'd like to do […] with my PDFs.

**Describe the solution you'd like**

What you want to happen?

**Describe alternatives you've considered**

Describe alternative solutions or features you've considered, if any.

**Additional information**

**Comment by wojtekmaj** [comment]
No, it's for PDFs only.
