### ISSUE TITLE
Overflow hidden type declaration in Style interface

### ISSUE THREAD

**Issue by frivolta** [wojtekmaj/react-pdf#745]
**Before you start - checklist**

 - [ X ] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [ X ] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**
Having overflow property, it is working but is missing type declaration.

In my project a user can upload images and they can be put inside the pdf, since I wanted the user to be able to have images with a circular border I have figured out I can make a  View container with overflow hidden and inside a squared image that will be cut out by the view.

**Describe the solution you'd like**
Style should accept overflow parameter in ts since is already working.

**Describe alternatives you've considered**
It is already working on my project and on the live editor on pdf.org but I need to update the type declaration for the Style interface to accept: overflow?: string; otherwise compiler will complain.

**Additional information**

I can provide help making a pr on this issue.

**Comment by wojtekmaj** [comment]
Wrong repo, see https://github.com/wojtekmaj/react-pdf#lost
