### ISSUE TITLE
Document doesn't render in Safari.

### ISSUE THREAD

**Issue by hmarat** [wojtekmaj/react-pdf#750]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

In mobile safari my document is not rendering and I got this error:
  The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead.

**Environment**

 - Browser: Safari 14.1.4
 - React-PDF version: 5.1.0
 - React version: 17.0.1

**Comment by fefuzz** [comment]
I have the same problem.

**Comment by wojtekmaj** [comment]
Hmm, both ReadableStream and Promise.allSettled is supported on Safari 🤔 Will need to investigate.

**Comment by wojtekmaj** [comment]
Both Safari Desktop and Safari Mobile are working fine for me:

![Zrzut ekranu 2021-03-25 o 11 43 17](https://user-images.githubusercontent.com/5426427/112460529-4bea7c00-8d5f-11eb-85ad-431853435227.png)

![obraz](https://user-images.githubusercontent.com/5426427/112460559-5442b700-8d5f-11eb-99ad-1e9861562b99.png)

Can you also check newest beta release?

**Comment by fefuzz** [comment]
Hi, i have no problem with safari, but that error occurs in ghost browser

**Comment by fefuzz** [comment]
Hi have this error on my console using "canvas" mode:

**details:** "Error: The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead."
**message:** "The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead."
**name:** "UnknownErrorException"

but in react-pdf I don't see the possibility to use es5 mode.

**Comment by hmarat** [comment]
@wojtekmaj I solved it. The problem was not from react-pdf. The Document component was inside react custom scrollbars component, and the scrollbars was not working fine in Safari, so the document was invisible.

**Comment by hmarat** [comment]
> Hi have this error on my console:
> 
> **details:** "Error: The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead."
> **message:** "The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `ReadableStream` and/or `Promise.allSettled`); please use an ES5-compatible build instead."
> **name:** "UnknownErrorException"
> 
> but in react-pdf I don't see the possibility to use es5 mode.

Inside your project's node_modules folder find pdfjs_dist, then inside of folder find es5. Move the folders "build" and "web" into pdfjs_dist. It must solve the problem.
![image](https://user-images.githubusercontent.com/55658812/112553535-1cc71f80-8dde-11eb-9c7e-2bcaf093b3a4.png)

**Comment by dlouisenz** [comment]
I have the same issue:

`The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. ReadableStream and/or Promise.allSettled); please use an ES5-compatible build instead.`

I am running on `iphone6 ios 12.0`

Tried the beta version and getting `Can't find variable: globalThis`
