### ISSUE TITLE
responsive mobile

### ISSUE THREAD

**Issue by orsaada** [wojtekmaj/react-pdf#752]
hey, i try to make the pdf responsive to mobile view.
how should i make it responsive to screen size? through css ?
```
  const pdfWrapperRef = React.useRef();

  return (
    <div className="center" ref={pdfWrapperRef}>
      <Document file={samplePDF}>
        <Page
          width={
            pdfWrapperRef.current?.getBoundingClientRect().width * 0.95 ||
            undefined
          }
          // className="resume-pdf"
          pageNumber={1}
        />
      </Document>
    </div>
```

**Comment by wojtekmaj** [comment]
You're getting there, only React isn't informed about width change so you will get correct width only initially. You'll have to use ResizeObserver with useState to keep track of container width.

**Comment by mrciolino** [comment]
This worked for me (with assistance of chatgpt)

`const pdfWrapperRef = React.useRef();
const [width, setWidth] = React.useState();

React.useEffect(() => {
  const resizeObserver = new ResizeObserver((entries) => {
    for (const entry of entries) {
      setWidth(entry.target.clientWidth * 0.95);
    }
  });

  resizeObserver.observe(pdfWrapperRef.current);

  return () => {
    resizeObserver.disconnect();
  };
}, []);

return (
  <div className="center" ref={pdfWrapperRef}>
    <Document file={samplePDF}>
      <Page
        width={width || undefined}
        pageNumber={1}
      />
    </Document>
  </div>
);
`
