### ISSUE TITLE
<Image> When PDF is rendered some images seem to be rotated.

### ISSUE THREAD

**Issue by Maciek-Jarmula** [wojtekmaj/react-pdf#753]
Hello,

I am using React-PDF to create documents on the fly based on data passed to the React App from the API. When a document is generated it shows images (originally in portrait) flipped to the side and cropped/distorted slightly. I double-checked and images on the server are the right way up. I get a link for each image from the mentioned API and this is how they turn out.

![FlippedImages](https://user-images.githubusercontent.com/14071466/112825160-55d3ee00-9083-11eb-8ebf-a4f334ac4a2b.jpg)

Below you can see all the CSS I am using for the Image tag:
`
      width: '75px',
      height: '100px',
      marginBottom: '10px',
      marginLeft: '5px',
`

I assume adding rotation to the image may solve the problem to some extent, but it just seems counter-intuitive, plus there still is the issue of images being cropped/distorted.

PS I just discovered that it only affects some images. I can not find any association to landscape/portrait mode or resolution, please see another picture below. I also edited CSS for this slightly.

![FlippedImagesRandom](https://user-images.githubusercontent.com/14071466/112834184-976a9600-908f-11eb-8b5f-058cf5519a97.jpg)

`
      width: '60%',
      height: 'auto',
      margin: '0 20%',
      marginBottom: '5px',
`

I have another update. I tried rendering images in the PDF and just below it. Images rendered as regular HTML img tags are rendered properly, while some images from the same set get rotated in the PDF document.

![FlippedImagesInOut](https://user-images.githubusercontent.com/14071466/112956796-ba04b980-9138-11eb-8738-009a49478b6a.jpg)

I tried to find the reason for this in PDF.js and react-pdf, the search was unsuccessful.
I am using react-pdf/renderer: ^2.0.0-beta.6 .

**Comment by marekhvolka** [comment]
Hello, does anybody have any update on this? We have a similar problem but with the pdf documents. Some pdf documents have their pages rotated. If we download that document and open it in some PDF viewer, everything looks correct.

**Comment by marekhvolka** [comment]
I managed to solve the issue. For some documents, the pdfjs library is doing some initial rotation (don't know really why). But you can access that rotation value in `onLoadSuccess` handler, which returns a Page object with a field `rotate` and adjust the `rotate` value you pass as a prop to the `Page` component

**Comment by melissa-gaivota** [comment]
Same problem here, with images. Any updates?

**Comment by wojtekmaj** [comment]
Wrong repository.

https://github.com/wojtekmaj/react-pdf#lost

**Comment by Lulu92270** [comment]
Hi, same issue here
![image](https://user-images.githubusercontent.com/70411900/143250209-de4f2e10-98f5-40c1-b294-a7f256bfa80f.png)
And sometimes I get a rotated image like this:
![image](https://user-images.githubusercontent.com/70411900/143250321-3357790f-2fbe-4493-869b-209186734778.png)

**Comment by CristianCiubancan** [comment]
Why is this closed? Is there any resolution for this?

**Comment by wojtekmaj** [comment]
Wrong repository. This issue is regarding diegomura's react-pdf renderer.
