### ISSUE TITLE
Memory leak when rendering PDFs without embedded fonts

### ISSUE THREAD

**Issue by peterzanetti** [wojtekmaj/react-pdf#759]
I have found that every time render is called on a PDF that is missing embedded fonts, memory usage increases exponentially and never goes back down. This is easy to reproduce with a sample app.

This seems like a major issue.

**Comment by peterzanetti** [comment]
Glad you reopened because this is definitely a major bug. We actually had to implement an entire ghostscript-based PDF conversion server utility to get around this bug.

**Comment by wojtekmaj** [comment]
Do you experience similar results with Mozilla's default PDF reader, or in React-PDF only? Trying to track this down...

**Comment by peterzanetti** [comment]
Well I'm not sure if I could reproduce it with "Mozilla's default PDF reader" because the issue occurs with re-render in React. React does a lot of render as you know. As user's interact with our features, there is lots of re-render, and the memory usage climbs with each render.
