### ISSUE TITLE
Download filled interactive PDF  

### ISSUE THREAD

**Issue by olivierkastel** [wojtekmaj/react-pdf#763]
I am displaying a PDF form with interactive fields where users can fill everything up. Is there a way to download the new edited version of this PDF?

**Comment by AhmedRyad22** [comment]
looking for same thing , did you find any solution ?

**Comment by jelizarovas** [comment]
see `pdf-lib`. I use `react-pdf` to display the pdf, but pdf-lib to make any changes.  This way you can show changes in real time. It is very taxing though, so use debounce to update data
```
 <Document
                file={!!pdf?.data ? { data: pdf.data } :  pdf?.url}
```
