### ISSUE TITLE
pdf object functions throwing "this is undefined" errors

### ISSUE THREAD

**Issue by DaniloHP** [wojtekmaj/react-pdf#771]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**
I wasn't sure whether to submit this as a bug report or a support question because I could totally see this being something that I got wrong, as I would assume a bug this big wouldn't go this long without this being noticed by anyone else. 

All of the functions (i.e. `getData`, `getPage`, etc) on the object given as an argument in a Document or Page component's `onLoadSuccess` will cause `Uncaught TypeError: this is undefined`  when called. 

**Steps to reproduce**

Call any of the functions attached to the object given as a parameter a Document or Page's `onLoadSuccess`.
For example, this causes the error for me:
```js
<Document
  file={{ data: data }} //currently a Uint8Array
  externalLinkTarget={"_blank"}
  loading={""}
  onLoadSuccess={async ({ numPages, getPage }) => {
    const page = await getPage(0); //error here
    setNumPages(numPages);
    setLoaded(true);
  }}
>
```
I've tried using a URL and Uint8Array for the file. There's nothing wrong with the PDF either as far as I can tell. Everything works great as long as I don't call any of those functions. I'm using CRA so I opted for 
```js
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js\`
```

**Expected behavior**

I would expect that the error does not occur.

**Environment**

 - Firefox 86.0.1
 - React-PDF 5.2.0
 - React 17.0.1
 - Webpack 4.44.2

**Comment by wojtekmaj** [comment]
I got a crash with

```js
  const onDocumentLoadSuccess = useCallback(async (document) => {
    const { getPage } = document;
    const page = await getPage(1);
  }, []);
```

but not with 

```js
  const onDocumentLoadSuccess = useCallback(async (document) => {
    const page = await document.getPage(1);
  }, []);
```

I hope this helps!
