### ISSUE TITLE
Dynamic Import react-pdf with Next.js

### ISSUE THREAD

**Issue by dolie** [wojtekmaj/react-pdf#773]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

Hello,
I'm trying to import dynamicaly `react-pdf` with `next.js`. Because, react-pdf (pdf.js) do crash IE 11. React-pdf is used only on a few pages where modern browsers are mandatory. That's why I opt for dynamic import.

I had the following error : 
`TypeError: can't access property "workerSrc", pdfjs.GlobalWorkerOptions is undefined`

The problem seems to be pdfjs. This do not work : 
```javascript
import {convertArraybufferToB64, convertB64ToBlob} from 'utils/files'

import dynamic from 'next/dynamic'

// 👇🏻 classic import do work 👍🏻
//import {pdfjs} from 'react-pdf'
// but I need dynamic import 😥

const Document = dynamic(() => import('react-pdf').then((mod) => mod.Document))
const Page = dynamic(() => import('react-pdf').then((mod) => mod.Page))
const pdfjs = dynamic(() => import('react-pdf').then((mod) => mod.pdfjs))

function ViewerPdf ({source, size, setOriginalSize, filename, draggable}) {
  
  useEffect(() => {
    if (typeof window !== undefined){
      pdfjs.GlobalWorkerOptions.workerSrc = `/utils/pdf.worker.min.js`
    }
  }, [])
  ```

Please help me, what am I doing wrong ?

**Environment**

 - Browser [Firefox 89.0b2]
 - NextJS [10.0.5]
 - React-PDF version [5.2.0]
 - React version [17.0.1]

**Comment by wojtekmaj** [comment]
Is `/utils/pdf.worker.min.js` being downloaded correctly?

**Comment by dolie** [comment]
Hello @wojtekmaj ,

Yes, it is downloaded correctly.

I finally found the solution : 
If I Dynamic import the entire component which do classic `import {Document, Page, pdfjs} from 'react-pdf'`, it works just fine 👍🏻 

```javascript
// `pages/Page`
import dynamic from 'next/dynamic'

const PDFViewer = dynamic(() => import('components/PDFViewer'), {ssr: false})

function Page() {
  // some logic code here
  
  // render
  return <PDFViewer>
}
```

```javascript
// `components/PDFViewer`

import {Document, Page, pdfjs} from 'react-pdf'

function PDFViewer() {
  // some logic code here
  
  // render
  return (
    <Document>
    // ...
    )
}
```

Thank you for your fast answer.
