### ISSUE TITLE
How to add annotations to the pdf loaded? 

### ISSUE THREAD

**Issue by eborst** [wojtekmaj/react-pdf#775]
Hi, I have a question: I would like to add new annotations (drawings) to a pdf, but for this I need to have a reference to the canvas. Is that possible with react-pdf? and if so, how should I do this? 
Saving the pdf is not necessary, I will feed them in from external.

Any help is appreciated!

**Comment by wojtekmaj** [comment]
Nope, sorry. React-PDF only supports displaying PDFs.

**Comment by aleksbobic** [comment]
Hey @wojtekmaj do you have any suggestions how this could be implemented or how one might extend react-pdf to get this feature? :)
