### ISSUE TITLE
How to solve: PDF installed instead of opening?

### ISSUE THREAD

**Issue by Dev01-vinamr-Ken** [wojtekmaj/react-pdf#776]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'd like to display multiple pages of my PDF. I've followed the code sample. However, when I run the site on localhost, the PDF is installed rather than opened. 

**Describe solutions you've tried**

- I've add the `//cdn` in my file
- Try all kinds of file path (in public, relative file, import with `file-loader`)

**Additional information**

- **Browser**: Microsoft Edge
- **Image**: 
![image](https://user-images.githubusercontent.com/73330048/116834288-8c070f00-abe7-11eb-8f34-305dfac16079.png)
- **Code snippet:**

```
import React from "react";
import { Page } from "react-pdf";
import { pdfjs } from "react-pdf";
import { Document } from "react-pdf/dist/esm/entry.webpack";

import Lesson_1 from "./Lesson 1.pdf";
// Another relative path '../../../public/docs/pdf/Lesson 1.pdf'

// pdfjs.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

const options = {
  cMapUrl: "cmaps/",
  cMapPacked: true,
};

function Lesson(props) {
  const [numPages, setNumPages] = React.useState(null);
  const [pageNumber, setPageNumber] = React.useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  return (
    <div>
      <Document
        file="Lesson 1.pdf"
        options={options}
        onLoadSuccess={onDocumentLoadSuccess}
      >
        <Page pageNumber={pageNumber} />
      </Document>
      <p>
        Page {pageNumber} of {numPages}
      </p>
    </div>
  );
}

export default Lesson;
```
- File structure: 
![image](https://user-images.githubusercontent.com/73330048/116834316-b2c54580-abe7-11eb-8e3a-08da886441a8.png)

**Environment**

 - Browser: **Microsoft Edge**
 - React-PDF version: **5.2.0**
 - React version: 17.0.2
 - Webpack version: 4.44.2

**Comment by Dev01-vinamr-Ken** [comment]
Hi @wojtekmaj , would you mind helping me? Thanks a lot!

**Comment by ArniyhJS** [comment]
Disable your IDM extension from your browse. IDM is built to listen to certain download files and download patterns. 
as long as you have it on, it will always hijack the download process.

**Comment by wojtekmaj** [comment]
This. And another issue with your code is that you're importing PDF straight to your bundle:

```js
import Lesson_1 from "./Lesson 1.pdf";
```

and then not using it, relying on a string which is actually interpreted as an URL:

```js
      <Document
        file="Lesson 1.pdf"
```

This may cause unexpected behaviors depending on your configuration. Choose one way to pass the file to Document.
