### ISSUE TITLE
Objects are not valid as a React child

### ISSUE THREAD

**Issue by marcusleeeugene** [wojtekmaj/react-pdf#778]
I followed the documentation, using webpack, however I am unable to load the resume file. Anyone faced this issue? Here's my code:

```
import React, { useState } from 'react';
import { Page } from 'react-pdf';
import { Document } from 'react-pdf/dist/esm/entry.webpack';
import resumeFile from '../resources/MarcusLeeEugene_Resume.pdf';

function Resume() {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  const onDocumentLoadSuccess = (numPages) => {
    setNumPages(numPages);
  }

  return (
    <React.Fragment>
      <Document
        file={resumeFile}
        onLoadError={(error) => alert(error.message)}
        onLoadSuccess={onDocumentLoadSuccess}
      >
        <Page pageNumber={1}/>
      </Document>
      <p>Page {pageNumber} of {numPages}</p>
    </React.Fragment>
  );
}

export default Resume;
```

![image](https://user-images.githubusercontent.com/19762656/117645500-41742c80-b1bd-11eb-85ac-024be96c9d61.png)

Running on:
"react": "^17.0.2",
"react-pdf": "^5.3.0",

**Comment by wojtekmaj** [comment]
You're importing Document and Page from entirely different entry points. Either use `'react-pdf'` _or_ `'react-pdf/dist/esm/entry.webpack'`.

**Comment by marcusleeeugene** [comment]
> You're importing Document and Page from entirely different entry points. Either use `'react-pdf'` _or_ `'react-pdf/dist/esm/entry.webpack'`.

I tried both as well and got the same error

**Comment by wojtekmaj** [comment]
Oh I can see it now. `<Document />`'s `onLoadSuccess` receives an object (`pdf`) as argument, and you're just naming the whole argument `numPages` by mistake.

So:

```diff
-  const onDocumentLoadSuccess = (numPages) => {
+  const onDocumentLoadSuccess = ({ numPages }) => {
    setNumPages(numPages);
  }
```

**Comment by marcusleeeugene** [comment]
> Oh I can see it now. `<Document />`'s `onLoadSuccess` receives an object (`pdf`) as argument, and you're just naming the whole argument `numPages` by mistake.
> 
> So:
> 
> ```diff
> -  const onDocumentLoadSuccess = (numPages) => {
> +  const onDocumentLoadSuccess = ({ numPages }) => {
>     setNumPages(numPages);
>   }
> ```

Ahh, it works fine now! Thank you so much!
