### ISSUE TITLE
Property pdf does not exist on <Page>. Incorrect typings

### ISSUE THREAD

**Issue by seanaye** [wojtekmaj/react-pdf#779]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] ~~If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox~~
 ^ Not Applicable

**Description**

Short description of the bug you encountered.

According to [docs](https://github.com/wojtekmaj/react-pdf#page) its possible to pass a `pdf` prop to a `<Page>` component to render a page from an arbitrary `pdfjs.PDFDocumentProxy` although typescript complains about this prop not existing.

I need this because I am trying to render pages from different pdfs together and multiple times so I don't want duplicate `Document` elements parsing the same pdf

**Steps to reproduce**

See below

**Expected behavior**

Typescript shouldn't complain about typings

**Additional information**

```tsx
        <Page
          pageIndex={pageIndex}
          rotate={doc.representation[index].rotation}
          pdf={ref as pdfjs.PDFDocumentProxy}
        />
```

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: N/A
 - React-PDF version [e.g. 3.0.4]: 5.2.0
 - React version [e.g. 16.3.0]: 17.0.2
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.39.1
 - Typescript: 4.2.4

**Comment by jljorgenson18** [comment]
pdfjs-dist changed their types so this is sort of expected. You can import the same types like this

`import { PDFDocumentProxy } from 'pdfjs-dist/types/display/api';`

However, apparently types in @types/react-pdf also have some bad references that look like they need to be patched 

```
node_modules/@types/react-pdf/dist/Document.d.ts:2:10 - error TS2305: Module '"pdfjs-dist"' has no exported member 'PDFDocumentProxy'.

2 import { PDFDocumentProxy } from 'pdfjs-dist';
           ~~~~~~~~~~~~~~~~

node_modules/@types/react-pdf/dist/Outline.d.ts:2:10 - error TS2305: Module '"pdfjs-dist"' has no exported member 'PDFTreeNode'.

2 import { PDFTreeNode } from 'pdfjs-dist';
           ~~~~~~~~~~~

node_modules/@types/react-pdf/dist/Page.d.ts:2:10 - error TS2305: Module '"pdfjs-dist"' has no exported member 'PDFPageProxy'.

2 import { PDFPageProxy as _PDFPageProxy } from 'pdfjs-dist';
           ~~~~~~~~~~~~

[5:31:33 PM] Found 3 errors. Watching for file changes.
```

**Comment by jljorgenson18** [comment]
Looks like @oBusk was digging into similar issues when dealing with the unofficial pdfjs-dist types https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52508

**Comment by seanaye** [comment]
I think this is a related but separate issue. Typescript is saying that the `pdf` prop doesn't exist at all on the `<Page>` component, not that the prop is the incorrect type.

**Comment by jljorgenson18** [comment]
O gosh you are right, I misread. These are a bit similar. I can create a different issue for the other type issues if no one is working on them or do a PR.

**Comment by hilmanski** [comment]
Anyone have solved this issue? any refrence?

**Comment by wojtekmaj** [comment]
Please raise an issue in DefinitelyTyped repo if needed.
