### ISSUE TITLE
SVG - source images hosted instead of base64 string

### ISSUE THREAD

**Issue by sudarshan-kamath** [wojtekmaj/react-pdf#780]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I am trying to display a PDF as an SVG and trying to store the SVG as a string (by using XMLSerializer) for storing it on the server. I have noticed that the background images in the SVG are converted to blobs which are hosted on the localhost. When I copy the SVG string, since the image hosted is not available elsewhere (when I render on another computer), it fails to display the file correctly with the images missing.

Is there any way that the background images be converted into base64 string such that it is part of the SVG rather than being hosted.

**Describe solutions you've tried**

Modified the sample repository and observed the source. This is no problem in the canvas mode as the document is converted to an image, but observed only when the SVG is the option being selected for rendering the page.

**Comment by wojtekmaj** [comment]
I don't think pdf.js was designed for server-side PDF rendering 🤔

**Comment by sudarshan-kamath** [comment]
Thanks for the quick reply. I was using this as a converter to convert the PDF to SVG. (By hosted, I meant the localhost. Sorry if I was not clear!). The SVG created has the images with the source pointing to a blob and I was hoping that having the image as a base64 would help to convert it into an independent SVG. 

Wonderful work by the way!

**Comment by wojtekmaj** [comment]
This discussion may come in handy: https://github.com/mozilla/pdf.js/pull/8350
