### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by shaynethiessen** [wojtekmaj/react-pdf#781]
The typescript definitions for react-pdf need to be updated.

**Comment by wojtekmaj** [comment]
I'm not maintaining them and they are not in this repo. Raise (more helpful) issue in DefinitelyTyped repo instead.

**Comment by shaynethiessen** [comment]
> I'm not maintaining them and they are not in this repo. Raise (more helpful) issue in DefinitelyTyped repo instead.

Thank you!
