### ISSUE TITLE
Error after v5.3.0 upgrade "Cannot read property 'WorkerMessageHandler' of undefined"

### ISSUE THREAD

**Issue by peterpeterparker** [wojtekmaj/react-pdf#783]
**Description**

In a React app, after upgrading to the last version `v5.3.0` I am facing the following error at runtime:

> Uncaught SyntaxError: Unexpected token '<'
> index.js:1 Error: Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined".
>     at api.js:1992

This error does not happen with `v5.2.0`.

**Steps to reproduce**

The following can be use to reproduce the issue. It is a sample react starter app (template typescript) with react-pdf.

```
git clone https://github.com/peterpeterparker/my-app-pdf
cd my-app-pdf
npm ci
npm run start
```

**Expected behavior**

No error while loading a PDF file.

**Additional information**

According [CHANGELOG](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.3.0) there are breaking changes, therefore I still followed the example provided in the [README.md](https://github.com/wojtekmaj/react-pdf#enable-pdfjs-worker) to import the worker in my sample demo app.

**Environment**

React

**Comment by lpke** [comment]
Can confirm - version `5.3.0` was giving me issues as well. I don't have much time to write up a full issue right now so I thought I would just at least mention the issue - `pdfjs.PDFDocumentProxy` loses it's type definition (even after updating `@types/pdf-js`).

**Comment by wojtekmaj** [comment]
@peterpeterparker The reason your app is not working is because you imported react-pdf from two different locations:

```js
import { Document } from 'react-pdf/dist/esm/entry.webpack';
import { Page } from 'react-pdf';
```

Hence, the default `'react-pdf'` entry file overwritten what Webpack entry file did, resulting in an error you've seen.

Change this to:

```js
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';
```

and everything works.

![Zrzut ekranu 2021-05-20 o 09 55 36](https://user-images.githubusercontent.com/5426427/118941067-a49a5780-b951-11eb-9f0b-1aa7e03ff28a.png)

**Comment by peterpeterparker** [comment]
You are absolutely right it does solve the issue!

Thanks a lot @wojtekmaj for having a look and, for improving the documentation.

**Comment by peterpeterparker** [comment]
Indeed the above did solve the issue with the development build but, did not for production.
When I deployed and, tested a prod build I faced the error #782.
