### ISSUE TITLE
Get line index on custom text render

### ISSUE THREAD

**Issue by matheusfillipe** [wojtekmaj/react-pdf#785]
I am creating a custom text render like:
```javascript
  function makeTextRenderer(textItem) {
    if (textItem === undefined) return;

    //console.debug(`page ${textItem.page._pageIndex} item: ${textItem.itemIndex}: ${textItem.str}`);
    const page_index = textItem.page._pageIndex;
    const line_index = textItem.itemIndex;
    const splitText  = textItem.str.split(DEFAULT_WORD_SEPARATOR).filter(e => e);
    console.log(textItem)
    console.log(`page: ${page_index}   line_index: ${line_index}`)
    console.log(splitText)
    // I need the right line index to do something here ad change the return
    return textItem.str;

  const textRenderer = useCallback(makeTextRenderer, [transcriptIndex]);
(...)
          <Page
            pageNumber={pageNumber}
            scale={size.x > MAX_SIDE_BY_SIDE_WIDTH ? PAGE_WIDTH : 1}
            width={size.x}
            key={`page_${pageNumber}`}
            //onRenderSuccess={() => setPagesRendered(pagesRendered + 1)}
            customTextRenderer={textRenderer}
          />,

```

But my line_index is not right. By line index I mean what line of the pdf I am (considering text on the same y coordinate a line). 
![100033300378_259827](https://user-images.githubusercontent.com/24435787/119457789-71b9e000-bd12-11eb-8962-c191b35c796e.jpg)

Even though "the" is on the same line it is displaying it on another one. I think is because textItems don't really care about lines? How can I get effective line indexes then?

This is the file: [AnansiandthePotofBeans.pdf](https://github.com/wojtekmaj/react-pdf/files/6537372/AnansiandthePotofBeans.pdf)

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [5.3]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by wojtekmaj** [comment]
In `textItem.transform`, last two elements of the array are X and Y coordinates.

Keep the list of Y coordinates you've already processed, for example:

```js
lines = [400, 410, 420]
```

In this array, array indices would be your line indices, and values would be Y coordinates.

As you move down the PDF, check if you've seen Y coordinate before. If not, push this Y coordinate to the array. Use its index as line index.
