### ISSUE TITLE
File loader dependency, is it really necessary?

### ISSUE THREAD

**Issue by FrancoSirena** [wojtekmaj/react-pdf#787]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I was hoping to be able to use the package without having to leak several other pieces to the production build, such as `worker-loader, file-loader, caniuse-lite` and so on.

I am using the package without the entry.webpack.js but as the `file-loader` is a direct dependency I can't get around having to allow CC licenses in my prod build.

Unfortunately, the licenses the company I work for allows us to ship to production do not have CC listed as one, so I was hoping to use react-pdf because it is an amazing package but with the file-loader direct dependency, I can't.

**Describe solutions you've tried**

I tried to downgrade to version 3 or 4 but then instead of `file-loader`, I got the worker-loader, which suffers from the same issues as the file-loader.

I cloned the repo locally and removed the file-loader as a direct dependency and added it as a peer-dependency because after all, that should be on the consumer side to install and not something that should be shipped with the package itself.

**Additional information**

I have a branch with the changes but I was hoping to get input before actually submitting a PR for this, because there can be real reasons to have it as a direct dependency and I may be missing those.

To get around the file loader I am simply using the type:"asset" that is the new webpack 5 way.

Just to illustrate my point.

Without file-loader:
```
➜ DEBUG=license-checker:log npx -q license-checker --summary --production
  license-checker:log scanning /Users/FrancoSirena/Repos/Personal/react-pdf +0ms
├─ MIT: 15
└─ Apache-2.0: 1
```

With file-loader:
```
➜ DEBUG=license-checker:log npx -q license-checker --summary --production
  license-checker:log scanning /Users/FrancoSirena/Repos/Personal/react-pdf +0ms
├─ MIT: 78
├─ BSD-2-Clause: 7
├─ BSD-3-Clause: 4
├─ Apache-2.0: 3
├─ ISC: 2
├─ CC-BY-4.0: 1
└─ 0BSD: 1
```

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: N/a
 - React-PDF version [e.g. 3.0.4]: 5.3.0
 - React version [e.g. 16.3.0]: > 16
 - Webpack version (if applicable) [e.g. 4.16.2]: 5

**Comment by wojtekmaj** [comment]
> To get around the file loader I am simply using the type:"asset" that is the new webpack 5 way.

Well that would require us to drop Webpack 4 support which is a breaking change.

I don't know how would we approach it best. Could it be in `optionalDependencies`, maybe? 🤔

**Comment by FrancoSirena** [comment]
Sorry, the way I got around it was on my side because I am using webpack 5, but yes for users that are using the webpack 4 and are going to use the entry.webpack.js they could just install the file-loader on their apps and that would do it.

I think the optionalDependencies will actually get installed either way but they don't break the install command if they fail to get installed, so I think peerDependency would be more appropriate in this case.

I tested locally with the optionalDependencies approach and still I get all the licenses as if it was a regular dependency.

**Comment by FrancoSirena** [comment]
I just took some time to set up a fully functional example:

Forked version without file-loader:
https://github.com/FrancoSirena/react-pdf

Npm package: 
https://github.com/FrancoSirena/react-pdf

A webpack 4 app with file loader, I just created it with create-react-app:
https://github.com/FrancoSirena/react-pdf-file-loader

That would not be a breaking change I would say, but arguable. I mean, just food for thought.

**Comment by wojtekmaj** [comment]
Closing this for now. We'll get back to this matter when we decide to drop support for Webpack 4 completely.

**Comment by tpict** [comment]
@wojtekmaj Wanted to give this a bump. Node 18 becomes the LTS in a few short months, and `file-loader` doesn't work under Node >= 17 due to the OpenSSL version bump.

**Comment by wojtekmaj** [comment]
file-loader isn't used when you use Webpack 5 entry file I believe. Its mere existence shouldn't cause any problems.

**Comment by tpict** [comment]
Yep, I skimmed over the `5` suffix in the entry path. No longer an issue. Thanks for the quick response!
