### ISSUE TITLE
The function onLoadProgress does not return callback in the Page Component.

### ISSUE THREAD

**Issue by dudubernardino** [wojtekmaj/react-pdf#789]
**Before you start - checklist**

 - [ x ] I followed instructions in documentation written for my React-PDF version
 - [ x ] I have checked if this bug is not already reported
 - [ x ] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [ x ] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Short description of the bug you encountered.

**Steps to reproduce**

1. When pdf load the function does not execute.

**Environment**

 - React-PDF version [e.g. 5.3.0]:
 - React version [e.g. 17.0.1]:
 - Next version  [e.g. 10.0.29]:

**Comment by wojtekmaj** [comment]
Page component does not have onLoadProgress prop.

**Comment by fl-knix** [comment]
Project README lists onLoadProgress as a prop of `Page`. Looks like it has been moved to `Document`?

**Comment by wojtekmaj** [comment]
Ah! It has always in Document. That's a bug in documentation. Thanks!

**Comment by Luccasoli** [comment]
I'm trying to fix this in the type file here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53488
