### ISSUE TITLE
Failed prop type: Expected 'pageNumber' to be less or equal to 1

### ISSUE THREAD

**Issue by Theophylline** [wojtekmaj/react-pdf#790]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I have a table component which allows the user to click on a row to display a pdf with relevant information. These pdf files are fairly small; only 1 - 3 pages. I noticed that when I switch from rendering a large pdf (e.g 3-page pdf) to a small pdf (e.g single page pdf), I get the following error in my console: `Failed prop type: Expected 'pageNumber' to be less or equal to 1.`. See screenshot for more details. 

**Describe solutions you've tried**
My current implementation is pretty much the same as the [sample code in the docs](https://github.com/wojtekmaj/react-pdf/tree/master/sample). The only change I made was passing different URLs to the `file` prop of the `<Document>` component based on click events.

```
const [numPages, setNumPages] = useState(null);

// ... code removed for clarity ...

<Document
  file={staticURL} //static URL changes depending on row click
  onLoadSuccess={({ numPages })=>setNumPages(numPages)}
>
  {
    Array.from(
      new Array(numPages),
      (el, index) => (
        <div className="pdf-page" key={`page_${index + 1}`}>
          <Page
            pageNumber={index + 1}
          />
          <Divider />
        </div>
      ),
    )
  }
</Document>
```

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.
![image](https://user-images.githubusercontent.com/19714287/120020435-b0bc8f80-bfb7-11eb-9a3a-8ae9f0b2905d.png)

**Environment**

 - Browser (if applicable): Chrome 89.0.4389.128
 - React-PDF version: 5.3.0
 - React version: 17.0.1
 - Webpack version (if applicable): 4.44.2

**Comment by wojtekmaj** [comment]
When "closing" the old document, reset all info you got from `onLoadSuccess` callback of said document. In this case, `numPages`. There shouldn't be a situation in which you load a new document but old numPages is still around, trying to render pages that don't exist.

**Comment by R4z1ell** [comment]
> When "closing" the old document, reset all info you got from `onLoadSuccess` callback of said document. In this case, `numPages`. There shouldn't be a situation in which you load a new document but old numPages is still around, trying to render pages that don't exist.

I'm facing the same problem, can you elaborate on this part "when closing the old document, reset the info"? thanks

**Comment by Theophylline** [comment]
@R4z1ell The way I resolved the error is setting the `numPages` state to null inside a useEffect. This way every time you rerender your pdf component the `numPages` gets reset.
