### ISSUE TITLE
Only the first page is shown (numberOfPages receiving by onDocumentLoadSuccess is undefined).

### ISSUE THREAD

**Issue by redday059** [wojtekmaj/react-pdf#792]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**
I'm trying to render PDF with multiple pages, but only 1 page is shown. I think it's because numberOfPages in onDocumentLoadSuccess is underfined.

```
...
  function onDocumentLoadSuccess({ numberOfPages }) {
    console.log('numberOfPages?: ', numberOfPages);
    setNumPages(numberOfPages);
  }
...

viewer = (
          <div>
            <PdfDocument
              file={`data:application/pdf;base64,${samplePDF}`}
              onLoadSuccess={onDocumentLoadSuccess}
            >
              {/* <Page pageNumber={pageNumber} /> */}
              {Array.from(
                new Array(numPages),
                (el, index) => (
                  <Page
                    key={`page_${index + 1}`}
                    pageNumber={index + 1}
                  />
                ),
              )}
            </PdfDocument>
            <p>Page {pageNumber} of {numPages}</p>
          </div>
        );
```

**Describe solutions you've tried**

Instead of passing the link to pdf from the server encoded to base64, I tried to pass:

```file={`data:application/pdf;base64,${samplePDF}`}```

where `samplePDF` is a hardcoded string (via https://base64.guru/converter/encode/pdf, so latin only)
The result is the same. Only 1 page and console.log gives: `numberOfPages:  undefined`
The same situation: only one page is shown.

What am I doing wrong? Please, help!

**Environment**

 - Browser: all
 - React-PDF version: 5.3.0
 - React version: 16.9.17
 - webpack wrapper: "@symfony/webpack-encore": "^1.3.0":

**Comment by redday059** [comment]
[Update]
I found out that this is the issue in React-PDF version: *5.3.0*,  but *it does work in 4.1.0*.
This does work in 4.1.0 in case PDF.js worker enabled.
Currently stuck on it as using
- pdfjs.GlobalWorkerOptions.workerSrc = '//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.8.335/pdf.worker.min.js'; 
- or copying to build folder
both give 
```
pdf.js:11096 Refused to create a worker from 'blob:https://localhost:8000/...' because it violates the following Content Security Policy directive: "script-src 'self' localhost:8421 'unsafe-inline' 'nonce-3b87305725b296dbf8dd45e10bf63930'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
```
But this is another issue.

**Comment by wojtekmaj** [comment]
It's not `numberOfPages`, but `numPages`. See README.

**Comment by redday059** [comment]
@wojtekmaj thank you so much!
(I'm still failing to set up worker, but I'll spend more time to be sure, I tried everything, and in case of unsuccess will open an issue-question)
