### ISSUE TITLE
Base64 encoded string is displaying image instead of pdf file format

### ISSUE THREAD

**Issue by ahsanshah7865** [wojtekmaj/react-pdf#797]
I am getting base64 encoded string from server. but instead of getting pdf I'm getting an image. 
My base64_encoded string starts with "JVBERi0xLjQKMSAwIG9iago8PAovVGl0bGUgKP7"
and when I test it on browser address bar, I'm getting Failed to load pdf document.
on the other hand, if i check that base64 encoded string in online base64 to pdf converting sites,
I'm getting the appropriate result as pdf.
This is my component code that i used,
`<Document
                        loading={<Loader />}
                        file={data:application/pdf;base64,${fileBase64}}
                        onLoadSuccess={onDocumentLoadSuccess}
                    >
                        <Page pageNumber={1}></Page>
                    </Document>`

**Comment by wojtekmaj** [comment]
`JVBERi0xLjQKMSAwIG9iago8PAovVGl0bGUgKP7` translates to 

```
%PDF-1.4
1 0 obj
<<
/Title %
```

so it seems like a valid PDF.

What image are you getting? 🤔
