### ISSUE TITLE
How to retry/reload the document on Error

### ISSUE THREAD

**Issue by nivekithan** [wojtekmaj/react-pdf#798]
**Before you start - checklist**

 - [X] I have read documentation in README
 - [X] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [X] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

When there is `onLoadError` I will display a `ErrorMessage` component which has  retry button. Now I need to retry loading the `Document` whenever user clicks retry.

**Describe solutions you've tried**

As of now I achieve this by having a `docKey` in state and whenever  there is `onLoadError` I will just increase the `docKey` value by 1. Then I will pass this `docKey` as `key` prop in `Document`. The code will  look something like this

```js

const App = () => {
   const [docKey, setDocKey] = useState(0);

    const onRetry = () => {
         setDocKey((s) => ++s);
     }

     return  <Document key={docKey} />    

```
The code is just representation not the actual code.

It works perfectly fine. I am just wondering weather this is preferred way of reloading, is there some other better way of doing this.

**Comment by wojtekmaj** [comment]
I would have done it the same way actually. Alternatively, you could set `file` to `null` and back to what it was before, but I think `key` is beautifully clean and less complicated solution.
