### ISSUE TITLE
Can't resolve 'canvas' in '(...)/node_modules/pdfjs-dist/build'

### ISSUE THREAD

**Issue by hfossli-agens** [wojtekmaj/react-pdf#799]
**Description**

When building my Next JS application I get this error:
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'canvas' in '(...)/node_modules/pdfjs-dist/build'
```

**Steps to reproduce**

1. Create a Next JS application
2. Install react-pdf 
3. Import react-pdf in some page
```js
import { Document, Page, pdfjs } from "react-pdf/dist/umd/entry.webpack"
```
4. Build (e.g. `yarn build`)

**Expected behavior**

Expected the application to build

**Additional information**

```
$ yarn build
yarn run v1.22.10
$ next build
(node:29765) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at (...)/node_modules/next/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
Loaded env from (...)/.env.local
info  - Using external babel configuration from (...)/.babelrc
info  - Creating an optimized production build  
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve 'canvas' in '(...)/node_modules/pdfjs-dist/build'


> Build error occurred
Error: > Build failed because of webpack errors
    at (...)/node_modules/next/dist/build/index.js:15:918
    at async (...)/node_modules/next/dist/build/tracer.js:1:1441
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Environment**

 - React-PDF version: 5.3.0
 - React version: 17.0.1
 - Webpack version (if applicable): 4.44.2

**Comment by hfossli-agens** [comment]
**Solution**

Add this to `.next.config.js`:
```js
module.exports = {
    target: "serverless",
    future: { webpack5: true },
    webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
        config.resolve.alias.canvas = false
        return config
    }
}
```

**Comment by yordis** [comment]
@hfossli-agens that fixes the issue, but, do we really suppose to disable that thou? I am confused about where `canvas` comes from 🤔  Why is that even the fix? 😭

**Comment by hfossli** [comment]
It is only disabled for serverside rendering which makes total sense. While rendering client side the canvas is available :)

**Comment by yordis** [comment]
Are you sure? I dont see `isServer` being used to added it thou, regardless, YOLO I guess LOL

**Comment by hfossli** [comment]
That could probably be an improvement. Does it work to replace false with isServer?

**Comment by yordis** [comment]
🤷🏻 I literally 12 hours trying to figure out how to deploy the app in Netlify, so I haven't get to see this working in prod LOL

So maybe?

**Comment by szczepanbarszczowski** [comment]
I managed to fix this issue with locking version of react pdf in package.json to
```    "react-pdf": "5.2.0",
```
previously it was 
```    "react-pdf": "^5.2.0",
``` with this character ^ and it was causing resolution of pdfjs-dist to version 2.5. After change it results in 2.5 version which is not causing this problem.

**Comment by pavithra-muniraju** [comment]
i'm having same issue with angular project, while working in dev mode its working but with production mode its giving error 
./node_modules/pdfjs-dist/build/pdf.js:7847:27-44 - Error: Module not found: Error: Can't resolve 'canvas' in 'C:\Users\177391\Downloads\Git_repos\pavi\node_modules\pdfjs-dist\build', this is when i try to add ng2-pdf-viewer
Kindly helo here

**Comment by pensionbox-piyush** [comment]
> i'm having same issue with angular project, while working in dev mode its working but with production mode its giving error ./node_modules/pdfjs-dist/build/pdf.js:7847:27-44 - Error: Module not found: Error: Can't resolve 'canvas' in 'C:\Users\177391\Downloads\Git_repos\pavi\node_modules\pdfjs-dist\build', this is when i try to add ng2-pdf-viewer Kindly helo here

i don' think that's how they will resolve this
 - please raise a new issue that might help

**Comment by pavithra-muniraju** [comment]
add a fake-canvas.ts in your src folder with an empty function like this "export default{}", and then add in the tsconfig.json under compiler option like this  "paths": {
      "canvas": ["./src/fake-canvas.ts"]
    },

this worked for me and it might for you as well

**Comment by pavithra-muniraju** [comment]
> > i'm having same issue with angular project, while working in dev mode its working but with production mode its giving error ./node_modules/pdfjs-dist/build/pdf.js:7847:27-44 - Error: Module not found: Error: Can't resolve 'canvas' in 'C:\Users\177391\Downloads\Git_repos\pavi\node_modules\pdfjs-dist\build', this is when i try to add ng2-pdf-viewer Kindly helo here
> 
> i don' think that's how they will resolve this
> 
> * please raise a new issue that might help

add a fake-canvas.ts in your src folder with an empty function like this "export default{}", and then add in the tsconfig.json under compiler option like this "paths": {
"canvas": ["./src/fake-canvas.ts"]
},

this worked for me and it might for you as well

**Comment by pensionbox-piyush** [comment]
> > > i'm having same issue with angular project, while working in dev mode its working but with production mode its giving error ./node_modules/pdfjs-dist/build/pdf.js:7847:27-44 - Error: Module not found: Error: Can't resolve 'canvas' in 'C:\Users\177391\Downloads\Git_repos\pavi\node_modules\pdfjs-dist\build', this is when i try to add ng2-pdf-viewer Kindly helo here
> > 
> > 
> > i don' think that's how they will resolve this
> > 
> > * please raise a new issue that might help
> 
> add a fake-canvas.ts in your src folder with an empty function like this "export default{}", and then add in the tsconfig.json under compiler option like this "paths": { "canvas": ["./src/fake-canvas.ts"] },
> 
> this worked for me and it might for you as well

cool mate!! thanks!!1
