### ISSUE TITLE
5.3.0 console error - invalid prop 'file' supplied to 'Document'

### ISSUE THREAD

**Issue by AlexTalis** [wojtekmaj/react-pdf#800]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

After upgrading from 5.2.0 to 5.3.0 I get console error about invalid prop 'file' supplied to 'Document'. The error happens only when Document is rendered for the first time. Despite the error message, PDF is rendered properly. If I downgrade back to 5.2.0 the error disappears. In the following screenshot I log the object that I'm about to pass to 'file' property on first render. It's an object with data property set to a string that contains PDF data.

![image](https://user-images.githubusercontent.com/1012600/122860976-88ccfd00-d2d3-11eb-9ae0-71853b561805.png)

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Chrome 91.0.4472.106
 - React-PDF version [e.g. 3.0.4]: 5.3.0
 - React version [e.g. 16.3.0]: 16.14.0
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by wojtekmaj** [comment]
Interesting, propTypes were not changed in 5.3.0.

**Comment by AlexTalis** [comment]
@wojtekmaj
I set up a minimal project that reproduces the problem here:

https://codesandbox.io/s/youthful-kirch-yo0ud?file=/src/App.tsx

Maybe you can spot if I'm doing something wrong on my end?

**Comment by wojtekmaj** [comment]
Caused by fix in https://github.com/wojtekmaj/react-pdf/commit/d8297ae81bcde52f21aa44626be71ed903c5ae68.

**Comment by wojtekmaj** [comment]
Fixed in v5.3.2.
