### ISSUE TITLE
Link is not clickable if text is wrap first in strong tag and after that added link on that bold text <a href='https://www.google.com'><strong>Google</strong></a> (And same for underline too)

### ISSUE THREAD

**Issue by Prakash-karena** [wojtekmaj/react-pdf#801]
**Description**

Link not clickable if first added any style on text and after that added link.

**Steps to reproduce**
  I have used html-to-pdfmake to convert html to pdf and used that value inside pdfmake and after that once pdf generated i have used that pdf here. into that pdf link is not clickable.

**Expected behavior**
  link should be clickable even if strong added first and after that link is added

**Additional information**

![Screenshot from 2021-06-22 19-09-18](https://user-images.githubusercontent.com/63772512/122934701-63042e80-d38d-11eb-8b3d-9bf0bdfd52d5.png)
Here on above supermart first added bold after that added link so that is not clickable and  on below supermart first added link and after that added bold so that is clickable.

**Environment** : any

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: any 
 - React-PDF version [ 4.2.0]:
 - React version [16.13.1]:

**Comment by wojtekmaj** [comment]
Wrong repo
https://github.com/wojtekmaj/react-pdf#lost

**Comment by Joshmamroud** [comment]
@wojtekmaj how is this the wrong repo? I'm having the same issue. Links in PDF's displayed using react-pdf v5.3.2 are not clickable. What am I missing here? Thanks!

**Comment by wojtekmaj** [comment]
Sorry, I had to have multiple tabs opened and confused threads 😅 Good news though: what you're experiencing should be fixed in latest beta.

**Comment by wojtekmaj** [comment]
Duplicate of #816 (actually the other way around but oh well)
