### ISSUE TITLE
TextLayerItem calculates element width incorrectly on component update

### ISSUE THREAD

**Issue by divpreet** [wojtekmaj/react-pdf#804]
**Description**

TextLayerItem calculates element width (actualWidth) incorrectly whenever componentDidUpdate is called. It uses element width after the transform: scaleX and sets the transform: scaleX to 1 because the targetWidth and actualWidth turn out to be the same. This causes the text layer to be incorrectly aligned to the canvas.

**Steps to reproduce**
Use Page with TextLayer enabled in a component that has state changes based on text selection.
On text selection, you will notice that the calculation happens again because of a re-render triggering the componentDidUpdate on TextLayerItem.

**Expected behaviour**

The calculation should exclude any transforms.

React-PDF version: 5.3.0

**Comment by wojtekmaj** [comment]
I'm not able to reproduce this issue. Can you provide me with a CodeSandbox that shows the issue? TIA.

**Comment by divpreet** [comment]
https://codesandbox.io/s/textlayeritem-re-render-v8vmw?file=/src/Child.js

Here is a very simplified implementation. The point to note here is there is an useEffect that is wrapping a piece of text with a wrapper span after text layer has loaded. It leaves the generated span untouched and just wraps the text node.
If you check the actual width calculation for a particular text node that happens the 2nd time (ie on a re-render), lets say the first span on the first page with text "Lorem Ipsum" (I generally use a conditional breakpoint with element.innerText.trim() === "Lorem Ipsum" on TextLayerItem line 141), it calculates the width including the transform.
