### ISSUE TITLE
My pdf is generated fine but i want some of my text in bold but fontWeight is not working anywhere. What should i do to make it happen ? Please help.

### ISSUE THREAD

**Issue by umeshken-42** [wojtekmaj/react-pdf#805]
**Before you start - checklist**

 - [ ] I have read documentation in README
 - [ ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [ ] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.

**Describe solutions you've tried**

Describe solutions you've already tried, if any. Make sure to include code samples if you're stuck on implementation.

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by wojtekmaj** [comment]
Wrong repo, empty template, closing.
