### ISSUE TITLE
Include `dest` array in `onItemClick` callback

### ISSUE THREAD

**Issue by malwilley** [wojtekmaj/react-pdf#812]
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

I have a requirement where destination links (in the document or outline) need to scroll to the specific destination, not just the page that contains the destination. Currently, the `onItemClick` callback is only provided `{ pageNumber }`, which isn't enough information to work with.

**Describe the solution you'd like**

I would like the original `dest` array associated with an outline item or link to be provided (along with pageNumber) in the `onItemClick` callback, both  in `<Outline  />` and `<Document />`.

It seems like this could be accomplished relatively simply, by modifying these two locations (the destination array is readily available in both):

https://github.com/wojtekmaj/react-pdf/blob/c6fad62dada6760fd48ad5ca3bbac2dd48b2790d/src/LinkService.js#L75

https://github.com/wojtekmaj/react-pdf/blob/c6fad62dada6760fd48ad5ca3bbac2dd48b2790d/src/OutlineItem.jsx#L60

However, it may require some good documentation to go along with it, since the data object is not very intuitive.

I'd be happy to submit a PR with these changes if they're agreeable.

**Comment by wojtekmaj** [comment]
Sounds like something we could easily implement with no breaking changes. Let's do it!

**Comment by MuthuChess** [comment]
@wojtekmaj @malwilley 
Hi guys,

1. I would like to know how to scroll into dest. Pls share some ideas/snippets.
2. The outline links only once per click. Second click on the same link does not work. Does it work for you @malwilley? . I would like to know if I missed something from my end or if you have a workaround.

Thank you!
