### ISSUE TITLE
Upgrading from 5.2.0 to 5.3.0 causes annotation links to no longer work

### ISSUE THREAD

**Issue by richthornton** [wojtekmaj/react-pdf#816]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

First, thank you so much for your hard work on this library! It's absolutely brilliant!

I noticed, when upgrading from v5.2.0 to v5.3.0, clicking on annotations no longer works for me. I get an error thrown of 'x is not a valid destination reference'.

**Steps to reproduce**

1. [Visit this minimal reproduction](https://codesandbox.io/s/dreamy-archimedes-39cft?file=/src/App.tsx)
2. Ensure that react-pdf 5.3.0 is being used
3. Click on any of the links, for example 'Forward'
4. See an error of '"c" is not a valid destination reference.'

**Expected behavior**

Go to the [same codesandbox](https://codesandbox.io/s/dreamy-archimedes-39cft?file=/src/App.tsx), and install react-pdf 5.2.0 instead. See that no error is thrown, and an alert is show with the correct page number.

**Additional information**

It seems like the first version that the error occurs is in v5.3.0-beta, which contains a change to [Replace PDFLinkService with custom LinkService](https://github.com/wojtekmaj/react-pdf/pull/749). Maybe this reduced the compatible link formats?

**Environment**

 - Chrome 57
 - React-PDF version 5.3.0
 - React version 16.3.0

**Comment by wojtekmaj** [comment]
Please kindly test in [v5.4.0-beta.2](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.4.0-beta.2).

**Comment by richthornton** [comment]
Thanks for the super quick update @wojtekmaj!

Trying it out on the original sandbox it seems great. Unfortunately I'm using NextJS in my actual project, and the [update to PDF.js](https://github.com/wojtekmaj/react-pdf/pull/818) is breaking my build. It seems like with that release PDF.js have started using the optional chaining operator in the output, which my version of NextJS doesn't recognise. Other people using PDF.js have had [similar](https://github.com/mozilla/pdf.js/issues/13331) [problems](https://github.com/mozilla/pdf.js/issues/13453).

I'll try updating my version of NextJS and see if that solves the build issue 🤞

**Comment by wojtekmaj** [comment]
Uh, oh. If that won't do the trick, I think #794 is going to become our #1 priority.

**Comment by richthornton** [comment]
Ah I see, yeah it might end up being an issue for quite a few people if they're using NextJS.

I've tested it out your change for the annotations and all looks good to me! Thanks so much @wojtekmaj!

**Comment by sjdemartini** [comment]
I was also looking for this fix, and just like richthrnton mentioned, upgrading to v5.4.0-beta.2 broke my build with a create-react-app app (not NextJS) due to the update to PDF.js, with the same error (as in https://github.com/mozilla/pdf.js/issues/13331):

```
./node_modules/pdfjs-dist/build/pdf.js 2407:53
Module parse failed: Unexpected token (2407:53)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|                 intent: renderingIntent,
|                 renderInteractiveForms: renderInteractiveForms === true,
>                 annotationStorage: annotationStorage?.getAll() || null
|               });
|             }
```

**Comment by ebrahimhassan121** [comment]
@wojtekmaj 
could you add this commit in a new release ?

**Comment by wojtekmaj** [comment]
Of course it will be in a new release. It's already in beta.
