### ISSUE TITLE
Support new "Sig" type in pdfjs

### ISSUE THREAD

**Issue by Jefiozie** [wojtekmaj/react-pdf#817]
**Before you start - checklist**

 - [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [X] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

Describe what the problem is. Ex. I'd like to do […] with my PDFs.

At the moment the library doesn't support the new "Sig" widget.

**Describe the solution you'd like**

What you want to happen?

To support the new widget the pdfjs core lib from Mozilla should be update to the latest [release](https://github.com/mozilla/pdf.js/releases/tag/v2.9.359). This version is now supporting this new type [Pdfjs 13214](https://github.com/mozilla/pdf.js/pull/13214)

**Comment by wojtekmaj** [comment]
Related to #772
Related to #691 
Related to #559

**Comment by wojtekmaj** [comment]
Please kindly check [v5.4.0-beta.2](https://github.com/wojtekmaj/react-pdf/releases/tag/v5.4.0-beta.2) in which support for Sig type has been added.

**Comment by Jefiozie** [comment]
@wojtekmaj , I just verified that indeed it works with the latest beta versions
