### ISSUE TITLE
Page Unresponsive for OCRED pdf.

### ISSUE THREAD

**Issue by selvaganapathi5995** [wojtekmaj/react-pdf#820]
**Before you start - checklist**

 - [ yes ] I have read the documentation in README
 - [ yes ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [ yes ] I have checked if this question is not already asked

### ISSUE:
I am trying to render the OCRED pdf in internet explorer but the application froze. 

### SOLUTION: 

Assigned the **text-layer property to false** this fixed the issue in other browsers but not in IE.

**Environment**

 - Browser  :  Internet Explorer
 - React-PDF version [^3.0.5]:
 - React version [^16.8.6]:

**Comment by wojtekmaj** [comment]
Likely too heavy task for IE JavaScript engine to handle.

I'm also not able to support outdated React-PDF versions, and the newest one is not supporting IE at all. I won't be able to help you. Sorry!
