### ISSUE TITLE
How to implement zoom in zoom out functionality or how to use react-prismazoom for every page Page of Document?

### ISSUE THREAD

**Issue by jackvik** [wojtekmaj/react-pdf#822]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

Describe what are you trying to achieve Ex. I'd like to display multiple pages of my PDF.

**Describe solutions you've tried**

Describe solutions you've already tried, if any. Make sure to include code samples if you're stuck on implementation.

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by PCOffline** [comment]
This issue is not going to advance anywhere, you didn't provide any information.

**Comment by Sharcoux** [comment]
Just put the pdf inside a div, with overflow: auto

Then increase the width of the pdf to zoom in.
