### ISSUE TITLE
Document loses height on page change

### ISSUE THREAD

**Issue by WhiskyToad** [wojtekmaj/react-pdf#826]
Before you start - checklist

I followed instructions in documentation written for my React-PDF version
I have checked if this bug is not already reported
I have checked if an issue is not listed in Known issues

My problem is when the user changes page the document and container div lose their height and so the bottom of the page jumps to the top and then back down as the page loads creating an annoying flicker on the screen.

I've tried adding a minimum height but this causes bugs with the zoom function, and if you zoom bigger than the minimum height the flicker will return. I've added the 'A4' size prop and didn't do anything

the pdf comes in as a url link

my code

```
<div
          className={css.pdfDocument}
        >
          <Document
            file={signedUrl}
            onLoadSuccess={this.onDocumentLoad}
          >
            <Page
              className={css.pdfPage}
              pageNumber={pageNumber}
              renderTextLayer={false}
              scale={zoom}
            />
          </Document>
        </div>
```

**Comment by wojtekmaj** [comment]
You can define fixed page height, and manipulate it so that e.g. zoom = 1 -> height = 300, zoom = 1.5 -> height = 450.

**Comment by WhiskyToad** [comment]
> You can define fixed page height, and manipulate it so that e.g. zoom = 1 -> height = 300, zoom = 1.5 -> height = 450.

so I've tried adding that in with inline styling but doesnt seem to do anything, tried messing about in the examples on the react-pdf page and couldn't get them to work with explicit height values either, tried it on document and page

any suggestions?

```
<div
          className={css.pdfDocument}
        >
          <Document
            file={signedUrl}
            onLoadSuccess={this.onDocumentLoad}
          >
            <Page
              className={css.pdfPage}
              pageNumber={pageNumber}
              renderTextLayer={false}
              scale={zoom}
              style={{ height: 750 }}
            />
          </Document>
        </div>
```

**Comment by wojtekmaj** [comment]
Read the docs. There's no `style` prop on `Page`. There's `height` prop.

**Comment by WhiskyToad** [comment]
> Read the docs. There's no `style` prop on `Page`. There's `height` prop.

Sorry was getting you mixed up with the other package I think

I've set the height and it is working now, the problem still exists though that when changing page the canvas/svg briefly flickers to 0 height and then back again causing the content below to flicker up then  back down

**Comment by wojtekmaj** [comment]
Wrap Page in a custom wrapper that holds specific height until Page actually gets rendered.

```
<div style={{ height }}>
  <Page height={height} />
</div>
```

**Comment by WhiskyToad** [comment]
THATS IT!! Thanks

incase anyone has a similar problem here's what I did, remember to remove the scale prop otherwise you get double zoom

```
<div
          className={css.pdfDocument}
        >
          <Document
            file={signedUrl}
            onLoadSuccess={this.onDocumentLoad}
          >
            <div style={{ height: 650 * zoom }}>
              <Page
                className={css.pdfPage}
                pageNumber={pageNumber}
                renderTextLayer={false}
                height={650 * zoom}
              />
            </div>
          </Document>
        </div>
```
