### ISSUE TITLE
can not load worker file successfully

### ISSUE THREAD

**Issue by zhangolve** [wojtekmaj/react-pdf#827]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I want to load worker file successfully so I could load pdf
**Describe solutions you've tried**

Describe solutions you've already tried, if any. Make sure to include code samples if you're stuck on implementation.

I am working on integrate `react-pdf` with my project. I am using webpack on my project.
I want to do use `worker`,  so just like `readme`  said,I add those code to my project:

`import { Document } from 'react-pdf/dist/entry.webpack';`  

But something wired happened.

![image](https://user-images.githubusercontent.com/7566337/128842400-7de45562-f661-4bbd-a1e9-7f1fc17e11c2.png)
![image](https://user-images.githubusercontent.com/7566337/128842652-fcbbc550-3458-47a2-929d-aba02da3a9c2.png)
![image](https://user-images.githubusercontent.com/7566337/128842768-954b8b1e-9540-440a-a081-af7d974d05ce.png)

`Unsafe attempt to load URL https://localhost:9007/static_cm_mgr/fe3e32f5df991e322a27.worker.js from frame with URL https://mycustomsite.com/reports/6111dbd2a6f41a13e35f04e6. Domains, protocols and ports must match.`

It seems because `worker.js` can not load successfully , so the pdf file could not load successfully  either.

**Additional information**

You know, currently we would do some proxy work using `nginx` or something else ([requestly](https://chrome.google.com/webstore/detail/requestly-redirect-url-mo/mdnleldcmiljblolnjhpnblkcekpdkpa) ), so once request some static files from our website, we could redirect to our local static file . Everything was fine before, but now when requesting a worker file, an error occurs just like the screenshot shows

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:

Chrome 92
 - React-PDF version [e.g. 3.0.4]:

V4.2.0 (I am using V4 because I want to support IE11)
 - React version [e.g. 16.3.0]:

 V16.13.1
 - Webpack version (if applicable) [e.g. 4.16.2]:
V4.35.2

**Comment by wojtekmaj** [comment]
Well. Just like the message says. You seem to be using custom domain Webpack may not know about (?). Webpack hosts the website on https://localhost:9007. You're trying to load it from https://mycustomsite.com/ which may be e.g. proxied using `hosts` file locally.

1. Access your website from https://localhost:9007
2. Configure Webpack to understand https://mycustomsite.com/ is your dev domain.

**Comment by wojtekmaj** [comment]
This could help: https://webpack.js.org/configuration/dev-server/#devserverhost
and if not, then this: https://webpack.js.org/configuration/dev-server/#devserverpublic
