### ISSUE TITLE
Background image does not load for some PDFs

### ISSUE THREAD

**Issue by anniebombanie** [wojtekmaj/react-pdf#832]
**Before you start - checklist**

 - [✔︎] I followed instructions in documentation written for my React-PDF version
 - [✔︎] I have checked if this bug is not already reported
 - [✔︎] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [✔︎] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**
PDF should look like this:
![yes](https://user-images.githubusercontent.com/42328163/130290046-c3aeb5eb-4341-4111-b42c-30961398cae7.png)

Instead it renders like this:
![no](https://user-images.githubusercontent.com/42328163/130290057-7ed35b24-f6dc-4d92-b8af-f9360e699fbd.png)

It displays a white background and this seems to be an issue in certain viewers. Here's are some other viewers I tested with,
where it works and where it fails:
- *WORKS HERE:* Chrome, [SodaPDF](https://www.sodapdf.com/), Adobe Acrobat Reader
- *DOESN'T WORK HERE:* Firefox, Safari, [DocFly](https://www.docfly.com/), Apple Preview

**Steps to reproduce**
1. Render this PDF using React-PDF: [welzRkYrNV6JRO8q.pdf](https://github.com/wojtekmaj/react-pdf/files/7023899/welzRkYrNV6JRO8q.pdf)
2. Alternatively, you can also open in the 6 viewers mentioned above to see the difference.

**Expected behavior**
To be able see the background image on the second page.

**Environment**
 - React-PDF version [4.2.0 but also tried 5.3.2]:
 - React version [16.13.1]:

**Comment by wojtekmaj** [comment]
It doesn't work even in the latest [PDF.js](https://mozilla.github.io/pdf.js/web/viewer.html), so this is supposed to be [raised to Mozilla instead](https://github.com/mozilla/pdf.js/issues/new).
