### ISSUE TITLE
Unable to load file in binary format

### ISSUE THREAD

**Issue by binobose** [wojtekmaj/react-pdf#837]
Iam trying to load a pdf file from an API response which is binary I believe, as it starts with %PDF when opened in notepad. It's returning an error as it is considering it as a string and take it as a url to load the pdf. Please help me to convert the binary to a format which is acceptable for the 'file'.

Meanwhile of I pass the api url with headers in the 'file', it loads the pdf file perfectly fine but whenever I click on zoom in or out which is custom made, it calls the api for each click, which is not the right way.

Please let me know how to resolve this issue

**Comment by wojtekmaj** [comment]
Try `file={dataFile}` where `dataFile` would be a memoized object that has `{ data: pdf }` structure. Make sure PDF isn't a string but actual binary data.

**Comment by binobose** [comment]
> Try `file={dataFile}` where `dataFile` would be a memoized object that has `{ data: pdf }` structure. Make sure PDF isn't a string but actual binary data.

It's not an object I guess, it's a binary but if I try the typeof, it returns string. How to handle in that case? Am I doing it wrong?

**Comment by wojtekmaj** [comment]
Huh, so if it's a string, not e.g. Uint8Array, then you'd need to convert data to actual binary format. Otherwise PDF.js doesn't really know what to do - it looks like a URL or data: URI, yet it isn't one.

I would need to do some trial and error on your specific case to get it right though.

**Comment by binobose** [comment]
> Huh, so if it's a string, not e.g. Uint8Array, then you'd need to convert data to actual binary format. Otherwise PDF.js doesn't really know what to do - it looks like a URL or data: URI, yet it isn't one.
> 
> I would need to do some trial and error on your specific case to get it right though.

Oh ok, then to which format should I convert it to? My primary concern is, if I'm passing the api url and headers to the file as input, it works fine but on every zoom in/out it's calling the api again. I'm just setting the scale of page in zoom method. Please suggest a solution.

**Comment by Sharcoux** [comment]
Try to downgrade to version 4. It was working by then and stopped working on v5 for some reason.

**Comment by binobose** [comment]
> Try to downgrade to version 4. It was working by then and stopped working on v5 for some reason.
> 
> Might be a duplicate of this: #737

I tried downgrading, but still no luck. Please suggest an alternative

**Comment by Sharcoux** [comment]
Ok, 3 points to verify:

1. What is the format of your file? If it's a buffer, you probably have nothing to do. If it's a string, you need to convert it this way: `Buffer.from(content, 'binary' | 'base64' | 'utf8').buffer`. Pick the correct encoding.

2. Ensure that you are correctly importing the `worker.js` file. Check the [readme](https://github.com/wojtekmaj/react-pdf) for usage with webpack for instance

3. Ensure that the pdf content is not corrupted. You can open it with: ```window.open(`data:application/pdf;base64,${base64}`, '_blank')```

**Comment by binobose** [comment]
> Ok, 3 points to verify:
> 
> 1. What is the format of your file? If it's a buffer, you probably have nothing to do. If it's a string, you need to convert it this way: `Buffer.from(content, 'binary' | 'base64' | 'utf8').buffer`. Pick the correct encoding.
> 2. Ensure that you are correctly importing the `worker.js` file. Check the [readme](https://github.com/wojtekmaj/react-pdf) for usage with webpack for instance
> 3. Ensure that the pdf content is not corrupted. You can open it with: `` window.open(`data:application/pdf;base64,${base64}`, '_blank') ``

Hi, I've been told that the API response is bnary, but infact if I check the response in network tab in browser, I am getting a string with special characters and junk data starting with %PDF. I believe its a string format which the pdf input cannot read. If I save the response to a text file and rename it to pdf, its opening in acrobat viewer without any error. Worker js has been imported properly as given in the doc. Please provide a solution.

**Comment by Sharcoux** [comment]
Then you are indeed facing a binary string. Just feed react-pdf with `Buffer.from(content, 'binary').buffer`

**Comment by binobose** [comment]
> Then you are indeed facing a binary string. Just feed react-pdf with `Buffer.from(content, 'binary').buffer`

Infact the have tried that solution as well, which you had suggested earlier. But for all these I'm getting the same Failed to load issue and the response string is send as a param in the url.

**Comment by Sharcoux** [comment]
You can try `utf16le` encoding maybe?

**Comment by binobose** [comment]
> You can try `utf16le` encoding maybe?

Tried, still no luck.

**Comment by binobose** [comment]
@wojtekmaj - could you please help, I'm still stuck at this point.

**Comment by Sharcoux** [comment]
Copy your pdf into a file. Check that it works if you open it with other tools like the browser. Then create or find a codesandbox with react pdf that will load this pdf. Then put the link here. This way we can help.

**Comment by liucong1** [comment]
I had the same problem.

Attempt to modify the responsetype property of the request:

```
axios({
    url,
    method: 'get',
    **responseType: 'blob'** // important
})
```
Then you can assign the returned data directly to file

**Comment by binobose** [comment]
Finally my Architect came to my rescue, fixed it by adding responseType: 'arrayBuffer' to the Axios config.

**Comment by jarretmoses** [comment]
@binobose would you mind posting your solution with axios + the pdf viewer. I am having the same issue as you but haven't been able to figure it out.

**Comment by binobose** [comment]
> @binobose would you mind posting your solution with axios + the pdf viewer. I am having the same issue as you but haven't been able to figure it out. When I use `arraybuffer` the entire response gets encoded with the response message etc...


HI @jarretmoses  - please try this
```
const apiCall = `${url}/doc/${id}`
// converting to arrayBuffer
const updateConfig = {...config, responseType: "arrayBuffer"}
myAPIService.get(apiCall, "", updateConfig).then((res)=>{setData(res.data)})_

```

and the myAPIService would be like

```
APIService.get = (url, arg = '', options) => {
  return axios.get(url + arg, {...options})
}
```

**Comment by june26** [comment]
> Finally my Architect came to my rescue, fixed it by adding responseType: 'arrayBuffer' to the Axios config.

hi, I have the same problem, I have tried the same solution as you. I want to display on modal, but what I get is just blank

`axios.get(
      urlDownload,
      { 
        headers: {
          'Content-type': 'application/json',
          'x-api-key': this.props.auth?.id_token,
        },
        'responseType': 'arraybuffer',
      },
    )
    .then(res => {
      this.setState({
        pdfFile: res
      })
    })
    .catch((err) =>{
      console.log('err',err)
    })`


`<Modal
    title="Preview"
    open={this.state.togglePreview}
    onOk={this.handleCloseModal}
    onCancel={this.handleCloseModal}
    footer={null}
  >
    <Document file={this.state.pdfFile}/>
  </Modal>`
  
  
  did I miss something?

**Comment by klaus7** [comment]
This `    <Document file={this.state.pdfFile}/>` should be `    <Document file={{ data: this.state.pdfFile}}/>`

**Comment by Anhaachan** [comment]
imagine didn't completely solved . then closing xD

**Comment by sangaaravind** [comment]
onLoadSuccess = ({ numPages }: any) => {
         this.setState({ pdfPageCount:numPages });
         
      };

  <Document
                        file={{data: this.props.ContractFile }}
                         onLoadSuccess={this.onLoadSuccess}
                       
                         onLoadError={this.onDocumentLoadError}
                    >
                        {[...Array(4)].map((_, index) => (               
                            <Page key={index} pageNumber={index + 1} /> 
                            ))}
 
                    </Document>

The above code is having issue "### Failed to load PDF file."

if I comment the line  onLoadSuccess={this.onLoadSuccess} as shown in the below code I am **not** getting the error.

 onLoadSuccess = ({ numPages }: any) => {
         this.setState({ pdfPageCount:numPages });
         
      };

  <Document
                        file={{data: this.props.ContractFile }}
                       //  onLoadSuccess={this.onLoadSuccess}
                       
                         onLoadError={this.onDocumentLoadError}
                    >
                        {[...Array(4)].map((_, index) => (               
                            <Page key={index} pageNumber={index + 1} /> 
                            ))}
 
                    </Document>

when i am trying to use onLoadSuccess={this.onLoadSuccess} and set a state inside the function I am getting error "Failed to load PDF file."


using react-pdf Version : 8.0.2

**Comment by v-arasanga** [comment]
onLoadSuccess is causing error : Error to load PDF, while trying to do (React) setState in side a function of onLoadSuccess , if i am not using onLoadSuccess, No error.

onLoadSuccess = ({ numPages }: any) => {
this.setState({ pdfPageCount:numPages });
};

<Document
file={{data: this.props.ContractFile }}
onLoadSuccess={this.onLoadSuccess}

                     onLoadError={this.onDocumentLoadError}
                >
                    {[...Array(4)].map((_, index) => (               
                        <Page key={index} pageNumber={index + 1} /> 
                        ))}
                </Document>
