### ISSUE TITLE
PDF files will be show at left and then centered, not all of them are centered at the beginning

### ISSUE THREAD

**Issue by kouwenpipon** [wojtekmaj/react-pdf#838]
**Before you start - checklist**

 - [yes] I have read documentation in README
 - [yse] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [yse] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'd like to display multiple pages of my PDF in chrome.
but, after I tested it many times, I found that some PDF files will be left first and then centered on chrome, not all of them are centered at the beginning

**Describe solutions you've tried**

**Additional information**

![image](https://user-images.githubusercontent.com/20450981/131605663-0896d2dd-55de-49b5-ae76-c752bad503ac.png)

![image](https://user-images.githubusercontent.com/20450981/131605674-960c5e72-65d6-4c6f-b30e-618a3a069fb8.png)

**Environment**
windows10、andorid10 webview 91
 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]:
 - React version [e.g. 16.3.0]:
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by wojtekmaj** [comment]
Can you pass some code example using CodeSandbox?
