### ISSUE TITLE
Different directory for worker and bundle?

### ISSUE THREAD

**Issue by prionkor** [wojtekmaj/react-pdf#84]
I am trying to use this library but unfortunately it is looking for the bundle and worker file at the root of the site instead of my custom directory `/js/dist/` is there any way of set the path for worker and bundle js files?

**Comment by wojtekmaj** [comment]
Hey @prionkor!
Not really at this point, I'm afraid. That would only be possible if I manage to create a custom entry file that allows you to pass custom, even more advanced config to PDF.js. If you need it right now, I'd suggest creating a custom entry file on your own based on some that already exist, with setting proper parameters to PDF.js [like so](https://github.com/wojtekmaj/react-pdf/blob/master/src/entry.noworker.js#L8). The parameter you're looking for is `workerSrc`.

**Comment by wojtekmaj** [comment]
Hey @prionkor,
support for custom settings have just landed in v2.3.0. Check it out :)
