### ISSUE TITLE
Text selection is displayed incorrectly (30-40px lower).

### ISSUE THREAD

**Issue by Don-Yin** [wojtekmaj/react-pdf#840]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Selected texts are around 25px lower than where they should be, which makes them extramely difficult to copy.

**Steps to reproduce**

```js
        <Document
          file="/assets/docs/cache.pdf"
          onLoadSuccess={onDocumentLoadSuccess}>
          <Page pageNumber={pageNumber} scale={scale} />
        </Document>
```
I followed your github homepage intro, did a vannila script, nothing special.
Here are some examples:

**Expected behavior**

If this is a known bug:  take my apologies and please explain the fix.
If unknown bug: fix.
If not a bug but me using it incorrectly: please explain the cause. 

**Additional information**

<img width="191" alt="Screenshot 2021-09-06 at 01 34 55" src="https://user-images.githubusercontent.com/65135356/132146113-55b15020-f42e-474c-be32-f2dcac248f84.png">
<img width="635" alt="Screenshot 2021-09-06 at 01 32 16" src="https://user-images.githubusercontent.com/65135356/132146119-ecd660c4-6937-4d5f-80eb-3d817286ca94.png">

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: tested on both chrome Version 93.0.4577.63 and firefox 91.0.2 (64-bit) both has it present.
 - React-PDF version [e.g. 3.0.4]: 5.3.2
 - React version [e.g. 16.3.0]: 17.0.1
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by Nxtra** [comment]
@Don-Yin , did you find a solution for this?
I have the same issue!
