### ISSUE TITLE
Invalid regular expression in Legacy Build

### ISSUE THREAD

**Issue by aedryan** [wojtekmaj/react-pdf#844]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

When I try to use 5.4.0-beta.3 in Chrome 63 I get an error about an invalid regular expression.  [The offending regex](https://github.com/mozilla/pdf.js/pull/13560/files#diff-b1cd4438c6073788e958b72e3305c9fb735c6b3be603fd5e904a099bbb9fd00cL27-L30) was removed from pdfjs which was included in [their latest release](https://github.com/mozilla/pdf.js/releases/tag/v2.10.377).  

**Steps to reproduce**

1. Try to render a PDF in Chrome 63.
2. Crash occurs.

**Expected behavior**

The PDF to render.

**Additional information**

None.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Chrome 63
 - React-PDF version [e.g. 3.0.4]: 5.4.0-beta.3
 - React version [e.g. 16.3.0]: 16.14.0
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.46.0

**Comment by wojtekmaj** [comment]
The problem is that this is a pre-release, not release. We can't be using pre-releases here, unfortunately.

**Comment by aedryan** [comment]
Thanks for your feedback, I expected as much but figured I'd get the ball rolling for when PDFJS properly releases this build.

**Comment by tdida** [comment]
`Uncaught SyntaxError: Invalid regular expression: /([\p{N}\p{L}\p{M}]+)|([^\p{N}\p{L}\p{M}]+)/: Invalid property name in character class
`

 the same problem

- android os version: Android 10
- Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Chrome 78.0.3904.108
- React-PDF version [e.g. 3.0.4]: 5.5.0
- React version [e.g. 16.3.0]: 17.0.2

**Comment by wojtekmaj** [comment]
PDF.js was updated in latest version of React-PDF and this problem should now be resolved.
