### ISSUE TITLE
Issue with the deps when building TypeScript app 

### ISSUE THREAD

**Issue by INSTA-Hugo** [wojtekmaj/react-pdf#848]
**Before you start - checklist**

 - [y] I followed instructions in documentation written for my React-PDF version
 - [y] I have checked if this bug is not already reported
 - [y] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [y] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

I have using the latest package version, and my install is clean.

pdfjs-dist recently changed their types, this is causing some Dependencies errors when building an app using TypeScript + react-pdf (and any other pdf related feature/library I believe).

The old imports were:
import { PDFDocumentProxy } from 'pdfjs-dist';

It is still possible to import the same types like this:
import { PDFDocumentProxy } from 'pdfjs-dist/types/display/api';

However, apparently types in @types/react-pdf also have some bad references that look like they need to be patched:

node_modules/@types/react-pdf/dist/Document.d.ts:2:10 - error TS2305: Module '"pdfjs-dist"' has no exported member 'PDFDocumentProxy'.
2 import { PDFDocumentProxy } from 'pdfjs-dist';
           ~~~~~~~~~~~~~~~~
node_modules/@types/react-pdf/dist/Outline.d.ts:2:10 - error TS2305: Module '"pdfjs-dist"' has no exported member 'PDFTreeNode'.
2 import { PDFTreeNode } from 'pdfjs-dist';
           ~~~~~~~~~~~
node_modules/@types/react-pdf/dist/Page.d.ts:2:10 - error TS2305: Module '"pdfjs-dist"' has no exported member 'PDFPageProxy'.
2 import { PDFPageProxy as _PDFPageProxy } from 'pdfjs-dist';
As a temporary, not recommended, not stable way to proceed, it is possible to directly modify the imports in the Node_modules, BUT, for some reason the 'PDFTreeNode' seems to have disappeared and therefor cannot be imported. Thus making it impossible to build the app :-(

**Steps to reproduce**

1. Create React-app with Vite and TypeScript
2. Install React-PDF + related @types/react-pdf
3. Build application

**Expected behavior**

The application proceeds and succeed.

**Additional information**

I also created a discussion on https://github.com/DefinitelyTyped/DefinitelyTyped/issues for this issue is also closely related to it.

**Environment**

 - React-PDF version [5.3.2]:
 -@types/react-pdf version [5.0.6]:
 - Typescript version [4.3.2]:
 - Vite version [2.3.8]
 - React version [17.0.2]:

As a temporary, not recommended, not stable way to proceed, it is possible to directly modify the imports in the Node_modules, BUT, for some reason the 'PDFTreeNode' seems to have disappeared and therefor cannot be imported. Thus making it impossible to build the app :-(

Any other workaround that might unlock the situation or idea when an update could correct this issue ?

Thanks in advance and have a nice day,
Hugo

**Comment by wojtekmaj** [comment]
Since TypeScript support is provided externally I don't think there's anything that can be done here, but I'll keep this thread open for visibility should someone be able to help out.

**Comment by JorgenRe1** [comment]
Since 2 years i've done:
> import { pdfjs, Document } from "react-pdf";
Then i get type eg:
> pdf: pdfjs.PDFDocumentProxy

If il be hones, i have no idea if it is a good solution, but it works, and you should already be importing pdfjs to set pdfjs.GlobalWorkerOptions.workerSrc = "..."

**Comment by INSTA-Hugo** [comment]
The functionalities are actually fully working, the issue happens purely at the building step, which is... well, super problematic.
I keep on looking for a solution, but it seems that I will be stuck with that for some time...

**Comment by wojtekmaj** [comment]
If you consider it resolved, so do I :)
