### ISSUE TITLE
unable to upload multipage PDF to browser with react-pdf

### ISSUE THREAD

**Issue by nitish-kalra-9** [wojtekmaj/react-pdf#855]
I am working on a project where the requirement is to upload a multipage pdf file, for which I am using react-pdf, I have implemented as mentioned in the sample.jsx of their node module, and I am failing to upload multipage pdf, only a single page is drawn on the browser, adding to that I am unable to find the value of 'numPages', here is the link to the sandbox, please let me know what else could be done.
https://codesandbox.io/s/react-pdf-multiple-file-upload-issue-forked-k5gmv

**Comment by wojtekmaj** [comment]
It's literally in the README:

https://github.com/wojtekmaj/react-pdf#usage

```
const onDocumentLoadSuccess = ({ numPages }) => {
  setNumPages(numPages);
}
```

**Comment by nitish-kalra-9** [comment]
Thanks, @wojtekmaj for looking into it, eventually I used the same code, but due to eslint it was marked as an invalid code, as numPages was already declared in the upper scope. 
I guess I've to suppress the eslint warning like this, which is working for me.
 `// eslint-disable-next-line no-shadow`
`const onDocumentLoadSuccess = ({ numPages }: any) => {
    setNumPages(numPages);
    setLoading(false);
  };`

Thanks for your help.

**Comment by wojtekmaj** [comment]
You could write `({ numPages: nextNumPages })`
