### ISSUE TITLE
XFA pdf support 

### ISSUE THREAD

**Issue by Liocat-sp** [wojtekmaj/react-pdf#856]
hey hi,

I would like to know the do you guys support XFA PDF rendering. So that user can view the PDF in react web app.
or is there any plan regarding the XFA PDF's support in react-pdf in the future.

Thanks in advance.

**Comment by wojtekmaj** [comment]
Looks like either we are, or will in the near future:

https://github.com/mozilla/pdf.js/issues/2373

**Comment by Liocat-sp** [comment]
Sir, you were way too quick, thanks.

I am looking forward to react-pdf XFA support. Till then will try doing my own integration of pdfjs.in React its kinda tricky, let see what happens.

and thanks again for the instant reply.

**Comment by wojtekmaj** [comment]
Update: React-PDF 5.4.0 includes PDF.js 2.9.359 update which, quoting Mozilla,  includes "improved XFA support (which is still experimental)".
There's also a pre-release of PDF.js 2.10.377 which will include "improved XFA support", but we will have to wait for the next stable release to update the dependency in React-PDF.

Not sure if there's any action, besides updating PDF.js, on our side? @Liocat-sp mind checking out the latest release?

**Comment by wojtekmaj** [comment]
v5.6.0 now runs PDF.js 2.10.377 which supports XFA.
