### ISSUE TITLE
"Invalid PDF structure."

### ISSUE THREAD

**Issue by pooldeveloper** [wojtekmaj/react-pdf#858]
This is my code and the PDF viewer is not working for me, I see that some say that it is a CORS problem but in the console it does not mark anything of CORS it marks me this and of course the PDF is perfectly visible in the browser already logging in
I hope any help thanks!

![image](https://user-images.githubusercontent.com/74687129/134757567-c7b09861-63c1-477f-ae43-f3e2039b48d0.png)

```
import React,{useState} from "react";
import { Document, Page } from 'react-pdf';
import { pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js`;


const Pdf = () => {

  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }

  return (
    <div>
     <Document
        file="https://demo.efirmalegal-dev.com/docslab/download-document/5141?content-disposition=inline"
        onLoadSuccess={onDocumentLoadSuccess}
      >
        <Page pageNumber={pageNumber} />
      </Document>
      <p>Page {pageNumber} of {numPages}</p>

    </div>
  );
};

export default Pdf; 
```

**Comment by wojtekmaj** [comment]
English please

**Comment by pooldeveloper** [comment]
@wojtekmaj  It is already translated

**Comment by wojtekmaj** [comment]
Looks like PDF.js can't quite read the PDF you're providing. Did you try downloading the PDF and opening it in Mozilla Firefox? If it won't work but you're sure that the PDF is correctly built, we will need to raise an issue against [mozilla/pdf.js](https://github.com/mozilla/pdf.js/).

**Comment by avichovatiya67** [comment]
Getting the same issue
Tried opening it in the browser and worked well
The only issue with this package.

**Comment by dvs110** [comment]
> Getting the same issue Tried opening it in the browser and worked well The only issue with this package.

Have u tried using another package?

**Comment by ideajohnson** [comment]
I got this error as well (same invalid characters as the screenshot). I could open the pdf in the browser.

I had two react functions. The first one i passed a memoized src url for the second function to memoize again which lead to invalid pdf error. I removed the first memoized one and it worked. 

![Image](https://github.com/user-attachments/assets/f481d20d-a617-468f-99ba-cd9c3cf5fd58)
