### ISSUE TITLE
Ability to access page dimensions in child component easily

### ISSUE THREAD

**Issue by michaeldzjap** [wojtekmaj/react-pdf#86]
It is great *react-pdf* now supports child components of `Page`. It would be nice though if the page dimensions were passed as a property to any child components. So instead of just passing {this.props.children} if you would do something like this in the render() of Page:
```javascript
const childProps = {
    scale: this.scale,
    width: page.pageInfo.view[2],
    height: page.pageInfo.view[3]
};
...
{Children.map(children, child => React.cloneElement(child, childProps))}
```
It would be quite convenient to have access to these properties in any children easily. For instance if you want to give a child component the same dimensions as the parent (page) component or if your child components need to be scaled relative to page width or height.

**Comment by wojtekmaj** [comment]
Hmmm, that's an interesting idea, although I must take into account that different types of components may land in <Document>, sometimes they may be simple <div>s which would cause React to throw a warning. So props would need to be filtered depending on what the children can support. That would be quite hard.

So I'd suggest to define childProps at your component level for the time being.

**Comment by michaeldzjap** [comment]
Yes, I see your point. No problem, I can workaround it for my specific use case.

**Comment by wojtekmaj** [comment]
Great! In case you stumble upon a smart solution I'd be happy to implement it.
