### ISSUE TITLE
Sticky note annotation

### ISSUE THREAD

**Issue by ashamn** [wojtekmaj/react-pdf#860]
**Before you start - checklist**

 - [X] I followed instructions in documentation written for my React-PDF version
 - [X] I have checked if this bug is not already reported
 - [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

When the PDF has a sticky annotation, it will not display correctly on the screen.

![image](https://user-images.githubusercontent.com/23427992/135020531-a228af0c-4796-4955-8e9e-12d37c0c4d47.png)

**Steps to reproduce**

1. Add sticky annotation in Acrobat reader
![image](https://user-images.githubusercontent.com/23427992/135020628-2b48fdaa-edb1-4a6f-b9d0-13a920a8ec41.png)
2. Upload PDF in the test server
https://projects.wojtekmaj.pl/react-pdf/test/

**Expected behavior**

There won't be this in the display
![image](https://user-images.githubusercontent.com/23427992/135020853-950c83b2-bb66-46db-b4db-af3b4a701fd2.png)

**Comment by wojtekmaj** [comment]
Do you have a test PDF on you by any chance?

**Comment by ashamn** [comment]
Hi here is a sample pdf

https://www.dropbox.com/s/b2bfllsdeqp8p1g/test%20pdf%20for%20annot%20-%20edited.pdf?dl=0

Thank you.

**Comment by wojtekmaj** [comment]
It looks like it expects `annotation-comment.svg` to be present in your `/`. This and other annotation icons can be taken from https://github.com/mozilla/pdf.js/tree/master/web/images. But I definitely agree this should work out of the box.

**Comment by ashamn** [comment]
Thank you! I'll check those :)
