### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval' 

### ISSUE THREAD

**Issue by mskzo** [wojtekmaj/react-pdf#862]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

- Version 5.4.0 is using unsafe eval code that is not compatible with web apps using csp tags.
- 
react_devtools_backend.js:4049 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'nonce-RPukjdOq7L0Ry+9a/fRRIw==' 'nonce-Zu/WxXUZuiyYVpKneulw8w==' 'nonce-F/QtNUz/WFmYzFb11CAZrg=='".

    at Function (<anonymous>)
    at Object.__webpack_modules__ (pdf.js:1462)
    at __w_pdfjs_require__ (pdf.js:24579)
    at Object.__webpack_modules__ (pdf.js:866)
    at __w_pdfjs_require__ (pdf.js:24579)
    at Object.__webpack_modules__ (pdf.js:58)
    at __w_pdfjs_require__ (pdf.js:24579)
    at pdf.js:24820
    at pdf.js:24601
    at factory (pdf.js:33)

**Steps to reproduce**

- Build the app and define CSP header
(You can also test with csp-html-webpack-plugin in order to generte html tag)

**Comment by wojtekmaj** [comment]
@aleksil I think that's a great idea, but I don't have a clue at the moment on how we could implement that. `pdfjs-dist` is used in lots of places throughout the code.

**Comment by twistedpair** [comment]
+1 vote here, as we'll likely have to remove react-pdf from our apps, given it's insecure nature.

It really would be nice if this could be addressed.

**Comment by wojtekmaj** [comment]
Since v5.4.0, PDF.js has been updated twice in React-PDF. Is this still an issue?

I was able to run v5.7.1 with  `<meta http-equiv="Content-Security-Policy" content="script-src 'self'" />` added to html with no issues.

**Comment by mskzo** [comment]
The issue is still happening in the last two versions (5.7.1 and 5.7.2) if you use the entry.webpack.
**But It is not replicable if you use the Standard configuration described in the documentation.**

**Comment by jepek** [comment]
I can confirm - On `5.7.1` and `5.7.2` it messes up with our CSP

**Comment by wojtekmaj** [comment]
Based on https://github.com/wojtekmaj/react-pdf/issues/862#issuecomment-941005115 I believe that 6.0.0 beta may solve this issue.

**Comment by jepek** [comment]
I am sorry @wojtekmaj I made a mistake. I edited my comment.
