### ISSUE TITLE
Can Prop types be exported?

### ISSUE THREAD

**Issue by AndrewSmithDev** [wojtekmaj/react-pdf#863]
**Before you start - checklist**

 - [x] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
 - [x] I have checked if this feature request is not already reported

**Is your feature request related to a problem? Please describe.**

I would like to extend built in prop but it's very difficult to do so when the prop types are not exported

**Describe the solution you'd like**

I'd like the prop types to be exported so that I can extend them

i.e.

```
import { ChartConfiguration } from "chart.js";
import { ImageProps } from "@react-pdf/renderer";

type ChartImageProps = Omit<ImageProps, "src" | "source"> & {
  chartConfig: ChartConfiguration;
};
```

**Comment by wojtekmaj** [comment]
Wrong repository
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
