### ISSUE TITLE
Dead space rendered at the bottom of some pdfs

### ISSUE THREAD

**Issue by jelizarovas** [wojtekmaj/react-pdf#866]
**Before you start - checklist**

 - [x ] I followed instructions in documentation written for my React-PDF version
 - [x ] I have checked if this bug is not already reported
 - [x ] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x ] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Some of pdfs are rendered with extra margin of dead space at the bottom.

**Steps to reproduce**

Source pdf
[firstpage.pdf](https://github.com/wojtekmaj/react-pdf/files/7274488/firstpage.pdf)

1. I get page size of 612 x 792, with container size of 1127 x 1458.47, but the height is actually closer to 1600px. So this extra piece is being rendered without being recognised by page size. I've opened it up on adobe reader and extra space is non existent.
2. I just put a view layer wrapper around it with background so you can see the invisible extra.
3. I'm trying to render form fields based on the coordinates and to keep it consistent with pdf coordinate system where y starts at bottom left, but these extra margin keep throwing me off.

svg and canvas render the same thing

**Expected behavior**

I expect the pdf to render only within the bounds of the page and nothing extra

**Additional information**

![image](https://user-images.githubusercontent.com/15138718/135698231-fa88c925-7f62-4701-96fe-39edd7e7cc2c.png)

![image](https://user-images.githubusercontent.com/15138718/135698246-670fda4e-982d-4d77-ab1e-f9e864fb7fbe.png)

**Environment**

 - Browser Chrome 94, Firefox newest as today]:
 - React-PDF version [e.g. 3.0.4]: react-pdf": "^5.4.0",
 - React version [e.g. 16.3.0]:  "react": "^17.0.2",

**Comment by paescuj** [comment]
Are you importing annotation styles? See https://github.com/wojtekmaj/react-pdf#support-for-annotations

**Comment by wojtekmaj** [comment]
Tried your example in my test suite (https://projects.wojtekmaj.pl/react-pdf/test/) and it looks good. Maybe some of your styles are conflicting with the defaults we have, or what @paescuj mentioned?

**Comment by jelizarovas** [comment]
No, I am not importing annotation styles - I am rendering my own form fields by getting the coordinates with pdf2json. I have a workaround to limit the height to FormField layer to fit with the page size. But I am wraping the pdf around `react-zoom-pan-pinch` and certain pdfs render with a chin/dead space so it's not a deal breaker but a mild ux inconvenience. I'll try to setup a codepen to see if i can easily replicate it

**Comment by paescuj** [comment]
I was just asking because I had a similar issue and it was solved by importing the annotation styles... Codepen would be great!

**Comment by jelizarovas** [comment]
https://codesandbox.io/s/icy-morning-2tt31?file=/src/Pdf.jsx

I quickly threw this all together to showcase it. Most pdfs render within range, but about 10-15% I've tested seem to have the chin/dead space. So the question is is it `react-pdf` or the `react-zoom-pan-pinch issue`?

![image](https://user-images.githubusercontent.com/15138718/136619776-1cfe8f7b-4764-4f14-b4b9-b540099b9d5d.png)

**Comment by wojtekmaj** [comment]
These issues go away when you import annotation styles which are required if you're planning to use annotations.
