### ISSUE TITLE
Testing Component Using usePDF

### ISSUE THREAD

**Issue by Rafael805** [wojtekmaj/react-pdf#870]
**Before you start - checklist**

 - [x] I have read documentation in README
 - [x] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [x] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I'm trying to write unit tests for a component that uses usePdf and I am seeing the following error:

**Error: usePDF is a web specific API. You're either using this component on Node, or your bundler is not loading react-pdf from the appropriate web build.**

**Describe solutions you've tried**

I tried mocking usePdf by doing the following:

```
jest.mock("@react-pdf/renderer", () => ({
    usePdf: () => null
  }));
```

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]:
 - React-PDF version [e.g. 3.0.4]: 2.0.19
 - React version [e.g. 16.3.0]: 17.0.2
 - Webpack version (if applicable) [e.g. 4.16.2]:

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
