### ISSUE TITLE
Can't resolve 'canvas' in '(...)/node_modules/pdfjs-dist/build'

### ISSUE THREAD

**Issue by cezarcarvalhaes** [wojtekmaj/react-pdf#874]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**
When building my Gatsby app, I get a module not found error: ` Error: Can't resolve 'canvas' in '(...)/node_modules/pdfjs-dist/build'`

This is likely the same issue as #799 , however, that issue was closed and the issue and solution were Next.js-specific. I'm encountering this issue in Gatsby (v3). 

**Steps to reproduce**

1. Create a Gatsby App
2. Install react-pdf
3. Import react-pdf on a page and render a document.
4. run `gatsby build`

**Expected behavior**

What you expected to happen?
The app to build.

**Additional information**
I was able to get around this by locking my react-pdf version at 5.2 as suggested in this [comment](https://github.com/wojtekmaj/react-pdf/issues/799#issuecomment-888468679) from the #799 issue, however, this should not be a long-term solution. I encountered this error in version 5.4.1.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: N/A
 - React-PDF version [e.g. 3.0.4]: 5.4.1
 - React version [e.g. 16.3.0]: 17.0.2
 - Webpack version (if applicable) [e.g. 4.16.2]: 4.44.2

**Comment by transitive-bullshit** [comment]
This doesn't seem specific to Gatsby as I'm also getting the same error with Next.js `11.1.2` no matter how I try to import `react-pdf` (normal, dynamic, and dynamic w/ `ssr` disabled).

**Comment by jonavdd** [comment]
@cezarcarvalhaes @transitive-bullshit I'm encountering the same issue, did you find any solutions to this perhaps?

**Comment by wojtekmaj** [comment]
Are you able to provide full error stack, or a repro repo?

**Comment by jonavdd** [comment]
> Are you able to provide full error stack, or a repro repo?

The workaround to fix the version to v5.2.0 mentioned by @cezarcarvalhaes works for me to resolve the build part. But i encounter another issue. When using [gatsby navigate](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/) to go to a page with the react-pdf on page its stuck in a loading state without any errors. When doing a hard refresh it works. 

When using the latest version of react-pdf this navigation problem doesn't occur but the original error `Can't resolve 'canvas'` is back. So i'm kind of stuck.

**Comment by yordis** [comment]
```ts
webpack(config, { isServer }) {
      // https://github.com/wojtekmaj/react-pdf/issues/799
      // https://github.com/mozilla/pdf.js/issues/13373
      if (isServer) {
        config.resolve.alias.canvas = false;
      }

      return config;
    },
```

That is how I solved the issue, `canvas` usage in the SSR should be avoided since it wouldn't make much sense

**Comment by plbrault** [comment]
I had the same error while using react-pdf on Gatsby, and I fixed it using that solution to an issue on another package:
https://github.com/react-pdf-viewer/react-pdf-viewer/issues/497#issuecomment-812905172

**Comment by cezarcarvalhaes** [comment]
@wojtekmaj Sorry for the wait, here's a sample repo: https://github.com/cezarcarvalhaes/gatsby-react-pdf

It's failing in the SSR build, which makes sense. That must be why it works in development mode, but not in builds.

Also, a quick heads up, this same error throws in Gatsby 4: both in development and build.

**Comment by syed-ahmed** [comment]
Leaving this here if people are integrating react-pdf with something like docusaurus. I took @[yordis](https://github.com/yordis)'s solution and added a docusaurus plugin for react-pdf: https://github.com/syed-ahmed/docusaurus-plugin-react-pdf :). I was facing the problem mentioned in this issue before making this plugin. Since docusaurus exposes configuration of webpack using plugins, it made sense to encapsulate react-pdf as a plugin. The current plugin doesn't expose all the configuration that react-pdf provides and I don't have any plans right now to extend this, but contributions are welcome. My rendered pdfs look great, so thanks react-pdf authors!

![image](https://user-images.githubusercontent.com/8906225/160479835-cb1d7f9c-958d-452a-9f44-ee4dcddabd24.png)

**Comment by coltenkrauter** [comment]
This answer has a bit moe context: https://github.com/wojtekmaj/react-pdf/issues/799#issuecomment-864887752

**Comment by NobinPegasus** [comment]
Having the same issue while building app using gatsby. After I install react-pdf
Can't apply #799 because I'm using gatsby.

**Comment by wojtekmaj** [comment]
Please kindly try react-pdf@7.0.0-beta.3 or later.
