### ISSUE TITLE
How to go to a specific page number

### ISSUE THREAD

**Issue by amansani15** [wojtekmaj/react-pdf#884]
**Before you start - checklist**

 - [ ] I have read documentation in README
 - [ ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/wiki/Recipes) suites to see real life basic implementation
 - [ ] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I am able to add single page with navigation from you recipes. Now I am trying to add an input field to go to a specific page number. When I am passing some value to the field, it is failing to load the pdf file. Any inputs are highly appreciated.

**Describe solutions you've tried**
Below is the reference code

`import { useState } from 'react';
import useWindowDimensions from './pages/useWindowDimensions';
import 'src/index.css';

import {Document, Page, pdfjs} from 'react-pdf/dist/esm/entry.webpack'
pdfjs.GlobalWorkerOptions.workerSrc = '//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js'

export default function Testpdf(props) {

  var {selectedPageNumber} = props  
  var {selectedScaleNumber} = props
  var {shortAnswerIs} = props

  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(selectedPageNumber);
  const [scaleNumber, setScaleNumber] = useState(selectedScaleNumber);
  const { pdf } = props;

  const { height, width } = useWindowDimensions();
  
  
  function onDocumentLoadSuccess({numPages}) {
    setNumPages(numPages);
    setPageNumber(selectedPageNumber);
    setScaleNumber(selectedScaleNumber)
  }  

  function changePage(offset) {
    setPageNumber(prevPageNumber => prevPageNumber + offset);
  }  

  function previousPage() {
    changePage(-1);
  }

  function nextPage() {
    changePage(1);
  }

  function changeScale(offset) {
    setScaleNumber(prevScaleNumber => prevScaleNumber + offset);
  }

  function zoomIn() {
    changeScale(0.25);
  }

  function zoomOut() {
    changeScale(-0.25);
  }

  function onChange(event) {
    setPageNumber(event.target.value);
  }

  return (
    <div style={{ height: '95vh'}}>      
      <div>
        <p>
          Page {pageNumber || (numPages ? 1 : '--')} of {numPages || '--'}
        </p>
        <button type="button" disabled={pageNumber <= 1} onClick={previousPage}>Previous</button>
        <button type="button" disabled={pageNumber >= numPages} onClick={nextPage} >Next</button>
        <button id="zoominbutton" type="button" onClick={zoomIn}>zoom in</button>
        <button id="zoomoutbutton" disabled={scaleNumber <= 0.5} type="button" onClick={zoomOut}>zoom out</button>
        <label htmlFor="goToPageNumber">Page Number:</label>
        <input type="Number" id="goToPageNumber" value={pageNumber} onChange={onChange} />
      </div>
      <Document file={pdf} onLoadSuccess={onDocumentLoadSuccess} onLoadError={(error) => alert('Error while retrieving the outline! ' + error.message)}>
        
        <Page pageNumber={pageNumber} width={width} height={height} scale={scaleNumber}/>
                
      </Document>
      
      <p>Page {pageNumber} of {numPages}</p>
    </div>
  );
}`
**Additional information**
Below is the reference screenshot

![image](https://user-images.githubusercontent.com/62998123/141342275-ab03d9d3-6f2c-4ac4-a28b-191f4a4f7aa9.png)

**Environment**
 - React-PDF version 5.5.0:
 - React version 16.14.0:

Thanks for the nice library.

**Comment by amansani15** [comment]
Sorry, it's a small issue in conversion. Once I converted it to integer, it worked. Posting the fix here, as it may help others.

function onChange(event) {   
    setPageNumber(parseInt(event.target.value));  
  }

**Comment by wojtekmaj** [comment]
I don't see a reason why pageNumber="30" shouldn't work though. This looks like a room for improvement.
