### ISSUE TITLE
How to align the text with highlight text pattern when Zooming is used

### ISSUE THREAD

**Issue by amansani15** [wojtekmaj/react-pdf#885]
**Before you start - checklist**

 - [ ] I have read documentation in README
 - [ ] I have checked [sample](https://github.com/wojtekmaj/react-pdf/tree/master/sample) and [test](https://github.com/wojtekmaj/react-pdf/tree/master/test) suites to see real life basic implementation
 - [ ] I have checked if this question is not already asked

**What are you trying to achieve? Please describe.**

I have used Highlight text on the page from your recipes(https://github.com/wojtekmaj/react-pdf/wiki/Recipes#highlight-text-on-the-page). The highlight text pattern should change the location based on the actual text when zoom applied. Any inputs are highly appreciated. TIA.

**Describe solutions you've tried**
Below is the reference code

`import { useState, useMemo } from 'react';
import useWindowDimensions from './pages/useWindowDimensions';
import {Document, Page, pdfjs} from 'react-pdf/dist/esm/entry.webpack'
pdfjs.GlobalWorkerOptions.workerSrc = '//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js'

function highlightPattern(text, pattern) {
  const splitText = text.split(pattern);

  if (splitText.length <= 1) {
    return text;
  }

  const matches = text.match(pattern);

  return splitText.reduce((arr, element, index) => (matches[index] ? [
    ...arr,
    element,
    <mark key={index}>
      {matches[index]}
    </mark>,
  ] : [...arr, element]), []);
}

export default function Testpdf(props) {

  var {selectedPageNumber} = props
  var {isModal} = props
  var {selectedScaleNumber} = props
  var {shortAnswerIs} = props

  console.log("Scale Number is: " + selectedScaleNumber)
  
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(selectedPageNumber);
  const [scaleNumber, setScaleNumber] = useState(selectedScaleNumber);
  const [searchText, setSearchText] = useState(shortAnswerIs);

  const { pdf } = props;

  const { height, width } = useWindowDimensions();

  function onDocumentLoadSuccess({numPages}) {
    setNumPages(numPages);
    setPageNumber(selectedPageNumber);
    setScaleNumber(selectedScaleNumber)
  }  

  function onChangeSearch(event) {
    setSearchText(event.target.value);
  }

  function changePage(offset) {
    setPageNumber(prevPageNumber => prevPageNumber + offset);
  }  

  function previousPage() {
    changePage(-1);
  }

  function nextPage() {
    changePage(1);
  }

  function changeScale(offset) {
    setScaleNumber(prevScaleNumber => prevScaleNumber + offset);
  }

  function zoomIn() {
    changeScale(0.25);
  }

  function zoomOut() {
    changeScale(-0.25);
  }

  function onChange(event) {
    setPageNumber(parseInt(event.target.value));
  }

  

  return (
    <div style={{ height: '95vh'}}>
      
      <div>
        <p>
          Page {pageNumber || (numPages ? 1 : '--')} of {numPages || '--'}
        </p>
        <button type="button" disabled={pageNumber <= 1} onClick={previousPage}>Previous</button>
        <button type="button" disabled={pageNumber >= numPages} onClick={nextPage} >Next</button>
        <button id="zoominbutton" type="button" onClick={zoomIn}>zoom in</button>
        <button id="zoomoutbutton" disabled={scaleNumber <= 0.5} type="button" onClick={zoomOut}>zoom out</button><br />
        <label htmlFor="goToPageNumber">Page Number:</label>
        <input type="Number" id="goToPageNumber" value={pageNumber} onChange={onChange} />
        <label htmlFor="search">Search:</label>
        <input type="search" id="search" value={searchText} onChange={onChangeSearch} />
        
              
      </div>
      <Document file={pdf} onLoadSuccess={onDocumentLoadSuccess} onLoadError={(error) => alert('Error while retrieving the outline! ' + error.message)}>
        <Page pageNumber={pageNumber} scale={scaleNumber} 
                    customTextRenderer={(textItem) => (highlightPattern(textItem.str, searchText))}/>                 
      </Document>      
      <p>Page {pageNumber} of {numPages}</p>
    </div>
  );
}`

**Additional information**
With the right page size and width
![image](https://user-images.githubusercontent.com/62998123/141373381-23802a03-d3ed-4451-be87-1d0dd77ff04b.png)

With zoom value changed:
![image](https://user-images.githubusercontent.com/62998123/141373454-ef184716-286c-4d4a-9936-0a33e3b987aa.png)

**Environment**
 React-PDF version 5.5.0:
React version 16.14.0:

Thanks for the nice library.

**Comment by amansani15** [comment]
Any inputs on this are highly appreciated. TIA

**Comment by amansani15** [comment]
I would like to know if this is possible or not. Thank you

**Comment by wojtekmaj** [comment]
Please try 6.0.0 beta. Text rendering is completely changed in this version.
