### ISSUE TITLE
Loading PDF…

### ISSUE THREAD

**Issue by asadkhan-dbz** [wojtekmaj/react-pdf#889]
Hi, 

I am using react 15.0.1 & react-pdf 1.6.1, unable to load PDF file, I have created Codesandox where is the scenario, please have a look and assist thanks

[codesandbox react pdf@1.6.1](https://codesandbox.io/s/react-pdf-1-6-1-my5gd?file=/src/App.js)

**Comment by wojtekmaj** [comment]
1.6.1 🤯 Sorry mate, I won't be able to help you out with 3 years old version.
