### ISSUE TITLE
how to get the whole actions from Mozilla PDFjs

### ISSUE THREAD

**Issue by webbieram** [wojtekmaj/react-pdf#89]
Hi Woj,
first of all thx for the great plugin. Currently i m integrating it in my project and now i would like to implement other functionalities too (i.e zoom in , out , thumbnail panel, save, print action bar) in the project.

How can i achieve those actions in the react wrapper?

**Comment by wojtekmaj** [comment]
Hey @webbieram,
what you're trying to achieve is perfectly doable. However, [see this answer please](https://github.com/wojtekmaj/react-pdf/issues/69#issuecomment-332210718).

**Comment by sm3sher** [comment]
I doubt that printing can ever be achieved the same way as mozilla does it. Even gmail PDF-viewer opens a new window when clicking on print option. Besides that every other action can be done.
