### ISSUE TITLE
Some PDFs do not load. 

### ISSUE THREAD

**Issue by anna-feliz** [wojtekmaj/react-pdf#892]
**Before you start - checklist**

 - [x] I followed instructions in documentation written for my React-PDF version
 - [x] I have checked if this bug is not already reported
 - [x] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
 - [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in Mozilla Firefox

**Description**

Some PDF documents do not load. For many documents the react-pdf works perfectly, but some documents do not load. I am loading the PDFs through a link. If I download the same PDF-document I can open in with react-pdf from my local file system. So the problem is fetching a document via link. 

**Steps to reproduce**

Example of document that does not load: https://www.cs.brandeis.edu/~olga/publications/neo2019.pdf

This is how I define my pdf-worker: 
```
import { pdfjs } from "react-pdf";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
```

**Expected behavior**

All PDF-documents to load. 

**Additional information**

If applicable, add screenshots (preferably with browser console open) and files you have an issue with to help explain your problem.

**Environment**

 - Browser (if applicable) [e.g. Chrome 57, Firefox 59]: Firefox
 - React-PDF version : ^5.4.1
 - React version: ^17.0.2
 - Next.js version: 10.2.3

**Comment by wojtekmaj** [comment]
Are you sure you're not hitting CORS issue? Did you try to load this PDF from your domain, or through a proxy on your domain, instead?
