### ISSUE TITLE
Some pages not displayed on IPad / Colors changed on Safari 

### ISSUE THREAD

**Issue by pakindessama** [wojtekmaj/react-pdf#893]
I am using react-pdf to render pdf.

I tried canvas and svg as renderMode. Below are the issues I got with each of them.

1.  Canvas

On Ipad, i have a particular PDF for which some pages are not rendered

![WechatIMG132](https://user-images.githubusercontent.com/45748649/142794192-2dfa5d37-3f31-45d7-b3cb-ab62b9d9b51d.jpeg)
Switching from canvas to svg solves this issue but provokes other another issue

2. SVG

The background of some pages are missing on Safari

How it should be 

![pdf](https://user-images.githubusercontent.com/45748649/142794702-90ae382a-552c-4c49-952d-575544c348b4.png)

How it is:

![pdf2](https://user-images.githubusercontent.com/45748649/142794632-20664f61-a387-4ee3-b674-0518530a9396.png)

Switching from svg to canvas solves the issue.

Below is a
```

import React, {useState, useEffect} from 'react';
import { pdfjs, Document, Page }
    from 'react-pdf/dist/umd/entry.webpack'; // slower but support older browser
import pdfjsWorker from 'react-pdf/dist/umd/pdf.worker.entry';
import * as UI from "../../libs/libUI";
import CpBtnGoTop from "./CpBtnGoTop";
import 'react-pdf/dist/umd/Page/AnnotationLayer.css';

pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorker;

const CpPDF = props => {
    const [loading, setLoading] = useState(0);
    const [ttlP, setTtlP] = useState(0); //total page of pdf
    const [draw, setDraw] = useState(0); //total page of pdf
    const [w, setW] = useState(0); //screen Width
    const pdf = '/test_pdfjs.pdf';

    useEffect(() => {
        const onResize = () => { setW(UI.getScreenWidth()); };
        window.addEventListener('resize', onResize); //add listen on create
        onResize(); //for init;
        return () => { window.addEventListener('resize', onResize); }; //dont leak, remove on cleanup
    },[]);

    const onPdfLoad = l => {
        console.log({onPdfLoad:l});
        setLoading(false);
        setTtlP(l.numPages);
        setDraw(l.numPages);
        // setLoaded(1);
    };

    //const pageW = Math.max(320, w - 82); //For canvas
    const pageW = Math.max(320, w * 0.7); //For svg

    const pages = [];

    for(let i = 1; i <= Math.max(0, draw); i++){
        pages.push(<Page key={'pdfP'+i+'_w'+pageW} width={pageW} pageNumber={i}/>);
        pages.push(<div key={"Gap"+i} style={{padding:'8px'}}></div>);
    }

    const handleRightClick = (e) => {
        e.preventDefault();
    }

    return <>
        <center>
                <div>
                    <CpBtnGoTop />
                    <div onContextMenu={handleRightClick}>
                        { loading ?
                            <div className='pdf_loading'>{UI.Loader('64px')}</div>
                            : <div style={{padding:'8px'}}>
                            </div>
                        }
                        <div style={{width:'100%'}} id={'pdfBlock'}>
                            <Document file={pdf} onLoadSuccess={onPdfLoad} renderMode={'svg'}>
                                {pages}
                            </Document>
                        </div>
                    </div>
                </div>
        </center>
    </>
};
export default CpPDF;

```

**Comment by wojtekmaj** [comment]
You removed default bug template so important questions remained unanswered. Please follow the template and we'll see what we can do. 

https://github.com/wojtekmaj/react-pdf/blob/main/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by pakindessama** [comment]
> You removed default bug template so important questions remained unanswered. Please follow the template and we'll see what we can do.
> 
> https://github.com/wojtekmaj/react-pdf/blob/main/.github/ISSUE_TEMPLATE/Bug_report.md

The URL seems to be dead, you can just delete the issue and I will open a new one following the bug template. 
Thanks

**Comment by wojtekmaj** [comment]
Yep sorry about that - actually this inspired me to implement better issue templates based on a new functionality in GitHub. They are now based on interactive forms.
