### ISSUE TITLE
Watermark support (Enhancement)

### ISSUE THREAD

**Issue by bhaumik-rishabh** [wojtekmaj/react-pdf#894]
I will be nice if user can add watermark and render it to desired place.

**Comment by wojtekmaj** [comment]
You have access to canvas via `canvasRef` so you can do just that by directly drawing on canvas when React-PDF itself is done with drawing.

https://codesandbox.io/s/react-pdf-watermark-5wylx

**Comment by bhaumik-rishabh** [comment]
Thanks, for your quick reply, however I need one more favour if that functionality exist as, I want to download pdf file with added watermark.

**Comment by wojtekmaj** [comment]
That's not possible. React-PDF is only for displaying PDFs.

**Comment by bhaumik-rishabh** [comment]
Okay, thanks.
