### ISSUE TITLE
pdf open bug

### ISSUE THREAD

**Issue by muchirajunior** [wojtekmaj/react-pdf#897]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

my code is always failing to load the pdf
![image](https://user-images.githubusercontent.com/56454064/143245046-55b45fb5-24f1-49d3-ad96-a29165d2b50f.png)

### Steps to reproduce

x

### Expected behavior

open the pdf page 1

### Actual behavior

failed to load pdf

### Environment

```markdown
- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:
```

**Comment by wojtekmaj** [comment]
Likely a CORS issue, see #36

**Comment by muchirajunior** [comment]
thanks it was CORS problem.
