### ISSUE TITLE
is there a plan for page thumbnail?

### ISSUE THREAD

**Issue by suikodev** [wojtekmaj/react-pdf#898]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one, but since mostly all PDF viewer have page thumbnails for preview, i think it will be helpful to provide Thumbnail component. The Thumbnail component's usage could just like the Page component(be placed inside <Document />, provide pageIndex or pageNumber to choose which page's thumbnail to render...).

### Proposed solution

I have read the source code about how to  [generate thumbnails](https://github.com/mozilla/pdf.js/blob/master/web/pdf_thumbnail_view.js) in pdf.js and some code of react-pdf, if you think my idea is adoptable, I really hope you can give me a chance to work on this:)

**Comment by wojtekmaj** [comment]
I don't think `<Thumbnail />` could differ a lot from `<Page />`.

For rendering thumbnails, go for something like

```
<Page 
  pageNumber={pageNumber} 
  renderAnnotationLayer={false} 
  renderTextLayer={false} 
  width={100}
/>
```

**Comment by wojtekmaj** [comment]
And I was wrong! There's a tiny but very important difference: Thumbnails should not register themselves as "link target" which the page is scrolled to upon clicking an internal PDF link. This, plus some accessibility features.
