### ISSUE TITLE
Update pdf.js to 2.10.377

### ISSUE THREAD

**Issue by wojtekmaj** [wojtekmaj/react-pdf#900]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

Update pdf.js to 2.10.377

### Proposed solution

* Update pdf.js to 2.10.377
* Automatic tests
* Manual regression tests

**Comment by MatanYemini** [comment]
There are any objections to upgrading?

The update of PDF.js solves very annoying CSP issue

**Comment by wojtekmaj** [comment]
Not any I'm familiar with.

**Comment by shye0000** [comment]
ah so cool, I was struggling with CSP issue this morning, finished by downgrade react-pdf to make the error disapear.
