### ISSUE TITLE
Text Laxer is not positioning correctly when using Microsoft encoding and Helvetica Font

### ISSUE THREAD

**Issue by jocarrit** [wojtekmaj/react-pdf#903]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

We have an issue with an App, so I tried to reproduce the issue with the library demo code, and the bug is still there. After doing many tests, I tried with four documents I have created, all of them are equal, the difference is that two are on Mac encoding and two are on Microsoft 365 encoding, and two have Helvetica Font and two have Open Sans. Next, you can see how the text Layer is displaced on the X axis, this only happens on the Microsoft encoded document with Helvetica Font.

![Screen Shot 2021-12-08 at 1 35 06 PM](https://user-images.githubusercontent.com/6272200/145274286-efbd17de-9796-447f-8de5-526dfef79ae0.png)

As you can see there are some lines that are displaced on X axis, and if you see there are no `transform: scaleX( )` properties on the span's (textItem) CSS.

Now, this is an example of the same file with Mac encoding and Helvetica font:

![Screen Shot 2021-12-08 at 1 36 45 PM](https://user-images.githubusercontent.com/6272200/145274672-edcdd449-ac15-4033-b247-22fb759c6773.png)

You can see the text layer is placed correctly and there is a `transform: scaleX ( )` calculus for each span (textItem).

### Steps to reproduce

1. Using the sample example provided with the library, `Yarn start`
2. Open the PDF files with different encodings and different fonts (I have found Helvetica is causing more trouble)
3. Add this line to sample.less, to observe the text layer
```
.react-pdf__Page__textContent {
  span {
    color: pink;
  }
}
```

### Expected behavior

Shouldn't be any differences between encodings And the text Layer should be aligned

### Actual behavior

The text Layer is not aligned in the X-axis when using Microsoft encoding and Helvetica Font. In some cases because of this, the text selections don't work accurately.

### Additional information

Here are the example documents

[Lorem ipsum (open sans - mac enc).pdf](https://github.com/wojtekmaj/react-pdf/files/7678847/Lorem.ipsum.open.sans.-.mac.enc.pdf)

[Lorem ipsum (open sans microsoft enc).pdf](https://github.com/wojtekmaj/react-pdf/files/7678850/Lorem.ipsum.open.sans.microsoft.enc.pdf)

[Lorem ipsum (helvetica - mac enc).pdf](https://github.com/wojtekmaj/react-pdf/files/7678844/Lorem.ipsum.helvetica.-.mac.enc.pdf)

[Lorem ipsum (helvetica microsoft enc).pdf](https://github.com/wojtekmaj/react-pdf/files/7678845/Lorem.ipsum.helvetica.microsoft.enc.pdf)

### Environment

```markdown
- **Browser (if applicable)**: Chrome Version 96.0.4664.55
- **React-PDF version**: 5.5.0 , 5.4.0
- **React version**: 17.0.0
- **Webpack version (if applicable)**: 5
```

**Comment by wojtekmaj** [comment]
I believe #944 is going to fix this.
