### ISSUE TITLE
Error: The Array. prototype contains unexpected enumerable properties

### ISSUE THREAD

**Issue by Yangbg2018** [wojtekmaj/react-pdf#905]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hello, I encapsulate the components myself. The first time I enter the page, I can normally load PDF files. When I enter or load other PDFs again, I will be prompted: Message: "the 'array. Prototype' contains unexpected enumerable properties: getofbykey, indexofbykey, removebykey, replacelist; then breaking e.g. ` for... In 'iteration of' array 's.", name: "unknown errorexception", details: "Error: The `Array. prototype` contains unexpected enumerable properties: getOfByKey, indexOfByKey, removeByKey, replaceList; thus breaking e.g. `for... in` iteration of `Array`s.", stack: " BaseExceptionClosure@webpack :///./ node_ modules/react-pdf/node_ modules/pdfjs-dist/legacy/build

### Steps to reproduce

I hope you can help me as soon as possible

### Expected behavior

I hope you can help me as soon as possible

### Actual behavior

I hope you can help me as soon as possible

### Additional information

I hope you can help me as soon as possible

### Environment

```markdown
- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:
I hope you can help me as soon as possible
```

**Comment by voneiden** [comment]
This has nothing to do with react-pdf.  The [error message](https://github.com/mozilla/pdf.js/blob/a2a5376adff2a608fcf3fa9c08d3e951cf1b91ae/src/core/worker.js#L128) is from the pdf-js library, but even then the functions `getOfByKey`, `indexOfByKey`, `removeByKey`, `replaceList` come from elsewhere. I'm guessing they are from your own code. 

Fix the issue by ensuring that the Array prototype is not polluted by enumerable properties. See [defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) and the enumerable option.

**Comment by Yangbg2018** [comment]
> 

Thank you very much for your answer. I have solved this problem with your help. Thank you again.

**Comment by Yangbg2018** [comment]
> This has nothing to do with react-pdf. The [error message](https://github.com/mozilla/pdf.js/blob/a2a5376adff2a608fcf3fa9c08d3e951cf1b91ae/src/core/worker.js#L128) is from the pdf-js library, but even then the functions `getOfByKey`, `indexOfByKey`, `removeByKey`, `replaceList` come from elsewhere. I'm guessing they are from your own code.
> 
> Fix the issue by ensuring that the Array prototype is not polluted by enumerable properties. See [defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) and the enumerable option.

Thank you very much for your answer. I have solved this problem with your help. Thank you again.

**Comment by voneiden** [comment]
Good to hear! Also, please close the issue since it is now resolved. Thanks!
