### ISSUE TITLE
Circle not render properly when in renderMode svg

### ISSUE THREAD

**Issue by amakaa** [wojtekmaj/react-pdf#906]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I am rendering a PDF with the prop renderMode: svg and there are some circular shapes contained in the file. However it renders with a square box around it and with a weird shape inside. Code snippet 
`<Document
                    file={file}
                  >
                    <Page
                      pageNumber={1}
                      scale={scale}
                      width={width}
                      rotate={rotate}
                      renderMode="svg"
                    />
                  </Document>`

### Steps to reproduce

See screenshots

### Expected behavior
<img width="41" alt="Screenshot 2021-12-09 at 10 22 51" src="https://user-images.githubusercontent.com/2635534/145379054-83d20827-2286-4c8f-bc36-77d89ee5567a.png">

### Actual behavior
<img width="83" alt="Screenshot 2021-12-09 at 10 19 00" src="https://user-images.githubusercontent.com/2635534/145378252-5db6733e-cf3f-4011-a1e5-740bc2871df5.png">
Renders as clippaths

<img width="1254" alt="Screenshot 2021-12-09 at 12 31 36" src="https://user-images.githubusercontent.com/2635534/145388861-0066db91-9252-4f16-99a7-83ae0409c15f.png">

### Environment

```markdown
OS: MacOS
Browser: Chrome
React-PDF version:: 3.0.5
React version: 16.1.1
```

**Comment by wojtekmaj** [comment]
This looks like PDF.js issue, not React-PDF issue. Unfortunately Mozilla isn't interested in fixes around SVG mode.
