### ISSUE TITLE
Error: Setting up fake worker failed: "Cannot load script at: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.worker.min.js"

### ISSUE THREAD

**Issue by Yangbg2018** [wojtekmaj/react-pdf#909]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hello, I updated to the latest version, and prompted this: Error: Setting up fake worker failed: "Cannot load script at: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf. worker.min.js", the previous version is working normally. May I ask what's going on? 

### Steps to reproduce

Hello, I updated to the latest version, and prompted this: Error: Setting up fake worker failed: "Cannot load script at: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf. worker.min.js", the previous version is working normally. May I ask what's going on? 

### Expected behavior

Hello, I updated to the latest version, and prompted this: Error: Setting up fake worker failed: "Cannot load script at: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf. worker.min.js", the previous version is working normally. May I ask what's going on? 

### Actual behavior

Hello, I updated to the latest version, and prompted this: Error: Setting up fake worker failed: "Cannot load script at: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf. worker.min.js", the previous version is working normally. May I ask what's going on? 

### Additional information

Hello, I updated to the latest version, and prompted this: Error: Setting up fake worker failed: "Cannot load script at: https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf. worker.min.js", the previous version is working normally. May I ask what's going on? 

### Environment

```markdown
- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:
```

**Comment by wojtekmaj** [comment]
https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf. worker.min.js is not a valid URL. https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.10.377/pdf.worker.min.js is.
