### ISSUE TITLE
Webpack version inconsistency after `npm update`

### ISSUE THREAD

**Issue by fkocovski** [wojtekmaj/react-pdf#911]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Whenever I run an `npm update` command to update other packages and after that I try an `npm run start` or `npm run build` I get following error message:

![Screenshot 2021-12-20 at 09 28 41](https://user-images.githubusercontent.com/9000611/146737015-8583856d-b647-4543-a497-5162b6d1abde.png)

The only way I currently found to fix this is to manually remove the `node_modules` folder and delete the `package-lock.json` file, uninstall `react-pdf`, run a clean `npm install` and only afterwards run once more `npm i react-pdf`. How can I fix this?

### Steps to reproduce

1. Install latest version
2. Downgrade another package
3. Run `npm update`
4. Run `npm run start` or `npm run build`

### Expected behavior

Should not have webpack inconsistency

### Actual behavior

![Screenshot 2021-12-20 at 09 28 41](https://user-images.githubusercontent.com/9000611/146737276-eda0b6e6-37dc-4adc-8f69-f556d4681fbb.png)

### Environment

```markdown
- **Browser (if applicable)**: Version 98.0.4758.9 (Official Build) dev (arm64)
- **React-PDF version**: 5.6.0
- **React version**: 17.0.1
- **Webpack version (if applicable)**:
```

**Comment by wojtekmaj** [comment]
No idea what your npm is doing, but `react-pdf` does not depend on `webpack`. It does, however, depend on `file-loader`, so you might be a victim of idiotic npm 7 behavior where peerDependencies are automatically installed.

**Comment by fkocovski** [comment]
Ok thanks for the info. Would you perhaps have an idea into which direction to point me to solve my issue perhaps? Many thanks

**Comment by rpaasche** [comment]
`file-loader` should be a devDependency in project.json instead an dependency. This causes problems with `create-react-app` >= 5.0.0 too.

**Comment by wojtekmaj** [comment]
`file-loader` is not really a `devDependency`. It has to install with React-PDF for Webpack 4 entry file to work. However, it has no use in Webpack 5 entry file, Parcel entry file, generic entry file... Perhaps dropping support for Webpack 4 altogether would be a better choice.

**Comment by wojtekmaj** [comment]
Agreed! Let's do this.

**Comment by yuliya-ivaniukovich** [comment]
Note that peerDependencies are now installed by default in npm7+, so probably we also should mark the dependency as optional: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta

**Comment by Snipx** [comment]
Would love to see this fixed!

**Comment by rpaasche** [comment]
@wojtekmaj I've added the otional flag to the PR

**Comment by rpaasche** [comment]
Any change to get a relase?

**Comment by rpaasche** [comment]
Ahh I see it is in [v6.0.0-beta.3](https://github.com/wojtekmaj/react-pdf/releases/tag/v6.0.0-beta.3), thanks.

**Comment by martinbroos** [comment]
I'm using webpack 5 with react-pdf 6.1.1 but the build breaks because I don't have file-loader installed. For all other assets I use the new asset loader from webpack. Is it  still required for webpack 5 to install file-loader when using react-pdf or it this a bug ?

**Comment by martinbroos** [comment]
Ah i see I was using `entry.webpack` instead of `entry.webpack5` . Thanks all working now :)
