### ISSUE TITLE
some Page content is empty

### ISSUE THREAD

**Issue by joker585** [wojtekmaj/react-pdf#913]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

some page components will render empty content when i repeat render it, like this: 
```
props => {
 const [ total, setTotal] = useState(0)
return (
 <Document onLoadSuccess={({numPages}) => setTotal(numPages)}>
   { new Array(numPages).fill('').map((i, index) => <Page pageNumber={index+1}  />}
   { new Array(numPages).fill('').map((i, index) => <Page pageNumber={index+1}  />}
 </Document>)
}
```

### Steps to reproduce

repeat render same index Page will reproduce

### Expected behavior

will render all page correctly, not some empty page

### Actual behavior

will render some empty page

### Additional information

![image](https://user-images.githubusercontent.com/30993639/147082981-eeca472a-a179-4501-9159-10d887c2260b.png)

canvas is rendered, but no content

### Environment

```markdown
- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:
```

**Comment by wojtekmaj** [comment]
I couldn't reproduce this using CodeSandbox. Can you please provide more context?

https://codesandbox.io/s/react-pdf-double-render-o22i0
