### ISSUE TITLE
The Pdf viewer is not loading pdf file while it was working well yesterday

### ISSUE THREAD

**Issue by Jvst1n** [wojtekmaj/react-pdf#922]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The Pdf viewer is not loading pdf file while it was working well yesterday

### Steps to reproduce

I want to load an a pdf file

### Expected behavior

The pdf content will be loaded

### Actual behavior

Failed to load PDF file

### Additional information

I got the error: 
![image](https://user-images.githubusercontent.com/20912135/149322175-efc6b1e7-ea5a-44b2-9056-321b0d02fee0.png)

I changed the worker version to 2.10.377, but the issues hasn't changed. I only got this problem today; everything was still working well yesterday. Any helps are much appreciated. 

### Environment

- **Browser (if applicable)**: All of browser
- **React-PDF version**: 5.6.0
- **React version**: 17.0.0
- **Webpack version (if applicable)**: 4.44.2

**Comment by Jvst1n** [comment]
I figured out how to fix it. Thank you.

**Comment by BDimaurizio** [comment]
How did you fix it?

**Comment by wojtekmaj** [comment]
* Dedupe your dependencies. '@types/react-pdf` is known to install newer react-pdf versions than supported by React-PDF.
* Check if you use pdfjs.version variable in your custom-defined pdfjs.workerUrl, as older docs suggested hardcoded versions, not dynamic, and PDF.js may be updated in React-PDF at any time.

**Comment by FrankJingZhi** [comment]
我也遇到了同样的问题，最终我修复了它。
原因是我的项目中使用了多个pdf插件，他们之间的版本不兼容导致，我把多余的删掉，只保留一个后，问题就修复了。
所以，请检查你的项目中是否有多个pdf插件

**Comment by Priyanka541-cell** [comment]
It means we have to use hardcoded versions only or is it fixed in latest versions?

**Comment by wojtekmaj** [comment]
You must use the exact version that is specified in dependencies of react-pdf version you're using.
