### ISSUE TITLE
Outline not working/not rendering on current main branch

### ISSUE THREAD

**Issue by kaceycleveland** [wojtekmaj/react-pdf#931]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I could not seem to get `Outline` working properly on the project I was working on recently so I pulled down and realized it is not working on the test environment that is set up in this repo.

For the test repo, the `Outline` code is included however nothing is outputted by it. I did not investigate much further then this though. You can see under class `Test__container_content_toc` it is empty.

In addition, having a better idea of what I am looking for when using `Outline` would be nice. I am not sure exactly what to look for since I could not find a reference picture to see what the UI should look like. My first thought was it was hidden somewhere off screen but like I said, it looks like it does not render at all.

### Steps to reproduce

1. Checkout current code
2. Run the test code
3. Upload a document
4. See that `Test__container_content_toc` is empty in the DOM.

### Expected behavior

TOC renders on the side I assume.

### Actual behavior

TOC does not render.

### Environment

- **Browser (if applicable)**: Chrome 97.0.4692.71
- **React-PDF version**: 5.6.0
- **React version**: 17.0.0
- **Webpack version (if applicable)**: 5.20.0

**Comment by benyamynbrkyc** [comment]
I have the same problem here :(

**Comment by stgermaniac** [comment]
Same. onLoadSuccess returns null. Otherwise the page loads fine. I'm trying to use [this recipe](https://github.com/wojtekmaj/react-pdf/wiki/Recipes#display-interactive-table-of-contents).

**Comment by yumanfeng1994** [comment]
Same. onLoadSuccess returns null, <Outline /> render nothing

**Comment by Legionses** [comment]
Hi! Same problem here. Does this issue in the queue for the fix?

**Comment by Legionses** [comment]
@yumanfeng1994 Hi, how

> > Same. onLoadSuccess returns null, `<Outline />` render nothing
> 
> 已经找到问题了，pdf 文件需要设置目录，然后 Outline 就渲染出来了

Hi! You said the file  'needs to set directory', how u did this?

**Comment by wojtekmaj** [comment]
Outline works just fine in test repo: https://projects.wojtekmaj.pl/react-pdf/test/

<img width="1511" alt="obraz" src="https://user-images.githubusercontent.com/5426427/186152372-9057ae88-3209-4677-b20d-aa472e10ebd9.png">

**Comment by Legionses** [comment]
@wojtekmaj is Outline adds by default in test repo or i should turn it somewhere? Because I tested 3 pdf files and didn`t see Outline with each of them.

**Comment by wojtekmaj** [comment]
You add Outline manually just like you add Page components manually.

**Comment by croraf** [comment]
@wojtekmaj This should be reopened as Outline is still not rendering anything in the DOM.
react-pdf version: 7.5.1
