### ISSUE TITLE
does not render in cypress tests

### ISSUE THREAD

**Issue by linojon** [wojtekmaj/react-pdf#939]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Works fine in browser except when run in a Cypress integration test. Generates the canvas and "renders" without errors but the canvas pixels are blank (white).

### Steps to reproduce

I've created a simple Next.js project and pdf_spec.js to demostrate the project.

1. Clone https://github.com/linojon/pdf-to-png
2. $ yarn install
3. $ yarn dev
4. browse to localhost:3000, click "Upload PDF", see it render on canvas.
5. Click "download file", saved png file is good.
5. $ yarn cypress run
6. tests "pass" but nothing is rendered. 
7. manually examine browser page and downloaded file (cypress/downloads/)

### Expected behavior

pdf should be rendered on canvas during tests

### Actual behavior

canvas pixels are all white

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 4.1.0
- **React version**: 17.0.2
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Hmmm, not sure what's going on, but I can see that when Cypress runs the app, pdf.js throws some warnings it doesn't throw on Chrome:

```
pdf.worker.min.js:22 Warning: Indexing all PDF objects
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 127
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 113
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 239
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 191
pdf.worker.min.js:22 Warning: getHexString - ignoring invalid character: 189
pdf.worker.min.js:22 Warning: getHexString - ignoring additional invalid characters.
```

**Comment by wojtekmaj** [comment]
Hah! Noticed that when I use `yarn cypress run --headed --no-exit` and interact with the page by myself, uploading the file manually in Test Runner, the file loads correctly. I guess it's something about this Cypress' upload method. You'll have to drive it from there :)
