### ISSUE TITLE
PDF will not rendered 

### ISSUE THREAD

**Issue by dsevenx** [wojtekmaj/react-pdf#940]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

My Code is
import { Document, Page, pdfjs } from "react-pdf";

pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

    <Modal.Body>
              <Container>
                <Document
                  file={{
                    url: "http://localhost:8080/api/v1/krisch/exportpdf",
                  }}
                  onLoadSuccess={this.onDocumentLoadSuccess}
                  onLoadError={(error) => console.log("Inside Error", error)}
                />
              </Container>
            </Modal.Body>

in Network everything fine, when I take the url and paste in Chrome or Firefox the pdf is available. 
The onLoadSuccess says the right amount of pages - but non visible.

### Steps to reproduce

I have only my code - i can demo it in a webex ...

### Expected behavior

that the pdf will rendered

### Actual behavior

empty space

### Additional information

?

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
You render document with zero pages inside - check the docs.

**Comment by dsevenx** [comment]
I read your doc - there is no hint of that behavior.

Now we use this :   window.open(pDokumentIDURL, "_blank");  and it is like 
 <a href={pDokumentIDURL}>
... this versions works always. What does the browser know more ?

**Comment by dsevenx** [comment]
ups - I wanted  a href={pDokumentIDURL}

**Comment by dsevenx** [comment]
> You render document with zero pages inside - check the docs.

- I know you have not so much time, but if our custoumer insist on the preview feature inside our application, can we hire you, to solve the problem. How much would it cost ?
