### ISSUE TITLE
react-pdf set pages Support scroll bar Rendering too slow

### ISSUE THREAD

**Issue by gitCMm** [wojtekmaj/react-pdf#943]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

The PDF document has 39 pages，Pdf document content rendering is too slow ，Cause page jam，
Can I listen to the scroll bar to load only the current few pages？There are no examples in the document. Is this function supported

**Comment by wojtekmaj** [comment]
Duplicate of #94 

Question raised as an issue, closing
