### ISSUE TITLE
Incomplete instruction on how to install in REACT CRA 5.0.0  for react-pdf 5.7.0 

### ISSUE THREAD

**Issue by spine001** [wojtekmaj/react-pdf#948]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

The instructions in the readme say: "[Standard instructions](https://github.com/wojtekmaj/react-pdf#standard-browserify-esbuild-and-others) will also work with Create React App. Please note that in CRA, you can copy pdf.worker.js file from pdfjs-dist/legacy/build to public directory in order for it to be copied to your project's output folder at build time."

They should say: "[Standard instructions](https://github.com/wojtekmaj/react-pdf#standard-browserify-esbuild-and-others) will also work with Create React App. Please note that in CRA, you can copy pdf.worker.js and pdf.worker.js.map files from pdfjs-dist/legacy/build to public directory in order for it to be copied to your project's output folder at build time.

### Steps to reproduce

Just follow the original instructions in the readme file regarding copying only the pdf.worker.js files to the public directory and eventhough the program will work, you will get an error reporting the it failed to open the pdf.worker.js.map file because of an incorret format (using inspect and looking at the console output). Follow the modified instructions and the error will go away.

### Expected behavior

No errors

### Actual behavior

Indicates that the pdf.worker.js.map file has an incorrect format and throws an error. Doesn't crash.

### Environment

Chrome Version 98.0.4758.80 (Official Build) (64-bit)
React-PDF version 5.7.0
React version 17.0.2
Create React App 5.0.0 (uses Webpack 5.0)

**Comment by arpitprod** [comment]
I am getting `Uncaught SyntaxError: Unexpected token '<'` error with cra v5 and I am following this [sample](https://github.com/wojtekmaj/react-pdf/tree/main/sample/create-react-app-5) code. Working fine in sample code but not working in my project.

**Comment by flacoman91** [comment]
I also encountered some issues with the sample when running yarn start in the sample folder.  Hopefully these steps helps someone else trying to get it up and running. 

I had to manually go into node_modules/pdfjs-dist/legacy and manually copy the pdf.worker.js file into create-react-app-5/public.  I did not need the map file copied there for it to work.

Another issue I got was regarding eslintrc.json:
`Failed to load config "wojtekmaj/react-no-automatic-runtime" to extend from.`  but i had to run yarn build from the root level of react-pdf first, and then run the `yarn install; yarn start` commands inside of the create-react-app-5 folder.

**Comment by spine001** [comment]
See https://stackoverflow.com/a/71105725/15355839

**Comment by spine001** [comment]
https://stackoverflow.com/a/71105725/15355839

**Comment by wojtekmaj** [comment]
Instructions were improved and checked by building real-life example that lives in the repo in sample directory now.

**Comment by spine001** [comment]
Thanks, I'll check it out.
