### ISSUE TITLE
[CRA5] pdf.worker.js not loading on double route links like `/pdf/two`

### ISSUE THREAD

**Issue by arpitprod** [wojtekmaj/react-pdf#949]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

pdf.worker.js not loading on double route links like `/pdf/two` and getting `Uncaught SyntaxError: Unexpected token '<'` error and working perfect on route link `/pdf`. This is my [sample](https://github.com/arpitprod/react-pdf-cra5) code. 

### Steps to reproduce

clone [this](https://github.com/arpitprod/react-pdf-cra5) code
open `http://localhost:3000/pdf/two` and showing `Failed to load PDF file.`
open `http://localhost:3000/pdf` and it's working fine

### Expected behavior

should load fine on `/pdf/two` and/or `/file/pdf/two` links etc

### Actual behavior

should load fine on `/pdf/two` and/or `/file/pdf/two` links etc

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by arpitprod** [comment]
working fine if we add this

```
import { pdfjs } from 'react-pdf';
pdfjs.GlobalWorkerOptions.workerSrc = '/pdf.worker.js';
```

**Comment by Gresliebear** [comment]
I have a similar issue this fix doesn't work 
```

import React from 'react';
import Navbar from '../components/Navbar';
import { Document } from 'react-pdf'
import PathToPDF  from "E:/BlogWebsite/lesblog/src/PDFs/Resume_Sept_V6_2021.pdf"
import { pdfjs } from 'react-pdf';


const Resume = () => {

    pdfjs.GlobalWorkerOptions.workerSrc = '/pdf.worker.js';
return <div>

        <Navbar/>
        <div className='flex flex-col'> 
            <h1 className='text-white text-8xl p-8'> Resume </h1>
            <div className='text-white text-8xl p-8'> Resume goes heres</div>
            
            <div className='text-white text-8xl p-8'> List of projects</div>
            {/* list of projects */}
                
                <Document file={PathToPDF}> </Document>
                
                <ul className='list-disc'> 

                    <li className='text-white text-4xl p-4'> OpenVessel start up - for 2020 - 2021</li>
                    <li className='text-white text-4xl p-4'> OpenVessel start up - for 2020 - 2021</li>
                    <li className='text-white text-4xl p-4'> OpenVessel start up - for 2020 - 2021</li>
                
```

**Comment by wojtekmaj** [comment]
For anyone having trouble with configuring workerSrc, I recommend reading:
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#absolute_urls_vs_relative_urls

In CRA5, please also ensure that you're copying `pdf.worker.js` to your `public` folder as instructed in README so that it's possible for PDF.js to request it.
