### ISSUE TITLE
Cannot load pdf with URL.createObjectURL() and https

### ISSUE THREAD

**Issue by kidqn** [wojtekmaj/react-pdf#952]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I use URL.createObjectURL() to create url for blob files.
My pdfDetail = {url: blob:pdfurl};

`<Document file={pdfDetail}  onLoadSuccess={onDocumentLoadSuccess}>
    <Page pageNumber={pageNumber} scale={1.2}/>
</Document>`

This is working on localhost with http. But when I deploy in production, it shows me cannot load PDF detail despite I can view file with that url.

### Steps to reproduce

1. create url for blob file by using URL.createObjectURL() 
2. pass url to <Document />

### Expected behavior

Be able to load PDF file by `blob:https://pdfurl`

### Actual behavior

Show error cannot load PDF detail

### Environment

Browser (if applicable): Chrome 96, Firefox 94
React-PDF version: 5.5.0
React version: 17.0.0
Webpack version (if applicable): 5.50.0

**Comment by mikejar** [comment]
I do not have this problem. I am able to pass an objectURL as created by window.URL.createObjectURL(blob) straight into react-pdf Document component as the file parameter; however, I'm not passing an object as you are:
```
const objectUrl = window.URL.createObjectURL(blob);
...
return <Document file={objectUrl} >...</Document>
...
```
