### ISSUE TITLE
Font render is incorrect

### ISSUE THREAD

**Issue by thanhchuongbmd** [wojtekmaj/react-pdf#953]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I have a pdf file using font UTF-8 (Vietnamese), but not render is in correct on web view android

### Steps to reproduce

Show on chrome then it's ok, but on web view android (version 8.1.0)  is not correct 
Link pdf: https://214portal.bmdapp.store:4214/book/e40047ed2c20f7b52db8447936cbbfdc.pdf

![image_2022-02-16_16-26-02](https://user-images.githubusercontent.com/67777599/154239821-5485983e-3273-464a-ad03-c9fc4e3e8ecf.png)

### Expected behavior

Show correct the font

### Actual behavior

Show correct the font

### Environment

- **Browser (if applicable)**: Web view android (8.1.0)
- **React-PDF version**: 5.6.0
- **React version**: 17.0
- **Webpack version (if applicable)**: 5.0

**Comment by wojtekmaj** [comment]
Does PDF.js demo look good on WebView Android 8.1?

This might be a very old version of Chrome underneath...

**Comment by thanhchuongbmd** [comment]
> Does PDF.js demo look good on WebView Android 8.1?
> 
> This might be a very old version of Chrome underneath...

The version chrome is 63. May be it's work on from ver 71
