### ISSUE TITLE
Blurry PDF uploads

### ISSUE THREAD

**Issue by elchaparrito1** [wojtekmaj/react-pdf#958]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I have an issue where there seems to be a decent level of px degradation when a pdf is uploaded to company AWS S3, and a customer goes to view it on company's platform. It isn't way noticeable, unless the PDF image is already of lower quality. Example of section of PDF prior to upload (is from customer invoice so don't want to show whole PDF):

<img width="220" alt="Screen Shot 2022-02-28 at 12 45 53 PM" src="https://user-images.githubusercontent.com/38321899/156051352-c756f385-a4f8-450c-8300-a846b60f8e95.png">

And what is looks like after upload, and is clicked for viewing:

<img width="212" alt="Screen Shot 2022-02-28 at 12 45 43 PM" src="https://user-images.githubusercontent.com/38321899/156051457-ffb1bcde-7457-4306-aa50-6325dcaf91af.png">

We were using version 5.1.0 and upgraded to 5.7.1 and this did not help the quality. 

### Steps to reproduce

Use PDF.js Demo locally to test quality of PDF for viewing online.

### Expected behavior

Expected behavior is for pdf image to at least have the same px quality as before.

### Actual behavior

Appears to be some degradation after PDF is ran though API services for upload.

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by jdc-cunningham** [comment]
A bit late bit commenting for ideas

I'm assuming you checked that after uploading your PDF/viewing it whether by public/direct S3 url or downloading from S3 and opening in a browser it's not blurry there?

If it looks good above then I would check the scale of the rendered react-pdf size (checking if modifying it improves quality (width/height or scale values)).

From my experience our PDFs were getting blurry because I was taking DOM screenshots/uploading that vs. using the original pdf/stacking changes on top of it using pdfkit on the backend.

**Comment by otnansirk** [comment]
Sorry A bit late. is this solved? 
But it's okey, I hope this helps the next reader.

have you tried add scale props to Page component. If not.
To overcome blurry you can add props `scale={5}`.  you can try replace 5 to 1,2,3, or you can try another number.

It's works for me.

**Comment by wojtekmaj** [comment]
Scale should be automatically multiplied by [devicePixelRatio](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio) so that shouldn't be the problem. At least on all my test devices PDFs are rendering super sharp.

**Comment by elchaparrito1** [comment]
Sorry. Coming back late to this. I will try the scale prop and see if that offers any improvements.

**Comment by georgiossalon** [comment]
> ,2,3, or you can try another num

So multiply what with `window.devicePixelRatio`?

Example:
<Document scale={window.devicePixelRatio*}/>

**Comment by tsaxena4k** [comment]
Did anyone found the solution here ?

**Comment by wojtekmaj** [comment]
Scale is automatically multipled by devicePixelRatio so that shouldn't be a problem for a long time now. If it is, I'm gonna need a repro.

**Comment by VikasPathaniaa** [comment]
have you tried add scale props to Page component. If not.
To overcome blurry you can add props scale={5}. you can try replace 5 to 1,2,3, or you can try another number.
scale={5}
It's works for me.

**Comment by Anhaachan** [comment]
Why this issues added `closed`?

**Comment by biennui1998mu** [comment]
> have you tried add scale props to Page component. If not. To overcome blurry you can add props scale={5}. you can try replace 5 to 1,2,3, or you can try another number. scale={5} It's works for me.

I was used scale={5} and other number but still not working. Any solution?

**Comment by bee-eater** [comment]
Also have this issue, using scale makes it better. I just use 1.5 right now... 
Not sure where it's coming from, but my structure is something like below. If I e.g. add a border it gets kinda blurry. But if I add the scaling as suggested above it gets a lot better! Thanks @otnansirk!


```jsx
<...>
    <Paper 50% with flex and stuff...>
        ...
    </Paper> 
    <Paper 50% with flex and stuff...>
        <>
            <Alert... >
                 ...
            </Alert>
            <Box ref={containerRef} id={'doc-pdf-container'}>
                <Document file={file} onLoadSuccess={onDocumentLoadSuccess}>
                  {Array.from(new Array(numPages), (el, index) => (
                    <Page scale={window.devicePixelRatio * 1.5} width={width} key={`page_${index + 1}`} pageNumber={index + 1} />
                  ))}
                </Document>
            </Box>
        </>
    </Paper>
</...>
```

with some css like this:

```css
.react-pdf__Page__canvas {
  width: 100% !important;
  height: auto !important;
  /* outline: #999999 1px solid; */
  border: #999999 5px solid;
}

#doc-pdf-container{
  overflow-y: scroll;
  overflow-x: hidden;
  /* outline:#424242 5px solid; */
}
```
