### ISSUE TITLE
Sample cannot be used with files from ./src directory

### ISSUE THREAD

**Issue by apla** [wojtekmaj/react-pdf#96]
This is actually the webpack excludes problem. I've changed relative path to the `react-pdf` in

```
import { Document, Page } from '../src/entry.webpack.js';
```

and cannot build js bundle anymore. I'm not familiar with webpack and spend few hours to figure out why it is not working. Error looks like this:

```
ERROR in ./node_modules/react-pdf/src/Page.jsx
Module parse failed: Unexpected token (19:8)
You may need an appropriate loader to handle this file type.
| 
| export default class Page extends Component {
|   state = {
|     page: null,
|   }
 @ ./node_modules/react-pdf/src/entry.webpack.js 3:0-26
 @ ./extraction.jsx
 @ ./extraction.sample.jsx
 @ multi ./extraction.sample.jsx
```

As a fix I propose to replace exclude in rule with

```
exclude: /node_modules\/(?!(react-pdf)\/).*/,
```

or leave the comment in webpack config about sample and excludes.

**Comment by wojtekmaj** [comment]
Nice catch. I believe getting entry file from ./build instead of ./src would have fixed this issue as well. And actually, this is how I recommend using React-PDF in README ;)
