### ISSUE TITLE
 Failed to load PDF file

### ISSUE THREAD

**Issue by sarwaras** [wojtekmaj/react-pdf#971]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

My goal:

Click the view button to preview the uploaded PDF file

Problems:

Failed to load PDF file is displayed after uploading

Result: the corresponding file cannot be previewed

Ask the big guys to help see what the problem is? Or if someone has encountered such problems, please help me to give instructions

thank you!

### Steps to reproduce

Upload PDF file, click the view button to display failed to load PDF file

### Expected behavior

Click the view button to preview the uploaded PDF file

### Actual behavior

Failed to load PDF file is displayed after uploading

### Additional information

I hope to get your help

### Environment

浏览器（如果适用）：Chrome 
React-PDF 版本：5.7.0
反应版本：17.0.0
Webpack 版本（如果适用）：5.70.0

**Comment by sarwaras** [comment]
Browser (if applicable): Chrome

React PDF version: 5.7.0

Reaction version: 17.0.0

Webpack Version (if applicable): 5.70.0

**Comment by intchensc** [comment]
I have the same problem :(

**Comment by sarwaras** [comment]
> 

It could be a network problem，My can sometimes load files, but sometimes not

**Comment by paul-altyfc** [comment]
I have the same problem I recently updated to the latest release my code works fine when using v5.3.2 but any version afterwards it fails.

**Comment by Boniich** [comment]
Hi

i had the same problem and fixed it in this way.

-first, i used the version that @paul-altyfc said. `5.3.2` (i was just testing it as a solution, maybe work with another version)
-second, i used this import 'react-pdf/dist/esm/entry.webpack';
-third, i save my pdf in one var and set this var in my document component

`import pdf from './somefile.pdf';`
`
<Document file={pdf}>
<Page pageNumber={1} />
</Document>`

i hope this help you guys.

**Comment by hamaarouf** [comment]
@Boniich I tried your suggested solution I'm not getting that error but, the pdf is not readable actually I'm getting the the content  and background in white color! please am I missing something?

**Comment by RishiMalhotra920** [comment]
I found that the second step i.e. importing webpack was enough!

**Comment by sarwaras** [comment]
thanks ,it is very helpfor for me



---Original---
From: "Danny ***@***.***&gt;
Date: Wed, Jun 15, 2022 20:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wojtekmaj/react-pdf]  Failed to load PDF file (Issue #971)




 
I had same issue when try it in my project, And I found a simple solution, just pass an object to the file prop inside the Document component:
 <Document     file={{       url:         'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',     }}     onLoadSuccess={onDocumentLoadSuccess} &gt;

**Comment by AmanTheGreatCoder** [comment]
@Boniich Importing Webpack Worked for me.Thank you!
