### ISSUE TITLE
react-pdf shows blank pages with React 18 in StrictMode

### ISSUE THREAD

**Issue by nickchauhan** [wojtekmaj/react-pdf#972]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

React 18 was released recently and I tried to upgrade my codebase to the latest version.

I have a PDF presentation slider page on my website which is working fine with react v17 but as soon I updated the codebase to react v18, PDF pages are appearing blank and there is no error.

I have created 2 sandboxes with the same code only difference is the react version changes and react v18 configuration on the index.tsx file

1. with react v17 - no issues - https://codesandbox.io/s/agitated-fog-emzy5t?file=/src/index.tsx
2. with react v18 - showing blank pages - https://codesandbox.io/s/fervent-microservice-cxtu30?file=/src/index.tsx

### Steps to reproduce

I have provided the sandbox URL for the demo and testing.

### Expected behavior

It should work as before.

### Environment

- **Browser (if applicable)**: Chrome
- **React-PDF version**: v5.7.1
- **React version**: v18
- **Webpack version (if applicable)**: v5

**Comment by nickchauhan** [comment]
When I changed the renderMode='svg' it worked fine. But the default renderMode='canvas' is not rendering correctly.

**Comment by wojtekmaj** [comment]
StrictMode is to blame here. If you remove it, it all works as it's supposed to.

**Comment by wojtekmaj** [comment]
Fixed in v5.7.2. Thanks!

**Comment by JasonLovesDoggo** [comment]
> Fixed in v5.7.2. Thanks!

I have the same issue in react-pdf 9.1.1 on react 19 & Next Js 15.

Turning strict mode off fixes it
