### ISSUE TITLE
"Highlight text on the page" is not working 

### ISSUE THREAD

**Issue by pathum-kalhan** [wojtekmaj/react-pdf#973]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

```
import React, { useMemo, useState } from 'react';
// import { Document, Page } from 'react-pdf';
import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';

import samplePDF from './test.pdf';

// https://gist.github.com/wojtekmaj/f265f55e89ccb4ce70fbd2f8c7b1d95d
function highlightPattern(text, pattern) {
  const splitText = text.split(pattern);

  if (splitText.length <= 1) {
    return text;
  }

  const matches = text.match(pattern);

  return splitText.reduce((arr, element, index) => (matches[index] ? [
    ...arr,
    element,
    <mark key={index}>
      {matches[index]}
    </mark>,
  ] : [...arr, element]), []);
}

export default function Test() {
  const [searchText, setSearchText] = useState('');

  // const textRenderer = useMemo((textItem) => {
  //   return highlightPattern(textItem.str, searchText);
  // }, [searchText]);

  function onChange(event) {
    setSearchText(event.target.value);
  }

  return (
    <>
      <Document
        file={samplePDF}
        // onLoadSuccess={onDocumentLoadSuccess}
      >
        <Page
          pageNumber={1}
          // customTextRenderer={textRenderer}
        />
      </Document>
      <div>
        <label htmlFor="search">Search:</label>
        <input type="search" id="search" value={searchText} onChange={onChange} />
      </div>
    </>
  );
}
```

I have this code copied from recipe https://github.com/wojtekmaj/react-pdf/wiki/Recipes#highlight-text-on-the-page.
Since I have `react-scripts-4` I added this line` import { Document, Page } from 'react-pdf/dist/esm/entry.webpack';` 

This is now working. This shows the PDF file. But when I uncomment the `textRenderer` function, everything breaks with the error
`TypeError: Cannot read properties of undefined (reading 'str')`

How do we fix this?

### Steps to reproduce

https://github.com/wojtekmaj/react-pdf/wiki/Recipes#highlight-text-on-the-page.

### Expected behavior

Should be able to search and highlight text

### Actual behavior

Page crashed

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: 5.7.2
- **React version**: 17.0.2
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
Yeah sorry about that - I should have used useCallback, not useMemo here. Fixed wiki.
