### ISSUE TITLE
some special texts can't be matched when I use Page.customTextRenderer try to match and highlight that user inputed keyword

### ISSUE THREAD

**Issue by XingToYang** [wojtekmaj/react-pdf#975]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [ ] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

![image](https://user-images.githubusercontent.com/9374545/161227541-48c96418-34f2-4405-b7ef-76a67da66a0a.png)
This is displayed in Chrome

![image](https://user-images.githubusercontent.com/9374545/161227730-02851cfe-c368-4b0f-ba12-ac549706c401.png)
This is displayed by react-pdf

This is part of codes:
```js
{selFile && !!selFile.isPdf && (
              <Document
                file={selFile.attachment_path}
                options={options}
                onLoadSuccess={onDocumentLoadSuccess}
                onPassword={onDocumentPassword}
                loading={<Spin size="large" />}
              >
                <div
                  className={cs('content', 'pdf', {
                    'zoom-in': canZoomByGesture && scale < maxScale,
                    'zoom-out': canZoomByGesture && scale >= maxScale
                  })}
                  onWheelCapture={canZoomByGesture ? onWheelCapture : undefined}
                  style={childStyle}
                >
                  <div className='insideImgWr'>
                    <Page
                      pageNumber={page}
                      scale={scale + 0.4}
                      loading={<Spin size="large" />}
                      canvasRef={canvasRef}
                      customTextRenderer={customTextRenderer}
                    />
                    <WaterMarkConsumer>
                      <div className='insideWatermark' />
                    </WaterMarkConsumer>
                  </div>
                </div>
              </Document>
            )}


  const customTextRenderer = useCallback((textItem) => {
    if (!textItem) return null;
    return highlightPattern(textItem.str, resultsList && resultsList.length ? searchString || '' : '');
  }, [resultsList, searchString]);



function highlightPattern(text: string, pattern: string) {
  const splitText = text.split(pattern);

  console.log('xxx highlightPattern: ', text);
  

  if (splitText.length <= 1) {
    return text;
  }

  const matches = text.match(pattern);

  return splitText.reduce(
    (arr, element, index) =>
      // @ts-ignore
      matches[index]
        ? [...arr, element, <mark key={index} className='gallery-hightlight'>{matches[index]}</mark>]
        : [...arr, element],
    []
  );
}
```

### Steps to reproduce

compare between Chrome PDF viewer and react-pdf of displaying a Chinese PDF.
One row content has part missing disaplayed, but it is displayed correctly at Chrome PDF viewer.

### Expected behavior

displayed correctly

### Actual behavior

missing displayed

### Environment

- **Browser (if applicable)**:Chrome
- **React-PDF version**:5.6.0
- **React version**:17.0.2
- **Webpack version (if applicable)**:5.65.0

**Comment by wojtekmaj** [comment]
Do you have cMaps configured?

**Comment by XingToYang** [comment]
const options = {
  cMapUrl: 'cmaps/',
  cMapPacked: true,
  standardFontDataUrl: 'standard_fonts/'
};

![image](https://user-images.githubusercontent.com/9374545/161238537-85b4a9e7-87e2-4f02-9a64-43fd0f66b57a.png)

I've cMaps configured and when I unset pdfjs.GlobalWorkerOptions.workerSrc, the not-displayed texts now is displayed

**Comment by XingToYang** [comment]
![image](https://user-images.githubusercontent.com/9374545/161239034-95ca8a0a-d63c-4829-8933-498e09d0c209.png)
Now it's displayed correctly.But here's another problem

**Comment by XingToYang** [comment]
const [pages, setPages] = useState<string[]>([]);

**Comment by XingToYang** [comment]
const [pages, setPages] = useState<string[]>([]);
useEffect(() => {
      if (!selFile?.attachment_path) {
          setPages([]);
          return;
      }
      pdfjs.getDocument(selFile?.attachment_path).promise.then((docData) => {
          const pageCount = docData._pdfInfo.numPages;

          const pagePromises = Array.from(
              { length: pageCount },
              (_, pageNumber) => {
                  return docData.getPage(pageNumber + 1).then((pageData) => {
                      return pageData.getTextContent().then((textContent) => {
                          return textContent.items.map(({ str }) => str).join(" ");
                      });
                  });
              }
          );

          return Promise.all(pagePromises).then((pages) => {
              setPages(pages);
          });
      });
  }, [selFile?.attachment_path]);

**Comment by XingToYang** [comment]
this is log of pages
![image](https://user-images.githubusercontent.com/9374545/161239541-6e5d9d7e-c04b-4f74-b70b-ed6ef96df6a9.png)
That special texts should be logged here, but it didn't. So in my Page.customTextRenderer function, I cannot match it and highlight it where I use it for searching

function highlightPattern(text: string, pattern: string) {
  const splitText = text.split(pattern);  

  if (splitText.length <= 1) {
    return text;
  }

  const matches = text.match(pattern);

  return splitText.reduce(
    (arr, element, index) =>
      // @ts-ignore
      matches[index]
        ? [...arr, element, <mark key={index} className='gallery-hightlight'>{matches[index]}</mark>]
        : [...arr, element],
    []
  );
}


const customTextRenderer = useCallback((textItem) => {
    if (!textItem) return null;
    return highlightPattern(textItem.str, resultsList && resultsList.length ? searchString || '' : '');
  }, [resultsList, searchString]);



<Page
                      pageNumber={page}
                      scale={scale + 0.4}
                      loading={<Spin size="large" />}
                      canvasRef={canvasRef}
                      customTextRenderer={customTextRenderer}
                    />

**Comment by XingToYang** [comment]
![image](https://user-images.githubusercontent.com/9374545/161240696-9e21b912-163f-47cd-b276-ae8f22328fe4.png)
1.search by this keyword ant higtlight keyword worked


![image](https://user-images.githubusercontent.com/9374545/161240981-648c0faa-b113-4e58-bea9-b8e6286ec433.png)
2.search by this keyword ant higtlight keyword not worked


Is special texts' font family missed?

**Comment by wojtekmaj** [comment]
What if you use old school Ctrl+F for searching? Is the text rendered, and consequently found, correctly?

If so, maybe the text is split into several chunks and can't be matched as a whole.

**Comment by XingToYang** [comment]
![image](https://user-images.githubusercontent.com/9374545/162201091-7d29e968-52de-46f9-bc74-5c0f641bb9be.png)
searching worked correctly in Chrom PDF viewer
