### ISSUE TITLE
VIctory charts or Recharts with React PDF

### ISSUE THREAD

**Issue by KhanimambaMasuka** [wojtekmaj/react-pdf#978]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

I'd like to have victory charts or recharts integration with react pdf to be simplified

**Comment by wojtekmaj** [comment]
I don't see how React-PDF could be "integrated" with recharts at all.

**Comment by KhanimambaMasuka** [comment]
Are there any suggestions as to how I can add a chart to react pdf?

**Comment by KhanimambaMasuka** [comment]
I tried a few suggestions on different forums with no luck...The only thing I was able to pull off is drawing a pie chart using svg's

**Comment by KhanimambaMasuka** [comment]
but now I need to be able to add line charts to the pdf

**Comment by wojtekmaj** [comment]
It looks like you confused React-PDF with [@react-pdf/renderer](https://github.com/diegomura/react-pdf). Please file an issue in their repo instead.
