### ISSUE TITLE
Unlock `pdfjs-dist` library version

### ISSUE THREAD

**Issue by andrewmiroshnichenko** [wojtekmaj/react-pdf#982]
### Before you start - checklist

- [X] I understand that React-PDF does not aim to be a fully-fledged PDF viewer and is only a tool to make one
- [X] I have checked if this feature request is not already reported

### Description

Currently`pdfjs-dist`'s version is [locked to 2.13.313 ](https://github.com/wojtekmaj/react-pdf/blob/main/package.json#L80).
It leads to a situation, when `react-pdf` used with other pdf-themed libraries (like [react-pdf-highlighter](https://github.com/agentcooper/react-pdf-highlighter)) can produce production bundle with at least two versions of `pdfjs-dist`, which adds up ~100kb gzipped javascript.

### Proposed solution

Unlock `pdfjs-dist` dependency in package.json

**Comment by wojtekmaj** [comment]
No gonna happen. Mozilla, unfortunately, doesn't conform to semver standard, and "minor" version updates almost always include new breaking changes.

**Comment by andrewmiroshnichenko** [comment]
>You may also notice that react-pdf-highlighter also uses a locked pdfjs-dist version.
It explains a lot :)
Yeap, I saw locked version in react-pdf-highlighter, so also created similar issue there. 
Anyway, thanks for the answer!
