### ISSUE TITLE
Annotation layer links are not clickable

### ISSUE THREAD

**Issue by vkalchuk** [wojtekmaj/react-pdf#985]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

I've checked similar issues, but none of the provided solutions seem to work in this case. My assumption is that this has something to do with pdf document itself, appreciate if anyone could take a look.

### Steps to reproduce

Here is the sandbox with the example
https://codesandbox.io/s/pensive-moon-tnqr2o?file=/src/App.js

### Expected behavior

Links are clickable

### Actual behavior

Links are not clickable

### Additional information

Link to the document itself: [2022-Nissan-Pathfinder.pdf](https://github.com/wojtekmaj/react-pdf/files/8519570/2022-Nissan-Pathfinder.pdf)

Interesting fact, that google viewer does not open the links either (pages 4, 5), but if you download the document, links are working. I'm using default previewer on MacOS

### Environment

- **Browser (if applicable)**: Chrome Version 100.0.4896.127 (Official Build) (x86_64)
- **React-PDF version**: 5.7.2, same behaviour on 4.1.0
- **React version**: 18.0.0, same on 16.4.0

**Comment by wojtekmaj** [comment]
It looks like the link on page 4 is not working anywhere, but the one on page 5 is indeed clickable in most PDF readers.

**Comment by juansebastianl** [comment]
I ran into this issue and fixed it with 

`.linkAnnotation {
    position: absolute;
}

.linkAnnotation a {
    display: flex;
    width: 100%;
    height: 100%;
}`
