### ISSUE TITLE
renderMode svg element color issue

### ISSUE THREAD

**Issue by DSp4wN** [wojtekmaj/react-pdf#986]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Almost all the text content such as title and other text content in the body of the pdf page as highlighted in the inspector is transparent in the renderMode "svg" and I can't find out what's wrong here, any kind of hints/help will be appreciated.

logs in console: 

![image](https://user-images.githubusercontent.com/48817540/163604543-1ae9a851-9a1d-413a-8aa1-4f341a582fe8.png)

### Steps to reproduce

N/A

### Expected behavior

Real pdf page part:
![image](https://user-images.githubusercontent.com/48817540/163603671-996f8894-6903-4a11-932b-6cb04b75a1ee.png)

### Actual behavior

Rendered page with renderMode svg: 
![image](https://user-images.githubusercontent.com/48817540/163603416-57bc7664-e15c-404f-b938-6b52fce2c8b7.png)

### Environment

- **Browser (if applicable)**: Latest Version of Chrome
- **React-PDF version**:  5.7.2
- **React version**:  16.13.1
- **Webpack version (if applicable)**:  4.44.2

**Comment by wojtekmaj** [comment]
Unfortunately, PDF.js treats SVG render mode as experimental and doesn't accept bug reports on this matter. You may try and raise it with Mozilla (look if it hasn't been reported yet!) but I can't promise you anything.

Should Mozilla ever fix this, React-PDF will get the fix on the next pdfjs-dist version bump.
