### ISSUE TITLE
PDF is not showing content on webview react JS app

### ISSUE THREAD

**Issue by ardiansyaherwin** [wojtekmaj/react-pdf#990]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hi,

I developed a reactjs app that's displayed under react native webview, so it will work on native app as well.

in the native app, the PDF is displayed without any errors (the amount of pages generated is correct as well), but the content is not showing. (FYI, the react-pdf package is installed in react js layers not in the native, the native is used only for displaying the react js app within webview container )

it only show the svg part, event though the svg is also not rendering properly as it's showing black fill color instead of the defined color.

### Steps to reproduce

1. use the base64 url data
2. then pass the data into Document component as per documentation.
3. then view the page in ios/android app.
here's the code:
```
<Document
            className="PDFDocument"
            file={file}
            onLoadSuccess={onDocumentLoadSuccess}
            onLoadError={onDocumentLoadErr}
            loading="..."
            externalLinkTarget="_blank"
          >
            {Array.from({ length: numPages }, (_, index) => (
              <Page
                className="PDFPage PDFPageOne"
                key={`page_${index + 1}`}
                pageNumber={index + 1}
                renderAnnotationLayer={false}
                renderTextLayer={false}
              />
            ))}
          </Document>
```

### Expected behavior

the content and the svg should rendered properly

### Actual behavior

the content is missing and the svg is not using the defined fill color

### Environment

- **Browser (if applicable)**:
- **React-PDF version**: "^5.7.2"
- **React version**: "^16.14.0"
- **Webpack version (if applicable)**:

**Comment by wojtekmaj** [comment]
SVG rendering is considered experimental by Mozilla and doesn't always render correctly in most advanced cases. There's nothing we can do about it.
