### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<' in pdf.worker.js

### ISSUE THREAD

**Issue by NaveenkumarMD** [wojtekmaj/react-pdf#994]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

got an error as Failed to load pdf in the screen and the "Uncaught SyntaxError: Unexpected token '<' in pdf.worker.js" in the console.

### Steps to reproduce

* Install the package
```
            <Document 
                   file={require('../../Images/sample.pdf')}
                onLoadSuccess={onloadsuccess}
            >
                <Page pageNumber={pageNumber} />
            </Document>
```

### Expected behavior

The pdf should be visible.

### Actual behavior

The pdf is not rendered.

### Environment

- **Browser (if applicable)**:
- **React-PDF version**:
- **React version**:
- **Webpack version (if applicable)**:

**Comment by Mitri45** [comment]
You have not mentioned what environment you are using, but assuming that you are using latest CRA application, which is using Webpack 5 under the hood, try to use different import for Document and Page components from react-pdf, like this: 
`import { Document, Page } from "react-pdf/dist/esm/entry.webpack";`

Docs also provides other options of import paths, if you are using other bundler: 
Bundler | Entry file
-- | --
Parcel 1 | react-pdf/dist/esm/entry.parcel
Parcel 2 | react-pdf/dist/esm/entry.parcel2
Webpack 4 | react-pdf/dist/esm/entry.webpack
Webpack 5 | react-pdf/dist/esm/entry.webpack5

**Comment by markivancho** [comment]
I could not reproduce it on my end, but our error tracking tool caught the similar error
I've recently switched to CRA-5 with React 18 and `react-pdf/dist/esm/entry.webpack5`
![image](https://user-images.githubusercontent.com/30623974/166669597-96bd93d6-70bb-4a5e-8a63-556d16154874.png)

**Comment by spogulis** [comment]
> 

This worked but console throws a warning regarding source map:

```
DevTools failed to load source map: Could not parse content for http://127.0.0.1:8000/pdf.worker.js.map: Unexpected token < in JSON at position 0
```
