### ISSUE TITLE
Outline onItemClick only works once

### ISSUE THREAD

**Issue by Leakune** [wojtekmaj/react-pdf#997]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [x] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

Hello,
I was using your example of Display interactive Table of Contents.
The display works: it changes the page of the pdf when I click to the links.
However each link only works once, when I click the same link over 2 times it doesn't change the page.

### Steps to reproduce

1. Click on one of the link from the table of contents.
2. Click on another link.
3. Click on the first link you clicked.
4. The page doesn't change on step 3.

### Expected behavior

1. Click on one of the link from the table of contents -> should change the page
2. Click on another link -> should change to another page
3. Click on the first link you clicked -> should change back to the page like in step 1.

### Actual behavior

1. Click on one of the link from the table of contents -> change the page
2. Click on another link -> change to another page
3. **[Issue here]** Click on the first link you clicked -> the page is not changing

### Environment

- **Browser (if applicable)**: Chrome 99
- **React-PDF version**: 5.7.2
- **React version**: 18.0.0

**Comment by jholmes033169** [comment]
I am also experiencing this exact same behavior on version 5.7.2, react version 17.0.2. Same browser.

**Comment by MuthuChess** [comment]
@wojtekmaj I also experience the same issue on version 5.7.2, react version 16.8.6.
