### ISSUE TITLE
renderTextLayer break change after v5.6.0. eg, v5.7.0

### ISSUE THREAD

**Issue by yunsii** [wojtekmaj/react-pdf#998]
### Before you start - checklist

- [X] I followed instructions in documentation written for my React-PDF version
- [X] I have checked if this bug is not already reported
- [X] I have checked if an issue is not listed in [Known issues](https://github.com/wojtekmaj/react-pdf/wiki/Known-issues)
- [X] If I have a problem with PDF rendering, I checked if my PDF renders properly in [PDF.js demo](https://mozilla.github.io/pdf.js/web/viewer.html)

### Description

upgrade `pdfjs-dist@2.10.377` to `pdfjs-dist@2.12.313`, and renderTextLayer get different text str:

v5.6.0:

![image](https://user-images.githubusercontent.com/18096089/167794550-d054f7e2-5257-4370-a2fc-f491e3295732.png)

v5.7.0:

![image](https://user-images.githubusercontent.com/18096089/167794397-23c4c532-8809-4a76-93b4-cc899540f84f.png)

v5.6.0 can render space at end of text, but v5.7.0 get lost. After try to dive into pdfjs source code, I couldn't figure out what happen.

### Steps to reproduce

open: https://codesandbox.io/s/react-pdf-rendertextlayer-zhvmc2

switch react-pdf version

### Expected behavior

I want get space at end of text at present.

### Actual behavior

Space at end of text get lost.

**Comment by wojtekmaj** [comment]
Looked at PDF.js and it appears this is expected.

Please note that there has been a significant change in the way text layer is rendered in 6.0.0-beta. You might want to check it out, too.
